### ISSUE TITLE
LocaleProperty does not set its type.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#1000]
Discovered while working on `secondLocaleProperty: LocaleProperty` in https://github.com/phetsims/number-pairs/issues/22 ...

In localeProperty.ts, LocaleProperty is exported so that clients can create other instances.  But unlike other Property subclasses, LocaleProperty  does not set its `phetioValueType` or `valueType`, and leaves that to clients.   So I'm getting this error in Number Pairs:

>  Assertion failed:  PhET-iO Properties must specify a phetioValueType: numberPairs.global.model.preferences.secondLocaleProperty

The singleton `localeProperty` is instantiated like this:

```ts
const localeProperty = new LocaleProperty( phet.chipper.locale, {
  tandem: Tandem.GENERAL_MODEL.createTandem( 'localeProperty' ),
  valueType: 'string',
  phetioFeatured: true,
  phetioValueType: StringIO,
  phetioDocumentation: 'Specifies language currently displayed in the simulation'
} );
```

So this should be a matter of moving `valueType: 'string'` and `phetioValueType: StringIO` to a LocaleProperty constructor (it currently has a default a constructor) and defining `LocalePropertyOptions`. 

Discussed with @zepumph in Slack#developer, and the above sounds correct and desirable, so I'll go for it.

**Comment by pixelzoom** [comment]
> ... So this should be a matter of moving `valueType: 'string'` and `phetioValueType: StringIO` to a LocaleProperty constructor (it currently has a default a constructor) and defining `LocalePropertyOptions`. 

... which is exactly what I did in https://github.com/phetsims/joist/commit/4810d1da70e9248341eb6114164386284e50f9f8.

@zepumph would you please review? Close if OK.

**Comment by zepumph** [comment]
Perfect. Thank you for doing this.
