### ISSUE TITLE
improve the quality of navbar icons when scaling them down from home screen icons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#108]
Related to https://github.com/phetsims/ph-scale/issues/39

But some browsers (e.g., Win8 and either IE10 or Firefox) do a poor job of scaling home icons down to navbar size.  A workaround is to provide navbar-specific versions of the icons, properly sized in some external program (e.g. Photoshop, Illustrator,…) But many sims have identical home and navbar icons.  Is it possible to instruct the browser to improve the quality of scaled images?

**Comment by pixelzoom** [comment]
I'm guessing this can be closed now that we have mipmapping. @jonathanolson please confirm, and close if mipmapping addresses this issue.

**Comment by jonathanolson** [comment]
Confirmed, although it's up to each sim to do it. Closing.
