### ISSUE TITLE
Better image (and audio) URLs to prevent multiple decoding of same data

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#110]
https://github.com/phetsims/scenery/issues/126 has a note about loading data URI images into a Blob, which we can then get an image reference to. Using this image reference (or in SVG rendering, the URL itself) may significantly speed up DOM/SVG rendered image changes.

**Comment by pixelzoom** [comment]
@samreid @jonathanolson Can one of you please explain why this issue is in joist, and indicate what the current status is?

**Comment by jonathanolson** [comment]
Joist isn't the right place anyways, chipper has the image plugin that could potentially be modified.

That said, we've been doing fine with the current approach, closing.
