### ISSUE TITLE
License files for all common phetsims repos should match

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#124]
All of phetsims common code repos should have MIT licensing.  We'll use GitHub's default MIT license formatting.  I generated a sample license file using GitHub "initialize with MIT license" here:
https://github.com/samreid/testmitlicense/blob/master/LICENSE

**Comment by samreid** [comment]
I wrote a script (see commit above) that iterates over all active repos and prints the 1st line of LICENSE.  Output follows:

Repo  | 1st line of LICENSE
------------- | -------------
acid-base-solutions  |  GNU GENERAL PUBLIC LICENSE
all-sims  |  GNU GENERAL PUBLIC LICENSE
area-builder  |  GNU GENERAL PUBLIC LICENSE
arithmetic  |  GNU GENERAL PUBLIC LICENSE
assert  |  The MIT License (MIT)
atomic-interactions  |  GNU GENERAL PUBLIC LICENSE
axon  |  The MIT License (MIT)
balancing-act  |  GNU GENERAL PUBLIC LICENSE
balancing-chemical-equations  |  GNU GENERAL PUBLIC LICENSE
balloons-and-static-electricity  |  GNU GENERAL PUBLIC LICENSE
babel  | undefined
beaker  |  The 'together' project and all of the files in this repository are Copyright 2002-2015, University of Colorado Boulder.
beers-law-lab  |  GNU GENERAL PUBLIC LICENSE
bending-light  |  GNU GENERAL PUBLIC LICENSE
blackbody-spectrum  |  GNU GENERAL PUBLIC LICENSE
blast  |  GNU GENERAL PUBLIC LICENSE
brand  |  The MIT License (MIT)
build-a-molecule  |  GNU GENERAL PUBLIC LICENSE
build-an-atom  |  GNU GENERAL PUBLIC LICENSE
capacitor-lab  |  GNU GENERAL PUBLIC LICENSE
charges-and-fields  |  GNU GENERAL PUBLIC LICENSE
chains  |  GNU LESSER GENERAL PUBLIC LICENSE
chipper  |  The MIT License (MIT)
circuit-construction-kit-basics  |  GNU GENERAL PUBLIC LICENSE
color-vision  |  GNU GENERAL PUBLIC LICENSE
concentration  |  GNU GENERAL PUBLIC LICENSE
curve-fitting  |  GNU GENERAL PUBLIC LICENSE
dot  |  The MIT License (MIT)
energy-forms-and-changes  |  GNU GENERAL PUBLIC LICENSE
energy-skate-park-basics  |  GNU GENERAL PUBLIC LICENSE
estimation  |  GNU GENERAL PUBLIC LICENSE
example-sim  |  GNU GENERAL PUBLIC LICENSE
faradays-law  |  GNU GENERAL PUBLIC LICENSE
fluid-pressure-and-flow  |  GNU GENERAL PUBLIC LICENSE
forces-and-motion-basics  |  GNU GENERAL PUBLIC LICENSE
fraction-comparison  |  GNU GENERAL PUBLIC LICENSE
fraction-matcher  |  GNU GENERAL PUBLIC LICENSE
friction  |  GNU GENERAL PUBLIC LICENSE
function-builder  |  GNU GENERAL PUBLIC LICENSE
gene-expression-basics  |  GNU GENERAL PUBLIC LICENSE
graphing-lines  |  GNU GENERAL PUBLIC LICENSE
graphing-quadratics  |  GNU GENERAL PUBLIC LICENSE
gravity-and-orbits  |  GNU GENERAL PUBLIC LICENSE
gravity-force-lab  |  GNU GENERAL PUBLIC LICENSE
griddle  |  The MIT License (MIT)
hookes-law  |  GNU GENERAL PUBLIC LICENSE
isotopes-and-atomic-mass  |  GNU GENERAL PUBLIC LICENSE
john-travoltage  |  GNU GENERAL PUBLIC LICENSE
joist  |  The MIT License (MIT)
kite  |  The MIT License (MIT)
least-squares-regression  |  GNU GENERAL PUBLIC LICENSE
lingo  |  The MIT License (MIT)
making-tens  |  GNU GENERAL PUBLIC LICENSE
masses-and-springs  |  GNU GENERAL PUBLIC LICENSE
mobius  |  The MIT License (MIT)
molarity  |  GNU GENERAL PUBLIC LICENSE
molecule-polarity  |  GNU GENERAL PUBLIC LICENSE
molecule-shapes  |  GNU GENERAL PUBLIC LICENSE
molecule-shapes-basics  |  GNU GENERAL PUBLIC LICENSE
molecules-and-light  |  GNU GENERAL PUBLIC LICENSE
neuron  |  GNU GENERAL PUBLIC LICENSE
nitroglycerin  |  The MIT License (MIT)
ohms-law  |  GNU GENERAL PUBLIC LICENSE
optics-lab  |  GNU GENERAL PUBLIC LICENSE
pendulum-lab  |  GNU GENERAL PUBLIC LICENSE
ph-scale  |  GNU GENERAL PUBLIC LICENSE
ph-scale-basics  |  GNU GENERAL PUBLIC LICENSE
phet-core  |  The MIT License (MIT)
phet-info  |  The MIT License (MIT)
phet-metacog  |  The 'phetsims/metacog' project and all of the files in this repository are Copyright 2002-2015, University of Colorado Boulder.
phetcommon  |  The MIT License (MIT)
phetmarks  |  The MIT License (MIT)
plinko-probability  |  GNU GENERAL PUBLIC LICENSE
projectile-motion  |  GNU GENERAL PUBLIC LICENSE
protein-synthesis  |  GNU GENERAL PUBLIC LICENSE
reactants-products-and-leftovers  |  GNU GENERAL PUBLIC LICENSE
resistance-in-a-wire  |  GNU GENERAL PUBLIC LICENSE
rosetta  |  GNU GENERAL PUBLIC LICENSE
rutherford-scattering  |  GNU LESSER GENERAL PUBLIC LICENSE
scenery  |  The MIT License (MIT)
scenery-phet  |  The MIT License (MIT)
seasons  |  GNU GENERAL PUBLIC LICENSE
sherpa  |  The MIT License (MIT)
shred  | undefined
simula-rasa  |  GNU GENERAL PUBLIC LICENSE
slater  |  The MIT License (MIT)
smorgasbord  |  The MIT License (MIT)
states-of-matter  |  GNU GENERAL PUBLIC LICENSE
states-of-matter-basics  |  GNU GENERAL PUBLIC LICENSE
sugar-and-salt-solutions  |  GNU GENERAL PUBLIC LICENSE
sun  |  The MIT License (MIT)
tandem  |  The MIT License (MIT)
together  |  The 'together' project and all of the files in this repository are Copyright 2002-2015, University of Colorado Boulder.
under-pressure  |  GNU GENERAL PUBLIC LICENSE
vegas  |  The MIT License (MIT)
vibe  |  The MIT License (MIT)
wave-on-a-string  |  GNU GENERAL PUBLIC LICENSE

**Comment by samreid** [comment]
Several problems here:

1. babel has no LICENSE file (even though the README links to it)
2. beaker's LICENSE file looks like a copy/paste error
3. chains is LGPL.  Should be GPL (if a sim) or MIT (if common code)
4. the text for phet-metacog/LICENSE is wrong
5. rutherford-scattering is the wrong license, should be GPL but it is LGPL
6. shred is missing its LICENSE file.  If common code, it should be MIT

**Comment by samreid** [comment]
I fixed two items above and created issues for the remaining four issues.  An additional step for this issue will be to make sure the formatting/text/everything matches up for all LICENSE files of the same type.  I do not have plans to work on that at the moment, and am hence unassigning the issue.  Others feel free to take a look if you wish.

**Comment by pixelzoom** [comment]
I'm going to close this issue because the remaining repos that don't have licenses (babel, shred) are covered by issues specific to those repositories.
