### ISSUE TITLE
Are the ScreenView layout bounds wrong?

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#126]
ScreenView layout bounds are reportedly:

```javascript
var DEFAULT_LAYOUT_BOUNDS = new Bounds2( 0, 0, 768, 504 );
```

So I created an image with those dimensions as a mockup.

Then I positioned the image using this code:
```javascript
    this.addChild( new Image( mockupImage, {
      centerX: ScreenView.DEFAULT_LAYOUT_BOUNDS.centerX,
      centerY: ScreenView.DEFAULT_LAYOUT_BOUNDS.centerY,
      scale: ScreenView.DEFAULT_LAYOUT_BOUNDS.height / mockupImage.height,

      //Decrease the opacity so you can compare this to new elements that are being added
      opacity: 0.5
    } ) );
```

And it came out looking like so:

![photo](https://cloud.githubusercontent.com/assets/679486/3108223/4c276a5e-e68e-11e3-9e10-a6f374fe2cdb.PNG)

Why is there extra whitespace on the sides of the image?  Do we have the layoutbounds wrong?  I printed out ```ScreenView.DEFAULT_LAYOUT_BOUNDS.height / mockupImage.height``` on the iPad and it is coming up as 1.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/joist/issues/185 is resolved and DEFAULT_LAYOUT_BOUNDS has been set to (0,0,1024,618).  Closing.
