### ISSUE TITLE
Large dt values, how to handle them?

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#130]
In ESPB I put:

``` javascript
        //If they switched windows or tabs, just bail on that delta
        if ( dt > 1 || dt <= 0 ) {
          dt = 1.0 / 60.0;
        }
```

and we were thinking of doing something similar for Color Vision.  What have others done, and should we centralize support for this in Sim.js?

**Comment by pixelzoom** [comment]
This issue has been dormant for 2+ years. @samreid @jonathanolson What (if anything) do we need to do here?

**Comment by jonathanolson** [comment]
We have a code-review item to handle capping DTs, so I think this can be closed.

**Comment by pixelzoom** [comment]
Closing.

**Comment by samreid** [comment]
It looks like this review checkbox was added February 2016 and color vision does not include this fix, see https://github.com/phetsims/color-vision/issues/115 . For color vision, it looks like the code review https://github.com/phetsims/color-vision/issues/32 was completed in 2014, so the code review predates the change to the review process.

@ariel-phet @kathy-phet would you like to proactively test through published sims and see if there are any others that suffer from this problem?

Also tagging for developer meeting to discuss:
* are we still happy with solving this on a sim-by-sim basis and through code reviews rather than in joist?

Also tagging @phet-steele to see if there is a QA checklist this should be added to.

**Comment by samreid** [comment]
After reviewing Color Vision, I'm somewhat inclined to solve this in Joist, because Color Vision has 4 `step` callbacks (out of 6 `step` implementations) and it would be better not to have to cap DT in each of them--would be better to centralize at the call site.

**Comment by jonathanolson** [comment]
> I'm somewhat inclined to solve this in Joist

Like having a default maximum timestep, but the ability to override it (or have no maximum)?

**Comment by samreid** [comment]
Yes, exactly, and it would be supported in Sim.options

**Comment by pixelzoom** [comment]
+1 for having a default maximum timestep, which can be overridden in Sim.options.  There should be some value that means "no maximum tilmestep".

**Comment by samreid** [comment]
Sounds good.  For Color Vision, I have made a sim-specific workaround commit that will allow us to proceed immediately with simple maintenance releases, then we can address this larger issue without being rushed.

**Comment by pixelzoom** [comment]
On second thought... Is Sim.options the right place for this?  What if each screen has different requirements for the dt cap?

**Comment by pixelzoom** [comment]
Or what if a screen's model and view have different requirements for the dt cap?

**Comment by pixelzoom** [comment]
Also wondering how this cap affects tween?

**Comment by samreid** [comment]
Good point! Sim.js may not be the right level for an option/default cap.

**Comment by pixelzoom** [comment]
More thoughts...

Perhaps Sim `options.dtCap`  would be useful if it defaults to "no cap"? Clients that want a single cap that applies uniformly to model/view/tween can then use `options.dtCap`.

It's not currently possible to cap the dt provided to tween (see Sim.js, line 787). This is yet-another deficiency in how we're treating tween animations. 

Should `ScreenView` have `options.dtCap` and a default `step` that handles capping?  Should we have a `ScreenModel` type that does the same?

**Comment by samreid** [comment]
Proposed solution at the top of stepSimulation:

```js
      if (screen && screen.maxDT){
        dt = Math.max(dt,screen.maxDT);
      }
```

**Comment by samreid** [comment]
@jonathanolson says: sometimes I need the ability to decouple things.

**Comment by samreid** [comment]
@jbphet says a default of 500ms sounds OK.

**Comment by samreid** [comment]
@jonathanolson recommends a default cap.

@pixelzoom is on the fence.

Let's try it out and see how it goes.  

Volunteers: @pixelzoom got volunteered :)

**Comment by samreid** [comment]
@pixelzoom and @Denz1994 can take a look.  We are considering `null` to mean "no cap"

**Comment by pixelzoom** [comment]
The `dt` parameter to Sim `stepSimulation` is in seconds.  So I'm going to make Screen's `options.maxDT` also be in seconds.  The consensus was 500 ms, so the default will be `maxDT: 0.5`.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/joist/issues/130#issuecomment-300859793, @samreid proposed putting this "at the top of stepSimulation":

```js
      if (screen && screen.maxDT){
        dt = Math.min(dt,screen.maxDT);
      }
```

It can't be put at the top, because `screen` isn't defined until much later, and it's only defined if the screen is active.   But `dt` is used to compute `phet.joist.elapsedTime`.   So it seems like both the dt cap and the computation of `phet.joist.elapsedTime` need to be moved later.   Wondering:

But I'm wondering.... Why is `phet.joist.elapsedTime` being computed when the sim is inactive? This seems like a bug.  But if I change this behavior, is anything going to break?

And there's other stuff in `stepSimulation` that doesn't seem right.  If the sim is inactive, why do we call `frameStartedEmitter.emit`, "fire or synthesize input events", etc? 

@samreid let's talk.

**Comment by pixelzoom** [comment]
@Denz1994 Unfortunately this isn't going to be straightforward.  It's going to proceed in tiny increments, as I have time to sort this out.   So I don't think this is something that's appropriate for us to collaborate on.

**Comment by Denz1994** [comment]
I understand and am actively following the feed. If I have any questions can I post them here?

**Comment by pixelzoom** [comment]
> If I have any questions can I post them here?

Of course. That goes without saying for any issue.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/joist/issues/130#issuecomment-301529408, I said:
> Looks like we need to do a full review of what's going on in `stepSimulation`.

@samreid Can you please take a look at Sim `stepSimulation`, and comment on https://github.com/phetsims/joist/issues/130#issuecomment-301529408?

**Comment by samreid** [comment]
> It can't be put at the top, because `screen` isn't defined until much later, and it's only defined if the screen is active.

Can we move this line to the top of stepSimulation?

```js
        // If the user is on the home screen, we won't have a Screen that we'll want to step
        var screen = this.showHomeScreenProperty.value ? null : this.screens[ this.screenIndexProperty.value ];
```

> Why is `phet.joist.elapsedTime` being computed when the sim is inactive? This seems like a bug.  But if I change this behavior, is anything going to break?

That seems like a bug to me too.  It seems like everything should pause when the sim pauses.

> If the sim is inactive, why do we call `frameStartedEmitter.emit`, "fire or synthesize input events", etc?

I'm not sure how playback works.  Perhaps the sim is inactive but still needs to process input events?  I'm not sure.  I see other logic dealing with activeProperty even before that main if statement:

```js
      // fire or synthesize input events
      if ( phet.chipper.queryParameters.fuzzMouse ) {
        this.display.fuzzMouseEvents( phet.chipper.queryParameters.fuzzRate );
      }
      else {

        // if any input events were received and batched, fire them now.
        if ( this.options.batchEvents ) {

          // if any input events were received and batched, fire them now, but only if the sim is active
          // The sim may be inactive if interactivity was disabled by API usage such as the SimIFrameAPI
          if ( this.activeProperty.value ) {
            this.display._input.fireBatchedEvents();
          }
```

**Comment by samreid** [comment]
Here's a new stepSimulation implementation that uses `&&` strategy and cleans up some of the logic.  It is about 14 lines shorter and hopefully has the same behavior.

```js

    /**
     * Update the simulation model, view, scenery display with an elapsed time of dt.
     * @param {number} dt in seconds
     * @public (phet-io)
     */
    stepSimulation: function( dt ) {

      // Store the elapsed time in milliseconds for usage by Tween clients
      // TODO: we are /1000 just to *1000?  Seems wasteful and like opportunity for error. See https://github.com/phetsims/joist/issues/387
      phet.joist.elapsedTime = phet.joist.elapsedTime + dt * 1000;

      this.frameStartedEmitter.emit();

      // increment this before we can have an exception thrown, to see if we are missing frames
      this.frameCounter++;

      phetAllocation && phetAllocation( 'loop' );

      // prevent Safari from going to sleep, see https://github.com/phetsims/joist/issues/140
      if ( this.frameCounter % 1000 === 0 ) {
        this.heartbeatDiv.innerHTML = Math.random();
      }

      this.resizePending && this.resizeToWindow();

      // fire or synthesize input events
      phet.chipper.queryParameters.fuzzMouse && this.display.fuzzMouseEvents( phet.chipper.queryParameters.fuzzRate );

      // Step the models, timers and tweens, but only if the sim is active.
      // It may be inactive if it has been paused through the SimIFrameAPI
      if ( this.activeProperty.get() ) {

        if ( !phet.chipper.queryParameters.fuzzMouse && this.options.batchEvents ) {

          // if any input events were received and batched, fire them now, but only if the sim is active
          // The sim may be inactive if interactivity was disabled by API usage such as the SimIFrameAPI
          this.display._input.fireBatchedEvents();
        }

        // If the user is on the home screen, we won't have a Screen that we'll want to step
        var screen = this.showHomeScreenProperty.get() ? null : this.screens[ this.screenIndexProperty.get() ];

        // Timer step before model/view steps, see https://github.com/phetsims/joist/issues/401
        Timer.step( dt );

        // If the DT is 0, we will skip the model step (see https://github.com/phetsims/joist/issues/171)
        screen && screen.model.step && dt && screen.model.step( dt );

        // If using the TWEEN animation library, then update all of the tweens (if any) before rendering the scene.
        // Update the tweens after the model is updated but before the view step, see #401
        //TODO https://github.com/phetsims/joist/issues/404 run TWEENs for the selected screen only
        window.TWEEN && window.TWEEN.update( phet.joist.elapsedTime );

        // View step is the last thing before updateDisplay(), so we can do paint updates there, see #401
        screen && screen.view.step && screen.view.step( dt );
      }
      else {

        // If the sim was inactive (locked), then discard any scenery events instead of buffering them and applying
        // them later.
        if ( !phet.chipper.queryParameters.fuzzMouse ) {
          this.display._input.clearBatchedEvents();
        }
      }
      this.display.updateDisplay();

      this.frameEndedEmitter.emit1( dt );
    }
```

**Comment by pixelzoom** [comment]
Changes to Sim and stepSimulation were done in https://github.com/phetsims/joist/issues/425.  So now continuing where we left off with capping dt...

**Comment by pixelzoom** [comment]
Screen options.maxDT implemented in above commit. 

Tested in function-builder by setting the following options:
PatternsScreen: maxDT: 0.001
NumbersScreen: maxDT: 0.002
... then switching between Screens and verifying (by console.log) that dt changes when Screen changes, and that the value of dt is as expected.

**Comment by jonathanolson** [comment]
Reopening to understand a potential change to ordering.

I had to apply the above workaround (https://github.com/phetsims/vegas/commit/4d42e0497ab6690a61e9859ff5675a09295b5050) to the Vegas demo, since the screenview was getting displayed BEFORE it was ever stepped.

Is that an anticipated change? (RewardNode isn't fully set up until it is stepped).

**Comment by pixelzoom** [comment]
What changed related to ordering?  Can you point to something specific in Sim.js?

**Comment by pixelzoom** [comment]
And how did you discover the need for the workaround in vegas?

**Comment by phet-steele** [comment]
> And how did you discover the need for the workaround in vegas?

@pixelzoom, bayes continuous testing was reporting this error in the vegas demo:
```
  Error: Assertion failed: CanvasNode should not be used with an empty canvasBounds. Please set canvasBounds (or use setCanvasBounds()) on RewardNode
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1496806071248/assert/js/assert.js:21:13)
    at CanvasNodeDrawable.paintCanvas (https://bayes.colorado.edu/continuous-testing/snapshot-1496806071248/scenery/js/display/drawables/CanvasNodeDrawable.js?bust=1496807941321:67:17)
    at CanvasBlock.renderDrawable (https://bayes.colorado.edu/continuous-testing/snapshot-1496806071248/scenery/js/display/CanvasBlock.js?bust=1496807941321:328:16)
    at CanvasBlock.update (https://bayes.colorado.edu/continuous-testing/snapshot-1496806071248/scenery/js/display/CanvasBlock.js?bust=1496807941321:156:16)
    at BackboneDrawable.update (https://bayes.colorado.edu/continuous-testing/snapshot-1496806071248/scenery/js/display/BackboneDrawable.js?bust=1496807941321:248:37)
    at DOMBlock.update (https://bayes.colorado.edu/continuous-testing/snapshot-1496806071248/scenery/js/display/DOMBlock.js?bust=1496807941321:55:26)
    at BackboneDrawable.update (https://bayes.colorado.edu/continuous-testing/snapshot-1496806071248/scenery/js/display/BackboneDrawable.js?bust=1496807941321:248:37)
    at Display.updateDisplay (https://bayes.colorado.edu/continuous-testing/snapshot-1496806071248/scenery/js/display/Display.js?bust=1496807941321:381:26)
    at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1496806071248/joist/js/Sim.js?bust=1496807941321:786:20)
    at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/snapshot-1496806071248/joist/js/Sim.js?bust=1496807941321:720:14)
```

**Comment by samreid** [comment]
I suspect we should (at a minimum) call model.step and view.step before calling display.update.

**Comment by jonathanolson** [comment]
> What changed related to ordering? Can you point to something specific in Sim.js?

I was hoping you or @samreid would know. It just seems that view.step used to be called before display.update, but now is not.

> I suspect we should (at a minimum) call model.step and view.step before calling display.update.

This sounds good to me.

**Comment by samreid** [comment]
I commented out the vegas workaround and tested http://localhost/vegas/vegas_en.html?brand=phet&ea and did not see any problems.

**Comment by samreid** [comment]
I also added console.logs for display.update and RewardNodeScreenView.step (still with workaround commented out) and saw:

![image](https://user-images.githubusercontent.com/679486/26889197-9179169a-4b6a-11e7-9c4d-217ea940e7bc.png)

The null is for the home screen.  It looks as if the view.step is being called before the display.update for the reward node screen.  Am I testing the wrong thing?

**Comment by jonathanolson** [comment]
I have just pulled, and just ran the vegas demo WITHOUT the workaround (http://localhost:8080/vegas/vegas_en.html?brand=phet&ea&fuzzMouse) and it instantly errored out.

**Comment by samreid** [comment]
I can see the problem with ?fuzzMouse but not without ?fuzzMouse

**Comment by samreid** [comment]
Hypothesis: the fuzz mouse changes the screen.

**Comment by samreid** [comment]
In the preceding commits, I changed stepSimulation to update the screen variable after fuzzMouse runs and it seems to have fixed the problem.  However, it seems we should also update some of the logic about when the dt is updated because the maxDT for one screen could be used then another screen could be stepped with it.

**Comment by samreid** [comment]
In the preceding commit I moved the screen getter to after the fuzzing.  It seems OK in my testing vegas + vegas fuzz + CCK.  @pixelzoom, will you please review?

**Comment by samreid** [comment]
I skyped the group:
> Coders beware, Joist is running with unreviewed changes, see #130

**Comment by pixelzoom** [comment]
@samreid said:
> In the preceding commit I moved the screen getter to after the fuzzing. It seems OK in my testing vegas + vegas fuzz + CCK. @pixelzoom, will you please review?

I'm confused.  Sim.js currently looks very different that commit https://github.com/phetsims/joist/commit/eb61943578ced23cd09ed3657ff41664200bd44e. Were more commits made and not linked here?  I now see only one call to `getSelectedScreen`.

**Comment by samreid** [comment]
After https://github.com/phetsims/joist/commit/eb61943578ced23cd09ed3657ff41664200bd44e

Sim.js had:
* 3 subsequent commits for this issue (see thread above)
* 1 commit for https://github.com/phetsims/build-an-atom/issues/160
* 8 commits for https://github.com/phetsims/phet-io/issues/1146

**Comment by pixelzoom** [comment]
Looks OK to me.  `getSelectedScreen` was factored out because it was used in 2 places, now it's used only once.  I'll leave it up to @samreid to decide whether to inline it.

**Comment by samreid** [comment]
`stepSimulation` seems a bit clearer with `getSelectedScreen` as a separate function, I vote to leave it.
