### ISSUE TITLE
Tapping rapidly between navbar screen icons causes one screen to become inaccessible on iPad.

### ISSUE THREAD

**Issue by bryo5363** [phetsims/joist#137]
Tapping rapidly between both Concentration and Beer's Law tabs in Beer's Law Lab causes the Beer's Law portion to become inaccessible. 

Tested on iOS 8

**Comment by samreid** [comment]
@bryo5363 can you test this issue in a recently published sim, such as Reactants Products and Leftovers?

**Comment by pixelzoom** [comment]
@bryo5363 can you please test?

**Comment by bryo5363** [comment]
This issue is no longer present in the most current version of beers law
