### ISSUE TITLE
Make sure SimLauncher is used to launch the sim

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#142]
In https://github.com/phetsims/arithmetic/issues/42 we found that the sim was being launched without SimLauncher, and thus images weren't necessarily loaded before the sim started.  We should add a check to make sure the sim is using SimLauncher.

**Comment by pixelzoom** [comment]
@jonathanolson can this be closed?

**Comment by jonathanolson** [comment]
Looks like it was ported, closing.
