### ISSUE TITLE
Should we use fixed or variable time steps (or something else)?

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#144]
In Java, we most frequently used a fixed time step (ConstantDtClock) so that the dt would be the same in each frame.

In HTML5 (and a few Java sims), we have been using a variable time step, where the amount of time elapsed by the simulation model is proportional to the amount of time that passed in real life.

There are many pros and cons between fixed/variable time steps, but the main reason we have started using the variable time step is so that a simulation running on a slow machine will run at the same speed as the same simulation running on a fast machine (though at a different frame rate).

Here are a few links that elaborate on the tradeoffs between using fixed vs variable frame rate:
http://gamedev.stackexchange.com/questions/1589/fixed-time-step-vs-variable-time-step

This article also demonstrates a semi-fixed model with state interpolation to address temporal aliasing:
http://gafferongames.com/game-physics/fix-your-timestep/

In Energy Skate Park: Basics, some scenarios were not reproducible by pressing "return skater" and I suspect that is caused by dynamic (i.e. different) values for dt and a sensitive dependence on initial conditions.  Perhaps the time step issue would be good to discuss time step models again.

**Comment by pixelzoom** [comment]
This issue is 2+ years old, and variable time step seems to be serving us well.  

@samreid Can this issue be closed?

**Comment by samreid** [comment]
Yes, our current strategy to use dynamic timesteps when possible seems to work well.
