### ISSUE TITLE
Dev bounds are behind everything else

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#145]
In https://github.com/phetsims/energy-skate-park-basics/issues/184 it was identified that the dev bounds are not appearing in ESPB.  The problem is that they are added to the ScreenView first, before the background is added.  We need to allow these bounds to be put in front of the rest of the children in the ScreenView.

**Comment by pixelzoom** [comment]
Assigning to myself to see if I can resolve this stalled issue.

**Comment by pixelzoom** [comment]
I factored out the duplicate code, so (1) above is resolved.  I haven't heard of (2) above being an issue yet, so I think we can safely ignore it and create a new issue if it every happens. So... closing this issue.
