### ISSUE TITLE
Decide on a good way of passing string direction (LTR / RTL) to Scenery

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#152]
Right now, RTL strings are bidi-reordered as embedded in LTR, breaking things like below (Wave on a String, Hebrew):

![woas-hebrew](https://cloud.githubusercontent.com/assets/480878/4038441/8ea05ffe-2cb5-11e4-89b6-8b003a0dea63.png)

**Comment by pixelzoom** [comment]
This issue is similar to https://github.com/phetsims/phetcommon/issues/16.

**Comment by jonathanolson** [comment]
Should we consider PhetText? Uses PhetFont by default, uses correct LTR/RTL, and any other default settings? It would also be able to trigger HTML rendering like HTMLText if necessary.

**Comment by pixelzoom** [comment]
I've been using sim-specific subtypes of Font (e.g., GLFont, RPALFont,...) to prepare myself for this eventuality.  So it would be a trivial refactor in my sims.

**Comment by jonathanolson** [comment]
Added to the developer agenda for discussion.

**Comment by jonathanolson** [comment]
See http://www.w3.org/International/questions/qa-bidi-unicode-controls for info on embedding.

**Comment by pixelzoom** [comment]
Notes from 3/26/15 developer meeting:

```
JO examples:
   new Text( string, { direction: phet.joist.direction, font: new PhetFont( 14 )  } )
   new PhetText( string, { size: 14 } )
   new PhetText( string, { size: 14, direction: 'ltr' } )
SR: how about indicating the direction in the string? (via Unicode escapes)
Unicode escapes needed for mixed-direction strings (eg, a RTL string with an English scientific term in the middle of it)
JO: Web standard is to set direction, not use Unicode escapes
SR: could also be metadata associated with string, instead of Unicode escapes in the actual string
Consensus: investigate Unicode escapes, investigate what others are doing
```

**Comment by jonathanolson** [comment]
In Chrome (Win 7):

Creating a div, filled with the string (default CSS direction: 'ltr):
![scenery-rtl-ltr](https://cloud.githubusercontent.com/assets/480878/7780145/95cbf8f8-0098-11e5-8223-8907b1f31d40.png)

Same div, direction set to 'rtl':
![scenery-rtl-rtl](https://cloud.githubusercontent.com/assets/480878/7780151/a4fce5bc-0098-11e5-983f-5b9067e849c6.png)

It looks like it's using the bidi algorithm for ordering, but since the base direction is LTR, any string that starts with punctuation will consider that punctuation as LTR, and the rest of the internal (Arabic/other RTL text) as RTL, causing the above issue.

So, it's my opinion that the built-in browser support is not sufficient.

I'm curious how this string was handled in Java (will check).

**Comment by jonathanolson** [comment]
Reference screenshot from Flash version of the sim:
![woas-rtl](https://cloud.githubusercontent.com/assets/480878/7780201/37b60b68-0099-11e5-9ee8-e9e3c04f81d8.png)

**Comment by jonathanolson** [comment]
Patched the text into the first tab title in a Java sim (running as Hebrew, _iw):
![scenery-rtl-java](https://cloud.githubusercontent.com/assets/480878/7780334/a1a4435e-009a-11e5-93d8-b9316bdc3e4f.png)

**Comment by jonathanolson** [comment]
Notably in Java, it has the same appearance regardless of what locale is being used.

**Comment by jonathanolson** [comment]
Investigating adding embedding marks around translated strings, as that may be a good out.

**Comment by jonathanolson** [comment]
Notably, U+202A pushes LTR, U+202B pushes RTL, U+202C pops, so we would have:
```js
'\u202a' + string + '\u202c';
```

**Comment by jonathanolson** [comment]
Adding embedding override marks looks like it will work, but we'll only want to do it for strings loaded from RTL locales (NOT the English fall-back strings)!

![scenery-rtl-embedding](https://cloud.githubusercontent.com/assets/480878/7780586/fc75bb70-009d-11e5-8677-5936c257aa5f.png)

**Comment by jonathanolson** [comment]
The string plugin and build process will need to know about which locales are RTL, so they can insert the embedding marks.

@jbphet, is it OK with you if I convert the Java locale list over, and include the LTR/RTL information (and put it in chipper)? Then rosetta should be able to refer to the same list, right?

**Comment by jonathanolson** [comment]
Also http://unicode.org/reports/tr9/#Directional_Formatting_Characters explains the special characters for formatting (will include in code documentation for this).

**Comment by jonathanolson** [comment]
Also, I'll have the locale information set up in a way that can be read in the browser and Node.js, since it has one browser requirement (string plugin) and 2-3 node.js requirements (string plugin, other grunt build, and rosetta).

**Comment by jonathanolson** [comment]
Java source code notes the following locale codes are RTL, everything else is LTR: iw, ar, fa, ur. Presumably any country code for those languages will also be RTL.

**Comment by jbphet** [comment]
It's fine with me to convert the Java locale list over and to use it for now to figure out LTR vs RTL.  We can always ditch it if we come up with something better in the future.

**Comment by jonathanolson** [comment]
Committed, tested with require.js ?locale=iw, and with built iw (hebrew) version.

Reassigning to @jbphet for any necessary review, and let me know if the localeInfo looks ok. It's basically like a map with entries:
```js
    iw: {
      name: 'Hebrew',
      localizedName: 'עברית',
      direction: 'rtl'
    },
```

When Unfuddle SVN stops failing with the following message, I'll have the code for the conversion set up:
```
Error:svn: E175002: Commit failed (details follow):
svn: E175002: timed out waiting for server
svn: E175002: PROPFIND request failed on '/svn/phet_svn/trunk'
```

**Comment by jbphet** [comment]
While reviewing localeInfo.js, I noticed the following comment:

```js
// NOTE: We are using an older version of ISO 639-1 because java.util.Locale maps some of the newer language codes to
// older codes.
// See Locale.convertOldISOCodes.
// The affected country codes are:
// he -> iw (Hebrew)
// yi -> ji (Yiddish)
// id -> in (Indonesian)
```

This begs the question: Why not update to the latest version while we're working on this?  This website shows the list, and it has the newer names: https://www.loc.gov/standards/iso639-2/php/code_list.php.

And, for that matter, why not use the three-letter codes listed in 639-2, if these are that latest and greatest identifiers for locales?

I asked @jonathanolson about this, and there would apparently be some impacts to the web site if we were to start using these updated locale IDs, but the benefits may outweigh the costs.  He recommended discussing and deciding whether to use these IDs at the next developer meeting.  I've put it on the agenda.

**Comment by jbphet** [comment]
While reviewing this, I noticed that the way mixed strings (i.e. strings with RTL and LTR portions) are shown when the string file is opened in IntelliJ or MS Word is a bit different from how they appear in the sim.  Screenshots are shown below.  I'm not sure that this matters.  What probably matters most is that the strings appear in the sim the same way that they appear in the translation utility web page.  I'll work with @aaronsamuel137 to verify that this is the case.

Mixed string from the Persian version of Acid Base Solution, as depicted in IntelliJ:
![rtl-abs-string-file-excerpt](https://cloud.githubusercontent.com/assets/3082831/8443987/124fe51e-1f49-11e5-9c28-cc6ff330a395.png)

And this is how is appears in MS Word:
![rtl-abs-string-file-in-word](https://cloud.githubusercontent.com/assets/3082831/8443990/1bf7325c-1f49-11e5-8a81-13dbf0b66610.png)

Here is how the same string appears in the sim:
![rtl-abs-screen-shot](https://cloud.githubusercontent.com/assets/3082831/8443998/2bd0b806-1f49-11e5-949d-a9ef875446a2.png)

**Comment by jonathanolson** [comment]
Remember the editors assume LTR on the outside, so it sees first an LTR chunk "PH" then the rest is RTL. Thus "PH" appears first in the editors, with an embedded RTL segment afterwards.

In the browser, we note this is a translated string (assumes RTL on the outside), so first it sees an embedded LTR chunk (PH), and places it in the RTL order (on the right) before the rest of the non-embedded RTL text is rendered.

**Comment by jbphet** [comment]
In a conversation with @jonathanolson, he suggested that I test changing the renderer to canvas and dom and make sure that the ordering of the strings looks consistent.

**Comment by jbphet** [comment]
We discussed the question about whether to update to a more recent version of the ISO language codes (originally raised in https://github.com/phetsims/joist/issues/152#issuecomment-117348862) in the 7/2/2015 developer meeting, and decided to leave these codes unchanged for now.  The reasoning is that the codes aren't used outside of PhET, and changing them would require work on the website code and the build tools code, so updating the codes doesn't seem worth the effort.

**Comment by jbphet** [comment]
Tested using alternative rendering, it all worked fine.  Example Sim was used, and Persian was the language.

**Comment by jbphet** [comment]
@jonathanolson and I briefly discussed the idea of embedding the Unicode control characters in the strings using rosetta so that no automatic insertion would be needed.  We decided against this, since it would likely make it tricky to edit these files by hand, which is probably going to happen at some point.

**Comment by jbphet** [comment]
As a result of testing this, some issues were logged on rosetta (the translation utility), please see https://github.com/phetsims/rosetta/issues/27 and https://github.com/phetsims/rosetta/issues/28.  Also, the translation pages for RTL languages are now set up so that the edit boxes "grow" from the right, which is how it should work.

**Comment by jbphet** [comment]
This all seems to be working well.  Other work on rosetta is being tracked in other issues, so this one will be closed.
