### ISSUE TITLE
Options dialog + query params

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#154]
This issue came up in https://github.com/phetsims/molecule-polarity/issues/5, where we need to be able to choose from 2 conventions for bond dipoles. 

Here's one idea that I proposed:
> As a general solution for setting global options, we might consider putting an (optional) 'Options' menu item in the PhET menu at the bottom-right of the navigation bar. Selecting 'Options' would open an Options dialog (similar to the About dialog) where global options could be set. In addition, we could have a query parameter for each option, so that teachers would have a choice of whether to provide a pre-configured URL, or let students set the options themselves.

Other ideas?

We should definitely ask what the requirements are, because changing global settings while the sim is running will be more expensive to implement than configuring the sim once at startup based on query parameters.

**Comment by jonathanolson** [comment]
Added back the close button for the Options dialog, but with better positioning (doesn't push content over, and is fitted along the border with an adjustable constant). Will wait to hear feedback on appearance, as it is likely to change.

**Comment by jonathanolson** [comment]
This feature is being used in molecule-shapes, molecule-polarity, charges-and-fields and states-of-matter-basics. I don't see any uncompleted requests here, so I'm closing the issue.

I'd encourage any requests for changes to be made in a new issue that is specific to the change.

**Comment by pixelzoom** [comment]
Reopening. Does anyone else feel that the 'Options' title occupies way too much vertical space? See screenshot below from Molecule Polarity. 

![screenshot_197](https://cloud.githubusercontent.com/assets/3046552/5961949/61a360d8-a79d-11e4-8041-0cfa28a8673d.png)

**Comment by jonathanolson** [comment]
It does bug me a bit, however the vertical spacing should be the same for the top/bottom. Recommended way to fix this?

**Comment by pixelzoom** [comment]
Looks like this is a general issue with joist.Dialog, not just Options.dialog.

Recommended to make 'Options' look more like a dialog title, with close button to the right. This would be fairly easy to do if we didn't have the titleAlign option. Imo, it should always be centered, so that all dialogs look similar, I don't see a reason to make it configurable. 

Here's a sample iOS options dialog. Not saying we should copy this, but just for comparison of how the title and buttons are placed. It don't think the title and button needs to be in a bar. 

![screenshot_443](https://cloud.githubusercontent.com/assets/3046552/5962719/06422052-a7a3-11e4-9b5f-cef07be2b27e.png)

**Comment by pixelzoom** [comment]
Perhaps this discussion (title + close button placement) should be moved to https://github.com/phetsims/joist/issues/166 (crate a Dialog base type)?

**Comment by pixelzoom** [comment]
Moved the discussion of title + close button to #166. Closing.
