### ISSUE TITLE
Factor out Logo colors

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#158]
In some sims, some colors are matched to the PhET logo colors.  For instance, PaperAirplaneNode matches the PhET shade of yellow.  In other sims, when yellow and blue are used they are sometimes matched to the PhET logo for consistency.  It would be good to create a Joist file like "Colors.js" or "LogoColorScheme.js" or something like that to store a single copy of the logo colors instead of copy/pasting these colors in multiple places.

**Comment by pixelzoom** [comment]
This should go in scenery-phet.PhetColorScheme.

**Comment by pixelzoom** [comment]
Looks like this was partially addressed in phetsims/scenery-phet#270.  In PhetColorScheme:

```js
26 var PHET_LOGO_YELLOW = new Color( 242, 233, 22 ); // the color of the yellow in the PhET logo
```

So now I'll investigate whether we also need PHET_LOGO_BLUE.  Or maybe I'll just add it, since @samreid said "yellow and blue are used they are sometimes matched to the PhET logo for consistency".

**Comment by pixelzoom** [comment]
I've been unable to find a .ai file for the PhET logo in GitHub, so I'm resorting to looking at other files.
Inspecting brand/phet/images/logo.png and phet-cafepress/webite-assets/phet-logo-registered.svg, I see these colors:

yellow = 'rgb( 254, 225, 5 )'
blue = 'rgb( 106, 206, 245 )'

PhetColorScheme.PHET_LOGO_YELLOW doesn't match this, so I've reopened phetsims/scenery-phet#270.

**Comment by pixelzoom** [comment]
The official PhET logo file is apparently brand/phet/assets/phet-brand-assets.ai. Inspecting that file confirms the above logo colors.

**Comment by pixelzoom** [comment]
PhET logo blue may also appear in client code as '#6acef5'.

**Comment by pixelzoom** [comment]
Added PHET_LOGO_BLUE.  The only usage I could find was in fraction-matcher, which I replaced. 

We'll sort out the correct value for PHET_LOGO_YELLOW in phetsims/scenery-phet#270.

Closing.
