### ISSUE TITLE
Are we really using 206 scenery nodes in the home screen?

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#160]
There is a scenery issue https://github.com/phetsims/scenery/issues/275 that shows Win8/Chrome stutters when the mouse changes to a hand due to DOM reflows.  It seems like the problem goes away as the size of the scenery tree is reduced.  In https://github.com/phetsims/energy-skate-park-basics/issues/208 I noticed that the number of nodes (as measured by simScene.popupDebug() drops by about 206 nodes when running with ?standalone.  This means the homescreen nodes + navbar nodes are taking up a significant amount of the scenery tree.  It should be investigated.  One part of the solution may be to use the new sun/buttons to implement the joist buttons if they have too many nodes (for mouseover,press,down,deselected,etc).

**Comment by pixelzoom** [comment]
@samreid Is this still relevant, or can it be closed now that we're using sun buttons?

**Comment by jonathanolson** [comment]
Balancing Act (3 screens) has a significantly smaller number of nodes, and with Scenery 0.2 the default is to not include the home screen in the SVG DOM when it isn't visible. I'd think this isn't the pain point it once was.

**Comment by pixelzoom** [comment]
Using phet.joist.sim.display.popupDebug(), it looks like energy-skate-park-basics has 36 nodes on its home screen (if I'm interpreting correctly). That's down from 206, and seems reasonable.

**Comment by samreid** [comment]
I think we're done here, closing.
