### ISSUE TITLE
create a Dialog base type

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#166]
As noted in https://github.com/phetsims/joist/issues/154, AboutDialog is not generalizable into a Dialog subtype. So we're going to start over.  Design and implement joist.Dialog, to be used as the base type for AboutDialog, OptionDialog, and other future dialogs.

**Comment by pixelzoom** [comment]
Moving this from https://github.com/phetsims/joist/issues/154 ... The title and close button need some work, they occupy too much vertical space. For example, here's the Options dialog from Molecule Polarity:

![61a360d8-a79d-11e4-8041-0cfa28a8673d](https://cloud.githubusercontent.com/assets/3046552/5965872/bf56ccf0-a7bc-11e4-8a1c-10e89be6a393.png)

**Comment by pixelzoom** [comment]
At 1/29/15 dev meeting, there was also discussion about trying this style of close button, like this example from least-squares-regression:

![screenshot_444](https://cloud.githubusercontent.com/assets/3046552/5965907/1451eb2c-a7bd-11e4-80ea-8a694a592815.png)

**Comment by pixelzoom** [comment]
@ariel-phet and @pixelzoom will triage the feature requirements.

**Comment by samreid** [comment]
I'm going to need a semitransparent overlay for https://github.com/phetsims/scenery/issues/414  Can @pixelzoom and/or @jonathanolson comment on whether this feature should use the barrierRectangle used by dialogs, or something new and separate?

**Comment by pixelzoom** [comment]
If the barrier rectangle is decoupled from Dialog, then it's probably appropriate to use it.

**Comment by pixelzoom** [comment]
If the barrier rectangle is decoupled from Dialog, then it's probably appropriate to use it. If it's not decoupled from Dialog, but would fit the bill, then decoupling it.  Not recommended to create something new and identical to the barrier rectangle.

**Comment by samreid** [comment]
Here's what the code looks like at the moment:

```js
    // Semi-transparent black barrier used to block input events when a dialog (or other popup) is present, and fade
    // out the background.
    this.barrierStack = new ObservableArray();
    this.barrierRectangle = new Rectangle( 0, 0, 1, 1, 0, 0, {
      fill: 'rgba(0,0,0,0.3)',
      pickable: true
    } );
    this.topLayer.addChild( this.barrierRectangle );
    this.barrierStack.lengthProperty.link( function( numBarriers ) {
      sim.barrierRectangle.visible = numBarriers > 0;
    } );
    this.barrierRectangle.addInputListener( new ButtonListener( {
      fire: function( event ) {
        assert && assert( sim.barrierStack.length > 0 );
        sim.hidePopup( sim.barrierStack.get( sim.barrierStack.length - 1 ), true );
      }
    } ) );
```

My main question is whether we have modal dialog support yet.  The overlay rectangle is conceptually similar to a (invisible) modal dialog.

**Comment by pixelzoom** [comment]
I don't know if we have modal dialog support yet. I've been somewhat out of the loop on Dialog development.

**Comment by jonathanolson** [comment]
The barrier rectangle is decoupled, however it won't block all input events as desired. I've implemented display.interactive (https://github.com/phetsims/scenery/issues/414) which should fit the bill for blocking events.

**Comment by samreid** [comment]
display.interactive is working perfectly for my purposes, thanks.  I may still use the barrier rect to show the sim as grayed out though, see #232

**Comment by pixelzoom** [comment]
In 8/16/15 dev meeting agenda, @ariel-phet asked:
> Should this issue be revisited? Closed? 

I'll review, to see what still needs to be done.

**Comment by pixelzoom** [comment]
I created issues (see above) for some of the things that haven't been completed.

A more general issue is that responsibilities have not been implemented as proposed in the requirements. From https://github.com/phetsims/joist/issues/166#issuecomment-57212796:

>PhET menu responsibilities (global dialogs):
• creates modal dialogs exclusively
• adds a dialog to the current screen, removes it from the current screen when dismissed
• responsible for positioning of the dialog (typically centered on screen)
>
> Screen responsibilities (screen-specific dialogs):
• a screen can create a modal or non-modal dialog, and is responsible for adding/removing it from its ScreenView
• responsible for positioning of the dialog (typically centered on screen)

Deviations:

• Screen and ScreenView are never involved. 
• Sim handles show/hide.
• Dialog (not Sim or Screen) handles positioning, and it's limited to centering.

Assigning to @jonathanolson to comment on why it's desirable to have Sim (which already has too many responsibilities, see #208) handle show/hide.  And why are we limited to centering?

**Comment by pixelzoom** [comment]
Also wondering how the current implementation will handle non-modal dialog, where the user may change screens while one or more dialogs (specific to the current screen) are displayed.

**Comment by pixelzoom** [comment]
I created a joist demo application for testing Dialog, see joist/joist_en.html.  Numerous problems noted with non-modal dialogs, see https://github.com/phetsims/joist/issues/293.

**Comment by jonathanolson** [comment]
> Assigning to @jonathanolson to comment on why it's desirable to have Sim (which already has too many responsibilities, see #208) handle show/hide. And why are we limited to centering?

It doesn't have to be sim, but it has to be something with access to the root node (which Sim has), and probably something global (since the background put up behind needs to be tracked in once place, and it needs to try to "exit" the top dialog if allowable).

And it doesn't necessarily need to be centered, is there a good use-case for non-centered?

**Comment by pixelzoom** [comment]
>  is there a good use-case for non-centered?

Any non-modal dialog. (And any API I've ever worked with that supports dialogs.)

**Comment by jbphet** [comment]
@pixelzoom has reviewed and has created specific issues for the problems described above.  This was reviewed at the 8/20/2015 dev meeting and we agreed it can be closed.
