### ISSUE TITLE
Improve the histogram visualization in ?profiler

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#168]

**Comment by samreid** [comment]
No plans to work on this at the moment.  Low priority but others feel free to work on this if you want.

**Comment by pixelzoom** [comment]
I'm guessing that "the histogram" is the comma-separate set of integers shown in the upper-left corner of the screen. E.g. in rutherford-scattering:

![screenshot_85](https://cloud.githubusercontent.com/assets/3046552/20722928/b2a19ca0-b625-11e6-837f-d45d4e74b829.png)

**Comment by samreid** [comment]
Yes, you guessed correctly!

**Comment by pixelzoom** [comment]
What are the x and y axes of the histogram?  (I read Profile.js, but still don't grok.)

**Comment by pixelzoom** [comment]
Also don't understand the bit after '+++ ='.  Is this also some sort of histogram?

**Comment by samreid** [comment]
0,0,1,5,7,4,3,0,0,0,0,0,0.... ++= 37, 99

would mean that 0 frames took 0 ms, 0 frames took 1ms, etc. 1 frame took 3ms, 5 frames took 4ms, etc.  Then additionally another frame took 37ms and another took 99ms.

**Comment by pixelzoom** [comment]
So... The part before the '+++ =' is a histogram for frame rates from 0-29ms, and the value is number of frames for each frame rate.  And the part after the '+++ =' is used to indicate frame rates that exceeded 29ms - without indicating how many frames exceeded 29ms.   Is that correct?

**Comment by samreid** [comment]
> without indicating how many frames exceeded 29ms.

Well, if there were 5 frames that took 37ms each, it would say: `+++=37,37,37,37,37`  Everything else you said looks correct.

**Comment by pixelzoom** [comment]
In the commit above, I improved the display formatting (shown below in rutherford-scattering) and documented the display format.  I hope you weren't too attached to the `'+++ ='` separator, because I changed it. Using a common separator between the 4 logical fields make it easier to document the general form, i.e.:

```js
12 * The general format is:
13 *
14 * FPS - ms/frame - histogram [- longTimes]
```

@samreid feel free to take a peek.

![screenshot_86](https://cloud.githubusercontent.com/assets/3046552/20736835/58138ffa-b666-11e6-85a8-320cef8841b0.png)

**Comment by pixelzoom** [comment]
Sure would be nice if the longTimes were sorted, so you could easily see the largest.

**Comment by pixelzoom** [comment]
Would also be nice if the histogram was divided into groups of 10.  With 30 numbers all mashed together, it's a little difficult to guess which times the numbers go with.

**Comment by pixelzoom** [comment]
I added sorting of longTimes, in ascending order. @samreid let me know if you think this will compromise the goal of being "minimally invasive".

**Comment by pixelzoom** [comment]
I noticed that when I turn on traces and the light in rutherford-scattering, I get a large number of values in `longTimes`. That part of the output gets pushed to a new line (see screenshot below) and the largest value may actually be off the right side of the screen.  So I changed `longTimes` to be sorted in descending order, so that the largest values are guaranteed to be visible. 

![screenshot_87](https://cloud.githubusercontent.com/assets/3046552/20737386/87c2b7aa-b669-11e6-88c4-bc81f25faa0d.png)

**Comment by pixelzoom** [comment]
Function `frameEnded` is structured like this:

```js
frameEnded: function() {

 var timeBetweenFrames = this.frameStartTime - this.lastFrameStartTime;
  if ( this.frameCount % 60 === 0 ) {
    // update the display and clear data structures
  }
  else {
    // add data point to data structures
  }
}
```

I think we're missing a data point every 60 frames. Shouldn't the `else` block happen on every call to `frameEnded`?

**Comment by pixelzoom** [comment]
Fixed the above bug in `frameEnded`.  Data for every 60th frame is now recorded.

**Comment by pixelzoom** [comment]
The histogram length `30` is repeated 3 times, should be a constant.

**Comment by pixelzoom** [comment]
The first time that `longTimes` is displayed, the first value is `NaN`.

**Comment by pixelzoom** [comment]
`NaN` was being displayed because `previousFrameStartTime` was undefined for the first frame recorded.  Fixed by skipping the first frame.   That also made me realize that `frameCount` was unnecessary, because `allTimes.length` is always the number of frames recorded.

**Comment by pixelzoom** [comment]
Think I'll stop here. @samreid let me know if you see anything that I've messed up.

**Comment by pixelzoom** [comment]
I noticed that the display div has `id="trace"`.  How about something that's more easily associated with this feature, like `id="profiler"` or `id="phetProfiler"` ?

**Comment by samreid** [comment]
Spot testing seems good, I also renamed the dom element ID in the above commit.  @pixelzoom anything else to do here?

**Comment by pixelzoom** [comment]
👍 Closing.
