### ISSUE TITLE
Add "built by ??? using PhET's Open Source libraries"

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#169]
In #120, we added custom branding and said:

> Add something like - built by XX using PhET's open source libraries - instead of a blank splash screen.
> 
> I recall someone was making artwork for this. I'll ask around.

**Comment by samreid** [comment]
@ariel-phet are we still going to do this?  Can this issue be closed?

**Comment by ariel-phet** [comment]
I don't think so. Closing
