### ISSUE TITLE
Investigate IDEA 14 for development

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#173]
IntelliJ IDEA 14 came out this week.  We should check it out and see whether it can be used for working on our projects.

**Comment by pixelzoom** [comment]
I'll check it out.

**Comment by pixelzoom** [comment]
I updated to IntelliJ 14 and reformatted the source for a couple of repos (but committed no changes): acid-base-solutions, graphing-lines, forces-and-motion-basics, build-an-atom.  Here's a summary of the formatting changes that I discovered.  In the examples below, I'll use '-' to indicate the old format, and '+' to indicate the new format.

By far, the 2 most common changes involve spaces within the brackets surrounding object literals and arrays. The default formatting is to have no spaces. Examples:

```js
// No space inside object literal braces (graphing-lines.SlopeToolNode line 41)
// CodeStyle > JavaScript > Spaces > Within > Object literal braces
- font: new GLFont( { size: 16, weight: 'bold' } ),
+ font: new GLFont( {size: 16, weight: 'bold'} ),

// No space inside array braces (graphing-lines.UndefinedSlopeIndicator line 32)
// CodeStyle > JavaScript > Spaces > Within > Brackets
+ Node.call( this, {children: [ this.line1, this.line2 ]} );
- Node.call( this, {children: [this.line1, this.line2]} );
```

The next most common change is in how braces for object literals are formatted. Here are some examples.  These may be related to the setting of CodeStyle > JavaScript > Wrapping and Braces > Object literals.

```js
// Put closing brackets on a new line (graphings-lines.GraphNode, line 144)
- var lineNode = new ArrowNode( tailLocation.x, tailLocation.y, tipLocation.x, tipLocation.y, {
    doubleHead: true,
    headHeight: AXIS_ARROW_SIZE.height,
    headWidth: AXIS_ARROW_SIZE.width,
    tailWidth: AXIS_THICKNESS,
    fill: AXIS_COLOR,
    stroke: null } );
+ var lineNode = new ArrowNode( tailLocation.x, tailLocation.y, tipLocation.x, tipLocation.y, {
    doubleHead: true,
    headHeight: AXIS_ARROW_SIZE.height,
    headWidth: AXIS_ARROW_SIZE.width,
    tailWidth: AXIS_THICKNESS,
    fill: AXIS_COLOR,
    stroke: null 
  } );

// Reformat closing braces and parens (graphing-lines.SlopeToolNode line 65)
- thisNode.parentNode = new Node( { children: [
    thisNode.riseArrowNode,
    thisNode.riseValueNode,
    thisNode.runArrowNode,
    thisNode.runValueNode
  ] } );
+ thisNode.parentNode = new Node( { 
     children: [
      thisNode.riseArrowNode,
      thisNode.riseValueNode,
      thisNode.runArrowNode,
      thisNode.runValueNode
    ] 
  } );

// Space after brace (build-an-atom.AtomView line 78)
- var atomNode = new AtomNode( model.particleAtom, mvt,
    { showElementNameProperty: model.showElementNameProperty,
      showNeutralOrIonProperty: model.showNeutralOrIonProperty,
      showStableOrUnstableProperty: model.showStableOrUnstableProperty,
      electronShellDepictionProperty: model.electronShellDepictionProperty
    } );
- var atomNode = new AtomNode( model.particleAtom, mvt,
    { 
      showElementNameProperty: model.showElementNameProperty,
      showNeutralOrIonProperty: model.showNeutralOrIonProperty,
      showStableOrUnstableProperty: model.showStableOrUnstableProperty,
      electronShellDepictionProperty: model.electronShellDepictionProperty
    } );
```

Lines that exceed the configured max line length are automatically reformatted. For example:

```js
// Reformat long lines (graphing-lines.IconFactory line 82)
// CodeStyle > JavaScript > Wrapping and Braces > Object literals
- var axisNode = new scenery.Line( 0, -0.05 * SCREEN_ICON_BASE_SIZE.height, 0, 1.05 * SCREEN_ICON_BASE_SIZE.height, { stroke: 'rgb(134,134,134)', lineWidth: 10 } );
+ var axisNode = new scenery.Line( 0, -0.05 * SCREEN_ICON_BASE_SIZE.height, 0, 1.05 * SCREEN_ICON_BASE_SIZE.height, { 
    stroke: 'rgb(134,134,134)', 
    lineWidth: 10   
  } );
```

All of the above seem like things that we can make decisions about, adjust PhetStyle.xml, and reformat code. But there are a few formatting changes that are a little worrisome.

In object literals, one or more extra spaces are sometimes inserted between field name and value. For example:

```js
// Spurious space? (build-an-atom.ChargeComparisonDisplay line 47, after ‘left’ field)
- var minusSymbolPath = new Path( minusSymbolShape, {
    stroke: 'black',
    lineWidth: 1,
    fill: 'rgb( 100, 100, 255 )',
    left: INTER_SYMBOL_DISTANCE / 2,
    centerY: VERTICAL_INSET + SYMBOL_WIDTH * 1.5
  } );
+ var minusSymbolPath = new Path( minusSymbolShape, {
    stroke: 'black',
    lineWidth: 1,
    fill: 'rgb( 100, 100, 255 )',
    left:   INTER_SYMBOL_DISTANCE / 2,
    centerY: VERTICAL_INSET + SYMBOL_WIDTH * 1.5
  } );
```

And fields values are sometimes left aligned, like in this example:

```js
// Horizontally aligned field values (graphing-lines.GLQueryParameters)
- var RPALQueryParameters = {

    // adds 'Test', 'Skip', 'Replay' buttons to the Game, shows challenge answers at the bottom of the Game screen
    DEV: !!getQueryParameter( 'dev' ) || false,

    // plays all reactions for each level of the game
    PLAY_ALL: !!getQueryParameter( 'playAll' ) || false,

    // initializes game spinners to the correct answer
    GUESS_CORRECT: !!getQueryParameter( 'guessCorrect' ) || false,

    // shows the game reward, regardless of score
    SHOW_REWARD: !!getQueryParameter( 'showReward' ) || false
  };
+ var RPALQueryParameters = {

    // adds 'Test', 'Skip', 'Replay' buttons to the Game, shows challenge answers at the bottom of the Game screen
    DEV:           !!getQueryParameter( 'dev' ) || false,

    // plays all reactions for each level of the game
    PLAY_ALL:      !!getQueryParameter( 'playAll' ) || false,

    // initializes game spinners to the correct answer
    GUESS_CORRECT: !!getQueryParameter( 'guessCorrect' ) || false,

    // shows the game reward, regardless of score
    SHOW_REWARD:   !!getQueryParameter( 'showReward' ) || false
  };```
```

**Comment by pixelzoom** [comment]
We should make some decisions about the above formatting changes at a near-future developer meeting. In the meantime,  I'm going to continue using IntelliJ 14, with 'reformat code before commit' turned off.

**Comment by pixelzoom** [comment]
Note that I examined a small sample of repos, from a couple of different developers. I also did not evaluate the impact on @jonathanolson's work (scenery, kite, dot) because he has typically not used IntelliJ.

**Comment by pixelzoom** [comment]
1/13/15 dev meeting:
- update joist/util/phet-idea-codestyle.xml add space inside of braces and brackets
- all developers update to IntelliJ 14 and install phet-idea-codestyle.xml
- all developers reformat their own sims; JO will handle scenery/kite/dot; CM will handle of there common repos
- add any additional issues encountered to this GitHub issue
- report issues to IntelliJ after we've reformatted all PhET code

**Comment by pixelzoom** [comment]
For Mac users, IntelliJ code styles live in $HOME/Library/Preferences/IntelliJIdea14/codestyles/.

**Comment by pixelzoom** [comment]
I've completed the code-style changes that we discussed in today's developer meeting. If you look at https://github.com/phetsims/joist/commit/73213c52dbd76625baac9b7606ceccc9133a2ba9, you can see what changed.  Setting Set SPACE_WITHIN_BRACKETS and SPACES_WITHIN_OBJECT_LITERAL_BRACES to "true" is the explicit change that we decide on. Other changes are default values of new settings.

**Comment by samreid** [comment]
I reformatted my repos above.  Liking IDEA 14 quite a lot so far, pushing is much faster for me!

**Comment by pixelzoom** [comment]
Pushing is much faster for me too.

**Comment by pixelzoom** [comment]
I completed reformatting of all sims where i was primary developer or liaison, and all common-code except scenery, kite and dot.

**Comment by pixelzoom** [comment]
I reformatted @aaronsamuel137 and @phetsims/jessegreenberg sims.

**Comment by pixelzoom** [comment]
Via Skype, @jonathanolson wrote:
[1/13/15, 12:35:50 PM] Jonathan Olson: Should I handle joist/ohtwo reformatting?
[1/13/15, 12:36:29 PM] Chris Malley: if you don't mind. i'm not clear on which branches of which repos are scheduled for merging into master.

I haven't checked joist/ohtwo, but joist/master is definitely not reformatted. Who is handling this? And what are the implications for merging ohtwo into master?

**Comment by jbphet** [comment]
Seeing some weirdness when reformatting SOM, see https://github.com/phetsims/states-of-matter/commit/75e7978c922687c8821f07fcbed7a0ced17ddcd2.  The behavior when making this reformatting change was quite odd.  When I reformatted the code using ctrl-alt-L, I got a bunch of changes.  When I went to commit them, they all went away.  When I turned off the "Reformat code" option, I could make the commit.  It was almost like it was using two slightly different code style files.  The commit seemed to align a bunch of things that we don't necessarily want aligned.

I discussed with with @pixelzoom over Skype, so he is familiar with the issue.

**Comment by pixelzoom** [comment]
More on the discussion with @jbphet ...

As I noted in my evaluation, IntelliJ 14 seems to be trying to do some left-justification of property values, as in this example from build-an-atom.ChargeComparisonDisplay. The value of the 'left' property is left-aligned with the value of the property immediately after it.

```js
+ var minusSymbolPath = new Path( minusSymbolShape, {
    stroke: 'black',
    lineWidth: 1,
    fill: 'rgb( 100, 100, 255 )',
    left:   INTER_SYMBOL_DISTANCE / 2,
    centerY: VERTICAL_INSET + SYMBOL_WIDTH * 1.5
  } );
```
If you put parentheses around ( INTER_SYMBOL_DISTANCE / 2 ), then the left-alignment is not done. So IntelliJ seems to be trying to do something clever, but not doing it well. And there doesn't appear to be a format setting for this.  So we should put together a small example and report this to JetBrains.

**Comment by pixelzoom** [comment]
Another issue with IDEA 14, not related to formatting. Paths in config.js files are being flagged with error: Cannot resolve file 'js'.  Here's a screenshot from molecule-polarity-config.js.

![screenshot_418](https://cloud.githubusercontent.com/assets/3046552/5785105/1f13bfae-9d90-11e4-9d91-64c95b281827.png)

**Comment by pixelzoom** [comment]
Decisions from 1/20/15 developer meeting:

• developers should feel free to reformat any code they come across that hasn't been reformatted
• it is preferable to reformat code as a separate step, rather than combining with other changes
• @pixelzoom will report the two IntelliJ 14 issues (identified above) to JetBrains

**Comment by pixelzoom** [comment]
The path issue in config.js files was reported to JetBrains here: https://youtrack.jetbrains.com/issue/IDEA-135446

**Comment by pixelzoom** [comment]
The left-alignment of property values was reported to JetBrains here: https://youtrack.jetbrains.com/issue/IDEA-135451

**Comment by pixelzoom** [comment]
The left-alignment of property values was reported to JetBrains here: https://youtrack.jetbrains.com/issue/IDEA-135451

Here's the example that I submitted:
```js
// Demonstrates left-alignment of values, not desired. How do we turn this off?
var foo = {
  x:         1 + 2,
  longitude: 3 + 4
};

// Demonstrates that parentheses disable the left-alignment. Why?...
var bar = {
  x: ( 1 + 2 ),
  longitude: 3 + 4
};
```

**Comment by pixelzoom** [comment]
JetBrains assigned both of the issues that I reported to developers. Forward progress...

**Comment by samreid** [comment]
Nice! :clap:

**Comment by pixelzoom** [comment]
IDEA 14.0.3 was released. It sadly does not contain fixes for the issues reported herein.

**Comment by pixelzoom** [comment]
No updated to the IDEA issues in JetBrains' tracking system. I'll leave this issue open and check periodically.

**Comment by pixelzoom** [comment]
No update to the IDEA issues in version 14.1, so I'm guessing it could be a long time before we see fixes.

**Comment by pixelzoom** [comment]
IntelliJ IDEA 14.1.1 released, no fix for these issues.

**Comment by pixelzoom** [comment]
IntelliJ IDEA 14.1.2 released, no fix for these issues.

**Comment by pixelzoom** [comment]
This issue is titled "Investigate IDEA 14 for development" and we've been using it successfully for a few months.  So I'm going to close this issue.  I'll track the reports to JetBrains using their issue system.
