### ISSUE TITLE
Add an option to stream scenery input events over iframe API

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#175]
Here's one way to add scenery input events to stream over the iframe API:

Add one line (marked as `// Send the events over the iframe` to Sim.js):

``` js
       if ( sim.options.recordInputEventLog ) {
          // push a frame entry into our inputEventLog
          var entry = {
            dt: dt,
            events: sim.scene.input.eventLog,
            id: sim.frameCounter,
            time: Date.now()
          };
          if ( !sim.inputEventBounds.equals( sim.scene.sceneBounds ) ) {
            sim.inputEventBounds = sim.scene.sceneBounds.copy();

            entry.width = sim.scene.sceneBounds.width;
            entry.height = sim.scene.sceneBounds.height;
          }
          sim.inputEventLog.push( entry );

          // Send the events over the iframe
          phetEvents && phetEvents.trigger( 'sceneryInputEvents', {sceneryInputEventLog: sim.scene.input.eventLog} );

          sim.scene.input.eventLog = []; // clears the event log so that future actions will fill it
        }
```

Add arch.js to the prelaunch, and launch the iframe sim with ?recordInputEventLog.  In the future, we may need a way to dynamically turn on the scenery input events (instead of with the query parameter as an up-front parameter) and it may be nice to interleave the scenery input events with the sim event stream (as parent events).

**Comment by samreid** [comment]
This will be a big next step for the together.js interoperability feature set.  I'm looking forward to working on it, but have many other things to do first.  Unassigning for now.  Others feel free to work on this if you get here first.

**Comment by pixelzoom** [comment]
@samreid Is this issue still relevant?

**Comment by samreid** [comment]
This feature is now supported by PhET-iO, closing.
