### ISSUE TITLE
Are we LTI compliant?

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#179]
This question came up at today's developer meeting, and @samreid volunteered to investigate.   Thanks, @samreid!

**Comment by samreid** [comment]
@ariel-phet any other investigation/discussion/work desired here?

**Comment by ariel-phet** [comment]
@samreid can you discuss with metacog and see if this is a feature that will be necessary in our future relationship with them? It seems one of the markets would be people accessing an enhanced sim from an LMS. If not, please close this issue, if so, please close this issue and create an LTI issue in the appropriate repository.

**Comment by samreid** [comment]
I emailed Doug Stein:

Doug,

For metacog's purposes, do you think it will be important to make our sims LTI compliant?  I'm not too familiar with LTI compliance or the ecosystem, but just wanted to see if it should be on my radar for the future.
http://www.imsglobal.org/toolsinteroperability2.cfm

Best Regards,
Sam

**Comment by samreid** [comment]
Response is in https://github.com/phetsims/special-ops/issues/2 @ariel-phet please review and let me know if you recommend further work on this issue.

**Comment by ariel-phet** [comment]
@samreid thanks for emailing Doug, his response certainly clarified the issue a bit. Seems like we are good on our side for the foreseeable future.
