### ISSUE TITLE
Review the SimIFrameAPI and sample usage

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#180]
At today's meeting, we agreed that @jonathanolson would review the SimIFrameAPI and its sample usage, and @samreid and @jonathanolson would iterate a bit before getting feedback from @pixelzoom.

I already added a protocol version and changed the messages to json, and this is ready for @jonathanolson's review.

Two issues we should look at in addition to the overall review:
1. Issue #175 regarding scenery event recording and possible integration with arch events
2. Looking at the molecule shapes iframe API and making sure they play nice together

**Comment by pixelzoom** [comment]
@samreid and @jonathanolson Is this issue still relevant?

**Comment by samreid** [comment]
@jonathanolson & I looked through SimIFrame API and we have moved relevant issues to together/arch my personal TODO list, etc.  Closing.
