### ISSUE TITLE
navbar and home screen layout are messed up due to dependencies on magic numbers

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#185]
In https://github.com/phetsims/joist/issues/126, ScreenView.DEFAULT_LAYOUT_BOUNDS was changed from (0,0,768,504) to (0,0,1024,618).  This exposed dependencies and assumptions elsewhere in joist about the layoutBounds. Many aspects of the home screen and navigation bar are affected, including:

• size of the navbar
• size of icons and labels
• spacing of icons and labels
• positioning of the PhET menu on the home screen

768, 504 and 40 (navbar height) appear in multiple places as magic numbers, with no association to  ScreenView.DEFAULT_LAYOUT_BOUNDS.  Font sizes also appear to have been selected based on these magic numbers, and will likely look smaller at the new DEFAULT_LAYOUT_BOUNDS. Here are some examples:

Sim:
> 518 //Use Mobile Safari layout bounds to size the home screen and navigation bar
> 519 var scale = Math.min( width / 768, height / 504 ); 
> 524  //40 px high on Mobile Safari
> 535 var navBarHeight = scale * 40;

NavigationBar:
> 35 this.navBarScale = 1;
> 36 this.navBarWidth = 768;
> 37 this.navBarHeight = 40;
> 50 this.titleLabel = new Text( sim.name, { font: new PhetFont( 18 ), pickable: false } );

**Comment by samreid** [comment]
I skimmed @pixelzoom change sets and tested a single-screen sim and a multi-screen sim and all seems good.  Closing.
