### ISSUE TITLE
Assertion is triggered when closing Dialog box from Close Button

### ISSUE THREAD

**Issue by bereaphysics** [phetsims/joist#187]
While working on getting a dialog box in least square regression, I noticed that the hasCloseButton in Dialog doesn't behave properly when one tries to close the Dialog box.

By default the AboutDialog bubble in Joist doesn't have a close button
```
    Dialog.call( this, content, {
      modal: true,
      hasCloseButton: false
    } ); 
```

To reproduce the issue,  set hasCloseButton to true, then open up the aboutDialog and click directly on the button to close the AboutDialog bubble, then an assertion is triggered.

**Comment by jonathanolson** [comment]
We're actually getting a new assertion (https://github.com/phetsims/joist/issues/199) from opening/closing the About dialog, but it's related to the PhetMenu.

Additionally, I have no trouble at all closing the AboutDialog with modal: false and hasCloseButton: true, so things may have changed since? Clicking the dialog body or close button works.

Since #199 may be hiding another exception, I'd opt to leave this issue open until we have no assertions failing related to the dialog.

**Comment by pixelzoom** [comment]
#199 is now closed, I don't see a dialog in least-squares-regression (other than About), and I can't reproduce this issue in other sims with dialogs (e.g. molecule-polarity).  

@bereaphysics can you verify? If it's no longer an issue, please close. Otherwise please enumerate steps to reproduce.

**Comment by bereaphysics** [comment]
Yes it is still present. The Dialog doesn't exist anymore in least squares regression but it can be reproduce in molecules-and-light which invokes Dialog in SpectrumWindows.js. (https://github.com/phetsims/molecules-and-light/blob/master/js/moleculesandlight/view/SpectrumWindow.js)

 
In SpectrumWindow.js, change line 473
hasCloseButton: false
 to
hasCloseButton: true, 

Run the sim and click on the 'Show Light Spectrum' . It should show a dialog with a close Button. Clicking directly on the CloseButton will trigger an assertion in Chrome.

**Comment by pixelzoom** [comment]
Would be good to fix the sim-specific problem (trying to hide twice).
How about also making Dialog.hide/show be no-ops if the dialog is already hidden/shown?

**Comment by jonathanolson** [comment]
> How about also making Dialog.hide/show be no-ops if the dialog is already hidden/shown?

Sorry, that's what I was trying to say with this:
> It sounds like Dialog should track whether it is shown, so that:
1. We don't hide it if it isn't shown.
2. We don't show it if it is already shown.

That would solve everything, since the SpectrumWindow listener is calling hide().

**Comment by pixelzoom** [comment]
Sounds good to me.

**Comment by jonathanolson** [comment]
@bereaphysics, can you verify that the change above fixed your issue?

**Comment by bereaphysics** [comment]
Yes it fixes it . closing
