### ISSUE TITLE
Adding Donate Now Button in "About" screen?

### ISSUE THREAD

**Issue by kdessau-PhET** [phetsims/joist#190]
In the HTML5 simulations, it would be good to add a Donate Now button in the About screen. People who actually are curious enough to go that screen would most likely donate. Page to link to is http://phet.colorado.edu/donate or https://donatenow.networkforgood.org/1437859

**Comment by ariel-phet** [comment]
@pixelzoom where is the appropriate place for this issue to live? We have been talking about some more changes to the about dialog?

**Comment by pixelzoom** [comment]
About dialog refinements are being tracked in https://github.com/phetsims/joist/issues/71. I've moved this request to that issue.
