### ISSUE TITLE
PhET Button sometimes disappears

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#191]
Chrome/OSX.  Try running Gravity and Orbits, then switch to a sim screen, then back to the home screen.  Voila!  The PhET button is gone!

**Comment by pixelzoom** [comment]
Version numbers? I'm running GAO master, and I don't see this on Mac OS 10.9.5 + Chrome 39.

**Comment by samreid** [comment]
Do you see the triple horizontal line get dimmer?

![image](https://cloud.githubusercontent.com/assets/679486/5750916/d0235b02-9c18-11e4-857b-2755601765e7.png)

**Comment by samreid** [comment]
The disappearing logo was happening with the phetsims/brand 'adapted-from-phet' branch--I think it was just using the black logo against the black background.

**Comment by samreid** [comment]
I do not see this problem in reactants-products-and-leftovers, perhaps it is related to the white navbar in gravity-and-orbits.

**Comment by samreid** [comment]
I'm on latest master branch of everything, on OSX 10.10.1 and Chrome Version 39.0.2171.95 (64-bit)

**Comment by pixelzoom** [comment]
@samreid asked:
> Do you see the triple horizontal line get dimmer?

Yes, with GAO master, Mac OS 10.9.5, Chrome 39.

**Comment by pixelzoom** [comment]
In GAO, the navbar background changes when switching between home and other screens. I'm guessing that the PhET menu is being modified once (when a screen is selected) to work on a white background, and then it no longer works on the home screens black background.  And if navbar background is screen-specific, then the PhET menu (screen icons? home icon?) needs to be modified every time you switch screens.

**Comment by pixelzoom** [comment]
Looking at joist code, I would expect GAO to be setting Sim.useInvertedColors = true.  But I don't find useInvertedColors in a search of GAO source. How is GOA requesting the inverted navbar?

**Comment by pixelzoom** [comment]
Ah, I see... useInvertedColors is annotated 'read-only' and is computed in Sim.js:

> if ( sim.currentScreen ) {
        sim.useInvertedColors = !!new Color( sim.currentScreen.backgroundColor ).equals( Color.BLACK );
      }

**Comment by pixelzoom** [comment]
Here's the bug, in PhetButton:

> Property.multilink( [this.interactionStateProperty, sim.useInvertedColorsProperty], function( interactionState, useInvertedColors ) {
      optionsButton.fill = useInvertedColors ? '#222' : 'white';
      phetLabel.image = useInvertedColors ? phetLogoDarker : phetLogo;
    } );

This code isn't taking into account whether we're on the home screen or some other screen. (It's also ignoring the interactionState, which makes me wonder why it's linking to it.)

**Comment by pixelzoom** [comment]
Proposed fix:

```js
Property.multilink( [ sim.useInvertedColorsProperty, sim.simModel.showHomeScreenProperty ], function( useInvertedColors, showHomeScreen ) {
      optionsButton.fill = ( useInvertedColors && !showHomeScreen ) ? '#222' : 'white';
      phetLabel.image = ( useInvertedColors && !showHomeScreen ) ? phetLogoDarker : phetLogo;
    } );
```

**Comment by pixelzoom** [comment]
Btw... The above proposed fix looks (to me) like it resolved this issue. But looking through the joist code, the way that this 'inversion' is handled, and the API for it, is a bit of a mess. There's a lot of coupling that shouldn't be there, there are undocumented assumptions, and the API allows clients to do things that they shouldn't be able to do.

**Comment by jonathanolson** [comment]
My recollection is that each screen has a background color which determines if the colors are inverted (not done on a whole-dim level).

**Comment by samreid** [comment]
I also think it will be important to rename useInvertedColorsProperty to something more straightforward like navbarFillProperty.  I'm sort of holding off on issues like this until we switch to ohtwo.

**Comment by pixelzoom** [comment]
> I also think it will be important to rename useInvertedColorsProperty

Agreed. That name is overly general for what it does.

**Comment by pixelzoom** [comment]
> I'm sort of holding off on issues like this until we switch to ohtwo.

Double agreed.

**Comment by pixelzoom** [comment]
This is still a bug, fix I proposed (https://github.com/phetsims/joist/issues/191#issuecomment-70032224) has not been implemented.

**Comment by pixelzoom** [comment]
Color-inversion issues moved to https://github.com/phetsims/joist/issues/222.

**Comment by pixelzoom** [comment]
I'm going to implement the fix that I proposed. gravity-and-orbits is broken (see https://github.com/phetsims/gravity-and-orbits/issues/139) so I can't test there.  But molecule-shapes exhibits this same problem, so I'll use that to verify.

**Comment by pixelzoom** [comment]
Fixed as proposed. Assign to @jonathanolson to verify.  You can verify using 1 sim that has an inverted navbar (e.g.  molecule-shapes) and one that has a black navbar (e.g. RPAL).

**Comment by jonathanolson** [comment]
Looks good, tested on Molecule Shapes (both color modes) and RPAL. Thanks!

**Comment by jonathanolson** [comment]
Also a note that it's a bit weird that the currentScreen isn't some sort of home screen (as the HomeScreen is a ScreenView).

**Comment by pixelzoom** [comment]
Bothers me too, and doesn't seem to be any good read for the bogus naming. Noted in https://github.com/phetsims/joist/issues/224.
