### ISSUE TITLE
what is the optimal size for navigation bar icons?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#192]
Screen.js documentation says 147x100:

> 33 navigationBarIcon: homeScreenIcon // must be a minimum of 147x100 and have an aspect ratio of 548/373=1.469.  See https://github.com/phetsims/joist/issues/76

But if I add this console.log to NavigationBarScreenButton.js, then I see 36.75x25.

> 34 var icon = new Node( {children: [screen.navigationBarIcon], scale: ( 0.625 \* navBarHeight ) / screen.navigationBarIcon.height} );
> 35 console.log( icon.width + 'x' + icon.height );

I've typically been adding navbar-specific images files when Firefox mangles the home-screen image files (e.g., https://github.com/phetsims/reactants-products-and-leftovers/issues/28). But I've been sizing them to 147x100. Which means that they are still being downscaled by ~4x.  And this is undoubtedly making them look somewhat lousy.

Is there any reason why we shouldn't be creation navbar-specific image files with size 37x25? Or something that is a little closer to 37x25?

**Comment by pixelzoom** [comment]
In  phetsims/reactants-products-and-leftovers#28, I confirmed that a 147x100 navbar image still looks a bit mangled in Win+Firefox.  If I reduce the size to 38x26 it looks nice. Even 70x48 looks good - probably because Firefox is only scaling down by ~2x.   So I suspect that our navbar-specific images have been looking lousy because they are too large.

**Comment by jonathanolson** [comment]
I just checked the displayed size of the navbar icon on my screen (81x56), and presumably on a retina device it could be ballpark ~160x110. Reducing to anything near 38x26 sounds like it would introduce a ton of blur on higher-resolution devices.

I'd rather solve this at the Scenery level (with a flag indicating that Scenery should be responsible for re-rasterizing images to best fit the display) rather than handicapping the resolution. If this sounds acceptable, I can create an issue (I didn't see an issue specific to image resolution).

**Comment by pixelzoom** [comment]
Ah, forgot about retina. Too bad, because I had phetsims/reactants-products-and-leftovers#28 looking great, guess I need to reopen it.  This needs to be completed for RPAL publication, and I guess my only choice is to leave it looking "sort of lousy" on Win+Firefox.

**Comment by pixelzoom** [comment]
@jonathanolson wrote:
> I just checked the displayed size of the navbar icon on my screen (81x56), and presumably on a retina device it could be ballpark ~160x110.

Which sim? I checked multiple sims on non-retina, and icons were all 36.75x25.

If retina requires ~160x110, why is 147x100 specified in Screen.js?

**Comment by samreid** [comment]
What is your screen size?  What is the maximum screen resolution we will want to support (including retina)?  How do the icons look if they are upscaled instead of downscaled?  As one data point, on iPad3, the screen icons are coming up as 98x67px.

**Comment by jonathanolson** [comment]
98x67px (CSS 'px') => 196x134 actual pixels?

**Comment by samreid** [comment]
> 98x67px (CSS 'px') => 196x134 actual pixels?

I was using photoshop to count pixels from a screenshot, so I think it was 98x67 actual pixels (if I am using the term pixels right?)

**Comment by pixelzoom** [comment]
Screen defines MINIMUM_NAVBAR_ICON_SIZE, and we've been using it without issue:

```js
29 var MINIMUM_NAVBAR_ICON_SIZE = new Dimension2( 147, 100 );
```

Closing.
