### ISSUE TITLE
Close the PhETMenu before invoking its action

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#195]
Currently PhETMenu has this code for invoking the action of one of its buttons:

```js
    var fire = function( event ) {
      callback( event );
      closeCallback( event );
    };
```

However, this is causing complication for keyboard accessibility in the case of the AboutDialog, because it creates a new focus context (the AboutDialog) then dismisses the previous focusContext (the AboutDialog).  Focus contexts are being designed as a stack, so it doesn't work to create push a new context then pop a *different* context.  This problem would be resolved if the closeCallback was called before the callback.  I don't think this will cause any problems but wanted to document it and make sure it is sufficiently reviewed.

**Comment by samreid** [comment]
I tested it a bit (OSX/Chrome only with a few menu item options) with the reversed order and did not see any problems.  Broader testing and review is warranted.

**Comment by pixelzoom** [comment]
I checked a few sims and don't see any problems. Closing.
