### ISSUE TITLE
Added ?cacheBuster=false option to sims

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#196]
At today's developer meeting, we decided to add a ?cacheBuster=false option to all simulations.  This would disable the cache buster in sims to improve interoperability with chrome dev tools (which get confused when there are query parameters).

We should also document the new query parameter.

**Comment by samreid** [comment]
Here is the snippet of code I am planning to add to each simulation's config file:

```js
  // add cache buster query string to make browser refresh actually reloads everything, or disable with ?cacheBuster=false
  // see https://github.com/phetsims/joist/issues/196
  urlArgs: (phetcommon.getQueryParameter( 'cacheBuster' ) !== 'false') ? ('bust=' + Date.now()) : ''
```

**Comment by samreid** [comment]
Can I get a quick microreview of the snippet above before I apply it everywhere @jonathanolson @pixelzoom or @jbphet?  There are a few ways this could have been done, just wanted to get confirmation from someone before I spend time propagating this around.

**Comment by pixelzoom** [comment]
The snippet being replaced is:

> urlArgs: new Date().getTime()

Why is 'bust=' being added?

Does it need to be *new* Date().getTime() ?

I'd prefer to see window.phetcommon.getQueryParameter.

**Comment by samreid** [comment]
> Why is 'bust=' being added?

This seems more conventional, see http://requirejs.org/docs/api.html#config-urlArgs and http://stackoverflow.com/questions/8315088/prevent-requirejs-from-caching-required-scripts

> Does it need to be new Date().getTime() ?
Date.now() is a nickname for "new Date().getTime()" starting in ES5 and is supported across our platforms.  See:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now

> I'd prefer to see window.phetcommon.getQueryParameter.

Why?  If there are problems here, should we be using `window.` in many other places as well?  Are there places where `window.` should be/can safely be omitted?

**Comment by pixelzoom** [comment]
> Why? If there are problems here, should we be using window. in many other places as well? Are there places where window. should be/can safely be omitted?

Mainly for consistency with other PhET code. query-parameter.js uses `window.phetcommon` throughout. Scenery uses `window.` throughout when referring to globals.  And I've tried to stick to that same convention. I'd like to hear @jonathanolson's opinion.

**Comment by samreid** [comment]
@pixelzoom I believe this issue is subsumed by your work in https://github.com/phetsims/tasks/issues/160.  If true, can this issue be closed?

**Comment by jonathanolson** [comment]
Review looks fine, I believe window.* is already handled like @samreid mentioned.

I usually just see ?\<number\>, but I don't mind "bust=".

**Comment by pixelzoom** [comment]
The issue of phet.phetcommon.getQueryParameter is indeed resolved by phetsims/tasks#160.   But I don't see urlArgs changed in any config.js files.  So no, this issue cannot be closed.

**Comment by samreid** [comment]
One more question: should we factor out this logic?  So instead of reading:

```js
urlArgs: (phetcommon.getQueryParameter( 'cacheBuster' ) !== 'false') ? ('bust=' + Date.now()) : ''
```

it would read

```js
urlArgs: phetcommon.getCacheBusterArgs()
```

With `getCacheBusterArgs` implemented appropriatel?

**Comment by jonathanolson** [comment]
That sounds nice to me.

**Comment by samreid** [comment]
I added `getCacheBusterArgs` above--wasn't sure if there is a better place for it than query-parameters.js.

Next it needs to be referenced in all config files.

**Comment by samreid** [comment]
Getting this error after testing the above:

> Error: Error: The config in mainConfigFile /Users/samreid/github/reactants-products-and-leftovers/js/reactants-products-and-leftovers-config.js cannot be used because it cannot be evaluated correctly while running in the optimizer. Try only using a config that is also valid JSON, or do not use mainConfigFile and instead copy the config values needed into a build file or command line arguments given to the optimizer.
> Source error from parsing: /Users/samreid/github/reactants-products-and-leftovers/js/reactants-products-and-leftovers-config.js: TypeError: Cannot call method 'getCacheBusterArgs' of undefined

**Comment by jonathanolson** [comment]
Presumably Node.js will need to be able to execute getCacheBusterArgs, from wherever it is defined (so we shouldn't rely on the existence of 'window' for it).

**Comment by samreid** [comment]
OK I'll add stubs for Gruntfile.js and commit everything.

**Comment by samreid** [comment]
I'll skip scenery/dot/kite since they are trying to be phetcommon agnostic, non?

**Comment by samreid** [comment]
Committed above, would be good for @pixelzoom or @jonathanolson to spot test at least.

**Comment by pixelzoom** [comment]
The first 3 sims I tried (RPAL, BAM, SOMB) have not been updated. Assigning back to @samreid.

**Comment by pixelzoom** [comment]
The following sims haven't been updated:

BAM
faraday
molecule-shapes
plinko
protein-synthesis
RPAL
resistance-in-a-wire
seasons
smorgasboard
SOMB
SOM
SASS
under-pressure
WOAS

**Comment by pixelzoom** [comment]
What should we do about non-sim repos that have cache busting in their config.js?  Leave it as the old-style? Remove it?...

**Comment by samreid** [comment]
How are you determining the list of sims that haven't been updated?  Checking BAM, I see 

```js
  // optional cache buster to make browser refresh load all included scripts, can be disabled with ?cacheBuster=false
  urlArgs: phet.phetcommon.getCacheBusterArgs()
```
in the config file, so it looks like it was updated.  Faraday also has this.  What am I missing?

**Comment by pixelzoom** [comment]
Do a search in all .js code for "urlArgs: new".  A couple of them are `*-dev-config.js`, but I don't see any reason why those shouldn't be changed too.

**Comment by jonathanolson** [comment]
The *-dev-config.js files should be changed also.

**Comment by samreid** [comment]
Ah, I see a problem.  Some of my original work didn't get pushed.  Should be pushed now.

**Comment by samreid** [comment]
@jonathanolson if you *don't* want this in any scenery/dot/kite files please check on them and make sure they are as you desire.

**Comment by jonathanolson** [comment]
Are there any thoughts on moving that to chipper? Otherwise I'll want to revert repos (like Scenery) that don't depend on phetcommon (see https://github.com/phetsims/scenery/issues/380).

I think we also discussed moving preloads to chipper, which would simplify this significantly. Opinions from @samreid @jbphet @pixelzoom?

**Comment by pixelzoom** [comment]
Since it's defined in query-parameters.js, I believe that it's moving to chipper, see https://github.com/phetsims/phetcommon/issues/23.

**Comment by samreid** [comment]
I've moved it to chipper in the issue @pixelzoom mentioned.

**Comment by pixelzoom** [comment]
@samreid @jonathanolson I can't tell if there's anything left to do in this issue, or if it can be closed. Can either of you please clarify?  If there's remaining work, please summarize. Thanks.

**Comment by jonathanolson** [comment]
I believe the sim work is done. I can't move certain common repos over to use it (see https://github.com/phetsims/scenery/issues/380), but it can live in that issue, so I'll close here.
