### ISSUE TITLE
Opening about dialog fires assertion in Input.popFocusContext

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#199]
Screenshot of the assertion:
![joist-about-assertion](https://cloud.githubusercontent.com/assets/480878/5954234/1884838c-a752-11e4-8d1e-65977ed5f445.png)

To reproduce, open any sim => PhET Menu => About...

Here's my guess after a very brief look:
1. We pushFocusContext with the PhetMenu's instance after it is opened
2. Click comes in to About..., which removes the PhETMenu from the scene graph.
3. In animationLoop, display.updateDisplay() happens, removing the instance attached to PhetMenu
4. We try to access the PhetMenu's instance in Sim.hidePopup(), which now doesn't exist.

I also think this is a symptom of tracking focused Instances, and I'd like to move to have a focusedTrail instead (especially since we don't seem to be storing information on the instance itself?)

**Comment by samreid** [comment]
@jonathanolson & I should discuss using trails instead of instances for accessibility

**Comment by samreid** [comment]
Was this fixed by phetsims/scenery#369 ?

**Comment by jonathanolson** [comment]
Yes, this is now fixed. Thanks!
