### ISSUE TITLE
webglContextLossTimeout query param causes fatal error

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#203]
Related to https://github.com/phetsims/joist/issues/202

When run with '?webglContextLossTimeout=1', this line fails in Sim.js:

> 286  sim.scene.simulateWebGLContextLoss();

The console error is:

> Uncaught TypeError: undefined is not a function

... where undefined is referring to simulateWebGLContextLoss.

The problem is that Scenery 0.2 no longer has a Scene, and Sim.js replaced it with Node.

**Comment by pixelzoom** [comment]
timeout to call scene.simulateWebGLContextLoss is called on line 286.
scene is created on line 302.
That seems a bit unwise.

**Comment by samreid** [comment]
Context loss handling was handled nicely in webgl-0.1.  Not supported yet in webgl-0.2 (a rewrite with very different strategies).  These flags should be removed or documented as such.

**Comment by samreid** [comment]
I removed the context loss handling hooks since this is not supported in the new higher performance webgl module.  Once it is introduced, we will probably need to add back similar testing harnesses.
