### ISSUE TITLE
document makeEverythingSlow and makeRandomSlowness

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#204]
Globals window.phet.joist.makeEverythingSlow and window.phet.joist.makeRandomSlowness are defined in Sim.js. They have no documentation and don't appear in any other .js or .html files. Please document what they are used for.  And do they below in Sim.js?

**Comment by jonathanolson** [comment]
First of all, they are used to make sure our sims still behave properly with an artificially higher load (so I can test what happens on desktop at 30fps, 5fps, etc). There tend to be bugs that only happen on less powerful devices, and I added that to both test a sim for robustness, and to allow others (MLL notably has needed to use it for WOAS and another sim) to reproduce the slow behavior bugs.

I don't have any major preferences on where they live. Let me know if Sim.js is best or if they should live somewhere else, and I can document them. Even better, should we replace it with query parameters in a tunable way?

**Comment by pixelzoom** [comment]
Thanks, that's helpful. Would you mind if I document them?

**Comment by jonathanolson** [comment]
I don't mind at all. Randomness is needed to reproduce bugs that happen when DTs are wildly different, the other one is just constant slowing.

**Comment by pixelzoom** [comment]
Documented in https://github.com/phetsims/joist/commit/abe5282f8cac081fc6fbb1fa2a134d7c874fd98a. I 'd like to see these move elsewhere, but that's true for a lot of other stuff in Sim.js.  So I'll wait and address that in https://github.com/phetsims/joist/issues/208.
