### ISSUE TITLE
delete Sim options showScreenshotOption and showFullscreenOption

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#206]
These appear to be standard features now, and their associated query parameters were commented out. So the options should be deleted, yes?

**Comment by jonathanolson** [comment]
I guess it's more of a question of whether we want the ability to disable them on a per-sim basis. I have no problem with removing the options so they are 'always-on'.

**Comment by samreid** [comment]
Yes, let's aim for "always on", and remove the options.

**Comment by ariel-phet** [comment]
I am not quite sure why these were aimed for "always on" without more discussion. These were "experimental" features that need to be:

1. Tested thoroughly
2. Decide exactly how the UI should work. I am not sure these should be in the PhET menu

It seems we should discuss in developer meeting, but whoever is the right person please put these to "always-off" and perhaps a query parameter that can be used to access they features so we can test them and make some design decisions about them.

**Comment by pixelzoom** [comment]
I had the same questions. 

I changed them to be "always off" and restored query parameters that were deleted in the move to joist 0.2. See https://github.com/phetsims/joist/issues/213.

Closing.
