### ISSUE TITLE
Can we remove ?standalone   ?

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#211]
The ?standalone query parameter just launches the sim with a single screen.  However, a newer query parameter ?screens=... allows this with much more flexibility.  I recommend we remove ?standalone.  Any reasons not to do so, @pixelzoom @jbphet or @jonathanolson?

**Comment by samreid** [comment]
Same question for screenIndex.  Since this is public facing, I think using the 1-indexed ?screens seems better.

**Comment by pixelzoom** [comment]
Sounds good to me. I've removed screenIndex from my code, and I've never used standalone.

**Comment by jonathanolson** [comment]
Sounds good to me.

**Comment by samreid** [comment]
Removed both above.  Closing.
