### ISSUE TITLE
screenshot feature on IE9 ?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#212]
joist.PhetMenu disables the 'Screenshot' feature for IE9, see:

> 257 present: !Platform.ie9,

Is this the longterm plan or a temporary issue? No clues in the code.

**Comment by samreid** [comment]
I have no idea, I'll ask @jonathanolson, the primary developer for the screenshot feature.

**Comment by pixelzoom** [comment]
Also... This comment in PhET menu should be deleted, no?

> 254 //Feasibility test for capturing screen shots as images

**Comment by ariel-phet** [comment]
I believe the screenshot feature is now in the wheelhouse of PhET-iO - can you comment on or close this issue @samreid

**Comment by samreid** [comment]
At our last discussion we still wanted to publish a "Screenshot" button in the PhET Menu, but it is currently buried behind a ?screenshot query parameter.  I don't recall why it is behind a query parameter, perhaps @jonathanolson does?

**Comment by jonathanolson** [comment]
It was in a "wait for design, since we may integrate it into the navbar or do something else" state.

@ariel-phet would presumably know if this has changed.

**Comment by ariel-phet** [comment]
Perhaps this is a question for @kathy-phet ...she might want the screenshot feature only available in iO sims. Since the webgl issues have not been all figured out and tested, we certainly should not be shipping it as a feature yet.

It is true we had discusses integrating the screenshot feature into the navibar, but for the moment, I think we were all OK with having it in the menu. The navbar integration causes many potential issues, especially with the limited real estate, so it does not seem worth pursuing at the moment. 

Marking for status meeting to see what @kathy-phet thinks

**Comment by samreid** [comment]
@kathy-phet said she is OK to put the screenshot feature into the phet.colorado.edu sims, though not at high priority.  Higher priority is for @jonathanolson and @samreid to make sure the BrainPop simulations can export screenshots even if WebGL is running:

Color Vision
Concentration
Molecules and Light
Balancing Act
Graphing Lines
Wave on a String
Energy Skate Park: Basics
Arithmetic

**Comment by jonathanolson** [comment]
Is pending on WebGL support, see https://github.com/phetsims/scenery/issues/308.

**Comment by jonathanolson** [comment]
I believe I've handled all of the screenshot-related issues (and https://github.com/phetsims/joist/issues/286 sufficiently?), so I've enabled it by default in the menu.

@ariel-phet, do we want to do additional testing now, or wait for an RC?

**Comment by ariel-phet** [comment]
@jonathanolson probably good to do some preliminary testing. Please create a task and assign to me with some relevant details. I imagine testing could be done from sims on phettest? And we could try a few cases (such as ESPB and other known ones?).

**Comment by jonathanolson** [comment]
Added task in https://github.com/phetsims/tasks/issues/556. Anything else I should do for this issue for now?

**Comment by ariel-phet** [comment]
I think nothing else until testing finishes.

**Comment by ariel-phet** [comment]
We no longer support IE9 closing
