### ISSUE TITLE
Arch fallback global is defined too late in the loading process

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#214]
Molecule Shapes: Basics will fail when it tries to load (or from a built version) because window.arch is set in SimLauncher (in require.js), and properties / propertysets can be created/used before then (in any require.js dependency).

We need to decide on where to handle namespaces in general.

**Comment by samreid** [comment]
Proposed solution committed above.  I also need to add check-arch to all preload matter.

**Comment by samreid** [comment]
I added the preloads above.  Also, I noticed that about half of the sim html had google-analytics--I removed them (and added this for discussion agenda).  I also removed check-accessibility.js in the above commits, where I saw it.

**Comment by samreid** [comment]
This work also prompted this issue:
https://github.com/phetsims/phetcommon/issues/23

**Comment by samreid** [comment]
Reassigned to @jonathanolson to make sure molecule-shapes is good to go, and for discussion.

**Comment by jonathanolson** [comment]
Molecule Shapes is working well, thanks!
