### ISSUE TITLE
Mouse Scrolling moves the screen view and the joist menu in Chrome

### ISSUE THREAD

**Issue by bereaphysics** [phetsims/joist#217]
In Chrome version 40.0.2214.111  (windows 7), it is possible to use the  mouse scroll to move the joist menu. This seems particular to this version of chrome, chrome 42 and firefox are fine. To reproduce place a charge (in charges and fields) on the board and generate an equipotential line that extends beyond the screenview. You should be able to use the mouse scroll to get in the state below.  

 
![joist_issue](https://cloud.githubusercontent.com/assets/7633344/6152333/8126bcc0-b1d9-11e4-9018-9e5cd56d53fe.PNG)

**Comment by bereaphysics** [comment]
I note in passing that is not unique to Charges and fields. Using the scroll button in Least squares regression and Blackbody spectrum, there is a noticable shift in the screenview and joist menu

**Comment by jonathanolson** [comment]
Scenery should be calling preventDefault() on mouse scrolls, but I'll check into it since this doesn't seem to occur in Scenery 0.1

**Comment by bereaphysics** [comment]
For your information, I tested IE-11 as well. No issue with IE. Right now, it is only possible to reproduce this issue with a particular version of chrome.

**Comment by jonathanolson** [comment]
@bereaphysics, can you pull the latest Scenery and test? I believe it's fixed.

**Comment by bereaphysics** [comment]
Thank @jonathanolson . That fixes it. Closing
