### ISSUE TITLE
In IE-11, the bubble menu is very large

### ISSUE THREAD

**Issue by bereaphysics** [phetsims/joist#218]
![image](https://cloud.githubusercontent.com/assets/7633344/6152608/c6f3d4de-b1db-11e4-8867-761906c36693.png)

This affects all sims. Firefox and chrome dont display this behavior

**Comment by pixelzoom** [comment]
Which version of Windows and which specific version of IE11?
I don't see this issue with master on Win7 + IE 11.0.9600.17420.

**Comment by bereaphysics** [comment]
This is from Master and running the requireJS. I have a similar issue when running least squares regression.

Name: Least-Squares Regression

URL: http://localhost:63342/phetsims/least-squares-regression/least-squares-regression_en.html?dev&ea

Version: 1.0.0-dev.6

Features missing: touch, fullscreen

Flags: pointerEnabled, msPointerEnabled, pixelRatioScaling

User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; rv:11.0) like Gecko

Language: en-US

Window: 128x68

Pixel Ratio: 10/1

WebGL: WebGL 0.94

GLSL: WebGL GLSL ES 0.94

Vendor: Microsoft (Internet Explorer)

Vertex: attribs: 16 varying: 15 uniform: 512

Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)

Max viewport: 16384x16384

OES_texture_float: true

**Comment by jonathanolson** [comment]
I'm also unable to reproduce, unless I change my zoom settings. Can you see if your zoom is at 100%?

**Comment by bereaphysics** [comment]
You are correct @jonathanolson. It has to do with with amount of zoom. I must have changed the zoom factor accidentally. It behaves fine if the zoom is at 100%.

**Comment by jonathanolson** [comment]
It looks like the PhetMenu doesn't resize with the rest of the sim - presumably it should? I'll create an issue for it.

**Comment by bereaphysics** [comment]
Upon inspection, this issue is not proper to IE but present across all browsers. It has to do with the zoom being a very large.  Only PhetMenu is affected by the zoom. This is better adressed in #219, so closing.
