### ISSUE TITLE
PhetMenu isn't scaled the same way sims are?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#219]
Seems like it would be nice to have it scale with the sim, so it's not ridiculously big on small resolutions, or ridiculously small on high resolutions.

Also would prevent https://github.com/phetsims/joist/issues/218

**Comment by samreid** [comment]
@aaronsamuel137, could you investigate this?

**Comment by aaronsamuel137** [comment]
I'm noticing that this doesn't happen in older published sims, such as the deploy version of color-vision.

**Comment by aaronsamuel137** [comment]
Actually, it does happen, it just won't resize dynamically as you zoom the browser, it will only take effect after closing the bubble and opening it again. In current master, it will rescale as you're zooming.

**Comment by samreid** [comment]
@aaronsamuel137 & I looked into this and discovered the problem.  The Sim.topLayer wasn't being scaled and hence none of the dialogs were being scaled by default.  We decided to add scaling to Sim.topLayer.  Content (including dialogs) will be automatically resized, but they will have to update their own location, accounting for the new scale factor.

We fixed occurrences we saw in Joist, including the PhET popup menu and about dialog.  We also fixed an occurrence in Molecules & Light.  We tested that Molecule Shapes's Options dialog is still working properly.  Will commit shortly.

**Comment by samreid** [comment]
@aaronsamuel137 & I pushed fixes above.  Reassigning to @pixelzoom, @jonathanolson or @jbphet to review our changes.

**Comment by pixelzoom** [comment]
Will all Options dialogs behave properly?

**Comment by samreid** [comment]
Not if they provide a broken `layoutStrategy`

**Comment by pixelzoom** [comment]
Tested About and Options dialogs in Molecule Polarity, and all seems well. But I have never experienced this issue firsthand, so I'm not confident that I'm testing correctly. Who initially reported this problem? Perhaps it would be best to have that person verify.

**Comment by samreid** [comment]
Looks like @phetsims/bereaphysics noticed this in #218.  Martin, can you take a look?

**Comment by samreid** [comment]
By the way @pixelzoom you can see the problem by launching http://phet.colorado.edu/sims/html/reactants-products-and-leftovers/latest/reactants-products-and-leftovers_en.html pressing the PhET button and then pressing CMD+ and CMD-

**Comment by pixelzoom** [comment]
That's not what I tested, and I never would have guessed to do that. That behavior does appear to be corrected by the fix.

**Comment by bereaphysics** [comment]
I've tested it across all the browsers. That fixes it. Thanks. Closing
