### ISSUE TITLE
rootRenderer query parameter

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#221]
This will override the scenery renderer for Sim.rootNode.

3/3/15 developer meeting notes:

SR: use joistRenderer=... as a query parameter?

JO: This would be helpful for me

CM: Do you want the query parameter to override the sim? It currently does not in some cases, eg new Sim(..., { joistRenderer: ‘svg’ } )

SR: example: ScreenView.call( this, { renderer: Sim.joistRenderer, layoutBounds: ForcesAndMotionBasicsLayoutBounds } );

SR: rootRenderer?  Default would be 'svg'.

CM: Query parameter overrides the sim.

Defaults to 'svg' (specified in Joist).  Overriden by options.rootRenderer in Sim constructor call.  That is also overriden by rootRenderer query parameter.

Iterate through all ScreenViews and remove renderer specifications? (Yes)

CM: Get rid of this in Sim.js too:  var renderers = [ 'null', 'svg', 'canvas', 'webgl', 'dom', 'pixi' ];
No validation in joist, scenery already handles validation.

SR Will do this one.

**Comment by samreid** [comment]
I replaced joistRenderer with rootRenderer above.  Next, I will look for renderer:'svg' on screen views and remove them.

**Comment by samreid** [comment]
OK I removed renderer:'svg' from all of the ScreenViews that I could find and opened related issue #225.  Can @jbphet @jonathanolson or @pixelzoom take a look at what's been done here?

**Comment by pixelzoom** [comment]
This logic is incorrect, the query parameter should override all other settings (default and options). It's also preferable to set the default ('svg') in the default options.

Checked in fix above, @samreid please review. 

```js
    // Choose a renderer for the joist components such as HomeScreen, NavigationBar, etc.
    // options.rootRenderer overrides the query parameter, see #221 and #184
    var rootRenderer = options.rootRenderer ||
                       phet.chipper.getQueryParameter( 'rootRenderer' ) ||
                       'svg';
```

**Comment by pixelzoom** [comment]
Reviewed the changes to my sims and tested a few, looks good.

**Comment by samreid** [comment]
The logic fix seems good, thanks for your review.  Closing.
