### ISSUE TITLE
Sim is responsible for adding critical Screen properties

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#223]
While reviewing the `together` repo, I wondered about this bit of code in joist.Screen:

```js
  getAPI: function( route ) {
      return {
        model: this.model.getAPI( route + '.model' ),
        view: this.view.getAPI( route + '.view' )
      };
    }
```

Screen's constructor shows no this.model or this.view.

Hours later, I stumbled across this in Sim.js while working on a joist issue:

```js
409      screen.model = screen.createModel();
412      screen.view = screen.createView( screen.model );
```

It seems very odd (ok, wrong) that Screen isn't handling this in its constructor, and that Sim is responsible for adding these crucial fields.  Any instance of Screen is broken after construction.

This is probably being done this way to prevent model/view initialization in the case where the 'screens' query parameter omits a Screen.  But I don't think the benefit is justified.

**Comment by samreid** [comment]
Screen arguments are createModel, createView to give us flexibility for loading.

> This is probably being done this way to prevent model/view initialization in the case where the 'screens' query parameter omits a Screen.

Yes, that is one benefit, but could be handled elsewhere (say if Sim's constructor is redesigned to be given an array of createScreen functions).  But generally it was designed this way so that we could control when loading occurs--for instance, if we have a 4-screen simulation, then we could show a loading bar that is broken into 8 steps (model + view for each screen).

Would creating null fields in Screen.js, documenting them, and providing methods on Screen.js API for filling them in at the appropriate time solve the problem?

**Comment by samreid** [comment]
One more point: I am not interested in making sims launch more slowly when using the ?screens parameter--that has been very nice for iteration during development of many projects.

**Comment by pixelzoom** [comment]
Not a fan of objects that are broken after construction, that typically indicates a design problem, and Sim/ScreenView are too foundational for that. How about a design that defers instantiation of ScreenViews until they are needed?

**Comment by pixelzoom** [comment]
Defining the fields in ScreenView would be much better than having part of its API definition hidden in Sim.  But I'm not a fan of objects that are broken after construction, that typically indicates a design problem, and Sim/ScreenView are too foundational for that. How about a design that defers instantiation of ScreenViews until they are needed?

**Comment by pixelzoom** [comment]
A few brainstorming ideas, based on reactants-products-and-leftovers-main.js ...  

```js
// what we have now - array of partially-constructed ScreenView instances
new Sim( title, [ new SandwichesScreen(), new MoleculesScreen(), new GameScreen() ], ...)

// array of zero-arg ScreenView constructors, would require ScreenView sub typing
new Sim( title, [ SandwichesScreen, MoleculesScreen, GameScreen ], ... )

// array of functions that return {ScreenView}, would support inlining style 
new Sim( title, [ 
   function() { return new SandwichesScreen() },
   function() { return new MoleculesScreen() },
   function() { return new GameScreen() }
], ...)

```
 Hmm... But looking at ForcesAndMotionBasicsSim, none of the above may work, looks like `together` API is going to require a Sim subtype with a field for each ScreenView.

**Comment by samreid** [comment]
I presume that every occurrence of ScreenView in the above comment should be Screen, please correct me if I misunderstood.

**Comment by pixelzoom** [comment]
Yes, ScreenView should have been Screen. But one can never be sure (https://github.com/phetsims/joist/issues/224). Fixed in above examples.

**Comment by samreid** [comment]
I investigated this strategy:

```js
  return inherit( PropertySet, Screen, {
    get model() {
      if ( this._model === null ) {
        this._model = this.createModel();
      }
      return this._model;
    },

    get view() {
      if ( this._view === null ) {
        this._view = this.createView( this.model );

        // Show the screen's layoutBounds
        if ( phet.chipper.getQueryParameter( 'dev' ) ) {
          this._view.addChild( devCreateLayoutBoundsNode( this._view.layoutBounds ) );
        }
      }
      return this._view;
    },

    getAPI: function( route ) {
      return {
        model: this.model.getAPI( route + '.model' ),
        view: this.view.getAPI( route + '.view' )
      };
    }
  } );
```

But it seems too risky since it does not make the model + view construction time explicit--may get done lazily right when clicking on a homescreen icon which would cause a major lag.

**Comment by samreid** [comment]
It would be good to get @jonathanolson @jbphet @aaronsamuel137 thoughts on this matter.

**Comment by jbphet** [comment]
IMO, the benefits of faster single screen init and the possibility of a stepping loading bar are worth a bit of trouble.  My general inclination would be to have the screens construct themselves with the values set to null or some other reasonable values that will not cause badness if accessed by the framework without initialization.  Also, it would be more "framework-ish" if the framework expected the Screen instances to implement methods that were called during initialization, such as initializeModel and initializeView, and called those methods during startup.

**Comment by pixelzoom** [comment]
How about this pattern for Screen? It makes Screen responsible from model and view creation, and performs that creation on demand. 

```js
function Screen( name, homeScreenIcon, createModel, createView, options ) {
  //...
  this.createModel = createModel; // @private
  this.createView = createView; // @private
  this._model = null; // @private, initialized on demand by ES5 getter
  this._view = null; // @private, initialized on demand by ES5 getter
}

inherit( PropertySet, Screen, {
  //...

  // Gets the Screen's model, created on demand.
  getModel: function() {
    if ( !this._model ) { this._model = this.createModel(); }
    return this._model;
  },
  get model() { return this.getModel(); },

  // Gets the Screen's view, created on demand.
  getView: function() {
     if ( !this._view ) { this._view = this.createView( this.getModel() ); }
    return this._view;
  },
  get view() { return this.getView(); }
} );
```

**Comment by samreid** [comment]
> How about this pattern for Screen? It makes Screen responsible for model and view creation, and performs that creation on demand. (Using the scenery pattern for ES5 getters here.)

This is the same as the method I proposed about 5 comments ago (please see the comment begininng with the text "I investigated this strategy:") and it suffers from the same problems I identified there:

> But it seems too risky since it does not make the model + view construction time explicit--may get done lazily right when clicking on a homescreen icon which would cause a major lag.

**Comment by samreid** [comment]
In the above commit, I am creating the model & view within Screen.js, with a public API for triggering their creation, and additional documentation, asserts, etc.  This feels like a step in the right direction--should we make any further changes?

**Comment by pixelzoom** [comment]
Looks good, I can live with this.

Recommended to add @private where appropriate. Definitely for tthis._model, this._view. Unclear what the intention is for initializeModel, initializeView.

**Comment by pixelzoom** [comment]
I noticed a couple of other things, so I made the changes for annotations and an additional assertion.

Back to @samreid for review.

**Comment by pixelzoom** [comment]
If Screen.initializeModel and initializeView are private, how about combining them into initializeModelAndView, and rename initializeModelAndView to initialize?

**Comment by samreid** [comment]
I'm leaving them all as public in case in the future we want to give the client more control over the creation process, such as for showing a progress indicator during loading.

**Comment by samreid** [comment]
Anything else for this issue?  Close if not.

**Comment by pixelzoom** [comment]
Sounds good, closing.
