### ISSUE TITLE
Screen isn't a Screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#224]
As noted in https://github.com/phetsims/joist/issues/191#issuecomment-77062005, it's odd that HomeScreen is not a Screen, it's a ScreenView.  Consider renaming it.

Also in Sim, we have this bit of weirdness:

```js
93 // [read-only] {Screen|null} - The current screen, or null if showing the home screen (which is NOT a Screen)
94 currentScreen: null,
```

"which is NOT a Screen"?... Then why is it's type {Screen} and why is it named current*Screen* ?!?

**Comment by samreid** [comment]
Perhaps it would be a good move to rename HomeScreen to HomeScreenView, then to create a new thing called HomeScreen which extends Screen and has HomeScreenView as its view, and a trivial model.  This could uniformify (sp?) things.  Thoughts @pixelzoom ?

**Comment by pixelzoom** [comment]
That sounds like a nice, uniform approach.

**Comment by samreid** [comment]
I've moved many things toward the "HomeScreen is a Screen with a HomeScreenView" approach, but noticing that in many cases it has special treatment and cannot be treated uniformly with the other sim content screens.  For instance, we must keep track of which sim content screen should be highlighted in the HomeScreenView (but not allowing the HomeScreen to highlight itself).  The navigation bar icons are different, the HomeScreen doesn't have a name, etc.  Still, it seems like a step in the right direction to use HomeScreen + HomeScreenView.  I'll look around a bit more to see if more cleanup or reorganization is warranted.

**Comment by samreid** [comment]
I guess the biggest inconsistency now is code like this:

```js
    sim.multilink( [ 'showHomeScreen', 'screenIndex' ], function( showHomeScreen, screenIndex ) {
      sim.currentScreen = showHomeScreen ? null : screens[ screenIndex ];
      sim.updateBackground();
    } );
```

This says that the currentScreen is null if the home screen is selected.  Perhaps this should be rewritten so that:
a) it refers to a currentContentScreen (where content means a screen other than the homescreen)
b) set the selected screen to be the home screen instance

b) is probably a better long term solution if it is technically feasible.

**Comment by samreid** [comment]
Another point related to the above comment: we cannot always mix HomeScreen in with the other screens--it is a special case for several concerns (see a few comments back).  But we could have allScreens and contentScreens fields?

**Comment by samreid** [comment]
This seems like a good point to have @pixelzoom review and advise.

**Comment by pixelzoom** [comment]
I'm OK with the remaining warts that this approach has. The only approach I can think of that might smooth things out is add the HomeScreen to the beginning of @param {Screen[]} screens, so that screens[0] is the home screen. But that has other warts: may require `instanceof HomeScreen`; would only be added when screens.length > 1; ... So I don't think that's worth the effort to investigate.

**Comment by samreid** [comment]
> The only approach I can think of that might smooth things out is add the HomeScreen to the beginning of @param {Screen[]} screens, so that screens[0] is the home screen.

As I mentioned before,

> I've moved many things toward the "HomeScreen is a Screen with a HomeScreenView" approach, but noticing that in many cases it has special treatment and cannot be treated uniformly with the other sim content screens.

So for me, this is an important reason not to mix it in with the other Screens.

Anything else to do here before closing?

**Comment by pixelzoom** [comment]
@samreid wrote:
> Anything else to do here before closing?

Nope. Closing.
