### ISSUE TITLE
renderer:'svg' interferes with rootRenderer

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#225]
Discovered during #221: 

renderer:’svg’ occurs in many many places.  Can/should someone go through and remove those?  It will generally interfere with ‘rootRenderer’.  The only renderer:’svg’ that I can think of that we must keep are where (a) it won’t work with other renderer or (b) parent was canvas and child must be set back to svg.  Those seem somewhat rare.  Let's discuss.  I put it on the agenda for next meeting.

**Comment by pixelzoom** [comment]
I removed `renderer: 'svg'` from under-pressure.UnderPressureView (a ScreenView subtype), looks like it was missed #221.  I also removed it from under-pressure.*PoolView, looks unnecessary there. Tested and I didn't see any issues.

**Comment by pixelzoom** [comment]
Sims that are setting renderer include:

```
blackbody-spectrum
build-an-atom
energy-skate-park-basics
friction
john-travoltage
least-squares-regression
```

Consensus at 3/10/15 developer meeting: No need to eagerly solve all of these now. But @jonathanolson & @samreid  can address them as they come across them without consulting with the original developers.  If anyone wants to eagerly fix these, feel free.

**Comment by bereaphysics** [comment]
That takes care of blackbody-spectrum and least-squares-regression on your list.

**Comment by pixelzoom** [comment]
The list has been pruned to:

```
build-an-atom
energy-skate-park-basics
friction
john-travoltage
```

**Comment by pixelzoom** [comment]
The remaining sims should be fixed before "Summer 2015 redeploy".

**Comment by pixelzoom** [comment]
Assigning to @jbphet, since build-an-atom is first on the list.

**Comment by jbphet** [comment]
I've removed renderer specs from build-an-atom and friction and have done basic testing on them (Chrome only so far) to verify that performance is not degraded for either.  I'll count on QA testing to make sure that this still performs well across all platforms for the Summer 2015 Redeploy.

Assigning this to @samreid for john-travoltage and energy-skate-park-basics.

**Comment by samreid** [comment]
John Travoltage has this code:

```js
    //The sim works best in most browsers using svg. But in firefox on Win8 it is very slow and buggy, so use canvas on firefox.
    ScreenView.call( this, {
      renderer: platform.firefox ? 'canvas' : 'svg',
      layoutBounds: new Bounds2( 0, 0, 768, 504 )
    } );
``` so it will need Win8/FF tests to see if we can drop this yet.

**Comment by samreid** [comment]
Energy Skate Park: Basics sets the renderer based on whether WebGL is available.

**Comment by samreid** [comment]
Since the remaining work is covered by the issues linked above, this main issue can be closed.
