### ISSUE TITLE
Move sim.simModel properties to the Sim properties

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#226]
There are currently two disjoint propertysets making up each Sim.  There is no good reason for the separation (cause is vestigial), and they should be merged.

**Comment by samreid** [comment]
Fixed above, would be good for @jonathanolson @pixelzoom @jbphet or @aaronsamuel137 to take a look around since this is central joist code.

**Comment by pixelzoom** [comment]
Assigning to me since @jonathanolson is on vacation.

**Comment by pixelzoom** [comment]
The 2 properties in question were homeScreen and screenIndex. Change looks good to me. Closing.
