### ISSUE TITLE
should copyright indicate "Some rights reserved" in About dialog?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#230]
The Java copyright indicates "Some rights reserved". The HTML5 copyright does not, should it? See screenshots below.   Assigning to @ariel-phet to decide.

![screenshot_491](https://cloud.githubusercontent.com/assets/3046552/6815885/54223374-d251-11e4-822b-2d080b07e217.png)

![screenshot_492](https://cloud.githubusercontent.com/assets/3046552/6815884/50caa616-d251-11e4-89ed-a874bcd5a6e9.png)

**Comment by pixelzoom** [comment]
In Java sims, clicking on "Some rights reserved" takes you to the licensing web page. In HTML5, that's done by clicking on "Terms, Privacy & Licensing".  So perhaps "Some rights reserved" is not needed (thought it's very common to see "All rights reserved" immediate after a ©Copyright mark.)

**Comment by ariel-phet** [comment]
I personally think we are fine as is. It is the same information, just not as proximal to the copyright.
