### ISSUE TITLE
When the sim is inactive, it should be grayed out

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#232]
Related to https://github.com/phetsims/scenery/issues/414

**Comment by samreid** [comment]
Here is a small change set that looks like it solves the problem.  Can one of @jbphet @jonathanolson @pixelzoom review it?

```js
    // When the sim is inactive, make it non-interactive, see https://github.com/phetsims/scenery/issues/414
    var inactiveOverlay = new Node();
    this.activeProperty.lazyLink( function( active ) {
      sim.display.interactive = active;
      if ( !active ) {
        sim.showPopup( inactiveOverlay, true );
      }
      else {
        sim.hidePopup( inactiveOverlay, true );
      }
    } );
```

**Comment by samreid** [comment]
The above code should surround the existing `sim.display.interactive = active;` line in Sim.js

**Comment by pixelzoom** [comment]
@samreid asked someone to review. I'll have a look.

**Comment by pixelzoom** [comment]
This is my first encounter with the sim.display.interactive property. I have no idea when (or why) we would be disabling mouse/touch/keyboard inputs, and can't find any documentation in joist.  

Also, the code that @samreid says should be surrounded is:

```js
// When the sim is inactive, make it non-interactive, see https://github.com/phetsims/scenery/issues/414
    this.activeProperty.link( function( active ) {
      sim.display.interactive = active;
    } );
```

Note that the comment references phetsims/scenery#141, which is closed.

@samreid and @jonathanolson, questions:

1. Is this still an issue?
2. When is a simulation grayed out?

**Comment by pixelzoom** [comment]
Assigning to @jonathanolson for feedback.

**Comment by jonathanolson** [comment]
My understanding of the "interactive" property is that it just shuts off actual user input, but still allows playing back previously recorded inputs.

For playback, we want to fully disable the input from the user playing back previously recorded input events, since otherwise they could "insert" clicks/etc. and screw up the playback.

Showing it as a popup is probably not a great way to accomplish this. Using CSS opacity on the entire sim might be the best option.

**Comment by pixelzoom** [comment]
@jonathanolson  Another question... Is playback something that is currently used by an sims? Ie, does this need to be addressed for "Summer 2015 redeploy"?

**Comment by samreid** [comment]
sim.active is used for together.js

Beaker is using it at the moment as far as I know.

**Comment by jonathanolson** [comment]
I don't know of any usage on the sims on our website (excludes together and beaker).

**Comment by pixelzoom** [comment]
Assigning to @jbphet, since he's working on beaker. Does this need to be addressed for "Summer 2015 redeploy"?

**Comment by samreid** [comment]
Actually for beaker it is important for it to be inactive *without* being grayed out.  It is unclear if/when the sim should be grayed out for other inactive cases.

**Comment by samreid** [comment]
I wonder if we could say this is the responsibility of the wrapper html, say, putting an opacity on the iframe..?

**Comment by jbphet** [comment]
I don't agree with the intent of this issue.  We currently have two customers who are using together.js to build learning systems around PhET simulations.  Both are using the inactive capability for playback or at least setting of state, and I don't think either would want the sim to gray out in this situation.  Assigning back to @samreid to either justify or close.  His suggestion in the comment immediately above about having it be the responsibility of the wrapper page might suffice.

**Comment by pixelzoom** [comment]
+1 for making this the responsibility of the wrapper.

**Comment by samreid** [comment]
Let's leave this up to the wrapper unless/until we run into a limitation that cannot be overcome by the wrapper.  Closing.
