### ISSUE TITLE
"adapted from" text doesn't show up for single-screen simulations

### ISSUE THREAD

**Issue by jbphet** [phetsims/joist#238]
I'm trying to use the "adapted from PhET" branding, and the black-and-white logo is showing up, but the "adapted from" text is missing.

**Comment by jbphet** [comment]
Fixed in this commit: c3a7ef7f7c6fa75de55ab7a5a164ee546c8e9197, which got lumped in with another commit.

**Comment by jbphet** [comment]
Assigning to @samreid for review.

**Comment by samreid** [comment]
The words "adapted from" no longer appear on the homescreen.  Not sure if that problem was caused by or in any way relates to this issue or not.

**Comment by samreid** [comment]
The text appears on the home screen now, closing.
