### ISSUE TITLE
home screen crashes when using "adapted from PhET" branding

### ISSUE THREAD

**Issue by jbphet** [phetsims/joist#240]
Hitting this error when launching a multi-screen sim using Adapted from PhET branding:
```Uncaught TypeError: Cannot read property 'link' of undefined```

The problem appears to be that AdaptedFromPhETText is expecting a lookAndFeel parameter but is getting a boolean property.

**Comment by jbphet** [comment]
Fixed in this commit: c3a7ef7f7c6fa75de55ab7a5a164ee546c8e9197.  Assigning to @samreid to make sure that there isn't something subtle that I'm missing that would explain why it was like this.

**Comment by pixelzoom** [comment]
I messed around with this elsewhere, so I'll investigate.

**Comment by pixelzoom** [comment]
Looks like this was fixed when I made changes in https://github.com/phetsims/joist/issues/256.

Closing.
