### ISSUE TITLE
i18n layout issue with navigation bar

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#241]
For example, see the screenshot of graphing-lines below, with ?stringTest=double.  Note how the home screen icon and PhET menu overlap. 

![screenshot_525](https://cloud.githubusercontent.com/assets/3046552/7779235/1ea5d300-0090-11e5-877d-f08a5c942672.png)

**Comment by pixelzoom** [comment]
Work on this after https://github.com/phetsims/scenery/issues/428 is completed.

**Comment by ariel-phet** [comment]
@pixelzoom - it looks like the scenery issue is complete. This issue seems like a good common code one to address

**Comment by pixelzoom** [comment]
On my list, along with several other similar i18n issues for common code.

**Comment by pixelzoom** [comment]
Closed by mistake, reopening.

**Comment by pixelzoom** [comment]
6/25/15 dev meeting notes:

Equally divide up space available in the navbar, accounting for spacing. Use that to set the maxWidth for the screen names. 

Limit the sim title to some percentage of the navbar width.

**Comment by pixelzoom** [comment]
This has been *really* frustrating. I've had to do major cleanup and deal with things that shouldn't even be related (AdaptedFromText? fullscreen feature? *REALLY?!?!*)

**Comment by pixelzoom** [comment]
This can't be addressed until https://github.com/phetsims/joist/issues/263 is resolved.

**Comment by pixelzoom** [comment]
Problematic to use maxWidth in this context because of the existing layout's reliance on setScaleMagnitude.  So I'll need to totally rewrite the layout.

**Comment by pixelzoom** [comment]
Major changes to navbar, using maxWidth to constrain the width text. It was impossible to make this pixel-identical to previous versions, so everyone is advised to take a look at their sims. 

Layout is now much better at handling i18n.  There is still one major wart, indicated by this TODO:

```js
// NavigationBar.js line 121
maxTextWidth: screenButtonWidth, //TODO this is closer, but not quite right, since it doesn't account for the button highlight  
```

The problem here is that we know how much width should be allocated to each button. So we really need to tell the button "this is your maxWidth", and let it decide how to compute the maxWidth for its text.  I was going down this path when I discovered that the buttons aren't JoistButtons (https://github.com/phetsims/joist/issues/273) and are in fact duplicating code. So I'll need to resolve that issue before proceeding.  

In the meantime... With extremely long strings and 3 or 4 screens, you may see some overlap between the sim title and the screen buttons.

**Comment by samreid** [comment]
To compare before/after, I took screenshots before and after joist 01433450bd949f8f281a6f62643573d23ec00fa7

Acid base solutions before:
![image](https://cloud.githubusercontent.com/assets/679486/8583536/8d89ea84-258b-11e5-9cd3-76a5d3c0fdfc.png)

Acid base solutions after:
![image](https://cloud.githubusercontent.com/assets/679486/8583546/97d57fda-258b-11e5-8354-243cf7f470b2.png)

FAMB before:
![image](https://cloud.githubusercontent.com/assets/679486/8583551/a2699fd0-258b-11e5-84d3-93d5bcd2c447.png)

FAMB after:
![image](https://cloud.githubusercontent.com/assets/679486/8583587/f5e38a22-258b-11e5-8111-e08e853cf6fa.png)

AB before:
![image](https://cloud.githubusercontent.com/assets/679486/8583564/b68ae136-258b-11e5-9544-037c3f9a8020.png)

AB after:
![image](https://cloud.githubusercontent.com/assets/679486/8583567/c09d1d24-258b-11e5-9889-441585709dcf.png)

In my opinion, the acid base icons are getting a bit too cozy!

**Comment by pixelzoom** [comment]
@samreid What do you think about using adaptive spacing between the screen buttons, so that the amount of spacing increases as the maxScreenButtonWidth decreases?

**Comment by samreid** [comment]
An adaptive spacing sounds ok, but we will still have to use an adaptive spacing that doesn't let the "2 small icons" case get *too far* apart, for example.  That is, we don't want a "use all of the available space rule", we will need more complex heuristics.

**Comment by pixelzoom** [comment]
Understood. But the issue with the icons getting to "cozy" in ABS is that they have very short screen names. If they had longer screen names, the icons would appear to be further apart.  So as maxScreenButtonWidth gets smaller, we would (slightly) increase the spacing between buttons.

**Comment by pixelzoom** [comment]
Another (much easier) option would be to just space the screen buttons out more in general. The current spacing between buttons is (and was) zero.

**Comment by samreid** [comment]
> Another (much easier) option would be to just space the screen buttons out more in general. The current spacing between buttons is (and was) zero.

That sounds great, I'd recommend to try that first.

**Comment by pixelzoom** [comment]
Push increase to SCREEN_BUTTON_SPACING.

**Comment by pixelzoom** [comment]
Mutability was added to spacing of HighlightNode (see #275), and ugly hack for adjusting highlight was removed from NavigationBarScreenButton (see https://github.com/phetsims/joist/commit/c20dc4ef6ec73ec048057097914b60631fc74fda).

**Comment by pixelzoom** [comment]
Here's an overview of how layout works now:

```js
Layout of NavigationBar adapts to different text widths and numbers of screens, and attempts to
 * perform and "optimal" layout. The sim title is initially constrained to a max percentage of the bar width,
 * and that's used to compute how much space is available for screen buttons.  After creation and layout of the
 * screen buttons, we then compute how much space is actually available for the sim title, and use that to
 * constrain the title's width.
```

I'm at a good point to have someone else look at this.  Any takers?

**Comment by pixelzoom** [comment]
@jessegreenberg volunteer to have a look, thanks!  

• Review the code.
• Compare sims to the website. The navbar layout will not be pixel accurate with published sims, but it's in the same ballpark.
• Test with stringTest=double
• Test with stringTest=X
• Test with stringTest=SomeReallyReallyLongCrazyStringToMakeSureNothingBreaks
• Test with a 1-screen sim (e.g., John Travoltage)
• Test with a 2-screen sim (e.g. Acid-Base Solutions)
• Test with a 3-screen sim (e.g., Balancing Act)
• Test with a 4-screen sim (e.g. Forces And Motion: Basics)

I've been testing with

**Comment by jessegreenberg** [comment]
##### Review of i18n layout issue with navigation bar

1. Code Review:

 * In NavigationBar, SCREEN_BUTTON_SPACING

**Comment by jessegreenberg** [comment]
###### Review of i18n layout issue with navigation bar

1. Code Review

 * In NavigationBar.js ( commit 30940a0 ) SCREEN_BUTTON_SPACING value was increased which prevented acid-base-solutions icons from getting too close together.  Commit cb87049 reset the value to zero so that the navbar icons match published sims, but acid-base-solutions icons are pretty tight again:  
![abs_spacing](https://cloud.githubusercontent.com/assets/6396244/8667339/8ca63b8e-29bb-11e5-92d7-18287bf24c5d.PNG).
      * Is this OK?  Spacing in the image above actually matches the published version pretty well, I only ask because of discussions above.

2. Comparing sims to published versions with no query parameters (tested with all sims in item 3)

 * The only noticeable difference is that the home button is more separated from the icon buttons now.  Not sure if this is desired, but if we are shooting for the layout of published sims, should HOME_BUTTON_LEFT_MARGIN be set to zero as well?

 * Otherwise, new navigation bar layout matches published sim navigation bar layout very well.

3. Some string Testing (tested all requested above, commenting only on issues found)

 * 1-screen sim:
     * Sim tested: molecules-and-light
     * stringTest=someCrazyLongString...
           - I notice that the title string begins to scale well before it reaches the left edge of the PhET button. 

![scalebeforephetbutton](https://cloud.githubusercontent.com/assets/6396244/8667707/56535404-29c0-11e5-9cf9-c4775c75d7af.PNG)
              From code and documentation I expected the title to extend all the way to the left margin of the PhET button before scaling down with maxWidth.  Am I missing something there?

  * 3-screen sim:
    * Sim tested: energy-skate-park-basics
      * stringTest=double
        * Found two unrelated i18n scaling issues:
          * phetsims/energy-skate-park-basics#323
          * phetsims/energy-skate-park-basics#328

  * 4-screen sim:
      * Sim tested: Forces and Motion Basics
      * stringTest=double
         * Found two unrelated i18n scaling issues:
             * phetsims/forces-and-motion-basics#136
         * Varying text sizes on the icons are quite noticeable for this sim.

![famb_st_double](https://cloud.githubusercontent.com/assets/6396244/8667985/841fd92c-29c3-11e5-9b47-31d4a1f4c97d.PNG)

'Acceleration' string is longest so its smaller y scale is noticeable.

**Comment by pixelzoom** [comment]
@jessegreenberg Thanks for the review.

Responses to above comments...

> ... SCREEN_BUTTON_SPACING value ... 

I set it back to zero because the additional spacing (requested by @samreid) felt too different from what we've had in the past.  If this needs to be tweaked, it's easily done by changing SCREEN_BUTTON_SPACING.  The work will be in reaching consensus. I've created https://github.com/phetsims/joist/issues/279 if anyone wants to tackle this.

> ... home button is more separated ...

I thought this was one case where a little additional padding looked better. Again, it's trivial to change by adjusting HOME_BUTTON_LEFT_MARGIN, and the work will be in reaching consensus. Also covered by https://github.com/phetsims/joist/issues/279.

> ... title string begins to scale ...

I suspect that your browser window was not at the same aspect ratio as ScreenView layoutBounds. Run with ?dev and adjust your browser window size.  Here's what I see (as expected) with john-travoltage:

![screenshot_564](https://cloud.githubusercontent.com/assets/3046552/8676504/217499b8-2a07-11e5-8871-50cc0508dca8.png)

> ... unrelated i18n scaling issues ...

I noticed a lot of sim-specific scaling issues while testing, but didn't create individual issues.  I'm assuming that task https://github.com/phetsims/tasks/issues/245 will identify (or has identified) sims with layout problems, and that developers will be doing thorough i18n testing on their sims before the next redeploy.

**Comment by jessegreenberg** [comment]
> ...additional spacing (requested by @samreid) felt too different...

That makes sense, I was just curious about the reversion.  Thanks for clarifying.

> I thought this was one case where a little additional padding looked better. Again, it's trivial to change by adjusting HOME_BUTTON_LEFT_MARGIN, and the work will be in reaching consensus. Also covered by #279.

I agree that it looks better, just wanted to make sure the deviation was intentional.

> I suspect that your browser window was not at the same aspect ratio as ScreenView layoutBounds.

Exactly right.  I adjusted the aspect ratio, and the title text goes to the phet button margin as expected. Thanks!

>  I'm assuming that task phetsims/tasks#245 will identify (or has identified) sims with layout problems...

Good to know that this exists. However, phetsims/forces-and-motion-basics#136 was not caught by stringTest=double in phetsims/tasks#245.  UI still 'looks' good because the out of bounds button is pushed entirely off screen for that test.

That is all that I could find in the review @pixelzoom, it looks very good as far as I am concerned.  Reassigning.

**Comment by pixelzoom** [comment]
Thanks @jessegreenberg.  Closing this issue.
