### ISSUE TITLE
Instrument dialog window and the "barrier stack" for together/tandem

### ISSUE THREAD

**Issue by jbphet** [phetsims/joist#242]
There is work underway on several simulations to support data sharing using the together and tandem libraries.  Currently, opening and dismissing dialog windows like the "About" dialog doesn't result in the sending of user messages.  This capability should be added.

**Comment by jbphet** [comment]
The work for the barrier stack portion of this issue is done, and was tracked against issue https://github.com/phetsims/together/issues/99.  The one thing that wasn't done yet is instrumenting the dialog window.  This should be done once work on interoperability resumes.

**Comment by jbphet** [comment]
I have no plan to work on this for now so I'm going to unassign the issue.  We will reassign once we get back to work on interoperability.

**Comment by samreid** [comment]
We will need a way to track joist (or other repo) issues for interoperability.  I'll create a label.  Not sure if interoperability or together is a better label.  together is the name of the repo, but interoperability implies tandem as well.  I guess I'll go with interoperability for now.

**Comment by samreid** [comment]
Dialog and barrier stack seem sufficiently instrumented for now.
