### ISSUE TITLE
Clicking "Report a Problem" or "Phet Website" while in full screen causes sim to crash

### ISSUE THREAD

**Issue by bryo5363** [phetsims/joist#244]
Test device: MacBook Pro

Operating System: OSX 10.9.5

Browser: Safari 7.0.6 (9537.78.2)

Problem description: When clicking anything that leads to another link while in full screen, the simulation will crash. This was not apparent on Chrome

Steps to reproduce:
1) open sim
2) click fullscreen
3) open side menu and click report a problem
4) go back to the sim tab on the browser

Severity:

Screenshots:
![screen shot 2015-05-29 at 10 41 35 am](https://cloud.githubusercontent.com/assets/7717368/7887554/3b9eee4c-05ef-11e5-8416-e065a8dca435.png)

Troubleshooting information (do not edit):
Name: Molecule Shapes
URL: http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.0.1-dev.1/molecule-shapes_en.html
Version: 1.0.1-dev.1 2015-05-29 03:40:24 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2
Language: en-us
Window: 1264x696
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (2.1 NVIDIA-8.26.28 310.40.55b01)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"comment":"# molecule-shapes 1.0.1-dev.1 Thu May 28 2015 21:40:23 GMT-0600 (MDT)","assert":{"sha":"903564a25a0f26acdbd334d3e104039864b405ef","branch":"master"},"axon":{"sha":"ed77e70addb76988c671757f53cf2391eafa916a","branch":"master"},"babel":{"sha":"4d8e6729cf020611aef68d71c06869c9277b0f07","branch":"master"},"brand":{"sha":"b3362651f1d7eddb7f8697d02400472f97f9d140","branch":"master"},"chipper":{"sha":"d4681a65828e360532440202e237056437841b96","branch":"master"},"dot":{"sha":"a6a50c92c4cda5f8a3371d8c357ea565b7e7bd6c","branch":"master"},"joist":{"sha":"2e558074fae41abaf9c3086ce55ca4021e1bee4d","branch":"master"},"kite":{"sha":"b915f3b160744e4833d177dc38e74e4cbc912883","branch":"master"},"molecule-shapes":{"sha":"15682d3054d3b057af59a9b425ad4fe7b88353ee","branch":"master"},"nitroglycerin":{"sha":"c6f79ce4664a1120a8d1d2393d5d48f9b72d4bc9","branch":"master"},"phet-core":{"sha":"23834d107dc1cb368c00901c76927b712b9caa10","branch":"master"},"phetcommon":{"sha":"bb92c52cd90fdaa0c2a746fea82594afd439b4db","branch":"master"},"scenery":{"sha":"4fdfbe9ea4c10f36df103f5b07c9ca262d35a0bf","branch":"master"},"scenery-phet":{"sha":"8c4d5f81ec257a5a944b3e5082b032ab62965f40","branch":"master"},"sherpa":{"sha":"f361a31ed97c29bd9b2d999e8eaa14bdfafa98a5","branch":"master"},"sun":{"sha":"ee8f44af90bd8dfd7d13399ecb429348c94e8dd5","branch":"master"}}

**Comment by jonathanolson** [comment]
Not able to immediately reproduce on MacBook Air, OS X 10.9.5, Safari 7.1.6. Report a problem notes:

Name: Molecule Shapes
URL: http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.0.1-dev.1/molecule-shapes_en.html
Version: 1.0.1-dev.1 2015-05-29 03:40:24 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.6.3 (KHTML, like Gecko) Version/7.1.6 Safari/537.85.15
Language: en-us
Window: 1264x670
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (2.1 INTEL-8.28.32)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true

Possibly this was fixed between Safari versions 7.0.6 and 7.1.6?

**Comment by bryo5363** [comment]
@jonathanolson did you have WebGL enabled?

**Comment by jonathanolson** [comment]
Yes.

**Comment by bryo5363** [comment]
Interesting. I will try to reproduce it and let you know how it goes

**Comment by bryo5363** [comment]
I was able to reproduce this on a different machine running 7.0.6 (9537.78.2) on 10.9.5. I guess it must be fixed on higher versions.

**Comment by jbphet** [comment]
After some work on another issue (see https://github.com/phetsims/scenery/issues/434), we learned that iOS 7.0.x had a number of issues with Safari crashing.  Later versions don't appear to have this issue.  We have decided not to try to support iOS 7.0.x or earlier.  Closing.
