### ISSUE TITLE
No troubleshooting info on IE11

### ISSUE THREAD

**Issue by phet-steele** [phetsims/joist#249]
During the Full Screen test of molecule shapes, when using IE11 on Win 8.1, there is no troubleshooting info shown on the Report a Problem page.

**Comment by jonathanolson** [comment]
Sorry, inaccurate tap on phone mid-assigned.

**Comment by arouinfar** [comment]
No worries!

**Comment by orejolaphet** [comment]
No trouble shooting information for IE 10 on Win 7

**Comment by jonathanolson** [comment]
Added redeploy tag.

It looks like IE11 is capping the URLs to 2083 characters. In some cases, this just cuts off the dependencies part, but here it interrupts the URL in-between two characters of an escape code, resulting in an invalid URI component.

Some quick googling shows this limitation: https://support.microsoft.com/en-us/kb/208427.

The best solution is probably to cut down the verbosity of the dependencies, not sending all of it as encoded JSON (lots of double quotes that essentially take up 3 characters each after escaping).

**Comment by pixelzoom** [comment]
> It looks like IE11 is capping the URLs to 2083 characters.

Won't that also be a problem for Rosetta and together, which both rely on passing large amounts of data via query parameters?

**Comment by jonathanolson** [comment]
Yes, I also made an agenda item for discussing the restriction. I knew there was a limit for IE, but didn't know it was quite so low.

**Comment by jonathanolson** [comment]
Tested multiple sims, all working with IE URL limit.
