### ISSUE TITLE
No full screen option for IE 10

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/joist#250]
I would post the trouble shooting information if there were any. Trouble shooting information is also not displayed, see https://github.com/phetsims/joist/issues/249

**Comment by pixelzoom** [comment]
@ariel-phet This issue was create 2 months ago, and seems to have fallen through the cracks. "Full screen" is a new feature for "Summer 2015 Redeploy".   If it doesn't work on IE10, is that OK?

**Comment by pixelzoom** [comment]
Looks like this was issue was created during testing of the full-screen feature, but not mentioned as related. See https://github.com/phetsims/tasks/issues/258

**Comment by pixelzoom** [comment]
"pH Scale" RC testing (https://github.com/phetsims/tasks/issues/322, https://github.com/phetsims/tasks/issues/323) is on hold until this issue is addressed or deferred.

**Comment by ariel-phet** [comment]
@pixelzoom I will let @jonathanolson comment. I believe this was either fixed, or we detect IE 10 and then just do not show the the option in the menu.

**Comment by pixelzoom** [comment]
Indeed, https://github.com/phetsims/tasks/issues/258#issuecomment-112153156 says:
> Internet Explorer 10 does not support webGL, and the option for "Full Screen" is not available under the PhET menu.

Is that OK? We're rolling out a new feature with no support for IE10?

**Comment by ariel-phet** [comment]
@pixelzoom - I think so. The full screen option to me is under a bit of a different category. This is sort of a "nicety" so if it can work great. But if not available, I felt that hiding the option was fine. We can certainly discuss more, but I did not see this feature as universally necessary, and not problematic if it was not available.

**Comment by pixelzoom** [comment]
@ariel-phet Then do you want to close this issue, or defer for later discussion?  And do you want to remove any of the labels?

**Comment by ariel-phet** [comment]
I am fine closing this issue, unless there are any serious objections. Any serious objections?

**Comment by pixelzoom** [comment]
Your call. I don't know the specifics of why this feature isn't supportable on IE10, or whether a different implementation would support all platforms.  I just want to know whether to proceed with publishing sims without IE10 support for the "full screen" feature.

**Comment by ariel-phet** [comment]
Yes proceed. Closing. Feel free to bring up at developer meeting if there might be a better approach to fullscreen for future.
