### ISSUE TITLE
No Full Screen option for iFrame

### ISSUE THREAD

**Issue by bryo5363** [phetsims/joist#251]
The iFrame version of Molecule Shapes does not have the option for Full Screen

**Comment by jonathanolson** [comment]
Looks like we're not adding the options in our iframe embedding test pages for this, see https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/Using_full_screen_mode#When_a_fullscreen_request_fails

I also don't see those options present on the website.

@ariel-phet, do we want to make our iframe test pages allow fullscreen, and/or do we want to put this in the embedding snippets we give out for HTML sims?

**Comment by samreid** [comment]
Since we are relying on iframes for some together.js interoperability, I think embedding in an iframe should support fullscreen *if* our normal sims do.

**Comment by samreid** [comment]
@jonathanolson can you add the attributes to enable this for iframes?

**Comment by jonathanolson** [comment]
Looks like the allowfullscreen option is working well in all latest browser versions.https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe noted no support in IE, but that might mean full-screen is supported anyways (works in IE11).

**Comment by jonathanolson** [comment]
@aaronsamuel137, I'd propose we add this to the embedding snippets in the website (LocalizedSimulation.getDirectEmbeddingSnippet). Thoughts?

**Comment by aaronsamuel137** [comment]
I don't see any reason why we shouldn't do this. I'll add it to the website code.

**Comment by aaronsamuel137** [comment]
Added to website code. Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks!

@ariel-phet, should a testing task for checking to make sure this works for all supported browsers be made?

**Comment by ariel-phet** [comment]
@jonathanolson - yes a testing task would be good. Please create the appropriate task and instructions and assign it to me for assignment/prioritization.

**Comment by jonathanolson** [comment]
Created https://github.com/phetsims/tasks/issues/286, closing this issue.
