### ISSUE TITLE
HomeScreen entries in LookAndFeel?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#255]
HomeScreen currently seems to assume that the background will always be 'black'.  Perhaps that's an OK assumption.  But if that ever changes, we'll need entries for the home screen in LookAndField.

**Comment by pixelzoom** [comment]
Folding this issue into #222. Closing.

**Comment by samreid** [comment]
There are still TODOs marked for this issue, discovered during https://github.com/phetsims/chipper/issues/946

**Comment by samreid** [comment]
I pointed the TODO at https://github.com/phetsims/joist/issues/222, closing.
