### ISSUE TITLE
should AdaptedFromText be part of PhetButton?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#256]
AdaptedFromPhETText has this ugly hack for keeping it next to the PhetButton when the browser window is resized:

```js
    updateLayout: function( scale, phetButton ) {
      this.setScaleMagnitude( scale );
      this.right = phetButton.left - 5 * scale;
      this.centerY = phetButton.centerY - 1 * scale;
    }
```

...and the exclusive usage is in HomeScreenView:

```js
if ( this.adaptedFromText ) {
   this.adaptedFromText.updateLayout( 1, this.phetButton );
}
```

Why isn't AdaptedFromPhETText simply a child of PhetButton? (Probably with pickable:false)

Assigning to @samreid for comment, since he designed this.

**Comment by pixelzoom** [comment]
Making this part of PhetButton would also remove the need for a separate AdaptedFromPhETText type (which is poorly named, because the text is "adapted from", not "adapted from PhET").

**Comment by pixelzoom** [comment]
This would also simplify nav bar layout, because we wouldn't have to conditionally check for the presence of AdaptedFromPhETText.

**Comment by pixelzoom** [comment]
FYI... I renamed AdaptedFromPhETText to AdaptedFromText, since it renders the string "adapted from".

**Comment by pixelzoom** [comment]
AdaptedFromText is now a decoration handled by PhetButton.  I anticipate that this will need to change again when we address broader branding issues. But at least it's encapsulated in one place now, without kludgy layout code.

Assigning to @samreid to review.

**Comment by samreid** [comment]
It seems like things would be significantly simpler if we could just put the "adapted from" text into the logo itself.  However, this would make it non-translateable *or* mean that we have one adapted-from logo per repository.  Can @ariel-phet or @kathy-phet comment on whether it is acceptable to hard code "adapted from" text into English?

**Comment by samreid** [comment]
@pixelzoom said

> We discussed this in a recent meeting, and the decision was to translate the text. See #254.

**Comment by samreid** [comment]
In the above commit, I converted link=>linkAttribute and tested that it worked properly in Molecule Shapes when the background color is toggled through the options menu.

**Comment by samreid** [comment]
I reviewed AdaptedFromPhET and its usages and all looks good, closing.
