### ISSUE TITLE
bad dependency on navigationBarFillProperty in PhetButton

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#257]
PhetButton appears on both the home screen and in the nav bar.

It's supertype constructor is called like this:

`JoistButton.call( this, icon, sim.lookAndFeel.navigationBarFillProperty, options );`

Using `navigationBarFillProperty` here is inappropriate for the case where the PhetButton appears on the home screen.

**Comment by pixelzoom** [comment]
Related to https://github.com/phetsims/joist/issues/256

**Comment by pixelzoom** [comment]
Also related to https://github.com/phetsims/joist/issues/188 (remove dependencies on {Sim} sim in numerous constructors).

**Comment by pixelzoom** [comment]
Bad dependency removed.  Assigning to @samreid to review.

**Comment by samreid** [comment]
Skimming through the change set, it seems like an improvement.  Closing.
