### ISSUE TITLE
What is the plan for brand-specific translatable strings?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#260]
joist.AdaptedFromText, and therefore the translated "adapted from" string, is included in all sims, regardless of whether they are the "adapted from PhET" brand.  This should be avoided if possible. Only relevant strings should be included.  Investigate moving this to the brand. Perhaps the brand could return a {Node} logo that is used for the PhetButton.

**Comment by samreid** [comment]
I also suggested moving the text to the logo in #256, pending discussion from @ariel-phet and/or @kathy-phet

**Comment by pixelzoom** [comment]
We discussed this in a recent meeting, and the decision was to translate the text. See https://github.com/phetsims/joist/issues/254.

**Comment by ariel-phet** [comment]
I think it is correct to have this text translatable.

**Comment by samreid** [comment]
We have discussed the possibility of adding metadata to the strings to indicate where they are used--@pixelzoom do you want to track this anywhere?  I'm not sure if there is an issue for it or if it is being tracked somewhere, or if it is an appropriate solution for this problem.

**Comment by pixelzoom** [comment]
I'm going to retitle this issue to "What is the plan for brand-specific translatable strings?"
Brand-specific strings is a general problem.  We currently have translatable strings for PhET-specific brands.  And will 3rd-party brands also want to have translatable strings?

Questions to answer:
1. Should brand-specific strings be translatable?
2. Should brand-specific strings show up in Rosetta only for a brand-specific deliverable?
3. Where should brand-specific translatable strings live? brand-strings_en.json?
4. What to do about common-code components that rely on a brand-specific string? Eg joist.AdaptedFromText.js.

**Comment by pixelzoom** [comment]
Since this issue affects translation, I've labeled it as "Summer 2015 redeploy".

**Comment by pixelzoom** [comment]
7/16/15 dev meeting

• remove "Summer 2015 redeploy" label
• investigate moving brand-specific strings and associated logic into brand

**Comment by aaronsamuel137** [comment]
Rosetta currently works by taking the strings currently in the source code of the sim from the published version. Therefore, adapted-from-phet brand strings will not show up. We discussed in 9/3 dev meeting that the current behavior is probably fine.

@jbphet, please feel free to fill in any details I missed.

Assigning to @pixelzoom for comment.

**Comment by pixelzoom** [comment]
On 7/7/15, the consensus was that the strings needed to be translated, see https://github.com/phetsims/joist/issues/260#issuecomment-119365110.

9/4/15 comment (https://github.com/phetsims/joist/issues/260#issuecomment-137527013) now indicates that it's OK that Rosetta won't support brand-specific strings. 

Can someone please explain how we went for "must to translate" to "OK that we won't be able to translate"?

**Comment by ariel-phet** [comment]
@pixelzoom after discussion yesterday it did not seem like there would be a use case with our published sims whereby these strings would be appropriate to translate.

For instance, the string "adapted from" will not appear in the published sim. If someone pulls our code and wants to publish an adapted from version, they would not be using the translation utility to make a translation.

It seems such string should definitely be translatable, but it does not seem like there needs to a possibility to translate them in rosetta (for the moment anyhow.

Does that make sense? I think brand specific strings need to be set up to have the ability to be translated but not need to have them interact with rosetta for the time being.

**Comment by pixelzoom** [comment]
> It seems such string should definitely be translatable, but it does not seem like there needs to a possibility to translate them in rosetta (for the moment anyhow.

brand-specific strings are not translatable, via Rosetta or otherwise (unless you include hacking the html file). i18n enables localization (string translation). There is no i18n of brand-specific code; strings are currently hard-coded English, not factored out into (e.g.) a strings.json file.

**Comment by ariel-phet** [comment]
Ah...that was not clear to me...well those strings should be i18n. Is this easy to take care of or should we have a deeper discussion?

**Comment by pixelzoom** [comment]
Not easy. Deeper discussion.

**Comment by samreid** [comment]
For the case of "Adapted from PhET", it is a joist string, loaded statically during joist initialization for every sim.  So won't it appear in the list of translatable strings for every sim?  if not, why not?  And if so, is there a reason we cannot use this strategy for brand-specific strings that we want to i18nize?

**Comment by aaronsamuel137** [comment]
It doesn't appear because rosetta looks at the source code of the published sim for the strings keys, and "Adapted from PhET" doesn't appear in the source code if the brand is phet.

**Comment by pixelzoom** [comment]
As @samreid said in https://github.com/phetsims/joist/issues/260#issuecomment-137892585, the "adapted from" string is loaded statically during joist initialization for every sim. PhetButton is included with every brand, it requires AdaptedFromText.js, which requires the "adaptedFrom" string:

`var adaptedFromString = require( 'string!JOIST/adaptedFrom' );`
 
I built hookes-law with `grunt --brand=phet`.  The following string is in output file hookes-law_en.html:

`"JOIST/adaptedFrom":"<202a>adapted\nfrom<202c>"`

So I would expect this string to be visible in Rosetta for all sims. Why isn't it? Are the beta-test sims old html files?

**Comment by aaronsamuel137** [comment]
Ah I see what you mean now. Yes adaptedFrom will appear in Rosetta because it is in the source code.

The reason it wasn't before is because the .htaccess files were pointing to old versions of the sim on phet-dev. Build-server updates these .htaccess files automatically, but in this case the files got resynced with the old versions on figaro. I've updated the files, and now adapted from is showing up as expected.

**Comment by pixelzoom** [comment]
Consensus 9/8/15 dev meeting:
If we have brand-specific strings that we want internationalized, they'll live in joist (like we've done with "adapted from PhET").   We should also keep in mind that Rosetta is only translating 'phet' brand html files.

Closing because we have "a plan".
