### ISSUE TITLE
buggy fullscreen code

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#261]
In HomeScreenView:

```js
   //Only show the full screen button on supported platforms
    var showFullScreenButton = !platform.android && !platform.mobileSafari && !platform.ie; // might work on IE11 in the future
    if ( showFullScreenButton && false ) {
      var fullScreenButton = new FullScreenButton();
      this.addChild( new HBox( {
        spacing: 10,
        children: [ fullScreenButton, new PhetButton( sim ) ],
        right: this.layoutBounds.maxX - 5,
        bottom: this.layoutBounds.maxY - 5
      } ) );
    }
    else {
      this.phetButton = new PhetButton( sim, { tandem: options.tandem ? options.tandem.createTandem( 'phetButton' ) : null } );
      this.addChild( this.phetButton );
    }
```

There are *so* many things wrong with this. 

(1)  This creates a big block of unreachable code: `if ( showFullScreenButton && false )`

(2) PhetButton is instantiated in 2 different ways, depending on whether the fullscreen button is added. Why? 

(3) It's questionable whether the if block is even relevant anymore, since a fullscreen button is in the PhET menu.

**Comment by pixelzoom** [comment]
@jonathanolson or @samreid Can you comment on any of the above?

**Comment by pixelzoom** [comment]
If this code is relevant, why is it short-circuited with `if ( showFullScreenButton && false )` instead of using the 'fullscreen' query parameter that's used elsewhere (e.g., in PhetMen) ?

**Comment by jonathanolson** [comment]
Pretty sure it is very old and deprecated code that can be removed?

**Comment by pixelzoom** [comment]
So there's no requirement for a separate fullscreen button that appears only on the home screen?

**Comment by jonathanolson** [comment]
Not that I have been involved in.

**Comment by pixelzoom** [comment]
@samreid  ?

**Comment by pixelzoom** [comment]
@jonathanolson and I both suspect that this is cruft that wasn't cleaned up from a previous prototype. I've deleted it.  Assigning to @samreid to verify.

**Comment by samreid** [comment]
It looks like we can additionally delete joist/js/FullScreenButton.js

**Comment by samreid** [comment]
I'm not too familiar with the rest of the full screen features, but the deletions above look good, closing.
