### ISSUE TITLE
Navigation bar creates all screen buttons twice

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#263]
In NavigationBar:

```js
// Create screen buttons once so we can get their dimensions
var buttons = _.map( screens, function( screen ) {
  return new NavigationBarScreenButton(..., 0 );
} );
var maxWidth = Math.max( 50, _.max( buttons, function( button ) {return button.width;} ).width );

// Create screen buttons again with equivalent sizes
buttons =_.map( screens, function( screen ) {
  return new NavigationBarScreenButton(..., maxWidth, ... );
} );
```

NavigationBarScreenButton is a complex node. Is this taking a significant amount of time?

**Comment by jonathanolson** [comment]
It might, but the alternative looks like we'd have to be able to adjust the button's dimensions after creation to match the largest one?

**Comment by pixelzoom** [comment]
Why do should screen icons have different dimensions in the first place? Shouldn't they all be created with one of these 2 sizes?:

```js
// Screen.js
  Screen.HOME_SCREEN_ICON_SIZE = new Dimension2( 548, 373 );
  Screen.NAVBAR_ICON_SIZE = new Dimension2( 147, 100 );
```

**Comment by samreid** [comment]
Perhaps the text is part of the button dimension?

**Comment by pixelzoom** [comment]
Why would we scale the entire button if the text is longer?

**Comment by pixelzoom** [comment]
Also related to this in NavigationScreenButton:

```js
// Buttons are created once with the wrong size then again with the right size.  Only register the final buttons.
options.tandem && options.tandem.addInstance( this );
```

Bad that NavigationScreenButton needs to know that NavigationBar is doing this.

**Comment by pixelzoom** [comment]
I see what's going on here.  NavigationScreenButton is adding an overlay (transparent) Rectangle, and all the overlays are the same width. The buttons are then put in an HBox, and the end result is that the icons look like they are equally spaced.  This approach makes it difficult to address navbar i18n (https://github.com/phetsims/joist/issues/241).

**Comment by pixelzoom** [comment]
The vertical highlight bars are also placed around the overlay, not the icon+text.  So if one screen name is exceptionally long, you get something that looks like this (where pointer is over "Systems" icon):

![screenshot_549](https://cloud.githubusercontent.com/assets/3046552/8502914/e44be58c-2173-11e5-865d-4c1b836b22e5.png)

Do we really want highlighting to behave like this? What's wrong with highlighting around the icon+text (plus some horizontal padding)?

**Comment by pixelzoom** [comment]
Recommendations:

To eliminate the need to create all NavigationScreenButton twice:
• Require all screen icons to be the same size. 
• Set NavigationScreenButton size based on icon+text+padding. Do not make them all the same width.

To facilitate i18n of screen button text:
• Make NavigationBar responsible for computing maxWidth for NavigationScreenButton text.
• Make NavigationBar responsible for handling layout of buttons. Use horizontal struts instead of HBox.

The only change here from the end-user's perspective is that the button highlight (vertical bars) will not be equally spaced for every screen icon.  Imo this is a positive change, since it currently looks odd in cases where screen names have different widths.

**Comment by pixelzoom** [comment]
I made the changes described above.  Computation of maxWidth for screen button text will be addressed in #241. 

Assigning to @samreid for review.

**Comment by samreid** [comment]
I was concerned that this new requirement may cause some sims to fail the icon size check.  To check, I ran http://localhost:8080/chipper/tests/test-sims.html?loadOnly

I saw this error in several sims:
> Uncaught Error: Assertion failed: all navigation bar icons must have the same size

balancing-act
build-an-atom
color-vision
energy-forms-and-changes
fluid-pressure-and-flow
gene-expression-basics
gravity-and-orbits
reactants-products-and-leftovers

Reassigned to @pixelzoom to discuss how to handle this problem.

**Comment by pixelzoom** [comment]
Imo, those sims all have the same defect and they should be fixed.

**Comment by pixelzoom** [comment]
Inspecting the issue in reactants-products-and-leftovers, here's what I see when I set a breakpoint in NavigationBar's constructor before the assertion:

```
> screens[0].navigationBarIcon.width
147
> screens[1].navigationBarIcon.width
548
> screens[2].navigationBarIcon.width
548
```

In this sim, the first screen has a navbar-specific icon, while the others are defaulting to the home screen icon.  I would expect that screen.navigationBarIcon would (at this point) be a navbar icon, not a home screen icon.

**Comment by pixelzoom** [comment]
Here's what I see with balancing-act:

```
> screens.length
3
> screens[0].navigationBarIcon.width
99
> screens[1].navigationBarIcon.width
99
> screens[2].navigationBarIcon.width
152
```

The icons in this sim are navbar-specific, and they are read from image files.  I see no reason why they should be something other than Screen.NAVBAR_ICON_SIZE = new Dimension2( 147, 100 ).  So for this sim, I believe this is a defect.

**Comment by samreid** [comment]
I finished reviewing the implementation, this is much nicer, thanks.  Shall we leave this issue open until broken sims get their own issues?

**Comment by pixelzoom** [comment]
Yes, leave open. We need to decide what to do about the broken sims.  I'll add to dev meeting agenda.

My opinion is that they should provide correctly-size icons for home screen and (optionally) navbar.  And if home screen icons are used for navbar, then they should be properly sized when they are attached to Screen.navigationBarIcon.

**Comment by pixelzoom** [comment]
To facilitate testing of #241 (navbar i18n layout), and until we've discussed how to proceed, I've temporarily disabled the requirement that all navbar screen icons must have the same size.

**Comment by pixelzoom** [comment]
Now that navbar layout is more robust (#241), perhaps we can remove the assertion. If screen icons are not the same size, then you'll see that they're not the same size in the navbar.  If they're too wide and there are a large number of screens, the icons may even be scaled down (via maxWidth) to fit the space allocated for each screen button.

**Comment by pixelzoom** [comment]
7/14/15 dev meeting: Assert that the aspect ratio matches the aspect ratio of either Screen.NAVBAR_ICON_SIZE or Screen.HOME_SCREEN_ICON_SIZE.

**Comment by pixelzoom** [comment]
Assertion added to NavigationBar, requiring navbar screen icons to have the same aspect ratio as either Screen.NAVBAR_ICON_SIZE or Screen.HOME_SCREEN_ICON_SIZE.

The following sims identified in https://github.com/phetsims/joist/issues/263#issuecomment-119299402 still fail this assertion, because their icons have an incorrect aspect ratio:

balancing-act
build-an-atom
color-vision
fluid-pressure-and-flow
gravity-and-orbits

(gene-expression-basics still fails, but at a later assertion.)

I did not test other sims, so there may be other cases were the aspect ratio is incorrect.

**Comment by pixelzoom** [comment]
I've created issues for all of the sims that are currently failing due to aspect ratio. Other sims will be identified through normal testing with assertions enabled.

Closing.

**Comment by samreid** [comment]
Reopening, this rule:

> requiring navbar screen icons to have the same aspect ratio as either Screen.NAVBAR_ICON_SIZE or Screen.HOME_SCREEN_ICON_SIZE

Seems unnecessarily strict.  For instance, I received artwork with an aspect ratio of
1.4697554697554698

which did not match either of these:

navbarIconAspectRatio = 1.47
homeScreenIconAspectRatio = 1.4691689008042896

So shouldn't we allow some tolerance around these values?

**Comment by samreid** [comment]
I committed a tolerance above, this should be discussed & reviewed by one of @pixelzoom @jbphet @jonathanolson.

**Comment by pixelzoom** [comment]
Looks ok to me, closing.
