### ISSUE TITLE
browser window title isn't properly internationalized

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#265]
In Sim.js:

`$( 'title' ).html( name + ' ' + sim.version + options.textDescription ); //TODO i18n of order`

The order isn't internationalized. Need to add something like this to joist strings file:

`"titlePattern": "{0} {1} {2}"

And perhaps we can get rid of options.textDescription, whose documentation is:

```js
// THIS IS EXPERIMENTAL, USE AT YOUR OWN PERIL
// Text description of the simulation that will be appended to the title, so that screen readers will read the text
// when they are launched.
textDescription: ''
```

**Comment by pixelzoom** [comment]
Assigning to @samreid to verify.  If textDescription is no longer needed, please remove it from Sim.js and joist-strings_en.json.

**Comment by samreid** [comment]
The only Sim.js usage of textDescription was removed in https://github.com/phetsims/forces-and-motion-basics/issues/134, so I'll remove it from Sim.js for now.

**Comment by samreid** [comment]
I removed textDescription above and reviewed @pixelzoom's titlePattern implementation above.  Everything looks good.  I also tested hooke's-law (requirejs and built version) and did not see any problems.  Closing.
