### ISSUE TITLE
highlight is different for home button vs screen buttons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#267]
Here's the highlight for a screen button in the navigation bar:

![screenshot_553](https://cloud.githubusercontent.com/assets/3046552/8503346/30508f3a-217b-11e5-9484-cd86866bbcb7.png)

Here's the highlight for the home button:

![screenshot_552](https://cloud.githubusercontent.com/assets/3046552/8503349/3ae00700-217b-11e5-94cf-6a8c23c3d78f.png)

Seems like they should be the same.

(NOTE: This and lots of code might be simplified if we stopped treating HomeScreen as something special, and started treating it as a Screen [which it does extend] that gets added by default to multi-screen sims.)

**Comment by pixelzoom** [comment]
There's also this bit of code in NavigationBar:

```js
// Center the home icon vertically and make it a bit larger than the icons and text, see https://github.com/phetsims/joist/issues/127
this.homeButton.setScaleMagnitude( scale * 1.1 );
this.homeButton.left = this.screenButtonsParent.right + 15;
this.homeButton.centerY = this.background.rectHeight / 2;
```

Why not handle the sizing and positioning of homeButton in the constructor, add it to screenButtonsParent, and be done with it?  As is, the scaling code here is identical to the scaling code for screenButtonsParent.

**Comment by pixelzoom** [comment]
Related to #241 (i18n layout of navbar).

**Comment by pixelzoom** [comment]
This is related to the fact that the home button is scaled differently, see https://github.com/phetsims/joist/issues/268.

**Comment by pixelzoom** [comment]
Addressed this issue.  Home button icon is the same size as it has been, but the highlight is the same size as the screen buttons.

Assigning to @samreid to review.

**Comment by samreid** [comment]
This looks much better in the UI, thanks.  I didn't spot any issues when I skimmed the change sets above.
