### ISSUE TITLE
Home button scaling issues

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#268]
The home button in the navbar is currently scaled in 2 places.

In HomeButton:

```js
var homeIcon = new FontAwesomeNode( 'home', {
  scale: 0.75
} );
```

In NavigationBar:

```js
// Center the home icon vertically and make it a bit larger than the icons and text, 
// see https://github.com/phetsims/joist/issues/127
this.homeButton.setScaleMagnitude( scale * 1.1 );
```

So it's being scaled it down, then scaled up.  Why not just scale it once, based on the navbar height?

**Comment by pixelzoom** [comment]
Related to #241 (i18n layout of navbar).

**Comment by pixelzoom** [comment]
This comment in NavigationBar is also odd:

> Center the home icon vertically and make it a bit larger than the icons and text, 
// see https://github.com/phetsims/joist/issues/127

The home button is visibly *smaller* than the screen icons, because the combined scale value is actually 0.825 (0.75 * 1.1) 

Does anyone know the history of this?

**Comment by pixelzoom** [comment]
Discussed with @jonathanolson. His recollection is that the home button should be a bit larger than the screen icons (which it is), not the "icons and text".  So I check the comment to:

`// Center the home icon vertically and make it a bit larger than icons on screen buttons`

**Comment by pixelzoom** [comment]
Discussed with @jonathanolson. His recollection is that the home button should be a bit larger than the screen icons (which it is), not the "icons and text". So I changed the comment to:

```js
// Center the home icon vertically and make it a bit larger than icons on screen buttons.
// Multiplier determined empirically. See https://github.com/phetsims/joist/issues/127
this.homeButton.setScaleMagnitude( 0.825 * scale );
```

**Comment by pixelzoom** [comment]
Scaling the home button differently is the root cause of #267 (highlight is different for home button vs screen buttons).

**Comment by pixelzoom** [comment]
All scaling is now handled by HomeButton.  Icon size and position should be unchanged. Assigning to @samreid to review.

**Comment by samreid** [comment]
I skimmed each change set above and tested a fresh acid-base solution to see if the home button still looked/behaved properly and did not discover any issues.  Closing.
