### ISSUE TITLE
move assets to brand?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#269]
Discovered while updating the PhET logo files in https://github.com/phetsims/joist/issues/258.

joist/assets contains 3 files:

phet-logo.svg
PhET_Logo_FINAL_RGB_NoTagLine.ai
PhET_Logo_FINAL_RGB_TagLine_White.ai

These are all related to the PhET logo, and logos live in the brand repository. Should these assets be move to brand/assets, in the 'phet' branch of brand?

Assigning to @samreid for comment, since I believe that he created brand.

**Comment by samreid** [comment]
Moving the assets to phetsims/brand/phet/assets seems like the best place to me, once all brand branches are moved to master.  Not sure why this was flagged for S2015R, can you comment?

**Comment by pixelzoom** [comment]
Flagged because KP requested that the logos be revised for S2015R, see https://github.com/phetsims/joist/issues/258.  If we're going to update the logos in brand, we might as well put the assets in the correct place.

**Comment by pixelzoom** [comment]
@samreid Do you know if phet-logo.svg is still relevant? I don't see it used anywhere. I suspect it was replaced by the various images in brand/images/.

**Comment by samreid** [comment]
I believe we were just treating the SVG file as the "original artwork" since it was full resolution vector art.  Not sure if we have an AI file for it now, but we probably should for consistency.

**Comment by pixelzoom** [comment]
The original artwork is an SVG file? Surely the original artwork was created using Illustrator, no? If not, why not? If so, where is the original .ai file?

And was phet-logo.svg used in the creation of PhET_Logo_FINAL_RGB_NoTagLine.ai and PhET_Logo_FINAL_RGB_TagLine_White.ai?

**Comment by samreid** [comment]
@ariel-phet is probably more in-touch with this kind of artwork, though I can always do some archaeology around in my email and find out what I was given originally.

**Comment by pixelzoom** [comment]
According @ariel-phet, @amanda-phet has the original .ai for the PhET logo.

**Comment by pixelzoom** [comment]
brand/assets/phet-brand-assets.ai replaces all of the files in joist/assets, so the contents of joist/assets/ has been deleted.  All assets and image related to the PhET brand now live in the 'phet' branch of the brand repository.

Closing.
