### ISSUE TITLE
missing items in the PhET menu

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#270]
Sometime very recently the "PhET Website" and "Report a Problem" items disappeared from the PhET menu.  Compare these 2 recent versions of hookes-law:

http://www.colorado.edu/physics/phet/dev/html/hookes-law/1.0.0-dev.22/hookes-law_en.html
http://www.colorado.edu/physics/phet/dev/html/hookes-law/1.0.0-dev.23/hookes-law_en.html

Was this intentional or a bug?

**Comment by pixelzoom** [comment]
Here's the culprit, line 158 of PhetMenu:

`var isPhETBrand = Brand.name === 'PhET Interactive Simulations';`

... and the missing menu items are added only if isPhetBrand === true.

Issue https://github.com/phetsims/joist/issues/258 requested adding the registered trademark symbol (®) to the string, so Brand.js changed to: 

`var phetString = 'PhET<sup>\u00ae</sup> Interactive Simulations';`

... and isPhetBrand suddenly because false.  This is a classic example of why duplicating a string literal (especially one used in logic) is a really bad practice.

**Comment by pixelzoom** [comment]
I should mention that there is this comment about `var isPhetBrand` in PhetMenu:

`//Note: this string below must stay in sync with the Brand.name or phet features will be dropped`

So an attempt was made to note the dependency. Unfortunately this dependency should have been noted in Brand.js, not here, since there's no way someone changing Brand.js would have known to look for this documentation.

**Comment by pixelzoom** [comment]
Temporary fix in https://github.com/phetsims/joist/commit/257ceb0ca4f29f328d5997652ec876fdac9324ac, I made a copy of the new Brand.js string.  This is not a longterm solution, but allows us to remove the "Summer 2015 redeploy" label from this issue.

**Comment by samreid** [comment]
Perhaps the brand instance should have the following entries:

brand.showPhETWebsiteButtonInPhETMenu
brand.showReportAProblemInPhETMenu

I'm flexible on what to name them, but you get the idea.  PhETMenu would use their values to decide whether to show the phet website button or the report a problem button.  This would also make it easy for 3rd parties to link back to PhET.

**Comment by pixelzoom** [comment]
I dislike the approach of adding brand-specific flags, i.e. flags that are intended to be true only for 1 specific brand.

**Comment by pixelzoom** [comment]
Or maybe you're suggesting that someone creating their own brand could choose to add these menu items to their brand?

**Comment by samreid** [comment]
Sure, let's say that another group wanted to link back to the PhET website in their rebranded sim, for example.

**Comment by samreid** [comment]
I think the solution in #271 solves this problem as well.  Thoughts?

**Comment by pixelzoom** [comment]
Agree that #271 solved this issue too. Closing.
