### ISSUE TITLE
how to identify a specific brand?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#271]
This issue is related to both brand and joist, but the logic inconsistencies manifest themselves in joist.

Joist does some tests that add features for the 'phet' and 'adapted-from-phet' brands.  

The 'phet' brand tests look like this:

```js
var isPhETBrand = Brand.name === 'PhET<sup>\u00ae</sup> Interactive Simulations';
if ( is PhETBrand ) {
   // add some feature
}
```

The 'adapted-from-phet' brand tests look like this:

```js
if ( Brand.adaptedFromPhET ) {
   // add some feature
}
```

Why is joist relying on string comparison in one case, and a brand-specific flag in the other? And is there a better way to do this?

Both approaches have flaws. The string comparison approach causes problems like #270. The brand-specific flag results in a field that must be added to all Brand.js instances, and is true in (presumably) only one instance.

Assigning to @samreid for comment, since he implemented both approaches.

**Comment by samreid** [comment]
I suggested an alternate approach in #270, let's discuss it.

**Comment by samreid** [comment]
I think a better strategy would be to include an "id" field in the brand which can be used for determining the brand.  The ID field should match the branch name for phet-supplied brands.  It won't be internationalizable and can be used as a uniform way to handle brand-specific logic for phet-supplied brands.

**Comment by samreid** [comment]
I implemented the id strategy described above, reassigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
I inspected changes and ran with the 'phet' brand. Looks great, I like this solutions. Closing.
