### ISSUE TITLE
NavigationScreenButton doesn't propagate options to supertype

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#272]
Yet another issue encountered while working on navbar i18n, https://github.com/phetsims/joist/issues/241.

**Comment by pixelzoom** [comment]
Reopening. Since options involves a tandem, it deserves a test with an interoperable sim.

**Comment by pixelzoom** [comment]
This work required a change that could affect tandem propagation. Can someone tell me how to test an interoperable sim? Or does someone want to do the test?  The test is to run any sim and verify that navbar buttons are sending messages.

**Comment by samreid** [comment]
@jbphet just reported that navbar events weren’t working anyways, see https://github.com/phetsims/together/issues/99

@jbphet is really best poised to test your changes to navbar tandem, though we could figure it out if he can't get to it in the near future.

**Comment by pixelzoom** [comment]
[7/8/15, 5:51:07 PM] Sam Reid: @jbphet just reported that navbar events weren’t working anyways, see https://github.com/phetsims/together/issues/99
[7/8/15, 5:51:34 PM] Sam Reid: @jbphet is really best poised to test your changes to navbar tandem
[7/8/15, 5:56:15 PM] Chris Malley: not working prior to my changes?
[7/8/15, 5:56:22 PM] Sam Reid: correct

@jbphet When you get phetsims/together#99 worked out, could you please verify this issue too?

**Comment by jbphet** [comment]
I've tested on an interoperable sim while working on https://github.com/phetsims/together/issues/99, and tandem information appears to be property propagated.  I think it is safe to close this one.
