### ISSUE TITLE
make spacing mutable in HighlightNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#275]
This would be convenient for adjusting screen button sizes when doing navbar layout, as in #241.

It would also make sense to handle spacing using HBox, instead of the current approach of creating 2 Rectangles as specific locations, 

Ie, instead of this:

```js
var leftBar = new Rectangle( -0.5, 0, 1, height, ... );
var rightBar = new Rectangle( width - 0.5, 0, 1, height, ... );
Node.call( { children: [ leftBar, rightBar ], ... );
```

do this:

```js
var leftBar = new Rectangle( 0, 0, 1, height, ... );
var rightBar = new Rectangle( 0, 0, 1, height, ... );
HBox.call( { children: [ leftBar, rightBar ], spacing: width, ... } ); 
```

**Comment by pixelzoom** [comment]
Mutability of spacing was added to LayoutBox in phetsims/scenery#446, and therefore to HighlightNode, since it's a subtype of LayoutBox.  This feature is now used when adjusting the width of highlights in NavigationBarScreenButton, rather than having to create new instances of HighlightNode.

Assigning to @samreid to review.

**Comment by pixelzoom** [comment]
@samreid is busy, and this is related to phetsims/scenery#446. So @jonathanolson please review this one too.

**Comment by jonathanolson** [comment]
Joist changes look good.
