### ISSUE TITLE
problems with layout constants in JoistButton

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#276]
```js
return inherit( Node, JoistButton,

    //statics
    {

      //How much space between the JoistButton and the right side of the screen.
      HORIZONTAL_INSET: 5,

      //How much space between the JoistButton and the bottom of the screen
      VERTICAL_INSET: 0
    } );
```

Problems:

(1) These constants are not static, they are being added to the prototype.
(2) Why does a general JoistButton need such constants?
(3) These constants are not used anywhere. (There are similar, static constants in PhetButton.)

**Comment by pixelzoom** [comment]
These constants were brought over when JoistButton was factored out of PhetButton by @samreid. They inadvertently became non-static in 3a07967 when @samreid deleted prototype functions.

Assigning to @samreid to review.

**Comment by samreid** [comment]
@pixelzoom it looks like your detective-work is all correct, nice work.  Closing.
