### ISSUE TITLE
Remove Key Listeners for Joist

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#278]
This block of code and associated TODO needs to be tested.

```js
    // Add a key listener on the menu that will dismiss it when escape is pressed
    // TODO: Test this cross browser, regarding issues like http://stackoverflow.com/questions/1160008/which-keycode-for-escape-key-with-jquery
    this.addInputListener( {
      keydown: function( event ) {
        var keyCode = event.domEvent.keyCode;
        if ( keyCode === Input.KEY_ESCAPE ) {
          options && options.closeCallback && options.closeCallback();
        }
      }
    } );
```

**Comment by pixelzoom** [comment]
This code and TODO was added in fae0a34 on 1/12/15 by @samreid with comment "Improved accessibility support for popup dialogs".

**Comment by samreid** [comment]
This doesn't seem like it is working at all in osx+chrome+requirejs.  It was added for previous accessibility prototypes but I can't tell from the above snippet why it is not working--perhaps the phet menu does not receive focus and hence does not receive key input events?  Perhaps this code should be deleted until we can focus more effort on accessibility?  @jonathanolson and possibly @ariel-phet can you weigh in on this?

**Comment by jonathanolson** [comment]
Accessibility was disabled:
```js
        // temporary disabling
        if ( !this.display.options.accessibility ) {
          return;
        }
```

Also if there is no keyboard focus, it looks like it wouldn't fire anyways. AND keyboard focus would need to be on a that node or a descendant.

**Comment by samreid** [comment]
@jonathanolson What action do you recommend we take, if any?

**Comment by jonathanolson** [comment]
Since most other keyboard accessibility is disabled, we should probably leave the escape key for that disabled too. Up to you and @pixelzoom whether the code should be kept.

**Comment by samreid** [comment]
Let's get rid of it so we can address all accessibility things uniformly when it is time.

**Comment by samreid** [comment]
There are actually several key listeners in joist that fall into this same category, so I'll retitle the issue to "Remove key listeners from Joist" and hit them all at once.

**Comment by samreid** [comment]
I've removed them in my working copy, tested that hookes-law + grunt finishes properly and tested running the built version of hookes-law.  Everything seems good so I will commit shortly.

**Comment by samreid** [comment]
Completed above.  @jonathanolson can you review this and suggest if any other tests or work is necessary?  Would be good to do before Monday's molecule-shapes redeploy.

**Comment by jonathanolson** [comment]
Looks fine, can't particularly think of other related changes (closing).
