### ISSUE TITLE
iOS 9 Safari portrait orientation layout bug

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#280]
See https://github.com/phetsims/tasks/issues/269#issuecomment-120164376, notably after rotating to portrait and waiting until the resize, the navbar is too high (https://cloud.githubusercontent.com/assets/5090275/8608277/7ec50e40-2656-11e5-9314-06f1e016060e.PNG)

I'm tentatively marking this as high-priority and summer-redeploy, since it appears like it might be an iOS 9 issue that would affect all sims. @ariel-phet, since this is the iOS 9 Beta and could have updates, should the priority be downgraded?

**Comment by jonathanolson** [comment]
Bug present in released iOS 9, @ariel-phet I'm assuming this should be my top priority?

**Comment by jonathanolson** [comment]
Exact iOS version: iOS 9.0 (13A4254v)

**Comment by jonathanolson** [comment]
Unable to reproduce after many attempts on iPad 3 with iOS 9.0 (13A344). Unsure if it's related to the retina display.

The iPad 2 I used for testing did note that an update was also partially pending (and I see it has a different build/something number). Might be worth a re-test on Tuesday.

@samreid, are you available to test on your iPad sometime?

**Comment by samreid** [comment]
I just started downloading iOS9 for my iPad3 and will try to test within the next few business days.  I also created a tasks issue and assigned it to me to help it stay on my radar.

**Comment by samreid** [comment]
I do not see the tall navbar after rotation on ipad3 running iOS 9.0 13A344 testing bending light 1.0.0-dev.24.  I tested both single and multi tabs, same good behavior in both cases.

**Comment by jonathanolson** [comment]
I just verified that Tycho seemed to still be on the iOS 9 beta, and hadn't completed the iOS 9 update. I just went ahead and updated (13A344 now), and the bug is NOT present.

Does not seem to affect the latest iOS 9 version, closing.
