### ISSUE TITLE
Investigate fullscreen in iframe for Safari 6.2

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#281]
See https://github.com/phetsims/tasks/issues/286, where OS X 10.8.5 with Safari 6.2 supports fullscreen without iframes, but the iframe tag doesn't seem to apply here. Do we need the webkitfullscreen tag?

**Comment by jonathanolson** [comment]
@ariel-phet, what's the priority here?

**Comment by ariel-phet** [comment]
Mediumish...If we are going to be deploying fullscreen as a feature, it seems like this is the last known issue.

**Comment by jonathanolson** [comment]
Closing as not important, since for interoperable sims we can not support this platform.
