### ISSUE TITLE
Navigation bar layout

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#283]
I was under the impression that the navbar layout would be implemented approximately as follows:

First, we calculate the area screen buttons are going to take, and we set the title's maxWidth based on that.
Then during layout we apply a single scale to everything in the navbar besides the background (to match the height of the desired navbar), center the screen buttons and right-align the PhET Menu button. Thus if a vertically-constrained sim has its width changed, it would JUST reposition the buttons (not scale), and if a horizontally-constrained sim has its height changed, it would JUST change the scale. If width/height are changed both at once, both scale and positioning could change.

As it is now, individual elements are being repositioned and scaled differently based on layout. When the navbar gets smaller, the same **fixed global paddings** are applied, causing things to overlap when they didn't before, and changes our thresholds, AND we are applying the scale independently to three different nodes.

**Comment by pixelzoom** [comment]
Would have been nice to have this input during the weeks that I spent working on this. I know we discussed on the phone, but what you describe above is not what I have in the my notes from our (admittedly confusing) conversation.

@ariel-phet This is currently unassigned. Does it need to be assigned? Does it need to be completed for S2015R?

**Comment by ariel-phet** [comment]
@pixelzoom - seems like a good topic for developer meeting

**Comment by pixelzoom** [comment]
Unassigning. Since this is labeled "developer-meeting" it will automatically be reviewed at developer meeting.

**Comment by zepumph** [comment]
Discussed 8/6 dev meeting. Now is the time to address this issue. @jonathanolson will tackle this as a high priority, in accordance with his time working with statistics  and working with @pixelzoom.

**Comment by jonathanolson** [comment]
Assigning for @pixelzoom for review, see the above commit. Let me know if anything should be clarified, or if there are any issues.

**Comment by pixelzoom** [comment]
Looks great. Closing.
