### ISSUE TITLE
Rename phetLogo to logo

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#284]
phetLogo appears in a few places throughout joist.  However, this could be a 3rd party logo, an adapted-from-logo, etc.  We should rename it to be simply logo instead of phetlogo.

**Comment by samreid** [comment]
Renamed in my working copy and tested by running optics-lab in requirejs mode.  No problem observed.  I'll commit shortly.

**Comment by samreid** [comment]
Renamed above and also tested that lint is ok (it is).  @pixelzoom @jonathanolson @jessegreenberg @jbphet @aaronsamuel137 this was a small change but I'm wondering if anyone would be kind enough to review it?

**Comment by pixelzoom** [comment]
Visual inspection looks good. Closing.
