### ISSUE TITLE
Chrome/Safari mouse events lost outside iframe

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#285]
See https://github.com/phetsims/molecule-shapes/issues/127 for details.

No known fix at this point besides waiting, issue here mainly for tracking, or resolving in the future.

**Comment by jonathanolson** [comment]
It also looks like this may affect Safari, as noted in https://github.com/phetsims/scenery/issues/464.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/molecule-shapes/issues/127#issuecomment-125717354, @jonathanolson said:
> Chromium bug that causes the current behavior: https://code.google.com/p/chromium/issues/detail?id=269917
> 
> Not too much we can do at this point from our end. @ariel-phet, should an issue be created in joist/scenery and left open to note this as an all-sims-in-iframe-in-Chrome issue?

That was on 7/28/15, perhaps the Chrome bug has been fixed.  Or if not, perhaps we should report it.  

Assigning to @ariel-phet to decide how to proceed.

**Comment by ariel-phet** [comment]
I cannot reproduce this bug after trying quite a bit on latest Chrome. 

Closing
