### ISSUE TITLE
ScreenView.layout should trigger notifications

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#287]
For https://github.com/phetsims/bending-light/issues/162 I would like to receive a callback after ScreenView.layout has been called in order to update other views accordingly.  Listening to scenery `resize` event and screenView `transform` events (as done in RewardNode.js) is insufficient since it does not provide the layout parameters.  I'd recommend to use a Axon Events channel as a property, to be a general solution and to avoid collision with the inherited scenery channel.

**Comment by samreid** [comment]
Fixed above, can @jonathanolson or @pixelzoom please review?

**Comment by samreid** [comment]
I tested lint, grunt and launching hookes law with these changes and did not observe any issues.

**Comment by pixelzoom** [comment]
Change set looks good.

Should RewardNode.js be modified to use this approach? If so, please create an issue.

**Comment by samreid** [comment]
RewardNode is solving a related but different problem where the RewardNode may appear at any point in the scene graph, and hence it must accommodate arbitrary global to local transforms.  The solution above is for the case where the scene graph topology is known.  Anything else here?

**Comment by pixelzoom** [comment]
> case where the scene graph topology is known.

Can you give me a more specific example? So I can understand and apply in the future.

**Comment by samreid** [comment]
BendingLightView has an immediate child called singleColorLightCanvasNode.  I need to fit the canvas to the visible bounds, so I use:

```js
    this.events.on( 'layoutFinished', function( dx, dy, width, height, scale ) {
        bendingLightView.singleColorLightCanvasNode.setCanvasBounds( new Bounds2( -dx, -dy, width / scale - dx, height / scale - dy ) );
      }
    );
```

One concern I have is that it appears the dx, dy are in stage coordinates and width, height are pixel coordinates.  Hence the scaling in my callback.  If this is indeed true, perhaps we should put them in the same coordinate frame (stage?).

**Comment by pixelzoom** [comment]
Thanks for the example. 

Not sure about the coordinate frame issue, assigning back to @samreid to potentially create an issue. (Might want @jonathanolson feedback on that issue).  

Then feel free to close this issue.

**Comment by samreid** [comment]
I decided to change the args width & height to be in stage coordinates but still provide the scale, so that the pixel coordinates can be computed if necessary.  I'll document and commit shortly.

**Comment by samreid** [comment]
Changed as described above.  I also decided to use JSDoc to document the trigger since I didn't see any other suitable place to document it (even though this is somewhat unconventional for us).  @pixelzoom do you want to take a look?

**Comment by pixelzoom** [comment]
I'm not totally understanding this issue. As mentioned above, I think it would be best if you have @jonathanolson review.

**Comment by jonathanolson** [comment]
Looks good to me.
