### ISSUE TITLE
should "PhET Website" go to the sim page?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#288]
Should the "PhET Website" menu item take you to the sim's page on the website, rather than home page?

Related to #97.

**Comment by ariel-phet** [comment]
Should go to homepage. That has been our standard. I believe the reason is that if someone is just handed a sim link, they are then encouraged to see we have entire website of resources. Not just a single sim. Closing.

**Comment by pixelzoom** [comment]
Assuming you want to go to the translated version of the sim page... 

Change PhetMenu line 190 from this:

`var phetWindow = window.open( 'http://phet.colorado.edu', '_blank' );`

to this:

```
var url = StringUtils.format( ''http://phet.colorado.edu/{0}/simulation/{1}', [ sim.locale, sim.name ] );
var phetWindow = window.open( url, '_blank' );
```
