### ISSUE TITLE
SettingsDialog should extend Dialog

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#289]
Factored out of https://github.com/phetsims/joist/issues/166.

SettingsDialog currently extends ScreenView.  It should extend Dialog.

**Comment by pixelzoom** [comment]
This dialog is not currently used. And if/when it extends Dialog, I don't see much of the current implementation that will survive.  Recommended to delete SettingsDialog and its usage in PhetMenu. 

@samreid Your opinion?

**Comment by samreid** [comment]
I removed the SettingsDialog in the preceding commits.  As far as I know, we do not need to remove stale keys from babel.  @pixelzoom would you like to review the changes?

**Comment by pixelzoom** [comment]
👍 Closing.
