### ISSUE TITLE
look of close button for Dialogs

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#291]
Factored out of #166 (create a Dialog type).

https://github.com/phetsims/joist/issues/166#issuecomment-72100645 says:

> At 1/29/15 dev meeting, there was also discussion about trying this style of close button, like this example from least-squares-regression. (This may make centering problematic.)

![1451eb2c-a7bd-11e4-80ea-8a694a592815](https://cloud.githubusercontent.com/assets/3046552/9366699/081fbc82-4676-11e5-96d8-61e2c99cfa3a.png)

This is a look that (I believe) is used exclusively in sims that @jonathanolson has worked on.

This is a design issue. Assigning to @ariel-phet to decide how to proceed.

**Comment by ariel-phet** [comment]
Personally, I prefer this style of close button for a dialog (I think it is clean, flat, and modern looking), but I suggest bring it up at a status meeting to see pros/cons get a consensus from both designers and developers as well as KP. Assigning to @pixelzoom to bring up at 8/27/2015 design meeting (if that is OK).

**Comment by pixelzoom** [comment]
@ariel-phet Assuming that you mean 8/27/15 *dev meeting*... I'll be happy to bring it up. But this is not a developer-only decision.

**Comment by ariel-phet** [comment]
Sorry I meant status meeting. (multitasking...)

**Comment by pixelzoom** [comment]
Workaround for centering: Create the dialog such that it's origin is the center to the rounded rectangle. The use option.x and option.y to position.

**Comment by pixelzoom** [comment]
Dev meeting notes:

• @samreid would like to see other alternative designs
• @jbphet and I would like us to decide on 1 design, rather than supporting multiple looks
• I don't a preference between this design and red 'X" box.
• @jbphet and @jonathanolson prefer this design

**Comment by pixelzoom** [comment]
@ariel-phet Dev meeting notes above. Since I really don't have a strong preference how this looks, I'd prefer not to be involved. Please assign to someone else to flesh out the design and implement it.

**Comment by ariel-phet** [comment]
I will take a look with design team/Dave and settle on a design

**Comment by ariel-phet** [comment]
A consistent set of icons is being developed for the website, and Dave Underwood suggested we keep a similar look and feel. Below is the icon he likes best

![close_icon](https://cloud.githubusercontent.com/assets/4051174/9451698/60ea9e0e-4a6d-11e5-860c-4eb4298c87a9.png)

**Comment by ariel-phet** [comment]
@amanda-phet - since you were involved in least squares do you want to comment on placement of this icon in dialog boxes? I agree it would be best to settle on one standard.

**Comment by pixelzoom** [comment]
A solid-colored circle (in this case, black) will disappear on a background of the same color. Recommend to stroke it with white, as is done in the example shown in https://github.com/phetsims/joist/issues/291#issue-101978830.

**Comment by amanda-phet** [comment]
I agree with @pixelzoom that a stroke is needed in case the background is black. I like the above design for the x though. I don't have strong design preferences beyond that. 

Placement should be in the upper right corner since that is a standard on all website dialog boxes. I think the example from LSR is probably a little too dramatically outside of the rounded rectangle. Maybe something more like this? 
<img width="578" alt="screen shot 2015-08-24 at 2 49 10 pm" src="https://cloud.githubusercontent.com/assets/7852916/9452035/52c8187c-4a6f-11e5-8a96-3adad1e899f6.png">

**Comment by ariel-phet** [comment]
Looking good to me...lets make this the standard. 

@pixelzoom - still have an objection to implementing?

**Comment by pixelzoom** [comment]
> @pixelzoom - still have an objection to implementing?

I haven't been involved in the implementation of joist.Dialog. My role was to triage #166 and identify sub-issues that hadn't been addressed.

**Comment by pixelzoom** [comment]
> @pixelzoom - still have an objection to implementing?

I didn't want to be involved in the design because I didn't have a strong opinion on the options, and I have way too much other work to do. I haven't been involved in the implementation of joist.Dialog. My role was to triage #166 and identify sub-issues that hadn't been addressed. @jonathanolson did the implementation.

**Comment by ariel-phet** [comment]
@pixelzoom - yes, I knew about the design, just thinking about implementation, thanks for the info. I will make a topic for developer meeting.

**Comment by samreid** [comment]
My recommendation for implementing this shape: implement the close button shape as a general scenery node, perhaps in scenery-phet, so that it can easily be reused in different contexts as necessary.

**Comment by ariel-phet** [comment]
From Dave:

>I'd say keep the icon inside the bounds of the box. That would seem to keep things less cluttered, and I think clutter is always the enemy.

**Comment by jbphet** [comment]
Let's have PhET tackle this in design meeting.  @jonathanolson was the original implementer and would be down with representing the dev team in design meetings.  @ariel-phet - can you put this on the agenda for design meetings until resolved?

**Comment by ariel-phet** [comment]
Roger

**Comment by samreid** [comment]
Brainstorming, here's one way to keep the button inside the dialog and integrate it with the dialog shape:

![image](https://cloud.githubusercontent.com/assets/679486/9648758/40a5c6a8-51a9-11e5-829c-f8c5f6274da0.png)

**Comment by emily-phet** [comment]
Just a thought, after discussions about keyboard navigation, you might want to also consider options for what the "x" looks like when focused on.

**Comment by amanda-phet** [comment]
smaller circle, black circle with white rounded x, sticking outside of rounded rectangle, roughly 2/3 of the circle is "inside" the rectangle. 

Focus could be a rectangle, or circle, or the circle could change color. 

OR

x will be *inside* the dialog box, no circle, title will wrap around so as not to interfere with the x, if there is no title then the context will be pushed down below the x.

**Comment by samreid** [comment]
We discussed many things today.  One item I thought was clean and simple would be like this screenshot:

![save](https://cloud.githubusercontent.com/assets/679486/9671368/a41a7d5e-524f-11e5-8e82-75dd3a49d6d5.png)

It got an upvote from @jbphet and @kathy-phet said she was fine with it.

There were also other suggestions from others and I was unclear whether there was any consensus.

**Comment by ariel-phet** [comment]
unassigning until this issue come up again, seems minor compared to other larger issues currently.

**Comment by pixelzoom** [comment]
This issue is superseded by #359. Look of the close button will be specified in the Dialog design documents (https://docs.google.com/document/d/12UkhG7lU-dLBCa-A8FcamkrPBLQxr6ft33Igbw6a5U8/edit#).

Closing.

**Comment by pixelzoom** [comment]
This got moved to #359, but has not been addressed. Reopening because the "closed" state gives the illusion that this was fixed, and it is not.

**Comment by pixelzoom** [comment]
3/29/18 dev meeting: @andrea-phet and I will triage this issue.

**Comment by pixelzoom** [comment]
The button shown in https://github.com/phetsims/joist/issues/291#issuecomment-137578788 (a simple 'x') is basically what was decided on.  See the Dialog design doc for specifics.

Closing, this is being handled in https://github.com/phetsims/joist/issues/413 (Add 'close' buttons to all dialogs).
