### ISSUE TITLE
Update check fails with HTTPS/HTTP mismatch in Chrome

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#295]
```
Mixed Content: The page at 'https://phet.colorado.edu/sims/html/molecule-shapes/latest/molecule-shapes_en.html' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://phet.colorado.edu/services/check-html-updates'. This request has been blocked; the content must be served over HTTPS.
```

Should be fixed by using '//phet.colorado.edu' instead of 'http://phet.colorado.edu', so that the browser uses the current protocol.

**Comment by jonathanolson** [comment]
This is also a bit tricky to test, since spot redirects HTTPS to HTTP (so it can't be used for testing dev/RC releases).

**Comment by samreid** [comment]
Will this change what happens for file:// ?

**Comment by jonathanolson** [comment]
> Will this change what happens for file:// ?

I'll check.

**Comment by jonathanolson** [comment]
file:// still makes an online request for the correct file, but there's another issue running with file://. I'll also verify, running from phet.colorado.edu.

**Comment by jonathanolson** [comment]
Actually, it wasn't quite working, AND Hewlett's Google Analytics tracker was also failing with the file:// protocol (but not our main google analytics code).

I've fixed both of those above, and tested on file://, http:// and https://. Should be ok, but will add to the developer agenda (are redeployments needed?)

**Comment by pixelzoom** [comment]
molecule-and-light needs to pick this up, @jbphet will handle.

ph-scale and ph-scale-basics already picked this up for 1.2.0-rc.1.
