### ISSUE TITLE
Implement setChildren/setVisible using Node.setExcludesInvisible

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#298]
We currently have custom logic to handle setChildren/setVisible for screens in Joist.  But this can be replaced by new scenery feature Node.setExcludesInvisible.  Marked for developer-meeting to prioritize.

**Comment by pixelzoom** [comment]
If anyone else is looking for this... It's `Node.setExcludeInvisible` (singular).

**Comment by pixelzoom** [comment]
9/8/15 dev meeting:

SR: joist feature is used by BAM and ESPB.
JO: This has been set to `true` for ScreenView for awhile. So joist feature may no longer be needed.
SR: Will delete joist feature.

**Comment by samreid** [comment]
There is a comment from @jonathanolson in build-a-molecule-main that says:

> on iPad3/iOS7 the default 'setVisible' screen switching strategy fails for this sim with an out of memory Safari crash.

Still, I think we were aware of that when we decided to remove the feature anyways.  @jonathanolson correct me if wrong, please.

**Comment by samreid** [comment]
Energy Skate Park: Basics launches fine on the iPad with the setVisible strategy, so I've committed that change above.

Build a molecule (built version) gets to the homescreen, but when showing a sim screen it is blank on the iPad3 with the setVisible strategy.

Running with ?screens=1 (and setVisible strategy), it launches OK.  So don't we still need this feature or an equivalent workaround for Build a Molecule?

**Comment by samreid** [comment]
By the way, there is a huge incentive to remove this feature from Sim.js because it will save us 65 lines of code.

**Comment by jonathanolson** [comment]
It's also causing a quirk in BAM, since https://github.com/phetsims/joist/issues/304 (Phet Button link position) will only work in the normal (setVisible) children strategy.

I'll be looking at this with higher priority.

**Comment by jonathanolson** [comment]
Removed layerSplits in BAM, and took it off of setChildren. It's working  on my iPad 3 now, feel free to remove this feature.

**Comment by samreid** [comment]
Fixed in my working copy by removing the `screenDisplayStrategy` property and defaulting to the behavior for setVisible instead of setChildren.  All changes are isolated to Sim.js.  I tested Acid Base Solutions before and after this change and it seems to be working properly.  I'll commit shortly.

**Comment by samreid** [comment]
Fixed above. This seemed straightforward and since I know others are busy I'm inclined to close the issue.  Still this is a change to a central class Sim.js and @jbphet @jessegreenberg @jonathanolson @pixelzoom should feel free to reopen + review the change if desired.

**Comment by pixelzoom** [comment]
I'd like to take a look, since I'm not totally clear on what was done and why.

**Comment by pixelzoom** [comment]
Yo comprendo, closing.
