### ISSUE TITLE
Global namespace option for debugging/together

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#300]
Creates things like phet.sun.CheckBox dynamically, so that it's easy to get global references to types.

Added developer-meeting tag to discuss.

**Comment by samreid** [comment]
This issue overlaps with https://github.com/phetsims/tasks/issues/378 "pattern for namespacing"

**Comment by pixelzoom** [comment]
9/29/15 dev meeting:
• @jonathanolson this can go away once we've namespaced things as in phetsims/tasks#378 
• @samreid  this handles images too, but that doesn't seem too important

**Comment by jonathanolson** [comment]
Will be repurposed for assertions in other issues.
