### ISSUE TITLE
PhET button changes position

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#304]
PhET button is shifted slightly right on the home screen, compared to its position on the navigation bar. To reproduce, switch between any screen and the home screen, watch the PhET button move back and forth.  This is a problem on all platforms, with all brands.  Noted in joist 5d0e22ec246ca7fa4e0af4ff4657dbb654cb15e4.

Assigning to @ariel-phet to prioritize.

**Comment by ariel-phet** [comment]
Nice catch @pixelzoom - I had not noticed this before. Not a high priority, but if it is easy to fix I would match the position that occurs within the sim itself. Is this something that would be quick for you to take care of? If not, please assign back to me.

**Comment by pixelzoom** [comment]
This was introduced in 7729853 by @jonathanolson. The layout for the PhET button was changed in NavigationBar, but not in HomeScreenView.

**Comment by pixelzoom** [comment]
I took a quick look at this, and it's not obvious to me why the layout in NavigationBar (line 217) is different for "expanded" vs "compact" (or what those refer to).  Assigning to @jonathanolson.

**Comment by ariel-phet** [comment]
Ah, this must have been when we were dealing with internationalization issues

**Comment by pixelzoom** [comment]
Yes, specifically #283.

**Comment by jonathanolson** [comment]
@ariel-phet, @samreid and @pixelzoom, if we want the same positioning of the PhET button, can we switch to having the navigation bar still visible on the home-screen, but make the sim title/screen buttons/home button invisible?

It seems tricky and problematic to position the phet button in two different places (since only one may get changed like this case).

If we need to keep it similar to how it is now, we could have the home screen's phet button ask the navigation bar where its phet button is positioned, and mimic the transform.

Thoughts?

**Comment by samreid** [comment]
I'd investigate the "navbar on the homescreen" idea.  It would make things simpler to have only 1 phetbutton instance in the sim, and also simpler to have it so that each screen has a navbar (though the visible contents of the navbar may be different).  You may also want to set the navbar fill to be null, to handle issues where the home screen color is changed (say in the future for projector mode or something like that).

Also, do we still have a different phet logo for on white background vs black background?  If so, and if you go ahead with the "one phet button instance" idea, then the phet button may need to be able to change its logo from one to the other.

**Comment by pixelzoom** [comment]
@jonathanolson asked:
>  can we switch to having the navigation bar still visible on the home-screen, but make the sim title/screen buttons/home button invisible?

Since the only thing that we are ever likely to want visible on the home screen is the PhET menu, this seems like a questionable (but perhaps unavoidable?) way to accomplish that.  But if you do proceed with this:

(1) You'll need to make the navigation bar itself invisible too, unless you go through the trouble of changing its color to match the home screen background.

(2) If additional things are added to the navigation bar in the future, we will need to remember to hide them for the home screen.  I guess we can discover that by running a sim, but it would be nice if that were made less likely to happen, or easier to fix (perhaps by adding all "not for the home screen" nodes to a common parent node).

**Comment by jonathanolson** [comment]
Just also tested, and the current Molecule Shapes / Charges and Fields "WebGL warning" node can move over where the navigation bar is, so it's also a potential design issue. It also looks like a headache to refactor the home screen to be more like other screens with the navigation bar.

With the maintainability points made by @pixelzoom and uncertainty about future design, I'm leading now towards duplicating the transform, with a public API method on NavigationBar.

Objections?

**Comment by ariel-phet** [comment]
Just to comment, this seems to me to be a low priority...it is aesthetically objectionable, but it can also be lived with. If it improves the structure and cleanliness of the code, I am for it, if not, I would say punt currently.

**Comment by jonathanolson** [comment]
I'll leave assigned. Changes to have the navbar be visible (with some things hidden) may be cleaner after major refactoring, but it's not an easy fix.

As it's low priority, dropping this off my current radar.

**Comment by samreid** [comment]
I'm ok with the "use the same transform" idea.

**Comment by pixelzoom** [comment]
I thought there was a joist issue regarding complexity that's added by treating HomeScreen differently than other Screens, but I can't find the issue. I've definitely run into that issue repeatedly when making joist changes. It seems like it would be advantageous to treat the HomeScreen instance as screens[0] for multi-screen sims, instead of having tests like `if ( sim.homeScreen )` throughout Sim.js. My point is, perhaps we should have a type hierarchy where all Screens have a PhET button, and non-Home screens have a navigation bar. Ie, the PhET button is not part of the navigation bar. But that will have its own set of problems.

**Comment by ariel-phet** [comment]
This seems developer meeting worthy...will plan it for Thursday

**Comment by samreid** [comment]
> My point is, perhaps we should have a type hierarchy where all Screens have a PhET button, and non-Home screens have a navigation bar. Ie, the PhET button is not part of the navigation bar. But that would have its own set of problems.

Or... each sim has *one* PhETButton that appears in the rootNode (in front of navbar, in front of homescreen).  That could make layout tricky (having something in the navbar just to the left of the PhETButton, say).

**Comment by jonathanolson** [comment]
Will apply the transform copying change.

**Comment by jonathanolson** [comment]
Applied the described fix.

I ended up opting to make the phetButton property on HomeScreenView AND NavigationBar public (joist-internal), as they are both constructed before either are added to the rootNode. This means I can't create a TransformTracker in NavigationBar and only export that.

All locations are documented with the reasoning for why they are public, with references to this issue.

@pixelzoom, can you verify, and comment if you have a preferred visibility/export pattern for the needed information?

**Comment by pixelzoom** [comment]
Yields that desired result and implementation looks reasonable. But in light of https://github.com/phetsims/joist/issues/208 ("move stuff out of Sim.js"), do we really want to put this in Sim.js?  Maybe move `linkPhetButtonTransform` to PhetButton, with this signature:

`function linkPhetButtonTransform( homeScreen, navigationBar, rootNode )`

... then call it from Sim.js like this:

`this.linkPhetButtonTransform( this.homeScreen, this.navigationBar, this.rootNode );`

Would that be acceptable?

**Comment by jonathanolson** [comment]
Sure, will do.

**Comment by pixelzoom** [comment]
How about @param doc for PhetButton.linkPhetButtonTransform?

**Comment by jonathanolson** [comment]
Sorry about that! Fixed, let me know if there's anything else.

**Comment by pixelzoom** [comment]
:+1:

**Comment by jonathanolson** [comment]
Reopening, seems to be a bug in build-a-molecule:

![bam-phet-button](https://cloud.githubusercontent.com/assets/480878/11262701/9d26c6b6-8e3f-11e5-9c9d-39998a513486.PNG)

I'll be looking into it.

**Comment by jonathanolson** [comment]
Moved BAM off of setChildren strategy, closing. Will rely on https://github.com/phetsims/joist/issues/298 removing the "broken" code.
