### ISSUE TITLE
add namespace

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#306]
See https://github.com/phetsims/tasks/issues/378

**Comment by jonathanolson** [comment]
I'll take care of the joist namespacing.

**Comment by pixelzoom** [comment]
I'll take care of this.

**Comment by pixelzoom** [comment]
I completed namespacing joist, but ran into something different with UpdateCheck.js, which looks like this:

```js
 // NOTE: singleton type!
  function UpdateCheck() {
  ...
  }
  ...
  return new UpdateCheck();
}
```

Note that it's returning an instance, not the constructor. 

Adding `joist.register( 'UpdateCheck', UpdateCheck )` resulted in this console.log with `?ea&checkNamespaces`:

`joist.UpdateCheck is different than the expected namespaced object`

I resolved this by registering the singleton instance, like so:

```js
```js
 // NOTE: singleton type!
  function UpdateCheck() {
  ...
  }
  ...
  var instance = new UpdateCheck();
  joist.register( 'UpdateCheck', instance ); 
  return instance;
}
```

But is this what we want? Assigning to @jonathanolson for comment.

**Comment by pixelzoom** [comment]
@jonathanolson replied on Skype:
> That sounds like what we'd want, as that's what's exposed with JOIST/UpdateCheck

Closing.
