### ISSUE TITLE
About dialog overlay is solid gray on Android+Firefox

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#31]
Nexus 7, Android 4.2.2, Firefox 22.0, Beer's Law Lab 1.0.0.

When you select PhET>About, the overlay behind the About dialog is solid gray, can't see anything in the play area. It's supposed to be translucent.

**Comment by jonathanolson** [comment]
Not a problem anymore for latest build and require.js on Nexus 7 (2012) with Firefox 35, closing.
