### ISSUE TITLE
Wrong default for Dialog

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#313]
While investigating https://github.com/phetsims/joist/pull/312 I noticed that in practice, all of our Dialog subclasses and instantiations use `modal:true` (aside from the demo).  Perhaps we should make `modal:true` the default if it is so popular?  I'll assign for the next developer meeting, but it would be great to discuss and decide before that, if @pixelzoom @jbphet @jonathanolson @jessegreenberg want to offer opinions.

**Comment by pixelzoom** [comment]
In most toolkits that I've worked with (X11, Motif, Swing,...) dialogs are modeless (i.e. non-modal) by default.  Not to say that we couldn't do something else, but I believe that joist.Dialog should be migrated to sun.  And sun is supposed to be useful beyond PhET.

**Comment by samreid** [comment]
Good argument about sun being useful outside of PhET, I'm OK to close this issue but will leave it open for now in case @jbphet @jonathanolson @jessegreenberg have other opinions.

**Comment by pixelzoom** [comment]
12/29/15 consensus is to keep as non-modal by default, and eventually move Dialog to sun (see #315).
