### ISSUE TITLE
move joist.Dialog to sun

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#315]
Factored this issue out of https://github.com/phetsims/joist/pull/312 and https://github.com/phetsims/joist/issues/313.  

Dialogs are a useful part of any general UI toolkit, so joist.Dialog should be moved to sun.

**Comment by pixelzoom** [comment]
This is trickier than it looks.
(1) There's a lot of `window.phet.joist.sim` stuff in Dialog.js, deep dependencies on joist.
(2) Where should the responsibility for modality lie?

**Comment by pixelzoom** [comment]
12/29/15 sounds like a lot of work, deferring.

**Comment by samreid** [comment]
When we work on this, we may be able to create an abstraction in sun like `DialogContainer` which can be reused by joist and other sun clients.

**Comment by pixelzoom** [comment]
Folded this issue into https://github.com/phetsims/joist/issues/359.  Closing.

**Comment by pixelzoom** [comment]
This got moved to #359, but has not been addressed. Reopening because the "closed" state gives the illusion that this was addressed, and it is not.

**Comment by pixelzoom** [comment]
I see that additional dependencies on joist have been added for a11y.  This is absolutely the wrong direction to be going with Dialog.   Labeling for discussion at developer meeting.

**Comment by pixelzoom** [comment]
As a first step in Dialog cleanup... How about if we remove the dependencies on joist and move it to sun?  Then start redesign/reimplementation there.

**Comment by jonathanolson** [comment]
I have no objections. Presumably we'd want to add glass-pane equivalents for the full sim and each screen, and have the client responsible for positioning the dialog? (And if it's modal, hooking into a common code way of having a barrier?)

**Comment by jessegreenberg** [comment]
Sounds good to me.

> Presumably we'd want to add glass-pane equivalents for the full sim and each screen, and have the client responsible for positioning the dialog

Yes, which will also be in sun.

**Comment by samreid** [comment]
@jonathanolson says one of the costs of moving files across repos is losing history.  We'll keep track of where it moved from, as a paper trail in case we need older history.

**Comment by pixelzoom** [comment]
Here's what we'll need to test after moving Dialog and DialogIO:


curve-fitting
ReducedChiSquaredStatisticDialog.js

equality-explorer
OopsDialog.js
SolveItScene.js
InfoDialog.js
SolveItSceneNode.js

gene-expression-essentials
FluorescentCellsPictureDialog.js

joist
DialogsScreenView.js
AboutDialog.js
Dialog.js
DialogIO.js
KeyboardHelpDialog.js
OptionsDialog.js
OptionsDialogIO.js
UpdateDialog.js

make-a-ten
InfoDialog.js

masses-and-springs
EnergyGraphNode.js

models-of-the-hydrogen-atom
SnapshotsDialog.js

molecules-and-light
SpectrumWindowDialog.js

pendulum-lab
EnergyLegendDialog.js

plinko-probability
OutOfBallsDialog.js

scenery-phet
ContextLossFailureDialog.js

sun
Dialog.js
DialogIO.js

vegas
RewardDialog.js

**Comment by pixelzoom** [comment]
Work completed by @andrea-phet and myself.  A couple of things that we weren't clear on how to test:

@jessegreenberg Please test KeyboardHelpDialog and check off in the above list. 

@zepumph Anything to test related to OptionsDialogIO?  Check off in the above list.

**Comment by pixelzoom** [comment]
We found KeyboardHelpDialog in john-travoltage, so that's done.

**Comment by pixelzoom** [comment]
Slack:

Chris Malley [5:15 PM]
We moved Dialog and DialogIO to sun.  OptionDialogIO extends DialogIO.  Any testing required for DialogIO or OptionsDialogIO ?


Michael Kauzmann [5:15 PM]
checking
Looks good to go. Checking it off the list

Chris Malley [5:16 PM]
thanks.

**Comment by pixelzoom** [comment]
Reopening. We neglected to move DialogsScreenView (demo app) to sun.
