### ISSUE TITLE
Dialog: visibility of this.modal

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#316]
Dialog.js line 59:

```js
    // @private
    this.isModal = options.modal;
```

Shouldn't this be `@private (read-only)`?  Or can a dialog's modality change after it's been instantiated.

Assigning to @samreid since he added this annotation.

**Comment by pixelzoom** [comment]
Since it's @private, it's not a big deal.  I'll stick a `(read-only)` on there for good measure.

**Comment by samreid** [comment]
@pixelzoom added (read-only) in 168eaa64189b68c111aa93db3fafa669645efbea

This is correct, you should not be able to change modality at runtime.  (Or if we later add that as a feature we can re-address this).
