### ISSUE TITLE
Dialog: visibility of this.isShowing

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#317]
Dialog.js line 62:

```js
    // @public - whether the dialog is showing
    this.isShowing = false;
```

I don't see this field used anywhere outside of Dialog, and suspect that it should be `@private`.

Assigning to @samreid since he added this annotation.

**Comment by samreid** [comment]
Thanks @pixelzoom I was confused by the isShowing of PhetMenu.js which has different visibility.  Dialog.js annotation should be fixed above.
