### ISSUE TITLE
add assertions to Sim.showPopup and hidePopup

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#318]
In Dialog.js, `this.isShowing` is used to guard against whether `show` or `hide` are called improperly:

```js
    // @public
    show: function() {
      if ( !this.isShowing ) {
        window.phet.joist.sim.showPopup( this, this.isModal );
        this.isShowing = true;
      }
    },

    // @public
    hide: function() {
      if ( this.isShowing ) {
        window.phet.joist.sim.hidePopup( this, this.isModal );
        this.isShowing = false;
      }
    }
```

This is fine. But `show` and `hide` rely on more general functions in Sim, `showPopup` and `hidePopup` respectively.  And those functions may be used by other clients, and contain no guards against calling them incorrectly. 

Recommendations:

(1) Add this assertion to Sim.showPopup:

`assert && assert( !this.topLayer.isChild( node ) );`

(2) Add this assertion to Sim.hidePopup:

`assert && assert( this.topLayer.isChild( node ) );`

Assigning to @jonathanolson since he added these functions in fa5a352157b3eb55ca512aef70ce65511bac4773.

**Comment by jonathanolson** [comment]
Sounds good, added them.
