### ISSUE TITLE
Edge 25 NavBar and Menu problems

### ISSUE THREAD

**Issue by phet-steele** [phetsims/joist#321]
@jonathanolson or whoever works on joist issues, there's a problem occurring in most (or all) of our sims' NavBar scene selection and menus. I am **only** seeing this in Edge 25.10586.0.0 (not earlier versions). You won't see the issue immediately upon opening the sim, you must interact with the NavBar (and menu). The issue is that scene names are being cut short:

![navbarcut](https://cloud.githubusercontent.com/assets/5863899/13097434/3c638040-d4de-11e5-94f8-18f8e852caa9.PNG)

and the ellipses move over the text:

![menucut](https://cloud.githubusercontent.com/assets/5863899/13097463/7a68c224-d4de-11e5-91b4-e8f5a6740f97.PNG)

Troubleshooting information:
Name: ‪Reactants, Products and Leftovers‬
URL: http://phet.colorado.edu/sims/html/reactants-products-and-leftovers/latest/reactants-products-and-leftovers_en.html
Version: 1.1.1 2016-02-13 09:55:56 UTC
Features missing: touch
Flags: pointerEnabled
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586
Language: en-US
Window: 1920x963
Pixel Ratio: 1/1
WebGL: WebGL 0.96
GLSL: WebGL GLSL ES 0.96
Vendor: Microsoft (Internet Explorer)
Vertex: attribs: 16 varying: 15 uniform: 512
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"3921bc37","branch":"HEAD"},"axon":{"sha":"fffc6c30","branch":"HEAD"},"babel":{"sha":"3975503a","branch":"master"},"brand":{"sha":"3b236d6f","branch":"HEAD"},"chipper":{"sha":"6735d265","branch":"HEAD"},"dot":{"sha":"5c39b7d8","branch":"HEAD"},"joist":{"sha":"2a5b44c4","branch":"HEAD"},"kite":{"sha":"84e84bca","branch":"HEAD"},"nitroglycerin":{"sha":"ef8c55a2","branch":"HEAD"},"phet-core":{"sha":"73a034c6","branch":"HEAD"},"phetcommon":{"sha":"20ce6f04","branch":"HEAD"},"reactants-products-and-leftovers":{"sha":"815f0d38","branch":"HEAD"},"scenery":{"sha":"c0c08ec5","branch":"HEAD"},"scenery-phet":{"sha":"61d8e7ed","branch":"HEAD"},"sherpa":{"sha":"be8c4fc9","branch":"HEAD"},"sun":{"sha":"267450f1","branch":"HEAD"},"tandem":{"sha":"e98bd8c3","branch":"HEAD"},"vegas":{"sha":"e5d21051","branch":"HEAD"},"vibe":{"sha":"40a28182","branch":"HEAD"}}

**Comment by phet-steele** [comment]
@jbphet this may be a more pressing, general issue concerning more than just the NavBar. Screenshot from Neuron 1.0.0-rc.4:

![neuron](https://cloud.githubusercontent.com/assets/5863899/13156029/bd80338e-d63d-11e5-9078-ab5696c95023.PNG)

Like the original comment, you have to move your cursor, with concentrations checked, for this to happen. Moving the cursor around also drastically lowers performance.

**Comment by jonathanolson** [comment]
Fixes have been released, closing.
