### ISSUE TITLE
layoutFinished args seem awkward

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#323]
The signature is:

```js
this.events.on( 'layoutFinished', function( dx, dy, width, height ) {
```

To put something in the bottom right it is:

```js
      // Float the resetAllButton to the bottom right
      resetAllButton.mutate( {
        right: -dx + width - 10,
        bottom: -dy + height - 10
      } );
```

Why is this dx/dy/width/height instead of a rectangle?  Having to subtract dx seems odd.

**Comment by samreid** [comment]
I marked this for developer meeting to see what other developers would like for this API.  But also, @jonathanolson @jessegreenberg @pixelzoom @jbphet please feel free to chime in sooner!

**Comment by pixelzoom** [comment]
Here's the current doc in joist.ScreenView:

```js
        /**
         * Trigger notifications that the visible bounds have changed, in case any clients need to update the views.
         *
         * @param {number} dx - the horizontal offset in stage coordinates
         * @param {number} dy - the vertical offset in stage coordinates
         * @param {number} width - the width of the entire visible area in stage coordinates
         * @param {number} height - the height of the entire visible area in stage coordinates
         * @param {number} scale - the scale factor between stage coordinates and pixel coordinates
         * @public
         */
        this.events.trigger( 'layoutFinished', dx, dy, width / scale, height / scale, scale );
```

I've never used this feature before.  And before I can recommend a better API, I need to understand the current API.  Questions:
(1) The doc for params `dx` and `dy` makes no sense to me - "offset" of what, and relative to what? 
(2) What are "stage coordinates" and "pixel coordinates"?  Afaik, this is the only place whether the term "stage" is used.  Is "stage" synonymous with "layoutBounds"?

**Comment by samreid** [comment]
We should switch this to use a visibleBoundsProperty in ScreenView.js

**Comment by samreid** [comment]
And for clients that need "scale", it should be a Property too.

**Comment by samreid** [comment]
I converted the `layoutFinished` event to a `visibleBoundsProperty`, updated Circuit Construction Kit, Bending Light and Pendulum Lab usages and tested.  Lint is passing and I don't see any problems in the sims.  For Pendulum Lab, I tested that the new layout values exactly matched the previous layout values.

I'll close this issue and create a developer meeting note about this new API.
