### ISSUE TITLE
Consider replacing "About" translation credits link with direct reference

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#326]
Since you're running the sim in one translation, it would make sense to just directly display credits for THAT translation (instead of having a link that shows credits for all translations).

**Comment by samreid** [comment]
Yes, @jonathanolson's recommendation makes good sense.  Directing to our site may have advantages though, like providing a nearby button that says "contribute translations", but I don't think we are leveraging this too much.

**Comment by pixelzoom** [comment]
The current link was implemented in https://github.com/phetsims/joist/issues/163. 

Hooke's Law (for example) goes to http://phet.colorado.edu/es_PE/for-translators/translation-credits#hookes-law-header

What would the proposed change ("just directly display credits for THAT translation") link to?

**Comment by jonathanolson** [comment]
> What would the proposed change ("just directly display credits for THAT translation") link to?

It wouldn't link to anything. It would only show translator information for that specific locale inline in the dialog.

**Comment by pixelzoom** [comment]
It seems like assuming 1 translator per locale is an assumption that is likely to bite us in the future.  

Why is the current solution not sufficient?

**Comment by jonathanolson** [comment]
> It seems like assuming 1 translator per locale is an assumption that is likely to bite us in the future.

The website I think internally handles multiple translators, and those could be listed in the About dialog.

> Why is the current solution not sufficient?

Seems very bulky. Requires an external link that goes to a page which then has to be scanned to find the locale.

**Comment by jessegreenberg** [comment]
3/10/16: Translation credits will be left as is.

The link takes you to a list of translations for the given sim.  In order to do this, it would complicate the build process.  Information would also come from Rosetta and we want to keep those details private.

The current solution has been working well, no complaints from translators so far.
