### ISSUE TITLE
Dialog windows shown by PhetMenu leak memory

### ISSUE THREAD

**Issue by jbphet** [phetsims/joist#329]
If I run a test where start up a sim and then use the button in the lower right to pop up the PhET menu, then select "About..." and then "Check for Updates..." several times each, and then capture a heap snapshot, the count for each of these dialog windows matches the number of times that it was brought up.  This would seem to imply that these dialogs are not getting garbage collected and are causing memory leaks.

This was found in the process of pursuing and testing https://github.com/phetsims/tasks/issues/546 and https://github.com/phetsims/joist/issues/327, and may help explain some of the leaking that we are observing.

**Comment by jbphet** [comment]
Here are a couple of screenshots from tests where I opened the About and Check for Updates dialogs four times each:

![dialog-leak-1](https://cloud.githubusercontent.com/assets/3082831/13962071/f76daada-f024-11e5-9d14-b7ad00355108.PNG)
![dialog-leak-2](https://cloud.githubusercontent.com/assets/3082831/13962076/fe0e3c42-f024-11e5-8cda-95e5b1cc6015.PNG)

**Comment by jbphet** [comment]
Assigning to @samreid, since this is joist code and since he just fixed a similar issue with PhetMenu.

**Comment by samreid** [comment]
@jbphet recommended bumping the priority

**Comment by jbphet** [comment]
True, mainly because having no memory leaks in the common code makes it easier to detect them and track them down in sim-specific code.

**Comment by samreid** [comment]
It seems like opening the about dialog 5 times in blast creates a 0.9MB memory leak:

![image](https://cloud.githubusercontent.com/assets/679486/14298529/b6e4422a-fb42-11e5-92d0-99279c389cdd.png)

Test procedure.  Open blast.  Take 5 memory snapshots.  Open about dialog 5 times.  Take 5 memory snapshots. I am taking multiple memory snapshots since the first 1-2 seem unstable.

**Comment by samreid** [comment]
Dialog has `sim.on( 'resized', updateLayout );` but never removes this listener.  Still, after removing this listener attachment, the problem is still present.

**Comment by samreid** [comment]
There are also independent leaks in these lines, or usage of those vars:

```js
      var upToDateNode = UpdateNodes.createUpToDateNode( positionOptions );
      var outOfDateNode = UpdateNodes.createOutOfDateAboutNode( positionOptions );
```

**Comment by samreid** [comment]
Putting the `upToDateNode` in children creates a memory leak.  Creating it but not adding to children, there is no leak...

**Comment by samreid** [comment]
Fixed one leak source above, but there is still at least one other source for AboutDialog leaks, as described in https://github.com/phetsims/joist/issues/329#issuecomment-206043397

**Comment by samreid** [comment]
One of the retainers "map descriptors", may be a chrome bug according to https://groups.google.com/forum/#!topic/google-chrome-developer-tools/-tBvJaaVMHc

**Comment by samreid** [comment]
Well, running with the chrome optimizations disabled, and with canary, I am still seeing the leak.

Commenting out the rectangle's FontAwesomeNode child makes the leak disappear:
```js
new FontAwesomeNode( 'check_without_box', { fill: '#fff', scale: 0.38, centerX: 10, centerY: 10 } )
```

**Comment by samreid** [comment]
Commenting out the shape caching in FontAwesomeNode.getShapeByName eliminates the AboutDialog memory leak.

**Comment by samreid** [comment]
I'm getting to a point where assistance from @pixelzoom @jbphet @jonathanolson or @jessegreenberg would be helpful.

One possibility would be to stop caching icons in Font Awesome Node, but it would be best to understand what is causing the root of the problem.

**Comment by samreid** [comment]
The FontAwesomeNode shape cache has a reference to the Shape.
The Shape extends Events, and uses:
```js
subpath.onStatic( 'invalidated', this._invalidateListener );
```

Commenting out this line in isolation does not prevent the memory leak.

**Comment by samreid** [comment]
In discussing this with @jonathanolson and @jbphet, @jonathanolson identified that the memory leak is due to the FontAwesomeNode's Path adding a reference to the cached Shape.

If FontAwesomeNode is typically used for button icons, it may not be too important to cache the shapes.

We could check to see if any FontAwesomeNodes were relying on the caching, to boost performance there we could reuse FontAwesomeNodes in sim code.

Add a note: why not to cache the shapes in FontAwesomeNode

**Comment by samreid** [comment]
@jonathanolson based on our discussion yesterday, I thought adding a `copy()` call in FontAwesomeNode like so would resolve the memory leak, but it does not:

```js
  var getShapeByName = function( iconName ) {
    if ( !shapeCache[ iconName ] ) {

      // create the shape for what we'll consider 'unity' scale
      shapeCache[ iconName ] = new Shape( icons[ iconName ] ).transformed( SHAPE_MATRIX );
    }
    return shapeCache[ iconName ].copy();
  };
```

Can you hypothesize why?  I also tried copying the bounds in the implementation of Shape.copy, but there is still a leak.

**Comment by samreid** [comment]
I'm seeing some 6/21 places where FontAwesomeNode is constructed dynamically in the UI and hence a delay would be undesirable.  I could measure the delay and see if it is acceptable, but I also looked at adding a `staticShape` option to Path, which would skip adding listeners:

```js
// at the end of Path.js constructor:


    // @private
    this.staticShape = options.staticShape || false;

    this.setShape( shape );

    this.mutate( options );
  }
```

and

```js

    // sets the shape drawn, or null to remove the shape
    setShape: function( shape ) {
      if ( this._shape !== shape ) {
        // Remove Shape invalidation listener if applicable
        if ( !this.staticShape && this._shape ) {
          this._shape.offStatic( 'invalidated', this._invalidShapeListener );
        }

        if ( typeof shape === 'string' ) {
          // be content with setShape always invalidating the shape?
          shape = new Shape( shape );
        }
        this._shape = shape;
        this.invalidateShape();

        // Add Shape invalidation listener if applicable
        if ( !this.staticShape && this._shape ) {
          this._shape.onStatic( 'invalidated', this._invalidShapeListener );
        }
      }
      return this;
    },
```

However, I am hesitant to increase the complexity of one of our core scenery classes.

@jonathanolson can you advise?

**Comment by samreid** [comment]
We discussed this at today's meeting.  Current sentiment is that we should:

* Remove caching from FontAwesomeNode
* Test performance on sims that are dynamically creating FontAwesomeNode
* In the future investigate `Node.dispose`

**Comment by samreid** [comment]
I'll assign this to @jbphet for now, @jbphet please do as much of steps 1-2 above as you wish, then reassign to me when complete.

**Comment by jbphet** [comment]
I disabled caching in FontAwesomeNode by commenting out the code so that it can be easily restored if needed.  I added documentation and a TODO that should serve to remind us to remove it permanently or put it back at some point.  I tested the the portions of Energy Skate Park Basics and Reactants Products and Leftovers that dynamically create FontAwesomeNodes and noticed no significant performance degradation on my Dell XPS laptop running Win 10 using Chrome, Firefox, and Edge.  I also tested on iPad2+iOS9.3 (Witten) and iPad3+iOS9.3 (Disessa) and couldn't discern any performance difference versus the currently published versions.

I saw FontAwesomeNodes in Circuit Construction Kit, but that sim isn't published, so I didn't test it.

Assigning to @samreid for review and, if necessary, further discussion.

**Comment by samreid** [comment]
Sounds great @jbphet, let's close this issue.

**Comment by samreid** [comment]
@jbphet my inclination is to remove the commented out code in FontAwesomeNode.js.  If we trace performance problems to FontAwesomeNode initialization in the future, we can re-evaluate or check history.  Sound OK?

**Comment by jbphet** [comment]
Sounds good, I went ahead and completely removed the caching code and added a comment about why caching isn't done (with a link to this issue) so that the problem isn't accidentally reintroduced.  I'll go ahead and close this issue but @samreid can feel free to review if so inclined.

**Comment by jbphet** [comment]
A note to anyone who looks at this in the future and is considering reintroducing caching into FontAwesomeNode: If dispose functions are added to Scenery nodes and used properly, caching of shapes will no longer cause memory leaks and the caching could be added back.
