### ISSUE TITLE
Investigate phetAllocation alternatives for memory/GC analysis

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#330]
Most browsers have tools for investigating memory leaks (more than creation of objects), and phetAllocation only touches certain types.

During collaboration with @jessegreenberg on performance, we patched this into require.js' execCb function, resulting in phetAllocation being able to watch creation of almost every type:

``` js
        var result = callback.apply( exports, args );
        if ( typeof result === 'function' ) {
          return new Proxy( result, {
            construct: function( target, argumentsList ) {
              window.phetAllocation && window.phetAllocation( name );
              return Reflect.construct( target, argumentsList );
            }
          } );
        }
        else {
          return result;
        }
```

It can't detect function closure creation or other problems, and it's unwieldy to patch require.js when this needs to be done, so I think looking into alternatives would be helpful.

**Comment by samreid** [comment]
What is Chrome DevTools lacking?

**Comment by samreid** [comment]
We no longer use requirejs, and the Chrome Dev Tools have helped me address recent memory leaks.  I recommend to close this issue, but @jonathanolson please reopen if you disagree.
