### ISSUE TITLE
Home screen icons drift

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#331]
Discovered by @phet-steele. Fuzzing for a few minutes makes it very obvious:

![acid-base-solutions-rise](https://cloud.githubusercontent.com/assets/480878/14368651/56844e8e-fcdc-11e5-9762-9e24e991a991.PNG)

Likely to be buggy re-layout code? I'll take a look.

**Comment by samreid** [comment]
In the above commits, I added a "band-aid" that resets the top of the icons each time they layout, which fixes the problem.  We should still investigate the cause, but this band-aid should be sufficient to proceed on https://github.com/phetsims/tasks/issues/546

**Comment by pixelzoom** [comment]
If you add a workaround that you intend to someday address properly, it's generally a good idea to add a TODO (which notes the issues number) in the code at the site of the workaround.  I'll add the TODO.

And yes, we should investigate the cause.

**Comment by pixelzoom** [comment]
After working on #332 and #337, I can see how this would cause drift.   Addressed, closing.
