### ISSUE TITLE
home screen leaks memory when switching between selections

### ISSUE THREAD

**Issue by jbphet** [phetsims/joist#332]
The file `HomeScreenView.js` contains the following code:

``` js
    sim.screenIndexProperty.link( function( screenIndex ) {

      //Space the icons out more if there are fewer, so they will be spaced nicely
      //Cannot have only 1 screen because for 1-screen sims there is no home screen.
      var spacing = sim.screens.length === 2 ? 60 :
                    sim.screens.length === 3 ? 60 :
                    33;

      var icons = _.map( screenChildren, function( screenChild ) {return screenChild.index === screenIndex ? screenChild.large : screenChild.small;} );
      center.children = [ new HBox( { spacing: spacing, children: icons, align: 'top', resize: false } ) ];
      center.centerX = homeScreenView.layoutBounds.width / 2;
    } );
```

This creates a new HBox every time the screen index changes.  Because the icons have a reference to the previous HBox, the previous HBox is still a reachable object and is thus never garbage collected.

To see the leak in action, add the line

``` js
      console.log( 'screenChildren[0].largeIcon.parents.length = ' + screenChildren[ 0 ].large.parents.length );
```

to the closure above (currently around line 245 in `HomeScreenView`).  Then, start up a sim with at least two screens and switch back and forth between the first and second icons.  When I did this, I got the following output:

```
enabling assert
HomeScreenView.js?bust=1460489253627:245 screenChildren[0].largeIcon.parents.length = 1
HomeScreenView.js?bust=1460489253627:245 screenChildren[0].largeIcon.parents.length = 1
2HomeScreenView.js?bust=1460489253627:245 screenChildren[0].largeIcon.parents.length = 2
2HomeScreenView.js?bust=1460489253627:245 screenChildren[0].largeIcon.parents.length = 3
2HomeScreenView.js?bust=1460489253627:245 screenChildren[0].largeIcon.parents.length = 4
2HomeScreenView.js?bust=1460489253627:245 screenChildren[0].largeIcon.parents.length = 5
2HomeScreenView.js?bust=1460489253627:245 screenChildren[0].largeIcon.parents.length = 6
2HomeScreenView.js?bust=1460489253627:245 screenChildren[0].largeIcon.parents.length = 7
HomeScreenView.js?bust=1460489253627:245 screenChildren[0].largeIcon.parents.length = 8
```

The number of parents is increasing because the HBox that previously contained the icon is still a parent, and therefore the icon still has a reference to it.

**Comment by jbphet** [comment]
I added a simple fix for this - retaining a reference to the previously allocated HBox and removing its children when it's replaced - but I think @jonathanolson (who figured out where this was coming from in the first place) may have had a different fix in mind.  Assigning to him to review, modify, and/or elaborate upon.

**Comment by jbphet** [comment]
Issue https://github.com/phetsims/tasks/issues/546 is kind of a parent issue for this one, since it is a general issue about tracking down memory leaks.

**Comment by pixelzoom** [comment]
Keeping a reference to the HBox is unnecessary.  The parent Node (`iconsParent`) is an intermediate Node, which exists solely to maintain rendering order. `iconsParent` has only 1 child, so simply verify that there's only 1 child, removeAllChildren, then addChild the new HBox. 

I also cleaned up the computation of `spacing`.  It only needs to be computed once, and the the computation was unnecessarily complex. 

@jbphet Please review the above commit.

**Comment by jbphet** [comment]
This change reintroduces the memory leak.  The leak results not because of a lingering reference to the HBox from its parent node, but from the child nodes, and those nodes - the screen icons - are retained.

I verified this by using the test described https://github.com/phetsims/joist/issues/332#issue-147851036.  You can also set a breakpoint in the closure, look at the parent of the first icon, and see the buildup of HBox parents.  From the console, it looks something like this:

```
> screenChildren[ 0 ].large.parents
[HBox, HBox, HBox, HBox, HBox]
```

**Comment by jbphet** [comment]
If the idea of retaining a reference to the HBox is bothersome, the changes could be kept and you could call `iconsParentNode.children[0].removeAllChildren` in the closure before removing the children from `iconsParentNode`, but I'm not sure that is an improvement over just keeping the reference around.

**Comment by pixelzoom** [comment]
I'll have a look on Monday.

**Comment by pixelzoom** [comment]
I restored the closure variable for the HBox and the call to `HBox.removeAllChildren`, so that icons don't end up keeping a reference to the HBox (their parent). @jbphet please review.

This issue demonstrates what I think is a general problem - the 2-way parent-child references can make it difficult and error-prone to "prune" the scene graph.  I've created https://github.com/phetsims/scenery/issues/592 to discuss adding something to scenery to make this easier.

**Comment by jbphet** [comment]
The changes in @pixelzoom's commit above look good, and I re-tested to verify that there is no leak when switching between active home screen icons.  Closing.
