### ISSUE TITLE
make home screen handle > 4 screens

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#334]
The home screen currently seems to have a limit of 4 screens.  When a 5th screen is added, layout is tight, see screenshot below from function-builder.  Since "Faraday's Electromagnetic Lab" has 5 screens and is likely to be ported in the not-too-distant future, this needs to be addressed.

![screenshot_26](https://cloud.githubusercontent.com/assets/3046552/15163658/fc026eaa-16c6-11e6-9f16-e6b54af874d0.png)

**Comment by pixelzoom** [comment]
Navigation bar looks fine with 5 screens:

![screenshot_27](https://cloud.githubusercontent.com/assets/3046552/15163739/87b78d90-16c7-11e6-8cc4-a7137217cfa7.png)

**Comment by samreid** [comment]
At today's meeting @samreid volunteered to work on this.

**Comment by samreid** [comment]
Fixed above, @pixelzoom can you please review?

**Comment by pixelzoom** [comment]
👍 Closing.
