### ISSUE TITLE
Show progress indicator while JS loading

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#348]
From #68 we would like to show progress of the JS loading.  For this part, we will get discrete steps, roughly N+M, where N is the number of screens and M is the number of other non-screen steps.

**Comment by samreid** [comment]
I demonstrated a prototype of this in #68 and am interested in taking next steps toward production.  This will require the following steps:

1. Check in proposed changes to a branch
2. Code review from another developer, possibly @schmitzware @jbphet or @pixelzoom.  Perhaps @mattpen could review the HTML part.
3. Functional testing from QA team to make sure the requirejs and built versions launch properly
4. Support from the design team to decide exactly what it should look like
5. Fine tuning and pixel polishing.

**Comment by samreid** [comment]
OK, with the 2 commits above (in progress-indicator branches for chipper + joist), builds will include a loading progress indicator.  To show the loading progress indicator for requirejs mode, you will need to include the svg code from chipper/templates/sim.html into the sim.

```html
<div id="progressBar" style="position:absolute;top:50%;left:50%;margin-left:-120px;margin-top:120px;width:200px;height:10px">
  <svg>
    <rect id="progressBarBackground" x="10" y="10" width="200" height="10" rx="8" ry="15"
          style="stroke: white;"></rect>
    <rect id="progressBarForeground" x="10" y="10" width="0" height="10" rx="8" ry="15" style="fill:#fee105;"></rect>
  </svg>
</div>
```

I'll add a todo to the above steps to update the `generate-development-html` template with this as well.

**Comment by samreid** [comment]
I'm happy with the progress in the branches and the code is ready for review.  @ariel-phet can you please review the steps in https://github.com/phetsims/joist/issues/348#issuecomment-245194269 to see what work remains, who will need to be involved--and let us know your recommendations for scheduling next steps?

**Comment by samreid** [comment]
Specific review questions (in addition to general review):
1. Is there a better way to position the progress bar?
2. Should the progress bar styling be provided through CSS classes, or inline `style=...`
3. Should we try to add a `workItem` (see Sim.js) for any work that happens before SimLauncher is called?

**Comment by ariel-phet** [comment]
@samreid I suggest doing a simple version (ideally without the word loading and only your progress bar) and showing at status meeting to get some quick designer feedback. I think we want to keep this animation simple and clear, nothing fancy.

**Comment by ariel-phet** [comment]
Also marking for dev meeting so we can discuss a bit more (and decide on review and such).

**Comment by samreid** [comment]
@jbphet volunteered to review the changes to Sim.js

**Comment by samreid** [comment]
I will hold off work until @jbphet completes his review and/or we get the branch back to master.

**Comment by jbphet** [comment]
I've reviewed the changes to Sim.js, and they look good for the most part.  Here are some minor suggestions:

[ ] document where the value for PROGRESS_BAR_INDICATOR comes from (e.g. // intended to be slightly larger than logo)
[ ] suggest naming runItem to runWorkItem or doWorkItem

I'd also like to test this a bit in some different situations before "signing off" on it, but was unable to run sims when switching joist to the progress-indicator branch.  I suspect that this is due to some recent changes to the master branch of joist.  Assigning to @samreid to decide whether to pull those changes on master into progress-indicator so that this can be tested.  I have a strong preference to do this testing, but @samreid can argue against if the thinks it will be too time consuming and/or tricky to pull in the changes from master that will enable this to run.

**Comment by samreid** [comment]
I added the progress bar to chipper's branch and merged changes into joist's branch and everything appears to be working.  To test:

1. check out chipper and joist branches
2. cd to a sim
3. grunt generate-development-html
4. launch sim as requirejs
5. grunt
6. launch sim in built mode

> I'd also like to test this a bit in some different situations before "signing off" on it

I couldn't agree more, let's make sure this strategy is viable, then get it back to master soon-ish so we can continue improving it without risk of diverging branches.

**Comment by jbphet** [comment]
I've tested this on the branches with a 4-, 2-, and 1-screen sim, and it pretty much worked in all cases.  The one thing that I noticed that was a little odd was that sometimes the progress bar did not fill in all the way before the home screen appeared.  Perhaps not a huge deal, but it would be nicer if it was consistent.  This happened a lot on the single screen sim (Charges and Fields), a little on the 2-screen sim (Balancing Chemical Equations), and I never saw it on the four-screen sims (ESPB and Expression Exchange).  I saw this on both Chrome and Firefox, which were the only two browsers I tested.

Back to @samreid to decide whether this is worth addressing.

After that, the next step would be to have @mattpen review the HTML.  I looked at it briefly, and there are a lot of hard coded values, and it would be nice if these could be changed to allow the progress bar to scale and position more automatically with the icon, but I'm not fluent enough in HTML to know how doable this would be.  Hence @mattpen.

After that, we would want to have the QA team test this on all supported platforms before moving it to master.

**Comment by jessegreenberg** [comment]
@samreid would you mind if we added some accessibility markup to the progress bar?  I have never tested before, but a ```<progress>``` html element exists, and there is also an aria role for ```progressbar```.  I have never tried either, but they should add information for the screen reader.  I will quickly try them out.

**Comment by samreid** [comment]
I have some reservations/questions but am not opposed to investigation.  I'll jot down my thoughts here so I don't forget:

1. Is the loading bar a visual enhancement or meant to convey meaningful semantic information?
2. When running a sim with assistive technology, should the first thing the user hears be "loading progress 15% 30% 60%" or a few seconds of silence followed by the sim title and description?
3. We may not be able to animate the `<progress>` element and style it as we wish, see #349, though aria role should still work for svg.

**Comment by jessegreenberg** [comment]
In response to the above:
 1. Only meant to provide semantic information.
 2. The first thing the AT reads is always the page title, which is "Loading simulation-name-here" at the moment.  I'm not sure if we can even get around this. It could continue to read the loading bar status.
 3. Yes, i quickly ran into that, good point.

Here is what I found from testing:
- Testing ```<progress>``` element:
  - Suffers from issue 3 above.
  - JAWS does not support this element
- Testing ```role=progressbar```
  - Very cool in NVDA + Firefox!  Firefox adds sonification to the element adding 'beeps' as ```aria-valuenow``` goes up.
  - Sort of cool in JAWS, JAWS reads the ```aria-valuenow``` number to the user.
  - NVDA and JAWS require delays in runItem setTimeout, NVDA needs ~150ms and JAWS needs ~5000ms to work properly. I don't think this is acceptable.
- Testing a ```<p aria-live="assertive"></p>``` element
  - Announces anything we want, tested with "Loading Forces and Motion: Basics, progress bar 20, 40, 60, 80, 100"
  - Sim is usually done loading before we get to 20.

Based on all this, I think we should not do this, each option has too many drawbacks and it doesn't enhance accessibility all that much.  I think it would be more helpful if we look into just announcing when the sim has finished loading.    User could hear "Loading sim.." then "Sim finished loading".

**Comment by jessegreenberg** [comment]
> After that, we would want to have the QA team test this on all supported platforms before moving it to master.

A maintenance version of forces-and-motion-basics will soon be ready for RC testing.  If the progress bar is ready for testing, it could be tested along with that RC.

**Comment by samreid** [comment]
There is a bit of a maintainability issue that start() adds a workItem.  We should try to create all work items up front (or at least know how many there are) so we can properly advance the progress bar.  Part of the hassle is that new Sim() and sim.start() are separate--we may benefit from joining them.

**Comment by samreid** [comment]
Perhaps saving the work items until start is called would be best.  I'll investigate that next.

**Comment by samreid** [comment]
In the above commits, I did the following:
* separated model and view into separate steps
* pause slightly between steps, and after all steps complete
* simplifications
* Util.linear for mapping progress

@jbphet can you please review the new proposal, and test on a few sims?

**Comment by jbphet** [comment]
I tested the progress indicator on requireJS and built versions of 1, 2, 3, and 4 screen simulations using Chrome and Firefox.  The sims were:
+ Friction
+ Acid Base Solutions
+ Balancing Act
+ Forces and Motion Basics

The progress bar functioned correctly on all simulations, and I felt like the timing of the animation was good.  There is some pixel polishing needed to make this a good size, but it looks like the basic functionality is all working well at this point.  I assume the pixel polishing will be done with the design team, and at that point we probably should discuss the exact timing, since there are some tweaks that can be done here as well.

Upon reviewing the code, I noticed a couple of triggers that seem potentially redundant or out of order.  The are ```this.trigger0( 'simulationStarted' )``` and ```this.trigger0( 'endedSimConstructor' )```.  I'll log a separate issue for this.

I went through some of the code with @samreid and we updated some comments to make things a little more clear.

There are also some instance of commented-out code and some comments that could be improved, so I think we should do another review before merging this into master, but the approach seems reasonable and the result - i.e. the behavior of the progress bar - is looking good IMO.

**Comment by jbphet** [comment]
Also, during the conversation with @samreid I suggested considering ```_.after``` as a way to clearly separate out the code for the portion that needs to be done after all the work items are complete.  He wasn't too keen on it and will likely not use it, but may keep it in mind as a possibility as we move forward.

**Comment by samreid** [comment]
> [@samreid] wasn't too keen on [_.after]

In this context, all of the actions are sequential, so we can easily track when they are done without using _.after.

**Comment by samreid** [comment]
Unassigning until November as @ariel-phet suggested in https://github.com/phetsims/special-ops/issues/40

**Comment by jbphet** [comment]
It's November, so I'm assigning to @ariel-phet.  If the design team has time, it might be good to put this up in design meeting and start refining it.  I hate to have it linger on this branch for too long, or it may become hard to merge into master, and it seems pretty close at this point.

Another consideration is whether it is okay to roll this out a little at a time as sims are published or whether we'd need to try to do maintenance releases on all published HTML5 sims.  I'd prefer the former, since we're all a little strapped for time these days.

**Comment by samreid** [comment]
> maintenance releases on all published HTML5 sims

Also, it is a nontrivial change to joist and our loading sequence, so maintenance releases sound very expensive.

**Comment by ariel-phet** [comment]
@samreid do you have time at some point to do some refinement with me? I think we all agreed this feature should be clean and minimalist. I think it will work fine for you and I to iterate and then bring up at status meeting as the proposed solution.

Perhaps lets you and I work together once you polish off the queryStringMachine work?

As for maintenance releases, that is not necessary, we can just roll things out as we update them or publish them.

**Comment by samreid** [comment]
> @samreid do you have time at some point to do some refinement with me?

> Perhaps lets you and I work together once you polish off the queryStringMachine work?

Sure, how about 10am on Wednesday Nov 30?

**Comment by ariel-phet** [comment]
@samreid that works well, on my calendar

**Comment by pixelzoom** [comment]
From https://github.com/phetsims/joist/issues/49...  The progress indicator should be displayed for a minimum amount of time.

**Comment by pixelzoom** [comment]
From #309:  Everything in a PhET simulation scales to fit the window except the splash screen logo/text. Should this scale as well?

**Comment by samreid** [comment]
@ariel-phet and I are meeting to refine the progress indicators, I created "progress-indicator-2" branches to continue.  I need to create an issue branch for that.

**Comment by samreid** [comment]
- [ ] We should make sure the progress bar fills to the end.

**Comment by samreid** [comment]
- [ ] PhET-iO logo should have "loading..." removed and be resized to match the width of the main logo.

**Comment by samreid** [comment]
The QA team should test this on:
Windows + Chrome/Firefox/Edge/IE11
Mac + Chrome/Firefox/Safari
iPad + Mobile Safari

I'll prepare a dev version.

**Comment by samreid** [comment]
Brand bought itself a branch in the above commit.

**Comment by samreid** [comment]
ESPB Dev is here:
http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.2.4-dev.1/energy-skate-park-basics_en.html

**Comment by samreid** [comment]
Faraday's law is here:
http://www.colorado.edu/physics/phet/dev/html/faradays-law/1.3.7-dev.1/faradays-law_en.html

**Comment by samreid** [comment]
I created new branch issues.  The "progress-indicator" branches are deprecated, to be used for reference only and can be deleted when this issue is closed.

**Comment by samreid** [comment]
By popular demand: here is the progress indicator in white:

http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.2.4-dev.2/energy-skate-park-basics_en.html

**Comment by samreid** [comment]
Blue wins, we'll move forward with that.

**Comment by samreid** [comment]
Testing completed in https://github.com/phetsims/tasks/issues/744 and we are approved to merge to master.

**Comment by samreid** [comment]
I merged the 3 branches and generated new development html.

A few things left to do here: https://github.com/phetsims/joist/issues/348#issuecomment-245194269 and I need to delete the remote branches from these repos.

**Comment by samreid** [comment]
Branches deleted, closing.
