### ISSUE TITLE
Screen name should be optional

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#351]
Related to https://github.com/phetsims/joist/issues/339...

`Screen` constructor currently has a `name` parameter, which is the name of the screen that is displayed to the user.  For single-screen sims, this is never displayed.  And what single-screen sims appear to be doing is using the sim name for the screen name. (See for example (e.g. john-travoltage-main.js.) 

TODO:
- [ ] Move `name` to `options`, with default `null`.
- [ ] Where screen.name is required in joist, assert that it is non-null.

**Comment by pixelzoom** [comment]
Since this and #339 both involve changing the signature of `Screen` constructor, it would be most efficient to do them at the same time.

**Comment by pixelzoom** [comment]
`screen.name` is used in these joist files: 

HomeScreenView
NavigationBarScreenButton

**Comment by pixelzoom** [comment]
@samreid We'll have to address this bit of code, which assumes that the home screen is the only screen with `name === null`:

```js
    // Home screen does not use tandem in its options, since tandem is required in joist.
    if ( name !== null ) {
      Tandem.validateOptions( options ); // The tandem is required when brand==='phet-io'
    }
```

**Comment by pixelzoom** [comment]
This was done at the same time as https://github.com/phetsims/joist/issues/339.  @jbphet since that issue is assigned to you for verification, please do this one at the same time.

**Comment by pixelzoom** [comment]
Above I said:
> This was done at the same time as #339. @jbphet since that issue is assigned to you for verification, please do this one at the same time.

#339 is closed. @jbphet what is the status of this one?

**Comment by jbphet** [comment]
I spot checked a number of the commits and they look reasonable, and this has been in operation for a while with no reports of issues, so I think it's safe to close.
