### ISSUE TITLE
should screen icons be validated by Screen?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#352]
Related to #339...

Icons for home screen and (optional) navigation bar are provided to the `Screen` constructor.  But they are currently not validated by Screen.  Navigation bar icon is validated in `NavigationBar`.  Home screen icon isn't validated at all - it's possible to use an icon with completely bogus size and aspect ratio.   

Questions:
• Should validation of both icons be done by `Screen`?
• Or should we add validation of home screen icon to `HomeScreenView`?

Since the validation is (currently) similar for both icons, it may be preferable to handle validation of both icons in `Screen`, rather than spread the validation out across `HomeScreenView` and `NavigationBar`.   On the other hand, the implementation of `HomeScreenView` and `NavigationBar` dictates the requirements for their respective icons, so it may be preferable to validate the icons where they are used.

**Comment by pixelzoom** [comment]
Consensus: Validate in Screen.

**Comment by pixelzoom** [comment]
Skype discussion:
> [9/8/16, 3:27:03 PM] Chris Malley: As I'm adding icon validation to joist.Screen (https://github.com/phetsims/joist/issues/352), I'm finding a number of sims whose home icon has dimensions smaller than Screen.HOME_ICON_SIZE.  build-an-atom, CLB, CCKBBS, energy-forms-and-changes,...   Screen.HOME_ICON_SIZE is documented as "optimal" size (whatever that is) while Screen.NAVIGATION_BAR_ICON_SIZE is documented as minimum size.  Any thoughts on how to proceed?  I'm inclined to treat Screen.HOME_ICON_SIZE as minimum size and file bug reports for failing sims.
[9/8/16, 3:29:17 PM] Sam Reid: How big are the discrepancies?  How difficult would it be to get all of the icons to be the same size?
[9/8/16, 3:29:37 PM] Sam Reid: (all home screen icons same size as each other, all navbar icons same size as each other).
[9/8/16, 3:30:24 PM] Chris Malley: Some are ridiculously off. seasons (for example) has home screen icon 21.1279296875x12
[9/8/16, 3:30:59 PM] Chris Malley: Screen.HOME_SCREEN_ICON_SIZE is new Dimension( 548, 373 )
[9/8/16, 3:32:25 PM] Chris Malley: Only 6 sims fail: build-an-atom, capacitor-lab-basics, CCK-BBS, energy-forms-and-changes, fraction-comparison, seasons.  Other failures are in chains, scenery-phet, sun (all easy to fix).  So I'm inclined to create issues for the failing sims.
[9/8/16, 3:32:32 PM] Sam Reid: Me too
[9/8/16, 3:33:19 PM] Sam Reid: Fraction Comparison and Seasons can use the new “Default Icons” when they are ready.
[9/8/16, 3:33:27 PM] Chris Malley: yes.
[9/8/16, 3:34:26 PM] Chris Malley: ditto energy-forms-and-changes
[9/8/16, 3:36:28 PM] Chris Malley: CCK-BBS appears to be using navbar icons for the home screen, 147x100.
[9/8/16, 3:37:55 PM] Chris Malley: build-an-atom 485x331, capacitor-lab-basics: 412x280 (both a little small)
[9/8/16, 3:38:41 PM] Sam Reid: Let’s put assertions in joist, and let them fail until they are fixed.
[9/8/16, 3:39:29 PM] Chris Malley: I'll fix as many as I can, then make issues for the others.

**Comment by pixelzoom** [comment]
Work completed, summary:

• Validation of the home screen icon has been added to Screen.
• Validation of the navigation bar icon has been relocated from NavigationBar to Screen.
• Fixed assertion failures in sims, and created issues for the 2 that I couldn't easily fix (issues immediately above.)

@samreid would you mind reviewing, since our discussion makes you most familiar with this.

**Comment by samreid** [comment]
This is looking good, in the above commit I also separated asserts and added docs to make it more readable.  I also recommend to (1) remove this logic, since it seems like an unnecessary complication:

```js
    // If the navigation bar icon is the same as the home screen icon, it doesn't need to be validated because the
    // homescreen icon size is larger than the navbar icon size and the aspect ration is the same.
    if ( options.navigationBarIcon !== options.homeScreenIcon ) {
```

And I recommend to (2) factor out the size validation code, I'll do these steps in a few moments.  

One other review comment, here is code from NavigationBarScreenButton

```js
assert && assert( screen.name, 'name is required for screen ' + screens.indexOf( screen ) );
assert && assert( screen.navigationBarIcon, 'navigationBarIcon is required for screen ' + screen.name );
```

Here is code from HomeScreenView
```js
assert && assert( screen.name, 'name is required for screen ' + sim.screens.indexOf( screen ) );
assert && assert( screen.homeScreenIcon, 'homeScreenIcon is required for screen ' + screen.name );
```

It looks like `navigationBarIcon` will always be non-null, so can the second of these asserts be removed?

Leaving assigned to myself while I complete (1) and (2) as described above.

**Comment by samreid** [comment]
Also, I'm seeing:

```js
var HOME_SCREEN_ICON_SIZE = new Dimension2( 548, 373 ); // minimum size
```

If this is truly a minimum size, perhaps we should rename the var to indicate as such.

**Comment by samreid** [comment]
The above commits (1) remove logic for whether to validate the navigation bar screen icon and (2) factor out the validation code.  @pixelzoom back to you.

**Comment by pixelzoom** [comment]
Changes look good. 

About the naming issue in https://github.com/phetsims/joist/issues/352#issuecomment-246395172... 
If we want to rename, we should do so for both HOME_SCREEN_ICON_SIZE (56 occurrences) and NAVBAR_ICON_SIZE (11 occurrences). How about HOME_SCREEN_ICON_MINIMUM_SIZE and NAVBAR_ICON_MINIMUM_SIZE, respectively?

**Comment by samreid** [comment]
How about:

```js
var MINIMUM_HOME_SCREEN_ICON_SIZE;
var MINIMUM_NAVBAR_ICON_SIZE;
```

**Comment by pixelzoom** [comment]
@samreid I made the change as you suggested in https://github.com/phetsims/joist/issues/352#issuecomment-247981061, but...

I had suggested HOME_SCREEN_ICON_MINIMUM_SIZE because (awhile back) we agreed to standardized var and option names like `xMin`, `yMinSize`, etc. versus `minX`, `minYSize`.  And the other constants in Screen are (e.g.) `HOME_SCREEN_ICON_ASPECT_RATIO`, and `HOME_SCREEN_ICON_MINIMUM_SIZE` seemed to follow that pattern.   To my eye, the new names are inconsistent with our naming decision, and inconsistent with other internal constant names. 

Thoughts?

**Comment by samreid** [comment]
> (awhile back) we agreed to standardized var and option names like `xMin`, `yMinSize`, etc. versus `minX`, `minYSize`

I am fine to use `HOME_SCREEN_ICON_ASPECT_RATIO` etc.  Also, I did not know that our decision to standardize var names like `xMin` etc extended outside of scenery options.

**Comment by pixelzoom** [comment]
Sorry, I was wrong about this: https://github.com/phetsims/joist/issues/352#issuecomment-248021016.  Looking at sun, scenery-phet, etc. our decision was apparently to standardize on (e.g.) `minX`, `minXSize`, `minXPadding`.   So the new constant names are fine.

Closing.  If I missed anything, feel free to reopen.
