### ISSUE TITLE
fix tandem handling in Screen and HomeScreen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#353]
Prerequisite to addressing #339 and #351.

Tandem handling looks suspect in Screen and HomeScreen.  Work with @samreid to fix this.

**Comment by pixelzoom** [comment]
@samreid and I worked on this together. Verified with instance-proxies wrapper. Closing.

**Comment by pixelzoom** [comment]
Reopening. Something still doesn't look right here. `HomeScreen` is passing all of its options to `HomeScreenView`, including a tandem - which seems wrong.  @samreid can you take a look?

**Comment by pixelzoom** [comment]
Here's where HomeScreen is instantiated in Sim:

```js
this.homeScreen = new HomeScreen( this, tandem.createTandem( 'homeScreen' ), {
        warningNode: options.homeScreenWarningNode,
        showSmallHomeScreenIconFrame: options.showSmallHomeScreenIconFrame
      } );
```

Unfortunately, both of these options are intended to be passed on to HomeScreenView.  Can we just cherry pick these options and pass them like this in HomeScreen?

```js
      // createView
      function() {
        return new HomeScreenView( sim, tandem.createTandem( 'view' ), 
          _.pick( [ 'warningNode',  'showSmallHomeScreenIconFrame' ], options );
      },
```

**Comment by samreid** [comment]
Fixed as @pixelzoom suggested (but note different order for `pick` args), @pixelzoom would you like to review?

**Comment by pixelzoom** [comment]
Looks good. (Sorry about the order of `pick` args, I was going from memory.)

Closing.
