### ISSUE TITLE
Screenshot feature captures things that aren't displayed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#356]
This was discovered by @phet-steele while testing Plinko Probability (https://github.com/phetsims/tasks/issues/702).  I've reproduced it on Mac+Chrome, Mac+FF, Mac+Safari.  I have not investigated other platforms.

The Screenshot feature does not appear to respect the bounds of CanvasNode, and what appears in the screenshot may be different from what is rendered on the screen.

Steps to reproduce:
(1) Start plinko-probablity with ?maxBallsIntro=1000
(2) Go to the Intro screen
(3) Select the "x All" radio button for the hopper
(4) Press the Play button
(5) Wait for the balls to fill up above the bottom edge of the hopper. What's rendered on the screen will look something like this:

![screenshot_19](https://cloud.githubusercontent.com/assets/3046552/18649539/4311d5c4-7e7d-11e6-945a-f5177b7dbf70.png)

(6) Select "Screenshot" from the PhET menu. The resulting screenshot will look something like this:

![plinko probability screenshot 1](https://cloud.githubusercontent.com/assets/3046552/18649570/6801ad28-7e7d-11e6-9889-9fae9ce10a09.png)

Notice that the screenshot shows balls _above_ the bounds of the CanvasNode.

In this specific sim, the situation shown in the above screenshot will never happen - it's causes by setting a query parameter that is exclusively for development test.  But many PhET sims use CanvasNode, and if they are relying on bounds, then this could be a significant problem.

Assigning to @ariel-phet to prioritize and assign.

**Comment by pixelzoom** [comment]
In the above example, the balls are rendered using BallsNode, a subtype of CanvasNode.

**Comment by samreid** [comment]
I saw something like this in a common library test homescreen.

**Comment by pixelzoom** [comment]
Do you mean something like sun or scenery demo application?

**Comment by samreid** [comment]
Yes, I didn't catch exactly which it was but saw something odd in the aqua screenshots.  I'll add myself to assignments to see if it is replicable and which it was.

**Comment by ariel-phet** [comment]
@samreid is the screenshot implementation something you are reasonably familiar with?

**Comment by ariel-phet** [comment]
Putting at medium priority for the moment

**Comment by samreid** [comment]
> @samreid is the screenshot implementation something you are reasonably familiar with?

Negative.

**Comment by ariel-phet** [comment]
@jonathanolson please give your thoughts

**Comment by jonathanolson** [comment]
I'll improve CanvasNode documentation to make this clear, but CanvasNode implementations (subtypes) should fulfill the contract:

- CanvasNode subtypes' paintCanvas should NEVER draw anything outside of the current canvasBounds.

The canvasBounds are used to determine what area of the screen the actual Canvas needs to cover, and what area needs to be cleared and repainted if (in the future again) Scenery partially redraws Canvases.

This CanvasNode in the sim appears to be drawing outside of the canvasBounds, and that causes the difference between the display and the screenshot. Temporarily changing the preventFit flag in Node to default to true forces the Canvas to take up the full screen, and when I did this, the appearance in the sim matched the screenshot.

**Comment by ariel-phet** [comment]
@pixelzoom see comment above, sounds like this might be a sim specific issue (not general to screenshot), although documentation needs to be improved.

**Comment by pixelzoom** [comment]
As noted in https://github.com/phetsims/joist/issues/356#issue-177903981:
> In this specific sim, the situation shown in the above screenshot will never happen

So I am unconcerned in the case of this specific sim; in practice, it will never draw outside the canvasBounds.

What I am interested in is: 
(1) Why does it show up in the screenshot? 
(2) Is there anything we can do to detect when we're drawing outside the canvasBounds, or do we need to rely on testing to catch this.

Back to @jonathanolson.

**Comment by pixelzoom** [comment]
@ariel-phet said:
> @pixelzoom see comment above, sounds like this might be a sim specific issue 

It is most definitely not specific to this sim.  And in practice, it's not even relevant to this sim, since the sim will not draw outside the canvasBounds unless `maxIntroBalls` (a testing query parameter) is set to a huge value.

**Comment by jonathanolson** [comment]
> Why does it show up in the screenshot? Anything that can be done to prevent that?

The screenshot drawing method draws to a single Canvas that is then turned into a data URL. The Canvas takes up the full display size, so the CanvasNode doesn't get clipped. Because the CanvasNode's canvasBounds are small, while actually running the sim, the Canvas block is fitted around the CanvasNode's bounds, and so anything outside is clipped.

> Is there anything we can do to detect when we're drawing outside the canvasBounds, or do we need to rely on testing to catch this.

Scenery can't do cheap detection (we COULD design tests that set outside regions to a specific color and then check every pixel, but those would be slow). Could visually test with the showCanvasNodeBounds query flag (if you know what is drawn in CanvasNode), and the showFittedBlockBounds query flag will show the bounds of the actual blocks (which may be larger than the canvasBounds).

> It is most definitely not specific to this sim.

To me, the "Plinko's CanvasNode can draw outside of its canvasBounds" is the sim-specific part, but the "CanvasNode shouldn't draw outside of their canvasBounds" is a general thing.

> And in practice, it's not even relevant to this sim

Agreed, not worried if it won't show up in production (unless phet-io settings could trigger this, then it's still very low priority).

**Comment by pixelzoom** [comment]
> Agreed, not worried if it won't show up in production (unless phet-io settings could trigger this, then it's still very low priority).

This is not a query parameter that is relevant to phet-io.  And if that many balls did stack up, the least of our worries would be the clipping at the top edge of the canvas.

**Comment by pixelzoom** [comment]
Current status of this issue... Screenshot feature does not respect the bounds of CanvasNode.  So if a sim uses a CanvasNode to 'clip' things, it's possible for things to appear in screenshots that don't appear on the screen.  This issue has not been addressed yet, but has been noticed only in developer features, not production features. We should be on the lookout for this problem when testing.

**Comment by jonathanolson** [comment]
> So if a sim uses a CanvasNode to 'clip' things

Shouldn't ever happen, I noted above:

> CanvasNode subtypes' paintCanvas should NEVER draw anything outside of the current canvasBounds.

This should be a sim bug?

**Comment by pixelzoom** [comment]
I don't see anything in CanvasNode that indicates that it's an error to draw outside the bounds.  The only thing even close to that is this comment:

```7 Any regions outside of the canvasBounds will not be guaranteed to be drawn.```

So if it's the client's responsibility to draw only things that are inside the CanvasNode bounds, how is it supposed to draw things that are *partially* in bounds? E.g., a circle that is partially inside the bounds and partially outside?

**Comment by pixelzoom** [comment]
... or should the client be explicitly setting `clipArea` for the CanvasNode?

**Comment by jonathanolson** [comment]
> ... or should the client be explicitly setting clipArea for the CanvasNode?

> So if it's the client's responsibility to draw only things that are inside the CanvasNode bounds, how is it supposed to draw things that are partially in bounds?

clipArea should be used if you want the clipping effect.

> I don't see anything in CanvasNode that indicates that it's an error to draw outside the bounds.

Maybe error is the wrong phrase, since Scenery can't detect drawing outside. The better phrase would be "drawing anything outside of the canvasBounds results in undefined graphical behavior", which I could better specify than setCanvasBounds' docs:

> These bounds should always cover at least the area where the CanvasNode will draw in. If this is violated, this
> node may be partially or completely invisible in Scenery's output.

**Comment by pixelzoom** [comment]
Thanks for the clarification. Now that I understand, I think the existing doc is fine. 

I've created an issue for myself (https://github.com/phetsims/tasks/issues/745) to look for usages of CanvasNode that should have an explicit `clipArea`. 

So I think we're done here. Closing.
