### ISSUE TITLE
Add modernizr/feature detection in to sim startup, show information if sim unable to run

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#36]
See critical features in the debugging information page.

**Comment by pixelzoom** [comment]
We're doing this for WebGL. What are feature detection do you think is needed?

**Comment by pixelzoom** [comment]
@jonathanolson  We're doing this for WebGL. What are feature detection do you think is needed?

**Comment by jonathanolson** [comment]
Now that we've dropped IE9, we could check for general ES5 features, existence of typed arrays, etc. (that are used in sims).

Basically, it would be helpful for any browser is expected to not run most sims successfully, so we could display information about that. If someone uses IE8, or Firefox 2, it would be helpful.

**Comment by ariel-phet** [comment]
Considering how long we have had HTML5 sims published and we have had none of these kinds of issues reported by users, this seems unnecessary. Recent stats on the website show all significant use is on modern browsers.
