### ISSUE TITLE
triggers potentially in incorrect order

### ISSUE THREAD

**Issue by jbphet** [phetsims/joist#360]
I noticed this when reviewing the code for #348.

There are a couple of triggers that seem potentially redundant or out of order. They are ```this.trigger0( 'simulationStarted' )``` and ```this.trigger0( 'endedSimConstructor' )```.  It just seems to me that the constructor would need to be completed before the simulation can be started.

**Comment by samreid** [comment]
The endedSimConstructor was unused, I removed it.
