### ISSUE TITLE
Rename simStarted => simInstanceCreated

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#361]
Discovered in #360 

simStarted should be renamed to simInstanceCreated.  PhET-iO things should be renamed as well.

**Comment by pixelzoom** [comment]
I see 9 occurrences of 'simStarted' in phet-io, zero occurrences in joist.  Why is this issue in joist?

**Comment by samreid** [comment]
It looks like the variable is called `simulationStarted` and called from line 465 of Sim.js:

```js
this.trigger0( 'simulationStarted' );
```

It is a bit of a misnomer since the Sim hasn't yet been `launch`ed.

**Comment by samreid** [comment]
But perhaps the best way to do this would be to call tandem.addInstance(this,TSim) and let it replace `simInstanceCreated`, if possible.

**Comment by samreid** [comment]
This could change what @zepumph and I are working on for playback--which detects the "simStarted" message.  I'd like to discuss with @zepumph what the best name for this event is.

**Comment by zepumph** [comment]
After working with @samreid on this, we decided that this is still a good name, and we shouldn't rename anything. The simStarted message is still the first event and it is being emitted once all of the screens have been fully initialized. Closing.
