### ISSUE TITLE
Convert from PropertySet to Property

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#365]
Per https://github.com/phetsims/axon/issues/102...  Convert from PropertySet to Property.

**Comment by pixelzoom** [comment]
@samreid Please review the changes that I made to Sim.js.  This was difficult to test because some of the query parameters were broken to begin with (see #367).

**Comment by pixelzoom** [comment]
UpdateCheck has its own special set of oddities that are making conversion unnecessarily difficult. 

From Skype conversation with @jonathanolson:
> [11/7/16, 12:01:22 PM] Chris Malley: Question about joist.UpdateCheck. Why does it have both updateURLProperty and updateURL?  And is updateProperty every used? (Looks like not.)
[11/7/16, 12:03:38 PM] Chris Malley: Seems like adding updateURL property (lowercase 'p') in the inherit call would create problems for attempt to access updateURLProperty via its ES5 set/get.
[11/7/16, 12:31:27 PM] Jonathan Olson: That's weird. Looks like we're always getting the update URL from the server then, so both are probably ignored
[11/7/16, 12:31:46 PM] Jonathan Olson: It's also not used as a Property (even though it can change)
[11/7/16, 12:31:49 PM] Chris Malley: There's an assignment in check()
[11/7/16, 12:32:16 PM] Jonathan Olson: yes, that's when it probably gets set
[11/7/16, 12:32:39 PM] Jonathan Olson: Feel free to remove the 'Property' one in the PropertySet constructor
[11/7/16, 12:32:48 PM] Jonathan Olson: and I'll test afterwards

So I'm going to make the changes, cross my fingers, and let @jonathanolson verify.

**Comment by pixelzoom** [comment]
@jonathanolson please review changes to UpdateCheck and related joist types (see above commit). I test by change "version" in a sim's package.json to something older than the published version. Then ran the sim and confirmed that it reported that an update was available. Similar test procedure for no update available.

**Comment by pixelzoom** [comment]
Joist is now free of PropertySet. Labeling review of this work as high-priority since it could really mess things up.

**Comment by samreid** [comment]
I skimmed the changes to Sim.js and didn't see any trouble.  I still need to test a few things.

**Comment by jonathanolson** [comment]
> @jonathanolson please review changes to UpdateCheck and related joist types (see above commit). 

Looks good, thanks.

**Comment by samreid** [comment]
Launching http://localhost/hookes-law/hookes-law_en.html?ea&brand=phet&screens=1 shows a blank screen, so something is amiss.

**Comment by samreid** [comment]
Proposed fix committed above, @pixelzoom can you please review?

**Comment by pixelzoom** [comment]
Thanks. Must've been this change in default options that was messing things up:

```js
83 showHomeScreen: ( screens.length > 1 ),
```

Back to @samreid. If your review is done, feel free to close.

**Comment by samreid** [comment]
@zepumph and @mattpen pointed out that the Classroom Activity was failing to launch.  I committed a fix above that should address the problem.  I checked for other usages of Sim properties in phet-io and didn't see any. @pixelzoom would you like to review that change?

**Comment by pixelzoom** [comment]
Fix looks good. Sorry I missed that one (but surprised I missed only that one :)

@samreid I'm assuming that means your review is done, so I'm closing. If that's not the case, please reopen.

**Comment by samreid** [comment]
Reopening to continue testing.

**Comment by samreid** [comment]
I haven't seen other issues, ready to close the issue now.
