### ISSUE TITLE
Dialog.dispose fails assertion

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#366]
See https://github.com/phetsims/models-of-the-hydrogen-atom/issues/10

Should be addressed as part of https://github.com/phetsims/joist/issues/359

@ariel-phet please prioritize and assign.

**Comment by pixelzoom** [comment]
The problem is in `Panel.dispose`, as described in https://github.com/phetsims/models-of-the-hydrogen-atom/issues/10#issuecomment-258893240.

It's also unclear whether Dialog needs to add anything additional in a `dispose` override.

**Comment by ariel-phet** [comment]
@andrewadare is this something you can handle whilst taking care of dispose in some other places? Or is it a complicated enough task to discuss more? If so, just reassign me.

**Comment by andrewadare** [comment]
I just looked into it, and I'm unable to reproduce the problem (see https://github.com/phetsims/models-of-the-hydrogen-atom/issues/10#issuecomment-259864800). This part of MOTHA seems to work fine for me. What am I missing?

**Comment by andrewadare** [comment]
https://github.com/phetsims/models-of-the-hydrogen-atom/issues/10#issuecomment-259865468, that's what.

**Comment by andrewadare** [comment]
@ariel-phet I'll have a look soon.

**Comment by pixelzoom** [comment]
Should be addressed when revising/rewriting Dialog in #359.

**Comment by pixelzoom** [comment]
All calls to `unlink`, `removeListener`, etc. should be inside a test for `hasListener`. See https://github.com/phetsims/scenery/issues/775#issuecomment-385801650.

**Comment by pixelzoom** [comment]
This was addressed during work that @andrealin did on Dialog in spring 2018. Closing.
