### ISSUE TITLE
showHomeScreen and screenIndex query parameters are broken

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#367]
Noted while working on https://github.com/phetsims/joist/issues/365.

I don't see how the `showHomeScreen` and `screenIndex` query parameters can possibly be working (and they don't appear to be working).  The query parameters are read long after their related Properties are initialized.

**Comment by pixelzoom** [comment]
initialize-globals.js says:

> showHomeScreen - if false, go immediate to screenIndex, defaults to screenIndex=0

But there's no screenIndex query parameter documented, and there's none implemented in Sim.

**Comment by pixelzoom** [comment]
`screens` query parameter numbers screen starting at 1.  `screenIndex` appears to number starting at zero.  Very confusing.

**Comment by pixelzoom** [comment]
Fixed. @samreid please review.

**Comment by samreid** [comment]
The change set looks good and works correctly.  I have taken the following steps:

1. Changed screenIndex to be 1-based, like ?screens
2. Removed the no-longer-used standalone option

Tests with build an atom and faradays law seem good, committing.

**Comment by samreid** [comment]
@pixelzoom please review changes at your convenience.

**Comment by pixelzoom** [comment]
Changes look good.

I fleshed out the doc for screenIndex in the above commit.  @samreid please review, refine if you'd like, and close.

**Comment by samreid** [comment]
Looks great, closing.
