### ISSUE TITLE
change Sim to use Emitters (by composition)

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#368]
Noted while working on #365.

Sim previously extended PropertySet, which extends Events.  Yuck - what a totally inappropriate type hierarchy.   After replacing PropertySet with Property in #365, Sim now extends Event.  Still major yuck. Recommended to replace this inheritance abuse with composition.

**Comment by samreid** [comment]
Please note that Events is deprecated and Sim.js should use Emitters instead (by composition).

**Comment by pixelzoom** [comment]
According to the `Sim` constructor documentation, there is only 1 Event:

```js
   * Events:
   * - resized( bounds, screenBounds, scale ): Fires when the sim is resized.
```

with associated trigger on line 564:

```js
564 this.trigger( 'resized', this.boundsProperty.value, this.screenBoundsProperty.value, this.scaleProperty.value );
```

But the documentation lies.  Sim triggers 3 other events:

```js
239 this.trigger1( 'startedSimConstructor',...
465 this.trigger0( 'simulationStarted' );
468 this.trigger1( 'frameCompleted', dt );
```

And `barrierRectangle` triggers 2 more:

```js
442 self.barrierRectangle.trigger0( 'endedCallbacksForFired' );
445 self.barrierRectangle.trigger0( 'endedCallbacksForFired' );
```

**Comment by pixelzoom** [comment]
I changed the documentation to:

```Events: search for 'trigger' to find the supported Events```

**Comment by pixelzoom** [comment]
Looks like these Events would be fairly easy to convert to Emitters. There are a handful of uses:

resized: 4 uses (Dialog, PhetButton, phetio.js)
simulationStarted: not used?
simulationStarted: 1 use (TSim) 
frameCompleted: 7 uses (Profiler, NeuronProfiler, phetio.js, TPhETIO)

**Comment by pixelzoom** [comment]
@samreid `startedSimConstructor` doesn't appear to be used anywhere, looks like something that you added long ago that used to have a corresponding `endedSimConstructor`.  Can this chunk of code be deleted from Sim, line 238? 

```js
    this.trigger1( 'startedSimConstructor', {
      sessionID: phet.chipper.queryParameters.sessionID,
      repoName: packageJSON.name,
      simName: this.name,
      simVersion: this.version,
      url: window.location.href,
      randomSeed: window.phet.chipper.randomSeed
    } );
```

**Comment by samreid** [comment]
It is used by TSim.js

**Comment by samreid** [comment]
The string mismatch problem should be solved by https://github.com/phetsims/phet-io/issues/886

**Comment by pixelzoom** [comment]
`startedSimConstructor` is not used by TSim (unless you're referring to some branch). Are you thinking of `simulationStarted`?

**Comment by pixelzoom** [comment]
@samreid said:
> The string mismatch problem should be solved by phetsims/phet-io#886

Was this meant for some other issue?

**Comment by samreid** [comment]
My apologies for being cryptic--I wanted to jot down enough to jog my memory before I had to take off.  TSim.js has this line:

```js
toEventOnStatic( sim, 'SimConstructor', 'model', phetioID, TSim, 'simStarted', function( value ) {
```

and `toEventOnStatic` prepends these started and ended strings like so:

```js
    model.onStatic( 'started' + suffix, function( arg1, arg2, arg3, arg4 ) {
      messageIndex = phetioEvents.start( messageType, phetioID, type, event, filter && filter( arg1, arg2, arg3, arg4 ) );
    } );
    model.onStatic( 'ended' + suffix, function() {
      phetioEvents.end( messageIndex );
    } );
```

So when doing a word search for `startedSimConstructor` it **looks** like there are no usages, but it is used by a concatenated string.

**Comment by pixelzoom** [comment]
Yikes. Why is that necessary?

**Comment by samreid** [comment]
It is not necessary, which is why we can fix it in https://github.com/phetsims/phet-io/issues/907.  It was my misguided attempt to "factor out" duplicated parts of strings.

**Comment by pixelzoom** [comment]
Got it. While it's being fixed, should it be changed to an Emitter?

**Comment by samreid** [comment]
> While it's being fixed, should it be changed to an Emitter?

Eventually, yes.  I'm not sure if that will be better to do separately or not.  I'll take a look when I'm there.

**Comment by pixelzoom** [comment]
Related to https://github.com/phetsims/chipper/issues/515... Removing Events from Sim looks like relatively low-hanging fruit. And since these Events are being used by PhET-iO, it seems like it would be good to do this sooner rather than later.  But my priorities are being shifted elsewhere, and I won't have time to do work on this in the foreseeable future.  So unassigning.

**Comment by samreid** [comment]
In the above commits, I used Emitter for resize.  Tested by resizing with dialogs open/closed in Faraday's Law, and tested phet-io mirror input events, and saw the screen resized properly in all 3 cases.

**Comment by samreid** [comment]
Other events changed to emitters in the above commits.  Sim no longer extends Events.  Tested lint and running Faraday's Law.  All seems well.  `self.barrierRectangle.trigger0( 'endedCallbacksForFired' );` will be handled as part of getting rid of the deprecated Events class or converting phet-io events to use Emitters.  Normally at this point I would reassign to @pixelzoom for review, but I know he is highly focused on another project.  These changes aren't too risky, but it would be good to have another developer take a quick look before we close the issue.  @pixelzoom and @ariel-phet, what do you think?

**Comment by pixelzoom** [comment]
I skimmed the commits and didn't see any obvious problems. 

2 documentation issues:

• All of the Emitter definitions need visibly annotations (`@public`?)
• `this.resizedEmitter` and `this.frameStartedEmitter` need to be documented. 

After that, I think we're good to close this issue.

**Comment by samreid** [comment]
I added docs in the above commit, @pixelzoom would you like to take a look?

**Comment by pixelzoom** [comment]
👍 Closing.
