### ISSUE TITLE
unnecessary Properties in Sim?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#369]
Sim.js line 182:

```js
//TODO why are these Properties? should their visibility be @public (joist-internal)?
// @public
this.showPointerAreasProperty = new Property( !!phet.chipper.getQueryParameter( 'showPointerAreas' ) );
this.showPointersProperty = new Property( !!phet.chipper.getQueryParameter( 'showPointers' ) );
this.showCanvasNodeBoundsProperty = new Property( !!phet.chipper.getQueryParameter( 'showCanvasNodeBounds' ) );
this.showFittedBlockBoundsProperty = new Property( !!phet.chipper.getQueryParameter( 'showFittedBlockBounds' ) );
```

Skype:
[11/7/16, 1:12:19 PM] Chris Malley: Why is showPointerAreas a Property in Sim? Is there a feature to dynamically turn them on/off?
[11/7/16, 1:12:46 PM] Chris Malley: Ditto for showPointers, showCanvasNodeBounds, showFittedBlockBounds.
[11/7/16, 1:13:12 PM] Chris Malley: These are all query parameters. Can't they be set once at startup? Why are they Properties?

I see that showPointerAreasProperty is passed to SettingDialog (which is currently not used). Is this really necessary? Do these things really need to be changed dynamically while the sim is running?

**Comment by samreid** [comment]
As far as I know, these are only set on startup, but got thrown into the PropertySet so they could be managed by built-in PhET-io support.  I don’t know of any wrappers that need to dynamically turn those on and off again.  For instance, the “Playback” wrapper would enable the showPointerAreas during startup.

For instance, `showCanvasNodeBoundsProperty` has one statement to declare the property, and one statement to link to it.  That is too much code?

**Comment by pixelzoom** [comment]
Also wondering about `showHomeScreen` and `screenIndex`.  The former has been broken for who knows how long.  And the latter was actually never implemented.  (See https://github.com/phetsims/joist/issues/367.)  If no one is using (or maintaining) these, then why do they exist?

**Comment by pixelzoom** [comment]
> For instance, showCanvasNodeBoundsProperty has one statement to declare the property, and one statement to link to it. That is too much code?

Any code that isn't use is "too much code".  All code has maintenance cost. Together they are N query parameters that I'm having to port to QueryStringMachine.  I'm not excited to port things that aren't used, or have questionable value.  And the very existence of this issue is a cost which I'm pretty sure is now in the hundreds of dollars to PhET.

**Comment by jonathanolson** [comment]
> I see that showPointerAreasProperty is passed to SettingDialog (which is currently not used). Is this really necessary? Do these things really need to be changed dynamically while the sim is running?

No preference, I'm fine to have it only be set on startup.

**Comment by pixelzoom** [comment]
11/10/16 dev meeting: Keep all of these, easier than deciding which to delete.
