### ISSUE TITLE
Resizing window during input event playback should not change scene size

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#37]

**Comment by pixelzoom** [comment]
Same question that @samreid had on 10/17/2013. @jonathanolson is this solved?

**Comment by jonathanolson** [comment]
Input event recording and playback hasn't yet been fully updated for Scenery 0.2. Is getting that working a priority for the summer deployment @pixelzoom?

**Comment by pixelzoom** [comment]
Now that I understand what this is... No, not a priority for the "Summer 2015 redeployment", so removing that label.

**Comment by pixelzoom** [comment]
@jonathanolson Is this issue still relevant?

**Comment by pixelzoom** [comment]
@jonathanolson Is this issue still relevant?  If no, please close. If yes, please briefly describe what needs to be done.

**Comment by jonathanolson** [comment]
@samreid, is this an issue for current playback?

**Comment by samreid** [comment]
This is an issue.  Our current workaround is to instruct researchers to not resize the window during playbacks.  What we should do instead is make it so that window resize events do not end up changing the scenery display size during playback.

**Comment by jonathanolson** [comment]
@samreid, is there documentation on how to record and play back? I'd like to reproduce and understand so I can fix it.

I was able to record a session with the record wrapper, but the playback wrapper (linked in phetmarks) doesn't seem to exist.

**Comment by jonathanolson** [comment]
Via @phet-steele, saw the metacog playback code (playback looks nice!)

It looks like this problem should be present if it wasn't wrapped in an iframe.

@samreid or @zepumph, what flags would Sim be able to check to see if it is in "playback" mode? handlePlaybackEvent looks like it's reaching in very directly, so I'm really not sure if there is a status that lets Sim know it's being played back.

Can I use activeProperty, that sets display.interactive?

**Comment by samreid** [comment]
> Our current workaround is to instruct researchers to not resize the window during playbacks. 

By embedding the playback frame inside an iframe, this is no longer a problem.  The size from the recording is set to the playback iframe and the playback iframe doesn't resize otherwise.

> @samreid or @zepumph, what flags would Sim be able to check to see if it is in "playback" mode? 

Looking in mirror.html, I'm seeing `disableRequestAnimationFrame` as a flag that is currently set for the playback frame.  And in playSession.js, I see `setPlaybackMode` which looks like it sets `phet.joist.playbackMode`.  That seems like the best flag to use.  I'll create an issue to see if we should adopt that flag for mirror.html too.

**Comment by jonathanolson** [comment]
Done, can you review?

**Comment by samreid** [comment]
The code change looks good, thanks!
