### ISSUE TITLE
issues with playbackMode feature

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#370]
Noted while working on https://github.com/phetsims/query-string-machine/issues/15.

There appears to be both a `playbackMode` query parameter (which is ignored) and a `phet.joist. playbackMode` global. 

Documentation of `playbackMode` in initialize-globals.js:

```js
playbackMode - for PhET-iO: if true the sim clock won't run and instead the sim will 
   receive dt events from stepSimulation calls.
```

The query parameter is read in Sim.js, where it's used to set the default value of `options.playbackMode`:

```js
103      // TODO: Is this still needed?
104      playbackMode: !!phet.chipper.getQueryParameter( 'playbackMode' ),
```

Later in Sim.js (line 495) `phet.joist.playbackMode` (a different global with the same name) is used:

```js
    // @public (joist-internal) - Bind the animation loop so it can be called from requestAnimationFrame with the right
    // this.  If PhET-iO sets playbackMode to be true, the sim clock won't run and instead
    // the sim will receive dt events from stepSimulation calls.
    this.boundRunAnimationLoop = phet.joist.playbackMode ? function() {} : this.runAnimationLoop.bind( this );
    this.trigger0( 'simulationStarted' );
```

This global appears to be set in TPhETIO.js:

```js
setPlaybackMode: {
      returnType: TVoid,
      parameterTypes: [ TBoolean ],
      implementation: function( playbackMode ) {
        phet.joist.playbackMode = playbackMode;
      },
      documentation: 'Disable the sim clock driver so that time will only pass as it is played back from a log file.'
    },
```

Questions:

• Why is there both a query parameter and a global?
• Which implementation should be deleted?

**Comment by samreid** [comment]
@jonathanolson it looks like Sim.playbackMode is no longer used since phet-io is now using `phet.joist.playbackMode`.  You originally added Sim.playbackMode and I cannot see it being used for anything at the moment, can it be removed now?

**Comment by jonathanolson** [comment]
Presumably it can be removed, I'm not using it for anything.

**Comment by samreid** [comment]
I removed playbackMode, tested grunt lint, ran a sim in requirejs mode and mirror-inputs mode and all seems well. Committing.

**Comment by samreid** [comment]
@pixelzoom would you like to review?

**Comment by pixelzoom** [comment]
Looks like `playbackMode` query parameter was successfully deleted, but...

@samreid said:
> it looks like Sim.playbackMode is no longer used since phet-io is now using phet.joist.playbackMode. 

Did you consider deleting `phet.joist.playbackMode` and changing phet-io to use the `playbackMode` query parameter?   It seems like phet-io should be using query parameters whenever possible, rather than creating its own globals (which btw don't appear to be documented or encapsulated in any one place.)

**Comment by samreid** [comment]
I considered using a query parameter to set up a simulation for playback mode, and thought that a global would be more straightforward, so that it can be set using the conventional PhET-iO API.  In the above commit, I initialized the global in Sim.js and documented it.  @pixelzoom would you like to review?
