### ISSUE TITLE
Screen could accept a backgroundColorProperty?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#373]
Right now, sims that use ColorProfile need to pass in the initial background color, and then update that color on updates, like so:
```js
    backgroundColor: ChargesAndFieldsColorProfile.backgroundProperty.value.toCSS(),
...
    ChargesAndFieldsColorProfile.link( 'background', function( color ) {
      self.backgroundColorProperty.value = color;
    } );
```

Can Screen just accept a backgroundColor as a Property (like Scenery) and not force creation of its own property? Do we ever need to change the Screen's backgroundColor independently of the color profile?

**Comment by pixelzoom** [comment]
Recommended to use the pattern employed elsewhere for optional Properties (e.g. `enabledProperty`):

```js
function Screen( ..., options ) {
  options = _.extend( {
    backgroundProperty: new Property( 'white' )
  }, options );

  this. backgroundProperty = options.backgroundProperty; // @public
}
```

**Comment by jonathanolson** [comment]
> Recommended to use the pattern employed elsewhere for optional Properties (e.g. enabledProperty):

Sounds great to me.

**Comment by pixelzoom** [comment]
The down side is that we have something like 150 usages of `backgroundColor` that will need to be converted to `backgroundColorProperty`.  If we want to avoid that conversion... We could keep both `backgroundColor` and `backgroundColorProperty`, make them mutually exclusive, and use `backgroundColor` as the default value for `backgroundColorProperty`.

**Comment by pixelzoom** [comment]
I.e.:

```js
function Screen( ..., options ) {

  assert && assert( !( options.backgroundColor && options.backgroundColorProperty), '...' );

  options = _.extend( {
    backgroundColor: 'white',
    backgroundColorProperty: null
  }, options );

  // @public
  this.backgroundProperty = options.backgroundColorProperty || new Property( options.backgroundColor );
}
```

**Comment by jonathanolson** [comment]
> If we want to avoid that conversion

Supporting both looks more complicated, and I'd volunteer for the refactoring to keep it simple.

**Comment by pixelzoom** [comment]
Keeping it simple would be my choice too.

**Comment by samreid** [comment]
I thought we recently added scenery support so you could pass in {Color|Property.<Color>}.  How did that work out?

**Comment by jonathanolson** [comment]
> I thought we recently added scenery support so you could pass in {Color|Property.<Color>}. How did that work out?

Works great in general for direct use, but many sun/scenery-phet types don't support all Scenery fill/stroke options. We're lacking the tools to transparently deal with these (say you want to get a slightly darker color, ```Color.toColor( fill ).darkerColor( 0.5 )``` will fail for a ```Property.<Color>```).

I didn't check how backgroundProperty is used, but Display.backgroundColor doesn't support property currently, so we may not be able to pass strings/colors/color-properties to the same 'background' interface.

**Comment by samreid** [comment]
Providing support for `Property.<Color>` in Screen sounds fine to me too.  It should be straightforward (though lots of busywork) to convert to `Property.<Color>`.

My only hesitation is that with 150+ copies of this, we will have 150+ copies of this duplicated code:
```
var Property = require('AXON/Property');
var Color = require('SCENERY/Color');
//...
backgroundColor: new Property(new Color( 'some color value')),
```

If we approximate `new Property(new Color()` as a line of code, then we have ~3*150 lines of duplicated code as a result of this change.  I guess adding 450 lines of code to slightly simplify this feature seems reasonable, it is the size of a small file.  Hacks like:

```js
backgroundColor: window.colorProperty('blue') // seems too 'magical'
```

cut down on lines of boilerplate, but end up obfuscating what is supposed to happen.  In summary, I guess I'm slightly favoring the strategy of refactoring to `backgroundColorProperty` and dropping support for `backgroundColor`.

**Comment by jonathanolson** [comment]
> My only hesitation is that with 150+ copies of this, we will have 150+ copies of this duplicated code.

5+ sims would use ColorProfile properties presumably.

I'm not concerned about the small (maximum 8 per sim if 4 screens) number of import lines, as there is much lower-hanging fruit for reducing the file size imports take up (abbreviate namespaces, make certain things global, etc.)

**Comment by samreid** [comment]
Consensus: we'll use backgroundColorProperty.

**Comment by jonathanolson** [comment]
Commits landed 6 days ago, forgot to close.

**Comment by pixelzoom** [comment]
Reopening. There are problems here.  Assigning to @jonathanolson to correct, since he did the work.

(1) Incorrect documentation in Screen.js:

```js
56      // {Color|string} initial background color of the Screen
57      backgroundColorProperty: new Property( new Color( 'white' ) ),
```

The type expression should be `{Property.<Color|string}`.

(2) Failure if the color is specified using a string.

For example, creating a Screen with `backgroundColorProperty: new Property( 'yellow' )` results in a hard failure:

```
Sim.js?bust=1485382964332:388 Uncaught TypeError: self.currentScreenProperty.value.backgroundColorProperty.value.toCSS is not a function
    at Sim.updateBackground (Sim.js?bust=1485382964332:388)
    at Sim.js?bust=1485382964332:399
    at new Multilink (Multilink.js?bust=1485382964332:48)
    at Function.multilink (Property.js?bust=1485382964332:425)
    at new Sim (Sim.js?bust=1485382964332:396)
    at unit-rates-main.js?bust=1485382964332:52
    at window.phetLaunchSimulation (SimLauncher.js?bust=1485382964332:50)
    at doneLoadingImages (SimLauncher.js?bust=1485382964332:60)
    at Object.launch (SimLauncher.js?bust=1485382964332:114)
    at unit-rates-main.js?bust=1485382964332:37
```  

Color should most definitely be specifiable using a Color or string.

**Comment by pixelzoom** [comment]
I fixed the type expression, problem (1) above.

**Comment by pixelzoom** [comment]
I fixed the error in Sim.js in the above commit. This allows me to continue with Unit Rates development.

**Comment by pixelzoom** [comment]
I searched joist for `backgroundColorProperty`, and didn't see any other problematic code like Sim.js.  But I'm wondering about this Sim.js (line 388):

```js
      self.lookAndFeel.backgroundColorProperty.value = self.currentScreenProperty.value ?
                                                       Color.toColor( self.currentScreenProperty.value.backgroundColorProperty.value ).toCSS() :
                                                       Color.toColor( self.homeScreen.backgroundColorProperty.value ).toCSS();
```

Are the `toCSS` calls needed? `LookAndFeel` looks like it supports string colors (would be nice if it were documented), because I see this initialization in its constructor:

```js
25    this.backgroundColorProperty = new Property( 'black' );
```

**Comment by pixelzoom** [comment]
I removed the `toCSS` calls, tested a Screen with both a string and Color value for `backgroundColorProperty`, and didn't see any problems.  That said, I'm not familiar with all of the situations were `LookAndFeel` might be used.  @jonathanolson please review what I've done and test any other situations that I might have missed.

**Comment by jonathanolson** [comment]
Sorry about missing the documentation update.

I had originally refactored as @samreid described:

> Providing support for Property.<Color> in Screen sounds fine to me too.

instead of

> The type expression should be {Property.<Color|string}.

So that `Property<string>` was not supported, although this required wrapping things with `new Color()` in some client usages.

The advantage would be that casts to Color (e.g. Color.toColor) wouldn't be required later, as we would only need one Color instance. Additionally, one instance is better so instance equality checks when setting the backgroundColor doesn't force an update (probably not too important).

> I removed the toCSS calls, tested a Screen with both a string and Color value for backgroundColorProperty, and didn't see any problems. That said, I'm not familiar with all of the situations were LookAndFeel might be used. @jonathanolson please review what I've done and test any other situations that I might have missed.

Looks safe. Only recommendation is that if we are keeping the `{Property.<Color|string>}`, all of the client usages should be refactored.

**Comment by pixelzoom** [comment]
@jonathanolson said:
> recommendation is that if we are keeping the {Property.<Color|string>}, all of the client usages should be refactored.

Agreed.  I've done this in my sims and runnables for common-code repos.  Looks like there are 63 remaining occurrences of `backgroundColorProperty: new Property( Color.toColor`.  How do you want to handle refactoring?

**Comment by jonathanolson** [comment]
@pixelzoom, I believe I hit all the usages above. Can you verify? (Tests are passing).

**Comment by pixelzoom** [comment]
Looks good, I don't see any that were missed.  Closing.
