### ISSUE TITLE
missing tandem.addInstance in Screen?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#376]
Screen has options.tandem, then does nothing with it.  

Looking at concentration, an instrumented sim...  In concentration-main.js, I see:

```js
33     var sim = new Sim( concentrationTitleString, [ new ConcentrationScreen( tandem.createTandem( 'concentrationScreen' ) ) ], simOptions );
```

So a tandem is created for `ConcentrationScreen`, which passes it to `Screen`, which does nothing with it. 

Should Screen's constructor call `tandem.addInstance`?

**Comment by pixelzoom** [comment]
TODO added in Screen.  Please remove it when this issue is addressed.

**Comment by samreid** [comment]
Fixed above and removed TODO.  Tested instrumented sim in instance-proxies and uninstrumented sim in require.js.  Lint is passing. @pixelzoom do you want to review?
