### ISSUE TITLE
Add an eslint rule that checks that TODOs are marked with an issue in joist

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#380]
See https://github.com/phetsims/joist/issues/64

Eventually provide this for scenery, kite, dot as well, when they are getting more issue coverage.

**Comment by samreid** [comment]
TODO: this should probably be an issue in chipper.

**Comment by samreid** [comment]
@pixelzoom suggested we shouldn't have a lint rule.

**Comment by samreid** [comment]
I'm fine with this being a manual process, as implied by https://github.com/phetsims/joist/issues/380#issuecomment-264272985, closing.

**Comment by samreid** [comment]
From https://github.com/phetsims/joist/issues/64#issuecomment-264272842 it looks like we are proceeding: 

> Consensus: we will try adding an eslint rule (to emit warnings, not errors). Leaving flagged for dev meeting until it gets implemented.

> *Edit:* The lint warnings are planned to be implemented only for Joist to start with.

I may not get to this soon, someone else please feel free to beat me to it.

**Comment by samreid** [comment]
In the above commit, I added a rule that checks that Joist TODOs have GitHub issues.  I left it as a Warning for now, since there are some 14 or so issues at the moment.  Once those 14 issues are cleared, we can turn the rule to Error.

**Comment by samreid** [comment]
Also, if we like this rule, we can add other repos to its whitelist (currently joist-only).

**Comment by samreid** [comment]
This rule is complete, we will discuss #64 in the next developer meeting, and we could discuss this issue too if we want to.  Until then, closing.

**Comment by jessegreenberg** [comment]
The eslint rule requires a full github url, but not an issue number reference like #ddd, where d is a digit. Is it OK if the rule allows for both or would we rather have it strictly check for url? Either url or issue number seems acceptable to me.

**Comment by jessegreenberg** [comment]
The above commit allows both.  @samreid are you OK with this change?

**Comment by samreid** [comment]
In the above commit, I fixed a variable name and fixed the logic for checking matching of a regular expression (indexOf only works if you pass a string parameter).

For testing ESLint rules, you must use `grunt --disable-eslint-cache` or the lint test may not run (if version in cache succeeded).

@jessegreenberg can you please review my commit and let me know if all is well?

**Comment by jessegreenberg** [comment]
Yes, this looks and works great @samreid. I should have checked the params of indexOf. Also thanks informing me of ```grunt --disable-eslint-cache```, I was not aware. I incorrectly assumed that changing the rule would blow away the cache.

Thanks for the fixes @samreid, closing.
