### ISSUE TITLE
"brand awareness" for the Splash screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#383]
Love the new animated progress bar on the Splash screen.  But a couple of observations related to "brand awareness":

(1) In requirejs mode, the official PhET logo (brand=phet) is displayed regardless of brand. Not a big deal since this mode is for developers, but would be nice to see the expected logo when testing.

(2) A sim that was built with `--brand=adapted-from-phet` shows no logo on the splash screen, only the progress bar.  Seems to behave as expected for `--brand=phet-io` (shows the PhET-iO logo).  If I defined a custom brand, what would it do?

**Comment by ariel-phet** [comment]
@samreid did a few changes sneak in with the addition of the progress bar?

As for (1) it seems that might be an easy fix

As for (2) my expectation is that the splash screen would open with either the custom defined brand or the "adapted from PhET" logo. Is that correct or is the behavior currently just nothing?

**Comment by samreid** [comment]
> (1) In requirejs mode, the official PhET logo (brand=phet) is displayed regardless of brand. Not a big deal since this mode is for developers, but would be nice to see the expected logo when testing.

It looks like the problem is that my build.json file indicates `{brand:'phet'}` and that value is used when running `grunt generate-development-html`.  If this hypothesis is correct, it seems the correct course of action would be to remove brand from my build.json and rebuild all development html.

**Comment by samreid** [comment]
Apparently this has been a problem since this feature was introduced about a year ago.

**Comment by samreid** [comment]
In the preceding commits, the fallback brand in development html is set to "adapted-from-phet".  

> (2) A sim that was built with --brand=adapted-from-phet shows no logo on the splash screen, only the progress bar. Seems to behave as expected for --brand=phet-io (shows the PhET-iO logo). If I defined a custom brand, what would it do?

As documented in https://github.com/phetsims/brand/blob/master/README.md the expectation is for 3rd parties to add their own logo.

@pixelzoom can you please review my commits and comments?

**Comment by samreid** [comment]
Also, do we want to change sim-development.html to hard-code "adapted-from-phet" so this doesn't happen again?

**Comment by pixelzoom** [comment]
Changes reviewed.

@samreid said:
> It looks like the problem is that my build.json file indicates {brand:'phet'} and that value is used when running `grunt generate-development-html`.
...
> Also, do we want to change sim-development.html to hard-code "adapted-from-phet" so this doesn't happen again?

No, I don't think we want to hard-code the development html to 'adapted-from-phet'.  It should default to that, but it should also obey the `?brand` query parameter.  For example, for the html files that you revised, I can specify `brand=phet` or `brand=phet-io` and see the expected splash logo.

And until this is fixed somewhere in the build process, this problem is highly likely to reappear. For example, I also have `{brand:'phet'}` in build-local.json, and running `grunt generate-development-html` results in a development html file that shows the logo for `brand=phet` when `?brand` query parameter is not specified.

@samreid said:
> As documented in https://github.com/phetsims/brand/blob/master/README.md the expectation is for 3rd parties to add their own logo.

Ah... So there is no "default" logo for `brand=adapted-from-phet`? Why not show the same default logo that's used in the navigation bar?

**Comment by samreid** [comment]
I'd be OK with `adapted from PhET` logo to be the splash screen.   @ariel-phet is that OK with you?

@pixelzoom the template sim-development.html currently has this line:
```js
var brand = brandMatch ? decodeURIComponent( brandMatch[ 1 ] ) : '{{BRAND}}';
```

The ``{[BRAND}}`` gets filled in based on the developer's build.json when `grunt generate-development-html` is run.  If we change sim-development.html (the template) to 

```js
var brand = brandMatch ? decodeURIComponent( brandMatch[ 1 ] ) : 'adapted-from-phet';
```

then no matter what is specified in build.json it will still generate sim_en.html that has the correct behavior to fall back to adapted-from-phet.

**Comment by pixelzoom** [comment]
> If we change sim-development.html (the template) to ... it will still generate sim_en.html that has the correct behavior to fall back to adapted-from-phet.

That sounds correct.

**Comment by pixelzoom** [comment]
@samreid said:
> I'd be OK with adapted from PhET logo to be the splash screen. @ariel-phet is that OK with you?

One problem - that logo has a translated component, "Adapted from PhET".   Imo, we should purge translation from the "adapted" logo.

**Comment by samreid** [comment]
By "purge translation" did you mean "remove English text" or "prevent i18n of the English text"?

**Comment by samreid** [comment]
OK I hard coded the 'adapted-from-phet' in the preceding commit and tested that grunt generate-development-html is unchanged.

**Comment by pixelzoom** [comment]
@samreid asked:
> By "purge translation" did you mean "remove English text" or "prevent i18n of the English text"?

I mean don't translate any portion of the logo, require each logo to be fully contained in an image file. We are currently doing something special for "adapted-from-phet" - we're adding text to the logo image. In PhetButton, line 114:

```js
// If this is an "adapted from PhET" brand, decorate the PhET button with "adapted from" text.
    if ( Brand.id === 'adapted-from-phet' ) {
      this.addChild( new AdaptedFromText( textFillProperty, {
        pickable: false,
        left: icon.left,
        bottom: icon.top + 3,
        maxWidth: logoImage.width
      } ) );
    }
```

**Comment by samreid** [comment]
@ariel-phet said OK to make the splash screen use the "adapted from phet" and to make it no longer translatable.

**Comment by samreid** [comment]
My comment in https://github.com/phetsims/joist/issues/374

> @jessegreenberg and @ariel-phet: in #383 we decided to make the "adapted from PhET" logo a single non-translatable image and show it in the splash screen (as well as the navbar). I was going to proceed with this, but it looks like the AI files don't include the "adapted from" text, perhaps it is still added in Joist. @ariel-phet and @jessegreenberg how would you like to proceed?

**Comment by samreid** [comment]
I completed the work in the above commits, and reassigned to @jessegreenberg for review in https://github.com/phetsims/joist/issues/374

@jessegreenberg after you have reviewed the code, please reassign to me if there are issues for me to work on/discuss.  If all seems well, please reassign #383 to @pixelzoom to see if there is anything else left to do.

**Comment by jessegreenberg** [comment]
Changes look good to me @samreid, layout looks good in the navbar and the logo also looks good in the splash screen.  @pixelzoom is there anything else to do for this issue?

**Comment by pixelzoom** [comment]
Looks good to me. Closing.
