### ISSUE TITLE
branch: splash-script

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#391]
See https://github.com/phetsims/joist/issues/382

**Comment by samreid** [comment]
Ready to merge to master.  I messaged on dev public:

Sam Reid [1:23 PM] 
Brace yourselves, I’m merging branches for chipper and joist to support splash screens.

[1:27] 
I’ll also have to run grunt generate-development-html for each repo and commit it, so it will be a many-repo commit.

**Comment by samreid** [comment]
I've locally merged and and run grunt generate-development-html.  I tested 2 requirejs sims and one build at a few different screen sizes on mac chrome, all seems well.  A bit of AQUA isn't revealing other problems.  I noticed one potential phet-io problem I'll create a separate issue for.

**Comment by samreid** [comment]
Branch merged and ready for deletion (here and in chipper).  I'll verify, delete, close.

**Comment by samreid** [comment]
Branch deleted, closing.

**Comment by zepumph** [comment]
Should be re-deleted as part of phetsims/special-ops#198

**Comment by samreid** [comment]
Deleted via the GitHub web interface, closing.
