### ISSUE TITLE
Factor out ScreenButton to its own file

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#395]
currently screenButtons (large and small) are being created on the spot from VBoxes in HomeScreenView.js. It should be in its own file.

**Comment by zepumph** [comment]
This was much more work than #394 and #393. It involved a lot of logic to manage small vs large screen buttons. After spending a fair amount of time simplifying the duplicated code from the first commit, I think that things look good, but it should definitely be looked into just in case I missed something important. I haven't done a lot of work in joist before. @samreid do you think you can look over this at some point?  I feel pretty good about it being functional code, perhaps less pretty than desired though.

Both phet-io and phet fuzz tests are passing.

**Comment by pixelzoom** [comment]
Problems noted in the TODO items added to the code in the above commit. Let me know if you have questions.  These are similar to the problems in #393 and #394, so let me (or @samreid) know if you have questions.

**Comment by samreid** [comment]
I'd recommend to read through @pixelzoom's review comments as well as the recommendations in #394 (to see if any of them apply here as well), then please reassign to me and @pixelzoom once a 2nd draft is ready.

**Comment by zepumph** [comment]
Will you guys take another look at this one too when you can. Thanks.

**Comment by pixelzoom** [comment]
A few documentation issues (fixed in above commit), but otherwise looks good. @zepumph feel free to close after reviewing what was missing.
