### ISSUE TITLE
Splash screen loading bar border is not symmetrical

### ISSUE THREAD

**Issue by phet-steele** [phetsims/joist#400]
The left side of the loading bar is just ever so slightly thinner than the right side:

<img width="938" alt="screen shot 2017-01-25 at 1 45 25 pm" src="https://cloud.githubusercontent.com/assets/5863899/22308632/fb7c8d34-e304-11e6-934a-83948a0b4e7d.png">

Seen on macOS 10.12.3 Chrome. For phetsims/tasks/issues/764.

**Comment by samreid** [comment]
This appears to be an svg aliasing problem.

**Comment by samreid** [comment]
Upon closer inspection, it seems like the left side is getting clipped, perhaps the svg bounding box isn't wide enough to account for the stroke width.

**Comment by jonathanolson** [comment]
Explicit width/height (and ideally namespace ` xmlns='http://www.w3.org/2000/svg' `) in the SVG element itself may fix this. Viewbox could also be used, but is more complicated.

**Comment by samreid** [comment]
I have replicated the problem in http://www.colorado.edu/physics/phet/dev/html/faradays-law/1.3.7-dev.3/faradays-law_en.html

![image](https://cloud.githubusercontent.com/assets/679486/22806532/d1be8844-eedf-11e6-8403-04627b820e8d.png)

**Comment by samreid** [comment]
Joist, brand and chipper have branches "splash-script" for this.

**Comment by samreid** [comment]
Those branches are too stale to work with master.

**Comment by samreid** [comment]
I merged master to the branches without any hassle.  Here is the div as shown in the chrome dev tools:

![image](https://cloud.githubusercontent.com/assets/679486/22806863/69bde544-eee1-11e6-8ee1-ce9ade79c102.png)

**Comment by samreid** [comment]
Putting x at 1 instead of 0 seems to solve the problem:

![image](https://cloud.githubusercontent.com/assets/679486/22807205/ff720bf0-eee2-11e6-8eea-55879c8e1eb0.png)

Is it still aligned, or should I subtract off some width?

**Comment by samreid** [comment]
Here are guides that show how bad the alignment is:

![image](https://cloud.githubusercontent.com/assets/679486/22807235/32529bf2-eee3-11e6-9903-495fe9934853.png)

it would be good to clean that up.

**Comment by samreid** [comment]
Proposed fix in http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.3.1-dev.3/energy-skate-park-basics_en.html

**Comment by phet-steele** [comment]
This is what I see, and it looks fine to moi:

![screen shot 2017-02-10 at 12 39 54 pm](https://cloud.githubusercontent.com/assets/5863899/22841278/2964d39c-ef8e-11e6-99bc-b85e2c77c598.png)

Closing.
