### ISSUE TITLE
Ordering of model/view steps and Timer/TWEEN

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#401]
Currently, Sim.js has the order:

1. Fire input events
2. model.step
3. view.step
4. Timer.step
5. TWEEN.update

This is problematic, since if any code relies on Timer or TWEEN.update, model.step and view.step can't assume all model/view "state changes" have happened.

Say you have some expensive-to-run view code (you want to run it only once per frame) that updates the positions of every model item:
```js
step: function( dt ) {
  this.viewItems.forEach( function( viewItem ) {
    viewItem.translation = modelViewTransform.modelToViewPosition( viewItem.model.position );
  } );
}
```
and also some vanilla "add an view item when a model item gets added" code:
```js
this.modelItems.addItemAddedListener( function( modelItem ) {
  var viewItem = new ViewItem( modelItem );
  self.viewItems.push( viewItem );
  self.addChild( viewItem );
} );
```

Now things go bad if you ever allow any component that uses Timer to add a model item (through no fault of the component on its own):
```js
var someProp = new Property( 5 );
var numberPicker = new NumberPicker( someProp, /* ... */ );
someProp.link( function( newCount, oldCount ) {
  if ( newCount > oldCount ) {
    self.modelItems.push( new ModelItem() );
  }
} );
```

for the above example, when you hold down the NumberPicker, it uses FireOnHoldInputListener (with Timer) to start creating model items. Thus you get the following order:

1. view.step (we position all current view items).
2. Timer.step
  a. Creates a model item
  b. Creates a view item, adds it to the scene with NO positioning

and you have an unpositioned view element showing up in the sim. The point isn't "this can be fixed by positioning view elements when created", it's that "view.step's one job is invalidated by Timer firing later".

So can we consider switching these to:

1. Fire input events
2. Timer.step
3. TWEEN.update
4. model.step
5. view.step

so that Timers act more like input events, or is there a way of having separate Timers for the model and view? If not, can we add model/view postTimerStep() functions that execute after Timer/TWEEN fire?

Does anyone anticipate that this type of reordering (particularly with TWEEN) would break things?

What type of testing would be appropriate if we make these changes?

**Comment by samreid** [comment]
The reason TWEEN was later in the sequence was that we have primarily used it as a visual sugar for the animation--hence applied it after the model step.  That being said, I don't think anything would break if we update the steps to the order you described.

Another alternative (just brainstorming for completeness): we could have 
1. Fire input events
2. Model timer
3. Model tween
4. model.step
5. View timer
6. View tween
7. View.step

**Comment by jonathanolson** [comment]
If we have separated model/view timers and model/view TWEENs, @samreid above proposal (https://github.com/phetsims/joist/issues/401#issuecomment-277037239) sounds great.

**Comment by samreid** [comment]
@jonathanolson what about:

Fire input events
Timer.step
model.step
TWEEN.update
view.step

**Comment by jonathanolson** [comment]
Done in the step-order branch.

@samreid, can you review?

@jbphet, can you let me know when a good time would be to test some sim behavior, including expression-exchange (that has the tween interactions)?

**Comment by samreid** [comment]
All of the logic seems good and the new order is as requested.  A new difference I noticed is that TWEEN used to only run when not on the home screen, now it runs any time.  If all TWEENS are transient, that shouldn't be a significant new problem.

I tested a few sims, including ones with TWEEN and all seems well. I'd recommend this for master.

Also, once in master, I was thinking about this pattern:
```js
screen && screen.model.step && dt && screen.model.step( dt );
```

instead of
```js
        if ( screen && screen.model.step && dt ) {
          screen.model.step( dt );
        }
```

I've generally been tending toward the former, but not feeling too strongly about it.

**Comment by jonathanolson** [comment]
> A new difference I noticed is that TWEEN used to only run when not on the home screen, now it runs any time.

I don't think so, before my change it used to run outside of the home screen:
```js
        // Update the active screen, but not if the user is on the home screen
        if ( !this.showHomeScreenProperty.value ) {

          // step model and view (both optional)
          screen = this.screens[ this.screenIndexProperty.value ];

          // If the DT is 0, we will skip the model step (see https://github.com/phetsims/joist/issues/171)
          if ( screen.model.step && dt ) {
            screen.model.step( dt );
          }
          if ( screen.view.step ) {
            screen.view.step( dt );
          }
        }

        Timer.step( dt );

        // If using the TWEEN animation library, then update all of the tweens (if any) before rendering the scene.
        // Update the tweens after the model is updated but before the scene is redrawn.
        if ( window.TWEEN ) {
          window.TWEEN.update( phet.joist.elapsedTime );
        }
```

> Also, once in master, I was thinking about this pattern

Also thought about it, and I'm fine with it. Feel free to make the change if you like it.

**Comment by samreid** [comment]
> I don't think so, before my change it used to run outside of the home screen

Thanks for clarifying, you are correct.

**Comment by jbphet** [comment]
I checked out the joist step-order branch and tested the only sim I have that does some TWEEN things in the model, and saw no problems.  I also checked the behavior of TWEEN in the view for Area Builder, Arithmetic, and Gene Expression Essentials and saw no problems.

**Comment by pixelzoom** [comment]
If the order of things is going to be changed, then https://github.com/phetsims/joist/issues/404 should be addressed also - TWEEN animations are currently not associated with a Screen, and continue to run when switching screens.

**Comment by jonathanolson** [comment]
Planning on moving these changes over to master and tracking remaining TWEEN ordering (or animation replacements) in https://github.com/phetsims/joist/issues/404.

**Comment by jonathanolson** [comment]
Pushed to master.
