### ISSUE TITLE
branch: step-order

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#402]
For https://github.com/phetsims/joist/issues/401

**Comment by jbphet** [comment]
I think I recall that this was merged with master.  GitHub says that it is 177 commits behind master.  Can this branch be removed and the issue closed?

**Comment by jonathanolson** [comment]
Deleted, thanks for noticing.

**Comment by zepumph** [comment]
Should be re-deleted as part of phetsims/special-ops#198

**Comment by jonathanolson** [comment]
Deleted.
