### ISSUE TITLE
Deselected homescreen buttons should start grayish

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#403]
@ariel-phet pointed out that the new Joist homescreen buttons all start bright instead of the deselected ones starting out grayish (as they used to).  Perhaps this broke in recent refactoring.  I'll take a look shortly.

**Comment by samreid** [comment]
@ariel-phet pointed out that this was buggy in http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.47/unit-rates_en.html?showAnswers&randomEnabled=false

I'll publish a new one for testing.  @pixelzoom heads up that we're going to dev.48 for Unit Rates.

**Comment by samreid** [comment]
New Unit rates is published here:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.48/unit-rates_en.html

@ariel-phet can you please take a close look and make sure the behavior is good?

**Comment by ariel-phet** [comment]
@samreid behavior looks correct to me, you might want to email the dev group about this change if anyone has had the bug in a recent RC or such

**Comment by samreid** [comment]
I notified the skype channel with this text:

> Builds from master which show the home screen (i.e. have more than 1 screen) since Feb 8 may exhibit this problem: https://github.com/phetsims/joist/issues/403 .   If you have been publishing RC or production versions from master since then, please review the issue and update accordingly.
