### ISSUE TITLE
PhetMenu accessibleContent triggers dispose multiple times

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#405]
Noticed in https://github.com/phetsims/scenery/issues/601.

Running Balloons and Static Electricity and opening the phet menu twice triggers disposal on the menu a second time, due to the `self.dispose()` in createPeer.

Can we just drop the disposal of the PhetMenu? I'm not sure what purpose it serves.

**Comment by jessegreenberg** [comment]
> I'm not sure what purpose it serves.

Hmm, nor do I, and I wish I did.  Seems fine to drop.  Actually the block of ```this.accessibleContent = {}```, and will be replaced with the Accessibility mixin in the near future.

**Comment by jessegreenberg** [comment]
Done above, closing.
