### ISSUE TITLE
disable "show answers" feature in production versions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#406]
Add something to joist that allows us to determine (at runtime) whether we're running a production version. The main purpose of this is to turn off query parameters that reveal answers. 

@jonathanolson suggested adding `Sim.isProduction` that parses the version number.

**Comment by pixelzoom** [comment]
@jonathanolson What do you think about this solution?

```js
isProduction: function() { return assert === null; }
```

**Comment by pixelzoom** [comment]
Or maybe we don't even need `isProduction`.  Would this be too awful in (for example) URQueryParameters, immediately after the `QueryStringMachine.getAll` call?

```js
URQueryParameters.showAnswers = !!( assert && URQueryParameters.showAnswers );
```

**Comment by pixelzoom** [comment]
Ah.... `assert` is also stripped out of dev versions. Bummer.

**Comment by pixelzoom** [comment]
I'm not wild about testing the version identifier.  But if all production versions truly followed the same convention, then it would be:

```js
isProduction: function() {
   return /^\d{1,2}\.\d{1,2}\.\d{1,2}$/.test( phet.chipper.version );
}
```

But would this be a problem for PhET-iO versions? Or research versions?

**Comment by jonathanolson** [comment]
> But would this be a problem for PhET-iO versions? Or research versions?

Definitely for phet-io, potentially other (future) versions. Could consider leaving it up to the Brand object to see (if it is brand-customized), then the 'phet' brand would just check `/^\d+\.\d+\.\d+$/`, the phet-io brand would check `/^\d+\.\d+\.\d+-phetio$/` or include other suffixes.

Alternately, we could add a flag in the build process (that will be complicated for maintenance releases and build-server).

If we're concerned about showing answers, it may be simplest to white-list domain ranges (www.colorado.edu/physics/phet/dev, phettest.colorado.edu, localhost/127.0.0.1, etc.) instead.

**Comment by jonathanolson** [comment]
> URQueryParameters.showAnswers = !!( assert && URQueryParameters.showAnswers );

We could have most dev builds skip the uglify step (so assertions can be turned on), but we'd probably want RCs to uglify.

**Comment by pixelzoom** [comment]
I'm unclear on a viable way to do this.  And now that I've created issues for where this needed to be applied in my sims, I'd like to get it done.  So labeling to (re)discuss at developer meeting.

**Comment by jonathanolson** [comment]
Thoughts on:

> Could consider leaving it up to the Brand object to see (if it is brand-customized), then the 'phet' brand would just check /^\d+\.\d+\.\d+$/, the phet-io brand would check /^\d+\.\d+\.\d+-phetio$/ or include other suffixes.

**Comment by samreid** [comment]
What about only enabling these features if the version contains "-dev" or "-rc"?

**Comment by jonathanolson** [comment]
> What about only enabling these features if the version contains "-dev" or "-rc"?

More specific patterns may be helpful, if things like `1.0.0-phetio-rca` could ever be potentially used for an 'RCA' organization, etc.

**Comment by samreid** [comment]
Perhaps checking if the string endsWith `-dev.[0-9]+` or `-rc.[0-9]+`?

**Comment by jonathanolson** [comment]
That sounds safe enough to me.

**Comment by pixelzoom** [comment]
3/2/17 dev meeting:
• Parse version identifier for `-dev.[0-9]+` or `-rc.[0-9]+`
• `Sim.isDevVersion` and `Sim.isRCVersion`

**Comment by pixelzoom** [comment]
We have `SimVersion, but it's used only by `UpdateCheck`.

`Sim` doesn't use `SimVersion`, it stores the version identifier as a string:

```js
220 this.version = packageJSON.version; // @public (joist-internal)
```

And there are multiple ways of getting the version identifier:

• Global `phet.joist.sim.version`
• Global `phet.chipper.version` if it's a published version (is this true for phet-io?)
• `SimVersion.parse`, as done by UpdateCheck

After discovering that `phet.chipper.version` is defined only by published versions, I'm tempted to write:

```function isProductionVersion() { return !!phet.chipper.version; }```

... but not confident that this would work with phet-io versions.

If I have to parse the version identifier, I'm tempted to add these static functions to SimVersion:

```js
    /**
     * Does the specified version identifier correspond to a dev version?  E.g. '1.0.0-dev.2'
     * @param {string} versionIdentifier
     * @returns {boolean}
     */
    isDevVersion: function( versionIdentifier ) {
      return /^\d+\.\d+\.\d+-dev.[0-9]+$/.test( versionIdentifier );
    },

    /**
     * Does the specified version identifier correspond to an RC (release candidate) version?  E.g. '1.0.0-rc.2'
     * @param {string} versionIdentifier
     * @returns {boolean}
     */
    isRCVersion: function( versionIdentifier ) {
      return /^\d+\.\d+\.\d+-rc.[0-9]+$/.test( versionIdentifier );
    }
```

... with awful call sites like:

```js
URQueryParameters.showAnswers = URQueryParameters.showAnswers && 
  !(SimVersion.isDevVersion( phet.joist.sim.version ) ||  SimVersion.isRCVersion( phet.joist.sim.version ));
```

Or I could take the easy way out and add more baggage to Sim:

```js
isShowAnswersEnabled: function() {
  var isDevVersion = /^\d+\.\d+\.\d+-dev.[0-9]+$/.test( this.version );
  var isRCVersion =  /^\d+\.\d+\.\d+-rc.[0-9]+$/.test( this.version );
  return ( isDevVersion || isRCVersion );
}
```

... with call sites that look  like:

```js
URQueryParameters.showAnswers = URQueryParameters.showAnswers && phet.joist.sim. isShowAnswersEnabled();
```

@jonathanolson @samreid, your input is needed:

• Can we just test if `phet.chipper.version` is defined? 
• If we have to parse the version identifier, where should we get it?
• Where should the parsing functions live?
• What should the call sites look like?

**Comment by pixelzoom** [comment]
A side issue here is that I no longer have any faith in the consistency of PhET's version identifier. Imo that is because (a) we haven't evolved the syntax and semantics to accommodate phet-io and (b) we've been publishing things (particularly phet-io) that don't conform to the syntax that we originally agreed on.

**Comment by samreid** [comment]
> Can we just test if phet.chipper.version is defined?

I ran Unit rates 1.0.0-dev.64 and saw this in the console:
![image](https://cloud.githubusercontent.com/assets/679486/23538152/53c17090-ff8e-11e6-8fd5-d94382f1fb3c.png)

I tested the production version of Make a Ten and saw:
![image](https://cloud.githubusercontent.com/assets/679486/23538175/71f89aa2-ff8e-11e6-8cb1-ea5b437cc37d.png)

So it seems we cannot use the existence phet.chipper.version to distinguish between dev/rc/production versions, because we would like to be able to show answers in published dev and rc versions.

> • If we have to parse the version identifier, where should we get it?
Use phet.joist.sim.version because the chipper one is only available for built versions.

> Where should the parsing functions live?

How about in SimVersion.parse?

> What should the call sites look like?

Create a simVersion instance in Sim.js like this:
```js
this.simVersion = SimVersion.parse( packageJSON.version, phet.chipper.buildTimestamp );
```

Then create `phet.joist.sim.simVersion.isDev` and `phet.joist.sim.simVersion.isRC` and `phet.joist.sim.simVersion.isDevOrRC` then call sites will look like 

```js
URQueryParameters.showAnswers = URQueryParameters.showAnswers && phet.joist.sim.simVersion.isDevOrRC;
```

**Comment by samreid** [comment]
> A side issue here is that I no longer have any faith in the consistency of PhET's version identifier. Imo that is because (a) we haven't evolved the syntax and semantics to accommodate phet-io and (b) we've been publishing things (particularly phet-io) that don't conform to the syntax that we originally agreed on.

In https://github.com/phetsims/chipper/issues/507#issuecomment-255193337 we decided to add the phetio string as metadata into the version number.  This conforms to semver as "Additional labels for pre-release and build metadata" and is formalized and documented in getVersionForBrand.js.  Please clarify your specific concerns so we can address or discuss them.

**Comment by jonathanolson** [comment]
Basically what @samreid said, with the addition that relying the existence of phet.chipper.version sounds very fragile to future changes.

**Comment by pixelzoom** [comment]
@samreid @jonathanolson So you're OK with having both of these in Sim.js?

```
 // @public (joist-internal)
this.version = packageJSON.version;

// @public (joist-internal)
this.simVersion = SimVersion.parse( packageJSON.version, phet.chipper.buildTimestamp );
```

**Comment by pixelzoom** [comment]
Perhaps there's no need for `this.simVersion` in Sim?  Could just use `this.version`?

**Comment by pixelzoom** [comment]
... ah, but this functionality really belongs in SimVersion, not in Sim.

**Comment by pixelzoom** [comment]
Having both `this.version` and `this.simVersion` has a smell to it, can't bring myself to do it.  So I investigated replacing `this.version` with `this.simVersion`.  I immediately ran into 3 sims that are improperly accessing `this.version`, see issues above.

**Comment by samreid** [comment]
After addressing the 3 issues identified above, let's set up Sim.js so it only has Sim.version and it is of type {SimVersion}.

**Comment by jonathanolson** [comment]
> @samreid @jonathanolson So you're OK with having both of these in Sim.js?

Having one way to get the version string sounds better.

> So I investigated replacing this.version with this.simVersion.

Sounds nice.

> I immediately ran into 3 sims that are improperly accessing this.version, see issues above.

It was public at the time, and sims will need to be able to access the version. Can these usages be refactored?

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/joist/issues/406#issuecomment-283865364 @samreid said:
> Please clarify your specific concerns so we can address or discuss them.

• No documentation about version identifier format and semantics in SimVersion (where it presumably belongs).
• Incomplete specification of the version identifier in getVersionForBrand.
• Multiple ways to get the version identifier, including multiple globals.
• Multiple representation of the version identifier (string, SimVersion)
• Multiple places where the version identifier is being read from package.json (Sim, UpdateCheck)
• Brand names that don't match the name used in the metadata (e.g. "phet-io" and "phetio")
• The fact that this issue has become non-trivial to address

**Comment by jonathanolson** [comment]
> Multiple places where the version identifier is being read from package.json (Sim, UpdateCheck)

`phet.chipper.version` is also accessed for things like statistics (google-analytics.js), if the version information is being consolidated.

**Comment by pixelzoom** [comment]
I really don't want to address this version identifier mess.  I'm so tempted just to add this to Sim:

```js
// See https://github.com/phetsims/joist/issues/406
isDevOrRCVersion: function() {
  var isDevVersion = /^\d+\.\d+\.\d+-dev.[0-9]+$/.test( this.version ); // e.g. '1.0.0-dev.1'
  var isRCVersion =  /^\d+\.\d+\.\d+-rc.[0-9]+$/.test( this.version ); // e.g. '1.0.0-rc.1'
  return ( isDevVersion || isRCVersion );
}
```

**Comment by jonathanolson** [comment]
> I really don't want to address this version identifier mess. I'm so tempted just to add this to Sim

That looks fine for now. I can potentially tackle the larger version refactoring later at lower priority.

**Comment by pixelzoom** [comment]
The plan was to do something like this in a sim's *QueryParameter file:

```js
URQueryParameters.showAnswers = URQueryParameters.showAnswers && phet.joist.sim. isDevOrRCVersion();
```

This is going to work because `phet.joist.sim` doesn't exist yet.  So we can either (a) modify `URQueryParameters.showAnswers` someplace outside of URQueryParameters, or (b) make every site that uses `URQueryParameters.showAnswers` perform the check, e.g.:

```js
if ( URQueryParameters.showAnswers && phet.joist.sim. isDevOrRCVersion() ) {
   // code to show answers
}
```

Really don't like either of these options.

**Comment by pixelzoom** [comment]
I need feedback from other developers on this to proceed, so labeling for developer meeting.   In https://github.com/phetsims/joist/issues/406#issuecomment-284897888, do you prefer option (a) or (b)?  Or do you have a better idea?

**Comment by pixelzoom** [comment]
The current scheme for phetio version identifiers breaks the detection function that we approved in https://github.com/phetsims/joist/issues/406#issuecomment-284893658.   E.g. `1.0.0-phetiodev.1` will not be recognized as a dev version.

**Comment by samreid** [comment]
Agreed, it looks like those regular expressions don’t support the current versioning scheme for phet-io sims.

**Comment by samreid** [comment]
> In https://github.com/phetsims/joist/issues/406#issuecomment-284897888, do you prefer option (a) or (b)?  Or do you have a better idea?

This idea is half-baked, but I wanted to pitch in for brainstorming:

```js
    // Shows answers for Shopping questions and marker editor
    showAnswers: {
      type: 'flag',
      ignored: phet.chipper.version.production
    },
```

Query String Machine could ignore entries with the `ignored` attribute set to true, and we could make a version object available during startup (possibly as a chipper global).

**Comment by pixelzoom** [comment]
I think that's preferable to parsing the version identifier - which (as noted in #411) is something that clients should not be doing directly.

**Comment by jonathanolson** [comment]
At what point in sim execution is phet.chipper.version.production required to be initialized? Looks like in the preloads before initialize-globals?

**Comment by pixelzoom** [comment]
If it's going to be used by QueryStringMachine, then yes, it needs to happen either before  initialize-globals.js, or in initialize-globals.js before requiring query parameters.

**Comment by pixelzoom** [comment]
4/13/17 dev consensus:

Punt on this until version id issues are resolved, specifically:
https://github.com/phetsims/joist/issues/411
https://github.com/phetsims/chipper/issues/560

Deferring and unassigning until then.

**Comment by pixelzoom** [comment]
Ideally `showAnswers` would move to initialize-globals.js, disabled for production versions in one place, and used by sims via `phet.chipper.queryParameters.showAnswers`.

**Comment by pixelzoom** [comment]
It occurred to me that we are already detecting production versions in order to strip out assertions.  In initialize-globals.js:

`573     var isProduction = $( 'meta[name=phet-sim-level]' ).attr( 'content' ) === 'production';`

How about if we promote this to a global variable? I.e.:

`window.phet.chipper.isProduction = $( 'meta[name=phet-sim-level]' ).attr( 'content' ) === 'production';`

Then to disable `showAnswers` in production versions (e.g. EqualityExplorerQueryParameters):

```js
var EqualityExplorerQueryParameters = QueryStringMachine.getAll( {

    // Shows answers to challenges in the 'Solve It!' screen. If assertions are enabled and fuzzMouse is disabled,
    // this also adds a 'test challenge generators' button to the level-selection UI.
    // For internal use only, not public facing.
    showAnswers: { type: 'flag' },
   
    ....
} );

EqualityExplorerQueryParameters.showAnswers = EqualityExplorerQueryParameters.showAnswers && !phet.chipper.isProduction;
```
The downside is that, like assertions, this will also disable `showAnswers` in dev versions. But that may be acceptable. And it seems preferable to using the version identifier to detect production versions.  

Labeling for discussion at developer meeting.

**Comment by pixelzoom** [comment]
We could enable `showAnswers` in debug.html by looking at `phet.chipper.isDebugBuild`.  This is how assertions are currently enabled in debug.html (see initialize-globals.js, line 576).

**Comment by samreid** [comment]
The two preceding comments seem sensible to me, and not too much work, easy to test.

**Comment by jonathanolson** [comment]
> It occurred to me that we are already detecting production versions in order to strip out assertions. In initialize-globals.js:

It looks like that is hard-coded to 'production' in the template, so ANY sim build includes that flag. So the above notes look good as long as we want showAnswers when "it's either not built or is the debug build".

**Comment by pixelzoom** [comment]
7/12/18 dev meeting:
Use approach in https://github.com/phetsims/joist/issues/406#issuecomment-404299706.
Create globals phet.chipper.isProduction and phet.chipper.showAnswers.
@pixelzoom will do this, and use in EqEx.

**Comment by pixelzoom** [comment]
Thinking about this a bit more...   Since we may want to disable more than just the `showAnswers` query parameter (e.g. 'autoAnswer' in ArithmeticQueryParameter), perhaps we should have a global variable whose value indicates that we're running the the primary built html file.  I.e.: 

`(phet.chipper.isProduction && !phet.chipper.isDebugBuild )`

Do other devs think this is a good idea? Suggestion for this global's name?

**Comment by samreid** [comment]
My initial reaction is that `( phet.chipper.isProduction && !phet.chipper.isDebugBuild )` seems clear enough--it suggests that production builds can be the debug version or not.  I don't know that giving a new name to that combination would be helpful.  Happy to be proved wrong though!

**Comment by jbphet** [comment]
If we're going to have two parameters, how about having an object that could also contain a version ID in case we ever need to change it, e.g:

```js
phet.chipper.buildConfig = {
  isProduction: true,
  isDebugBuild: false,
  formatVersion: "1.0"
}
```

**Comment by pixelzoom** [comment]
@jbphet suggested:
> how about having an object ... `phet.chipper.buildConfig`

That doesn't address the issue.  Call sites would then have to do `( phet.chipper.buildConfig.isProduction && !phet.chipper.buildConfig.isDebugBuild )`.   And `buildConfig` has an entirely different meaning in the chipper implementation.

**Comment by pixelzoom** [comment]
I added `phet.chipper.isProduction` and `phet.chipper.queryParameters.showAnswers`.  The latter is set to overridden and set to false when running the primary built html file.  

Tested in equality-explorer with requirejs html file, equality-explorer_en_phet.html, and equality-explorer_all_phet_debug.html.  `?showAnswers` was ignored when used with equality-explorer_en_phet.html.

**Comment by pixelzoom** [comment]
All of my sims have been converted to use `phet.chipper.queryParameters.showAnswers`.

**Comment by pixelzoom** [comment]
@jonathanolson randomly selected to review.

**Comment by jonathanolson** [comment]
The commits and strategy look good to me. Closing.
