### ISSUE TITLE
[Safari] Splash screen increases in scale slightly after loading has begun

### ISSUE THREAD

**Issue by phet-steele** [phetsims/joist#407]
Blink and you'll miss it (actually the looping gif makes it very obvious, but it is very subtle otherwise):

![splashscreen01](https://cloud.githubusercontent.com/assets/5863899/23314208/364a8700-fa7e-11e6-91ec-fee12ccc604f.gif)

This is present on both mobile and desktop Safari. It happens every time I load the sim on macOS 10.12.3, but only happens once on the initial load for iOS 10.2 Safari. To make it happen again on mobile Safari, I can switch to and from another open tab, then reload the sim.

Tested with this link http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.3.1-dev.3/energy-skate-park-basics_en.html

**Comment by samreid** [comment]
I recommend to fix this not because it is a jarring visual issue but because it could indicate problems with how CSS is being dealt with in Joist, and could lead to problems in future browser versions (not just safari).

**Comment by samreid** [comment]
This is very subtle on my MBP, but I can see it.

**Comment by samreid** [comment]
To get to the same version of the code, I used dependencies.json and grunt --lint=false.  I tried commenting out several CSS parts in joist, but the problem persists.

**Comment by samreid** [comment]
The problem is that the image changes size.  On the first call, it is 273px wide then after load it is 274px wide.  

Adding this code works around the problem:

```js

  var splashImageWidth = 0;
  var splashImageHeight = 0;

  /**
   * Scale and position the given div, using the dimensions of the image for sizing.
   * @param {Element} div - the div to position
   * @param {HTMLImageElement} splashImg - the image to use for determining scale factor.  Not as exact as using the full
   *                                     - container div, but that dimension is not available on startup.
   */
  function positionDiv( div, splashImg ) {
    if ( splashImageWidth === 0 && splashImageHeight === 0 ) {
      splashImageWidth = splashImg.width;
      splashImageHeight = splashImg.height;
    }
    var currentWidth = splashImageWidth;
    var currentHeight = splashImageHeight;
```

**Comment by samreid** [comment]
Still seeing the problem in latest safari and merged with master.

**Comment by samreid** [comment]
I committed the workaround above and it still seems good for safari.

**Comment by samreid** [comment]
Dev version is here: http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.3.1-dev.5/energy-skate-park-basics_en.html

**Comment by samreid** [comment]
@jonathanolson suggested to check the naturalwidth

**Comment by samreid** [comment]
naturalWidth had the same problem as width, but @jonathanolson suggested to round out the image size by expanding the artboard then svg, and that seemed to fix the problem.  Didn't fix IE though.

**Comment by samreid** [comment]
Fixed in the preceding commits, on hold until we work out IE in #408

**Comment by samreid** [comment]
This is out for testing in the aforementioned issue.

**Comment by phet-steele** [comment]
I no longer see this on macOS 10.12.6, iOS 10.3 beta, or iOS 9.3.5.
