### ISSUE TITLE
Prevent negative DTs

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#409]
In https://github.com/phetsims/make-a-ten/issues/273, @phet-steele found it looks like leaving Firefox open with the sim (and leaving overnight) will cause an incorrect ordering of dates when re-opening. This means the sim thinks it has gone back in time, stepping the simulation with a negative dt.

This can also be reproduced by stepping the system clock back in time.

Sims are not built to handle these negative dts, so we should gracefully handle incorrect ordering of dates by:

1. Don't call stepSimulation with negative dts.
2. Move back to the "old" time, so the sim will still animate after system clock changes.

Additionally, looking into whether this causes bugs for currently-available sims may be good (@ariel-phet, is this worth time, should this just be fixed in master, or should there be any maintenance releases, particularly for make-a-ten?)

**Comment by phet-steele** [comment]
> This can also be reproduced by stepping the system clock back in time.

@ariel-phet it should be noted that, so far, FF is the only browser that is doing this "naturally". All browsers are affected by the manually adjusting the system clock.

**Comment by jonathanolson** [comment]
Fix pushed to master, @phet-steele can you test make-a-ten to ensure that this prevents the bug (using the system clock?)

Fuzzing sims with possibly negative timesteps caused assertion errors in the following: atomic-interactions, energy-forms-and-changes, fluid-pressure-and-flow, gene-expression-essentials, make-a-ten, twixt demo (I'm running a longer fuzz dedicated to this to see if it pops up anything else). Note that this may not catch all bugs, because some sims may not error out (but instead behave incorrectly).

**Comment by ariel-phet** [comment]
@jonathanolson I think it would be fine to do a Make-a-Ten maintainence releases (it looks like the credits might need adjusting). But I would just fix in Master and not worry about published sims.

**Comment by phet-steele** [comment]
Chances are github thinks I'm making this comment before this issue existed (my clock is a few days behind)!

> @jonathanolson I think it would be fine to do a Make-a-Ten maintainence releases

@jonathanolson Make a Ten is fixed in current master. I tested with macOS 10.12.3 Chrome & FF

**Comment by jonathanolson** [comment]
Ok, with it fixed I'll plan on tracking make-a-ten maintenance release in https://github.com/phetsims/make-a-ten/issues/273.
