### ISSUE TITLE
Can we add a Property to track whether the sim is visible?

### ISSUE THREAD

**Issue by jbphet** [phetsims/joist#421]
In https://github.com/phetsims/joist/issues/418, a Property was added to the `Screen` type that monitors whether or not that screen is active.  While working on sonfication, a need has come up where continuously generated sounds need to be turned off when the browser tab containing the simulation is hidden.  I added a bit of experimental code that works for this, and was wondering if it should be integrated into joist.  The code looks like this:

```js
    // create a property the tracks whether this sim is visible
    var simVisibleProperty = new BooleanProperty( true );
    // TODO: The following should probably be integrated into joist
    document.addEventListener( 'visibilitychange', function() {
      simVisibleProperty.set( document.visibilityState === 'visible' );
    }, false );
```

Caniuse.com seems to indicate that `visbilitychange` is available in our supported platforms (https://caniuse.com/#search=visibilitychange) , but I've only tested it on Chrome, and not extensively there.  I just thought I'd see what other devs thought before spending much time on it.

**Comment by samreid** [comment]
It sounds to me like you are barking up the right tree.

**Comment by samreid** [comment]
@ariel-phet points out that by default browsers leave audio on for inactive tabs.  @jbphet will ask at the upcoming sonification meeting what the desired behavior is.

But if we are capping dt, then it could be confusing for the sim to continue making audio while the model is not running.  For instance, in FAMB it could "sound like" the skater went many miles, but when you tab back you can see they only moved a few centimeters.

@jbphet points out that some sounds are continuous, and that changing the gain can handle switching tabs.

**Comment by samreid** [comment]
@samreid suggested a specific new axon property `browserTabVisibleProperty` in Sim.js, which could be used for this (if we proceed).

**Comment by samreid** [comment]
There is general agreement that a new Axon property would be the right way to do this.

**Comment by jbphet** [comment]
The sonfication behavior was discussed in the 5/12/2017 Sonification Design Meeting, and it was decided that continuous sounds should stop playing when a sim is hidden.  So, there is at least one use case where this will be needed soon.  I will move forward with the implementation.

**Comment by jbphet** [comment]
Implemented, assigning to @samreid to review.  I tried to match style of `Sim.js`, but feel free to move things around if doing so would be more consistent with the spirit of this file.

**Comment by samreid** [comment]
The implementation in Joist looks like it works properly.  I would recommend to take it one step further and change the API to match the page visibility API specs.  https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API

For instance, the proposed joist implementation currently checks `document.visibilityState === 'visible'`, but there are other states we may want to eventually support, such as `hidden`, `prerender` and `unloaded`.  So we could rename the joist property to `documentVisibilityStateProperty` to match the browser API variable name `document.visibilityState` and have it be a `Property.<string>`.  This way we will not have to make any changes if we want to use these other values in the future.

**Comment by jbphet** [comment]
@samreid said:
> I would recommend to take it one step further and change the API to match the page visibility API specs.

I feel like this would essentially cause leakage of the specifics of the Page Visibility API into our sim code, and this seems of questionable value to me.  According to https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API, browser support for the states `prerender` and `unloaded` are optional.  That means the only states that we can trust are `visible` and `hidden`, so why not keep it simple and just use a boolean?  That way, developers who wish to use this property don't have to look up the various possible states, what they mean, and basically ramp up on the Page Visibility API.

Also, my particular immediate need within is to turn off sound when the sim is hidden.  The finer details of the visibility state don't matter in this use case, and I suspect others who use this property will be in the same situation.  If a situation arises in the future where the other states are needed, we could modify this property then, or if it's a very unique situation, they could reach into the document API themselves.

Back to you @samreid - feel free to label for dev meeting if you think getting input from other devs would be helpful.

**Comment by samreid** [comment]
Since prerender and unloaded are currently optional, it seems unlikely that we will use them (at least in the near future).  So perhaps your recommendation would be best.  Still, I think it would be good to have @pixelzoom or @jonathanolson give their opinion before we proceed.

**Comment by jbphet** [comment]
Unassigning myself for now. @jonathanolson and @pixelzoom - please assign back to me once you've both weighed it.  I'll set a calendar reminder to check in on this in two weeks.

**Comment by jonathanolson** [comment]
To me, the best first thing would be to have a boolean property (with whatever states mapping to true/false that makes sense). Then if we ever truly need more information, we can figure out something more detailed?

**Comment by samreid** [comment]
Sounds good to me, thanks @jonathanolson. @jbphet I think everything is all set.

**Comment by jbphet** [comment]
Okay, thanks all.  Closing.
