### ISSUE TITLE
Add support for Legends of Learning API

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#423]
We would like to add support for the Legends of Learning platform.

**Comment by samreid** [comment]
@jessegreenberg and I experimented with using a standardized PhET postMessage API for doing this in #420 but since Legends of Learning requires a single-file solution, it seems we won't be able to use an iframe adapter to make that work.  @jonathanolson helped us try out making a sim iframe data base64 but it was laggy and buggy.

So I think we should investigate another way of adding support for legends of learning messages.

**Comment by samreid** [comment]
I have a proposed implementation for this, but it relies on (a) putting hooks in Sim.js in 2 spots, and chipper using Query String Machine.  It may not be able to cherry pick into all legacy branches for maintenance releases.

**Comment by samreid** [comment]
OK I made commits to master to support Legends of Learning messages, trying to remain as decoupled as possible but still satisfy the constraint of having a single build and one-file solution.  It is not too different from our strategy for game up camera.

@jessegreenberg can you please review these joist changes?

**Comment by jessegreenberg** [comment]
The nice thing about a standardized postMessage API was that Sim.js didn't need any hooks that were specific to a third party.  @samreid what do you think about changing to something like https://github.com/phetsims/chipper/commit/c4c0850781639c3e0f0b441984317dadbd9024f3 and https://github.com/phetsims/joist/commit/d626170c4b990f6513974a4f2c3adc7429d2420b , where ThirdPartySupport.js will delegate setting up specific listeners depending on the third party that is specified in a query parameter?

**Comment by samreid** [comment]
I see where you are going with this, but am wondering if there would be cases where 3rd party hooks shouldn't be mutually exclusive.  We could have something like ThirdPartySupport.js and it would just iterates through the list:

```js
if (legendsOfLearning) new LegendsOfLearning();
if (somethingElse) new SomethingElse();
...

Rather than mutually exclusive ones.  This could still keep Sim.js pretty clean?

**Comment by jessegreenberg** [comment]
Yes, that makes sense.  @samreid also pointed out that the lookup using ThirdPartySupport makes it much less clear when trying to understand where the third party hooks are. The recommendation in https://github.com/phetsims/joist/issues/423#issuecomment-305375062 is clean.  I will revert to the strategy in https://github.com/phetsims/joist/issues/423#issuecomment-304490286.

**Comment by jessegreenberg** [comment]
I reverted the changes for third party support so we are back to https://github.com/phetsims/joist/issues/423#issuecomment-304490286.  @samreid is there anything else to do for this issue?

**Comment by samreid** [comment]
We published build-an-atom with LOL features we are going to test out, closing.
