### ISSUE TITLE
Should we make a more generic name for the legendsOfLearning feature set?

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#426]
At yesterday's meeting @jbphet proposed that we come up with a more generic query parameter than `?legendsOfLearning` in case another group wants to leverage the same features.  The features in particular are:

* After sim construction is complete, a message "init" is broadcast to the parent.
* When the sim receives a postMessage with its data `messageName`==='pause', the sim will pause
* When the sim receives a postMessage with its data `messageName`==='resume', the sim will resume

You can see these implemented in master in LegendsOfLearningSupport.js. Should we make a generic term for these features?  If so, what should we call it?  Would it be OK if we told other 3rd parties to "use the legendsOfLearning API"?

Tagging @pixelzoom and @jonathanolson and @jbphet for discussion.

**Comment by jonathanolson** [comment]
Not sure why it would need a name, presumably it would just be part of the available API?

If it has its own access control/permissions/etc. that get enabled separately, then maybe it would be a "Pause" feature? Presumably we could always send the init message?

**Comment by pixelzoom** [comment]
> Should we make a generic term for these features?

I'm still advocating a general API, rather than adding customer-specific features (or even groups of features).

> Would it be OK if we told other 3rd parties to "use the legendsOfLearning API"?

That would probably be up to Legends Of Learning.  But I also think it's undesirable from PhET's perspective.

**Comment by samreid** [comment]
> Not sure why it would need a name, presumably it would just be part of the available API?

The name we are deciding on is the name of the query parameter.

> Presumably we could always send the init message?

I'm not sure what kind of interaction that may have with other places the simulation is embedded, if any.

> I'm still advocating a general API,

Sounds good, but to support legends of learning we must broadcast an "init" message.  What if another group wants us to emit "initialized" or "gameReady"?  Maybe a query parameter that indicates what message is sent after the sim is constructed, and if there is no such query parameter, then nothing will be emitted.  Maybe we could use the same approach for pause/resume.

`
sim.html?onInitialized=init&pauseCommand=pause&resumeCommand=resume
`

That doesn't lock us in to one particular API and will still support LOL

**Comment by jonathanolson** [comment]
> The name we are deciding on is the name of the query parameter.

The name of the query parameter to enable this particular subset of features? What about a query parameter per feature enabled?

**Comment by pixelzoom** [comment]
Why do these features need to be enabled/disabled?  If we had a generic API, why wouldn't these (and other) features always be enabled?

**Comment by samreid** [comment]
> What about a query parameter per feature enabled?

That was proposed in https://github.com/phetsims/joist/issues/426#issuecomment-307441969 and seems reasonable.

> Why do these features need to be enabled/disabled?

As described in https://github.com/phetsims/joist/issues/426#issuecomment-307441969 I'm not sure what kind of interaction that may have with other places the simulation is embedded, if any.  Maybe it would be fine to leave them on for all time, but then we could use a query parameter so we aren't locked in to specific (e.g. LOL-specific) terms for each command.

**Comment by samreid** [comment]
I'm actually liking the idea of the proposed strategy much more than the "adapter iframe" strategy.  Let's discuss abandoning that and focusing on this.  Would be good to get input from @jessegreenberg on this topic.

**Comment by pixelzoom** [comment]
Related to https://github.com/phetsims/joist/issues/420 (Standardize a PhET postMessage API).

**Comment by pixelzoom** [comment]
Related to https://github.com/phetsims/joist/issues/420 (Standardize a PhET postMessage API).  The important conclusion there was https://github.com/phetsims/joist/issues/420#issuecomment-304477377, where @samreid said:

> @jessegreenberg and I wrote a 1st draft of a public postmessage API. However, it seems we will be unable to use our proposed thin-wrapper-adapter solution (or at least it will be awkward to use it) for Legends of Learning because they require a single-file submission.

**Comment by samreid** [comment]
It was suggested to use the expanded query parameters like `sim.html?onInitialized=init&pauseCommand=pause&resumeCommand=resume` and combine that with the option to create composite mappings like `legendsOfLearning` mapping to the above commands.

**Comment by samreid** [comment]
Regarding whether things are on by default or not @zepumph and I can discuss whether messages are targeted or not--whether it is safe to broadcast init always, or always listen.

**Comment by samreid** [comment]
@pixelzoom suggests just focusing on Legends of Learning at the moment rather than trying to generalize it too much.

**Comment by ariel-phet** [comment]
@samreid since we are not doing something more general and just focusing on Legends of Learning for the short term future, can we close this issue?

**Comment by samreid** [comment]
Closing for now, thanks.
