### ISSUE TITLE
"addition" should be "additional" in the tandem ID

### ISSUE THREAD

**Issue by phet-steele** [phetsims/joist#427]
The about dialog variable `this.additionalLicenseStatement` is currently instrumented as:

`[sim].navigationBar.phetButton.phetMenu.aboutDialog.additionLicenseStatement`

We are missing the "al" at the end of "addition" in the tandem ID. In other words, it should say "additional". @zepumph, pretty sure that many currently delivered phet-io sims have this typo.

**Comment by pixelzoom** [comment]
Relevant code in AboutDialog:

```js
    this.additionalLicenseStatement = new MultiLineText( Brand.additionalLicenseStatement, {
          font: new PhetFont( 10 ),
          fill: 'gray',
          align: 'left',
          maxWidth: MAX_WIDTH,
          tandem: tandem.createTandem( 'additionLicenseStatement' )
        }
```

The tandem id currently violates the convention that the id must match the variable name.

**Comment by pixelzoom** [comment]
Note that changing this tandem id is a breaking change for any clients using `[sim].navigationBar.phetButton.phetMenu.aboutDialog.additionLicenseStatement`.

**Comment by zepumph** [comment]
>Note that changing this tandem id is a breaking change for any clients using `[sim].navigationBar.phetButton.phetMenu.aboutDialog.additionLicenseStatement.`

Agreed. We should really figure out a system to track these. The most basic strategy would be to document all of these changes in one place, with the date changed, so if someone needs to update to a new version, we can reference this document and look at all of the changes from (Date 1) to (Date 2). 

tagging @samreid if he wants to comment.

I hope this is something that we can talk about in the coming meeting about phet-io.

**Comment by zepumph** [comment]
https://github.com/phetsims/phet-io/commit/8073319a923e89328f86654795ea3084335cdc0a added a document to track api changes.

**Comment by zepumph** [comment]
I think the rest of this discussion can be taken up in https://github.com/phetsims/phet-io/issues/1137. Closing.

**Comment by zepumph** [comment]
Reopening since this is a phet-io breaking change to the api, and it is currently not being tracked. Unassigning.

**Comment by samreid** [comment]
Hopefully not too many clients are using `additionLicenseStatement` in their wrappers, and our API diffing tool when it exists should address this API change.  I don't think there is a need for tracking this now.  Also, I am somewhat confused that there are 3 open "breaking API change" issues and 8 closed ones.  What is the distinction between them?

**Comment by zepumph** [comment]
All of the closed issues are from issues from a year or more ago. I have since repurposed this label into open issues to keep track of changes made to the api until we figure out the next system.

> our API diffing tool when it exists should address this API change. 

I was using this as a solution without thinking through that our api change detection will need to be backwards compatible. We don't need to necessarily keep track of this. I defer to your judgment.

**Comment by samreid** [comment]
OK thanks for discussing it, my recommendation is to focus efforts on an API diffing tool.
