### ISSUE TITLE
Hyperlinks in the AboutDialog can only be selected with 'Enter' key, no 'Space'?

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#428]
When using keyboard navigation to access the about dialog's hylinks, you can select these with the 'Enter' key.

![image](https://user-images.githubusercontent.com/6856943/27558031-405d6e52-5a68-11e7-92f7-5dd79b6da389.png)

I would have expected 'Space' to work also. Is this by design, or a bug. @terracoda could you speak to this?
It is probable that I have it wrong.

**Comment by terracoda** [comment]
@zepumph, great question.
Links are operable with the Enter key.
Buttons are operable with Space or Enter keys.

Not sure why, but that's the default expected behaviour.

**Comment by zepumph** [comment]
Good to know. Thanks!
