### ISSUE TITLE
AboutDialog multiline texts don't wrap

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#435]
Discovered by @phet-steele in https://github.com/phetsims/QA/issues/32 

When the QA credits got very large, they extended past the MAX_WIDTH in the AboutDialog. I'm not quite sure how that happened. I would have expected to see it wrap, here is what it looks like now.

![image](https://user-images.githubusercontent.com/6856943/29049891-0e7a8058-7b85-11e7-8f0b-e2186383b256.png)

So as a workaround I have been adding new lines manually to the credit strings.

**Comment by jonathanolson** [comment]
RichText would get wrapping somewhat for free if I handle it the approximate way I was thinking for adding line breaks (https://github.com/phetsims/scenery-phet/issues/310).

If wrapping text is desired, that would be the correct long-term way. Wrapping, line breaks and bidirectional text is ... complicated, so I'm probably looking at between 2-20 hours depending on exactly what level of quality is needed.

@ariel-phet, since this is now the second time this has come up, it may be worth about ~2 hours of investigation time to see if I can knock this out quickly (or come up with a decent way of handling text that is less optimal than what browsers do). Thoughts?

**Comment by ariel-phet** [comment]
@jonathanolson yes I think 2-3 hours of investigation would be reasonable. Let's check in once you have done that.

**Comment by jonathanolson** [comment]
RichText now has 'lineWrap'. It mostly works, but I'll need to handle whitespace slightly differently (will handle tomorrow).

For the purposes of this issue (which won't have right-aligned text with a space right before an HTML tag with long content), please try it out.

**Comment by jonathanolson** [comment]
> @jonathanolson yes I think 2-3 hours of investigation would be reasonable. Let's check in once you have done that.

I'm at about 3 hours, expecting 30 minutes more to implement improvements to whitespace. RichText now supports manual line breaks (`<br>`) and line-wrapping, along with multi-line features (will probably deprecate MultiLineText).

**Comment by jonathanolson** [comment]
Current RichText wraps at spaces or HTML tag boundaries currently. Feel free to try it out as a replacement for MultiLineText here?

**Comment by zepumph** [comment]
I replaced all MultilineTexts with RichText in the CreditsNode. Then I removed the hard coded new line in the QA credits string, the result was the same as with MultilineText. I printed out the width of the about dialog and it was 601, event though I would have expected that `MAX_WIDTH` would have caused wrapping.

```js
 // Maximum width of elements in the dialog
  var MAX_WIDTH = 550;
```

What do you think @jonathanolson? Does it have something to do with a way that the AboutDialog is implemented? Nothing obvious stood out to me

**Comment by zepumph** [comment]
Thanks for implementing that @jonathanolson! Back to you because of some strange layout in right to left languages.

**Comment by jonathanolson** [comment]
Above commit fixes RTL layout with high confidence. Closing.

**Comment by pixelzoom** [comment]
Reopening.  3 things still to be done:

(1) CreditsNode needs `options = _.extends( ... )`.  It's currently using `options.maxWidth`, which may not exist.

(2) Some of the credits can't rely on lineWrap, and require explicit line breaks.  These are probably the `thanks:` credits field in *-main.js. 

(3) Old-style (`\n`) line breaks that are no longer needed should be removed from *-main.js, they are misleading.

**Comment by pixelzoom** [comment]
The "thanks" credits that need conversion are the ones that consist of multiple bullets.  E.g. in acid-base-solutions-main.js:

```js
 thanks: '\u2022 Conversion of this simulation to HTML5 was funded in part by the Royal Society of Chemistry.\n' +
              '\u2022 Thanks to Mobile Learner Labs for working with the PhET development team to convert this\nsimulation to HTML5.'
```

**Comment by pixelzoom** [comment]
There's 1 line break to convert, and 1 to remove.  Should be:

```js
 thanks: '\u2022 Conversion of this simulation to HTML5 was funded in part by the Royal Society of Chemistry.<br>' +
         '\u2022 Thanks to Mobile Learner Labs for working with the PhET development team to convert this simulation to HTML5.'
```

**Comment by pixelzoom** [comment]
I converted acid-base-solutions-main.js as an example, see above commit.

**Comment by zepumph** [comment]
I did the above 3 tasks. There was only one other place where a '<br>' was needed for "thanks bullets." 

The wrapping is based on the max size of the AboutDialog, which is 550px wide. There are a few dialogs where this looks weird now that we got rid of the manual newlines. This is because there is one line (probably the thanks or QA credit) that is about twice as long as all the others, but only wraps for the last word or so. 

This is currently working as expected, but perhaps warrants some design attention. No matter this issue is pretty close to ready to close. @pixelzoom will you review please

**Comment by pixelzoom** [comment]
Options in CreditsNode was still a little wonky, I cleaned up in the above commit. 

There were several credits that had problems, see:
https://github.com/phetsims/balancing-chemical-equations/commit/38c7e6c62466f2aca2b58ae3125194d3be727a27
https://github.com/phetsims/energy-skate-park-basics/commit/a5b34100057c4b305e11a5fc5db6bcff2aa3b785
https://github.com/phetsims/fraction-matcher/commit/4a8101b39f3c897b2cfa5574ae0fc11a625bc55b
https://github.com/phetsims/isotopes-and-atomic-mass/commit/87f95ddf48dc4d1cb775fab88172446091d4717d

Back to @zepumph. Feel free to close after reviewing.

**Comment by zepumph** [comment]
All looks good. Thanks for the learning. Closing
