### ISSUE TITLE
[Instance Proxies] Do screen titles have a maxWidth?

### ISSUE THREAD

**Issue by phet-steele** [phetsims/joist#438]
@jessegreenberg @samreid @zepumph, presumably this is a joist issue. It may not be too important, but worth noting.

It looks like both the screen title text on the home screen (not the sim title) and the screen title text in the navbar do not have a maxWidth set...or something. Typing in long strings pushes elements around the screen.

- On the home screen, other screen buttons are pushed off screen:

1. Go to http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.3.0-phetiorc.3/wrappers/instance-proxies/instance-proxies.html?sim=forces-and-motion-basics&relativeSimPath
2. Select the Motion screen icon (do not enter the screen)
3. Edit `forcesAndMotionBasics.homeScreen.view.netForceScreenLargeButton.text`
4. Click the Net Force screen button
![screen shot 2017-08-24 at 3 34 39 pm](https://user-images.githubusercontent.com/5863899/29689811-ca784e16-88e1-11e7-99e0-eb2d1ac13c18.png)

- In the navbar, the screen with the long string migrates its way to the right:
Editing `forcesAndMotionBasics.navigationBar.netForceScreenButton.text`
![screen shot 2017-08-24 at 3 48 39 pm](https://user-images.githubusercontent.com/5863899/29690310-bd6680ba-88e3-11e7-90a5-f253d3867291.png)

Seen on macOS 10.12.6 Chrome. For phetsims/QA#42.

**Comment by samreid** [comment]
I reproduced the problem, it seems ideally we would want to reflow the layout if these screen names are changed or set a max width.  @ariel-phet and @kathy-phet can you help prioritize this issue?

**Comment by kathy-phet** [comment]
I think setting a max width for the names, something that is beyond what we would choose as a name, would be good.

**Comment by samreid** [comment]
In the preceding commit, I used maxWidth for the home screen buttons and it prevents the text from getting too large, but unfortunately the text doesn't remain centered (even though resize:true is set in VBox).

![image](https://user-images.githubusercontent.com/679486/29746413-a6c03fa4-8a96-11e7-8fd0-f2ecde0e5b05.png)

Still, I think this is a step in the right direction.  @pixelzoom or @jonathanolson or @jbphet can you please review the preceding commit?

**Comment by samreid** [comment]
Likewise, @pixelzoom @jonathanolson or @jbphet can you please review the 2 preceding commits regarding fixing the navigation bar button text from getting too wide?

**Comment by jonathanolson** [comment]
It sounds fairly safe (after a brief review), as long as we don't try to bold the text after or something like that.

Let me know if you want an in-depth review.

**Comment by samreid** [comment]
A cursory review seems acceptable to me, I'm inclined to move the centering issue in https://github.com/phetsims/joist/issues/438#issuecomment-325171719 to a new lower-priority issue and close this one.
