### ISSUE TITLE
attempt to register the same listener twice for Screen.backgroundColorProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#441]
Related to https://github.com/phetsims/axon/issues/140 (Phase 2: remove the guard from Property.link).

In Sim.js:

```js
      screens.forEach( function initializeScreen( screen ) {
        workItems.push( function() {
667       screen.backgroundColorProperty.link( self.updateBackground );
          screen.initializeModel();
        } );
        workItems.push( function() {
          screen.initializeView();
        } );
      } );
```

If Screens share the same instance for `backgroundColorProperty`, then line 667 above will result in an attempt to register the same listener twice. 

We'll need to resolve this before proceeding with sim testing for https://github.com/phetsims/axon/issues/140.

**Comment by pixelzoom** [comment]
Proposed fix:

```js
667       screen.backgroundColorProperty.link( self.updateBackground );
```

to:

```js
     // Screens may share the same instance of backgroundProperty, see joist#441
     if ( !screen.backgroundProperty.hasListener( self.updateBackground ) ) {
      screen.backgroundColorProperty.link( self.updateBackground );
    }
```

@samreid @jonathanolson any objections?

**Comment by pixelzoom** [comment]
I went ahead an committed the proposed fix, since it was needed to proceed with sim testing. @samreid or @jonathanolson please review.

**Comment by jonathanolson** [comment]
Seems safe enough, thanks.
