### ISSUE TITLE
Sim: startedSimConstructorEmitter and endedSimConstructionEmitter

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#442]
I ran into this while looking for something that fires after the Sim is up an running.

In Sim.js:

```js
// @public (phet-io) Emitter for PhET-iO data stream to describe the startup sequence
this.startedSimConstructorEmitter = new Emitter();

// @public (phet-io) Emitter for PhET-iO data stream to describe the startup sequence
this.endedSimConstructionEmitter = new Emitter();
```

Problems here....

(1) One is named "Constructor", the other "Construction".  Tricky.

(2) The documentation tells us nothing about when these fire. And it's not at all clear from reading the code: `startedSimConstructorEmitter` isn't at the very beginning of the constructor. `endedSimConstructionEmitter` is in async code that appears in `start`. 

(3) Are these for use _only_ by PhET-iO?

**Comment by zepumph** [comment]
`statedSimConstructorEmitter` doesn't exist anymore. `endedSimConstructionEmitter` can be used by anyone like LegendsOfLearnerSupport does. Doc has been improved. Closing
