### ISSUE TITLE
Are there too many active Properties?

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#443]
This came up last week during a PhET-iO design meeting to rework Faradays law with @samreid and @kathy-phet. In instance proxies you can only set the sim's active property, but there are active properties for each screen that seem to just be read only. Should they be renamed? Is this even a problem. From a phet-io standpoint it is a little confusing that they are named the same thing, but don't work the same. @jbphet what do you think. I believe you had something to do with the implementation to support the sonification wrapper?

Marking for dev phet-io, but it could be a broader conversation.

**Comment by samreid** [comment]
Here is the doc for the recently added Screen.activeProperty:

```js
    // @public {Property.<boolean>} indicates whether the Screen is active. Clients can read this, joist sets it.
    // To prevent potential visual glitches, the value should change only while the screen's view is invisible.
    // That is: transitions from false to true before a Screen becomes visible, and from true to false after a Screen becomes invisible.
    this.activeProperty = new Property( false, {
      phetioValueType: TBoolean,
      phetioInstanceDocumentation: 'this Property is read-only, do not attempt to set its value'
    } );
```

It doesn't appear to have a tandem, is this showing up in instance proxies or the data stream?

**Comment by phet-steele** [comment]
> It doesn't appear to have a tandem, is this showing up in instance proxies or the data stream?

@samreid yup:

`energySkateParkBasics.homeScreen.activeProperty`
`energySkateParkBasics.introScreen.activeProperty`
`energySkateParkBasics.frictionScreen.activeProperty`
`energySkateParkBasics.playgroundScreen.activeProperty`

and yup:

<img width="497" alt="screen shot 2017-10-04 at 9 17 17 am" src="https://user-images.githubusercontent.com/5863899/31183803-e12e8d6e-a8e4-11e7-9cd7-4de0fdc1b704.png">

**Comment by jbphet** [comment]
@zepumph said:

> @jbphet what do you think.  I believe you had something to do with the implementation to support the sonification wrapper?

Yes, I requested these properties and worked on them to support being able to mute sounds when a screen within the sim is not being shown, or when the tab in which the sim is running in hidden, or when the whole browser window is minimized.  Please see https://github.com/phetsims/joist/issues/418 and https://github.com/phetsims/joist/issues/421.  I would have no objection to renaming these if other names worked better, but we'd need to coordinate such changes with the existing sonification wrappers, since such a change would constitute a change to the PhET-iO API..

**Comment by samreid** [comment]
It makes sense to me for the screens to be active and the sim to be independently active.  Perhaps this can be covered with `phetioDocumentation`?

**Comment by zepumph** [comment]
I think the reason why I was getting confused is because the sim `activeProperty` behaves differently than the individual screen's `activeProperty`. You can set the sim's, but not the screen's. At first I thought it may be confusing to have the same name, but now I disagree with past michael.

I think it is the most straightforward to set the active property on the entire sim, and let joist internal set the screen active properties. Keeping the same name keeps the same thought process about what the Property means. Using tandem flags or `TPropertyReadOnly` or however we do it, I think that these Properties should be made phetioReadOnly. Currently this is done with `phetioDocumentation`.

Note that the screen `activeProperty` is mentioned no where in https://github.com/phetsims/joist/issues/445, but must still be supported for sonification, so I will add it with the same thought process as the `browserTabVisibleProperty`

Closing.
