### ISSUE TITLE
Add screen name to title when multiscreen sim is run with one screen via `?screens=3`

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#449]
From https://github.com/phetsims/joist/issues/445: 
> when multiscreen sim and you specify 1 screen with ?screens=2, then update the title in the nav bar to include the screen name: "Forces and Motion: Basics — Motion"

This seems like a nice improvement across the board, and will be especially nice is PhET-iO. I will take a stab at this and then ask for review since it touches every multiscreen sim.

**Comment by zepumph** [comment]
Commit is below. @samreid  will you please review.

**Comment by samreid** [comment]
I suspect we will need to internationalize this using a pattern so it will work well for RTL languages as well.

**Comment by zepumph** [comment]
How about that implementation? Especially the name of the string key, I feel like I'm bad at naming those things.

**Comment by samreid** [comment]
There is a lint error:

> /Users/samreid/github/joist/js/NavigationBar.js
  45:3  error  Mismatched var in require(string!), key=simTitleWithScreenNamePattern, var=simTitleWithScreenNamePattern, desiredVar=simTitleWithScreenNamePatternString  string-require-statement-match

**Comment by samreid** [comment]
Everything else looks good to me.

**Comment by samreid** [comment]
Do @kathy-phet and @ariel-phet want maintenance releases of this feature for our LOL sims?

**Comment by kathy-phet** [comment]
It's not a high priority, but if it can be done without much difficulty, it seems worthwhile. Not time sensitive either.

**Comment by zepumph** [comment]
@samreid I'm very un-involved in the LOL process, what sims would need this if we decide it is worth the cost?

**Comment by zepumph** [comment]
@samreid I see https://github.com/phetsims/joist/issues/450, want to just add these commits into that?

https://github.com/phetsims/joist/commit/a3e46b837526023de9518247a1e68b991be440b6
https://github.com/phetsims/joist/commit/d418f9eb727f33d50b6cb403ce9b1c96f479f8ad4
https://github.com/phetsims/joist/commit/28a9c131cd75787a431b64af63f52a185cb842ca

**Comment by ariel-phet** [comment]
Removing assignment since @kathy-phet answered

**Comment by samreid** [comment]
> @samreid I see https://github.com/phetsims/joist/issues/450, want to just add these commits into that?

I suspect that will be best, but I have little experience with running 4 cherry picks together--it sounds as if the cherry picking will be order dependent.  I'm wondering if we should attempt to squash these 3 commits into one?  Also, the commits above introduce a new i18n string and I don't expect it to cause trouble but would love to double check that with someone more familiar with the i18n project.

**Comment by zepumph** [comment]
Assigning @jbphet. Is the new i18n string from https://github.com/phetsims/joist/commit/d418f9eb727f33d50b6cb403ce9b1c96f479f8ad used appropriately?

**Comment by zepumph** [comment]
@samreid I am not familiar with consolidating commits, does that mean reverting all three and making the changes as 1? I think that that may take just as long as the following three lines of bash in joist. Order does matter:

```
git cherry-pick a3e46b837526023de9518247a1e68b991be440b6
git cherry-pick d418f9eb727f33d50b6cb403ce9b1c96f479f8ad
git cherry-pick 28a9c131cd75787a431b64af63f52a185cb842ca
```

**Comment by samreid** [comment]
> I am not familiar with consolidating commits, does that mean reverting all three and making the changes as 1 commit?

Search google for `git squash` but in this case it looks like 3 cherry picks are appropriate.

**Comment by phet-steele** [comment]
What an unexpected and brilliant surprise this enhancement is! Thanks @zepumph and @samreid.

While we are at it, any clue how we could change the name of the sim in the troubleshooting info (when clicking "Report a Problem...")? Not critical, but figure I should say something:

> Troubleshooting information (do not edit):
> Name: ‪Projectile Motion‬
> URL: https://www.colorado.edu/physics/phet/dev/html/projectile-motion/1.0.2-rc.1/projectile-motion_en.html?screens=3
> Version: 1.0.2-rc.1 2017-10-31 20:18:14 UTC


Would be cool if "Name" said "Name: Projectile Motion - Drag". I know there are a bunch of reasons we don't need to do this, just seeing if it could be done easily.

**Comment by phet-steele** [comment]
OH! And the About dialog still has the old name:

<img width="801" alt="screen shot 2017-11-01 at 11 16 25 am" src="https://user-images.githubusercontent.com/5863899/32287362-30152100-bef6-11e7-998f-df2f8e6837f9.png">

**Comment by zepumph** [comment]
Your wish is my command! I'll at least take a look. I don't think it will be difficult. Is there any reason that we wouldn't want it in the about dialog?

**Comment by zepumph** [comment]
@kathy-phet do you think this title update should go into the about dialog as well?

**Comment by kathy-phet** [comment]
I don’t think so actually. The About menu is for the sim and version, so I think should reflect the full code in the file regardless of the query parameter. We haven’t removed any code in the file, so I think it should be the name for the base sim.

Happy to discuss. But it also seems like it’s not going to make much difference for the user.

Best,
Kathy

Sent from my iPhone

On Nov 1, 2017, at 1:43 PM, Michael Kauzmann <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #449<https://github.com/phetsims/joist/issues/449> to @kathy-phet<https://github.com/kathy-phet>.

**Comment by samreid** [comment]
My inclination is to use the hyphenated title everywhere the old title was used.  That is, on line 71 of Sim.js replacing `name` with the hyphenated name (if one ?screens is specified).  This will automatically update everything downstream including the browser tab title, save filename, etc.  That is, my recommendation is to treat it as if it is really the name of the sim instead of just a different way of displaying it in one spot, because in effect is it a different sim.

**Comment by zepumph** [comment]
>My inclination is to use the hyphenated title everywhere the old title was used. That is, on line 71 of Sim.js replacing name with the hyphenated name (if one ?screens is specified). This will automatically update everything downstream including the browser tab title, save filename, etc. That is, my recommendation is to treat it as if it is really the name of the sim instead of just a different way of displaying it in one spot, because in effect is it a different sim.

I'm inclined to agree unless the AboutDialog needs to uphold the "actual" sim name for licensing.

**Comment by samreid** [comment]
@pixelzoom and @ariel-phet feel strongly that the "screen-based" title only appear in the navbar, and that the browser tab and about dialog remain the same.  @pixelzoom reason is that it is the same "deliverable", i.e. the same software being downloaded and run (albeit with customization).

**Comment by samreid** [comment]
@zepumph will prevent cases like "Concentration -- Concentration"

**Comment by samreid** [comment]
Or it should error out if you put ?screens=... for a one screen sim?

**Comment by pixelzoom** [comment]
11/2/17 dev meeting:

Do this only in the navbar, not in the About dialog or Report A Problem.  Also not in the browser title because that may mess up statistics.

**Comment by kathy-phet** [comment]
Sounds decided - only in the nav bar.

**Comment by samreid** [comment]
@zepumph anything else to do for this issue other than https://github.com/phetsims/joist/issues/449#issuecomment-341513411
?

**Comment by jonathanolson** [comment]
https://github.com/phetsims/pendulum-lab/issues/197 also waiting for this (it looks like).

**Comment by zepumph** [comment]
Looks good, closing!

**Comment by jonathanolson** [comment]
Is there a list of commits to cherry-pick to apply this to a maintenance release branch?

**Comment by zepumph** [comment]
https://github.com/phetsims/joist/issues/449#issuecomment-340573495

**Comment by jonathanolson** [comment]
Thanks!

**Comment by zepumph** [comment]
I'm pretty sure that we decided that

**Comment by phet-steele** [comment]
> @phet-steele please close if this sounds good to you.

Yup, just making sure we covered all of our bases.
