### ISSUE TITLE
Home screen icons shift when one selected

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#45]
For example, in Forces and Motion: Basics, if you tap on the "Motion" tab, the friction and acceleration tabs change location a bit.

**Comment by pixelzoom** [comment]
This issue is waiting for review by @jonathanolson.

**Comment by jonathanolson** [comment]
Fix looks good, thanks!

**Comment by phet-steele** [comment]
@samreid Idk if this fix never worked or if there was regression, but I'm seeing this again.

**Comment by samreid** [comment]
I reproduced the problem on Chrome/Forces and Motion Basics/Requirejs

**Comment by phet-steele** [comment]
@samreid I found this version of ESPB built ten days after https://github.com/phetsims/joist/commit/bcc67fc74fe5d2324fb17f17e6e63d3ee7da1ad3 and it still has the problem: https://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.0.0-dev.23/energy-skate-park-basics_en.html
I'm not convinced that commit did anything.

**Comment by pixelzoom** [comment]
After the icons have shifted once, they never appear to do so again.  So my guess would be that there is duplicated (but slightly different) logic for initial state vs updates.

**Comment by pixelzoom** [comment]
In HomeScreenView, `var screenChildren` is a very misleading name.  "Children" in this context is typically `{Node[]}`.   But `screenChildren` is actually an array of data structures, where the data structure is defined on line 162:

`return { screen: screen, small: smallScreenButton, large: largeScreenButton, index: index };`

Highly recommended to rename `screenChildren`.

**Comment by pixelzoom** [comment]
I wonder if this is an issue with HBox?

**Comment by samreid** [comment]
Putting resize: true in the hBox makes it clear that the problem comes from the size of the border when a button is highlighted:

![famb2](https://user-images.githubusercontent.com/679486/35259999-2cda86a4-ffc6-11e7-82da-205e07345360.gif)

@pixelzoom or @jonathanolson what's the recommended way to eliminate the highlighting from the node's bounds?  Or should we give all of the nodes equal highlighting (but only one is opaque/visible)?

**Comment by samreid** [comment]
This code at the bottom of Frame.js's constructor solves the problem (you need to import Color too):

```js
    this.addChild( new Rectangle( -1.5 / 2, -1.5 / 2, this.frameWidth + 1.5, this.frameHeight + 1.5, {
      stroke: new Color( 0, 0, 0, 0 ),
      lineWidth: 4.5,
      x: this.rectangle.x,
      y: this.rectangle.y
    } ) );
```

However, I'd prefer to hear from @jonathanolson and/or @pixelzoom if there's a better way.

**Comment by jonathanolson** [comment]
> what's the recommended way to eliminate the highlighting from the node's bounds?

That's not recommended, it we repaint only changed bounds in the future, it could break things.

> This code at the bottom of Frame.js's constructor solves the problem

That works fine. If it helps, the string `'transparent'` is a CSS equivalent to `new Color( 0, 0, 0, 0 )`, and is somewhat easier to read (e.g. `stroke: 'transparent'`).

**Comment by samreid** [comment]
I pushed a fix that always creates and adds the highlight, but only shows it when the frame is supposed to be highlighted.  @jonathanolson or @pixelzoom can you please review?

**Comment by jonathanolson** [comment]
Changes and simplifications look good.

Using `Rectangle.bounds( Bounds2.rect( this.rectangle.x, this.rectangle.y, this.frameWidth, this.frameHeight ).dilated( 0.75 ), { ... } )` may be somewhat easier to understand. I'll leave up to @samreid .

**Comment by pixelzoom** [comment]
I trust whatever @samreid and @jonathanolson decide, so I'm going to bow out of this issue.

**Comment by samreid** [comment]
Thanks @jonathanolson, I went with Rectangle.bounds.  Can you check it again?

**Comment by jonathanolson** [comment]
Looks correct to me. I presume it's working? (I'm running snapshot comparison tests on a change, so I can't easily check out and verify right now). If so, can this be closed?

**Comment by samreid** [comment]
It works OK in my tests, but I'd love to run it past @phet-steele for the final say.

**Comment by phet-steele** [comment]
Works for me in master, using FAMB.

**Comment by samreid** [comment]
Thanks @jonathanolson and @phet-steele, closing.
