### ISSUE TITLE
Republish LOL sims with the animation frame fix

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#450]
From https://github.com/phetsims/joist/issues/447

@ariel-phet said:

Ah, it appears there is a google doc with this info:

https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0

Looks like Projectile Motion, Pendulum Lab, FAMB, BAA, ESPB should all receive this update.

UPDATE: changed BAM to BAA

**Comment by samreid** [comment]
The commit to cherry pick removes 1 line of code:
63046a699e8e3994f9c40f8d93482a497f0316b3

**Comment by samreid** [comment]
> Looks like Projectile Motion, Pendulum Lab, FAMB, BAM, ESPB should all receive this update.

Based on the spreadsheet, I think @ariel-phet probably meant BAA instead of BAM.

**Comment by samreid** [comment]
I created issues for the 5 affected simulations and assigned them to the appropriate developers, @ariel-phet would you like to leave this open as a "master" issue, or just continue in the sub-issues?

**Comment by ariel-phet** [comment]
@samreid yes meant BAA! And yes lets leave this open

**Comment by samreid** [comment]
Please note that we also want to publish with https://github.com/phetsims/joist/issues/449 and https://github.com/phetsims/joist/issues/458, both are still in development or review at the moment.

**Comment by jonathanolson** [comment]
The change from https://github.com/phetsims/joist/issues/458 looks good, presumably we can un-hold this?

**Comment by zepumph** [comment]
Indeed! We are good to go.

**Comment by samreid** [comment]
This issue is on hold while we proceed with the maintenance releases.

**Comment by samreid** [comment]
Removing hold to check status.

**Comment by pixelzoom** [comment]
Since we're currently republishing sims to update LoL support...  @samreid what is the status of this issue?

**Comment by samreid** [comment]
I'm not sure of the status of the LOL maintenance releases or republications.  I can see that several of the referenced issues above are closed.  Maybe @jonathanolson or @ariel-phet can comment?

**Comment by jonathanolson** [comment]
I'm not sure what to comment on. What is the issue that may/may not be patched in, and what sim release branches would need to be patched?

**Comment by samreid** [comment]
2 of the sims didn't need the patch, 2 were already maintenance released with the fix, and Energy Skate Park: Basics is pending re-release in https://github.com/phetsims/energy-skate-park-basics/issues/375.  In my opinion, this issue should be closed.  @ariel-phet in https://github.com/phetsims/joist/issues/450#issuecomment-340073198, you requested this to be left open as a parent issue when we were still working on it.  Can it be closed now?

**Comment by ariel-phet** [comment]
Sounds good @samreid, closing
