### ISSUE TITLE
Remove disableRequestAnimationFrame from TSim

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#452]
It is only used in `assess.html` to keep pointer events from interacting with the sim. These days we often use css (`pointer-events: none`) or setting the activeProperty if applicable. This method on TSim seems like unneeded bloat on the TType. @samreid what do you think?

**Comment by samreid** [comment]
Agreed, we should eliminate it and use a better way of disabling interaction.

**Comment by zepumph** [comment]
Alright. Since `assess.html` points to a published sim, I think that we should just delete it in master. When we rework `assess.html` there will be much more to do than just this call.

**Comment by zepumph** [comment]
I'm not sure why there was so much deliberation here, after looking into it, `Sim.disableRequestAnimationFrame` is no longer a method anyways, so this was already broken. Closing
