### ISSUE TITLE
Find a way to keep the logo in PhET-iO brand, but disable the menu

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#453]
From #445:
Kathy says clients will need to disable the phet button, perhaps via setPickable(false), OK to show the 3 dots, Kathy is not worried about that. The key is to keep the logo.

This could be done pretty easily if we create a new TType for the PhETMenu button that doesn't extend from node, that way you can't set its visibility, Then we can implement pickable on that Ttype. 

This strategy is straightforward and easy to implement, but isn't the best long term strategy. @samreid what do you think we should do?

**Comment by samreid** [comment]
The proposal to create a new type sounds great, perhaps also add an instance proxies control for it to call setPickable true/false.

**Comment by zepumph** [comment]
@samreid please review. I added TPhetButton that implements the same methods as TNode for pickable manipulation. This seems a bit strange and hard to maintain. Now if pickable changes in node, the dev will need to remember to fix it in TNode, but also in TPhetButton, which doesn't really make any sense, but seems to be the direction we are moving to take a step away from implementation details (like combining all Text TTypes into a single TPhETText or something).

**Comment by samreid** [comment]
Let's also remove the methods `TPhetButton.isPickable` and `TPhetButton.addPickableListener`, it will help clarify that the only reason the TType exists is to make the PhETButton unpickable.

The toStateObject/fromStateObject/setValue are necessary to capture the customization?

**Comment by zepumph** [comment]
@samreid, the instance proxy interface for pickable (createInstanceProxyDiv:127 or so) uses all three of these methods. I think that this implementation is good, and refactored nicely for use in TNode and TPhetButton. Is your concern added maintainability complexity?

**Comment by samreid** [comment]
I see, thanks for explaining that.  The only remaining problem (is it a problem?) is that you have to setPickable once on the home screen button and again on the navbar button.  Should we create a separate issue for that?

**Comment by zepumph** [comment]
Here is fine with me, but I'm drawing blanks on a solution. We could have the pickable interface through Sim, which has access to the nav bar and the home screen.

**Comment by samreid** [comment]
Maybe only instrument one TPhETButton instance and make sure it updates both real instances?

**Comment by samreid** [comment]
How about get rid of TPhETButton and create a new joist boolean property `phetButtonPickable` which defaults to true, and is used by all instances of the PhET Button?

**Comment by samreid** [comment]
@zepumph I'd love to hear your thoughts on the preceding idea.

**Comment by zepumph** [comment]
Thanks for your patience, I ran out of PhET-iO time last week. 

>How about get rid of TPhETButton and create a new joist boolean property phetButtonPickable which defaults to true, and is used by all instances of the PhET Button?

I think that could solve our problem. I'm thinking having a property in Sim. PhetButton is passed a Sim instance so it would be easy for all phetButtons to link to that property. Then TSim can interface accordingly. Any other thoughts? Should I go for it and see if it works?

**Comment by samreid** [comment]
I vote go for it!

**Comment by zepumph** [comment]
@samreid please review in code and instance proxies. Notice that we still need a TPhetButton type so that it doesn't resort back to TNode with full control over the button.

**Comment by samreid** [comment]
The preceding commits look great.  I thought we could remove TPhETButton and remove PhETButton's call to `tandem.addInstance` altogether, but when I do so, I get this assertion error: `Assertion failed: Only instrumented instances can emit to the data stream.`

It's confusing because TPhetButton doesn't declare any events.  @zepumph can you investigate?

**Comment by zepumph** [comment]
This is a bit of a strange case in terms of who owns the phetio event that is being added to the data stream. I addressed it in https://github.com/phetsims/phet-io/issues/1235#issuecomment-343295708 and we should pursue it there. Marking as on hold.

**Comment by samreid** [comment]
Proposed strategy is in https://github.com/phetsims/scenery/issues/711#issuecomment-372192021

**Comment by zepumph** [comment]
Honestly,  phetsims/scenery#711 has become this issue. It looks like a `PhetButtonIO` that doesn't extend node, but that has it's own pickable controls, is the leading solution. (although it could still change).

Closing this one.

**Comment by zepumph** [comment]
in https://github.com/phetsims/scenery/issues/711 we decided to go with `PhetButtonIO` as the solution here, but in https://github.com/phetsims/phet-io/issues/1326 we moved public NodeIO methods to properties, so this solution no longer works. As of now clients can just interface directly with the visibilityProperty. Tagging @samreid, isn't this a problem?

**Comment by samreid** [comment]
It was unclear why you said `PhetButtonIO` no longer works--it doesn’t extend NodeIO, so it doesn’t inherit the new Properties.  Can you elaborate?

**Comment by zepumph** [comment]
I guess what I am saying is that we will need to create a `pickableProperty` for PhetButtonIO, since it doesn't inherit from NodeIO. We decided that PhetButtonIO shouldn't be able to set its visibility, and to the same extent I think that applies to opacity.

**Comment by samreid** [comment]
Sure, let's adopt the same pattern for `PhetButtonIO.pickableProperty`

**Comment by samreid** [comment]
@zepumph said this would be good to solve before creating a dev version for https://github.com/phetsims/energy-skate-park-basics/issues/411

**Comment by samreid** [comment]
@zepumph said he'll tackle this.

**Comment by zepumph** [comment]
Added in the above commit. Closing

**Comment by zepumph** [comment]
@samreid please review.

**Comment by zepumph** [comment]
this should be fixed before https://github.com/phetsims/energy-skate-park-basics/issues/411#issuecomment-398110355

**Comment by zepumph** [comment]
Right! Thanks for that.
