### ISSUE TITLE
Add validation to ?screens to not accept duplicate indices

### ISSUE THREAD

**Issue by phet-steele** [phetsims/joist#457]
Currently something like `?screens=3,3` totally breaks.

Try https://www.colorado.edu/physics/phet/dev/html/projectile-motion/1.0.2-rc.1/projectile-motion_en.html?screens=3,3

If you do this with `?ea`, you get:

```
Uncaught Error: Assertion failed: there was already a model
    at window.assertions.assertFunction (assert.js:22)
    at DragScreen.initializeModel (Screen.js?bust=1509557319324:212)
    at Array.<anonymous> (Sim.js?bust=1509557319324:669)
    at Sim.js?bust=1509557319324:680
```

@samreid, thoughts?

**Comment by phet-steele** [comment]
Not sure if we should error and say "don't use the same index twice", or if we just ignore duplicates and only load one instance per passed index. So the above example would ignore the second "3" and just load one screen. Something like `?screens=1,3,3` would also ignore the second "3" and just load the 1st and 3rd screens.

**Comment by samreid** [comment]
Typically it is better to throw an error because it might indicate to clients they are doing something that makes no sense (in case it indicates a flaw in their thinking or software).

**Comment by samreid** [comment]
Committed above, the error is:

> Error for query parameter "screens": invalid value: 3,3

The error appears whether or not ?ea is turned on.  @phet-steele can you please test?

**Comment by samreid** [comment]
Bonus commit above.

**Comment by phet-steele** [comment]
Working great, thanks @samreid.
