### ISSUE TITLE
Screen buttons should be centered

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#459]
From https://github.com/phetsims/joist/issues/451#issuecomment-342212501

> Is that are new problem, or did it exist before the changes made for this issue?

@phet-steele said:

Looks like it happened when we moved the home screen button (so probably unrelated to this issue). The home screen button maybe used to not be considered when centering screen icons?

Production:
<img width="643" alt="screen shot 2017-11-06 at 9 52 55 am" src="https://user-images.githubusercontent.com/5863899/32453031-718e635e-c2d8-11e7-9d2f-db686d744b6c.png">

2.3.0-rc.3:
<img width="605" alt="screen shot 2017-11-06 at 9 53 05 am" src="https://user-images.githubusercontent.com/5863899/32453032-71a0434e-c2d8-11e7-920f-9f16bf9202dc.png">

We need to enforce centering with and without the home button (now can be hidden with ?homeScreen=false)

**Comment by samreid** [comment]
I let @ariel-phet know that I'd be spending a couple of hours on this soon.

**Comment by samreid** [comment]
It looks like the home button was accounted for in centering starting in fabc93650ec62e17e6da62e2aed2bf4bd7db4649

It would be good to get @jessegreenberg in this conversation since I'm not familiar with many of the details of https://github.com/phetsims/joist/issues/374 or the layout changes.

It looks like the original design was that the screen buttons (not accounting for the home button) would be centered in the nav bar.  It is easy to test for centering in screens 2-4 of forces and motion basics, which has a slider in the middle of the screen.  It also looks like fabc93650ec62e17e6da62e2aed2bf4bd7db4649 centered the entire batch of buttons including the home screen, which in my opinion, throws off the symmetry of the layout a bit.  But maybe it was necessary to accommodate long sim titles?  @jessegreenberg can you please take a look?

**Comment by jessegreenberg** [comment]
From #374 
> The title looks a bit too small in the worst case scenario. Centering the home screen icon + screen icons in the navbar (instead of just the screen icons) would give the title a bit more room.

Here is the 'worst case scenario' referenced from that comment (5 screens, long title, adapted-from-phet with a 'keyboard help'  button):
![ffcfc54a-bc03-11e6-8f94-303bf3694d13](https://user-images.githubusercontent.com/6396244/32671854-33008136-c606-11e7-902d-dde5b27b1f04.PNG)

Here is what the nav bar looks like in that case now:
![capture4](https://user-images.githubusercontent.com/6396244/32671856-3447191a-c606-11e7-9015-8753109ad8ea.PNG)

Centering the screens without the home icon would reduce the title size a bit. @ariel-phet @arouinfar @samreid are we OK with a smaller title if the screens are centered with the home icon?

**Comment by ariel-phet** [comment]
@jessegreenberg I am fine with reducing the title a bit, so long as for the "adapted from" we are using the second treatment shown in the comment.

**Comment by jessegreenberg** [comment]
> so long as for the "adapted from" we are using the second treatment shown in the comment.

Definitely,  first screen shot was taken before we changed it.

**Comment by arouinfar** [comment]
@jessegreenberg I'm also fine with reducing the title a bit to center the icons.

**Comment by jessegreenberg** [comment]
Sounds good, here is what it looks like now:
FAMB with home screen:
![center3](https://user-images.githubusercontent.com/6396244/32673852-e02bc06c-c60d-11e7-8ddd-175744ea7532.PNG)

FAMB without home screen:
![center1](https://user-images.githubusercontent.com/6396244/32673835-cbe7e8ec-c60d-11e7-9de4-13866cdc7f3e.PNG)

"Worst case scenario" from above:
![center2](https://user-images.githubusercontent.com/6396244/32673843-d58e66dc-c60d-11e7-9d50-0740b2bc6c58.PNG)

**Comment by jessegreenberg** [comment]
@samreid would you like to review?

**Comment by samreid** [comment]
Sure, I'll leave it assigned to myself to take a look, thanks!

**Comment by samreid** [comment]
Code change looks good, and tests in ESPB with and without stringTest=long look good, closing.
