### ISSUE TITLE
Sim: rAF? render?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#460]
While attempting to understand the chunk of code identified by @samreid in https://github.com/phetsims/joist/issues/208#issuecomment-342328089 ....

In Sim.js

```js
                // place the rAF *before* the render() to assure as close to 60fps with the setTimeout fallback.
                // http://paulirish.com/2011/requestanimationframe-for-smart-animating/
                // Launch the bound version so it can easily be swapped out for debugging.
                self.boundRunAnimationLoop();
```

The first comment is Greek. What are "rAF" and "render()"? I find no occurrences of them in Sim.js.

@samreid @jonathanolson perhaps you can clarify.

**Comment by samreid** [comment]
`rAF` is `request Animation Frame` and `render()` is the step that does the drawing.  Full details on this strategy are in the URL http://paulirish.com/2011/requestanimationframe-for-smart-animating/

**Comment by pixelzoom** [comment]
Comment changed from:

```js
// place the rAF *before* render() to assure as close to 60fps with the setTimeout fallback.
```

```js
// place the requestAnimationFrame *before* rendering to assure as close to 60fps with the setTimeout fallback.
```

Now why is this comment where it is?  The comment is on line 733, is called on line 785.  And I have yet to identify where "rendering" is in relation to the comment.

**Comment by samreid** [comment]
The main part of the recommendation is to do:

```js
requestAnimationFrame();
doWork();
```

rather than

```js
doWork();
requestAnimationFrame();
```

According to their explanation, it is so that a polyfill that uses setInterval will have behavior more similar to the real `requestAnimationFrame`.
