### ISSUE TITLE
Sim.activeProperty should be BooleanProperty

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#461]
@zepumph I have a real puzzle.  Try the following:

1. Run Beer's Law Lab/state wrapper => Observe that everything is working properly
2. In Sim.js, change `this.activeProperty = new Property(` to a `BooleanProperty` and remove the `phetioValueType`.
3. Run Beer's Law Lab/state wrapper => Observe `Assertion failed: invalid value: undefined`
4. Add a debugger to assert.js and investigate

The problem is that the activeProperty is giving state as `false` but it should be giving state as `{value:false}`, see Property.toStateObject.  Can you help figure this out?

**Comment by zepumph** [comment]
It's laughable how I just tracked the getState method fully from the sim to the wrapper, only to find this line in the state wrapper:

```js
        if ( state ) {
          state[ sim.camelCaseName + '.sim.activeProperty' ] = false;
        }
```

**Comment by zepumph** [comment]
Back to you @samreid for review. Is this what you were thinking?

**Comment by samreid** [comment]
This is looking better, but I'm still worried about `state[ sim.camelCaseName + '.sim.activeProperty' ] = { value: false };` . Is there a way to leverage PropertyIO here to guarantee they never get out of sync again?

**Comment by samreid** [comment]
Or should we omit this value from the state and try to control it through an explicit API call?

**Comment by zepumph** [comment]
Yeah what if we just set it once at the  beginning, and then removed the activeProperty tandem from the state before sending it downstream to be set.

**Comment by samreid** [comment]
This issue is all set, closing.  I created new issue https://github.com/phetsims/phet-io-wrappers/issues/32
