### ISSUE TITLE
Implement keyboard nav for the navigation bar

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#462]
From https://github.com/phetsims/a11y-research/issues/45, here is a link to the mockup:

http://htmlpreview.github.io/?https://github.com/phetsims/a11y-research/blob/master/html-sketches/sim-screens/template-sim-screen/01-screen-template.html

https://github.com/phetsims/a11y-research/blob/master/html-sketches/sim-screens/template-sim-screen/01-screen-template.html

**Comment by zepumph** [comment]
I added keyboard nav bigly today to the navigation bar. @terracoda how does this look to you? I like to look at RPAL for a good example since it already has a lot of keyboard nav added. See phettest (phettest.colorado.edu/reactants-products-and-leftovers/reactants-products-and-leftovers-a11y-view.html?brand=phet) or on the dev server (https://www.colorado.edu/physics/phet/dev/html/reactants-products-and-leftovers/1.2.0-dev.3/reactants-products-and-leftovers-a11y-view.html)

Try it out with other sims too!

**Comment by terracoda** [comment]
@zepumph, this is looking really good. I do however get leftover ghost focus highlights when going from home screen to sim screen and from sim screen to home screen. I also noticed that in the radio group, focus should go to the selected item in the group, not the first or last item depending on direction of tabbing. See screen shots below with visual examples. They happen in FF and Safari.

**Focus Ghost from Home Screen on Sim Screen**
<img width="593" alt="screen shot 2017-11-07 at 21 48 07" src="https://user-images.githubusercontent.com/1902116/32526944-89aa16de-c406-11e7-98a2-1fb85b9e02f8.png">

**Focus Ghost on Home Screen from Sim Screen Navbar**
<img width="590" alt="screen shot 2017-11-07 at 21 47 48" src="https://user-images.githubusercontent.com/1902116/32526954-94b9420c-c406-11e7-9176-c50d3f64c3d9.png">

**Incorrect focus in the radio group**
In this example, I am tabbing backward to the radio group with Shift Tab. The focus highlight should go on the radio which is actually selected, not first or last radio in the group.
![screen shot 2017-11-07 at 21 57 55](https://user-images.githubusercontent.com/1902116/32526991-bdbb0140-c406-11e7-9f50-175be07986c9.png)

**Comment by jessegreenberg** [comment]
In phetsims/balloons-and-static-electricity @terracoda mentioned

> For single screen sims like Balloons and Static Electricity, the label should not include a reference to Sim Screens, and just be "Sim Resources and Tools".

@zepumph could you please work on that adjustment as part of this issue?

**Comment by zepumph** [comment]
Right, thanks for the reminder.

**Comment by zepumph** [comment]
@terracoda BASE and other single screen sims should now be restored.

**Comment by zepumph** [comment]
Home button blur is fixed above, Weird home screen focus bug is to be addressed in https://github.com/phetsims/chipper/issues/622 and the radio button issue is in https://github.com/phetsims/sun/issues/316

@terracoda until chipper 622 is resolved, please try not to use firefox + a11y view + multiscreen simulations. You can use firefox + multiscreen sims directly still. Anything else for this issue @terracoda?

**Comment by terracoda** [comment]
phetsims/chipper#622 is resolved.

@jessegreenberg, can I close this issue. It looks like @zepumph implemented my mockups.

**Comment by zepumph** [comment]
Closing, bugs will be addressed in their own issues
