### ISSUE TITLE
Use FocusHighlightPath to get consistent dilation of bounds

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#464]
@jessegreenberg I just added the static method `FocusHighlightPath.getDilationCoefficient()` so that you can get the appropriate dilation based on the size of the node. Could you please implement that here if you think it is appropriate?

Here is what it looks like now:
`      focusHighlight: Shape.bounds( closeButtonShape.getBounds().dilated( 10 ) )`

**Comment by jessegreenberg** [comment]
@zepumph `getDilationCoefficient` is really great.  I used it in `KeyboardHelpDialog` for the highlight dilation in the example you mentioned. I reviewed the new function too, which has great documentation. Thanks for this! Closing.
