### ISSUE TITLE
Round Two: PhET-iO Design meeting for joist + a11y

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#465]
Once #445 is wrapped up, we will want another design meeting to confirm that everything is looking stable, and to ask a few more questions. Here is a list of stuff that comes up so we don't forget.
- [ ]  phetioIDIndices included in the state of Focus: https://github.com/phetsims/joist/issues/445#issuecomment-345109113

**Comment by samreid** [comment]
@zepumph can you please report on the status of this issue?

**Comment by zepumph** [comment]
> phetioIDIndices included in the state of Focus: #445 (comment)

This has had iteraction multiple times since 2017.


I think we can close this issue. Sims have been published with the current PhET-iO design.
