### ISSUE TITLE
"Error: Impossible set state" with  AboutDialog

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#467]
Occurs in state wrapper when opening the aboutDialog

```
SimIFrameAPI Invocation Error: Error: Impossible set state:
chains.navigationBar.phetButton.phetMenu.aboutDialog.link1
chains.navigationBar.phetButton.phetMenu.aboutDialog.link2
chains.navigationBar.phetButton.phetMenu.aboutDialog.link3
chains.navigationBar.phetButton.phetMenu.aboutDialog
chains.navigationBar.phetButton.phetMenu.aboutDialog.closeButton
```

This has to do with our recent addition of instrumenting the aboutDialog. The about dialog should be removed from the state, and so should the barrierRectangle.

**Comment by zepumph** [comment]
excluding from phet-io state did the trick. In this commit I excluded the AboutDialog, it's children, and the barrierRectange. Assigning to @samreid to confirm that this is the best strategy for phetioState. In the state wrapper, nothing will change in the downstream sim when interacting with the phetMenu/AboutDialog.

**Comment by zepumph** [comment]
Bayes was pretty broken until this commit.

**Comment by samreid** [comment]
Yes, excluding from state seems best, closing.
