### ISSUE TITLE
make Home Screen gracefully handle larger numbers of screens 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#470]
With the addition of the Mystery screen (see https://github.com/phetsims/equality-explorer/issues/34) Equality Explorer is likely to be PhET's first 5-screen sim.   After adding a skeleton for this 5th screen, I noticed that the home screen then adds *more* space to the left and right of the home screen icons, shrinking them further than necessary.  Compare screenshots below for 4-screen and 5-screen sims.

I looked at the implementation of `HomeScreenView`, and couldn't immediately determine how to fix this.  I'm guessing that someone decided that a sim would never have > 4 screens, and therefore didn't make the implementation scale gracefully/consistently.  Not surprisingly, `HomeScreenView` doesn't make use of scenery's `maxWidth` (since it's a newer feature), but that would be a good place to start.  And `HomeScreenView` has several magic numbers - `60`, `33`, `170` - that should be derived from `LAYOUT_BOUNDS`.   

If we're going to gracefully handle larger numbers of screens, then we might also look at what it would take to have more than 1 row of icons on the home screen.

I don't have time for this diversion right now. But it may need to be addressed before Equality Explorer 1.0.0 is published.  Assigning to @ariel-phet to prioritize and assign.

**Comment by pixelzoom** [comment]
![screenshot_473](https://user-images.githubusercontent.com/3046552/35583816-59a4add2-05b0-11e8-9e11-a5b892e4dc77.png)

![screenshot_474](https://user-images.githubusercontent.com/3046552/35583819-5c5cea30-05b0-11e8-8b79-a517fc3cfaa1.png)

**Comment by pixelzoom** [comment]
Equality Explorer actually has a 6th screen that I use for debugging/testing.  It's enabled with the `?xy` query parameter.  See screenshot below.  This demonstrates that as the number of screens increases, the left/right margins increase.

![screenshot_476](https://user-images.githubusercontent.com/3046552/35584570-9cf8e632-05b2-11e8-8080-41c9f0f1fdea.png)

**Comment by pixelzoom** [comment]
I started increasing the number of screens to see how gracefully the home screen handles things.  

Things look sane up to 7 screens:

![screenshot_478](https://user-images.githubusercontent.com/3046552/35584699-06ec33a0-05b3-11e8-8361-5e281e805255.png)

At 8 screens, things go terribly wrong:

![screenshot_479](https://user-images.githubusercontent.com/3046552/35584737-1f19d8ce-05b3-11e8-91d3-fb116e8bcd41.png)

There's no reason for this behavior, things should just scale gracefully.

**Comment by ariel-phet** [comment]
@jonathanolson said this would only be 4'ish hours of work plus time for testing. Assigning at medium priority.

@pixelzoom feel free to ping me on this issue in a couple of weeks if it is starting to become pressing. Probably won't be worked on for about 2 weeks.

**Comment by pixelzoom** [comment]
@ariel-phet ping.  Equality Explorer is definitely a 5-screen sim, and this needs to be a addressed before publishing.

**Comment by ariel-phet** [comment]
I have asked @jonathanolson to put this work at the top of his ToDo list for the start of April.

**Comment by pixelzoom** [comment]
It looks like there's been an attempt to keep the size of the selected icon constant, regardless of the number of screens.  If that's the case... Then I would think that the size of the unselected icons and the amount of space between them would be scaled to fit the remaining horizontal space.

**Comment by ariel-phet** [comment]
@jonathanolson I think right now, up to 5 screen icons, the selected icon should stay the same size as now, and the other icons should shrink as needed.

After 5 screens (I will push very hard for PhET to never have more than 5 screens in a sim...) lets go with the plan you suggest in the preceding comment (things just scale down).

**Comment by ariel-phet** [comment]
@jonathanolson, yes all look good in previous comment

**Comment by pixelzoom** [comment]
Labeling as "block-production".  This issue must be closed before Equality Explorer can start RC testing, scheduled to begin 7/11/18.

**Comment by jonathanolson** [comment]
Simplified above, closing.

**Comment by pixelzoom** [comment]
Reopening.  There's a problem here, reported by @phet-steele during RC testing of Equality Explorer (https://github.com/phetsims/QA/issues/144).  

With `?stringTest=long`, there is vertical displacement of the home screen icons as you select them.  For example, run https://phet-dev.colorado.edu/html/equality-explorer/1.0.0-rc.1/phet/equality-explorer_en_phet.html?stringTest=double.  Stay on the home screen and switch between the screen icons.  You'll see the unselected icons move up and down.  

This was not a problem prior to the changes made in this issue. For example, https://bayes.colorado.edu/dev/html/equality-explorer/1.0.0-dev.108/phet/equality-explorer_en_phet.html?stringTest=double.

This will need to be patched in the joist dependency for the 1.0 release branches of equality-explorer, equality-explorer-basics, and equality-explorer-two-variables. 

Assigning to @jonathanolson with top priority.

**Comment by pixelzoom** [comment]
Created https://github.com/phetsims/equality-explorer/issues/143 to track in EqEx RC testing, and to see if this needs to be addressed for 1.0 release.

**Comment by jonathanolson** [comment]
Implemented the change in alignment above. It may slightly change the vertical position of the icons on some sims. @ariel-phet can you check to make sure things still look ok?

**Comment by ariel-phet** [comment]
@jonathanolson I tried this out on master with `?stringTest=double` and without for the following sims

Equality Explorer (5 screens)
Function Builder (4 screens)
Masses and Spring (4 screens)
Build an Atom (3 screens)
Beer's Law (2 screens)

All looks good to me.

Tagging @pixelzoom to see if he is OK with closing and if he wants to try to patch EqEx before publishing (not necessary, but his call if it seems simple)

**Comment by pixelzoom** [comment]
If I patch, it's going to require another RC cycle.  I can't do that and get the sim published tomorrow 7/18.  Which means that I will not meet KP's request of publishing before I leave for vacation - publication will push to after August 5.  @ariel-phet Your call.

**Comment by pixelzoom** [comment]
If I patch, it's going to require another RC cycle.  I can't do that and get the sim published tomorrow 7/18.  Which means that I will not meet KP's request of publishing before I leave for vacation - publication will push to after August 5.  That will be personally very disappointing. But @ariel-phet your call.  And @amanda-phet FYI.

**Comment by pixelzoom** [comment]
On second thought, I guess I do have a strong opinion :)   While this patch looks very simple, I don't want to deal with it for EqEx 1.0 sims.  Since this fix didn't get tested properly the first time, I would feel the need to test, regardless of the fact that @ariel-phet tested (no offense).  I do not have the time to do that, and, at this late date, I don't want to do anything to jeopardize publishing EqEx sims tomorrow, no matter how simple it is. QA and I have worked too hard over the past week, and it would be very disappointing not to meet KP's request of publishing before I leave for vacation.  So I recommend that we proceed with publishing the 3 EqEx sims, and have @jonathanolson patch this sometime shortly after.

**Comment by ariel-phet** [comment]
@pixelzoom sounds good, proceed with that plan

**Comment by ariel-phet** [comment]
Let's discuss at dev meeting briefly....RC for masses and springs coming up, can this be patched in?

**Comment by samreid** [comment]
@jonathanolson said this can be patched in before M&S RC.

**Comment by jonathanolson** [comment]
@Denz1994 I applied the patch to masses-and-springs' 1.0 branch.

**Comment by Denz1994** [comment]
Thanks for the patch @jonathanolson. This is resolved in masses-and-springs master branch aswell. Closing.
