### ISSUE TITLE
branch: accessible-home

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#471]
Identified by `print-branches.sh`. @jessegreenberg please describe.

**Comment by jessegreenberg** [comment]
This branch is no longer relevant, it was used to explore adding a11y to the home screen before more general support for a11y was added. Branch has been deleted.

**Comment by zepumph** [comment]
Should be re-deleted as part of phetsims/special-ops#198

**Comment by zepumph** [comment]
Deleted
