### ISSUE TITLE
LoL harness errors on iOS 9.3.5

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/joist#474]
Hey @samreid, I can't get

https://developers.legendsoflearning.com/public-harness/index.html

to load on on Tycho (iOS 9.3.5). Do you have any idea why this is the case? Do we care about this? Should we notify LoL?

The errors:

![screen shot 2018-03-19 at 3 34 25 pm](https://user-images.githubusercontent.com/31285590/37624000-40354e72-2b8c-11e8-9303-0e1ce4a0ef74.png)

According to this https://github.com/rails/webpacker/issues/974#issuecomment-340024112, "Versions 5.1 - 9.1 do not support using const in strict mode." Tycho has Safari 9.0.

I've done some Googling for the second issue, and I don't know what I'm reading.

**Comment by samreid** [comment]
My High Sierra seems incapable of running Web Inspector for iOS 9.3.5, possibly the same as reported in https://apple.stackexchange.com/questions/305954/safari-remote-debugger-on-ios-9-3-5-not-working-in-high-sierra

It could be that Legends of Learning is trying to use a HTML feature that is not present in Safari for iOS 9.3.5.  It looks like they are using ES6 (with const), but perhaps this is only for their developer site--they may still support clients running iPad2.  I'll check if they have "supported platforms" docs.

**Comment by samreid** [comment]
According to https://www.legendsoflearning.com/teachers/faq/

> Legends of Learning supports Chromebooks, recent iPads, iPad Air 4, and iPad Pros. Laptop/desktop computers will also work. Android tablets and smartphones are not officially supported.

I'm inclined to close this issue, but perhaps we should run it past @ariel-phet so he is aware.  @ariel-phet go ahead and close after reading, unless you recommend further work.

**Comment by lmulhall-phet** [comment]
OK, thanks @samreid. I'll edit the testing matrix so that we don't do LoL testing for iOS versions < "recent" if @ariel-phet thinks this makes sense.

**Comment by lmulhall-phet** [comment]
@phet-steele can you edit the template for testing matricies?

**Comment by ariel-phet** [comment]
@lmulhall-phet @samreid sounds good. We still need iOS 9.3.5 obviously for our own testing, but since LoL does not support iPad2's seems perfectly reasonable to drop that testing for us.

**Comment by phet-steele** [comment]
Dropped iOS 9.3.5 + LoL in testing matrix.
