### ISSUE TITLE
KeyboardHelpButton does not need to know about Sim

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#475]
From https://github.com/phetsims/joist/issues/374#issuecomment-376287416:

> If KeyboardHelpButton is already being passed the full {Sim}, can it pull out sim.lookAndFeel.navigationBarFillProperty on its own?
> > Done.

This is an example of violating this item from the [code review checklist](https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md):

>  - [ ] Is there any unnecessary coupling? (e.g., by passing large objects to constructors, or exposing unnecessary properties/functions)

`Sim` is a _huge_ object, and there's no way that `KeyboardHelpButton` should know about it.   In fact, it only needs to know about `keyboardHelpNode` and `showHomeScreenProperty`.   So those things should be `KeyboardHelpButton` constructor parameters, not `{Sim} sim`.

**Comment by pixelzoom** [comment]
While you're in there... `KeyboardHelpButton` is missing JSdoc for its constructor.

**Comment by pixelzoom** [comment]
KeyboardHelpButton constructor signature should look like this:

```js
/**
 * @param {Node} keyboardHelpNode - describe me
 * @param {Property.<boolean>} showHomeScreenProperty
 * @param {Property.<Color|string>} backgroundFillProperty
 * @param {Tandem} tandem
 * @constructor
 */
 function KeyboardHelpButton( keyboardHelpNode, showHomeScreenProperty, backgroundFillProperty, tandem )
```

**Comment by jessegreenberg** [comment]
Sim is no longer passed to KeyboardHelpButton, and after other changes for #374 the JSDoc looks like

```js
  /**
   * @param {Node} keyboardHelpNode - content for the KeyboardHelpDialog
   * @param {LookAndFeel} simLookAndFeel - state and colors of sim/NavigationBar to set color for icon of this button
   * @param {Tandem} tandem
   * @constructor
   */
```
@pixelzoom does this look OK?
