### ISSUE TITLE
Dialog lacks options for adding listeners to close button and boundary rectangle

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#478]
There's definitely no way to add a listener to the close button.  You're stuck with this:

```js
function() {
  self.hide();
}
```

If there's a way to listen for the clicks to the boundary rectangle (outside the Dialog), I can't find it.

**Comment by pixelzoom** [comment]
`closeButtonListener` option added in above commit.

**Comment by pixelzoom** [comment]
Question to Slack developer channel:

> Chris Malley [6:01 PM]
Anyone know how I can get a callback when a Dialog is closed by clicking outside the Dialog?  Looks like Make A Ten worked around this by creating it’s own barrier rectangle (MakeATenGameScreenView, line 148).

**Comment by pixelzoom** [comment]
Wow is this convoluted... Dialog `show` calls `window.phet.joist.sim.showPopup( this, this.isModal );`  If `isModal`, then the Dialog gets pushed onto Sims' `{ObservableArray} this.modalNodeStack`.   Sim has an instance of `BarrierRectangle` in `this.barrierRectangle`.  When `modalStack` is not empty, the BarrierRectangle is show.   When you click on the BarrierRectangle, whatever is on the top of `modalStack` has its `hide` method called (and it had better have a `hide` method, or boom, because there's no checking.)   And finally.... There's no callback to tell the Dialog that it was hidden by clicking on the BarrierRectangle.   So I guess the (bad) assumption is that clients will override Dialog `hide` and handle everything there.

**Comment by pixelzoom** [comment]
No reply to my question about this on Slack, so labeling for developer meeting discussion.   The question is "How do I know if a Dialog was dismissed by clicking in the barrier rectangle?"

**Comment by jonathanolson** [comment]
> "How do I know if a Dialog was dismissed by clicking in the barrier rectangle?"

Based on your description (and a quick review of the code), currently you can't tell. Presumably that can be changed.

> Looks like Make A Ten worked around this by creating it’s own barrier rectangle (MakeATenGameScreenView, line 148).

It also didn't use Dialog.

**Comment by pixelzoom** [comment]
Maybe I'll just punt on this, create my own Dialog subtype, and override `hide` so that it also calls `dispose`.  Doesn't feel like a "solution", feels like yet-another Dialog workaround that will need to be undone in the future.

**Comment by pixelzoom** [comment]
4/5/18 dev meeting:
Punt on a real solution for now, use whatever workaround I can find.  Revisit when Dialog is revisited.

**Comment by pixelzoom** [comment]
I'm going to add option `hideCallback`, which is called just before the dialog is hidden.

**Comment by pixelzoom** [comment]
The 3 callbacks that I added (`closeButtonListener`, `showCallback` and `hideCallback`) give me what I need to proceed with Equality Explorer.  Closing.
