### ISSUE TITLE
Rename Screen.activeProperty to Screen.screenActiveProperty

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#479]
Although this may be a bit redundant, @samreid and I think it is best to make sure that this property is definitively distinguished with `Sim.activeProperty` which isn't read only, and is very important, especially in a phet-io context. @jbphet is the author of this property, so I want to tag him so he is aware. Nothing will break in the sonification wrapper after this change until we update versions, but it is good for all parties to be aware.

**Comment by zepumph** [comment]
@samreid please review. Although it is redundant, I like it.

**Comment by samreid** [comment]
I skimmed the change set, reviewed appearance in Studio and checked for other potential missed cases of `activeProperty` in joist, all seems well, thanks!

**Comment by zepumph** [comment]
this needs to be reverted because of the consensus in https://github.com/phetsims/tasks/issues/929.

Instead, @samreid had the idea to detect naming collisions and add more of the phetioID in the display name. I'll take a look.

**Comment by zepumph** [comment]
Reverted above.

**Comment by zepumph** [comment]
>Instead, @samreid had the idea to detect naming collisions and add more of the phetioID in the display name. I'll take a look.

https://github.com/phetsims/phet-io-wrappers/issues/21#issuecomment-391078810 could cover this, but even so that problem doesn't belong in this issue, adding it to phetsims/faradays-law#107.

**Comment by zepumph** [comment]
Closing

**Comment by pixelzoom** [comment]
Note that this change broke Equality Explorer, see https://github.com/phetsims/equality-explorer/issues/120.  If you're going to change the name of something that's public, please change usages.

**Comment by zepumph** [comment]
Sorry about that, and thank you for taking care of it.
