### ISSUE TITLE
PhetButton has lost its highlight on mouse hover

### ISSUE THREAD

**Issue by phet-steele** [phetsims/joist#482]
Assigning to @zepumph and @jessegreenberg since they "volunteered".

The PhetButton no longer "highlights" on mouse hover. It should behave similar to the screen icon buttons where it would get two vertical lines on either side of it.

I'm seeing this issue on master (all sims) and some recent builds, notably phetsims/QA/issues/108 (RIAW 1.5.0-rc.1).

![navbarhighlight](https://user-images.githubusercontent.com/5863899/38822702-7b06fa06-4161-11e8-9965-3cb8998047c2.gif)

**Comment by phet-steele** [comment]
RIAW 1.5.0-rc.1 was built March 9th.
https://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.5.0-rc.1/phet/resistance-in-a-wire_all_phet.html

**Comment by phet-steele** [comment]
Sim that was tested before RIAW that didn't have this issue was MAS, built February 27. Issue was likely introduced between those two dates.
https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.81/phet/masses-and-springs_en_phet.html

**Comment by samreid** [comment]
Most likely introduced in https://github.com/phetsims/sun/issues/173 .  The new values are 

```js
    // button is just sitting there, doing nothing
    IDLE: 'IDLE',

    // a pointer is over the button, but not pressing it
    OVER: 'OVER',

    // the button is pressed, generally because the user has clicked on it or touched it
    PRESSED: 'PRESSED',

    // the button is disabled
    DISABLED: 'DISABLED',

    // the button is disabled, but was already pressed when that happened, so it is also pressed
    DISABLED_PRESSED: 'DISABLED_PRESSED'
```

However, JOIST is checking for 

```js
    // Update the highlights based on whether the button is highlighted and whether it is against a light or dark background.
    Property.multilink( [ interactionStateProperty, navigationBarFillProperty ], function( interactionState, navigationBarFill ) {
      console.log(interactionState);
      var useDarkenHighlight = navigationBarFill !== 'black';
      brightenHighlight.visible = !useDarkenHighlight && ( interactionState === 'over' || interactionState === 'pressed' );
      darkenHighlight.visible = useDarkenHighlight && ( interactionState === 'over' || interactionState === 'pressed' );
    } );
```

@jbphet can you take a look?

**Comment by jbphet** [comment]
Should now be fixed.  The commits were tracked against the issues linked above, but here they are for easy reference if needed:

+ https://github.com/phetsims/joist/commit/b1a7f578f461add4bbf3ef244d8dcc424fa10479
+ https://github.com/phetsims/joist/commit/0dac2eca3f65b86b92b4ca4925d48cc346972577

The other issue is slated for code inspection, so I'm assigning this one back to @phet-steele for verification on master and, if the behavior looks correct, closure.

**Comment by phet-steele** [comment]
Things have been looking great, thanks.
