### ISSUE TITLE
[LoL] Error in ColorProfile.js

### ISSUE THREAD

**Issue by phet-steele** [phetsims/joist#484]
Not sure what started causing this, but running sims from master that use `ColorProfile.js` coupled with `?legendsOfLearning` is throwing an error. Also not sure the error is the true problem, but here it is:

```
Uncaught SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at ColorProfile.js?bust=1524082393635:113
```

Note that running in the LoL harness is not needed to throw this error. Seen on master (2 PM 4/18) macOS 10.13.4 Chrome.

**Comment by phet-steele** [comment]
An example if you want to run off phettest like I was: http://phettest.colorado.edu/area-model-introduction/area-model-introduction_en.html?ea&brand=phet&legendsOfLearning

**Comment by jonathanolson** [comment]
Should be fixed in the above commit, can you verify?

**Comment by phet-steele** [comment]
Good to go.
