### ISSUE TITLE
Homebutton won't click with keyboard

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#485]
Currently pressing space or enter on `HomeButton.js` will only blur the button, not click it. Tagging @jessegreenberg because we both saw this today in meetings.

**Comment by zepumph** [comment]
Weird logic, if you add a debugger to JoistButton's click listener, then it will work after you play through the debugger.

**Comment by zepumph** [comment]
I removed the blur event that I added to the `HomeButton` and it fixed this issue. I look through the project, and the blur event isn't really used in other places, especially no buttons. @jessegreenberg please review.

**Comment by jessegreenberg** [comment]
Thanks @zepumph, looks good and I verified that this fixed the problem. Ill bet the blur was necessary prior to our work in `AccessibleInstance.updateVisibility`. Closing.
