### ISSUE TITLE
various issues in KeyboardHelpButton and KeyboardHelpDialog

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#487]
Noted while working on https://github.com/phetsims/joist/issues/486.

KeyboardHelpButton and KeyboardHelpDialog have many small issues that need to be addressed.  I'll put TODO items in the code that reference this issue.

**Comment by pixelzoom** [comment]
I've done as much as I can here.  Over to @jessegreenberg and @zepumph.

**Comment by zepumph** [comment]
@pixelzoom I don't see any more todos. Tandem as a required param vs option was promoted to #489. I think that is all for this issue.
