### ISSUE TITLE
Should tandem be in options or required param?

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#489]
For joist, @samreid and I have implemented tandems as required parameters. @pixelzoom in https://github.com/phetsims/joist/issues/487 pointed out that he wished that they were in options. I'm not just I see the benefit in moving these to options in joist. @pixelzoom what were your concerns?

**Comment by pixelzoom** [comment]
(4) Having tandem as a required parameter makes it unnecessarily complicated to test in the browser console.  E.g. the case I ran into while debugging/testing yesterday:

`new phet.joist.KeyboardHelpDialog( ...., phet.tandem.Tandem.optional ).show()`

vs. 

`new phet.joist.KeyboardHelpDialog( .... ).show()`

_All_ code should be testable without tandems.

**Comment by samreid** [comment]
The description in https://github.com/phetsims/joist/issues/489#issuecomment-397467894 sounds great to me, should we capture it in the "how to instrument" documentation and close this issue?

**Comment by zepumph** [comment]
Handled as part of https://github.com/phetsims/phet-io/issues/1243. Closing
