### ISSUE TITLE
Should ScreenView have an h1 label?

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#491]
I stumbled across this today, but I'm unsure what the best protocol is. For multiscreen sims, so we want the screen name to be a large header in the PDOM? We havent needed this before, but on the home screen I see some shenanigans in RPAL:
![image](https://user-images.githubusercontent.com/6856943/39789268-494bdf14-52db-11e8-88a4-d42faa07def3.png)

I'm not sure if we want the "Home Screen" header at all, let along BEFORE the sim name. Let's discuss this.

**Comment by terracoda** [comment]
@zepumph, we do not want "Home Screen" at all on the home screen, just the name of the sim.

The current thinking on this is that the sim's h1 is the same for each screen. We may want to consider this more carefully, but my current thinking was that the sim is single page with different parts visible at different times.

The sim's name remains constant in the Sim Resources bar.

**Comment by terracoda** [comment]
Adding, one could consider each part having it's own h1, but we have not done this for the multi-screen sims to date.

**Comment by terracoda** [comment]
We discussed this issue a little yesterday, and we might need a combination of sim name and screen name in the h1, for example:
```html
<h1>Sandwiches Screen: Reactants, Products and Leftovers</h1>
<h1>Reactants, Products and Leftovers - Sandwiches Screen</h1>
<h1>Reactants, Products and Leftovers - Sandwiches</h1>
<h1>Sandwiches, Screen 1 for Reactants, Products and Leftovers</h1>
<h1>Reactants, Products and Leftovers - Screen 1: Sandwiches</h1>
```
Other possible arrangements, too. 
I like to put the most important or new information first.

**Comment by zepumph** [comment]
I'm happy to implement anything, just let me know what you would like the title for each screen to look like.

**Comment by terracoda** [comment]
I the latest thinking on this is here:
https://github.com/phetsims/joist/blob/master/doc/HomeScreen.md

Each screen should start with an H1, in my opinion.

**Comment by terracoda** [comment]
@zepumph, let me review this issue a little more carefully. It has been a while.

**Comment by terracoda** [comment]
@zepumph, you said: 

> let me know what you would like the title for each screen to look like.

Just want to be clear that we both know that the `title` element is different than the `h1` or `h1`'s as the case may be.

**Comment by jessegreenberg** [comment]
I think this can be closed after https://github.com/phetsims/joist/issues/679 and https://github.com/phetsims/ratio-and-proportion/issues/282, and I think there were other issues for HomeScreen description. @zepumph is that right?

**Comment by zepumph** [comment]
Yes Thanks.

**Comment by terracoda** [comment]
Also, the https://github.com/phetsims/joist/blob/master/doc/HomeScreen.md was updated a week or so ago to include the design for Ratio and Proportion.
