### ISSUE TITLE
BarrierRectangle and its sub-components should be marked as phetioReadOnly

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#495]
Before https://github.com/phetsims/energy-skate-park-basics/issues/411 can go to dev test, the BarrierRectangle and its sub-components should be marked as readOnly.  This became broken in https://github.com/phetsims/phet-io/issues/1326

**Comment by samreid** [comment]
Proposed fix pushed and ready for review.

**Comment by zepumph** [comment]
That looks good. I wonder how we should handle `phetioState` or other phetio options (high frequency). Do we just want to cherry pick out specific bubbling options?

**Comment by samreid** [comment]
I suspect that if a Node is marked as `phetioState: false` then its children should be too.  Other attributes don't seem like they should propagate (let me know if you disagree).  I'll propagate `phetioState` shortly.

**Comment by samreid** [comment]
Proposed fix pushed, please review.
