### ISSUE TITLE
Integrate global sound controls into sim framework

### ISSUE THREAD

**Issue by jbphet** [phetsims/joist#497]
There are two sound controls that need to be added into the sim framework, one for turning sound on and off for the sim, and another for choosing between "basic" and "enhanced" sounds.

The issues where this was previously discussed are:
+ https://github.com/phetsims/tambo/issues/11
+ https://github.com/phetsims/tambo/issues/12

The UI design is being finalized in:
+ https://github.com/phetsims/tambo/issues/19

In the 7/9/2018 sonification framework design meeting we decided that this should be committed to a branch on joist until the Equality Explorer release branch is created in order to minimize the risk of destabilizing core framework code.

**Comment by jbphet** [comment]
I committed some code for this but forgot to reference the issue, please see https://github.com/phetsims/joist/commit/4dd92fc5dc4965826cbfd90dfb40ee5b8cc9f75f.

**Comment by pixelzoom** [comment]
@jbphet said:
> ... we decided that this should be committed to a branch on joist until the Equality Explorer release branch is created in order to minimize the risk of destabilizing core framework code.

RCs are published for all EqEx sims, so you may proceed with merging into master.

**Comment by jbphet** [comment]
@samreid - since the Equality Explorer RC is out, please review the code on the sound-control branch and let me know what if anything needs to be done before merging it to master.  One exception: for now, please don't spend any time on `NavigationBarSoundToggleButton`, since we are looking at ways to reduce the amount of memory that it used.

**Comment by samreid** [comment]
In the preceding 3 commits (note these are for 3 repos), I added review comments for the proposed changes.  @jbphet please take a look?

**Comment by samreid** [comment]
Code review complete, everything is looking good or mentioned in outstanding issues (some will be created shortly).

**Comment by jbphet** [comment]
@samreid and I worked together on merging in the sound-control branch and taking the steps necessary to add TAMBO to the config file for all runnables.  The merge is completed, but I'm following up on a few loose ends, including whether the test-config files need to be updated.

**Comment by jbphet** [comment]
All of the `<sim-name>-config.js` have been updated to define TAMBO, and there are no failures occuring on continuous test related to this (there were when I first did this, but they have all been addressed).  I used the command `grunt generate-config` to update the config files, but apparently I should have used `grunt update`.  I went back and tried running `grunt update` in all the "active runnables", but all it did was change some CR LF formatting in the main HTML files, which I did not commit.

@jonathanolson has told me that this might leave the  `<sim-name>-config.js` files out of date.  I tried running `grunt generate-test-config`, but that ends up generating test-config files for everything, which isn't what we want.  @jonathanolson has been out sick and unable to consult on how to fix this, so I'm going to assign the issue to him and perhaps he can either help me sort it out and just fix it once he's back in action.

**Comment by jonathanolson** [comment]
I ran `grunt update` on every active-repo (`perennial/bin/for-each.sh active-repos grunt update` and committed the results (omitting interaction-dashboard).

@jbphet I believe the config files are now correct. Is there some place we should document how to update dependencies?

**Comment by jbphet** [comment]
Thanks for the fix.

> Is there some place we should document how to update dependencies?

Sure.  Maybe a new document in `phet-info/doc`?  The challenge will be remembering that it exists and using it when needed and keeping it updated, since adding a new dependency is a pretty rare event.  I would suggest creating it (it should be quite short, right?) then marking for dev meeting to see if people agree with the location and just to let the other devs know that it exists.

**Comment by jonathanolson** [comment]
Added phet-info/checklists/updating_metadata.md (fits as a checklist). Tagging for developer meeting to see if anything needs to change.

**Comment by jonathanolson** [comment]
https://github.com/phetsims/phet-info/blob/master/checklists/updating_metadata.md

**Comment by pixelzoom** [comment]
My task is to review https://github.com/phetsims/phet-info/blob/master/checklists/updating_metadata.md.
