### ISSUE TITLE
branch: sound-control

### ISSUE THREAD

**Issue by jbphet** [phetsims/joist#498]
The sound-control branch was created to develop the global sound controls without risking destabilization of the framework code.  This is necessary because the Equality Explorer simulation is quite close to creating a release candidate (RC) branch.  See https://github.com/phetsims/joist/issues/497.

**Comment by pixelzoom** [comment]
RCs are published for Equality Explorer, so you may proceed with merging to master.

**Comment by jbphet** [comment]
The sound-control branch has been merged into master and then deleted.  Closing.

**Comment by zepumph** [comment]
Should be re-deleted as part of phetsims/special-ops#198

**Comment by zepumph** [comment]
Deleted
