### ISSUE TITLE
Incorrect dispose in NavigationBarSoundToggleButton

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#501]
While investigating https://github.com/phetsims/tambo/issues/18 I noticed this code in NavigationBarSoundToggleButton.js

```js
    /**
     * To make eligible for garbage collection.
     * @public
     */
    dispose: function() {
      JoistButton.prototype.dispose && JoistButton.prototype.dispose.call( this );
    }
```

The way that prototypes and overrides works, this code is unnecessary.  Or perhaps we need to unlink some things, and that is yet to be completed?

**Comment by jbphet** [comment]
This was actually copied from `KeyboardHelpButton`, which was suggested as the template for this button.  I've removed the code from `NavigationBarSoundToggleButton`, back to you @samreid to decide if `KeyboardHelpButton` requires the same fix.

**Comment by samreid** [comment]
Reassigned to @jessegreenberg--were you planning to add more code to the dispose function, or can the dispose function be removed?

**Comment by jessegreenberg** [comment]
This can  be removed.

**Comment by jessegreenberg** [comment]
It has been removed from both KeyboardHelpButton and NavigationBarSoundToggleButton so this issue can be closed.
