### ISSUE TITLE
Loading sim on iOS Reading List shows sim before splash screen

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/joist#502]
When I try to load a simulation that has been added to the iOS "Reading List," the simulation will be shown prior to the splash screen.

Here's a video:

https://drive.google.com/file/d/1FHXqxf-s2CSK1Gl4VuH-Az3zO9uMvQy9/view?usp=sharing

Here's another video:

https://drive.google.com/file/d/1Twpx2mP3UFxT3oKhHT0SoqlNuEtrDmK9/view?usp=sharing

I have also seen the splash screen off center.

Also, notice how the panel on the left doesn't go away when something on the Reading List is clicked. The panel disappearing when something is clicked is the normal behavior.

Related to phetsims/masses-and-springs/issues/301.

@ariel-phet, please assign and prioritize.

(EDIT: Note to self: Check latest iOS.)

**Comment by samreid** [comment]
@ariel-phet asked @samreid to investigate this up to an hour.

**Comment by samreid** [comment]
On second thought, @ariel-phet wants to investigate and discuss further with QA.

**Comment by ariel-phet** [comment]
Discussed with @lmulhall-phet. This issue does not occur on latest iOS

So...
1. Issue does not occur on latest iOS
2. This issue, though distasteful, does not stop the sim from running
3. The reading list is a very rarely used feature for running our sims offline (and our app nicely solves the offline running issue).

Assigning to @KatieWoe so she is aware. @KatieWoe please close the issue once you have reviewed it.
