### ISSUE TITLE
branch: nav-bar-to-home-screen

### ISSUE THREAD

**Issue by chrisklus** [phetsims/joist#506]
This branch is to be used for the implementation of showing the nav bar on the home screen with only the PhET button and a11y buttons visible. See https://github.com/phetsims/joist/issues/503

**Comment by chrisklus** [comment]
I merged nav-bar-to-home-screen to master and deleted it.

**Comment by zepumph** [comment]
Should be re-deleted as part of phetsims/special-ops#198

**Comment by zepumph** [comment]
Deleted
