### ISSUE TITLE
Instrument the kabob menu image?

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#507]
While working on https://github.com/phetsims/scenery/issues/711#event-1755290785, I saw that we could potentially instrument the "kabob dots" in the button. This could be nice if someone wanted to disable the phetmenu, then there wouldn't be a visual cue to click on the logo. This is a small issue, since you can still disable the menu opening by setting the phetMenuButton to pickable false.

Here are a few pictures of toggling the dots' visibility.
![image](https://user-images.githubusercontent.com/6856943/43283995-f23568ce-90c6-11e8-9fb4-e050ce15e8a8.png)
![image](https://user-images.githubusercontent.com/6856943/43284000-fc379bd0-90c6-11e8-80a2-9f797b79978d.png)

@samreid do you think this is a good idea?

**Comment by samreid** [comment]
I agree it would be best for the kabob dots not to show when the button isn't pickable.  Maybe we can/should tie them together in joist?  So that if the phet menu button becomes unpickable the dots automatically disappear?

**Comment by zepumph** [comment]
Great idea! I implement it above. I made it so that `pickable = null` will still show the dots, since the menu is still usable when `pickable = null`.

![image](https://user-images.githubusercontent.com/6856943/43334458-0a5fb07c-917a-11e8-8677-fb4e7d3b4e7d.png)
![image](https://user-images.githubusercontent.com/6856943/43334466-0c602dfc-917a-11e8-8646-496bb7acdde5.png)

@samreid do you think we need to pass this off to a designer to sign off on? I feel like it is good, but we may want to have someone double check it.
