### ISSUE TITLE
Update the layout of the PhET-iO button when the kabob is hidden

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#508]
When the kabob is hidden (for PhET-iO), the PhET-iO button has asymmetric margins.  See https://github.com/phetsims/joist/issues/507 for context.  I do not know how many clients want to make the PhET-iO button unpickable.  @ariel-phet should we investigate adjusting the layout when the kabob is hidden?

**Comment by ariel-phet** [comment]
@samreid I do not think we should investigate. The negative space to the right, although a tad imbalanced with the negative space on the left of the sim title, does not look horrible. Considering the complexity, and this really being only a minor aesthetic concern for a feature that may not be used too often, I do not think it is worth the effort.

Assigning back to you to close or defer.

**Comment by samreid** [comment]
Sounds great, closing.
