### ISSUE TITLE
Convert SceneSummary to new structure

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#509]
In https://github.com/phetsims/a11y-research/issues/94 @terracoda created the structure for a simulation and made `HomeScreen.md` in this repo. One large change from how we were doing things is that we no longer will have a "Scene Summary" h2. This issue is to implement that change. 

In terms of implementation, I think that we will want to do most of the work in `ScreenView.js`. Now that the independent a11y tree has been implemented, I want to add a member to `ScreenView` perhaps called `sceneOverview` (to avoid confusion that this is not the "scene summary" h2), which will be a node that holds the description located directly under the h1 sim heading. The var name is just an implementation detail though, and I don't have a strong preference.

Then in the parent type we can add the first sentence like "{{Friction}} is an interactive sim. It changes as you play with it." From there the suptype can add children as they see fit for it, and the order in the PDOM will be as expected.

**Comment by zepumph** [comment]
Tagging @jessegreenberg so he is aware of how I'm planning to affect joist code.

**Comment by zepumph** [comment]
@jessegreenberg please review the above commits before I continue so that we make sure that things are ok before proceeding. Marking as a high priority because we want to move friction along before I go on vacation.

**Comment by jessegreenberg** [comment]
@zepumph would it be possible for what has been done so far to be implemented in Screen.js? This would address some challenges listed in the TODOs you added in https://github.com/phetsims/joist/commit/72625d0918ebbb69d95fd037b3fc2aa311d6aa92, and could make the `multiscreen` option unnecessary.

Another observation, it looks like the usage of "Screen" for a11y and other usages throughout the project have aligned now, based on descriptions in HomeScreen.md. Maybe we should go through and change `scene` prefixes to `screen` no in variables and string keys?

**Comment by zepumph** [comment]
Really great feedback, and I will go ahead and look into the implementation in `Screen.js` instead. 

As for renaming, that seems like a chip away issue that I will not be able to dive into before my vacation. Would you mind making an issue for that @jessegreenberg?

**Comment by zepumph** [comment]
The above commit simplified quite a bit. Thank you @jessegreenberg for the recommendation. Now there are a few other concerns.

Since this node is created in `initializeView`, we don't have access to it in the `FrictionScreenView.js` subtype constructor. So notice I factored the overview content creation/setting to a method that is called in initalizeView. I can foresee this being constraining at somepoint as we increase complexity.

Another way to do this, would be to create the node in the constructor and don't fill the strings we need the simName and multiscreen option for. Then we can retroactively fix it in initializeView, with this sort of pseudo code:

```
this._view.screenOverviewA11yNode.setIntroScreenString( simName, numberOfScreens);
```

Then we wouldn't need an entirely new pattern for setting a11y content to the screenOverview, which I could foresee us getting pushback for anyways.

I'm going to give this a try. It will require us creating a new joist type: ScreenOverviewA11yNode which can handle setting it's content outside of the constructor, like with the `setIntroScreenString` method mentioned above.

**Comment by zepumph** [comment]
After talking with @jessegreenberg, and also @ariel-phet briefly, we have decided to go with the following, (hopefully) future proof solution.

* Create a type in scenery-phet called `ScreenSummaryNode` (to eventually replace SceneSummaryNode)
* Move logic out of `Screen.js` and into that type.
* create a method on that node that knows how set the intro string given the name and number of screens. This method will be called from initializeView to customize the string appropriately.
* create this node in ScreenView.js and make it a protected member called `this.screenSummaryNode`. 
* This Node can then be accessed from any subtype to add the summary content needed for the screen in the PDOM.

Thanks for the help @jessegreenberg.

**Comment by pixelzoom** [comment]
This issue looks like it's related to https://github.com/phetsims/scenery-phet/issues/393, "Replace SceneSummaryNode with ScreenSummaryNode".

**Comment by zepumph** [comment]
It is indeed. This issue is for implementation of the new strategy, and that other issue is to convert usages. Thanks for the link.

**Comment by jessegreenberg** [comment]
This looks good @zepumph, thanks. I reviewed changes and tested with single and multi screen sims.  Closing, we will continue in https://github.com/phetsims/scenery-phet/issues/393.
