### ISSUE TITLE
add "Sound Design" section to credits

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#512]
... needed for the sonification effort.

**Comment by pixelzoom** [comment]
Done. Tested in a sim with and without "Sound Design" credits. Here's what it looked like in Graphing Quadratics with "Sound Design" credits:

![screenshot_722](https://user-images.githubusercontent.com/3046552/44541396-0822c800-a6c7-11e8-9d5f-c26305f5ac71.png)

Note that I used the old-style pattern for the new 'credits.soundDesign' string: `"Sound Design: {0}"`.  Our policy is to use new-style patterns (i.e. `"Sound Design: {{credit}}`), but in this case it seems more important to remain consistent with the other 7 strings related to the credits (see strings with "credit." key prefix).

@Denz1994 randomly selected to review.

**Comment by Denz1994** [comment]
Considering the other 7 strings mentioned above use the old format, the above commit follows the pattern for the other credit object fields. I was able to successfully to create a sound design field in Masses-and-Springs. 
![image](https://user-images.githubusercontent.com/13894380/45040710-9a668c80-b034-11e8-8bb1-b75c4e0585f1.png)

I did remove one unused require statement in CreditNode.js. I will make an attempt to refactor the other 7 strings to follow our new string policy in a new issue. Assigning to @pixelzoom to close this issue.

**Comment by pixelzoom** [comment]
@Denz1994 said:
> I did remove one unused require statement in CreditNode.js.

For the record, this used require statement was dead code (commented out) introduced by @zepumph in https://github.com/phetsims/joist/commit/e3c3c82fbc5102524cddef4adb5a007ffc285a64.

Closing.
