### ISSUE TITLE
Convert MenuItem to PressListener

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#517]
From https://github.com/phetsims/scenery/issues/719#issuecomment-417509785, I think this will help to solve an issue we are getting for a11y. @jonathanolson does this seem like something that is reasonable to do? If you sign off I can implement. 

Let me know if you want more context. Tagging @jessegreenberg too because he was involved in finding this too.

**Comment by jonathanolson** [comment]
Seems reasonable to investigate.

**Comment by zepumph** [comment]
Looks like this was done during https://github.com/phetsims/sun/commit/b09ae801a5ff4572a9bc1c74472660f5c187eda5. It is now running on FireListener. Closing
