### ISSUE TITLE
Credits should follow updated string pattern.

### ISSUE THREAD

**Issue by Denz1994** [phetsims/joist#518]
From @pixelzoom in #512.

> Note that I used the old-style pattern for the new 'credits.soundDesign' string: "Sound Design: {0}". Our policy is to use new-style patterns (i.e. "Sound Design: {{credit}}), but in this case it seems more important to remain consistent with the other 7 strings related to the credits (see strings with "credit." key prefix).

Perhaps it would be a good practice to retrofit these patterns as we come across them in common code. I will make an attempt to do so. There are 7 credits fields that should be corrected.

**Comment by pixelzoom** [comment]
We had previously decided not to attempt to change existing uses of the old pattern, because of the effort involved in changing translations.  Happy to re-discuss.  But I still feel that any benefit we'd get from doing this would be negated by the effort to change translations.

**Comment by Denz1994** [comment]
After discussion with @pixelzoom via slack, it seems like this is a larger issue with common string files for all translations. It was explained that any change in a singular translation file needs to be handled in similar translation files (about 63 other files). There needs to be a better solution for this, perhaps involving an automated grunt command that handles managing all transations with the altered string or string pattern. 

Further discussion can be found in https://github.com/phetsims/rosetta/issues/197 and I'll await the discussion in this issue before continuing work here.

**Comment by Denz1994** [comment]
This is stable right now and it doesn't look like https://github.com/phetsims/rosetta/issues/197 will be touched anytime soon. I'm going to close this issue and if our conventions change or find a better pattern to follow, I'll revisit.
