### ISSUE TITLE
Slow loading on phettest

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/joist#519]
@arouinfar and I have both noticed that load times for phettest sims have been very slow.  The load bar does not seem to progress until the sim has almost entirely loaded as well.  Times can last up to a minute.  On Win 10 Chrome I've been noticing 10-30 seconds on average, sometimes longer.
I have been using a Win 10 primarily on Chrome and Firefox. @arouinfar uses a MacOS 10.13. on Chrome.

**Comment by samreid** [comment]
I tested launching http://phettest.colorado.edu/wave-interference/wave-interference_en.html?ea&brand=phet on my MacBook Pro on 10.13.6 running Chrome Version 69.0.3497.81 (Official Build) (64-bit) over my home network with VPN and it launched in about 5 seconds.

**Comment by samreid** [comment]
I tested a few other sims as well as Firefox and saw about the same behavior 5 seconds for Arithmetic, (around 7 seconds to launch Build An Atom).  Can you have other QA team members try to replicate the problem?

**Comment by KatieWoe** [comment]
I asked @JRomero0613 to take a look.  I did just look at the ones you said and I seem to be getting faster times on them.  It does seem to vary by sim and updating Chrome seems to improve times a bit.  It still seems slower than the website or load times usually are.
Try http://phettest.colorado.edu/circuit-construction-kit-dc-virtual-lab/circuit-construction-kit-dc-virtual-lab_en.html?ea&brand=phet
or http://phettest.colorado.edu/area-model-algebra/area-model-algebra_en.html?ea&brand=phet

**Comment by arouinfar** [comment]
@samreid that took well over 30 seconds to load on my Mac, also running macOS 10.13.6. My Chrome was slightly out of date (version 68) so I updated. Wave Interference still took quite a bit of time to load on the latest Chrome -- 12 seconds.

**Comment by KatieWoe** [comment]
@samreid I went to network in the developer tools to look at the loading times for the requests.  This was suggested by @jbphet.  Not sure if it helps, but the phettest version had significantly more requests than the published version.  It also took somewhere over 10 seconds to reach the interactive part of the sim, where the published version took just under 4 seconds.  Hope this helps pin down any possible issues, if any.
Published version:
![publish](https://user-images.githubusercontent.com/41024075/45116147-23ea8d00-b10f-11e8-8e51-314b2fb4ae75.PNG)
Phettest version:
![phettest](https://user-images.githubusercontent.com/41024075/45116163-306ee580-b10f-11e8-9821-21439f472261.PNG)

**Comment by JRomero0613** [comment]
I have just tested about 30 sims and get an average loading time of ~9.5 seconds. Many sims take around 5 or 6 seconds to load, however there are some (around 5 sims) that take 20+ seconds to load, so this drags the average up. If specific sims need to be tested for loading times let me know and I can test.

**Comment by arouinfar** [comment]
I tried loading Wave Interference again from phettest, and the load time is pretty inconsistent. When writing https://github.com/phetsims/joist/issues/519#issuecomment-418849057 the load times were ~12 seconds. Now, it's taking ~ 30 seconds. Both with latest Chrome.

**Comment by samreid** [comment]
@KatieWoe said @jonathanolson has been tinkering with phettest--may be correlated with what we are seeing.

**Comment by jonathanolson** [comment]
Looks like there is a terminal open taking up 100% cpu:

> 53261  Terminal     99.9  3047 hrs

It's probably worth checking the open terminals in person to see if there's something we can restart.

**Comment by KatieWoe** [comment]
Just did a quick check myself.  Some seemed faster this morning, but I just got significant load time on the area model multiplication sim.

**Comment by zepumph** [comment]
Perhaps there is a difference between remote on vpn and on campus.

**Comment by phet-steele** [comment]
Took me 2 seconds to load MAS using VPN just now.

**Comment by arouinfar** [comment]
> Took me 2 seconds to load MAS using VPN just now.

I just clocked 13 seconds on UCB Wireless. 

 I decided to re-test the sims from my earlier https://github.com/phetsims/joist/issues/519#issuecomment-419201156. I'm seeing significant improvement in most cases.  I'll test again later this afternoon.

* Rutherford Scattering: 5 seconds
* Wave Interference: 26 seconds
* Function Builder: 6 seconds 
* Molarity: 4 seconds
* Gravity Force Lab: 10 seconds

**Comment by samreid** [comment]
Would it be better for people on the team to clone & serve the sims on their own machines?  It sounds complicated but it isn't complicated.

**Comment by phet-steele** [comment]
> Would it be better for people on the team to clone & serve the sims on their own machines?

For some people, sure. I started doing that after a while. Told @arouinfar how to but I bet she hasn't been doing that anymore 😝.  But for other people who don't need to look at master often, phettest should still be up and running. It's easier and quicker to have one machine to maintain (ie. keeping up to date) than having every individual person remember.

**Comment by jonathanolson** [comment]
Also if people are just running things off of "latest master", bayes' CT is fairly up-to-date, so you can load sims like https://bayes.colorado.edu/continuous-testing/beers-law-lab/beers-law-lab_en.html?brand=phet&ea

Might be worth a speed comparison check.

**Comment by samreid** [comment]
I thought bayes CT was continually swapping out different snapshots.  How does the continuous-testing/ directory work?

**Comment by jonathanolson** [comment]
It basically is in a continuous "pulling" loop that is interrupted while it creates a snapshot.

**Comment by samreid** [comment]
@jonathanolson and @mattpen do we have gzip enabled for phet-dev and phettest?  

@KatieWoe are you interested in having the simulations checked out on your primary computer?  Or if you are switching devices frequently that may not be too helpful.

**Comment by KatieWoe** [comment]
@samreid it might be useful, I'm not sure.  Maybe we could discuss it later this week?

**Comment by mattpen** [comment]
@samreid I enabled compression for phet-dev, it is much faster now.  I currently don't know how to access phettest and I don't know which application(s) are serving the sims there.  @phet-steele was managing this if I recall correctly, I'm not sure who is responsible for it now.  @jonathanolson, are you able to help with that machine?

**Comment by KatieWoe** [comment]
@arouinfar @jonathanolson loading is back down to a crawl.  It took over two minutes to load one of the sims.  This one took over a minute, see below.  Filmed so that screen capture does not change run time.
https://drive.google.com/file/d/1LI777DRN2EgDnUAfWs_aiopgi-ts3CEu/view?usp=sharing

**Comment by arouinfar** [comment]
Here are some of the fabulous speeds I've experienced today.

* Capacitor Lab: Basics: 83 seconds
* Rutherford Scattering: 88 seconds
* Wave Interference: 85 seconds
* Function Builder:  91 seconds

For the record, I do have a local copy, and know how to use it. The user experience on phettest is vastly superior than dealing with the unix terminal (until the load speeds become so horrendous, that is). I also don't think it's reasonable to require all team members to use a local copy, particularly when it comes to QA testers.

**Comment by arouinfar** [comment]
Thanks @samreid! 

Today's been particularly bad, but I've also noticed that the internet speeds in Duane have been somewhat slower than normal. In general, sims on phettest have been taking in excess of 30 seconds for the past two weeks or so. Occasionally I'll get lucky and a sim will load in about 10s, but that's rare, and still noticeably slower than it used to be.

**Comment by jonathanolson** [comment]
@arouinfar maybe I could help debug in-person or with zoom? I'm getting sims loaded in 3-4 seconds remotely over VPN.

I'm curious if clearing the cache / checking browser plugins / incognito tabs / network debugging etc. could help.

**Comment by jessegreenberg** [comment]
Just another data point, sims listed in https://github.com/phetsims/joist/issues/519#issuecomment-420799813 are loading in 8-10 seconds for me remotely over VPN.

**Comment by arouinfar** [comment]
Thanks for the offer @jonathanolson! If time allows, can you can stop by my office after dev meeting? 

My general approach has included:
* Ensuring macOS and Chrome version are latest
* Trying Incognito tabs (load times are not noticeably different)
* Restarting my computer and opening only a single Chrome window to test phettest

Today, phettest is pretty speedy, but for good measure I completely wiped by browsing history and cache. The sim load times appear unaffected.

The load times have been pretty inconsistent. There have been rare good days (like today) and abysmal days (like yesterday), but most of the time I'm hovering around 30 second load times. Generally speaking, @KatieWoe has been experiencing similarly long load times on her machine (Win10).

**Comment by jonathanolson** [comment]
Was discussed that it may be related to the wifi connection. @KatieWoe can you try an ethernet connection to see if it helps?

I'll stop by after dev meeting to try to get this solved.

**Comment by arouinfar** [comment]
I'll try the ethernet connection next time phettest is acting up and see if that helps. Thanks @jonathanolson!

**Comment by jonathanolson** [comment]
I talked with @KatieWoe about this for a bit. I also recommended testing https://bayes.colorado.edu/continuous-testing/beers-law-lab/beers-law-lab_en.html?brand=phet&ea when it's slow (this is the same "mode" of loading a sim, but from bayes), see if ethernet helps, and see if different browsers makes a difference. Someone in dev meeting mentioned that switching to guest wifi may also help.

Feel free to message/zoom me when it's happening, and I can help and test from my end.

**Comment by arouinfar** [comment]
@jonathanolson to make sure I understand, do I simply replace the portion of the URL before the sim directory (`phettest.colorado.edu/`) with `https://bayes.colorado.edu/continuous-testing/`?

**Comment by samreid** [comment]
> @jonathanolson to make sure I understand, do I simply replace the portion of the sim URL before the sim directory (`phettest.colorado.edu/`) with `https://bayes.colorado.edu/continuous-testing/`?

Hopefully we can get phettest working fast or identify whatever internet problems have been problematic.  But if we can get it to load its index page fast but not load sims fast, we could add a link from phettest => bayes?  Anyways just an idea that we hopefully don't need to use.

**Comment by KatieWoe** [comment]
This hasn't been an issue in awhile.  If @arouinfar agrees I think this can be closed.

**Comment by arouinfar** [comment]
Luckily I haven't run into this issue in a very long time, so I think we can go ahead and close it @KatieWoe
