### ISSUE TITLE
Can phetLaunchSimulation be renamed to phet.joist.launchSimulation?

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#522]
In https://github.com/phetsims/phet-io/issues/275#issuecomment-423762741 @zepumph pointed out that `phetLaunchSimulation` does not follow our usual convention for global naming.  Can/should it be renamed to `phet.joist.launchSimulation`?

**Comment by zepumph** [comment]
Sounds reasonable to me. Does this need a quick dev meeting to make sure that isn't dangerous?

**Comment by samreid** [comment]
This seems safe to implement--I tried it locally and aqua/phet and phet-io fuzz tests seem OK.  I'll commit, Bayes CT can test further.  If we see any problems, we can rethink or revert.

**Comment by samreid** [comment]
Pushed, closing for now.
