### ISSUE TITLE
Convert ScreenButton to use FireListener

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#528]
For https://github.com/phetsims/sun/issues/396, so this will use the Emitter pattern defined by FireListener.

**Comment by samreid** [comment]
The proposed fix is above.  Please note this required changes to two `addAccessibleInputListener` calls.  @zepumph can you please review and test?

**Comment by zepumph** [comment]
this shares the same review comment as https://github.com/phetsims/sun/issues/396#issuecomment-427982527. See there.

**Comment by samreid** [comment]
Addressed in https://github.com/phetsims/sun/issues/396#issuecomment-428802431, anything else for this issue?
