### ISSUE TITLE
[IE] "Report a Problem" page may be blank

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#533]
First noticed in https://github.com/phetsims/graphing-quadratics/issues/85, but affects all sims. 

On IE, the "Report a Problem" page (accessed from the PhET menu) may be blank if you use other query parameters.

@mattpen's evaluation in https://github.com/phetsims/graphing-quadratics/issues/85#issuecomment-432078326 was:
> @phet-steele contacted me on Slack with further information.  To recreate the problem, you have to run the sim on IE11 with the query parameter `profiler`.  It probably works with some other query params too, but its not clear which. 
> 
> The resulting error is : "The URI to be decoded is not a valid encoding".
> 
> It appears that this is likely due to the URI being truncated because it is over 2083 characters long, which appears to be the maximum length [that IE can process](https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers).  We'll either need to reduce the amount of data processed by this page, build a backend that can handle it as POST data, or choose to ignore the issue since it only affects IE11.

**Comment by ariel-phet** [comment]
Marking for dev meeting to discuss at some point at low priority

**Comment by samreid** [comment]
It seems like our decision to work on this should depend on our long-term plans for IE and, in turn, our fraction of IE users in analytics.

**Comment by samreid** [comment]
We decided we would like to remove the SHAs from the report an error URI.

**Comment by jonathanolson** [comment]
Ideally we should strip out the SHAs (or other information we don't really use), and ideally add in the URL that was run? We can generally get the SHAs from the URL, and it should shorten things.

**Comment by zepumph** [comment]
@jonathanolson @samreid please review.

**Comment by rea-laura** [comment]
Also found in https://github.com/phetsims/QA/issues/219
Device: Schrodinger
OS: Windows 8.1
Browser: Internet Explorer 11.0.9600.19155
Only occurs in query parameter ?rtl - all other queries normal.

**Comment by rea-laura** [comment]
Also found in phetsims/QA#243
Device: Bates
OS: Windows 7
Browser: IE 11
Only found in XHTML version of sim

**Comment by zepumph** [comment]
So do we need to cherry pick this change into RC branches? Here is the joist sha:
`3fd17c49d440d899dfcb06d2d4bc2061f672d693`

**Comment by ariel-phet** [comment]
@samreid @zepumph I do not think this warrants a Maintenance release, it will basically be picked up by new sims going into RC in the future, and it is minor enough not to worry about IMO. Closing
