### ISSUE TITLE
Eliminate frameStartedEmitter and frameEndedEmitter

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#534]
From https://github.com/phetsims/phet-io/issues/1383, we would like to eliminate frameStartedEmitter and frameEndedEmitter, and replace usages with `stepSimulationEmitter` (we would make that public).

There are 4 usages of frameStartedEmitter and 3 usages of frameEndedEmitter which would be good to convert, if possible.

**Comment by pixelzoom** [comment]
You haven't provided enough info here. Is `stepSimulationEmitter` functionally equivalent to `frameStartedEmitter` and `frameEndedEmitter`? What is the proposed conversion?

**Comment by pixelzoom** [comment]
I looked at `stepSimulationEmitter` in Sim.js.   A few things:

(1) Emitter takes a `listener` option, and you're apparently relying on that to be called first.  As I mentioned recently, relying on the order of listeners is (in general) a code smell and an anti-pattern.  And the number of times that I've seen this order dependency leveraged in the past week is alarming. I think this warrants a developer discussion.

(2) Is Emitter's `listener` is indeed called first, then all of other listeners are notified after the step is completed.  This makes `stepSimulationEmitter` a replacement for `frameEndedEmitter`, but not for `frameStartedEmitter `.  How to intended to notify listeners before the `step` has been performed?

**Comment by samreid** [comment]
> And can you please summarize why this replacement is needed?

PhET-iO playback and record warranted introduction of `stepSimulationEmitter`.  We hypothesize that we do not need listeners at the beginning of frame and end of frame and that all usages can be converted to use `stepSimulationEmitter` instead.

Let's discuss `Emitter` listener ordering in another issue such as https://github.com/phetsims/scenery/issues/928

**Comment by pixelzoom** [comment]
It sounds like you further hypothesized that no one needs `frameStartedEmitter, because `stepSimulationEmitter` is equivalent to `frameEndedEmitter`.  Is that the case?  How am I supposed to accomplish https://github.com/phetsims/equality-explorer/issues/148, which needs to be done _before_ the first `step` happens?

**Comment by samreid** [comment]
I don't understand why `termCreator.positiveLocation` and `termCreator.negativeLocation` have to be set before `step`.  Would the behavior be different if those values were set at the end of the first step?

**Comment by pixelzoom** [comment]
It may well be the case that we can get away with performing EqEx's callback at the end of the frame.  That's not the point.  The point is that the callback is work that should semantically be done before the first step, and doing it before the first step ensures that it's further proof.  And the general issue is not whether EqEx can be changed or not.  The issue is that there is a legitimate need to have this functionality, and that the proposal here does not meet that need.

**Comment by samreid** [comment]
> The point is that the callback is work that should semantically be done before the first step

The documentation for that listener says

```js
// Things to do after the sim has loaded, when this Node has a valid location.
```

So perhaps adding a listener to `sim.endedSimConstructionEmitter` would be more appropriate?

**Comment by pixelzoom** [comment]
> So perhaps adding a listener to sim.endedSimConstructionEmitter would be more appropriate?

I don't know. The doc tells me that endedSimConstructionEmitter "indicates sim construction completed".  Recommended to replace that with something that actually tells the reader something.

`TermCreatorNode`'s `frameStartedCallback` needs to be called after it has a valid location and before `step`.

**Comment by pixelzoom** [comment]
Continuing discussion of `endedSimConstructionEmitter` in EqEx in https://github.com/phetsims/equality-explorer/issues/148.

**Comment by samreid** [comment]
It looks like the `frameEndedEmitter.addListener` usage by PhET-iO is important--we may need to keep that intact.  I wonder if that should be powered by `stepSimulationEmitter.after`.

**Comment by zepumph** [comment]
From this it may be nice to document a preferred way to add a listener to a frame. Which emitter should be used by default? Is the visibility annotation and documentation clear enough for all of them?

**Comment by samreid** [comment]
I think most simulations should add a listener by implementing `Model.step` or `ScreenView.step`.  When that is impossible, the `Sim` emitters can be used.  I committed better docs.  Anything else to do here?

**Comment by pixelzoom** [comment]
@samreid said:
> I think most simulations should add a listener by implementing `Model.step` or `ScreenView.step`. ...

Is something like this what you had in mind? 

```js
class MyScreenView extends ScreenView {
  constructor(...) {
    this.firstStep = false;  
    ...
  }

  step: dt => {
    if ( this.firstStep ) {
      this.firstStep = false;
      // do some view initialization
    }
   ...
  }
}
```

**Comment by samreid** [comment]
Yes, but this is broader than just doing something on the first try.  Normal models and views implement step like this:

From Balancing Act:
```js
    // Step function, called by the framework, clocks time-dependent behavior.
    step: function( dt ) {
      this.plank.step( dt );
      this.massList.forEach( function( mass ) {
        mass.step( dt );
      } );
    },
```

From Hooke's Law:
```js
step: function( dt ) {
  this.animator.step( dt );
}
```

Hooking into `Sim` emitters gives callbacks for every screen.  Implementing `step` in a model or view is called only for the selected screen.

**Comment by zepumph** [comment]
Looks really good. Thank you both.
