### ISSUE TITLE
screen icons blend into home screen and navigation bar

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#538]
Gas Properties needs to support Projector Mode, so I was looking at how it's implemented in other sims.   While looking at SOM, I noticed these problems, which are also likely to occur in Gas Properties.

Two problems, both of which are general:

### (1) Home screen icons blend into home screen background

The home screen in SOM currently looks like this:

![screenshot_848](https://user-images.githubusercontent.com/3046552/48378949-b703ee00-e68f-11e8-9489-cba0647af64a.png)
 
But the developer (@jbphet) had to put a white stroke around the screen icons so that they wouldn't be lost when unselected.   Compare to the home screen in the Gas Properties (under development):

![screenshot_849](https://user-images.githubusercontent.com/3046552/48379004-eb77aa00-e68f-11e8-8ec2-b8390792d5f1.png)

Shouldn't joist handle the stroke around the unselected icons?

### (2) Navigation bar icons blend into navigation bar background

Here's an example from SOM to illustrate. When in normal mode, the navigation bar looks like this, very clear rectangular screen icons:

![screenshot_846](https://user-images.githubusercontent.com/3046552/48378755-e49c6780-e68e-11e8-8d00-cd862a8e201c.png)

When in Projector mode, the navigation looks like this, where the screen icons disappear into the navigation bar:

![screenshot_847](https://user-images.githubusercontent.com/3046552/48378805-0d246180-e68f-11e8-888e-5c61c53215b5.png)

The problem is worse here than on the home screen.  Even the selected screen icon blends into the navigation bar.  Again, shouldn't joist handle stroking the selected and unselected icons?
 
@arouinfar What's your opinion on these issues?  Should they be addressed?  How should they be addressed?

**Comment by arouinfar** [comment]
@pixelzoom I would LOVE for joist to handle adding a white stroke around icons. For SOM, I think it was more of an oversight on my part. For Wave Interference, I added a white stroke around the artwork itself, which works fine for the home screen icons.
![image](https://user-images.githubusercontent.com/8419308/48379451-67262680-e691-11e8-935b-b554dce4e188.png)

When scaling down the icons for the navbar, the white stroke ends up really faint (basically invisible). 
![image](https://user-images.githubusercontent.com/8419308/48379458-70af8e80-e691-11e8-9ff2-ea168c9e93a4.png)

It would be so much easier if joist could just handle the stroke around the icons.

**Comment by pixelzoom** [comment]
For home screen icons, there is apparently an option to add a stroke, and it's used in SOM.  In JOIST/Sim:

```js
      // If true, there will be a border shown around the home screen icons.  Use this option if the home screen icons
      // have the same color as the background, as in Color Vision.
      showSmallHomeScreenIconFrame: false,
```

The option name could use some work, and the doc isn't quite right.  What it really does is puts a border around unselected home screen icons.  

@arouinfar You should probably use this option in Wave Interference and remove the border from the artwork.

@ariel-phet There should be a similar option to put borders around the navigation bar icons.  Please assign to someone.

**Comment by pixelzoom** [comment]
Since this isn't exactly straightforward (joist has a wonky way of handling this), I'd like some clarification before I spend the time. 

Is this what you want?

(1) Handling of the home screen icons via the `showSmallHomeScreenIconFrame` is OK as is, make no changes.

(2) You'd like another option, say `showNavigationBarScreenIconFrame`, that does the exact same thing as `showSmallHomeScreenIconFrame`.  That is, it strokes the outline of the icon with the exact same color as used on the home screen.

(3) If the same screen icons are used for both the home screen and navigation bar, then the value of `showSmallHomeScreenIconFrame` will also apply to `showNavigationBarScreenIconFrame`, unless `showNavigationBarScreenIconFrame` is explicitly set.

**Comment by ariel-phet** [comment]
@pixelzoom I think so. Since this is in Joist, and should be a relatively quick issue to review, I am going to mark for dev meeting tomorrow (since it would be good for other devs to be aware anyhow). We should be able to get through this issue quickly, so I will mark it high priority.

**Comment by samreid** [comment]
From today's meeting: When testing this, check States of Matter and make sure the light outline isn't too visible against the light navigation bar.

**Comment by pixelzoom** [comment]
Here's what the home screen looks like for the published version of Equality Explorer:

![screenshot_877](https://user-images.githubusercontent.com/3046552/48736474-8f210700-ec08-11e8-95f0-ebae87db287f.png)

Here's what is looks like if we always put the '#dddddd' border around icons on the home screen:

![screenshot_878](https://user-images.githubusercontent.com/3046552/48736486-98aa6f00-ec08-11e8-9388-17e873be933f.png)

I actually kind of like the added border, it prevents the unselected icons from disappearing into the background, makes them pop a little more.  And it's still very clear which icon is selected.

@ariel-phet your opinion?

**Comment by pixelzoom** [comment]
On second thought... I don't like the border on the unselected icons.  I also don't like them being omnipresent in the navigation bar.   No idea what to do here.

**Comment by arouinfar** [comment]
So, I know my two cents weren't requested, but I'm going to throw them out there anyway.  

I really dislike the stroked icons in Equality Explorer. The stroke highlights the unselected screens and creates some competition with the selected screen. In part, I think it's because the screen icons have pastel-colored backgrounds, rather than black.

I would rather manually add white outlines around the artwork for icons with black backgrounds, than see this outline universally applied to all screen icons.

**Comment by pixelzoom** [comment]
> I really dislike the stroked icons in Equality Explorer.

Agreed.

> I would rather manually add white outlines around the artwork for icons with black backgrounds, than see this outline universally applied to all screen icons.

The background color changes dynamically (e.g. projector mode).  And in the future, the navbar may not be limited to 'black' and 'white'.   So if you add the stroke to the artwork, you'll be creating a related but different problem.

**Comment by ariel-phet** [comment]
@pixelzoom yeah...not digging the stroke around the equality explorer icons

**Comment by ariel-phet** [comment]
It seems one needs the option to stroke specific icons, and not others (such as in the wave interference example above).

**Comment by pixelzoom** [comment]
> It seems one needs the option to stroke specific icons, and not others (such as in the wave interference example above).

That's a totally different implementation that what currently exists.  Rather than creating a brand new hack, effort would be better spent addressing the lack of ColorProfile support in joist, https://github.com/phetsims/joist/issues/222.

**Comment by samreid** [comment]
@arouinfar requested this be completed for wave interference 1.0, coming up soon, for https://github.com/phetsims/wave-interference/issues/32.  Bumping priority accordingly.

**Comment by pixelzoom** [comment]
@samreid said:
> @arouinfar requested this be completed for wave interference 1.0, coming up soon,...

What's the ETA?

**Comment by samreid** [comment]
From https://github.com/phetsims/wave-interference/issues/32#issuecomment-453272758

> At today's design meeting, @ariel-phet and @arouinfar said this is not essential for 1.0, marking deferred.

**Comment by pixelzoom** [comment]
In the above commits, I replaced Sim's `showSmallHomeScreenIconFrame` options with `Screen` option `showUnselectedHomeScreenIconFrame` (default `false`).   This allows us to specify _per screen_ whether the unselected (small) home screen icon should have a frame around it.

This was update in color-vision, gas-properties, states-of-matter (@jbphet), wave-interference (@samreid).

**Comment by pixelzoom** [comment]
The above commits introduce a new `Screen` options, demonstrated in gas-properties:

```js
// {string|null} show a frame around the screen icon when the navbar's background fill is this color
// 'black', 'white', or null (no frame)
showScreenIconFrameForNavigationBarFill: null,
```

If anyone has a better name for this option, feel free to change it. Though the fact that it's just as awful as `showUnselectedHomeScreenIconFrame` provides some nice symmetry.

Setting `showScreenIconFrameForNavigationBarFill: 'black'` in GasPropertiesScreenView looks like this:

Projector Mode off, no icon frame:
<img width="899" alt="screenshot_965" src="https://user-images.githubusercontent.com/3046552/51162610-0f07ce00-1854-11e9-83ce-609404a62171.png">

Projector Mode on, icon frame is shown:
<img width="900" alt="screenshot_967" src="https://user-images.githubusercontent.com/3046552/51162707-7160ce80-1854-11e9-9367-e9542a8d7a6d.png">

**Comment by pixelzoom** [comment]
Over to @samreid for review, in case he wants to use this in Wave Interference.   Below is what it would look like (not committed) with `showScreenIconFrameForNavigationBarFill: 'black'`.

<img width="899" alt="screenshot_968" src="https://user-images.githubusercontent.com/3046552/51162842-dd433700-1854-11e9-9139-84db5583388d.png">

**Comment by samreid** [comment]
In the commits for this issue, `'#dddddd'` was added once for `showScreenIconFrameForNavigationBarFill` and again for `showUnselectedHomeScreenIconFrame`.  It is documented as a gray that works well against black.  Should these be factored out into JoistConstants (which doesn't yet exist), or is it important that these vary independently?

**Comment by pixelzoom** [comment]
In the above commit, I added PhetColorScheme.SCREEN_ICON_FRAME.  Back to @samreid for review.

**Comment by samreid** [comment]
Changes look good.  I also tested the options in Gas Properties.  No other recommendations at this time, closing.
