### ISSUE TITLE
Add intermediate "general" tandem

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#539]
From https://github.com/phetsims/phet-io-wrappers/issues/143#issuecomment-440859324

> organize joist-like stuff all under "universal" or "general" "framework", we like "general". Keep navigationBar, and homeScreen out of there. Current list to move to "general":
activeProperty
browserTab
phetioCommandProcessor
resizedEmitter
screenIndexProperty
showHomeScreenProperty

**Comment by samreid** [comment]
@chrisklus and I added "general" in the above commits.  It seems things are mostly working aside from the "diff" and "multi" wrappers.

**Comment by chrisklus** [comment]
@samreid and I have fixed the "multi" wrapper. The "diff" wrapper error was triggered by checking "pause on caught exceptions" for a non-PhET related script, so it appears to not be an issue. Ready to close.

**Comment by samreid** [comment]
My apologies, https://github.com/phetsims/tandem/commit/9c1990fccd66b0e17375e08c7cdfa0437d000aa9 introduced `const` into a preload file.  Preloads do not run through babel and iPad 2 crashes when it parses.

**Comment by samreid** [comment]
Patch fix committed in https://github.com/phetsims/tandem/commit/4336872f0c7c6e3571d99c4b1c9c36da39915ecc

That commit can be used as a cherry-pick.

**Comment by samreid** [comment]
I additionally said on slack:

Sam Reid [6:11 PM]
Master is fixed.  Commit should be cherry-pickable.  Let me know if you want me to use that to create RC.2 of anything.

Reassigned to @pixelzoom and @jonathanolson since they created RC's with this bug.  Sorry for the trouble and let me know how I can help.

**Comment by pixelzoom** [comment]
Self assigning so that I can cherry pick for Graphing Quadratics 1.0 release branch.

**Comment by jonathanolson** [comment]
I patched the area-model RCs.

**Comment by pixelzoom** [comment]
Graphing Quadratics 1.0 release branch is also patched in tandem branch "graphing-quadratics-1.0".

**Comment by samreid** [comment]
Thanks @jonathanolson and @pixelzoom.  Master is fixed, recent branches are fixed, and we have an open issue to prevent this class of error from happening again.  Since this error was only introduced 6 days ago, it seems unlikely that we have taken other SHAs from master that contain this problem, closing.
