### ISSUE TITLE
kebab menu icon

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#544]
During 12/6/18 status meeting, @samreid referred to the "shish kabob" menu in the context of PhetButton:

![screenshot_934](https://user-images.githubusercontent.com/3046552/49602020-af5cff80-f944-11e8-9be5-4db3fe826450.png)

Slack discussion ensued:

Chris Malley [10:31 AM]
Shish kabob button? JB and I are interested in why you’re calling it that.

Sam Reid [10:33 AM]
I heard it from someone else on the team (don’t remember who).    The three lines which used to be prevalent were referred as the “hamburger menu”.  When everybody switched that to dots, someone called it “shish kabob” because of the food analogy?

Chris Malley [10:33 AM]
Ah, I see… Sort of a hamburger button with severe aspect ratio. https://en.wikipedia.org/wiki/Hamburger_buttonhttps://en.wikipedia.org/wiki/Hamburger_button (edited)

Sam Reid [10:34 AM]
 
![image](https://user-images.githubusercontent.com/3046552/49601966-918f9a80-f944-11e8-9bc3-ec9dcbd8351d.png)

Sam Reid [10:34 AM]
https://ux.stackexchange.com/questions/115468/what-the-difference-between-the-2-menu-icons-3-dots-kebab-and-3-lines-hambur

Chris Malley [10:39 AM]
I’ve documented “kebab menu icon” in PhetButton.js

Sam Reid [10:40 AM]
Thanks

Chris Malley [10:41 AM]
I didn’t rename any local vars (optionsShape, optionsCircleRadius, optionsButton), but perhaps we should.  `optionsButton` doesn’t seem correct regardless of the shape, so it took me longer than I thought it should to locate.
`optionsButton` is also not a button, it’s a Path.
kebabIconShape, kebabCircleRadius, kebabIcon respectively?
I’m going with kebabShape, kebabRadius and kebabIcon.

**Comment by pixelzoom** [comment]
I factored out KebabMenuIcon, used some more descriptive var names in PhetButton, and fixed some doc in PhetButton.  @samreid please take a peek, feel free to close.

**Comment by pixelzoom** [comment]
I also simplified the Shape description by using `circle` instead of `arc`.  Comparing before and after, they look identical.

**Comment by samreid** [comment]
Looks great, thanks, closing.
