### ISSUE TITLE
Show mouse/touch areas for navigation buttons?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#545]
@kathy-phet was curious why the mouse/touch areas for the navigation buttons don't show up with ?showPointerAreas, e.g.:

![image](https://user-images.githubusercontent.com/5096804/50136288-8dbd1b80-0254-11e9-984e-4cde253a2a3f.png)

which is due to the code in NavigationBarScreenButton:

```js
    // add a transparent overlay for input handling and to size touchArea/mouseArea
    var overlay = new Rectangle( 0, 0, box.width, box.height, { center: box.center } );
```

Should this be changed to use the mouseArea/touchArea setting (instead of a Rectangle, which in this case is also used for sizing)?

Should this be something done in general?

**Comment by pixelzoom** [comment]
> Should this be changed to use the mouseArea/touchArea setting (instead of a Rectangle, which in this case is also used for sizing)?

Yah, probably. But if we remove `overlay`, we'll need to adjust the horizontal spacing of the buttons.

> Should this be something done in general?

What do you mean by "in general"?  In general for NavigationBarScreenButton.  In general for all Node, no.

**Comment by jonathanolson** [comment]
> What do you mean by "in general"?

I guess it's helpful for the ?showPointerAreas query parameter to be able to display any non-intuitive areas. For example, looking at the navbar buttons, I wouldn't be able to tell where the touch areas would be.

**Comment by pixelzoom** [comment]
Sorry, I still don't understand.  What are "non-intuitive areas"?  Are you proposing that Nodes without explicit pointer areas should show their bounds as the default pointer areas?

**Comment by jonathanolson** [comment]
> What are "non-intuitive areas"?

In general, an area that is different than the actual components visual area. In this case, There are two pieces of each component: the text and the icon. However the mouse/touch area expands horizontally, and includes the bottom corners where there is empty space.

> Are you proposing that Nodes without explicit pointer areas should show their bounds as the default pointer areas?

I'm considering something similar to this, since it seems to be confusing that certain "nonobvious" things don't show their pointer areas with the query parameter. The "default" (without this transparent rectangle) would be just clicking directly on the icon/text. In general I would definitely not like to expand this to "clickable anywhere within its bounds".

I think the proposal to consider (that I'm somewhat on the fence for) is "prefer explicit mouse/touch areas over creating transparent nodes, and have explicit mouse/touch areas if the clickable area would not be visually obvious)".

**Comment by kathy-phet** [comment]
>Are you proposing that Nodes without explicit pointer areas should show their bounds as the default pointer areas?
Both Amanda and I noticed that the "Mixed Number" checkbox originally showed now touch area. I had to decide what I thought it would be and requested it to be bigger. It would have been useful to be able to review what it was and not have to guess what it was before deciding if it should be bigger for that component.

**Comment by ariel-phet** [comment]
@ariel-phet says that showing pointer Areas for these navigation buttons is unnecessary (we have never changed them, they are not an issue in interviews, etc) and it is not worth the effort to make this change.

However, we will investigate showing pointer areas for checkboxes, as per @kathy-phet comment in a separate issue.
