### ISSUE TITLE
Limit width of content in KeyboardHelpDialog

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/joist#546]
KeyboardHelpDialog currently assumes that its content will keep the width within the dev bounds.  But this means that we generally need to define a max width on the content every time we create a KeyboardHelpDialog. In https://github.com/phetsims/resistance-in-a-wire/issues/203 @jbphet recommended 
> it seems like it would be better to do this generally so that KeyboardHelpDialog is automatically limited to the dev bounds.

Assigning to myself to investigate.

**Comment by jessegreenberg** [comment]
This issue is not specific to KeyboardHelpDialog but all Dialogs. Dialogs don't have knowledge of the dev bounds and are often not attached to a ScreenView so it doesn't seem like a Dialog can do this generally.

**Comment by jessegreenberg** [comment]
What if we have a supertype KeyboardHelpDialogContent that has a default maxWidth that works well for default layout bounds of ScreenView but can be specified as an option for sims that are not using default layout bounds?

**Comment by zepumph** [comment]
I found phet.sim.joist.screenBoundsProperty (joist-internal) (read-only). What if we just used a percent of that?

**Comment by zepumph** [comment]
@jessegreenberg please review. Do you think that this kind of solution could work?

**Comment by jessegreenberg** [comment]
Ah, I found that Dialog has a layout strategy option that has everything that we need!

**Comment by jessegreenberg** [comment]
I tested this in RIAW, friction, and coulombs-law. @zepumph can you please review?

**Comment by zepumph** [comment]
This looks awesome! Well done. I will note in friction, and let you handle RIAW.
