### ISSUE TITLE
[Edge] right end of screen can be cut off

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/joist#549]
Found during https://github.com/phetsims/QA/issues/276, but is present in any sim.  When the Edge window is very tall and thin, the right edge of the sim can be hidden.  This does not seem to occur if the sim is loaded into a window in this state.  To reproduce:
1. Size edge window so that it is tall and wide, but not full screen
2. load sim
3. Quickly drag right side in so window is tall and thin

![sidesimoutbounds](https://user-images.githubusercontent.com/41024075/52000349-1fd25980-247a-11e9-8f4a-5ce4b4f2918b.jpg)

![resize](https://user-images.githubusercontent.com/41024075/52000090-78552700-2479-11e9-9faa-7d4a2962b6e6.gif)

**Comment by zepumph** [comment]
@emily-phet should this block the next publication for friction?

**Comment by KatieWoe** [comment]
Agreed.  Minor issue and also not unique to friction.  It happens with any sim.

**Comment by samreid** [comment]
@ariel-phet how do you want to proceed on this issue?

**Comment by ariel-phet** [comment]
Considering Edge bugs should generally be fixed when it moves to chromium, we have not been paying attention to them unless they are more int he "showstopper" category. Given the nature of this bug I am going to mark as `wontfix` and close.
