### ISSUE TITLE
One step() is called before endedSimConstructionEmitter emits

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#550]
Discovered in https://github.com/phetsims/equality-explorer/issues/148, the startup sequence ends like this:

```js
// place the requestAnimationFrame *before* rendering to assure as close to 60fps with the setTimeout fallback.
// http://paulirish.com/2011/requestanimationframe-for-smart-animating/
// Launch the bound version so it can easily be swapped out for debugging.
self.boundRunAnimationLoop();

// Communicate sim load (successfully) to joist/tests/test-sims.html
if ( phet.chipper.queryParameters.postMessageOnLoad ) {
  ( window.parent !== window ) && window.parent.postMessage( JSON.stringify( {
    type: 'load',
    url: window.location.href
  } ), '*' );
}

// After the application is ready to go, remove the splash screen and progress bar
window.phetSplashScreen.dispose();

// Signify the end of simulation startup, finish the simStartedEvent.  Used by PhET-iO. This does not
// coincide with the end of the Sim constructor (because Sim has asynchronous steps that finish after
// the constructor is completed )
self.endedSimConstructionEmitter.emit();
```

This has the result that `step()` is called once before `endedSimConstructionEmitter`.  This may not cause practical problems, but I wonder if it needs to be swapped to keep things nice and organized.  I'm not sure if any code is relying on this ordering at the moment (I hope not).

@pixelzoom thoughts?

**Comment by pixelzoom** [comment]
My thought its that this is not good - stepping the model and view could cause problems if the scenegraph isn't constructed. Recommended to fix this, but I don't have the time to participate.

Re impact on EqEx... Since this step this also happens before `frameStartEmitter` and `frameEndEmitter` emit, using `endedSimConstructionEmitter` shouldn't be an issue.

**Comment by samreid** [comment]
> stepping the model and view could cause problems if the scenegraph isn't constructed.

The model and views *are* constructed before the first step, but step is called before endedSimConstructionEmitter notifications.

**Comment by pixelzoom** [comment]
I said:
> ... using endedSimConstructionEmitter shouldn't be an issue.

I spoke too soon.  The change to `endedSimConstructionEmitter` is causing problems. see https://github.com/phetsims/equality-explorer/issues/149. 

@samreid said:
> The model and views are constructed before the first step, but step is called before endedSimConstructionEmitter notifications.

Then perhaps endedSimConstructionEmitter needs to be moved earlier (depending on its semantics) or we need another Emitter that signifies "model and view are constructed".

**Comment by samreid** [comment]
I committed the proposed fix.  It could cause trouble if some code is relying on one step() being done before doing work on the `endedSimConstructionEmitter` notifications.  But that is hopefully not happening, and if it is, it sounds like it should be repaired.

**Comment by pixelzoom** [comment]
I looked at the commit and don't see anything obviously wrong.  I'll leave this assigned to @zepumph in case he wants to also have a look.
