### ISSUE TITLE
Profiler broken

### ISSUE THREAD

**Issue by jbphet** [phetsims/joist#552]
The profiler isn't working on master.  I investigated a little bit, and it looks like `sim.frameEndedEmitter` is never firing.  I think @samreid has been doing some work related to these emitters (he asked me something about them for the Neuron sim), and he is also one of the primary authors for joist, so I'm assigning to him.

I'm marking this as high priority since it prevents me from being able to take the measurements needed for issues like https://github.com/phetsims/energy-forms-and-changes/issues/191.

**Comment by samreid** [comment]
I added a commit which should fix the issue, thanks for pointing out this problem.  Let me know if it's resolved.

**Comment by jbphet** [comment]
Looks great, thanks for the quick fix.  Closing.
