### ISSUE TITLE
AboutDialog should be created during startup

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#558]
From https://github.com/phetsims/phet-io/issues/1454, we would like to simplify the PhET-iO API by creating the about dialog during startup.  But we would also like to postpone network activity until the dialog is shown, if that is not too much trouble. 

Mentioning @jonathanolson because this overlaps with #557 

Also, we should check that this doesn't put too much additional burden on the heap or startup time.

**Comment by pixelzoom** [comment]
This is a slippery slope.  Dialogs should generally be created on demand, and eagerly creating the About dialog doesn't address the problem generally.  Are we also going to create the (optional) Options dialog?  What are the alternatives?

**Comment by pixelzoom** [comment]
I'm confused. Reading https://github.com/phetsims/phet-io/issues/1454, it sounds like there's an intention to "support instrumented element that is dynamic/lazily created".  Why is that not applicable to the About dialog?

**Comment by samreid** [comment]
> Dialogs should generally be created on demand

Why?  Do they incur too much CPU time during startup?  Too much memory usage on the heap?  Better programming practice?  Other runtime considerations?

> it sounds like there's an intention to "support instrumented element that is dynamic/lazily created"

The strategy we used for Group is to provide an archetypal element that completely describes the PhET-iO structure/api (subtandems and all) for members of the group.  If we apply that pattern to dynamic/lazily created elements, then we might end up with something like this: create a "synthetic" About Dialog to signify the API structure, then when the button is pressed, create the "real" About Dialog.  That plan creates 2x too many About Dialogs!  I foresee the following possibilities:

a) Create the dialogs and other things on startup
b) Somehow capture the static API from the baseline file and use that as the "archetype"

(b) sounds complicated and brittle, so I wanted to investigate (a) more to see if it is feasible.

In simulations, we often create dialogs lazily, but do not apply this practice to other parts of the sim.  For instance in Wave Interference Screen 1, the simulation starts by showing the Water Scene, but the Sound and Light scenes are eagerly (not lazily) created.  That is good because they become immediately interoperable for PhET-iO.  I don't know how we've arrived at the policy of "create everything in the sim eagerly except for dialogs", but I'm inclined to investigate that as a pattern, including investigating the impact on heap and startup time.

**Comment by pixelzoom** [comment]
> I don't know how we've arrived at the policy of "create everything in the sim eagerly except for dialogs", but I'm inclined to investigate that as a pattern, including investigating the impact on heap and startup time.

We are not creating everything eagerly, we are creating the initial state of all screens eagerly.

We create screens eagerly because the time delay to create and switch to a new screen was determine to be (in general) unacceptable.  It's assumed that students will visit each screen, and we decided that it was a preferable UX to have the cost to create all of the screen incurred on startup.  

Requiring everything to be created eagerly is imo an unacceptable limitation.  It makes no sense to eagerly create things that may never need to be created.  About dialog certainly falls into that category.   The only reason we're having this discussion is that we've waited until far too late in this process to fully consider how PhET-iO works with dynamic creation.

**Comment by samreid** [comment]
Some ideas on the spectrum from easy to difficult:

1. Dynamic things are uninstrumented.  They are not customizable and we don't get data stream for them
2. Dynamic things are converted to static, created eagerly.
3. Dynamic things are created eagerly during baseline creation, but not during the sim runtime

For the latter: if we reuse the same code for creating the "prototypes" as the real instances, it could look something like:

```
Index: js/PhetMenu.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/PhetMenu.js	(revision ac1aeb89f6688f3ac8c3ca443b8e277487d22edf)
+++ js/PhetMenu.js	(date 1556206001000)
@@ -121,6 +121,13 @@
     var optionsDialog = null;
     var updateDialog = null;
 
+    const createAboutDialog = () => {
+      aboutDialog = new AboutDialog( sim.name, sim.version, sim.credits, Brand, sim.locale, phetButton,
+        tandem.createTandem( 'aboutDialog' ) )
+    };
+
+    printBaselineFile && createAboutDialog();
+
     /*
      * Description of the items in the menu. See Menu Item for a list of properties for each itemDescriptor
      */
@@ -309,8 +316,7 @@
         separatorBefore: isPhETBrand,
         callback: function() {
           if ( !aboutDialog ) {
-            aboutDialog = new AboutDialog( sim.name, sim.version, sim.credits, Brand, sim.locale, phetButton,
-              tandem.createTandem( 'aboutDialog' ) );
+            createAboutDialog();
           }
           aboutDialog.show();
         },
```

**Comment by samreid** [comment]
We measured the size of the about dialog to be about 1MB, so we would like to create it lazily.  Not sure what approach to use, it will depend somewhat how we want to see it in Studio, which is a question for PhET-iO design meeting.

@chrisklus says maybe the about dialog could be streamlined to not take up 1MB.

**Comment by samreid** [comment]
@kathy-phet suggests: let's not instrument the About Dialog for now.  We can take time to make sure we design Group and/or Lazy things properly.

**Comment by zepumph** [comment]
Note that this will currently break phet-io/a11y together, see `Display.focus` setter:

```js
    set focus( value ) {

      // If in phet-io brand, a11y is enabled, and the focus is not null
      if ( window.phet && phet.phetio && phet.chipper.accessibility && value ) {
        var node = value.trail.lastNode();
        assert && assert( node.isPhetioInstrumented(),
          'When running phet-io mode, all focusable instances must be instrumented.' );
      }
```

**Comment by zepumph** [comment]
In the above commits I made the following changes:
* Uninstrumented AboutDialog
* Add phetioComponentOptions to other menu items (from https://github.com/phetsims/phet-io/issues/1420, I made all the menu items consistent)
* Relax the assertion that all focusable elements need to be phet-io instrumented, and tweak a few bugs found about focus related to https://github.com/phetsims/scenery/issues/866.
* The majority of the above commits are from baseline updates. From the instrumentation changes.

@samreid please review.

**Comment by samreid** [comment]
Are values for `phetioIDIndices` ever read or used by anything?  Or is that for data stream output only?

**Comment by zepumph** [comment]
Just for data stream output. Focus changes are downstream of Keyboard related input actions, so a11y input record playback works largely the same way as traditional input.

**Comment by samreid** [comment]
`TARGET_SUBSTITUTE_KEY` is difficult for me to understand.  For example:

```js
// Special case for target since we can't set that read-only property. Instead use a substitute key.
if ( key === 'target' ) {
  domEvent[ TARGET_SUBSTITUTE_KEY ] = eventObject[ key ];
}
```
Why is `'target'` the appropriate substitute?  What does it mean?  When/why is this code (i.e. `deserializeDomEvent`) called?

Other changes look good, I'm just trying to understand the changes in Input.js better.

**Comment by zepumph** [comment]
`event.target` is a read-only field that the browser set's on an event. It is very important for a11y input that we know what HTML element received the event. This is because in the PDOM to go from HTMLElement -> Node, we keep the TrailID (string) as a data attribute on the HTMLElement. When serializing the event, we make sure to keep track of the trailID from the target:
![image](https://user-images.githubusercontent.com/6856943/58600220-345c0e00-8230-11e9-9ac4-6e6631a41a2f.png)


When deserializing (needed for phet-io playback), we are not able to set that back to the target, so we use a substitute key that we can set to:

![image](https://user-images.githubusercontent.com/6856943/58600257-59e91780-8230-11e9-99fb-6fb9ffe1673a.png)


Please feel free to reach out and we can talk more if this still doesn't make sense.

**Comment by zepumph** [comment]
Removing from blocks publication.

**Comment by samreid** [comment]
Remarking as blocks publication because this seems it should be done for GQIO11

**Comment by samreid** [comment]
@chrisklus and I reviewed the changes and have a better understanding of `TARGET_SUBSTITUTE_KEY`.  We think this issue can be closed.
