### ISSUE TITLE
Screenshot button in PhET menu prompts alert saying webpage trying to open popup

### ISSUE THREAD

**Issue by ghost** [phetsims/joist#559]
Found while doing testing for phetsims/QA#313. Seen on iOS 9.3.5 + XHTML version.

I've only seen this once and I can't reproduce.

**Comment by lmulhall-phet** [comment]
@ariel-phet, I'm going to mark as deferred since we don't support iOS 9 and I've only seen this in XHTML and I haven't found a way to reliably reproduce.

**Comment by samreid** [comment]
Closing for now based on the unsupported platform and rare sighting, thanks for reporting this!
