### ISSUE TITLE
branch: browserZoom

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/joist#562]
In support of initial investigation for phetsims/scenery#175, to see if we can leverage the browser to support zoom and magnify. Expecting changes in scenery, joist, and chipper, each which will require a branch like this one. For more documentation, please see phetsims/scenery#175.

**Comment by samreid** [comment]
@jessegreenberg has this branch been merged to master, can this branch/issue be deleted/closed?

**Comment by zepumph** [comment]
@jessegreenberg, I'm going through my repos to check in on branches, can this branch be closed? If not please let us know the current status of it.

**Comment by jessegreenberg** [comment]
Yes, thanks this can and has been deleted.
