### ISSUE TITLE
branch: customZoom

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/joist#563]
A branch to explore custom panning/zooming of Sim.js. Changes are part of https://github.com/phetsims/scenery/issues/974. This is an alternative to #562 where we explored pan/zoom/magnify done natively with the browser. This branch uses PanZoomListener to do this in a custom way with Scenery.

**Comment by samreid** [comment]
@jessegreenberg has this branch been merged to master, can this branch/issue be deleted/closed?

**Comment by jessegreenberg** [comment]
Yes, this exploratory branch can be deleted now, it has been removed.

**Comment by zepumph** [comment]
Should be re-deleted as part of phetsims/special-ops#198

**Comment by zepumph** [comment]
Deleted
