### ISSUE TITLE
NavigationBar tandem should be nested under `general`

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#564]
I made a slack poll, and it seems like this should be done.

**Comment by zepumph** [comment]
@samreid I made the changes above. Please review

**Comment by samreid** [comment]
@chrisklus and I reviewed the changes and agree this looks good.  Still, we are wondering if it needs @kathy-phet to sign off because it changes our previously prescribed tandem structure for the nav bar.  I'll mark for quick discussion in an upcoming PhET-iO meeting.

**Comment by samreid** [comment]
@kathy-phet reviewed this and said it seems fine, closing.
