### ISSUE TITLE
Some sims will activate home screen buttons when you right click

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/joist#567]
I noticed that some sims would either make a small screen icon big, or take you into a screen if the icon is big, if you right click on it.  This is normally only the behavior if you left click on those buttons.  Right clicks do not seem to activate any portion of the screens themselves from what I have so far observed.  It does happen on gravity and orbits and not on energy forms and changes  If more testing is needed to narrow down what sims are affected, let me know.
![rightclickopens](https://user-images.githubusercontent.com/41024075/60917882-24801280-a24f-11e9-83a4-96a25bd7d291.gif)
@ariel-phet for priority

**Comment by samreid** [comment]
Also adding @jonathanolson since scenery handles the left/right mouse buttons.

**Comment by ariel-phet** [comment]
@KatieWoe can you identify when this bug went away? I think there might be a way to see the publication date of sims, certainly all the sims on the  "new sims page" don't seem to have this bug, and it sounds like it is not appearing in master, so I am tempted to mark as `wontfix`

**Comment by KatieWoe** [comment]
I'll take some time when the repo is a bit more clear and look for the latest sim to have the problem.

**Comment by KatieWoe** [comment]
Here is a list of sims that are affected.  Some other only have one screen, so they might have the code bug, but not show it.
Acid Base Solutions
Area Builder
Area Model Algebra
Area Model Introduction
Area Model Multiplication
Arithmetic
Balancing Act
Beer's Law Lab
Bending Light
Build an Atom
Capacitor Lab Basics
Circuit Construction Kit DC
Color Vision
Energy Skate Park Basics
Equality Explorer
Equality Explorer Basics
Expression Exchange
Forces and Motion Basics
Fraction Matcher
Function Builder
Function Builder Basics
Gene Expression Essentials
Gravity and Orbits
Hooke's Law
Make a Ten
Masses and Springs
Molecule Polarity
Pendulum Lab
pH Scale
Plinko Probability
Projectile Motion
Proportion Playground
Reactants Products and Leftovers
Rutherford Scattering
States of Matter
States of Matter Basics
Unit Rates

**Comment by ariel-phet** [comment]
@KatieWoe thanks

Considering that the bug appears fixed in master, and it is unlikely to be pedagogically damaging (really the main purpose of the homescreen is to navigate to the sim), I think we can close this issue. It is a good find, but I am going to mark this as `wontfix` as it does not seem worth the resources to track it down and perform a maintenance release.
