### ISSUE TITLE
change API for OptionsDialog content

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#568]
Over in https://github.com/phetsims/tandem/issues/96#issuecomment-512588509, I noted that the OptionsDialog is created as tandem `general...phetMenu.optionsDialog`.  But there's no way to get that tandem to use as the parent for the dialog's content. 

The API for creating the Options dialog is to provide `options.optionsNode` to `Sim` constructor, and OptionsDialog is automatically with that content in `PhetMenu`. 

Maybe the API should be changed to pass a function that will create the content for the `OptionsDialog`, so that `OptionsDialog` can create the correct tandem.

Something like this passed to Sim constructor:

```js
createOptionsDialogContent: tandem => new MyContentNode( tandem ) 
```

Then in PhetMenu:

```js
optionsDialog = new OptionsDialog( createOptionsDialogContent, { 
  tandem: tandem.createTandem( 'optionsDialog' ) 
} );
```

Then in OptionsDialog:

```
function OptionsDialog( createContent, options ) {
  ...
  const content = createContent( options.tandem.createTandem( 'content' ) );
```

**Comment by pixelzoom** [comment]
Looks like we have 14 sims that use the `optionsNode` option.

**Comment by samreid** [comment]
We reviewed this at today's meeting and it seems like a good pattern.  @pixelzoom will proceed.

**Comment by pixelzoom** [comment]
The API change was completed in the above commits.

Note that 3 sims were creating the OptionDialog's content with phetioID "globals.options": blackbody-spectrum, charges-and-fields, coulombs-law.   You will no longer see the dialog content at `globals.options` is the Studio tree, and you won't see it (or the OptionsDialog) in Studio until https://github.com/phetsims/phet-io/issues/1454 and https://github.com/phetsims/phet-io-wrappers/issues/288 are addressed. 

When those issues have been addressed (including the TODOs in OptionsDialog), the OptionsDialog content will have phetioID:

`${{SIM}}.general.navigationBar.phetButton.phetMenu.optionsDialog.content`

 @zepumph would you mind reviewing? Start with the changes to Sim, PhetMenu, and OptionsDialog in https://github.com/phetsims/joist/commit/4088c5cd568d42a133cce36f984d39c4dea3e163.

**Comment by pixelzoom** [comment]
After making these changes, I'm seeing this error in CT for sims that have an OptionsDialog, presumable with the Option menu item gets selected:

```js
gas-properties : phet-io-tests : assert
7 out of 9 tests passed. 2 failed.
SimTests: gas-properties: iframe api failed:
Uncaught Error: Uncaught Error: Assertion failed: api mismatches present:

gasProperties.general.navigationBar.phetButton.phetMenu.optionsMenuItem:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.,
gasProperties.general.navigationBar.phetButton.phetMenu.optionsMenuItem.inputListener.firedEmitter:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.,
gasProperties.general.navigationBar.phetButton.phetMenu.optionsMenuItem.inputListener.pressAction:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.,
gasProperties.general.navigationBar.phetButton.phetMenu.optionsMenuItem.inputListener.releaseAction:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.,
gasProperties.general.navigationBar.phetButton.phetMenu.optionsMenuItem.opacityProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.,
gasProperties.general.navigationBar.phetButton.phetMenu.optionsMenuItem.pickableProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.,
gasProperties.general.navigationBar.phetButton.phetMenu.optionsMenuItem.visibleProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
https://bayes.colorado.edu/continuous-testing/snapshot-1563662192305/phet-io-wrappers/js/tests/SimTests.js?:318
```

**Comment by pixelzoom** [comment]
Workaround for the CT errors appears in the above commit.  I'm creating OptionsDialog with `Tandem.optional` until there's support for dynamic elements.

**Comment by zepumph** [comment]
* Thanks for the workaround, it looks better than the one I put in place.

* I like that you are passing tandem into items via options if that is already set up for it. That pattern is new (I think from GQ), and I see it working very nicely.

* Sim cases, for example commits like https://github.com/phetsims/atomic-interactions/commit/93d0d4808855a70c80f46baaf198946c055ce2ab, seem good, future proof, and make things consistent to convert to a function, though there is a part of me that wonders if we should support `{null|function|node}` and you can pass a creator or just the `Node`. No preference for me, but I just thought I'd mention the thought. 


Otherwise things look very good. Nice work!

**Comment by pixelzoom** [comment]
> there is a part of me that wonders if we should support `{null|function|node}` and you can pass a creator or just the `Node`.

This would be useful if OptionNode had a use outside of PhET Menu > Options, but it currently does not.   And we definitely don't want to pass a `Node`  in any of those cases.   If it comes up in the future, we can add it later. 

Closing.
