### ISSUE TITLE
change ProjectorModeCheckBox API

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#569]
Now that we have Tandem.global and it shows up in Studio (courtesy of https://github.com/phetsims/tandem/issues/94), I see that there a conflict between ColorProfile's `profileNameProperty` (a string) and GasPropertiesGlobalOptions `projectorModeEnabledProperty` (a boolean).  Both Properties are `phetioReadOnly: false`. 

If the client sets `profileNameProperty` to `'projector'`, then `projectorModeEnabledProperty` does not change to `true`.

**Comment by pixelzoom** [comment]
Top priority, this must be addressed before gas-properties begins testing.

**Comment by pixelzoom** [comment]
Top priority, this must be addressed before gas-properties begins testing.

**Comment by pixelzoom** [comment]
Proposal to address this issue.

(1) Add this field to `ColorProfile`, so that we can verify that it has 'projector' profile:

```js
// @public (read-only)
this.profileNames = profileNames;
```

(2) Change constructor of `ProjectorModeCheckBox` to include the ColorProfile, so that we can sync with it:

```js
/**
 * @param {ColorProfile} colorProfile
 * @param {Object} [options]
 */
constructor( colorProfile, options ) {
```

Add this assertion to `ProjectorModeCheckBox` constructor, to verify that the ColorProfile has a profile named 'projector':

```js
assert && assert( colorProfile.profileNames.indexOf( 'projector' ) !== -1, 'colorProfile must have projector profile' );
```

Add this in `ProjectorModeCheckBox` constructor, to sync projectorModeEnabledProperty with profileNameProperty.

```js
projectorModeEnabledProperty.link( projectorModeEnabled => {
  colorProfile.profileNameProperty.value = projectorModeEnabled ? 'projector' : 'default';
} );

colorProfile.profileNameProperty.link( profileName => {
  projectorModeEnabledProperty.value = ( profileName === 'projector' );
} );
```

**Comment by pixelzoom** [comment]
And yes, it would be nice not to be copying `'projector'` and `'default'` everywhere, but that's a more pervasive problem that this issue is not trying to solve.

**Comment by pixelzoom** [comment]
Here's how I'm currently working around this in Gas Properties, see `GasPropertiesGlobalOptionsNode`, the content for the Options dialog.

```js
      // Switch between default and projector color profiles.
      // This requires keeping 2 Properties in sync, a workaround for https://github.com/phetsims/joist/issues/569.
      GasPropertiesGlobalOptions.projectorModeEnabledProperty.link( projectorModeEnabled => {
        GasPropertiesColorProfile.profileNameProperty.set( projectorModeEnabled ? 'projector' : 'default' );
      } );
      GasPropertiesColorProfile.profileNameProperty.link( profileName => {
        GasPropertiesGlobalOptions.projectorModeEnabledProperty.value = ( profileName === 'projector' );
      } );
```

**Comment by pixelzoom** [comment]
Even simpler.... Make `projectorModeEnabledProperty` private to `ProjectorModeCheckBox`.  There's no need for it other than to pass to the Checkbox.  The client should only have to pass in a ColorProfile that has exactly 2 profiles, named 'default' and 'projector'.

**Comment by pixelzoom** [comment]
There are 8 sims that use `ProjectorModeCheckbox`.

**Comment by pixelzoom** [comment]
I did a rewrite of ProjectModeCheckbox and tested it in the context of Gas Properties.  It seems to work nicely.  And it looks relatively easy to modify in the other 13 sims that use ProjectModeCheckbox.

Here's the proposed rewrite of ProjectModeCheckbox:

<details>
<summary> ProjectModeCheckbox.js</summary>

```js
// Copyright 2018-2019, University of Colorado Boulder

/**
 * A checkbox that can be used to turn projector mode on and off.
 * This involves switch between 'default' and 'projector' color profiles.
 *
 * @author John Blanco
 * @author Chris Malley (PixelZoom, Inc.)
 */
define( require => {
  'use strict';

  // modules
  const BooleanProperty = require( 'AXON/BooleanProperty' );
  const Checkbox = require( 'SUN/Checkbox' );
  const joist = require( 'JOIST/joist' );
  const OptionsDialog = require( 'JOIST/OptionsDialog' );
  const Tandem = require( 'TANDEM/Tandem' );
  const Text = require( 'SCENERY/nodes/Text' );

  // strings
  const projectorModeString = require( 'string!JOIST/projectorMode' );

  /**
   * @param {ColorProfile} colorProfile - must have exactly 2 profiles, named 'default' and 'projector'
   * @param {Object} [options]
   */
  class ProjectorModeCheckbox extends Checkbox {

    constructor( colorProfile, options ) {

      assert && assert( colorProfile.profileNames.length === 2, 'colorProfile has the wrong number of profiles' );
      assert && assert( colorProfile.profileNames.indexOf( 'default' ) !== -1, 'colorProfile must have a default profile' );
      assert && assert( colorProfile.profileNames.indexOf( 'projector' ) !== -1, 'colorProfile must have a projector profile' );

      options = _.extend( {
        font: OptionsDialog.DEFAULT_FONT,
        maxTextWidth: 350, // empirically determined, works reasonably well for long strings
        tandem: Tandem.required
      }, options );

      // This is an internal adapter Property, not exposed via PhET-iO.
      const isProjectorModeProperty = new BooleanProperty( colorProfile.profileNameProperty.value === 'projector' );
      isProjectorModeProperty.link( isProjectorMode => {
        colorProfile.profileNameProperty.value = ( isProjectorMode ? 'projector' : 'default' );
      } );

      const profileNameListener = profileName => {
        isProjectorModeProperty.value = ( profileName === 'projector' );
      };
      colorProfile.profileNameProperty.link( profileNameListener );

      const label = new Text( projectorModeString, {
        font: options.font,
        maxWidth: options.maxTextWidth
      } );
      super( label, isProjectorModeProperty, options );

      // @private - dispose function
      this.disposeProjectorModeCheckbox = function() {
        colorProfile.profileNameProperty.unlink( profileNameListener );
      };
    }

    dispose() {
      this.disposeProjectorModeCheckbox();
      super.dispose();
    }
  }

  return joist.register( 'ProjectorModeCheckbox', ProjectorModeCheckbox );
} );
```

</details>

Here's a patch that includes the changes to ProjectorModeCheckbox, ColorProfile, and gas-properties:

<details>
<summary>patch</summary>

```
Index: gas-properties/js/phet-io/gas-properties-phet-io-elements-baseline.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- gas-properties/js/phet-io/gas-properties-phet-io-elements-baseline.js	(revision e33c4c44e015a5b8c11f0b07393310ecef52ad30)
+++ gas-properties/js/phet-io/gas-properties-phet-io-elements-baseline.js	(date 1563425792000)
@@ -6810,17 +6810,6 @@
       "phetioStudioControl": true,
       "phetioTypeName": "PropertyIO.<BooleanIO>"
     },
-    "gasProperties.global.options.projectorModeEnabledProperty": {
-      "phetioDocumentation": "Projector Mode is a color profile that is suitable for display on a classroom projector",
-      "phetioEventType": "model",
-      "phetioFeatured": false,
-      "phetioHighFrequency": false,
-      "phetioPlayback": false,
-      "phetioReadOnly": false,
-      "phetioState": true,
-      "phetioStudioControl": true,
-      "phetioTypeName": "PropertyIO.<BooleanIO>"
-    },
     "gasProperties.homeScreen.activeProperty": {
       "phetioDocumentation": "Indicates whether the screen is active.  For single-screen simulations, the screen is always active.",
       "phetioEventType": "model",
Index: gas-properties/js/common/view/GasPropertiesGlobalOptionsNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- gas-properties/js/common/view/GasPropertiesGlobalOptionsNode.js	(revision e33c4c44e015a5b8c11f0b07393310ecef52ad30)
+++ gas-properties/js/common/view/GasPropertiesGlobalOptionsNode.js	(date 1563425588000)
@@ -38,10 +38,10 @@
       const children = [];
 
       // Projector Mode checkbox
-      const projectorModeCheckbox = new ProjectorModeCheckbox( _.extend( {}, GasPropertiesConstants.CHECKBOX_OPTIONS, {
-        font: GasPropertiesConstants.CONTROL_FONT,
-        projectorModeEnabledProperty: GasPropertiesGlobalOptions.projectorModeEnabledProperty
-      } ) );
+      const projectorModeCheckbox = new ProjectorModeCheckbox( GasPropertiesColorProfile,
+        _.extend( {}, GasPropertiesConstants.CHECKBOX_OPTIONS, {
+          font: GasPropertiesConstants.CONTROL_FONT
+        } ) );
       children.push( projectorModeCheckbox );
 
       // Pressure Noise checkbox
@@ -58,15 +58,6 @@
       options.children = children;
 
       super( options );
-
-      // Switch between default and projector color profiles.
-      // This requires keeping 2 Properties in sync, a workaround for https://github.com/phetsims/joist/issues/569.
-      GasPropertiesGlobalOptions.projectorModeEnabledProperty.link( projectorModeEnabled => {
-        GasPropertiesColorProfile.profileNameProperty.set( projectorModeEnabled ? 'projector' : 'default' );
-      } );
-      GasPropertiesColorProfile.profileNameProperty.link( profileName => {
-        GasPropertiesGlobalOptions.projectorModeEnabledProperty.value = ( profileName === 'projector' );
-      } );
     }
   }
 
Index: gas-properties/js/common/GasPropertiesGlobalOptions.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- gas-properties/js/common/GasPropertiesGlobalOptions.js	(revision e33c4c44e015a5b8c11f0b07393310ecef52ad30)
+++ gas-properties/js/common/GasPropertiesGlobalOptions.js	(date 1563425690000)
@@ -19,13 +19,6 @@
 
   const GasPropertiesGlobalOptions = {
 
-    // @public
-    projectorModeEnabledProperty:
-      new BooleanProperty( phet.chipper.queryParameters.colorProfile === 'projector', {
-        tandem: optionsTandem.createTandem( 'projectorModeEnabledProperty' ),
-        phetioDocumentation: 'Projector Mode is a color profile that is suitable for display on a classroom projector'
-      } ),
-
     // @public
     pressureNoiseProperty:
       new BooleanProperty( GasPropertiesQueryParameters.pressureNoise, {
Index: joist/js/ProjectorModeCheckbox.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- joist/js/ProjectorModeCheckbox.js	(revision 9ea7dfdc8fe866f7aafd8e864ac6fbb06fc4fb64)
+++ joist/js/ProjectorModeCheckbox.js	(date 1563426141000)
@@ -1,9 +1,11 @@
 // Copyright 2018-2019, University of Colorado Boulder
 
 /**
- * a checkbox that can be used to turn projector mode on and off
+ * A checkbox that can be used to turn projector mode on and off.
+ * This involves switch between 'default' and 'projector' color profiles.
  *
  * @author John Blanco
+ * @author Chris Malley (PixelZoom, Inc.)
  */
 define( require => {
   'use strict';
@@ -20,53 +22,43 @@
   const projectorModeString = require( 'string!JOIST/projectorMode' );
 
   /**
+   * @param {ColorProfile} colorProfile - must have exactly 2 profiles, named 'default' and 'projector'
    * @param {Object} [options]
-   * @constructor
    */
   class ProjectorModeCheckbox extends Checkbox {
 
-    constructor( options ) {
+    constructor( colorProfile, options ) {
+
+      assert && assert( colorProfile.profileNames.length === 2, 'colorProfile has the wrong number of profiles' );
+      assert && assert( colorProfile.profileNames.indexOf( 'default' ) !== -1, 'colorProfile must have a default profile' );
+      assert && assert( colorProfile.profileNames.indexOf( 'projector' ) !== -1, 'colorProfile must have a projector profile' );
 
       options = _.extend( {
-
         font: OptionsDialog.DEFAULT_FONT,
         maxTextWidth: 350, // empirically determined, works reasonably well for long strings
-
-        // property that can be used for setting the projector mode, created below if not supplied
-        projectorModeEnabledProperty: null,
-
         tandem: Tandem.required
       }, options );
 
-      // Does this instance own projectorModeEnabledProperty?
-      const ownsProjectorModeEnabledProperty = !options.projectorModeEnabledProperty;
-
-      // superclass option that the client cannot set
-      assert && assert( options.phetioLinkProperty === undefined, 'ProjectorModeCheckbox sets phetioLinkProperty' );
-      options = _.extend( {
-        phetioLinkProperty: !ownsProjectorModeEnabledProperty
-      }, options );
-
-      // @public {BooleanProperty} - projector mode state, create one if not provided
-      const projectorModeEnabledProperty = options.projectorModeEnabledProperty ||
-                                           new BooleanProperty( phet.chipper.queryParameters.colorProfile === 'projector', {
-                                             tandem: options.tandem.createTandem( 'projectorModeEnabledProperty' )
-                                           } );
+      // This is an internal adapter Property, not exposed via PhET-iO.
+      const isProjectorModeProperty = new BooleanProperty( colorProfile.profileNameProperty.value === 'projector' );
+      isProjectorModeProperty.link( isProjectorMode => {
+        colorProfile.profileNameProperty.value = ( isProjectorMode ? 'projector' : 'default' );
+      } );
+
+      const profileNameListener = profileName => {
+        isProjectorModeProperty.value = ( profileName === 'projector' );
+      };
+      colorProfile.profileNameProperty.link( profileNameListener );
 
       const label = new Text( projectorModeString, {
         font: options.font,
         maxWidth: options.maxTextWidth
       } );
-      super( label, projectorModeEnabledProperty, options );
-
-      // @public {BooleanProperty} - make the projector mode enabled property available to clients
-      this.projectorModeEnabledProperty = projectorModeEnabledProperty;
+      super( label, isProjectorModeProperty, options );
 
       // @private - dispose function
       this.disposeProjectorModeCheckbox = function() {
-        if ( ownsProjectorModeEnabledProperty ) {
-          projectorModeEnabledProperty.dispose();
-        }
+        colorProfile.profileNameProperty.unlink( profileNameListener );
       };
     }
 
Index: scenery-phet/js/ColorProfile.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- scenery-phet/js/ColorProfile.js	(revision 65a06e1e98288bdf9eb11c50f7ece2591e65230e)
+++ scenery-phet/js/ColorProfile.js	(date 1563425647000)
@@ -75,6 +75,9 @@
   function ColorProfile( profileNames, colors ) {
     var self = this;
 
+    // @public (read-only)
+    this.profileNames = profileNames;
+
     // @public {Property.<string>}
     // The current profile name. Change this Property's value to change which profile is currently active.
     // 'default' will use all default colors, and 'projector' is a common color profile that is also used.
```

</details>

**Comment by samreid** [comment]
I don't know all the context for this, but it seems like part of the solution is like a bidirectional version of `DerivedProperty.valueEquals`.  Not sure if we can build one of those using `DynamicProperty` or not.  Or even if there is common code to support this kind of mapping, maybe the proposed implementation is clearest, I'm not sure.

**Comment by pixelzoom** [comment]
I started down the path of using `DynamicProperty`, but it seemed unnecessary complicated and obfuscating.  And contrary to the code comment, we will probably need to instrument the internal `isProjectorModeProperty` because I believe Checkbox requires it to be instrumented,.

**Comment by samreid** [comment]
We agreed this is going in a good direction.  After this is committed and complete, @pixelzoom will reassign to @jbphet for review.

**Comment by pixelzoom** [comment]
A couple of changes from `ProjectorModeCheckbox` API proposal in https://github.com/phetsims/joist/issues/569#issuecomment-512665977 were necessary:

(1) I had to add `options.defaultColorProfileName`, since molecule-shapes-basics uses a specific profile ('basics') as its default.

(2) I instrumented internal Property `projectorModeEnabledProperty` because Checkbox expects its associated Property to be instrumented.  This means that PhET-iO will typically expose both `projectorModeEnabledProperty` and ColorProfile's `profileNameProperty`, but now they will stay synchronized.

Assigning to @jbphet for review, since he was the original author of `ProjectorModeCheckbox`. Let me know if you have any questions.

**Comment by pixelzoom** [comment]
I just realized that @jbphet unavailable until 7/29/19, and this should really be reviewed with high priority.  @samreid since you had a look at the proposal, would you mind reviewing?  If you don't have time, feel free to assign to @ariel-phet.

**Comment by pixelzoom** [comment]
Please ignore the commit between this comment and the previous comment.  They were incorrectly associated with this issue, and are for https://github.com/phetsims/joist/issues/568.

**Comment by pixelzoom** [comment]
This is block-publication because it should be reviewed before Gas Properties starts RC testing.

**Comment by pixelzoom** [comment]
7/25/19 dev meeting: assigned to @jessegreenberg to review with high priority. (Thanks!)

**Comment by jessegreenberg** [comment]
Changes to ProjectorModeChecbox look great. I skimmed through the sim commits, they look reasonable too.

> I had to add options.defaultColorProfileName, since molecule-shapes-basics uses a specific profile ('basics') as its default.

I understand why it was added but think it would be better without this. Shoudl we change `MoleculeShapesColorProfile` (use `basics` colors as `default` colors in a new `MoleculeShapesBasicsColorProfile`) instead of changing the API?

> I instrumented internal Property projectorModeEnabledProperty because Checkbox expects its associated Property to be instrumented.

Could the new Tandem.optOut (https://github.com/phetsims/tandem/issues/97) be used for this?

I noticed a bug in the colors of molecule-shapes-basics. I loads with what looks like the color profile of molecule-shapes (regular). Then just opening the OptionsDialog changes the color profile. Unsure if the bug is related to this issue or https://github.com/phetsims/joist/issues/568.

I quickly reviewed the other sims and they are all working well.

**Comment by pixelzoom** [comment]
Thanks for the feedback @jessegreenberg.

>  Should we change `MoleculeShapesColorProfile` (use basics colors as default colors in a new `MoleculeShapesBasicsColorProfile`) instead of changing the API?

The 'projector' profile for the 2 sims is currently identical.  So if we do what you've proposed, then `MoleculeShapesColorProfile` and `MoleculeShapesBasicsColorProfile` will duplicate colors for the 'projector' profile, and keeping them in sync would require changing both ColorProfile subclasses.   That said, I prefer the current solution.  It would be good to get @jonathanolson's input, since he's the author of `MoleculeShapesColorProfile`.

> Could the new Tandem.optOut (phetsims/tandem#97) be used for this?

The issue is not that Property requires a tandem.  The issue is that Checkbox expects its associated Property to be instrument so that it can create a linked element.   I don't agree with that expectation, so I've created  https://github.com/phetsims/sun/issues/518.

That said, I chose not to address the Checkbox problem, and instrumented `projectorModeEnabledProperty`.   But the decision about whether to instrument `projectorModeEnabledProperty` is ultimately up to designers, so I've created https://github.com/phetsims/joist/issues/572.

> I noticed a bug in the colors of molecule-shapes-basics. ...

Thanks, I'll investigate.

**Comment by pixelzoom** [comment]
molecule-shapes-basics bug is addressed in the above commit.  @jessegreenberg please verify.

**Comment by jessegreenberg** [comment]
Thanks for clarifying in https://github.com/phetsims/joist/issues/569#issuecomment-515794317. I just tested molecule-shapes-basics and confirmed that the issue has been fixed.

**Comment by pixelzoom** [comment]
Thanks @jessegreenberg.

I just discovered that there's more work for me to do here.  After these changes, the `colorProfile` query parameter, used to specify the profile used on startup, is being ignored.

**Comment by pixelzoom** [comment]
Support for the `colorProfile` query parameter is restored in the above 2 commits.  You can test a sim that has a ColorProfile (blackbody-spectrum, gas-properties,...) using `?colorProfile=projector`.  

For molecules-shapes-basics, I restored it's behavior to what it was before ProjectorModeCheckbox changes.  That is, it recognizes `?colorProfile=projector`, but silently ignores anything else.    This demonstrates the complication with having a sim that uses something other than 'default' as it's default color profile, and I've create https://github.com/phetsims/molecule-shapes-basics/issues/13 to continue discussion of that issue.

@jessegreenberg one more review please, thanks!

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/scenery-phet/commit/589f1bd24feec9c49b5415b3d7bc5d7322b2f7ab Looks good. I tested ?projectorMode on a few sims including molecule-shapes-basics, it is working as expected. Good catch.

**Comment by pixelzoom** [comment]
Thanks @jessegreenberg.

Remaining questions are being tracked in separate GitHub issues, so I'll close this one.

**Comment by pixelzoom** [comment]
@jessegreenberg said:
> ...  I tested ?projectorMode on a few sims ...

I just noticed this.  There is no `?projectorMode`, so I'm assuming that you meant `?colorProfile=projector`.   Is that correct?

**Comment by jessegreenberg** [comment]
Yep, sorry, that is totally what I meant.
