### ISSUE TITLE
Touch fuzzer should be implemented

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#57]
Will be useful for catching multi-touch bugs

**Comment by pixelzoom** [comment]
@jonathanolson status?

**Comment by jonathanolson** [comment]
Not done yet, please leave open.

**Comment by pixelzoom** [comment]
@jonathanolson status?

**Comment by jonathanolson** [comment]
Status is "hasn't reached a high enough priority level, and we haven't implemented the robust multi-touch handling yet".

**Comment by pixelzoom** [comment]
@jonathanolson Didn't you implement this recently?

**Comment by jonathanolson** [comment]
Yup, closing.
