### ISSUE TITLE
standards for ScreenView margins

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#571]
Over in https://github.com/phetsims/acid-base-solutions/issues/160, we discovered that the pH probe was a bit too close to the top of the screen, making it difficult to select on iPhone. 

As noted in that issue, I would be nice to have some standards for margins, since this is a general problem.   I've noticed that several sims put things much closer to the edges of the screen than I think is safe or esthetically pleasing.  

Assigning to @ariel-phet to prioritize and assign.

**Comment by ariel-phet** [comment]
I think enforcing such standards does not actually make sense to do programmatically as we have some sims (like Energy Forms and Changes) where it makes sense for items to be close to, or violate the border. 

@pixelzoom always feel free to make a sim specific issue if you notice something you think should be polished and assign me. But I do not actually think this is a general issue we currently need to solve or address in some systemic way. 

Closing
