### ISSUE TITLE
should ProjectorModeCheckbox projectorModeEnabledProperty be instrumented?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#572]
Creating this issue based on feedback by @jessegreenberg in https://github.com/phetsims/joist/issues/569#issuecomment-515250918.

There are 2 Properties associated with the "Projector Mode" checkbox that typically appears in the Options dialog for a sim that has this feature. 

The first Property is `profileNameProperty`, the name of the selected ColorProfile.  The choices are typically "default" or "projector", and it's presented as a pair of radio buttons in Studio.   For example, for Gas Properties:

<img width="556" alt="screenshot_1292" src="https://user-images.githubusercontent.com/3046552/62012558-2d288200-b145-11e9-83b1-a90633dde280.png">

The second Property is internal to `ProjectorModeCheckbox`, a joist common-code component.  It maps `profileNameProperty` to a boolean value, as required by Checkboxes in general.  It currently doesn't appear in Studio because of lack of support for dynamic elements (Options dialog is created on demand).   When it does appear, it will look like a typical Checkbox in Studio, featured by default.  In Gas Properties, it's phetioID would be:

`gasProperties.general.navigationBar.phetButton.phetMenu.optionsDialog.content.projectorModeCheckBox.projectorModeEnabledProperty`

The question is whether to instrument `projectorModeEnabledProperty`.  It is sufficient to instrument `profileNameProperty`, and `projectorModeEnabledProperty` is an internal implementation detail.  If instrumented, it would be as a convenience, at the expense of exposing internals of `ProjectorModeCheckbox`.  

`projectorModeEnabledProperty` is currently instrumented, because Checkboxes expect their associated Property to be instrumented (so that they can create a linked element).  If that's not desired, we'll need to investigate how to get around that -- a good thing to do, since I don't think that's a valid expectation.

Since this came up in the context of Gas Properties PhET-iO design https://github.com/phetsims/gas-properties/issues/30, assigning to @arouinfar.

**Comment by zepumph** [comment]
This was instrumented and design reviewed in https://github.com/phetsims/joist/issues/654. 

Current implementation: https://github.com/phetsims/joist/blob/676449add44cad62cce105d763bbccd3f048c73b/js/ProjectorModeCheckbox.js#L54-L56
