### ISSUE TITLE
How to handle conditionally created sound button for PhET-iO

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#573]
While working on https://github.com/phetsims/phet-io/issues/1454 @chrisklus and I were looking at this code in AllyButtonsHBox.js:

```js
    // only put the sound on/off button on the nav bar if the sound library is enabled
    // TODO: Support instrumented element that is dynamic/lazily created, see https://github.com/phetsims/phet-io/issues/1454
    if ( sim.supportsSound ) {
      var soundOnOffButton = new NavigationBarSoundToggleButton(
        soundManager.enabledProperty,
        backgroundColorProperty,
        Tandem.optional
        // tandem.createTandem( 'soundOnOffButton' )
      );
      a11yButtons.push( soundOnOffButton );
    }
```

For PhET-iO, we would like to always create and instrument this button if the sim supports sound. However `sim.supportsSound` also includes other information from query parameters and is described as:
`// true if the simulation supports sound and sound is enabled`

We therefore recommend renaming `sim.supportsSound` to something that also indicates sound is enabled.  Maybe something like `sim.isSoundEnabled`.  Then adding `sim.supportsSound` to match the value specified in the Sim options.  Presumably `supportsEnhancedSound` would change as well.

At a minimum, we need a way to access the Sim constructor option `supportsSound` before it gets mutated by query parameters.

@jbphet can you please take a look?

**Comment by jbphet** [comment]
> @jbphet can you please take a look?

I'd strongly prefer not to rename this.  The parameter has some history, see:
+ https://github.com/phetsims/tambo/issues/11
+ https://github.com/phetsims/tambo/issues/26
+ https://github.com/phetsims/tambo/issues/47

> At a minimum, we need a way to access the Sim constructor option supportsSound before it gets mutated by query parameters.

I don't think that this setting should be instrumented for phet-io at all.  It exists to support the situation where we have a sim with some partially developed sound, but we don't want it to be enabled or even have the tambo library running most of the time - we just want to turn it on for testing and development.  Once sound is fully developed for a sim, the value of the `supportsSound` field is set to true in the options hash that is provided to the `Sim` constructor, and the query parameter is subsequently ignored.  No one outside of PhET should ever be messing with this.

There **is** a query parameter for setting the state of sound in a sim that supports sound, and allows sound to be fully disabled (such that the mute button doesn't appear), muted at load time, or enabled (the default).  That may be more what you're looking for.

**Comment by samreid** [comment]
To clarify on the problem, the simulation will throw a validation error if it doesn't create all of the components specified in its PhET-iO API.  If the API specifies that a `NavigationBarSoundToggleButton` will exist, then the simulation should create it.  Our idea is that if a query parameter disables sound, the `NavigationBarSoundToggleButton` will still be created but just not added to the scene graph.  So we need to know whether the sim supports sound independently of whether it has been disabled via query parameter.  How do you recommend to proceed?

**Comment by jbphet** [comment]
It seems a bit limiting and inflexible to require the creation of a component that we don't need in support of an API spec that will be describing something that can't be manipulated.  In the code snippet above, there is a TODO item that says:

```
// TODO: Support instrumented element that is dynamic/lazily created, see https://github.com/phetsims/phet-io/issues/1454
```

The GitHub issue referenced in that comment is long, so I didn't read it all, but it seems to me that support for dynamically created elements is exactly what's needed in this case.  If that's not doable, or doesn't apply here for some reason, then I'd say just create the thing but don't add it, though I find that pretty distasteful.  In other words:

```js
      var soundOnOffButton = new NavigationBarSoundToggleButton(
        soundManager.enabledProperty,
        backgroundColorProperty,
        Tandem.optional,
        tandem.createTandem( 'soundOnOffButton' )
    );
    if ( sim.supportsSound ) {
      a11yButtons.push( soundOnOffButton );
    }
```

**Comment by samreid** [comment]
Thanks for discussing this @jbphet, I noted your remarks in https://github.com/phetsims/phet-io/issues/1454 and we'll discuss further.

**Comment by zepumph** [comment]
This issue is largely overlapping https://github.com/phetsims/phet-io/issues/1457, and there is a TODO in that block in code pointing over to that issue. We will unassign here and mark on hold for now, and see what we come up with over there!

**Comment by samreid** [comment]
From today's discussion, we would like to create the sound buttons based on whether `supportsSound` is true in package.json.  We will determine whether to show the buttons depending on whether `sim.SupportsSound` is true.  @zepumph will work on this as part of https://github.com/phetsims/phet-io/issues/1457

**Comment by zepumph** [comment]
>@zepumph will work on this as part of phetsims/phet-io#1457

Right! Commits are over there are out for review. Closing.
