### ISSUE TITLE
Should ResetAllButton be factored out and renamed?

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#574]
We currently have 115 occurrences of `new ResetAllButton` and we have a policy that each `ScreenView` will create exactly one `ResetAllButton`.  We also would like each screen to create its reset button with a specific tandem name `resetAllButton` so this code is getting copied many places:

```
tandem: tandem.createTandem( 'resetAllButton' )
```

Also, I don't see any reason that `ResetAllButton` shouldn't just be wired up to automatically call `Screen.reset` and `ScreenView.reset`.

Also, perhaps we should rename it `ResetScreenButton` since that is how it should be used.

If the z-order is important, we could leave it to the child type to call `addChild`.

* guarantee that each screen has a resetAllButton
* factor out duplicated code, prevent typos without needing assertions
* guarantee that tandem names and structures are uniform across screens and sims
* central point to listen for when a screen is reset for https://github.com/phetsims/phet-io-wrappers/issues/296, rather than heuristics

Assigning to @zepumph for initial discussion.

**Comment by zepumph** [comment]
I think this makes a lot of sense. Perhaps the next step is to mark for developer meeting to see if others think this is a reasonable refactor.

**Comment by samreid** [comment]
> If the z-order is important, we could leave it to the child type to call addChild.

It seems the default should be to add the child to the back, since other tools and things should be dragged in front of it.  It some particular screenView needs the ResetScreenButton elsewhere in the z-order, it can call `moveToFront` or equivalent.

**Comment by pixelzoom** [comment]
This proposal assumes that all Screens have a  ResetAllButton, and that is not the case.  Game screens often don't have a ResetAllButton at all, or (as @jessegreenberg and @jonathanolson noted above) the use of the ResetAllButton is a bit different.  My vote is to leave as is.

**Comment by Denz1994** [comment]
Discussed at dev meeting: 09/19/19

We will not proceed with the factor due to the concerns brought up by @jessegreenberg, @jonathanolson and @pixelzoom. The edge cases described above warrant no further action for this issue.

Also discussed: ResetAllButton refers to all reset actions on the specific screen, not the scene. This works as a Tandem name for phet-io.

**Comment by pixelzoom** [comment]
> Also, I don't see any reason that ResetAllButton shouldn't just be wired up to automatically call Screen.reset and ScreenView.reset.

Addressed in https://github.com/phetsims/simula-rasa/commit/0d63bcb4e2953d8f45204d5068089cb50be5b8a5, by adding to simula-rasa template.
