### ISSUE TITLE
Home screen buttons shift

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/joist#575]
The first time you click a new icon on the home screen of a sim the icons shift a bit.  Not big and it's in published.
![firsttimeshifts](https://user-images.githubusercontent.com/41024075/65191264-a00cf580-da30-11e9-9d3a-fee2eb4699d3.gif)

**Comment by ariel-phet** [comment]
@KatieWoe I am not seeing this on recently published sims (like gas properities), I am guessing Build an Atom just has an old version of Joist. Are you seeing this on any recently published sims?

**Comment by zepumph** [comment]
This issue is outdated. I'm going to close this
