### ISSUE TITLE
iOS 13 Screen shifts down after closing tab next to sim but pointer areas does't

### ISSUE THREAD

**Issue by megan-phet** [phetsims/joist#577]
<b>Test Device</b>
- iPad (6th generation)

<b>Operating System</b>
- iOS 13.1

<b>Browser</b>
- Safari

<b>Problem Description</b>
For phetsims/QA#429

Screen shifts down after closing the tab next to it but pointer areas do not change.
(Need to click above the object or icon intended to select.)

Tried on iPad pro-OS 12.4.1 and the screen jumps back to the original place after closing the tab next to it.

<b>Steps to Reproduce</b>
- Only works when the new tab is opened within the sim and without any tabs in between.
- Issue in all sims on iOS 13
1. Go to the PhET website from the sim or click on Report a Problem.
2. Close the website tab next to the simulation tab.

<b>Visuals</b>

![Uploading Kapture 2019-09-30 at 11.17.24.gif…]()

<details>
<summary><b>Troubleshooting Information</b></summary>
!!!!! DO NOT EDIT !!!!!
Name: ‪Gravity Force Lab: Basics‬
URL: https://phet-dev.colorado.edu/html/gravity-force-lab-basics/1.0.0-rc.1/phet/gravity-force-lab-basics_all_phet.html
Version: 1.0.0-rc.1 2019-09-17 19:49:09 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15
Language: en-US
Window: 1321x734
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jessegreenberg** [comment]
Thanks @megan-phet - it looks like the gif visual didn't quite upload all the way, could you please try that again? It might be hlepful to see.

**Comment by megan-phet** [comment]
Yep, here you go.

![Kapture 2019-09-30 at 11 17 24](https://user-images.githubusercontent.com/40698031/65907971-a41b0a80-e382-11e9-8f54-b89f963a0dbd.gif)

**Comment by jessegreenberg** [comment]
Thanks @megan-phet that is helpful, I will try to produce on my end. Probably an issue for all sims, but there is a chance it is caused by the PDOM.

**Comment by jonathanolson** [comment]
I just built a version of a sim that tries to resize every frame. Can you test https://phet-dev.colorado.edu/olsonjb/resizer.html to see if it has the same problem?

**Comment by megan-phet** [comment]
It still has the same problem @jonathanolson.

**Comment by jonathanolson** [comment]
The fact that it's happening with the above HTML means it's unlikely something I can directly "fix" on our sim side (and Safari is reporting the wrong width/height).
