### ISSUE TITLE
UpdateCheck does not meet code standards

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#578]
While working on https://github.com/phetsims/perennial/issues/111, I found a fair number of improvements I would like to make along the way.

* Faulty documentation
* in es5
* some local fields that should be constants
* `stateProperty` should be and EnumerationProperty
* It's a singleton with incorrect capitalization, and usages should be updated too.

**Comment by zepumph** [comment]
In the above commits I . . . 
 * converted the file to es6
 * factored out `stateProperty` values to an Enumeration called `UpdateState`
 * refactored items that had incorrect visibility for their purpose (some fields moved to constants, and some just got updated annotations)
 * Converted the file to be named like a singleton (lowerCaseCamelCase) and updated usages
 * Found and fixed a few bugs in usages where `stateProperty` was being directly compared, instead of `stateProperty.value`, like `stateProperty === 'up-to-date'`.
 * Made it more explicit as to the api of the update checking website service, and how to keep those in sync

@pixelzoom please review these changes in correlation to https://github.com/phetsims/perennial/issues/111

**Comment by pixelzoom** [comment]
I skimmed the changes, and I don't see anything obviously amiss.  But I'm not very familiar with `updateCheck`, so you might want to have @jonathanolson (author) review.

**Comment by jonathanolson** [comment]
Looks good to me!
