### ISSUE TITLE
Win 7 appears to slightly cut off the bottom of the sim when using a second screen

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/joist#579]
Seen all sims, all 3 supported Win 7 browsers (Chrome, IE, FF)

When the browser window is maximum, AND the browser window is being viewed on a second screen (the one without the task bar), the bottom of the browser window slightly overlaps the navbar. Only observable on my desktop where I am using two screens, but I am concerned this issue could potentially show up on interactive whiteboards or projector situations or such. Not a high priority, but I did want to document. I believe @samreid saw something similar.

![cutoff](https://user-images.githubusercontent.com/4051174/65921117-8f4c7000-e39e-11e9-9bb2-522a17f64e45.PNG)

**Comment by samreid** [comment]
I have a vague memory about something like this happening in the past.  I tried to reproduce the problem on my Mac OS 10.14.6 and Win 10 Pro, using laptop as primary display and external monitor as extended desktop, and didn't see it in either case.

**Comment by ariel-phet** [comment]
I am seeing this problem when using zoom as well. Seems to be a general issue out of our control. Closing
