### ISSUE TITLE
rename supportsTouchA11y-> supportsGestureA11y

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#583]
@jessegreenberg and @terracoda and I have been trying to specific this particular feature support of mobile VO + iOS as gesture instead of touch, as it feels a bit more specific.

**Comment by zepumph** [comment]
@jessegreenberg please review. Feel free to close if you don't have any thoughts.

**Comment by jessegreenberg** [comment]
Sounds great, thanks.
