### ISSUE TITLE
Problems with menu item options

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#590]
From https://github.com/phetsims/phet-io/issues/1585, we are working on component options in this file again.

I found that all component options are marking `phetioState:false`, this means that studio is not able to pass that customization to the "launched sim". I don't know why we originally did that, but I don't think it should stick around.

**Comment by zepumph** [comment]
After more investigation, here is what I would like to do for this issue:

* MenuItem should be phetioState:false by default
* The we can remove all the usages of setting those in PhetMenu.
* Remove phetioState:false from component options. This is prohibiting customization support and I don't know why it is the case. The best I found for the change for the about dialog takes me to https://github.com/phetsims/joist/commit/03a0edee5eea409eb95db993a39a36f3531f2b4e and https://github.com/phetsims/phet-io/issues/1420, but I defer to @samreid if it makes more sense to keep it the way it is now.
* The way that the "itemDescriptors" are handled is very bizarre, and I think it could be simpler if all the "options" passed to MenuItem were under an "options" key, so that they didn't have to be plucked from the itemDescriptor object.

**Comment by zepumph** [comment]
Basically this issue accomplished two things:

* Removing `phetioState:false` from component options fixed a bug where PhET-iO customization was broken for menu items (hiding one and then launching studio would not keep it hidden).
* Simplify, organize, remove duplication, and document options being passed to MenuItem. 
  * `phetioState:false` was duplicated in descriptors and is covered by Node.js
  * `tagName: 'button'` was duplicated in descriptors and is covered by MenuItem.js
  * Add defaults to options used in MenuItem
  * In item descriptors specify all options in the `options` key instead of at the top level, simplifying the creation of MenuItems (where `new MenuItem(. . .` is called.

@samreid please review these mostly non-phet-io changes. Thanks!

**Comment by samreid** [comment]
I reviewed the commits and did not see any problems to report.  https://github.com/phetsims/joist/commit/af56fb20ea1c499e77552d5f2cf34e434a5b3c81 looked particularly good, thanks!  Closing.
