### ISSUE TITLE
Only PhET-iO instrument soundEnabledProperty if there is sound in the sim?

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#591]
From https://github.com/phetsims/phet-io/issues/1585:

>We were not sure why `gravityAndOrbits.general.soundEnabledProperty` was present since this sim did not have sound? Also, documentation was needed.

We should probably just not have it instrumented unless sound is enabled. That is acceptable and supported with PhET-iO because that will never change for the whole "platform" of a published sim. Once it is on, it is always on.

@samreid do you agree? Is it best to instrument conditionally?

**Comment by samreid** [comment]
I'm not sure.  Our long-term plan is that sims will have sound effects, so maybe it makes sense to put this as a placeholder even though it doesn't do anything for quiet sims at the moment, to keep the code simpler and more uniform.

For instance, faraday's law is a one-screen sim, but it still has `faradaysLaw.general.screenIndexProperty`.  Let's say the designers reviewed faraday's law and said that property doesn't need to be instrumented because it is a one-screen sim.  Would we uninstrument that too?  Let's discuss.

**Comment by zepumph** [comment]
Let's get some design time for this tomorrow.

**Comment by zepumph** [comment]
We can add phetioDocumentation to this that says "if the sim contains sound. . . ", but we will not conditionally instrument this.

**Comment by samreid** [comment]
@kathy-phet also pointed out that the sound icon button in the navigation bar should have a LinkedElement for the soundManager.enabledProperty.

**Comment by zepumph** [comment]
>@kathy-phet also pointed out that the sound icon button in the navigation bar should have a LinkedElement for the soundManager.enabledProperty. 

This was done as part of https://github.com/phetsims/joist/issues/597

Also over in https://github.com/phetsims/phet-io/issues/1457 we created `sim.soundPartOfAPI` as a boolean to check against whether or not to instrument the soundToggleButton, so I think we can use the same thing here.

**Comment by zepumph** [comment]
https://github.com/phetsims/joist/issues/591#issuecomment-565151726 was completed above with the addition of documentation. We decided not to conditionally instrument it, so `Sim.soundPartOfAPI` is not needed. Adding that would be difficult since soundManager is a singleton, and its enabledProperty is created before the sim has been constructed. I like the current solution. @chrisklus please review.

**Comment by chrisklus** [comment]
I made small doc changes above. What is `phet.isWrapper`? I can't find any other usages of `isWrapper`.

**Comment by zepumph** [comment]
I created https://github.com/phetsims/chipper/issues/942. Closing
