### ISSUE TITLE
error dialog for invalid query parameter value

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#593]
In 12/12/19 design meeting for Natural Selection, we identified a need to have a dialog open when a query parameter value is incorrect.   This is important because we're making query parameters available to users (e.g. teachers) who will not have a console open, and will therefore not see an error. 

Also note that query parameters should not be validate using `assert`.  They should throw `Error`.  Some query parameters, like `initialScreen`, result in bizarre behavior when given invalid values without `?ea`.

**Comment by jonathanolson** [comment]
Do we need a general way of catching and showing errors without going to the console? Are you proposing something in general for this, or asking what should be done?

**Comment by pixelzoom** [comment]
That is what has been requested, by @kathy-phet specifically.

**Comment by pixelzoom** [comment]
That is what has been requested, by @kathy-phet specifically.   This issue addresses getting determining priority and getting it done.

**Comment by chrisklus** [comment]
I'm up to work on this if we need a volunteer!

**Comment by pixelzoom** [comment]
12/19/19 dev meeting:

* Public-facing query parameters should not be validated using assertions. They need to `throw Error` if value is invalid. 
* First thing to do might be to warn to console, then revert to the default value when an invalid value is provided.  @chrisklus will do this part. 
* The modal dialog is more user-friendly, and would be something similar to the "WebGL required" dialog.  It would identify the incorrect query parameter that is being ignored, and the sim still comes up. @pixelzoom will collaborate with @chrisklus on this part, since it's needed for Natural Selection.

**Comment by pixelzoom** [comment]
@chrisklus I have no urgent need for this (May timeframe would be fine).  It sounds like you'll need it for EFAC sooner.  Let me know when you'd like to collaborate on this, anytime after 1/1/2020.

**Comment by chrisklus** [comment]
>First thing to do might be to warn to console, then revert to the default value when an invalid value is provided. @chrisklus will do this part. 

I addressed this item in the commit above. @samreid helped me get started and then assisted again when I had some questions, so assigning to him for review.

There is a new schema key `isGraceful` that can be added to public query parameters. This way, internal query parameters can still throw errors for PhET developers, but public query parameters can just warn in the console and revert to default values. I added the key to the appropriate usages in EFAC and Natural Selection.

Here is a simple patch for starting next steps with @pixelzoom.

<details>

```diff

Index: js/Sim.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/Sim.js	(revision d95daf0fd7f6c31c110ec1f7c0ac1c1f02a41358)
+++ js/Sim.js	(date 1577144895000)
@@ -19,6 +19,7 @@
   const BooleanProperty = require( 'AXON/BooleanProperty' );
   const Bounds2 = require( 'DOT/Bounds2' );
   const Brand = require( 'BRAND/Brand' );
+  const Dialog = require( 'SUN/Dialog' );
   const Dimension2 = require( 'DOT/Dimension2' );
   const Display = require( 'SCENERY/display/Display' );
   const DotUtil = require( 'DOT/Util' );// eslint-disable-line
@@ -48,6 +49,7 @@
   const soundManager = require( 'TAMBO/soundManager' );
   const Tandem = require( 'TANDEM/Tandem' );
   const timer = require( 'AXON/timer' );
+  const Text = require( 'SCENERY/nodes/Text' );
   const updateCheck = require( 'JOIST/updateCheck' );
   const Util = require( 'SCENERY/util/Util' );
 
@@ -772,6 +774,23 @@
       // @public (joist-internal)
       // Bind the animation loop so it can be called from requestAnimationFrame with the right this.
       this.boundRunAnimationLoop = this.runAnimationLoop.bind( this );
+
+      // show any query parameter warnings in a dialog
+      if ( QueryStringMachine.warnings.length ) {
+        let warningString = '';
+        QueryStringMachine.warnings.forEach( warning => {
+          warningString += JSON.stringify( warning );
+        } );
+
+        const warningDialog = new Dialog( new Text( warningString ), {
+          title: new Text( 'Warning' ),
+          closeButtonListener: () => {
+            this.hidePopup( warningDialog, true );
+          }
+        } );
+
+        this.showPopup( warningDialog, true );
+      }
     },
 
     /*


```

</details>

**Comment by samreid** [comment]
I looked through the proposal and had recommendations and questions which I wrote in this patch:

<details>

```diff

Index: js/QueryStringMachine.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/QueryStringMachine.js	(revision 9d9b49e390f0cb303f6f96603de8889d5dd43985)
+++ js/QueryStringMachine.js	(date 1577155118411)
@@ -69,7 +69,7 @@
      * visit PhET's <a href="https://github.com/phetsims/query-string-machine" target="_blank">query-string-machine</a>
      * repository for documentation and examples.
      */
-    var QueryStringMachine = {
+    const QueryStringMachine = {
 
       // @public {{key:string, message:string, value:{*}, defaultValue:{*}}[]}
       warnings: [],
@@ -118,9 +118,7 @@
 
         validateSchema( key, schema );
         const value = parseValues( key, schema, values );
-        const validatedValue = validateValue( key, schema, value );
-
-        return validatedValue === undefined ? value : validatedValue;
+        return validateValue( key, schema, value );
       },
 
       /**
@@ -326,7 +324,7 @@
      * @param {string} string - the parameters string
      * @returns {Array.<string|null>} - the resulting values, null indicates the query parameter is present with no value
      */
-    var getValues = function( key, string ) {
+    const getValues = function( key, string ) {
       const values = [];
       const params = string.slice( 1 ).split( '&' );
       for ( let i = 0; i < params.length; i++ ) {
@@ -352,7 +350,7 @@
      * @param {string} key - the query parameter name
      * @param {Object} schema - schema that describes the query parameter, see QueryStringMachine.get
      */
-    var validateSchema = function( key, schema ) {
+    const validateSchema = function( key, schema ) {
 
       // type is required
       queryStringMachineAssert( schema.hasOwnProperty( 'type' ), key, 'type field is required' );
@@ -430,7 +428,7 @@
      * @param {string[]} requiredProperties - properties that the schema must have
      * @param {string[]} optionalProperties - properties that the schema may optionally have
      */
-    var validateSchemaProperties = function( key, schema, requiredProperties, optionalProperties ) {
+    const validateSchemaProperties = function( key, schema, requiredProperties, optionalProperties ) {
 
       // {string[]}, the names of the properties in the schema
       const schemaProperties = Object.getOwnPropertyNames( schema );
@@ -456,39 +454,30 @@
      * @param {string} key - the query parameter name
      * @param {Object} schema - schema that describes the query parameter
      * @param {*} value - type depends on schema type
+     * @returns {*} the validated value, or an alternate valid value if the value was not validated
      */
-    var validateValue = function( key, schema, value ) {
-      let defaultValue = null;
+    const validateValue = function( key, schema, value ) {
 
       // value is a member of validValues
       if ( schema.hasOwnProperty( 'validValues' ) ) {
-        const errorMessage = 'value must be a member of validValues: ';
-        if ( !schema.isGraceful ) {
-          queryStringMachineAssert( isValidValue( value, schema.validValues ),
-            key, errorMessage + value );
-        }
-        else if ( !isValidValue( value, schema.validValues ) ) {
-          defaultValue = schema.defaultValue;
-          QueryStringMachine.addWarning( key, errorMessage, value, defaultValue );
+        const ok = isValidValue( value, schema.validValues );
+        queryStringMachineAssert( ok, key, 'value must be a member of validValues: ' + value, schema.isGraceful );
+        if ( !ok && schema.isGraceful ) {
+          value = schema.defaultValue;
         }
       }
 
       // isValidValue evaluates to true
       if ( schema.hasOwnProperty( 'isValidValue' ) ) {
-        const errorMessage = 'invalid value: ';
-        if ( !schema.isGraceful ) {
-          queryStringMachineAssert( schema.isValidValue( value ), key, errorMessage + value );
-        }
-        else if ( !schema.isValidValue( value ) ) {
-          defaultValue = schema.defaultValue;
-          QueryStringMachine.addWarning( key, errorMessage, value, defaultValue );
+        const ok = schema.isValidValue( value );
+        queryStringMachineAssert( ok, key, 'invalid value: ' + value, schema.isGraceful );
+        if ( !ok && schema.isGraceful ) {
+          value = schema.defaultValue; // TODO: https://github.com/phetsims/joist/issues/593 what if no defaultValue is provided?
         }
       }
 
       // dispatch further validation to a type-specific function
-      value = TYPES[ schema.type ].validateValue( key, schema, value );
-
-      return defaultValue || value;
+      return TYPES[ schema.type ].validateValue( key, schema, value );
     };
 
     /**
@@ -496,6 +485,7 @@
      * @param {string} key - the query parameter name
      * @param {Object} schema - schema that describes the query parameter
      * @param {boolean} value
+     * TODO https://github.com/phetsims/joist/issues/593 this should declare its return type
      */
     const validateFlagValue = function( key, schema, value ) {
       return validateBooleanValue( key, schema, value ); // flag is a convenient variation of boolean
@@ -507,7 +497,7 @@
      * @param {Object} schema - schema that describes the query parameter
      * @param {boolean} value - value from the query parameter string
      */
-    var validateBooleanValue = function( key, schema, value ) {
+    const validateBooleanValue = function( key, schema, value ) { // TODO: https://github.com/phetsims/joist/issues/593 this is called as if it has a return value, but it has no return value
       queryStringMachineAssert( value === true || value === false, key, 'invalid value: ' + value );
     };
 
@@ -561,7 +551,7 @@
      *   could be multiple for ?value=x&value=y for example
      * @returns {*} the associated value, converted to the proper type
      */
-    var parseValues = function( key, schema, values ) {
+    const parseValues = function( key, schema, values ) {
 
       let returnValue;
 
@@ -598,7 +588,7 @@
      * @param {undefined|null} value - value from the query parameter string
      * @returns {boolean}
      */
-    var parseFlag = function( key, schema, value ) {
+    const parseFlag = function( key, schema, value ) {
       queryStringMachineAssert( ( value === undefined || value === null ), key, 'flag type does not support a value: ' + value );
 
       // value is true if the flag is present, false if absent
@@ -708,7 +698,7 @@
      * @param {Array.<*>} validValues
      * @returns {boolean}
      */
-    var isValidValue = function( value, validValues ) {
+    const isValidValue = function( value, validValues ) {
       let found = false;
       for ( let i = 0; i < validValues.length && !found; i++ ) {
         found = QueryStringMachine.deepEquals( validValues[ i ], value );
@@ -722,11 +712,18 @@
      * @param {boolean} condition - if this condition is false, an Error is throw
      * @param {string} key - the query parameter name
      * @param {string} message
+     * @param {boolean} [isGraceful]
      */
-    var queryStringMachineAssert = function( condition, key, message ) {
+    const queryStringMachineAssert = function( condition, key, message, isGraceful = false ) {
       if ( !condition ) {
-        console && console.log && console.log( formatErrorMessage( key, message ) );
-        throw new Error( 'Assertion failed: ' + message );
+
+        if ( isGraceful ) {
+          QueryStringMachine.addWarning( key, message, null, null ); // TODO https://github.com/phetsims/joist/issues/593 what to do with these args?
+        }
+        else {
+          console && console.log && console.log( formatErrorMessage( key, message ) );
+          throw new Error( 'Assertion failed: ' + message );
+        }
       }
     };
 
@@ -736,7 +733,7 @@
      * @param {string} message
      * @returns {string}
      */
-    var formatErrorMessage = function( key, message ) {
+    const formatErrorMessage = function( key, message ) {
       return 'Error for query parameter "' + key + '": ' + message;
     };
 
@@ -756,7 +753,7 @@
      * separator -  array elements are separated by this string, defaults to `,`
      * parse - a function that takes a string and returns an Object
      */
-    var TYPES = {
+    const TYPES = {
 
       // value is true if present, false if absent
       flag: {

```

</details>

Ultimately what may be best for this file is to convert its numerous `validate` patterns (which throw an assertion error if failed) to `isValid` patterns.  Please take a look at the partial changes and recommendations in the patch and let's discuss.

**Comment by chrisklus** [comment]
Thanks @samreid. The changes in `validateValue` look good, but the changes in `getForString` cause the following error on startup because `validateValue` does not always return a value, as pointed out by your TODO in `validateBooleanValue`:

```
require-2.3.6.js?bust=1577335826540:143 Uncaught Error: unsupported locale: undefined
    at Object.load (string.js:193)
    at Module.<anonymous> (require-2.3.6.js?bust=1577335826540:1095)
    at require-2.3.6.js?bust=1577335826540:134
    at on (require-2.3.6.js?bust=1577335826540:517)
    at Module.callPlugin (require-2.3.6.js?bust=1577335826540:955)
    at Module.fetch (require-2.3.6.js?bust=1577335826540:824)
    at Module.check (require-2.3.6.js?bust=1577335826540:856)
    at Module.enable (require-2.3.6.js?bust=1577335826540:1176)
    at Module.<anonymous> (require-2.3.6.js?bust=1577335826540:999)
    at require-2.3.6.js?bust=1577335826540:134
```

Regarding this TODO in `validateValue`, `// TODO: https://github.com/phetsims/joist/issues/593 what if no defaultValue is provided?` - i verified that is indeed a problem, so in `validateSchema`, if `isGraceful` is `true`, it should assert that there's a default value.

I like how `addError` is moved to `queryStringMachineAssert`, but all call sites of `queryStringMachineAssert` need to be updated to pass in `isGraceful`.

For this TODO in `validateBooleanValue`, `TODO: https://github.com/phetsims/joist/issues/593 this is called as if it has a return value, but it has no return value` - all of these validate functions should return a value. This makes me think that the following check should be moved to `queryStringMachineAssert` instead of each of the validate functions:

```js
if ( !ok && schema.isGraceful ) {
  value = schema.defaultValue;
}
```

I pushed the ES6 conversion changes and am ready to update the patch further but thought it might be good to discuss more first or pair on the next changes.

**Comment by chrisklus** [comment]
@samreid paired more on this today and were able to make some improvements. We followed through with @samreid's `isValid` suggestion from https://github.com/phetsims/joist/issues/593#issuecomment-568633044 and like how it worked out.

Assigning to @pixelzoom and @chrisklus for next steps (starting patch in https://github.com/phetsims/joist/issues/593#issuecomment-568608216).

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/joist/issues/593#issuecomment-568608216, @chrisklus said:
> There is a new schema key `isGraceful` that can be added to public query parameters. This way, internal query parameters can still throw errors for PhET developers, but public query parameters can just warn in the console and revert to default values. 

Presumably all public-facing query parameters should fail gracefully. And we need a way to designated which query parameters are public-facing. So how about something like `public: true` (default false) instead of `isGraceful`?

>  I added the key to the appropriate usages in EFAC and Natural Selection.

We should do the same for initialize-globals.js.

**Comment by pixelzoom** [comment]
> There is a new schema key isGraceful that can be added to public query parameters. This way, internal query parameters can still throw errors for PhET developers, but public query parameters can just warn in the console and revert to default values. 

I verified with natural-selection and `?allelesVisible=foobar`, a boolean query parameter.  In the console, I see:

> QueryStringMachine.js?bust=1578083492754:355 Value was not true|false for key "allelesVisible". Reverting to default value: true

But I'm a little confused here...  Why does this not throw an Error, which can then be caught and displayed in a Dialog?  And if not caught, will print the Error to the console?

**Comment by chrisklus** [comment]
@pixelzoom said:

>Presumably all public-facing query parameters should fail gracefully. And we need a way to designate which query parameters are public-facing. So how about something like `public: true` (default false?) instead of `isGraceful`?

Sounds good to me, I converted usages and added the one marked as public in initialize-globals.js. I suspect more of these are intended to be marked public, like `screens` (since we advertise it), so I created a separate issue, see https://github.com/phetsims/chipper/issues/829.

@pixelzoom said:

>But I'm a little confused here... Why does this not throw an Error, which can then be caught and displayed in an error dialog? And if not caught, will print UncaughtError to the console?

In https://github.com/phetsims/joist/issues/593#issuecomment-567623410, @pixelzoom said:

>First thing to do might be to warn to console, then revert to the default value when an invalid value is provided. @chrisklus will do this part.

I guess I took that pretty literally ha, but I still prefer it this way. The validation was changed to a getValidValue function:

```js
const getValidValue = ( ok, key, value, schema, message ) => {
  if ( !ok ) {

    if ( schema.public ) {
      QueryStringMachine.addWarning( key, message, value, schema.defaultValue );
      value = schema.defaultValue;
    }
    else {
      queryStringMachineAssert( ok, message );
    }
  }
  return value;
};
```

@samreid and I were instead catching errors at one point as you expected, but I preferred using a warning since the sim is not crashing, and didn't like the look in the console of having a warning and an error for the same problem. Obviously, this could easily be changed.

**Comment by chrisklus** [comment]
>But I'm a little confused here... Why does this not throw an Error, which can then be caught and displayed in an error dialog? And if not caught, will print UncaughtError to the console?

Also worth noting in case you hadn't seen the starting patch in https://github.com/phetsims/joist/issues/593#issuecomment-568608216 yet - all of the info sent to `QueryStringMachine.addWarning` becomes available to the dialog popup, which is more informative to the user than just the queryStringMachineAssert error message since the provided value and default value are also included independently from the message. There are many call sites to queryStringMachineAssert, so keeping its api simple felt better than including extra info everywhere else, too.

![image](https://user-images.githubusercontent.com/5618316/71757128-7b168400-2e61-11ea-9ba2-e2c25c61dcbb.png)

We should be able to make a nice and friendly message with this metadata instead of just dumping the console error on users.

**Comment by pixelzoom** [comment]
QueryStringMachine now puts together a list of warnings.   @chrisklus Questions for designers that could be investigated while you're waiting for me to work on this....

* Do we display a dialog when the first warning occurs, or after query parameters have been processed? 
* If the latter, do we display the first warning, or all warnings?  
* If displaying all warnings, what do we do if there are too many warnings to comfortably fit in the dialog? 
* Do the warnings need to be translatable?

**Comment by pixelzoom** [comment]
@ariel-phet We need designer input to proceed on this issue.  Specifically, we need answers to the questions on https://github.com/phetsims/joist/issues/593#issuecomment-573334639.  Could you please assign someone?

**Comment by ariel-phet** [comment]
Reading over the questions in https://github.com/phetsims/joist/issues/593#issuecomment-573334639 I think we should bring this discussion to iO meeting this week. @arouinfar do you mind taking a quick first pass with your thoughts? I think we will need KP sign off here though to be efficient in moving forward.

**Comment by arouinfar** [comment]
Here are my initial thoughts. I'll think more about the dialog content before Thursday's iO meeting, and possibly mock up a few options.

A few assumptions I'm making about query parameters:

1. Nonexistent/misspelled query parameters (such as `?nonsense` or `?skreens=1`) are ignored and the sim loads normally.
2. The sim will fail to load if the a query parameter is passed a bad (or no) value like `?screens=99` or `?screens`

> Should we display a dialog when the first warning occurs, or after all query parameters have been processed?

I think the latter would be more useful.

> If the latter, do we display only the first warning, the first N warnings, all warnings,...?

All warnings seems more ideal, but not might be practical as I could see QA breaking this spectacularly. Maybe we could choose a sufficiently large N so that there is an upper limit, but effectively large enough that realistic usage of query parameters would never reach it? Maybe N=10?

> If displaying all warnings, what do we do if there are too many warnings to comfortably fit in the dialog?

I think it's probably most practical to choose some large (but manageable) N to cap the warnings at. 

> Do the warning messages need to be translatable? (Reminder that query parameter names themselves are not translatable, but messages could be.)

Probably. Perhaps we could use some standard warning string(s), and then drop the errant query parameter into it. 

> The warning example in #593 (comment) is not at all user friendly. How should these warnings generally be presented? Who is the audience?

Agreed, we should not simply redirect console errors to the dialog. I think the audience would be teachers and the occasional instructional designers. The errors should be human-readable. Suppose you attempted to load a sim with `?nonsense&allelesVisible=foobar`, the dialog content could be something like:

(very rough idea here)
```
Warning!

nonsense is an invalid query parameter and has been ignored.
foobar is not an accepted value of allelesVisible. 
```
We may also want to consider adding links to sim-specific or general information about query parameters.

> Does the sim continue to run with default values after the dialog is dismissed?

Yes, that would be preferred. It would be nice if misspelled/invalid query parameters are simply ignored, but that doesn't seem to be the case of the type which require a value. I can't run Gas Properties with something like `?pressureNoise=off`.

**Comment by pixelzoom** [comment]
Based on @arouinfar's feedback in the previous comment, it seems like there's an assumption that we will recognize unsupported query parameters -- e.g. if the user accidentally types "screenz=1,2" instead of "screens=1,2".  Unsupported query parameters are currently ignored, and nothing in this issue (so far) has planned to address that.  And I really don't recommend that we do this -- it will be problematic for cases where a sim is run in an iFrame, the iFrame recognizes some of the query parameters, but passes all query parameters through to the sim.

**Comment by arouinfar** [comment]
> Based on @arouinfar's feedback in the previous comment, it seems like there's an assumption that we will recognize unsupported query parameters -- e.g. if the user accidentally types "screenz=1,2" instead of "screens=1,2".

Sorry, I wasn't clear. I am not suggesting that the sim corrects the query parameter, but simply ignores it. Currently, something like `?skreenz=1` is ignored and the sim will load, but the sim won't load if you pass a bad value like `?screens=99`. The latter seems problematic to me, since I'm not sure how the dialog would function. Would you get a dialog over a black screen?

**Comment by pixelzoom** [comment]
> Sorry, I wasn't clear. I am not suggesting that the sim corrects the query parameter, but simply ignores it.  ...

@arouinfar I'm confused.  You gave this as an example:

```
Warning!

nonsense is an invalid query parameter and has been ignored.
foobar is not an accepted value of allelesVisible. 
```

As currently implemented, the sim will never know about `nonsense` and therefore cannot warn about it.   Warning about an unsupported query parameter is not ignoring it.

**Comment by arouinfar** [comment]
If the goal of the this dialog is to make users aware that there are errors in the query parameters, then we would need to print a warning about `nonsense`.  That said, I don't think I understand the goals of this dialog or inner-workings of query parameters well enough to continue an asynchronous discussion. I think it will be more productive to pick it up at Thursday's iO meeting, so I'll unassign myself.

**Comment by chrisklus** [comment]
From 01/23/20 phet-io meeting:

We're okay with ignoring misspelled query parameter keys, but we'll proceed with adding warnings for bad values, and reverting to default values for any warnings that came up. In the long term, it would be nice to have a UI to select QPs so invalid keys are far less likely to be a problem.

* General message format:
```
Title: Invalid Query Parameter

One or more query parameters have invalid values:
screens: 1,23
initialScreen: 4
The simulation is starting with default values for these query parameters.
```
We may also add a PhET girl image, like the one from the Oops dialog.

We might also add info about query parameters to the help center. However, sim specific QPs could only be added here if the process was automated with publications so they would be correct with the current version.

@pixelzoom and I will continue with creating this dialog.

**Comment by pixelzoom** [comment]
Thoughts/notes:

* Need to decide when (in the startup sequence) the dialog should be displayed.  Maybe after the sim has fully loaded?  Ask designers.

* The dialog should be created by joist.

* Reuse OopsDialog? It lives in scenery-phet, and joist already depends on scenery-phet.
`class QueryParameterWarningDialog extends OopsDialog`

* Strings should live in joist-strings_en.json, something like:

```
  "invalidQueryParameter": {
    "value": "Invalid Query Parameter"
  },
  "oneOrMoreQueryParameters": {
    "value": "One or more query parameters have invalid values:"
  },
  "theSimulationWillStart": {
    "value": "The simulation will start with default values for those query parameters."
  },
```

**Comment by pixelzoom** [comment]
Slack with @arouinfar:

Chris Malley  2:40 PM
Re https://github.com/phetsims/joist/issues/593 (query parameter warning dialog)...  We need to decide when (in the startup sequence) the dialog is displayed.  Would it be OK to display it after the sim has fully loaded, and the home screen (or sole screen) has been rendered?

Amy Rouinfar  2:40 PM
That sounds reasonable to me

Chris Malley  2:40 PM
Thanks, we'll proceed with that plan.

**Comment by chrisklus** [comment]
@pixelzoom and I worked on this and created a new Dialog called QueryParametersWarningDialog.js. For now, we decided to not instrument it for phet-io.

It looks like this:

![image](https://user-images.githubusercontent.com/5618316/73200217-5cc04300-4104-11ea-8466-d872144c2511.png)

What do you think @arouinfar - anything else to add or change?

**Comment by arouinfar** [comment]
Looks good to me @chrisklus @pixelzoom!

**Comment by pixelzoom** [comment]
@arouinfar @chrisklus 

I tried using this for the `mutations` and `population` query parameters that in Natural Selection, whose values are dependent on each other (see https://github.com/phetsims/natural-selection/issues/9).   

For query parameters `?&allelesVisible=fals&mutations=F&population=Ff:20,Ee:15`, the resulting dialog is shown below.  The value of `allelesVisible` is invalid due to a misspelling of `false`.  The values of `mutations` and `population` are incompatible because `population` contains abbreviations for ears alleles ('E, 'e'), and `mutations` only describes the fur gene ('F' for brown fur dominant).  And we don't know whether `mutations` or `population` is incorrect.

There's currently no way to note that `mutations` and `population` are invalid because they are related. Will that be a problem?  Or is this "good enough", and we expect the user to do their own debugging? 

<img width="883" alt="screenshot_65" src="https://user-images.githubusercontent.com/3046552/73203936-4b266d80-40fb-11ea-98f8-b4289686ec20.png">

**Comment by arouinfar** [comment]
> There's currently no way to note that mutations and population are invalid because they are related (values are syntactically valid but semantically incompatible). Will that be a problem? Or is this "good enough", and we expect the user to do their own debugging?

I believe the conclusion in PhET-iO meeting was to keep the dialog simple and shift some responsibility to the user. That said, I'm not the lead for Natural Selection, so I would really prefer to defer to @amanda-phet to make sure this is an acceptable solution.

**Comment by amanda-phet** [comment]
If the decision is to keep the dialog simple, this certainly works. It's not the most user-friendly, but I think that isn't necessarily the goal right now. My understanding is that we want to create a more robust solution later and will put more effort in to making it user friendly at that time. If that is all correct, then this looks like a fine solution for now.

**Comment by pixelzoom** [comment]
Here's another problem with validating query parameters that depend on each other -- what I will refer to herein as "compatibility constraints". 

Suppose that I query parameters `width` and `height` that are numbers, they are both > 0, and their compatibility constraint is `width >= height`.

Here's the implementation:

```
const MyQueryParameters =QueryStringMachine.getAll( {
    width: {
      type: 'number',
      defaultValue: 10,
      isValidValue: width => width > 0
      public: true
    },

    height: {
      type: 'number',
      defaultValue: 10,
      isValidValue: width => height > 0
      public: true
    }
} );

// compatibility constraint for width and height
if ( MyQueryParameters.width < MyQueryParameters.height ) {
 QueryStringMachine.addWarning( 'width', NaturalSelectionQueryParameters.width, ...);
 QueryStringMachine.addWarning( 'height', NaturalSelectionQueryParameters.height,...) 
}
```

With `?width=10&height=20`, I get this dialog, which looks OK:

<img width="692" alt="screenshot_66" src="https://user-images.githubusercontent.com/3046552/73211870-487f4480-410a-11ea-94ee-d0948ea21154.png">

But with `?width=0&height=20` (I typed '0' instead of '10' for `width`), here's what happens:

<img width="689" alt="screenshot_67" src="https://user-images.githubusercontent.com/3046552/73211943-6b115d80-410a-11ea-9fb7-b0f355fcb396.png">

QueryStringMachine's validation notices that `width` is not > 0, so it adds a warning, and sets its value to the default (10).    Then the validation comparing `width` and `height` fails, and warnings for `width` and `height` are added.  This results in 2 messages for `width`, very confusing!  

The problem is that QueryStringMachine does some basic validation (type, `isValidValue`), and we have no way of knowing if that passed or failed.  If it failed, there's no reason to check the compatibility constraint, because failed values will have been reverted to defaults. 

I can improve things a bit by changing the logic to this hot mess:

```js
  // compatibility constraint for width and height
  if ( NaturalSelectionQueryParameters.width < NaturalSelectionQueryParameters.height ) {
    const message = 'width must be >= height';
    if ( !QueryStringMachine.hasWarning( 'width' ) ) {
      QueryStringMachine.addWarning( 'width', NaturalSelectionQueryParameters.width, 10, message );
    }
    if ( !QueryStringMachine.hasWarning( 'height' ) ) {
      QueryStringMachine.addWarning( 'height', NaturalSelectionQueryParameters.height, 10, message );
    }
  }
```

With `?width=0&height=20`, the resulting dialog is:

<img width="691" alt="screenshot_68" src="https://user-images.githubusercontent.com/3046552/73212236-086c9180-410b-11ea-9cd0-49e6236c838f.png">

This is better. But there's no reason to warn about `height` because `width` was inherently invalid, and we're not comparing `height` to `width=0`, we're comparing to `width=10`.  This is easier to see with `?width=foo&height=20`, where `width` fails QueryStringMachine's type validation (it should be a number).   In that case the dialog is:

<img width="692" alt="screenshot_69" src="https://user-images.githubusercontent.com/3046552/73212367-54b7d180-410b-11ea-8d45-a4f181653645.png">

I'm not sure how to proceed with this, it will require more discussion.

**Comment by pixelzoom** [comment]
We probably need to do something like this:

* Let `QueryStringMachine.getAll` do its validation.
* For each compatibility constraint, if any query parameter had a problem in `getAll`, then reset all query parameters involved in the relationship to their default values.
* Have exactly 1 warning for any query parameter that was reset to its default values. 

We can use `QueryStringMachine.hasWarning` to see if a query parameter failed validation during `getAll`.   

We need a public method to set a query parameter to its default value.

All of the above would currently be quite a messy bit of code in {{REPO}}QueryParameters.js.

What do we do if a query parameter is involved in > 1 relationship?

**Comment by kathy-phet** [comment]
Another question around these query parameters was if we should test whether there is a "match" in query parameters but the case sensitivity makes if off. Today a mistyped the case for allowLinks and had to fix it. Is it easy to flag this without adding complication about the passthough stuff?

**Comment by pixelzoom** [comment]
There's nothing in the current implementation (QueryStringMachine) that checks for case-insensitive key matches.  It's not easy to flag these, and (at this point) also not easy to add that to the warning dialog.  (We decided last week that warning would pertain to values, not keys.)

**Comment by pixelzoom** [comment]
I have this working in Natural Selection, see https://github.com/phetsims/natural-selection/issues/9#issuecomment-630543721.   I have no plans to do additional work on this in the near future, so unassigning myself.

**Comment by chrisklus** [comment]
Likewise - this feature is working in Energy Forms and Changes. @pixelzoom should we close this issue and open a new one in the future if we need to build it out more?

**Comment by pixelzoom** [comment]
Sounds good to me @chrisklus. Closing.

**Comment by samreid** [comment]
There are still TODOs marked for this issue, discovered during https://github.com/phetsims/chipper/issues/946

**Comment by pixelzoom** [comment]
I see 1 TODO, in QueryStringMachine.js:

```
required: [ 'parse' ], // TODO: https://github.com/phetsims/joist/issues/593 how to allow custom parse implementations to use getValidValue or otherwise deal with public?
```

@chrisklus I'm unfamiliar with this, could you handle it?

**Comment by zepumph** [comment]
Removing one todo, as it makes no sense to dive back into this function 18 months later. As for this issue:

```
required: [ 'parse' ], // TODO: https://github.com/phetsims/joist/issues/593 how to allow custom parse implementations to use getValidValue or otherwise deal with public?

```


I created a test:

    tempPublic: {
      public: true,
      defaultValue: '4',
      parse: v => v,
      isValidValue: v => v === '4' || v === '7',
      type: 'custom'
    },

And saw that it worked as expected. When omitted, the value was '4', when I added `tempPublic=3`, I got the warning dialog. When I added `tempPublic=4`, everything worked, also for 7. I'm going to remove the TODO and close.

**Comment by chrisklus** [comment]
Thanks for testing this out @zepumph!
