### ISSUE TITLE
Support graceful validation for ?screens query parameter

### ISSUE THREAD

**Issue by chrisklus** [phetsims/joist#599]
From https://github.com/phetsims/joist/issues/593 and https://github.com/phetsims/chipper/issues/829.

The validation for the `screens` query parameter happens in Sim.js instead of the usual flow in QueryStringMachine. In order to support the functionality of the new `public` schema key, the validation should be handled by QueryStringMachine. Marking a TODO to this issue and self-assigning.

**Comment by chrisklus** [comment]
We may not be able to validate these values using QSM since `screens` is a general QP and its valid values vary sim by sim. However, we can continue to validate in selectScreens.js and then leverage QSM's `addWarning` function to show a dialog in the sim and launch with the default number of screens. 

@arouinfar it seems like this should be done sooner rather than later. Sims currently crash with bad values for `screens` instead of using the error dialog. What do you think?

**Comment by arouinfar** [comment]
> Sims currently crash with bad values for screens instead of using the error dialog. What do you think?

This sounds a bit problematic, and we should probably fix it.

> However, we can continue to validate in selectScreens.js and then leverage QSM's addWarning function to show a dialog in the sim and launch with the default number of screens.

Sounds like you have a plan!

**Comment by chrisklus** [comment]
working patch:

<details>

```diff
Index: joist/js/selectScreens.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- joist/js/selectScreens.js	(revision f65c5a183d013ef3dee700a1b0d2b5b2c629071c)
+++ joist/js/selectScreens.js	(date 1589848584000)
@@ -42,20 +42,28 @@
   }
 
   // the sim screens for this runtime, accounting for specifying a subset with `?screens`
-  let selectedSimScreens;
+  let selectedSimScreens = [];
 
   // The screens to be included, and their order, may be specified via a query parameter.
   // For documentation, see the schema for phet.chipper.queryParameters.screens in initialize-globals.js.
-  // TODO: Use QueryStringMachine to validate instead, see https://github.com/phetsims/joist/issues/599
-  if ( screensQueryParameterProvided ) {
+  if ( screensQueryParameterProvided && screensQueryParameter ) {
     //REVIEW: Shouldn't we just see if the result is the default value of `null`, instead of checking if it was
     //REVIEW: provided? See https://github.com/phetsims/joist/issues/614
-    selectedSimScreens = screensQueryParameter.map( userIndex => {
+    screensQueryParameter.forEach( userIndex => {
       const screenIndex = userIndex - 1; // screens query parameter is 1-based
-      if ( screenIndex < 0 || screenIndex > allSimScreens.length - 1 ) {
-        throw new Error( 'invalid screen index: ' + userIndex );
+
+      // add screen to selectedSimScreens if its a valid index
+      if ( screenIndex >= 0 && screenIndex < allSimScreens.length ) {
+        selectedSimScreens.push( allSimScreens[ screenIndex ] );
       }
-      return allSimScreens[ screenIndex ];
+      else {
+        const errorMessage = `invalid screen index: ${userIndex}`;
+        assert && assert( false, errorMessage );
+        QueryStringMachine.addWarning( 'screens', userIndex, null, errorMessage );
+
+        // set selectedSimScreens to default values
+        selectedSimScreens = allSimScreens;
+      }
     } );
   }
   else {
Index: chipper/js/initialize-globals.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- chipper/js/initialize-globals.js	(revision ebe0e90278d6a440705817644bfcf444ae05f8ac)
+++ chipper/js/initialize-globals.js	(date 1589848489000)
@@ -429,7 +429,8 @@
 
         // screen indices cannot be duplicated
         return value === null || ( value.length === _.uniq( value ).length );
-      }
+      },
+      public: true
     },
 
     /**
```

</details>

**Comment by chrisklus** [comment]
Implemented above. Note that I ran into one gotcha; not all of the validation for `?screens` happens in selectScreens.js - there's also an `isValidValue` function as part of its schema in initialize-globals.js. Since `screens` is now marked as public, it's possible that its value has already been reverted to its default of `null` by the time it gets to selectScreens.js. I added a comment to explain and linked to this issue later in the `if` block.

I also added an assert that still fails loudly when running with ?ea so that selectScreensTests passes appropriately for failure cases.

@pixelzoom would you be interested in reviewing the two commits from this issue? The scope is pretty small, and I think you're most familiar with using QueryStringMachine.addWarning. Based on the potentially hard-to-read change set, it might be simpler to just look at a before and after of the relevant code in selectScreens.js

**Comment by pixelzoom** [comment]
@chrisklus and I reviewed this via Zoom, and made one change above.  This is all looking good for the `screens` query parameter.

There are still some TODO items related to this issue in selectScreens.js, and the `initialScreen` and `homeScreen` query parameters (which are also public) seems like they should be handled here too.  Back to @chrisklus.

**Comment by chrisklus** [comment]
Thanks @pixelzoom - we chatted on zoom and I mentioned that I forgot to bring up earlier that I was holding off on finishing `homeScreen` and `initialScreen` because there was no way to get the default value of their schemas (will eventually be possible from https://github.com/phetsims/chipper/issues/936). This was not a problem for `screens` because the default value is all of the sim's possible screens, which does not relate to the `screens` QP. 

However, when @pixelzoom and I looked at the remaining cases, we realized there was no need to revert the QPs to their default values in order for the sim to run, we just needed to tell the user that the values they provided are not being used, and then continue launching the sim as normal. This is because in all three remaining cases, the values were *already* their default value, it's just considered a problem that the user explicitly included them (since they contradict with other QP values or the number of screens the sim has). Implemented in the commits above.

Question for @pixelzoom: the signature for `QueryStringMachine.addWarning` is `( key, value, defaultValue, message )`, but it doesn't seem to make sense to provide a default value for the above cases (they are all null at the moment) for two reasons:
* At the moment, we'd have to duplicate their schema to get their default value.
* As mentioned above, their values in these error cases are already the default values, so the console warning from QueryStringMachine would be confusing:

```
cannot specify homeScreen=true for single-screen sims. Reverting to default value: true
```

- [ ] Proposal (as an action item for @chrisklus before @pixelzoom review): change `QueryStringMachine.addWarning`'s signature to `( key, value, message, defaultValue )`, where defaultValue is optional. Then, `addWarning` can be used when the default value is unknown, and if it's not provided, the second half of the warning would be omitted. So the above error case would read like this:

```
cannot specify homeScreen=true for single-screen sims.
```

**Comment by pixelzoom** [comment]
This defaultValue parameter is suspicious.   If we really want to revert to the default value, QSM should handle that based on key, and we shouldn't be providing a value.   As is, I can provide any value for `defaultValue`, it will still be identified as "Reverting to default value", and the warning dialog will then be in error too.  I also don't see code that actually reverts to `defaultValue` -- it sure didn't work for me in Natural Selection.  So (for now) I would delete the `defaultValue` parameter entirely, along with the "Reverting to default value" part of the console.warn message.

**Comment by chrisklus** [comment]
Oh right, it's separate - see line 80 in QueryStringMachine.js:

```js
if ( schema.public ) {
  QueryStringMachine.addWarning( key, value, schema.defaultValue, message );
  value = schema.defaultValue;
}
```

When QueryStringMachine leverages `addWarning` during its own validation, it does revert to the default value. And I think that's the behavior what we want for the simpler cases that don't require leveraging `addWarning` in sim code.

I see how the separation of the "resetting to default" message from the *actual* resetting is problematic. If `addWarning` is going to be public for use by sim code (like we need it to be for these special cases), then resetting to a default value in the context of QueryStringMachine is meaningless because we've already harvested the value. I removed the parameter and the message above. Please review the most recent 3 commits from this issue.

**Comment by pixelzoom** [comment]
Change to `QueryStringMachine.addWarning` and call sites look great. Back to @chrisklus.

**Comment by chrisklus** [comment]
Thanks @pixelzoom, closing.
