### ISSUE TITLE
standardize tandem name for sim title

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#604]
These 2 elements in Studio display the sim's title:

```
phScale.general.navigationBar.titleTextNode
phScale.homeScreen.view.title
```

Should we standardize the tandem name? `titleNode` perhaps?

**Comment by zepumph** [comment]
I think that `titleText` is most idiomatic to how we name things since each of these will be a `TextIO` and will have a textProperty sub Property.

**Comment by samreid** [comment]
This is an API breaking change of an important feature, and seems like it should have higher priority.

**Comment by chrisklus** [comment]
This was implemented as the second item of https://github.com/phetsims/joist/issues/627#issue-600559441. Closing.
