### ISSUE TITLE
elementsToRemove appears unused

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#609]
Discovered in https://github.com/phetsims/chipper/issues/844, it looks like `SimLauncher.elementsToRemove` hasn't been used in many years.  It seems safe to remove, but I should run it past @jonathanolson who introduced it.

**Comment by samreid** [comment]
I tested a sim without this code in built and requirejs mode, and launched scenery playground.  No problems noted.  I'll commit, @jonathanolson can you please review?  I don't think this commit in itself should block publication, but it would be good to understand why that code may no longer be necessary, so I will mark for blocks-publicaiton.

**Comment by jonathanolson** [comment]
Looks safe to me, thanks!
