### ISSUE TITLE
Screen changes are triggering sounds even when user interface sounds are disabled

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/joist#611]
@jbphet: this was first noticed in http://phettest.colorado.edu/circuit-construction-kit-ac/circuit-construction-kit-ac_en.html?ea&brand=phet
There are several UI sounds that are disabled (volume set to 0), but the screen buttons continue to play sounds -- so they don't appear to be labeled as UI sounds.

**Comment by jbphet** [comment]
Fixed by setting the sound generator for these screen sounds to the 'user-interface' category, closing.
