### ISSUE TITLE
Just pass in the index

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#612]
From https://github.com/phetsims/joist/issues/602, @jonathanolson remarked in the code review:

```js
    innerContent: StringUtils.fillIn( screenNameStringPatternString, {
      //REVIEW: Just pass in the index? https://github.com/phetsims/joist/issues/602
      number: simScreens.indexOf( screen ) + 1 // convert from index to display number
    } )
```

It's unclear what the recommendation is, @jonathanolson can you please clarify?

**Comment by jonathanolson** [comment]
There were multiple accesses to `simScreens.indexOf( screen )`, AND `simScreens` was only used for that purpose. Just passing in the index of the screen (instead of the simScreens array) should improve encapsulation and be simpler.

**Comment by samreid** [comment]
@chrisklus can you please take a look?

**Comment by chrisklus** [comment]
Ah I understand, thanks for clarifying @jonathanolson. I committed the recommended change above. @samreid would you please review?

**Comment by samreid** [comment]
Looks great, thanks @chrisklus and @jonathanolson, closing.
