### ISSUE TITLE
Should "?screens=1" or "?initialScreen=1" or "homeScreen=false" fail for single screen sims?

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#613]
From #602 and #603, this came up during review:

```js
  if ( allSimScreens.length === 1 ) {

    // Problems related to query parameters throw errors instead of assertions (so they are not stripped out)
    if ( homeScreenQueryParameterProvided ) {
      throw new Error( 'homeScreen query parameter not supported for single-screen sims' );
    }
    //REVIEW: Why is initialScreen not allowed on single-screen sims? Does this mean that for anything that iterates
    //REVIEW: over sims and tries to go to the 1st screen, we'll need to record whether they have just one and omit
    //REVIEW: the query parameter for no other reason than it would error out due to this assertion?
    //REVIEW: See https://github.com/phetsims/joist/issues/602
    if ( initialScreenQueryParameterProvided ) {
      throw new Error( 'initialScreen query parameter not supported for single-screen sims' );
    }
```

Before we can proceed, we need to ask the dev team: Should "?screens=1" or "?initialScreen=1" or "homeScreen=false" fail for single screen sims?

**Comment by samreid** [comment]
At today's meeting @pixelzoom @kathy-phet @arouinfar agreed that these should not be failure cases.  @chrisklus can you please address this accordingly?

**Comment by chrisklus** [comment]
Implemented above, @samreid please review.

**Comment by zepumph** [comment]
I'm going to review this while reviewing  https://github.com/phetsims/joist/issues/603#issuecomment-59427069

**Comment by zepumph** [comment]
I see now that `?homeScreen=true` will fail on a single screen sim, but not on a multi-screen simulation that only has a single screen specified. This feels good and right to me. Great work @chrisklus. Anything else here?

**Comment by chrisklus** [comment]
All set, thank you. Closing.
