### ISSUE TITLE
Make it easier for sims to listen to when phetioSetStateCompleted

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#615]
Here's a patch from discussion today:

<details>

```diff

Index: main/balloons-and-static-electricity/js/balloons-and-static-electricity/view/SweaterNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- main/balloons-and-static-electricity/js/balloons-and-static-electricity/view/SweaterNode.js	(revision 1d6990f9b3dca37d17cbc5b249465b2b8240b183)
+++ main/balloons-and-static-electricity/js/balloons-and-static-electricity/view/SweaterNode.js	(date 1584036094891)
@@ -125,11 +125,23 @@
 
   // When setting the state using phet-io, we must update the charge visibility, otherwise they can get out of sync
   // due to the fact that the movedProperty state could get loaded before the chargeProperty state.
-  _.hasIn( window, 'phet.phetIo.phetioEngine' ) && phet.phetIo.phetioEngine.phetioStateEngine.stateSetEmitter.addListener( function() {
+  // A
+  sim.stateSetProperty.lazyLink( settingState => {
+    if ( !settingState ) {
+      updateChargesVisibilityOnSweater( model.showChargesProperty.get() );
+    }
+  } );
+
+  // B
+  sim.phetioFinishedSettingState.addListener( () => {
+    updateChargesVisibilityOnSweater( model.showChargesProperty.get() );
+  }
+
+  // C
+  sim.phetioSetStateComplete.addListener( () => {
     updateChargesVisibilityOnSweater( model.showChargesProperty.get() );
-  } );
-}
+  }
 
-balloonsAndStaticElectricity.register( 'SweaterNode', SweaterNode );
+  balloonsAndStaticElectricity.register( 'SweaterNode', SweaterNode );
 
-export default inherit( Node, SweaterNode, {} );
\ No newline at end of file
+  export default inherit( Node, SweaterNode, {} );
\ No newline at end of file
Index: main/joist/js/Sim.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- main/joist/js/Sim.js	(revision b20b47b058cab82fe6ef6adb04e1b54c24dfbdf6)
+++ main/joist/js/Sim.js	(date 1584036094887)
@@ -426,6 +426,9 @@
                                         _.identity ) :
                                       new BooleanProperty( false );
 
+  // Sends out notification after phet-io finished setting the state
+  this.phetioSetStateCompleteEmitter = new Emitter();
+
   // commented out because https://github.com/phetsims/joist/issues/553 is deferred for after GQIO-oneone
   // if ( PHET_IO_ENABLED ) {
   //   this.engagementMetrics = new EngagementMetrics( this );


```

</details>

We wanted to ask @zepumph if we can eliminate the `stateSetEmitter` by bundling its behavior into the `isSettingStateProperty`. There is an `updateViews` between them.

**Comment by zepumph** [comment]
> There is an updateViews between them.

Yes I think that there is an important distinction here, and I don't think that we can combine out of the box.

`isSettingStateProperty` is what you listen to if you want to know if the phet-io engine is in the process of setting state. This is purposefully the very first and very last things in the `setState` call.

`stateSetEmitter`, likely the worse named of the two`, is meant to be a hook for the time in which state setting logic has completed, and if the sim has specific needs as it pertains to state setting, to do it now. A potential usage of the `stateSetEmitter` would be if you set all elements in a sim to `phetioState` false and then have a single listener to `stateSetEmitter` that sets the entire sim's state. Another usage could be if there is a specific function in a sim's model that needs to be called once all model Properties have been set to recalculate something internally. In both of these cases, it is important that this happens before the view is redrawn/updated, and I would not consider "state setting complete" at this time. 

1. Note that the BASE example "A" above is potentially not having views updated after that model call. 
1. Let's come up with a better name for `stateSetEmitter`
2. I'd be fine with a pointer to phetioStateEngine.stateSetEmitter on Sim.js, like `phet.joist.sim.timeToDoPhetioStateWorkEmitter` (with the same name for both probably)

Let's discuss!
