### ISSUE TITLE
Should ScreenView be Tandem.REQUIRED?

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#616]
Over in https://github.com/phetsims/studio/issues/109 there was a bug for sims that had an instrumented ScreenViews. It made me realize that there is no consistency across sims as to if we instrument the ScreenView for sims. 

To illustrate this, note that HomeScreenView is instrumented, but many sims don't have their other sims instrumented (you can see this by looking at the commits in https://github.com/phetsims/studio/issues/109 and see where the baseline only changed for the homescreen, but not anywhere else). 

There are 66 instrumented phetioIDs for screens, so I feel like it is likely best to make this Tandem.REQUIRED. @chrisklus what do you think? Can you think of a reason why we wouldn't want to make this required?

**Comment by chrisklus** [comment]
Oh wow, yeah I've never noticed this either. Seems best to be consistent - I can't think of a reason why it shouldn't be required. Should we also assert that `tandem.name` === `view`? Feel free to leave assigned to me to implement.

**Comment by samreid** [comment]
For my future reference, here is a list of sims failing this at the moment:

http://localhost/main/aqua/test-server/test-sims.html?ea&audioVolume=0&sound=disabled&testDuration=10000&testConcurrentBuilds=4&brand=phet-io&fuzz&phetioStandalone&testSims=atomic-interactions,blackbody-spectrum,circuit-construction-kit-dc,coulombs-law,energy-forms-and-changes,faradays-law,friction,gravity-and-orbits,gravity-force-lab,gravity-force-lab-basics,phet-io-test-sim,projectile-motion,states-of-matter,states-of-matter-basics,wave-on-a-string

**Comment by samreid** [comment]
Proposed fix pushed, @zepumph would you like to review?

**Comment by zepumph** [comment]
Instead of checking supplied. I would have thought to use isPhetioInstrumented with a check on if phetio is enabled. In general I don't like exposing "supplied" since we have other, more formalized abstractions.

**Comment by samreid** [comment]
Thanks, I changed from `tandem.supplied` to `isPhetioInstrumented`.  Ready for re-review.

**Comment by zepumph** [comment]
Looks great. Thanks.
