### ISSUE TITLE
fix incorrect scaling of KeyboardHelpDialog

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#618]
Over in #586, @pixelzoom investigated that dialogs are getting weirdly scaled. Over in that issue, fixing the problem was deferred, but @pixelzoom recommended a word around in https://github.com/phetsims/joist/issues/586#issuecomment-602745008 to make sure the issue isn't continued to be propagated. 

This workaround won't work for additional keyboard help content that will be created, and I think that we should try to fix it here now, since many more keyboard help dialog contents will be created in the future. 

One possible solution is to try to add this scale to KeyboardHelpDialog has the right scale.

**Comment by jessegreenberg** [comment]
Closing this since a fix was applied in https://github.com/phetsims/joist/issues/586 that is working well.
