### ISSUE TITLE
replace phet.phetio with Tandem.PHET_IO_ENABLED in conditionals

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#619]
Testing `phet.phetio` appears to be widely used as a way of determining whether PhET-iO is running.  Searching .js files in PhET repos:

* 9 occurrence of `( phet.phetio`
* 4 occurrence of `( window.phet.phetio`
* 2 occurrences of `( !phet.phetio`
* 2 occurrence of `( !window.phet.phetio`

... and there may be more.

Shouldn't these be testing `Tandem.PHET_IO_ENABLED`?   See https://github.com/phetsims/tandem/issues/153.

**Comment by zepumph** [comment]
@chrisklus is this something you can look at?

**Comment by chrisklus** [comment]
I attempted to get all of the occurrences that can rely on Tandem.js. Tested with aqua (both brands), Studio, and wrapper unit tests. @samreid or @zepumph please review.

**Comment by zepumph** [comment]
I added one more. Ready to close after spot check.

**Comment by chrisklus** [comment]
Looks good, thanks. Closing.
