### ISSUE TITLE
NavigationBarScreenButton highlight wrong when text grows

### ISSUE THREAD

**Issue by chrisklus** [phetsims/joist#620]
Discovered during https://github.com/phetsims/joist/issues/597.

When the text in NavigationBarScreenButton gets longer, it correctly updates by centering the text and respecting its max-width, but the button still gets wider. This causes the right-side highlight from mouseover to be positioned incorrectly:

<img width="426" alt="Screen Shot 2020-03-30 at 1 57 15 PM" src="https://user-images.githubusercontent.com/5618316/77951316-d953d700-7297-11ea-8081-93b0ddd85ac4.png">

**Comment by zepumph** [comment]
@chrisklus I believe this has been sorted out. We have brought multiple sims through RC, and have had recent layout work related to the dynamic text of these buttons over in https://github.com/phetsims/joist/issues/718 et al. I also don't see this in master:

![image](https://user-images.githubusercontent.com/6856943/126186528-6fb929a3-d064-4d38-9e8a-40acd74ea9ec.png)


Closing
