### ISSUE TITLE
sim.screenProperty phetioDoc does not match phet-io style

### ISSUE THREAD

**Issue by chrisklus** [phetsims/joist#623]
```js
// @public {Property.<Screen>} - Specifies the selected Screen
this.screenProperty = new Property( screenData.initialScreen, {
  tandem: Tandem.GENERAL_MODEL.createTandem( 'screenProperty' ),
  phetioFeatured: true,
  phetioDocumentation: 'Which sim screen is selected, including the home screen',
  validValues: this.screens,
  phetioType: PropertyIO( ScreenIO )
} );
```

I will omit the code comment and update the phet-io doc. The valid values show up in Studio, so I don't think this needs to be very descriptive. How does this sound:

```
Indicates which screen is selected in the simulation
```

**Comment by samreid** [comment]
"Indicates" sounds like a one-way process, like it is just showing a value.  But it can also be used to set which screen is showing.  So maybe "Determines which screen is selected in the simulation"?

**Comment by chrisklus** [comment]
Oh right, thanks. That sounds good to me.

**Comment by chrisklus** [comment]
Thanks! @zepumph or @samreid please spot check and close if all set. Commit is https://github.com/phetsims/joist/commit/4e442e6241307a16d7bb537dc0843e355c73d303.

**Comment by samreid** [comment]
That commit looks good to me, thanks.  Closing.
