### ISSUE TITLE
many sims are not using ScreenIcon

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#626]
`ScreenIcon` was created so that home screen and navbar icons have a consistent size, and we could easily change that consistent size in one place.  It has existed since 6/29/15, and history can be found in https://github.com/phetsims/joist/issues/259.

Looking at recently-published sims many of them (including Number Line, Wave Interference, and EFAC) are not using `JOIST/ScreenIcon`.  Maybe this is due to a lack of awareness of `ScreenIcon`.    But this is building technical debt, and it will make adjusting icons sizes expensive (something we've done at least once before). 

Recommendations:

- [x] Create a 'chip away' list of sims that need to be converted to`ScreenIcon`.
- [x] In `JOIST/Screen` constructor, add the following assertions:

```js
assert && assert( !options.homeScreenIcon || options.homeScreenIcon instanceof ScreenIcon, 'invalid homeScreenIcon' );
assert && assert( !options.navigationBarIcon || options.navigationBarIcon instanceof ScreenIcon, 'invalid navigationBarIcon' );
```

Those assertions can also be used to create the 'chip away' lists.  Put them in `Screen`, then run aqua locally to identify sims that aren't using `ScreenIcon`.

Assigning to @ariel-phet to decide if this should be done, and (if so) prioritize and assign.

**Comment by pixelzoom** [comment]
A few of my older sims that pre-dated `ScreenIcon` have been converted in the above commits.

**Comment by pixelzoom** [comment]
The easiest way to convert existing icons is to wrap them in `ScreenIcon`.

Here's an example were the existing icons are `Image` nodes.

Before:

```js
      homeScreenIcon: new Image(...),
      navigationBarIcon: new Image(...),
```


After:

```js
      homeScreenIcon: new ScreenIcon( new Image(...), {
        maxIconWidthProportion: 1,
        maxIconHeightProportion: 1
      } ),
      navigationBarIcon: new ScreenIcon( new Image(...), {
        maxIconWidthProportion: 1,
        maxIconHeightProportion: 1
      } ),
```

By default, `ScreenIcon` puts a margin around the icon that you provide. Setting `maxIconWidthProportion: 1` and `maxIconHeightProportion: 1` prevents this, so that your icons will look the same after they are wrapped.

**Comment by ariel-phet** [comment]
Considering that this seems pretty quick, it seems reasonable to me to make a chip-away issue. I will mark as high-priority for dev meeting just to see if there are any objections (seems potentially doable by an intern)

**Comment by samreid** [comment]
@jbphet & @ariel-phet recommended proceeding with this as a chip-away issue.  Assigning all developers to chip away at this, then sometime in the future, we will switch the assertions on.

**Comment by jessegreenberg** [comment]
I got sims I am responsible for and the scenery-phet and sun demos. Here is a list of whats left:

- [ ] area-builder
- [ ] area-model-algebra
- [ ] area-model-introduction
- [ ] area-model-multiplication
- [ ] arithmetic
- [ ] balancing-act
- [ ] bending-light
- [ ] blast
- [ ] build-a-fraction
- [ ] build-an-atom
- [ ] circuit-construction-kit-ac
- [ ] circuit-construction-kit-black-box-study
- [ ] circuit-construction-kit-common
- [ ] circuit-construction-kit-dc
- [ ] circuit-construction-kit-dc-virtual-lab
- [ ] color-vision
- [ ] coulombs-law
- [ ] density
- [ ] energy-forms-and-changes
- [ ] estimation
- [ ] expression-exchange
- [ ] fluid-pressure-and-flow
- [ ] fraction-matcher
- [ ] fractions-equality
- [ ] fractions-intro
- [ ] fractions-mixed-numbers
- [ ] gene-expression-essentials
- [ ] interaction-dashboard
- [ ] isotopes-and-atomic-mass
- [ ] make-a-ten
- [ ] masses-and-springs-basics
- [ ] molecule-shapes
- [ ] molecule-shapes-basics
- [ ] number-line-integers
- [ ] number-play
- [ ] pendulum-lab
- [ ] phet-io-test-sim
- [ ] plinko-probability
- [ ] projectile-motion
- [ ] proportion-playground
- [ ] ratio-and-proportion
- [ ] rutherford-scattering
- [ ] tambo
- [ ] under-pressure
- [ ] vibe
- [ ] wave-interference
- [ ] waves-intro

**Comment by jessegreenberg** [comment]
@pixelzoom do you recall why `maxIconWidthProportion` and `maxIconHeightProportion` default to 0.85?  It seems like 1 would generally be the desired value.

**Comment by pixelzoom** [comment]
The original intent was to create an icon, pass it to ScreenIcon, and let ScreenIcon put it on a background with a margin around it.  So the 0.85 was what we decided on for a standard margin.  The icons that we're retrofitting have the background and margin built into them, so that's why we're using 1.

**Comment by zepumph** [comment]
My sims have been completed above. I also did whatever common code repos I saw in the list (vibe and tambo). 

Note phet-io-test-sim and vibe didn't have any usages as far as I saw. I checked them off.

**Comment by chrisklus** [comment]
I did my sims in the above commits.

**Comment by samreid** [comment]
I addressed several repos.  I didn't see any occurrences in circuit-construction-kit-common or under-pressure, so I wasn't sure if I was searching in the wrong way, or if those didn't need changes.

**Comment by Denz1994** [comment]
I finished my sims from above.

**Comment by pixelzoom** [comment]
Shall we set a deadline for adding the assertion to check this? I'm concerned that we've done a bunch of work to address this, but new cases will be introduced.   @jbphet @jessegreenberg when do you think you can complete your repos?

**Comment by jessegreenberg** [comment]
Sorry, mine were done in https://github.com/phetsims/joist/issues/626#issuecomment-628328164 I just forgot to check off rutherford-scattering.

**Comment by jbphet** [comment]
I've finished the sims assigned to me, will check CT tomorrow morn to see if it's causing any failures.

**Comment by chrisklus** [comment]
from 06/18/20 dev meeting:

Thanks all, looks like we're ready to close!
