### ISSUE TITLE
SimLauncher should be an es6 module singleton

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#630]
From https://github.com/phetsims/joist/issues/621

Since SimLauncher now holds state, I think it is a bit more idiomatic to make SimLauncher a singleton, and export it as a lowercase `simLauncher`, which is instantiated with the new operator.

This would mean a change to all sims. @samreid what do you think?

**Comment by samreid** [comment]
It seems to me that SimLauncher should be a `class` and have an instance returned.  Not sure if we should double check that with @pixelzoom or @jonathanolson.  Also, I won't have time to work on that soon.  @zepumph how do you want to proceed?

**Comment by pixelzoom** [comment]
@samreid Are you suggesting to use the Singleton pattern, something like this?

```
// simLauncher.js

class SimLauncher {...}

const simLauncher = new SimLauncher( ... );

joist.register( 'simLauncher', simLauncher );
export default simLauncher;
```

**Comment by samreid** [comment]
Yes.

**Comment by zepumph** [comment]
Implemented above. @samreid please spot check. It involved re-running `grunt modulify` on every sim repo, and so I found a few places where img data was changed, but I brought it along in these commits because it was too prevalent to try to revert just the image changes. Does that mean that people aren't running grunt modulify along with image file changes? Should be make a new issue or mark that for dev meeting PSA? 

Otherwise it was a simple and straight forward rename/class conversion.

**Comment by zepumph** [comment]
REpeating https://github.com/phetsims/joist/issues/630#issuecomment-625478118 because it was hidden:

>Implemented above. @samreid please spot check. It involved re-running grunt modulify on every sim repo, and so I found a few places where img data was changed, but I brought it along in these commits because it was too prevalent to try to revert just the image changes. Does that mean that people aren't running grunt modulify along with image file changes? Should be make a new issue or mark that for dev meeting PSA?

>Otherwise it was a simple and straight forward rename/class conversion.

I also found a few more, that for some reason didn't get modulified and were showing up in CT.

**Comment by zepumph** [comment]
CT is clear for this issue now.

**Comment by samreid** [comment]
I reviewed the changes in SimLauncher and they looks great (both the ES6 class and singleton).  I added a PSA to the dev meeting agenda.  Thanks @zepumph!  Closing.
