### ISSUE TITLE
PhetioObject call to sim.runOnNextFrame fails when sim doesn't exist

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#631]
In https://github.com/phetsims/joist/commit/eff01ed11b014d76e4281c6b4d69e47044f7a313, @samreid and I added `Sim.runOnNextFrame` to address performance issues in `PhetioObject.dispose`, see https://github.com/phetsims/natural-selection/issues/61.   Here's its current usage in `PhetioObject.dispose`:

```js
assert && phet.joist.sim.runOnNextFrame( () => { // eslint-disable-line bad-sim-text
  assert && assert( self.phetioMessageStack.length === 0, 'phetioMessageStack should be clear' );
} );
```

@jonathanolson reported that this breaks cases where Nodes are created before a Sim exists (e.g. charges-and-fields) or where no Sim exists (CT, scenery doc).

The proposed workaround is to check to see whether Sim exists, like this: 

```js
assert && window.phet && phet.joist && phet.joist.sim && phet.joist.sim.runOnNextFrame( () => { // eslint-disable-line bad-sim-text
  assert && assert( self.phetioMessageStack.length === 0, 'phetioMessageStack should be clear' );
} );
```

**Comment by pixelzoom** [comment]
Workaround pushed.  @samreid please review and decide (for the purposes of PhET-iO) whether this workaround is a solution, or whether something else is needed here.

**Comment by samreid** [comment]
This workaround seems like it has the opportunity to miss assertions for disposes that happen before joist.sim is assigned.  Perhaps we should bail on this and use axon timer.setTimeout instead.  Or add a this interface to axon timer.  @pixelzoom what do you think?

**Comment by pixelzoom** [comment]
I don't honestly know what the correct solution is here, and haven't reviewed the uses beyond PhetioObject.  Using global `phet.axon.timer` will likely run into similar "undefined" issues, and recall that we experienced circular dependency problems when trying to import timer.js.

**Comment by zepumph** [comment]
Over in https://github.com/phetsims/phet-io/issues/1659, we decided to offload this call from sim, to `timer` which always exists. The PhetioObject usage now calls on `timer.runOnNextFrame`. Closing. Please reopen if there is anything else to discuss.
