### ISSUE TITLE
QueryParametersWarningDialog does not close when you click outside of it

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#632]
The "Invalid Query Parameters" dialog does not close when you click outside of it.  The only way to close it is to click on the 'X' close button.  That's not how other PhET dialogs behave (e.g. About  dialog).

@chrisklus if you might know where this needs to be fixed, would you mind?  Otherwise assign back to me and I'll poke around.  The problem is somewhere in QueryParametersWarningDialog.js, I'm guessing.

Steps to reproduce:
1. Start Natural Selection with `?allelesVisible=bogus`
2. Dialog will appear, see screenshot below.
3. Click outside the dialog and note that it does not close.

<img width="1095" alt="screenshot_321" src="https://user-images.githubusercontent.com/3046552/82282401-f8461f80-9950-11ea-81ff-66977d4573ad.png">

**Comment by chrisklus** [comment]
Good catch @pixelzoom, thanks. I didn't notice any relevant differences in QueryParametersWarningDialog compared to AboutDialog or OopsDialog, but it looks like I cut out some of the show/hide work of Dialog.js by directly using showPopup/hidePopup in Sim.js. Using show/hide from Dialog instead seems to have fixed the problem.

@pixelzoom please review and close if all looks good.

**Comment by pixelzoom** [comment]
Looks good, thanks! Closing.
