### ISSUE TITLE
change wording of "Invalid Query Parameters" dialog

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#635]
Sometimes query parameters are interdependent, and we can't tell which one is invalid.  In cases like that, we don't infer intent, and report all of the dependent query parameter as invalid.  See for example https://github.com/phetsims/natural-selection/issues/9:

![image](https://user-images.githubusercontent.com/7852916/82368305-73034f00-99d2-11ea-892c-b841badecd3a.png)

In https://github.com/phetsims/natural-selection/issues/9#issuecomment-634957072, @ariel-phet suggested that we change the wording:

> Perhaps we could say in the dialog "one or more of the Query Parameters listed below has invalid values" so it is perhaps more clear that we are just listing all the parameters, and at least one has a mistake? I agree we should not try to suss out user intent.

... and @amanda-phet gave this a 👍.

Before I change the text, a couple of questions:

* Are you OK with this wording when there's only 1 query parameter shown? 

* Are you OK with this wording when we know there are no interdependent query parameters, and all of the query parameters listed are definitely wrong?  (No idea how we'd determine this in the Dialog.)

I recommend that we don't go down the path of multiple wordings, with logic to select the correct wording, and multiple strings to translate.  This is supposed to be simple.

Mentioning @chrisklus, the author, in case he has any opinions.

**Comment by amanda-phet** [comment]
>Are you OK with this wording when there's only 1 query parameter shown?

Yes

>Are you OK with this wording when we know there are no interdependent query parameters, and all of the query parameters listed are definitely wrong? (No idea how we'd determine this in the Dialog.)

This gives me pause. This could be confusing in the case you mentioned, but also if every query parameter the user decided to use was wrong (and therefore listed), they might think we just list all in the dialog, not just the incorrect ones. I'm having a hard time even describing this case, but hopefully that makes sense. 

I don't have a strong preference for either the current wording or the one being proposed by @ariel-phet , but I slightly prefer keeping it as-is.

**Comment by pixelzoom** [comment]
5/28/2020 NS design meeting @amanda-phet @ariel-phet @kathy-phet 

I will change to "One or more of these ... "

**Comment by pixelzoom** [comment]
Revised in the above commit.  Lines were getting a bit long, so I also adjusted the line breaks. Example screenshot below from Natural Selection.  @ariel-phet please review. If this looks OK to you, feel free to close.

<img width="738" alt="screenshot_357" src="https://user-images.githubusercontent.com/3046552/83197720-2b2fa680-a0fb-11ea-87f1-654aee050669.png">

**Comment by ariel-phet** [comment]
Looks good.
