### ISSUE TITLE
Add sound for PhetMenu

### ISSUE THREAD

**Issue by jbphet** [phetsims/joist#637]
I pointed out today in the 7/7/2020 sound design meeting for Ratio & Proportion that the PhET menu button doesn't produce any sound.  We decided to add the generic button sound for now, review next week, and go from there.

**Comment by jbphet** [comment]
We reviewed this in the 7/14/2020 sound design meeting and decided that the generic sound is good for now, and @emily-phet with review it with @kathy-phet et al sometime soon.  We may revisit in the future.

**Comment by emily-phet** [comment]
I don't recall this conversation, but I think the sounds is good. Closing.
