### ISSUE TITLE
do not explicitly set layoutBounds to default value

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#638]
Related to https://github.com/phetsims/joist/issues/542, and discussed with @ariel-phet while investigating a workaround for https://github.com/phetsims/ph-scale/issues/168.

The default layoutBounds are defined in ScreenView.js:

`const DEFAULT_LAYOUT_BOUNDS = new Bounds2( 0, 0, 1024, 618 );`

@ariel-phet and I were trying to identify which sims use non-default layoutBounds. The straightforward way to do that is to search for "layoutBounds:".   But that identifies a number of sims that are explicitly setting `layoutBounds` to the default value.   That is unnecessary and (in this case) undesirable.

@ariel-phet asked me to remove these:

- [x] ChainsView.layoutBounds
- [x] ChargesAndFieldsScreenView.layoutBounds
- [x] EESharedConstants.LAYOUT_BOUNDS
- [ ] FBConstants.SCREEN_VIEW_LAYOUT_BOUNDS
- [x] HookesLawConstants.SCREEN_VIEW_OPTIONS.layoutBounds
- [x] LeastSquaresRegressionScreenView.layoutBounds
- [ ] MakeATenConstants.LAYOUT_BOUNDS
- [x] MoleculeShapesScreenView.layoutBounds
- [ ] NLIConstants. NLI_LAYOUT_BOUNDS
- [x] PlinkoProbabilityCommonView.layoutBounds
- [x] ProportionScreenView.layoutBounds
- [ ] RatioAndProportionScreenView.LAYOUT_BOUNDS
- [ ] VectorAdditionConstants.SCREEN_VIEW_BOUNDS

@ariel-phet also requested a dev-meeting PSA, to remind developers:

(1) Do not use non-default layoutBounds.
(2) Do not explicitly set layoutBounds to the default.

**Comment by pixelzoom** [comment]
5 of the above sims are doing significant computations with the layoutBounds, and it makes sense to have a sim-specific constant instead of using ScreenView.DEFAULT_LAYOUT_BOUNDS directly.  So I did not change these:

- [ ] FBConstants.SCREEN_VIEW_LAYOUT_BOUNDS
- [ ] MakeATenConstants.LAYOUT_BOUNDS
- [ ] NLIConstants. NLI_LAYOUT_BOUNDS
- [ ] RatioAndProportionScreenView.LAYOUT_BOUNDS
- [ ] VectorAdditionConstants.SCREEN_VIEW_BOUNDS

Modifying the PSA accordingly:

(1) Do not use non-default layoutBounds.
(2) Do not explicitly set layoutBounds to the default, unless you have a need to do computations with the layoutBounds and it's not available via `this.layoutBounds`.   In that case, factor out a sim-specific constants, like `MySimConstants.LAYOUT_BOUNDS = ScreenView.DEFAULT_LAYOUT_BOUNDS`.  See for example the above 5 sims.

**Comment by zepumph** [comment]
I wasn't really sure from this issue if anything should change in my sims listed above: Ratio and Proportion. It sounds like the answer is "no." But I'm not positive.

**Comment by Denz1994** [comment]
From Dev Meeting on 07/16/20:

Discussion:
PSA from https://github.com/phetsims/joist/issues/638#issuecomment-657697065 has been relayed to devs.

@samreid Some of these cases mentioned above might have been defensive measures in case the standard `LAYOUT_BOUNDS`  were to change in the future. Instead, create a specific constant for situations like this.
