### ISSUE TITLE
incorrect scaling of AboutDialog

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#639]
Reported in https://github.com/phetsims/ph-scale/issues/168. Possibly related to https://github.com/phetsims/joist/issues/586.

AboutDialog scaling is incorrect.  Unclear whether this issue is specific to AboutDialog, or is a more general problem with Dialog scaling.  There are 2 main problems:

(1) On non-Home screens, long credits can result in the About dialog overlapping the navigation bar, and/or falling off the top of the screen.  See screenshot below. Dialogs should always be scaled to fit the ScreenView layoutBounds.

<img width="1048" alt="screenshot_427" src="https://user-images.githubusercontent.com/3046552/87203788-948d0280-c2c0-11ea-995d-12946c1717fd.png">

(2) On the Home screen, the dialog size is different than the other screens. See screenshot below. This may be because HomeScreenView.js is using non-standard layoutBounds:

`const LAYOUT_BOUNDS = new Bounds2( 0, 0, 768, 504 );`

<img width="1046" alt="screenshot_428" src="https://user-images.githubusercontent.com/3046552/87203810-a1a9f180-c2c0-11ea-81b7-a051f9ae7fa1.png">

**Comment by pixelzoom** [comment]
@ariel-phet asked me to apply the scaling workaround from #586 to AboutDialog.  I noted that this would result in a smaller About dialog in all sims, as well as the Home screen.  And a sim with long credits may still encounter the problem.

A real solution is still needed, probably in connection with #586. Assigning to @ariel-phet to prioritize and assign.

**Comment by ariel-phet** [comment]
I am currently marking this work deferred. As long as this workaround is working for the moment the work is not a major priority. It is important the about dialog fit within the bounds and everything in it can be read, but the aethetics of this dialog are not of major concern (no effect on pedagogy etc).

A long term solution should be found at some point.

**Comment by KatieWoe** [comment]
Noting here that the size difference is fairly noticeable and may be difficult to read in cases where there is a lot of text. Should be fine for now, but I will keep an eye out and make an issue if a future sim seems to have too small of text. Seen on master 7/14/2020

**Comment by KatieWoe** [comment]
Potential example of this in Acid Base Solutions. Has a fairly large amount of text and a home screen where things would be smaller. May not be problematic in this case, but shows how it might get there.
Published:
![published](https://user-images.githubusercontent.com/41024075/87476692-0e382f80-c5e4-11ea-8dc7-cf034e53ef4a.png)
Master:
![new](https://user-images.githubusercontent.com/41024075/87476704-12644d00-c5e4-11ea-88e2-2045dc3e4db0.png)

**Comment by pixelzoom** [comment]
Looks like @jonathanolson removed the workaround in https://github.com/phetsims/joist/commit/695644fbf2d8293d9d0e043bfac58dff51d1c245 for https://github.com/phetsims/joist/issues/586.  

Remaining AboutDialog tweaks will be done in https://github.com/phetsims/joist/issues/586.

Closing.
