### ISSUE TITLE
review TODO items in code

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#64]
Review the 22 TODOs in source code, including 9 in PropertySet. Address them, or make GitHub issues.

**Comment by samreid** [comment]
Well, there are 32 occurrences of TODO under joist/js, so let's reopen this issue for joist.  Address the issues or make them GitHub issues.

**Comment by ariel-phet** [comment]
@samreid how many TODO issues are currently in Joist?

**Comment by samreid** [comment]
26 matches in 14 files.

**Comment by pixelzoom** [comment]
All TODO items should reference a GitHub issues.  There are current 20+ that do not.

**Comment by jonathanolson** [comment]
Side-note: Should I do this for dot/kite/scenery?

**Comment by pixelzoom** [comment]
Imo, any TODO item in production (i.e. published) code should have an associated GitHub issue.  Less strict would be to require that only in common code.  Up to @ariel-phet to set the policy.

**Comment by ariel-phet** [comment]
I am marking this issue for developer meeting as it seems to warrant a larger discussion of pros cons. Although I feel like chipping away at TODO in joist seems worthy of attention.

**Comment by jonathanolson** [comment]
I feel like cleaning this up is also good. 300+ TODOs are marked in Scenery alone, so I'll spend some of my cleanup-time triaging those, until every TODO is marked with an issue reference.

**Comment by samreid** [comment]
> I am marking this issue for developer meeting as it seems to warrant a larger discussion of pros cons.

As with many maintenance issues, this is a tradeoff between building new features/simulations vs improving our foundation. We could easily go >1 years working on TODOs, addressing lint concerns, improving the quality of our code, etc, but at the end of that time we wouldn't have any new simulations.  So we must pick a nice point within this spectrum.

**Comment by pixelzoom** [comment]
> ... We could easily go >1 years working on TODOs, ...

I believe the dev meeting discussion is going to be whether to create a GitHub issue for each TODO, not where to address all the TODOs.

**Comment by andrewadare** [comment]
@ariel-phet suggested that we make this the next "chip-away" priority after removing deprecated code (https://github.com/phetsims/chipper/issues/515).

@samreid suggested that we add a lint rule to common code repos in order to make the outstanding TODO items more prominent.

**Comment by andrewadare** [comment]
Consensus: we will try adding an eslint rule (to emit warnings, not errors). Leaving flagged for dev meeting until it gets implemented.

**Comment by samreid** [comment]
> Leaving flagged for dev meeting until it gets implemented.

It was implemented in #380, but perhaps we should leave this marked for developer meeting so we can choose a "volunteer" to help address the new lint issues.

**Comment by samreid** [comment]
Today I became volunteered.

**Comment by samreid** [comment]
In the above commit, I removed todo-should-have-issue rule (set from warning to off).  This will take the pressure off from having to address this quickly.  Please pull chipper.   I will re-enable the rule when the warnings are addressed.

**Comment by samreid** [comment]
In the above commit, I decided the input listener for the large screen button is working nicely and does not need to be refactored to use ButtonListener, hence I removed that TODO.

**Comment by samreid** [comment]
The commit https://github.com/phetsims/chipper/commit/48b774fa2b21d53076ff0cd340928acf25f129dc also turned on the "TODOs require Issues in Joist" lint rule.

Closing.
