### ISSUE TITLE
Multi-screen Sim Screen intro text

### ISSUE THREAD

**Issue by terracoda** [phetsims/joist#642]
Related to issues #641 and #496, while reviewing RaP, I noticed the first sentences are not following the template provided in HomeScreem.md

```html
<h1>{{ScreenName01}} Screen, {{SimName}}</h1>
   <!-- Screen specific intro with Screen Parameters -->
   <p>The interactive {{ScreenName01}} Screen changes as you play with it. It has a Play Area and a Control Area. The Play Area {{DESCRIPTION OF PLAY AREA FOR SCREEN 01}}. The Control Area has {{DESCRIPTION OF CONTROL AREA FOR SCREEN 01,}} and a reset button to reset the sim.</p>
   <!-- Screen Specific Interaction Hint -->
```

**Screenshot of RaP's Create Screen**
![Screen Shot 2020-07-16 at 12 30 37 PM](https://user-images.githubusercontent.com/1902116/87687326-2df46280-c760-11ea-838b-91ca0607463a.png)

The first paragraph would be better as:
```html
<p>The interactive Create Screen changes as you play with it. It has a Play Area and a Control Area. </p>
<!-- The rest of the screen summary -->```

**Comment by terracoda** [comment]
@zepumph, I think I forgot we had this pattern already worked out which is why @Matthew-Moore240 did not use this sentence in the design doc for RaP.

**Comment by zepumph** [comment]
This is implemented above. Please review

**Comment by terracoda** [comment]
The P1 in Rap now looks good, so I assume this issue can be closed.
Thanks @zepumph.
