### ISSUE TITLE
problems with screens query parameter

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#644]
This started out as a specific problem in https://github.com/phetsims/ph-scale/issues/171.  After digging in, more problems were discovered, so this general issues was created.

The problems, which can be demonstrated in ph-scale:

- [x] (1) `screens=4,1` displays a warning dialog. But you end up with 2 copies of screen 1 (Macro), both of which are selected on the home screen.  See screenshot below.

- [ ] (see https://github.com/phetsims/query-string-machine/issues/42) (2) `screens=Macro,Micro` fails hard. This is likely a general problem with not being able to display a warning dialog when the `elementSchema` of a query parameter is violated. 
**>>> TO BE ADDRESSD IN phetsims/query-string-machine#42**

- [ ] (see https://github.com/phetsims/query-string-machine/issues/42) (3) `screens=1.2` fails hard. There's apparently no verification that values are integers. Unfortunate since '.' used to be the separator for arrays.
**>>> TO BE ADDRESSD IN phetsims/query-string-machine#42**

- [x] (4) unit tests in selectScreensTests.js are insufficient. 

<img width="1060" alt="screenshot_434" src="https://user-images.githubusercontent.com/3046552/88109782-54ebd380-cb68-11ea-9f65-01f628926335.png">

**Comment by pixelzoom** [comment]
To address problem (1) above, @samreid started with https://github.com/phetsims/joist/commit/3cd429cccc852148956a00b053a1ae790c9c4dba.   I noted that `forEach` is the wrong iterator to use in this case, and results in the query parameter being identified multiple times in the warning dialog.  I addressed this in https://github.com/phetsims/joist/commit/c29f824fc60c6ff9efbbd540d17d5764fe56e87e and https://github.com/phetsims/joist/commit/e12b7b2f00fe9a1e540032e9d5ecb1b1f8664721.  

Some test cases are:

```
// These will start without error
ph-scale-basics_en.html?screens=1
ph-scale_en.html?screens=1,2,3
ph-scale_en.html?screens=2
ph-scale_en.html?screens=2,3

// These contain errors, display warning dialog, and revert to default.
ph-scale-basics_en.html?screens=2,1
ph-scale_en.html?screens=1,4 
```

I would like @samreid to address this fix for problem (1).

**Comment by pixelzoom** [comment]
Assign @chrisklus to address problems (2), (3), (4) when he returns.  Priority high, since this is blocking ph-scale RC.

**Comment by pixelzoom** [comment]
Assigning @chrisklus to address problems (2), (3), (4) when he returns. Priority high, since this is block publication of all sims, include an in-progress ph-scale RC.

**Comment by samreid** [comment]
It was unclear in https://github.com/phetsims/joist/issues/644#issuecomment-662122814 where @pixelzoom said:

> I would like @samreid to address this fix for problem (1).

@zepumph and I reviewed the changes for (1) and they looked good.  We also added more unit tests in the commit.  Some of the requested tests in https://github.com/phetsims/joist/issues/644#issuecomment-662122814 already had adequate coverage in selectScreenTests.js.  Anything else for (1) @pixelzoom?

**Comment by zepumph** [comment]
@samreid and I tested the above changes and cannot reproduce the case pictured above with two screen one instances. We also created https://github.com/phetsims/query-string-machine/issues/42 to investigate catching warnings when a parameter doesn't pass its validity check in the provided schema. 

From here we think this is ready to unblock publication, but defer to @pixelzoom for that decision.

We also want to keep this assigned to @chrisklus to spot check the changes, since he was a primary author of the screens refactor, and we also defer to him for writing a few more tests, (4) from the above list.

**Comment by pixelzoom** [comment]
`screens` is a public query parameter, so it's supposed to fail gracefully -- display a warning dialog and revert to defaults.  It does not do that and fails hard for the 2 outstanding cases described in https://github.com/phetsims/joist/issues/644#issue-663325840.

**Comment by pixelzoom** [comment]
`screens` is a public query parameter, so it's supposed to fail gracefully -- display a warning dialog and revert to defaults.  It does not do that and fails hard for the 2 outstanding cases described in https://github.com/phetsims/joist/issues/644#issue-663325840.  So if it were my call, I feel that this is still plenty buggy, and still blocks publication.  But I'll be happy to defer to a designer.

**Comment by zepumph** [comment]
I totally agree with you! My feeling is that this issue was related to a bug in `selectScreens.js`, but exposed further issues with QSM `public` schema field. Let's treat these as two separate items. @chrisklus please review this issue in the context of `selectScreens.js`, and let's meet over in a new blocking publication issue (https://github.com/phetsims/query-string-machine/issues/42) to discuss the changes needed for QSM.

Unmarking blocks publication here.

**Comment by chrisklus** [comment]
Changes to `selectScreens` and added tests look good. Thanks for handling this @zepumph @samreid @pixelzoom. Ready to close if the remaining items are to be handled separately in https://github.com/phetsims/query-string-machine/issues/42.

**Comment by pixelzoom** [comment]
Before closing, I need to test this in ph-scale, and cherry-pick to ph-scale 1.4 and ph-scale-basics-1.4.

**Comment by zepumph** [comment]
>Changes to selectScreens and added tests look good. 

@chrisklus, https://github.com/phetsims/joist/commit/bde554917ede4088394bd8023cea6bce843499d2 added tests that were specifically buggy that @pixelzoom reported, but I didn't feel like @samreid and I spent time thinking through other cases. Can you think of any other tests to add?

**Comment by pixelzoom** [comment]
Ugh... I just finished cherry-picking, and now there are more commits?

**Comment by pixelzoom** [comment]
Closing.  If additional unit tests are needed, they'll be tracked in https://github.com/phetsims/joist/issues/643.
