### ISSUE TITLE
Safari Full Screen dev tools don't show up

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/joist#647]
**Test device**
Dirac
**Operating System**
Mac 10.12
**Browser**
Safari 12
**Problem description**
Found during https://github.com/phetsims/QA/issues/515, but occurs in other sims. Most likely to impact phet-io, but fairly minor even then.
If you have the dev tools, such as the console, open in Safari and put the sim in full screen mode, there will be a black space where the dev tools would be, but the tools don't show up. If you exit full screen everything appears normal again. Assigning @ariel-phet for priority and assignment.

**Visuals**
![Screen Shot 2020-07-28 at 3 30 49 PM](https://user-images.githubusercontent.com/41024075/88726036-3c406800-d0ea-11ea-802f-3b2cc1d174c7.png)
![Screen Shot 2020-07-28 at 3 30 40 PM](https://user-images.githubusercontent.com/41024075/88726038-3cd8fe80-d0ea-11ea-860b-3c4f3235bb8e.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Area Builder‬
URL: https://phet.colorado.edu/sims/html/area-builder/latest/area-builder_en.html
Version: 1.1.20 2020-06-23 11:51:07 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15
Language: en-US
Window: 1222x643
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"area-builder":{"sha":"ab41564f","branch":"HEAD"},"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"5e33541f","branch":"HEAD"},"babel":{"sha":"bc83d3fa","branch":"master"},"brand":{"sha":"101869d9","branch":"HEAD"},"chipper":{"sha":"2643cc44","branch":"HEAD"},"dot":{"sha":"bf6f038b","branch":"HEAD"},"joist":{"sha":"0d821aa5","branch":"HEAD"},"kite":{"sha":"dce9765e","branch":"HEAD"},"phet-core":{"sha":"745d5fbb","branch":"HEAD"},"phetcommon":{"sha":"99c3655b","branch":"HEAD"},"phetmarks":{"sha":"3fdfece0","branch":"HEAD"},"scenery":{"sha":"4a65c37f","branch":"HEAD"},"scenery-phet":{"sha":"7def38a3","branch":"HEAD"},"sherpa":{"sha":"a7ccb78f","branch":"HEAD"},"sun":{"sha":"9f2d40d5","branch":"HEAD"},"tandem":{"sha":"0ad35fb7","branch":"HEAD"},"vegas":{"sha":"32591f0e","branch":"HEAD"},"vibe":{"sha":"b7f457e4","branch":"HEAD"}}

</details>

**Comment by ariel-phet** [comment]
@KatieWoe I think this is a good find, but likely not worth fixing

My feeling is that we can just close this issue as `wontfix` -- I would feel differently if the the dev tools did not appear for safari in general since that would be important for debugging. However, debugging the sim while in fullscreen mode in safari seems unlikely to come up. If it does, we can address the issue at that time, but I think it is unlikely to be a problem.
