### ISSUE TITLE
Incorrect scaling of Options dialogs and sim-specific dialogs

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/joist#650]
#### `joist.OptionsDialog`, whose content is sim-specific (search for "createOptionsDialogContent:")
- [x] gravity-force-lab @zepumph 
- [x] tambo @jbphet 

#### Sim-specific dialogs:
- [x] gene-expression @jbphet 
- [x] masses-and-springs @Denz1994 
- [x] plinko-probability @chrisklus

**Comment by zepumph** [comment]
gravity-force-lab was actually gravity-force-lab-basics, and that options dialog is just being used by self voicing stuff. I'm going to check it off. There will be lots of development time if that dialog ends up being used for production.

**Comment by jbphet** [comment]
Updates made to gene-expression-essentials and tambo, unassigning.

**Comment by Denz1994** [comment]
Masses and springs was fixed to account for the recent changes in dialog.

**Comment by chrisklus** [comment]
Plinko Probability was updated in the commit above. Assigning back to @ariel-phet to close if everything's set.

**Comment by ariel-phet** [comment]
I think that will do it for this issue, thanks all!
