### ISSUE TITLE
Odd partial flash of screen when loading a downloaded html of sim

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/joist#651]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/525.
When saving an html copy of the sim and then opening it, there is a brief, partial flash of the home screen. This appears odd, but does not seem to cause any problems.

**Visuals**
![oddflashwhenstartingdownload](https://user-images.githubusercontent.com/41024075/89471433-5f4ac780-d73b-11ea-8288-ea967c10a499.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪States of Matter‬
URL: file:///C:/Users/PhET%20QA/Downloads/_States%20of%20Matter_.html
Version: 1.2.0-rc.1 2020-07-31 21:24:36 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by samreid** [comment]
@ariel-phet can you please review this issue and advise?

**Comment by ariel-phet** [comment]
@KatieWoe 

I don't think this particular issue is worth worrying about. The majority of people who want to use a sim offline are either going to click the "download" button on the sim page or use something like our new offline installer. 

Marking as `wontfix` and closing.
