### ISSUE TITLE
Visual/Interaction Design for Accessibility Options and related Quick Menus for individual features

### ISSUE THREAD

**Issue by terracoda** [phetsims/joist#652]
PhET will hopefully publish it's first sim with a Self-Voicing feature as early as March 2021. Self-voicing is not on by default and needs to be enabled by the learner. When enabled, a subset of descriptions are read aloud directly through the browser, distinct from the experience of using a screen reader. 

Publication will require there be a sustainable long-term way for self-voicing to be enabled, and a way for making selections amongst self-voicing options (e.g., regarding verbosity level, voice, etc.). There's a lot of visual design to be done, and we would like this to proceed through a collaboration across a11y folks and the broader PhET team. 

In our first meeting (Friday Aug 7, 2020), we discussed possible locations for a general options icon, and where access to selected individual features could be accessed once enabled.

I am opening this issue, so work can continue on this.

Prior to the meeting I had sketeched out ideas here in these google slides (slides 3 to 5) https://docs.google.com/presentation/d/1Koh72FrkzbCbhPdByvDFcRaMpc6iwZpa41b-ni7CGKA/edit#slide=id.g8b4de1ccfb_0_12

But then, after @amanda-phet thinks that we can fit one more icon in the bottom navbar - an "A11y Options" icon or a "General Options or Settings" icon. This would create a dialog with all the Options.

Once options were selected, we discussed potentially having feature icons along the left side of the sim with little drawer-like pull-out menus as needed - possibly similar to slide 5, but on the other side of the sim and a different icon.

Assigning to @amanda-phet and @arouinfar to sketch out some more PhET-like sketches :-)

**Comment by emily-phet** [comment]
@amanda-phet @arouinfar 
Can you let us know when you've discussed, and who'll be taking the lead on this? 

Regarding timeline - there's essentially 18 weeks until we need to have designs finalized, implemented, and locked in for first publication. The first sim to be published with this feature (GFL:B) will move from the design/implement/iterate phase and moved into the code review/dev test/rc test phase starting Dec 18th, on-track for a March 31st publication deadline.

**Comment by amanda-phet** [comment]
I can think about this in about a week, but not any sooner. Happy to discuss it further and potentially take on the visual design at that point.

**Comment by arouinfar** [comment]
I can start working on this on Monday.

**Comment by terracoda** [comment]
@amanda-phet and @arouinfar, you are both awesome!

**Comment by jbphet** [comment]
In one of the recent sound design meetings we were talking about how to control the relative volume of UI sounds, sim specific sounds, and self-voicing.  @BLFiedler mentioned that he'd seen something like that before, and later sent the screenshot below.  I thought this might be a useful reference for some of the elements that will go into the accessibility options dialog.

![volume-controls](https://user-images.githubusercontent.com/3082831/92664174-83f90880-f2c0-11ea-96a2-beb59a57b584.png)

**Comment by terracoda** [comment]
@amanda-phet and @arouinfar, the last 2 interviews were super positive and both made use of the zoom feature, too. The next steps for self-voicing is visually brainstorming how we would incorporate the Options menu and any particular feature tool menus when special features are enabled.

Both interviewees commented that it would be nice if the Options menu was easier to find and that the Self-Voicing Quick menu was easier to find.

We still have time, but let me know what availability you might have to start sketching possibilities out.

**Comment by emily-phet** [comment]
@arouinfar 

Can you please let us know when you'll be able to do the initial mockups? We really need to have this sorted by Dec. 18th (locked in, no more changes prior to publication)...which is coming up fast.

**Comment by terracoda** [comment]
I am okay with closing this issue. Implementation has started. I imagine issues will start popping up as we have something to review.
