### ISSUE TITLE
Potential issue opening screenshots

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/joist#653]
Seen during https://github.com/phetsims/QA/issues/531, but I think it has happened elsewhere.
I have had an issue a few times now where I try to open a screenshot created in the sim, but it doesn't open properly in the viewer. Upon creating the screenshot, a download bar appears on the bottom of the browser with the file. Clicking it would normally open the default photoviewer and display the image. When the issue happens, the viewer opens but is completely blank and looks like it is failing to load. If I close it and try again, it will usually work. I have had an instance where I got a pop-up error that I didn't get a chance to see. In all cases so far, the screenshot seems to be made fine, and I can open it from the folder, or even from the download bar later.
I have only seen this so far on my Win 10 device. I think it has also only been Chrome, but I'm less sure about that. However, this started happening relatively recently and I can't seem to reproduce it regularly, so it is hard to say for sure.

**Comment by KatieWoe** [comment]
This was discussed with @samreid over zoom.

**Comment by KatieWoe** [comment]
I just had this happen with an image downloaded from github, so I am fairly sure now that it is my computer

**Comment by samreid** [comment]
@KatieWoe can this issue be closed? If not, what do you recommend for this issue?

**Comment by KatieWoe** [comment]
I think so. Especially since I saw it outside of a sim, I don't think there's anything on our end to do.
