### ISSUE TITLE
projectorModeCheckbox PhET-iO tree structure

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#654]
Over in https://github.com/phetsims/states-of-matter/issues/346, @jbphet and I realized it was weird that there was a linked property right next to the checkbox. I think it would be best to not link there, and instead just have the passed in property be called "property" I will take a look.

Here is what the structure looks like:

![image](https://user-images.githubusercontent.com/6856943/90830082-7b2e9b80-e2ed-11ea-81ee-6e0415413834.png)

**Comment by zepumph** [comment]
This is now the new structure. Notice that it isn't blue, because it isn't linked, but we also don't have an extra `projectorModeEnabledProperty` next to the linked `property`:

**Comment by arouinfar** [comment]
@zepumph the tree structure looks good to me.

@kathy-phet @jbphet and I discussed this a bit in https://github.com/phetsims/states-of-matter/issues/346, and we decided it wasn't critical for the 1.2.0 release. Since it can't be included in a MR, I'm fine with leaving it out. Clients should be using the query parameter for projector mode, anyway.

**Comment by samreid** [comment]
This looks like the optimal implementation to address these issues, nice work!  I'm also glad we tried out the strategy to make API calls to linked elements work the same as calls to core elements.  I don't have any recommendations for the review.  I don't mind that it won't be in States of Matter 1.2.0, it will go out with other PhET-iO simulations published after today.  @zepumph can this be closed?

**Comment by zepumph** [comment]
>Clients should be using the query parameter for projector mode, anyway.

I see that `colorProfile` is used in client guides but isn't marked as "public" I also see that for `?locale`. I want to add that to those. @arouinfar please note that any query parameter discussed in those guides should be marked as "public:true" in the schema (in [initialize globals](https://github.com/phetsims/chipper/blob/master/js/initialize-globals.js)). This adds support for the graceful dialog. It can be really hard to keep track of all the public usages, so another set of eyes would be nice to have. See https://github.com/phetsims/chipper/issues/974 to fix that.

Otherwise I am ready to close.
