### ISSUE TITLE
HomeScreenModel could use some additional documentation

### ISSUE THREAD

**Issue by jbphet** [phetsims/joist#655]
I'm doing some work to improve sound generation for screen selection changes, and I'm working with `HomeScreenModel` as part of this effort.  This class has a public property named `screenProperty` and another named `selectedScreenProperty`.  It's not clear what the difference is, and neither has any documentation beyond visibility and type specs.  I'll figure it out, but it would save time for the next person who has to work with this if there were a sentence or two that described the distinction.

**Comment by samreid** [comment]
I added documentation for this, ready for review.

**Comment by jbphet** [comment]
That looks great - thanks!  Closing.
