### ISSUE TITLE
NavigationBarScreenButton "Assertion failed: Bounds mismatch after validateBounds"

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#656]
When running a multi-screen sim with `?eall`, this fails. @jonathanolson can you take care of this?

```
assert.js:22 Uncaught Error: Assertion failed: Bounds mismatch after validateBounds: [x:(-5,41.72922252010724),y:(-2,37)], expected: [x:(-5,41.72922252010724),y:(0,37)]
    at window.assertions.assertFunction (assert.js:22)
    at Node.js:1332
    at NavigationBarScreenButton.validateBounds (Node.js:1338)
    at TinyStaticProperty.get (TinyProperty.js:45)
    at TinyStaticProperty.get value [as value] (TinyProperty.js:57)
    at NavigationBarScreenButton.getBounds (Node.js:1745)
    at NavigationBarScreenButton.getWidth (Node.js:3105)
    at NavigationBarScreenButton.get width [as width] (Node.js:3107)
    at NavigationBar.js:256
    at baseExtremum (lodash-4.17.4.js:2874)

**Comment by zepumph** [comment]
I'm going to give a ping on this because I'm about to add ?eall to CT testing, so there will likely be lots of red about it.

**Comment by zepumph** [comment]
This is failing CT now.

**Comment by jonathanolson** [comment]
That was a hunt! Looks like NavigationBarScreenButton was mutating the bounds inside an expression (https://github.com/phetsims/joist/commit/2067bb561be21355bc43922b613976b1ac8a4241):

```js
this.focusHighlight = Shape.bounds( this.bounds.setMinY( this.bounds.minY - highlightLineWidth / 2 ) );
```

This caused an internally broken state in the Node itself, which gets caught by the extra assertions.

@zepumph does the above change look safe?

**Comment by jonathanolson** [comment]
Also added logging and removed an extra useless check in the assertions above.

**Comment by zepumph** [comment]
Oh Michael, you naïve little puppy (https://github.com/phetsims/joist/commit/2067bb561be21355bc43922b613976b1ac8a4241).  Thank you so much for the investigation! I really appreciate it. 

Since this was my fault, I wonder if you could put a few words down about how you went about investigating this (just an outline), that I may be able to use in the future if I find a scary scenery-internal assertion like this again.

**Comment by jonathanolson** [comment]
It was mainly narrowing down when the value could have changed (partially with logging), and seeing that it had no Scenery-based change. Then a scan for bounds setters in the relevant files pulled that up!
