### ISSUE TITLE
Should selected HomeScreenButton fire on up instead of down?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/joist#658]
Is there a reason that the selected HomeScreenButton fires on down event instead of up? This is especially noticeable now that the zoom feature is enabled by default. If you go to a multi-screen sim and try to zoom in on the selected screen button, it will go right to that screen rather than allow user to zoom in on button.

Could the button fire on pointer up instead?

**Comment by ariel-phet** [comment]
@jessegreenberg sorry for the delay reply. I see no problem with firing on pointer up for homescreen buttons, especially if it fixes this issue

**Comment by jessegreenberg** [comment]
Change made above. @chrisklus I saw you listed as an author of HomeScreenButton.js would you mind reviewing this change?

**Comment by chrisklus** [comment]
Thanks @jessegreenberg - looks great. It was unclear to me why fire on down was the desired behavior when I ported the button from its previous file anyway. Back to you to close if all set.

**Comment by jessegreenberg** [comment]
OK great, thanks!

**Comment by jbphet** [comment]
The behavior on touchscreen devices that results from this change is not correct.  With this in place, a single touch of a home screen icon goes to the screen, rather than selecting the icon.

**Comment by jbphet** [comment]
@jessegreenberg - we should coordinate the effort on this one and #689, since they are closely related.

**Comment by jessegreenberg** [comment]
I see, thanks.  It is caused by the `touchover` listener
```js
    // If you touch an unselected button, it become selected. If then without lifting your finger you swipe over to the
    // next button, that one becomes selected instead.
    this.addInputListener( {
      touchover: event => {
        buttonWasAlreadySelected = homeScreenModel.selectedScreenProperty.value === screen;
        homeScreenModel.selectedScreenProperty.value = screen;
      }
    } );
```

I am not sure how important this is, would it be OK to remove this? It looks like you were exploring that in https://github.com/phetsims/joist/issues/689#issuecomment-772816551 as well.

**Comment by jessegreenberg** [comment]
In https://github.com/phetsims/joist/issues/689, we decided to revert this change and wait until a decision is made for how to proceed with HomeScreenButtons. This issue may be resolved naturally if the 'swipe selection' feature is removed, or it may be resolved naturally when other changes to HomeScreenButton occur. Unfortunately this regression is in the CCK Virtual Lab RC, so the revert will need to be cherry-picked into that release..

**Comment by samreid** [comment]
I believe @jbphet indicated he intends to work on this.

**Comment by samreid** [comment]
While working on https://github.com/phetsims/circuit-construction-kit-common/issues/667, @jonathanolson recommended using the maintenance release process to patch between https://github.com/phetsims/joist/commit/f08abbb088afde8b581412293acbd4076922aec9 and https://github.com/phetsims/joist/commit/d0be22a46c325481ea2cb3bca6bb5d3c02f1a704.  This commit was only in for 3 days, but we know it affected at least two release branches (for CCK-DC and CCK-DC Virtual Lab).  The MR process would be able to discover if it affected any other release branches.  @jessegreenberg can you take the lead on this?

**Comment by jessegreenberg** [comment]
@samreid and I used the MR process to verify that CCKDC and CCKDC Virtual Lab were the only release branches that had picked up the breaking commit https://github.com/phetsims/joist/commit/f08abbb088afde8b581412293acbd4076922aec9.

**Comment by jbphet** [comment]
At this point, I think this issue is redundant with https://github.com/phetsims/joist/issues/689.  I'm going to close this issue and continue the work in the other.
