### ISSUE TITLE
Review zoom feature with sims that are using WebGLNode and three.js

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/joist#659]
From #657 - It was noticed that several (but not all) sims that are using WebGLNode are not working with the zoom feature. The problem is that the content of the WebGLNode does not zoom with the rest of the sim. The issue does not seem to be a general problem with WebGLNode but with the sim-specific usage. We need to review usages of WebGLNode to find all sims where this is a problem, then fix.

**Comment by jessegreenberg** [comment]
Here are the sims that use WebGLNode:
      bending-light
      charges-and-fields
      nueron

In #657 I also noticed that buoyancy sims had this problem but they are not using WebGLNode they are using three.js. Sims using three.js are
    build-a-molecule
    buoyancy
    density
    density-buoyancy-common

**Comment by jessegreenberg** [comment]
Checked off sims are working well. Remaining sims have the issue where zooming in on the sim does not zoom the WebGL content.

**Comment by jessegreenberg** [comment]
These are the three sims with issues related to zoom and webgl. @ariel-phet can you please comment on priority for addressing these?

**Comment by ariel-phet** [comment]
@jessegreenberg - Buoyancy and density would be high priority to get zoom working with IMO since we will be publishing these sims in the near future. As much as possible sims going forward should try to support zoom. I will note in the sim specific issues you have made.

**Comment by jessegreenberg** [comment]
Alright, sounds great thanks. Closing this issue since sim specific problems have been identified.
