### ISSUE TITLE
Error thrown while trying to enter full screen from keyboard

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/joist#662]
From #660, I found that when trying to enter full screen from PhET menu with keyboard input an error is thrown in Chrome.
First we get warning
> FullScreen.js:51 Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture.

Then full error:
```
FullScreen.js:51 Uncaught (in promise) TypeError: fullscreen error
    at Object.enterFullScreen (FullScreen.js:51)
    at Object.toggleFullScreen (FullScreen.js:75)
    at callback (PhetMenu.js:297)
    at fire (MenuItem.js:115)
    at Object.click (MenuItem.js:144)
    at Input.dispatchToListeners (Input.js:1852)
    at Input.dispatchToTargets (Input.js:1884)
    at Input.dispatchEvent (Input.js:1810)
    at Input.dispatchA11yEvent (Input.js:1040)
    at Input.clickAction.Action.phetioPlayback (Input.js:637)
  | enterFullScreen | @ | FullScreen.js:51
  | toggleFullScreen | @ | FullScreen.js:75
  | callback | @ | PhetMenu.js:297
  | fire | @ | MenuItem.js:115
  | click | @ | MenuItem.js:144
  | dispatchToListeners | @ | Input.js:1852
  | dispatchToTargets | @ | Input.js:1884
  | dispatchEvent | @ | Input.js:1810
  | dispatchA11yEvent | @ | Input.js:1040
  | Input.clickAction.Action.phetioPlayback | @ | Input.js:637
  | execute | @ | Action.js:226
  | (anonymous) | @ | Input.js:742

```

I verified that the issue is not related to #660 because it has been present since at least before https://github.com/phetsims/joist/commit/2a8ddcdaa3aac8ed4572466adc60b64633c7f851. This is not happening in the latest published a11y sim https://phet.colorado.edu/sims/html/molecules-and-light/1.5.0/dependencies.json.

This breaks the sim so it is blocking publication of any sim with alternative input.

**Comment by pixelzoom** [comment]
> This breaks the sim so it is blocking publication of any sim with alternative input.

Is there a list of sims with alternative input? And how is alternative input enabled?

**Comment by jessegreenberg** [comment]
Yes, it is the perennial/data/interactive-descriptions list. Alternative input is enabled by the package.json entry `supportsInteractiveDescriptions`.

**Comment by jessegreenberg** [comment]
This is happening because a11y was added to FireListener in https://github.com/phetsims/scenery/issues/1076. FireListener is used in sun/MenuItem.js, but there was an additional listener to `click` because FireListener previously didn't support a11y. This is fixed in this case by removing the extra listener.

But we should review usages of FireListener and make sure this isn't happening in other places.

**Comment by jessegreenberg** [comment]
HomeScreenButton is the only other place I could find where `click: ` was used in addition to FireListener.

**Comment by jessegreenberg** [comment]
Removed in the above commits, tested both and they seem to be working well. @zepumph would you mind reviewing?  Also, can the click listener on 207 be removed? I wasn't sure why that was necessary since click would always select the next screen.

**Comment by jessegreenberg** [comment]
> I wasn't sure why that was necessary since click would always select the next screen.

Oh, ill bet it is for screen reader compatibility since the button may be clicked without focus ever landing on it when AT is in use. I added a note about this.

**Comment by zepumph** [comment]
Thanks for taking this on; the commits look great. 

While looking for more I found this line, can it be removed?

https://github.com/phetsims/sun/blob/d74441aaf9ebae151566208486ab8c05a8468ad5/js/buttons/RectangularButtonView.js#L112

**Comment by jessegreenberg** [comment]
Yes, thanks! I don't see `accessibleClick` used anywhere, I guess this is from an old option we used to have for the buton model listener that should have been removed before.

**Comment by jessegreenberg** [comment]
Removed in above commit. Closing since that was the only comment.
