### ISSUE TITLE
Multi-Screen sim Home Screen - Would like to adjust accessible text on home screen & screen pages

### ISSUE THREAD

**Issue by terracoda** [phetsims/joist#665]
Ratio and Proportion will be our first described 
### The first general paragraph on Home Screen
In the initial paragraph that invites learners to explore, please add the word "interactive":
**Current phrase:**
>> Come explore with {{Ratio and Proportion}}. It has {{2}} screens.

**Change to:**
>> Come explore with {{Ratio and Proportion}}. It has {{2}} **_interactive_** screens.

### On the individual screen pages
Remove the word "interactive" in the intro line of the screen pages. For example:
**Current phrase for Discover Screen of RaP:**
>> The interactive {{Discover Screen}} changes as you play with it. It has a Play Area and a Control Area.

**Change to:**
>> The {{Discover Screen}} changes as you play with it. It has a Play Area and a Control Area.

@zepumph, would these changes be possible?

On single-screen sims we would still need the word "interactive", for example:
>> {{Gravity Force Lab: Basics}} is an interactive sim. It changes as you play with it. It has a Play Area and a Control Area.

**Comment by terracoda** [comment]
@zepumph, do you have any questions about the changes I requested above?

In a recent interviews, I got feedback that the current Home screen is a little sparse on content, and in a previous interview a learner was confused about the number of screens. I want to make new changes to the over all set up. Some more like this:

H1: {{Name of SIM}}

P: Welcome to {{Name of SIM}}. It has {{Number of Screens}} interactive screens that you can explore. Choose a screen to start exploring.

OL
LI: 
   BUTTON: {{Screen Name}} Screen
   P: {{Custom hint for screen}}
LI: 
   BUTTON: {{Screen Name}} Screen
   P: {{Custom hint for screen}}

H2: Sim Resources
   BUTTON: "Global Options/Settings" (eventually, but not now)
   BUTTON: Mute Sound
   BUTTON: Keyboard Shortcuts
   BUTTON: PhET Menu

**Comment by terracoda** [comment]
@zepumph, would these content changes be fairly trivial?

**Comment by zepumph** [comment]
Looks easy enough to me!

**Comment by zepumph** [comment]
Please note that by getting rid of "Sim Screens", I also removed the surrounding `nav` element, which was originally documented in https://github.com/phetsims/joist/blob/b91e469a596eb2e2f206f93b15a299aef342b4da/doc/HomeScreen.md#L68-L77. Please review the current HTML for the home screen in the a11y view and let me know how it sounds!


Here is a copy of the PDOM, with only the home screen and home screen nav bar showing. There is a bit of noise, but as always please ignore the long `id`, `data-trail-id`, and `data-focusable` attributes.

<details>

```html
<div class="pdom-root" lang="en">
  <article data-trail-id="1049-1050-1178" id="container-1049-1050-1178" data-focusable="false" class="pdom-sibling"
           tabindex="-1"><h1 data-trail-id="1049-1050-1178" id="label-1049-1050-1178" data-focusable="false"
                             class="pdom-sibling" tabindex="-1">Ratio and Proportion</h1>
    <p data-trail-id="1049-1050-1178" id="description-1049-1050-1178" data-focusable="false" class="pdom-sibling"
       tabindex="-1">Welcome to Ratio and Proportion. It has 2 interactive screens that you can explore. Choose a screen
      to start exploring.</p>
    <div data-trail-id="1049-1050-1178" id="1049-1050-1178" data-focusable="false" class="pdom-sibling" tabindex="-1">
      <ol data-trail-id="1049-1050-1178-1208" id="1049-1050-1178-1208" data-focusable="false" class="pdom-sibling"
          tabindex="-1">
        <li data-trail-id="1049-1050-1178-1208-1211-1196" id="container-1049-1050-1178-1208-1211-1196"
            data-focusable="false" class="pdom-sibling" tabindex="-1">
          <button data-trail-id="1049-1050-1178-1208-1211-1196" id="1049-1050-1178-1208-1211-1196" data-focusable="true"
                  class="pdom-sibling" aria-describedby="description-1049-1050-1178-1208-1211-1196" tabindex="-1">
            Discover Screen
          </button>
          <p data-trail-id="1049-1050-1178-1208-1211-1196" id="description-1049-1050-1178-1208-1211-1196"
             data-focusable="false" class="pdom-sibling" tabindex="-1">Explore this screen to discover set challenge
            ratios.</p></li>
        <li data-trail-id="1049-1050-1178-1208-1211-1207" id="container-1049-1050-1178-1208-1211-1207"
            data-focusable="false" class="pdom-sibling" tabindex="-1">
          <button data-trail-id="1049-1050-1178-1208-1211-1207" id="1049-1050-1178-1208-1211-1207" data-focusable="true"
                  class="pdom-sibling" aria-describedby="description-1049-1050-1178-1208-1211-1207" tabindex="-1">Create
            Screen
          </button>
          <p data-trail-id="1049-1050-1178-1208-1211-1207" id="description-1049-1050-1178-1208-1211-1207"
             data-focusable="false" class="pdom-sibling" tabindex="-1">On this screen, set your own challenge ratios to
            explore.</p></li>
      </ol>
    </div>
  </article>
  <article data-trail-id="1049-1050-1212" id="container-1049-1050-1212" data-focusable="false" class="pdom-sibling"
           hidden="" tabindex="-1"><h1 data-trail-id="1049-1050-1212" id="label-1049-1050-1212" data-focusable="false"
                                       class="pdom-sibling" tabindex="-1">Discover Screen, Ratio and Proportion</h1>
    . . . . 
  </article>
  <article data-trail-id="1049-1050-1352" id="container-1049-1050-1352" data-focusable="false" class="pdom-sibling"
           hidden="" tabindex="-1"><h1 data-trail-id="1049-1050-1352" id="label-1049-1050-1352" data-focusable="false"
                                       class="pdom-sibling" tabindex="-1">Create Screen, Ratio and Proportion</h1>
    . . . 
  </article>
  <nav data-trail-id="1049-1050-1059-1061-1139" id="container-1049-1050-1059-1061-1139" data-focusable="false"
       class="pdom-sibling" aria-labelledby="label-1049-1050-1059-1061-1139" hidden="" tabindex="-1"><h2
      data-trail-id="1049-1050-1059-1061-1139" id="label-1049-1050-1059-1061-1139" data-focusable="false"
      class="pdom-sibling" tabindex="-1">Sim Screens</h2>
    . . . 
  </nav>
  <section data-trail-id="1049-1050-1059-1177" id="container-1049-1050-1059-1177" data-focusable="false"
           class="pdom-sibling" aria-labelledby="label-1049-1050-1059-1177" tabindex="-1"><h2
      data-trail-id="1049-1050-1059-1177" id="label-1049-1050-1059-1177" data-focusable="false" class="pdom-sibling"
      tabindex="-1">Sim Resources</h2>
    <div data-trail-id="1049-1050-1059-1177" id="1049-1050-1059-1177" data-focusable="false" class="pdom-sibling"
         tabindex="-1">
      <button data-trail-id="1049-1050-1059-1177-1138-1128" id="1049-1050-1059-1177-1138-1128" data-focusable="true"
              class="pdom-sibling" aria-pressed="false" tabindex="-1">Mute Sound
      </button>
      <button data-trail-id="1049-1050-1059-1177-1138-1136" id="1049-1050-1059-1177-1138-1136" data-focusable="true"
              class="pdom-sibling" tabindex="-1">Keyboard Shortcuts
      </button>
      <button data-trail-id="1049-1050-1059-1177-1114" id="1049-1050-1059-1177-1114" data-focusable="true"
              class="pdom-sibling" aria-haspopup="true" tabindex="-1">PhET Menu
      </button>
    </div>
  </section>
</div>
```

</details>

**Comment by terracoda** [comment]
In phetsims/ratio-and-proportion#231, @zepumph and I were discussing common code phrases for that sim's screen summaries. That sim is a multi-screen sim. I was thinking it was safe to remove the word "interactive" from the intro sentence on the screen page because we say "interactive screens" on the Home page.  We may need to tweak things (i.e. repeat the word "interactive" on the screen page) if this pattern does not fit across all sims. That said, this is how I imagined things rolling out. **Note** this is our first multi-screen sim with interactive description, and we have only had 4 interviews. The latest interview with the following pattern worked well:

**On the home screen the sim says "interactive screens":**
-  "Welcome to {{Ratio and Proportion}}. It has {{2}} interactive screens that you can explore. Choose a screen to start exploring."

**On the screen page the sim starts like this:**
- The {{Discover}} Screen changes as you play with it. It has a Play Area and a Control Area. 
I don't want to remove "interactive" from single screen sims like JT, BASE, Fiction, etc which have this sentence:

For contrast, this is the current pattern for single-screen sims.
**Single-screen sims starts like this:**
- {{Gravity Force Lab: Basics}} is an interactive sim. It changes as you play with it. It has a Play Area and a Control Area.

@zepumph, can you tell me if removing "interactive" removes it from single-screen sims?

**Comment by terracoda** [comment]
@zepumph, other than my question in my previous comment, the latest content on the home page worked great in the latest interview. Assigning back to you to answer my question.

**Comment by terracoda** [comment]
In Nov 13th interview for ratio and proportion, this set-up for the Home Screen worked rally well for the learner.

**Comment by terracoda** [comment]
@zepumph, I am looking at dev version 1.0.0-dev.73, and the first 2 sentences on the screen pages actually read fine:
- Screen 1: The interactive Discover Screen changes as you play with it. It has a Play Area and a Control Area.
- Screen 2: The interactive Create Screen changes as you play with it. It has a Play Area and a Control Area.

I'm fine with leaving "interactive" in on all screens (home screen), indy screens and single-screen sims.

**Comment by terracoda** [comment]
Regardless, of my question now in https://github.com/phetsims/joist/issues/665#issuecomment-729670841, I think we can close this issue.

**Comment by zepumph** [comment]
Sounds good! Closing
