### ISSUE TITLE
ModuleIndex comment in Sim.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#667]
In Sim.js, added by @samreid in the original commit on 4/22/2013:

```js
  finishInit( screens ) {

    // ModuleIndex should always be defined.  On startup screenIndex=1 to highlight the 1st screen.
    // When moving from a screen to the homescreen, the previous screen should be highlighted
```

I have no idea what this comment means. There is nothing in Sim.js named "ModuleIndex".  Recommend to either delete this comment or turn it into something that makes sense.

**Comment by samreid** [comment]
No longer necessary, removed, closing.
