### ISSUE TITLE
Adjust screen h1 when using `?screens=1`

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#677]
When I go to Ratio and Proportion's first screen, this is the H1:

>Discover Screen, Ratio and Proportion

When I go to Friction (a single screen sim), the H1 is:

>Friction

When I go to Ratio and Proportion with `?screens=1`, the H1 is:

>Ratio and Proportion

On this third case though, note that the sim title is different, it says "Ratio and Proportion - Discover". I wonder if we should update the H1 for the screen in this case also, so that it is easier to recognize that it is a subset of the ratio and proportion sim. 

I thought of this while working on https://github.com/phetsims/joist/issues/665

What do you think @terracoda?

**Comment by terracoda** [comment]
@zepumph, I was not aware of this third case.
So what currently happens with the actual `title` element in these three cases? I think it is very important to know what is happening from the very top. The `title` element is read first and populates the browser tab.

**Comment by zepumph** [comment]
When adding `?screens=1` to RaP:

![Uploading image.png…]()

**Comment by zepumph** [comment]
@terracoda and I agree that altering the H1 to match the title of the nav bar works great. So in the above, the H1 title would match and be "Ratio and Proportion — Discover".

**Comment by zepumph** [comment]
This is now implemented. 

![image](https://user-images.githubusercontent.com/6856943/98744395-19b32180-235e-11eb-8f27-69caa4ad1e0f.png)

@terracoda please review.

**Comment by terracoda** [comment]
I see I mention "screen" on the second screen further down in the screen summary. I might tweak that in RaP repo.
The headings look great.

**Comment by terracoda** [comment]
Please close if you are all done :-)
