### ISSUE TITLE
Focus, Multi-screen Sims & Screen Changes from Nav Bar

### ISSUE THREAD

**Issue by terracoda** [phetsims/joist#679]
In recent interviews with our first multi-screen sim with Interactive Description, it has become clear that focus needs to go to the H1 when a new screen is selected from the nav bar.

Learners using Ratio and Proportion have no trouble when a screen is loaded from the home page and focus starts at the top of the screen.

However, learners did say that it was unexpected that their focus stayed on the screen button when they loaded a new screen from the nav bar.

There may already be an open issue for this. I think @samreid brought it up when working on Waves Intro.

Assigning to @zepumph because this issue related to Ratio and Proportion.

**Comment by zepumph** [comment]
This seems to have been covered by https://github.com/phetsims/ratio-and-proportion/issues/282. @terracoda please reopen if there is more here.
