### ISSUE TITLE
output level is not being set to 0 for some joist buttons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#680]
Fourier has sim-specific sound, and (for now) we want to disable all of the sounds that come with UI components.  So I've added this to fourier-making-waves-main.js:

```
soundManager.setOutputLevelForCategory( 'user-interface', 0 );
```

This silences most UI components. But I'm still hearing sounds associated with the home screen buttons and navigation bar screen buttons.

For the home screen buttons, I'm only hearing the sound when a new screen is actually selected, not the sound when a new icon is selected. 

For the navigation bar screen buttons, I'm not hearing the sound for the home button, just the buttons for the non-home screens.

Everything else in the sim is silent. (PhET menu, Reset All button, other UI components,...)

**Comment by pixelzoom** [comment]
Raising the priority of this because it's a requirement for Fourier, and it annoying when I'm fuzz testing.  Labeling for dev meeting discussion so we discuss who should do this and when.

**Comment by pixelzoom** [comment]
I think I've discovered the problem here.  Screen selection uses ScreenSelectionSoundGenerator.  Unlike the sounds for other UI components, this is a SoundClip, not a SharedSoundClip.  And it therefore does not register itself as `categoryName: 'user-interface'`.

Is there some reason why this should not be converted to a SharedSoundClip, using the same pattern as (e.g.) checkboxCheckedSoundPlayer.js?

**Comment by pixelzoom** [comment]
Worked on this with @jbphet, fixed in above commit.  Closing since we collaborated.

**Comment by samreid** [comment]
In https://github.com/phetsims/circuit-construction-kit-common/issues/667#issuecomment-780095159 @arouinfar said:

> @samreid can you add https://github.com/phetsims/joist/commit/991d6a448a869bff9ed7836676eae9fdd2c9aeed to the list? There are joist sounds in the latest rc, which is odd because all other UI sounds are disabled, see https://github.com/phetsims/joist/issues/680

We know this problem affects at least 2 release branches (cck-dc and cck-dc-virtual-lab).  While working on https://github.com/phetsims/circuit-construction-kit-common/issues/667 @jonathanolson recommended using the maintenance release process to update all affected release branches (including but not limited to the CCK ones mentioned).

@jbphet or @pixelzoom can you please take the lead?  Please also coordinate with @jessegreenberg since there is one maintenance release in process and another one recommended in https://github.com/phetsims/joist/issues/658#issuecomment-780148576

**Comment by pixelzoom** [comment]
Sorry, I don't have time to take the lead on this. 

This presumably affects only sims that were turning off the 'user-interface' category of sounds.  Searching for `setOutputLevelForCategory( 'user-interface'`, I find only 5 occurrences: Fourier (1) and the CCK suite (4).  Fourier is unpublished, so I would guess that only CCK is affected.  @samreid is the responsible dev, so can he sort out what release branch(es) need to be patched?

**Comment by samreid** [comment]
Thanks, I ran this maintenance script to update the CCK 1.2 sims:

```js
Maintenance.reset()
Maintenance.createPatch( 'joist', 'https://github.com/phetsims/joist/issues/680', 'patch-1' )
Maintenance.addNeededPatch( 'circuit-construction-kit-dc', '1.2', 'patch-1' )
Maintenance.addNeededPatch( 'circuit-construction-kit-dc-virtual-lab', '1.2', 'patch-1' )
Maintenance.addPatchSHA( 'patch-1', '991d6a448a869bff9ed7836676eae9fdd2c9aeed' )
Maintenance.applyPatches()
Maintenance.updateDependencies()
```

Closing.
