### ISSUE TITLE
Updates to HomeScreen logic

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#683]
From https://github.com/phetsims/ratio-and-proportion/issues/311, it will fix a bug on iOS when using VoiceOver to not recreate the HBox containing the screen buttons each time a selection changes. While poking around there, I found a couple of other things that I would like to cover at this time.

- [x] Just call `updateLayout` instead of recreating a new HBox on each screen selection change (selectedScreenProperty)
- [x] We don't need to duck type a "screenElement" with a `screen` and `button`. Instead just set a public read-only `screen` member on HomeScreenButton, to be used by the HomeScreenView.
- [x] I would like to see if HomeScreenButton's input listener logic can be simplified at all.
- [x] iconsParentNode can be merged with the HBox since it is sticking around now.
- [x] highlightedScreenButton isn't needed, we can just look up the correct screen each time from a map.

Thanks @chrisklus for helping me discover the solution to the first checkbox. Commit coming shortly.

**Comment by zepumph** [comment]
Alright, all has been implemented, and https://github.com/phetsims/ratio-and-proportion/issues/311 has been confirmed fixed and closed. @jessegreenberg can you please review the above commits?

**Comment by jessegreenberg** [comment]
Changes all look great and things are behaving well with various forms of input. The only thing I wanted to check was in
6270e6d600b2679e1e0688b3df1b7ad6a8469b09, a focus listener was removed and not replaced. Is that because the listener on line 188 is already doing that?

```js
this.addInputListener( { focus: event => { !isSelectedProperty.value && fireListener.fire( event ); } } );
```

**Comment by zepumph** [comment]
Yes, I was confused by logic that focused itself when getting the focus event in addition to the listener you posted above that is actually executing the focus logic. It looked buggy to me, so I removed it and haven't seen any issues come from it. Can you think why that may have been there? Would you like me to put it back?

**Comment by jessegreenberg** [comment]
No, I agree and think it is better without - just making sure. Closing.
