### ISSUE TITLE
Move phet.joist.random out of joist

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#685]
From https://github.com/phetsims/tambo/issues/126, this will help us break the dependency many common code repos have on joist. We think this will be best to do by moving to a `Random` singleton instance in DOT.

**Comment by zepumph** [comment]
phet.chipper.randomSeed will go away, because dotRandom.setSeed will be the mutable mechanism for altering the randomness.

**Comment by zepumph** [comment]
Main work done above:

* Create DOT/dotRandom which is seeded by phet.chipper.queryParameters.randomSeed if available, for use globally
* Get rid of phet.joist.random.
* Get rid of phet.chipper.randomSeed, and just use the phet.chipper.queryParameters.randomSeed because it is not mutable by phet-io anymore.
* Add support for mutating the see of a Random, which is important for PhET-iO
* In phetioEngine, call dotRandom.setSeed to set the random seed for the sim, but make sure that random hasn't been called up to this point.
* In Random, update options to remove staticSeed, and have dotRandom just pass through the right seed.

Main files for review:
* Random.js
* dotRandom.js
* simLauncher.js
* phetioEngine.js


All sims are fuzzing, and @samreid and I were able to use PhET-iO mirror inputs wrapper in BLL and NS to see that the randomness matched between the two sims (shaker particles and bunny placement/hops).
@jonathanolson would you please review these changes. Can you think of any issues with having the singleton Random in dot?

**Comment by zepumph** [comment]
Review should block publication as it effects many repos.

**Comment by pixelzoom** [comment]
Reminder to:

- [ ] Change CRC to indicate that `dotRandom` should be used
- [ ] Post this breaking change to Google Group

**Comment by jonathanolson** [comment]
Changes look safe, however Random.js has a few issues:

- If a seed is 0, then it uses a random seed.
- `new dot.Random()` or `new dot.Random( { seed: 5 } )` are both failing in the dot playground (and presumably the build). At least the first used to work.
- Random.setSeed says it only takes numbers, but null is passed in

Removing blocks-publication, since this looks good for publication.

> Can you think of any issues with having the singleton Random in dot?

Dot has more of a dependence on seedrandom... should that be included in dot builds? Otherwise seems fine.

**Comment by zepumph** [comment]
@jbphet  found an error because recent commits were using `phet.dot.dotRandom` on the namespace instead of importing it. @jonathanolson came in for the quick fix, and I added the namespace call to bad text for clarity.

**Comment by samreid** [comment]
Thanks for fixing this--I mistakenly used `phet.dot.dotRandom` as an analogy with `phet.joist.random`, but should have used the import. My pattern was copied into ComboBox as part of https://github.com/phetsims/sun/issues/679.  Thanks again!

**Comment by zepumph** [comment]
>new dot.Random() or new dot.Random( { seed: 5 } ) are both failing in the dot playground (and presumably the build). At least the first used to work.

and

>Dot has more of a dependence on seedrandom... should that be included in dot builds? Otherwise seems fine.


Are intertwined to me. I totally see how I added a hard dependency to seedrandom with my changes. Sorry about that. I see two steps forward. Either accept that, or add in this patch to get things to work when seedRandom doesn't work. @jonathanolson do you have a preference?

```
Index: js/Random.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/Random.js b/js/Random.js
--- a/js/Random.js	(revision 131c882cde28cee009cedb226352763d9928baca)
+++ b/js/Random.js	(date 1611790042275)
@@ -200,7 +200,7 @@
 
     // Math.seedrandom is provided by seedrandom.js, see https://github.com/davidbau/seedrandom.
     // @private {function:number|null} initialized via setSeed below
-    this.seedrandom = new Math.seedrandom( seed + '' );
+    this.seedrandom = Math.seedrandom ? new Math.seedrandom( seed + '' ) : () => Math.random(); // eslint-disable-line bad-sim-text
   }
 }
 

```

Otherwise I did all other items here.

**Comment by jonathanolson** [comment]
I'm fine with a hard dependency, but seedrandom would need to be added to many HTML files (a lot where `assert/js/assert.js` is included and seedrandom isn't).

Otherwise a soft dependency is fine like above.

**Comment by zepumph** [comment]
Committed with grace above. 

I noticed though that without seedrandom, seed doesn't do anything or work as expected. Should we assert out if seed is provided and there is no Math.seedrandom?

```
Math.seedrandom = undefined;
x = new dot.Random( {seed:0});
y = new dot.Random( {seed:0});

x.nextDouble() === y.nextDouble(); // false
```

**Comment by samreid** [comment]
Yes, that should be an assertion error.

**Comment by zepumph** [comment]
Alright thanks for all the help. Closing. Please reopen if there is anything else.

**Comment by samreid** [comment]
I noticed this line in the commit:

```js
assert && assert( Math.seedrandom, 'cannot set seed with 3rd party library "Math.seedrandom".' );
```

But I forgot that `assert` no longer evaluated functions passed to its 1st arg, which changed in https://github.com/phetsims/assert/issues/2.  Sorry for the false alarm, closing again.

**Comment by pixelzoom** [comment]
Reopening.  I still see `phet.joist.random` in the CRC:

> - [ ]  Are random numbers using phet.joist.random, and  ...

**Comment by zepumph** [comment]
Ahh, right, thanks.

**Comment by pixelzoom** [comment]
In phet-software-design-patterns.md:

> Some code is loaded in our "preloads" section, and is available through the global phet object, like `phet.joist.random`.

**Comment by zepumph** [comment]
updated documentation above, and posted to the google group for breaking API changes. Closing
