### ISSUE TITLE
Move blur listener on ScreenView to display

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/joist#688]
It was discovered in https://github.com/phetsims/sun/issues/676 that a blur listener added to ScreenView in https://github.com/phetsims/joist/commit/180efd8722f2a11aede948f4e8d5b6b769860e10 for focus management is effectively making all Nodes under the ScreenView `pickable: true`, changing hit testing and breaking behavior in many cases. I am not sure if adding a blur listener should impact hit testing of the sub tree, and that will be discussed more generally. But for now, we should see if we can move or change the listener so master doesn't sit broken.

We could try adding the listener to the Display, or we could try blurring immediately so that the listener is immediately removed.

**Comment by jessegreenberg** [comment]
I tried blurring immediately but it didn't work for NVDA, focus went away but the virtual cursor stayed in the navigation bar. We likely tried that in https://github.com/phetsims/ratio-and-proportion/issues/282. Ill try moving to the display next.

**Comment by zepumph** [comment]
Thanks!

**Comment by jessegreenberg** [comment]
This listener was moved from the ScreenView to the Display in the above commit. I verified that the behavior still works with keyboard navigation and screen readers. @jonathanolson would you mind reviewing this change?

**Comment by jonathanolson** [comment]
- `if ( has ) { remove() } add()` could be changed to `if ( !has ) { add() }` (shorthanding it) for adding the blur listener? It would be ideal if we didn't remove and then re-add?
- Is there a case where currentView.visible would be false?
- I don't know the constraints, but is it possible to have one persistent listener on the Display (that doesn't need to be added/removed), with just extra logic/conditions when it gets fired to see if it needs to blur something?

But the changes look safe and presumably makes things non-blocking, thanks!

**Comment by jessegreenberg** [comment]
Thanks @jonathanolson -

The above commit removes the unnecessary conditionals. I will take a look at changing the listener so that it doesn't have to be added/removed.

**Comment by jessegreenberg** [comment]
The Display listener was changed so it doesn't need to be added/removed when screen changes - @zepumph would you mind reviewing this part?

**Comment by zepumph** [comment]
That looks really nice. Thanks.

**Comment by jessegreenberg** [comment]
Thanks, closing.
