### ISSUE TITLE
OK to use the alternative RequireJS format in our main sim files?

### ISSUE THREAD

**Issue by jbphet** [phetsims/joist#69]
A while back, we adopted a format for defining RequireJS dependencies that looks like this:

define( function( require ) {
  var NumberAtom = require( 'BUILD_AN_ATOM/common/model/NumberAtom' );
   .
   .
   .

This is an alternative to the format described in most of the RequireJS documentation, which looks like this:

require( [  'BUILD_AN_ATOM/common/model/NumberAtom'  ],
   function( NumberAtom ){
   .
   .
   .

The former format is preferred, since it is more readable.  Until now, we PhET developers have avoided using this format in the simulation main.js file (e.g. build-an-atom-main.js) because we thought that it didn't work.  However, MLL has been using it for a while now in the main.js files for the sims that they develop, and we haven't noticed any adverse effects.  Does that mean we can safely use it in all simulation main files?

**Comment by jonathanolson** [comment]
Looks like this is done for the <sim>-main also? Just BAM and masses-and-springs remain, will take care of those.
