### ISSUE TITLE
Move `resizeAction` to top level and get rid of `alwaysPlaybackableOverride`

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#693]
From https://github.com/phetsims/phet-io/issues/1693

@zepumph said:

> * We may want to refactor the resizeAction, which seems to be the only case of nested actions that don't get played back. [...] Then we could get rid of the "hack" (imo) that is `alwaysPlaybackableOverride`.

**Comment by zepumph** [comment]
- [ ] Once we get rid of this, would we want to assert that nested playback:true is not allowed?

**Comment by samreid** [comment]
I launched Natural Selection with ?phetioConsoleLog=json and resized the window.  I saw:

```json
{
  "index": 117,
  "time": 1615391783880,
  "type": "model",
  "phetioID": "naturalSelection.general.model.resizeAction",
  "name": "emitted",
  "componentType": "ActionIO<NumberIO, NumberIO>",
  "data": {
    "width": 857,
    "height": 938
  },
  "metadata": {
    "alwaysPlaybackableOverride": true,
    "dataKeys": [
      "width",
      "height"
    ],
    "playback": true
  },
```

This was not a child event.   Is there another context where it is nested?  I'm not sure I understand this issue.

**Comment by zepumph** [comment]
Yes this is the nested case that I would most expect to see. I'll take a look at why it isn't showing up as nested.

**Comment by zepumph** [comment]
I was able to use this link to get the below event: http://localhost:8080/natural-selection/natural-selection_en.html?brand=phet-io&phetioConsoleLog=json&phetioStandalone&ea&debugger 


```json
{
  "index": 2687,
  "time": 1615416602470,
  "type": "model",
  "phetioID": "naturalSelection.general.model.stepSimulationAction",
  "name": "emitted",
  "componentType": "ActionIO<NumberIO>",
  "data": {
    "dt": 0.018
  },
  "metadata": {
    "dataKeys": [
      "dt"
    ],
    "playback": true
  },
  "children": [
    {
      "index": 2688,
      "time": 1615416610430,
      "type": "model",
      "phetioID": "naturalSelection.general.model.resizeAction",
      "name": "emitted",
      "componentType": "ActionIO<NumberIO, NumberIO>",
      "data": {
        "width": 819,
        "height": 977
      },
      "metadata": {
        "alwaysPlaybackableOverride": true,
        "dataKeys": [
          "width",
          "height"
        ],
        "playback": true
      },
      "children": [
        {
          "index": 2689,
          "time": 1615416651467,
          "type": "model",
          "phetioID": "naturalSelection.general.view.panZoomListener.matrixProperty",
          "name": "changed",
          "componentType": "PropertyIO<Matrix3IO>",
          "data": {
            "oldValue": null,
            "newValue": {
              "entries": [
                1,
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                1
              ],
              "type": "IDENTITY"
            }
          }
        },
        {
          "index": 2690,
          "time": 1615416651467,
          "type": "model",
          "phetioID": "naturalSelection.general.view.panZoomListener.sourceFramePanBoundsProperty",
          "name": "changed",
          "componentType": "PropertyIO<Bounds2IO>",
          "data": {
            "oldValue": {
              "minX": 0,
              "minY": 0,
              "maxX": 787,
              "maxY": 977
            },
            "newValue": {
              "minX": 0,
              "minY": 0,
              "maxX": 819,
              "maxY": 977
            }
          }
        },
        {
          "index": 2691,
          "time": 1615416651467,
          "type": "model",
          "phetioID": "naturalSelection.general.view.panZoomListener.matrixProperty",
          "name": "changed",
          "componentType": "PropertyIO<Matrix3IO>",
          "data": {
            "oldValue": null,
            "newValue": {
              "entries": [
                1,
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                1
              ],
              "type": "IDENTITY"
            }
          }
        }
      ]
    },
    {
      "index": 2692,
      "time": 1615416651470,
      "type": "model",
      "phetioID": "naturalSelection.general.controller.input.validatePointersAction",
      "name": "emitted",
      "componentType": "ActionIO<>",
      "metadata": {
        "dataKeys": [],
        "playback": false
      }
    },
    {
      "index": 2693,
      "time": 1615416651471,
      "type": "model",
      "phetioID": "naturalSelection.general.model.frameEndedEmitter",
      "name": "emitted",
      "componentType": "EmitterIO<>"
    }
  ]
}
```

Perhaps you were experiencing something that I experienced, where this link didn't console log the above event:
http://localhost:8080/natural-selection/natural-selection_en.html?brand=phet-io&phetioConsoleLog=json&phetioStandalone&phetioEmitHighFrequencyEvents=true&ea&debugger

phetioEmitHighFrequnecyEvents=true should be the same as the default. I will do a bit more investigation.

**Comment by zepumph** [comment]
>phetioEmitHighFrequnecyEvents=true should be the same as the default. I will do a bit more investigation.


I think it was dev tools bugs, I restarted chrome and it fixed things.


>https://github.com/phetsims/joist/issues/693#issuecomment-795648830

@samreid I am able to see the same behavior with `phetioEmitHighFrequencyEvents=false`, is it possible that you weren't emitting high frequency events (which would include the resize's parent event "stepSimulationAction").

**Comment by samreid** [comment]
That's probably it, thanks!

**Comment by samreid** [comment]
Here is the spot in Sim.js where the `stepSimulationAction` calls the resize:

```js
    this.stepSimulationAction = new Action( dt => {
      this.frameStartedEmitter.emit();

      // increment this before we can have an exception thrown, to see if we are missing frames
      this.frameCounter++;

      // Apply any scaling effects here before it is used.
      dt *= phet.chipper.queryParameters.speed;

      if ( this.resizePending ) {
        this.resizeToWindow();
      }
```

What are our options for moving the resize up a level in the data stream?

**Comment by zepumph** [comment]
I've been bashing my head against a data-streamy wall here for a few minutes, and can't really think outside of our current constraints to see how this could work.

We could embed the data for resize into the stepSimulationsAction, by passing in resizePending as an argument to stepSimulationAction, but we would also need that to keep track of the resize values too. We could instrument something else that is more upstream of the resizeAction to hold those values. 

Here is a brainstorming patch that just has documentation. Honestly I'm tempted to just keep it as is in master, since there doesn't seem to be an elegant way to proceed. What would be the point in coming up with another weird hack in order to get rid of the weird hack we know and love (alwaysPlabackableOverride)?

**Comment by samreid** [comment]
I'm not sure I understand the documentation patch, it seems to document the parameters differently than they actually are?  I'm fine to leave master as it is, I can't think of a better approach to make resize events top level.

**Comment by zepumph** [comment]
Sounds good to me.
