### ISSUE TITLE
branch: preferences

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/joist#694]
A branch to explore changes related to the Preferences Dialog and Toolbar without destabilizing code in master.

**Comment by zepumph** [comment]
@jessegreenberg can this branch/issue be deleted and close?

**Comment by zepumph** [comment]
Just a ping here, do we still need this branch?

**Comment by jessegreenberg** [comment]
No, this branch can be deleted now.

**Comment by jessegreenberg** [comment]
It has been deleted.
