### ISSUE TITLE
Focus should be at top when returning to home screen

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#695]
@jessegreenberg @terracoda, I believe we have discussed this before. 

@terracoda thinks this should match the current behavior for sim screens (focus the h1), and not focusing to the highlighted screen button. Basically we should be able to just get rid of `focusHighlightedScreenButton`.

Tagging this for https://github.com/phetsims/ratio-and-proportion/issues/363.

**Comment by zepumph** [comment]
@jessegreenberg, I'm not sure how we accomplish this, or even if we can. Is this needed for Greenhouse effect?

**Comment by terracoda** [comment]
Actually, a better, more natural user experience is for focus to go the button of the source screen. 
We are talking about a re-visit to the Home screen, right?

I thought I had this plan mapped for RaP? There might be an interaction design pattern in Binder?? - not sure.
1. Focus is at top of Home Screen when the sim loads for the first time.
2. Focus is at the top of  Sim Screen when a screen is selected from the Home page - this was requested by blind users in interviews.
3. When returning to the Home Screen from a Sim Screen, the Sim Screen button of the source Sim Screen receives focus. There's no need to read from the top in this case. If the user wants to do that they can use their preferred screen reader navigation method.
4. Note that we have not done many interviews on multi-screen sims yet. I think right now, when swapping between Sim Screens in the navbar, focus is just on the Sim Screen buttons as they are selected. I think the user in this case needs to jump to the top of the Sim with their preferred screen reader navigation method.

**Note having a 4-screen sim like GHE in development** will give us an opportunity to investigate the sim screen interactions further. We have not done an exhaustive investigation of the Sim Screen interactions.

**Comment by jessegreenberg** [comment]
Discussed with @terracoda, focus should return to the h1 on the home screen to be consistent with other screens. Ill take a look.

**Comment by jessegreenberg** [comment]
There is specific code in the NavigationBar that is putting focus on the home screen button.

```ts
            // only if fired from a11y
            if ( this.homeButton!.isPDOMClicking() ) {
              sim.homeScreen!.view.focusHighlightedScreenButton();
            }
```

It is very old (2018), predating our decision to put focus on the 'h1' of the ScreenView (2021), so I will go ahead and remove it.

**Comment by jessegreenberg** [comment]
This was pushed to main, closing.
