### ISSUE TITLE
branch: fireHomeButtonsOnUp

### ISSUE THREAD

**Issue by jbphet** [phetsims/joist#697]
This branch was created as a place to safely experiment with home button behavior without imperiling any upcoming releases.  See https://github.com/phetsims/joist/issues/689.

**Comment by jbphet** [comment]
The changes the were tested out on this branch have now been moved to master, and the branch has been deleted.  And further work will be done under the main issue, which is linked in the original description.  Closing.

**Comment by zepumph** [comment]
Should be re-deleted as part of phetsims/special-ops#198

**Comment by zepumph** [comment]
Deleted
