### ISSUE TITLE
CT errors around ScreenView tandems named "view"

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#698]
Over in https://github.com/phetsims/tandem/issues/228 we made an assertion run for tandem names in PhET brand. This broke a couple of sims. I'll update all occurrences I can find. Right now ESP(B) are both not working

**Comment by zepumph** [comment]
@samreid please review. I don't know how to create and assertion for the "model" part, but perhaps the symmetry will be obvious because we now have the ScreenView assertion.

**Comment by samreid** [comment]
These changes look excellent, thanks!  If we had a model assertion, it may be located elsewhere, like in `Screen` or as part of an audit during phetio engine or phetioAPIValidation.  We can add that in the future if there is a need for it.  But code reviews and design reviews may be sufficient for now.  Closing.
