### ISSUE TITLE
(Preferences Menu) HTML Structures for Preferences Menu and Voicing Toolbar

### ISSUE THREAD

**Issue by terracoda** [phetsims/joist#699]
We might need separate issues, but here's a list of things I think we need look at more carefully. I am going on the assumption that the Preferences Menu and Voicing Toolbar need to be screen reader accessible via the PDOM. I am assuming the sim can still be screen reader accessible with Voicing enabled, but that is not the ideal experience since more than one voice would be speaking at the same time. 

**Preferences Menu - When using a screen reader**
- [x] Preferences Menu button has no name in Sim Resources navbar
- [x] No access to H1 for Preferences Dialog. I think this is intentional since each Tab says "Preferences".
- [x] Preferences Tabs are read as radiobuttons 
- [x] No names on buttons in Prefs Menu
- [x] No names on checkboxes in Prefs Menu
- [x] No access to help text for buttons and checkboxes in Prefs Menu
- [ ] Preferences menu closes when selecting a Tab on iOS 14.14.1 with Safari and VO

**Voicing Toolbar - When using a screen reader**
- [x] Speech on/off button (soon to be named "Sim Voicing") has no name, ideally on focus, it should include the on or off state, e.g., "Sim Voicing on" and "Sim Voicing off" 
- [x] Play buttons, are just "Play" buttons in the PDOM, and just "Overview", "Details" and "Hint" in Voicing, can their names be "Play Overview", "Play Details", "Play Hint" in both the PDOM and in the Voicing? I think having the verb "Play" with make it clear to non-visual learners that it is interactive and you they need to activate each to play the content for each one.

**Comment by jessegreenberg** [comment]
> Preferences menu closes when selecting a Tab on iOS 14.14.1 with Safari and VO

After verifying the PDOM instrumentation for Preferences this is still happening and I suspect that it is an issue with Dialogs in general.

**Comment by jessegreenberg** [comment]
Dialogs are not working well on iOS 14 but I still think this is ready for review @terracoda, can you please check the PDOM in this version?

https://phet-dev.colorado.edu/html/john-travoltage/1.6.0-preferences.1/phet/john-travoltage_en_phet.html?supportsVoicing

**Comment by terracoda** [comment]
I think we can close this issue and follow-up a few more new issues in issue https://github.com/phetsims/john-travoltage/issues/403

**Comment by terracoda** [comment]
Everything above that is checked verified and the unchecked issue does not seem to be a problem anymore. Closing
