### ISSUE TITLE
multi-touch: cancel interactions when switching screens

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#70]
This is a general problem with multi-touch that affects all sims.

First reported by @orejolaphet in this beers-law-lab issue: https://github.com/phetsims/beers-law-lab/issues/57.

If you change between screens while interacting with an object, that object will freeze and be immovable when you return to that screen. Resetting the screen will move objects to original position, but the object will still be frozen. You can also freeze the reset button and the selections to different screens themselves. The only way to correct the problem is to reload the sim.

**Comment by jonathanolson** [comment]
@ariel-phet, this is also a probably-multi-day issue tagged for the redeploy, should I bump up the priority of this Scenery work (currently tagged as medium priority)?

**Comment by jonathanolson** [comment]
Removed redeploy label since we're not running into it much right now.

**Comment by pixelzoom** [comment]
5/28/15 dev meeting: @ariel-phet said "don’t worry about it for now".

**Comment by ariel-phet** [comment]
I attempted to reproduce this issue on Beer's Law lab on iPad2 iOS 9.3.5 and it is not longer present, I can switch screens while manipulating objects with no obvious consequences. Closing

**Comment by pixelzoom** [comment]
Reopening.

It's probably no longer present in Beer's Law Lab because I worked around it in client code.  Depending on how the client implements interaction, I still stand by my original statement: "This is a general problem with multi-touch that affects all sims."  There needs to be common-code support for cancelling interactions, and that support needs to be wired into joist for screen switching. 

Unfortunately there is still no common-code support. The plan is to address this in scenery, but the issue hasn't gotten any traction (see https://github.com/phetsims/scenery/issues/218, over 3 years old).

My recommendation is to leave this issue open, so that if/when https://github.com/phetsims/scenery/issues/218 gets some love, we remember to wire it into joist.

**Comment by pixelzoom** [comment]
I renamed this issue to indicate what we need to remember to do.

**Comment by pixelzoom** [comment]
@jonathanolson Now that we have an API for canceling interactions... Your thoughts on how to cancel interactions when switching screens?  It seems like this is something that should be handled automatically in joist, whenever screen selection changes.

**Comment by samreid** [comment]
> Your thoughts on how to cancel interactions when switching screens?

I wonder if it should be even more general and handled in scenery.  Something like "when a node is no longer in the scene graph, interaction is automatically cancelled".  Not sure if we would need to expand this to "no longer in the scene graph or visible".

**Comment by jonathanolson** [comment]
> Now that we have an API for canceling interactions... Your thoughts on how to cancel interactions when switching screens? It seems like this is something that should be handled automatically in joist, whenever screen selection changes.

Yes, presumably Joist would call interruptSubtreeInput on the screenView and any listeners using this (https://github.com/phetsims/scenery/issues/131) would handle it properly.

**Comment by jonathanolson** [comment]
> Something like "when a node is no longer in the scene graph, interaction is automatically cancelled".

I had thought about that, but was concerned enough about when children of a node is changed, it triggers removal of everything and then adds everything (potentially adding nodes back), and figured that would break things.

**Comment by samreid** [comment]
OK it sounds good to have explicit triggers for breaking interaction, but we should make sure it is general and flexible so it works for screens/scenes or other types of modal behavior.

**Comment by samreid** [comment]
@jonathanolson and @pixelzoom will talk about this.

**Comment by pixelzoom** [comment]
4/27/17 dev meeting: @jonathanolson and I will talk about ways to do this.

**Comment by pixelzoom** [comment]
Skype:
> [6/12/17, 2:42:57 PM] Jonathan Olson: Pushing input interruption changes to common code. If you notice anything going wrong, contact me or comment in https://github.com/phetsims/scenery/issues/218 (has commits that would need to be reverted).
[6/12/17, 2:45:16 PM] Chris Malley: ph-scale has a relatively simple example of zoom buttons for the "Linear" scale in the "Micro" screen.  See ph-scale.GraphNode.
[6/12/17, 2:47:16 PM] Jonathan Olson: Note that now, subtypes of DownUpListener/SimpleDragHandler (like almost all of our listeners that matter), can be interrupted properly by calling interruptSubtreeInput() on a Node. It will "interrupt" the listeners on all descendants
[6/12/17, 2:48:11 PM] Chris Malley: Could this be a simple way to interrupt interactions when switching Screens? https://github.com/phetsims/joist/issues/70
[6/12/17, 2:48:30 PM] Jonathan Olson: My commit interrupts the freshly-inactive screen
[6/12/17, 2:48:52 PM] Jonathan Olson: So, that issue might have just been handled for almost all listeners
[6/12/17, 2:49:29 PM] Jonathan Olson: Haven't tested fully, but it should presumably be fixed

So this may have been handled.

**Comment by pixelzoom** [comment]
@jonathanolson indicated "haven't tested fully" and I'm unclear on how to test.  So unassigning myself for now.  Feel free to assign to me if it needs future test or review.

**Comment by pixelzoom** [comment]
This has been handled for awhile by Sim.js, using scenery's `interruptSubtreeInput` feature.  I.e.:

```js
    // When the user switches screens, interrupt the input on the previous screen.
    // See https://github.com/phetsims/scenery/issues/218
    this.currentScreenProperty.lazyLink( function( newScreen, oldScreen ) {
      if ( oldScreen === null ) {
        self.homeScreen.view.interruptSubtreeInput();
      }
      else {
        oldScreen.view.interruptSubtreeInput();
      }
    } );
```

See also https://github.com/phetsims/scenery/issues/218 and https://github.com/phetsims/joist/commit/b35547e9747cd53d5b3f702ac3caa95a907961d3.

So... closing
