### ISSUE TITLE
(Preferences Menu) Content for Preferences Menu and Voicing Toolbar

### ISSUE THREAD

**Issue by terracoda** [phetsims/joist#700]
@jessegreenberg, after March 25th Design meeting, @emily-phet and I went through all the content options I had laid out in the tables in the design doc.

I just cleaned up the tables, by copying them and removing all crossed out iterations. Please see the Preferences Menu Content (cleaned up) section
https://docs.google.com/document/d/1Qu3U8IsFYn486oJUzQ71BXs_lBKZTVS5NVdLJlTK7gw/edit#heading=h.yiz4f6yh55bs

I marked all tables (ready) except the "General Tab". I need to know more about that one. Is it always there, even if the sim has no sim-specific options?

@jessegreenberg, I'm still a little unsure about the Voicing responses for the different inputs when toggling the buttons and checkboxes that don't have direct help text. In my initial design for GFLB, I customized response to voice the button or checkbox label and state change.

The responses in the "Responses" column will work in the PDOM for sure, but a few still may need some tweaking for the Voicing experience to maintain consistency with the button and checkbox names.

**Comment by terracoda** [comment]
Yes, General Tab is always present when the preferences menu is enabled in a sim. May need to optimize content for that Tab for sims that don't have sim-specific options.

**Comment by jessegreenberg** [comment]
Alright @terracoda I think we are up to date here! As discussed I went through the doc and changed the red TODO text to a blue color to indicate what was complete. Can you please review the behavior here?
https://phet-dev.colorado.edu/html/john-travoltage/1.6.0-preferences.1/phet/john-travoltage_en_phet.html?supportsVoicing

**Comment by terracoda** [comment]
@jessegreenberg, I think you got everything except what I will review when I verify the changes for https://github.com/phetsims/john-travoltage/issues/401 

Nice work. Closing.
