### ISSUE TITLE
(Preferences Menu & Toolbar) Make Read-me buttons independent (if possible)

### ISSUE THREAD

**Issue by terracoda** [phetsims/joist#701]
From interviews I learned that the Read Me buttons (play buttons in Voicing Toolbar) are super helpful for many learners.

I'd like these read-me button to behave independently from both the Voicing on/off switch in the Toolbar and be unaffected by the checkboxes in the Voicing section of the Audio Preferences Tab.

**Reasoning:** The buttons do not change anything. They provide access to valuable state information. The content they "play" is not like an "object response" or "context response". I.e. the content is quite different from the Reset All button's context response. These read-me buttons just reveal the current state. This is why I think they need to unaffected the checkboxes that enable/disable the Object and Context Responses.

And because the content is delivered only on-demand, and doesn't ever get in the way, I would like them to remain accessible and enabled, even when the Sim Voicing on/off switch in the Tool bar is set to off.

I hope this is all possible.

**Comment by jessegreenberg** [comment]
The Toolbar buttons are now independent of "Sim Voicing" and "Preferences" options. Can you please verify this is working correctly in https://phet-dev.colorado.edu/html/john-travoltage/1.6.0-preferences.1/phet/john-travoltage_en_phet.html?supportsVoicing @terracoda?

**Comment by terracoda** [comment]
Seems to work great. 

I was a little thrown off that the read-me buttons are silent on focus, but I think that makes sense. The words are on the screen. The content still plays when button is pressed.

Closing.
