### ISSUE TITLE
(Voicing) Create shortcut key to stop voicing

### ISSUE THREAD

**Issue by terracoda** [phetsims/joist#702]
In research interviews with the Voicing sims, a couple of participants suggested a hotkey or shortcut key to immediately stop the voicing. The main screen readers on the market (JAWS, NVDA and VoiceOver) all use the Control key. It was suggested we use the same key for our Voicing feature.

This hotkey would not turn the feature off, it would just immediately stop it. This allows for a long stretch or continuous responses to be stopped for learners to discuss something or for a learner to move onto a new task (with voicing enabled).

@jessegreenberg, not sure if joist is the right repo for this issue.

**Comment by terracoda** [comment]
We all agreed at March 30th design meeting that a hotkey to stop the voice was a good idea.

**Comment by jessegreenberg** [comment]
This has been added @terracoda, can you please verify in https://phet-dev.colorado.edu/html/john-travoltage/1.6.0-preferences.1/phet/john-travoltage_en_phet.html?supportsVoicing?

**Comment by terracoda** [comment]
Awesome! The shortcut key works great.

**Comment by terracoda** [comment]
Closing.
