### ISSUE TITLE
About dialog refinements

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#71]
About dialog needs to be dressed up a bit, it's pretty primitive. 

Needs:
- logo
- improved spacing
- improved formatting of credits and thanks you

...anything else?

**Comment by pixelzoom** [comment]
In #190, @kdessau-PhET requested:
> In the HTML5 simulations, it would be good to add a Donate Now button in the About screen. People who actually are curious enough to go that screen would most likely donate. Page to link to is http://phet.colorado.edu/donate or https://donatenow.networkforgood.org/1437859

**Comment by jonathanolson** [comment]
Do we show the button if the brand shows "adapted from PhET"?

**Comment by pixelzoom** [comment]
Probably not. I'm not even convinced that we really want a "Donate" button that accessible to students. 

I'm assuming that we're going to triage all of the features mentioned in the issue before we do any work.

**Comment by ariel-phet** [comment]
More thoughts from @kathy-phet 

1) For "PhET Regular HTML Simulation Files" (the minified files), it would be nice if the about dialog had the CC-BY image, so its clearly CC-BY. Text can be small.
"This is a PhET Regular HTML Simulation File."
![ccby](https://cloud.githubusercontent.com/assets/4051174/6343048/4484a1fe-bb9f-11e4-9b19-475080ee570a.png)

2) The "PhET Enhanced HTML Simulations Files" could say instead "This is a PhET Enhanced HTML Simulation: Contact phethelp@colorado.edu to inquire about licensing"

3) Both simulation files would still have the "Terms, Privacy, and Licensing" text with the link to the website licensing page.

4) The "Enhanced" single file simulation files should have an additional header in the source code (above the 3rd party credits) that explains that it cannot be used unless properly licensed from University of Colorado. The feedback on the software agreement will help us understand what to put there.

**Comment by pixelzoom** [comment]
@ariel-phet Can you clarify what "Regular" versus "Enhanced" is?  And do you really want those terms to be public facing?

**Comment by samreid** [comment]
I'm going to remove the `licensing` label since we have decided that 3rd party credits will appear as a link from the About Dialog to the website.

**Comment by pixelzoom** [comment]
Still relevant.  Now dependent on revision of Dialog, https://github.com/phetsims/joist/issues/359.

**Comment by pixelzoom** [comment]
Actually, I think the About dialog is looking pretty good these days. The only improvement I'd make is the formatting of the credits.  Here's a recent example:

![screenshot_267](https://user-images.githubusercontent.com/3046552/26852906-215eda0e-4acd-11e7-88eb-14d7d1a9a9c1.png)

**Comment by pixelzoom** [comment]
Perhaps we can use RichText to make the credit categories ("Lead Designer", "Software Development",...) stand out from the person names.

**Comment by pixelzoom** [comment]
Here's the About dialog with RichText for the credits, and a wee bit more leading between the credits lines.  Unfortunately, RichText does not currently support line breaks. 

![screenshot_268](https://user-images.githubusercontent.com/3046552/26853277-9ac2d6d8-4ace-11e7-9de7-c665f8d892b9.png)

**Comment by samreid** [comment]
That looks pretty great @pixelzoom, we should go for it +1

**Comment by pixelzoom** [comment]
Two problems that must be addressed:

(1) Add line breaks and justification to RichText

(2) The markup must be included in joist strings, and that requires changes to English and translation string files.  E.g. "Lead Design: {0}" must be changed to "<i>Lead Design</i>: {0}".

**Comment by pixelzoom** [comment]
Labeling for developer meeting.  Questions:

(1) Should we bother with this at all?
(2) Should we add line breaks to RichText? 
(3) Should we change the strings that are related to credits? English only or translations? 
(4) Should RichText support both `<br>` and `\n` so that credits translations continue to work?

**Comment by jonathanolson** [comment]
> (2) Should we add line breaks to RichText?

I would like to add this.

> (4) Should RichText support both <br> and \n so that credits translations continue to work?

Even if we want both in credits, RichText could potentially only support `<br>`, and the AboutDialog could map `\n` to `<br>`.

**Comment by pixelzoom** [comment]
@jonathanolson said:
> Even if we want both in credits, RichText could potentially only support `<br>`, and the AboutDialog could map `\n` to `<br>`.

As I mentioned in https://github.com/phetsims/scenery-phet/issues/310#issuecomment-307822271, MultiLineText uses `\n`.  So whether to support `\n` involves more than the About dialog.

**Comment by samreid** [comment]
> (1) Should we bother with this at all?

It seems like a nice improvement though dealing with the translation files seems like the biggest hassle to me.

**Comment by pixelzoom** [comment]
6/15/17 dev meeting consensus:

• Adding styling too much work, investigate adding leading.
• Yes to the RichText changes, generally useful.

**Comment by pixelzoom** [comment]
I played around with increasing leading (spacing:5) and reducing font size (10pt).  Below is what I came up with.  It doesn't excite me, and I suspect that there will be mixed opinions about it.  So I'm going to bail on this issue. 

![screenshot_283](https://user-images.githubusercontent.com/3046552/27296351-c05450f2-54dd-11e7-8aa2-a1de0b2cf41d.png)
