### ISSUE TITLE
[Voicing] Preferences Dialog's click to dismiss listener triggers voicing string "Preferences audio tab"

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#710]
Steps to reproduce:

1. Launch sim
2.  In Preferences menu, turn on voicing
3. click away from the dialog.
4. Reopen the dialog, and correctly hear, "Preferences, audio tab" or whatever tab you are on
5. Click away to dismiss again, and you hear again, "Preferences, audio tab".

**Comment by jessegreenberg** [comment]
I just tested and I am no longer seeing this happening. I believe this has been fixed after changes in https://github.com/phetsims/scenery/issues/1217
