### ISSUE TITLE
(Voicing) Preference menu tabs are not being read out after reopening preference menu

### ISSUE THREAD

**Issue by Matthew-Moore240** [phetsims/joist#711]
**Test device**
Windows 10 desktop
**Operating System**
Windows 10 desktop
**Browser**
Firefox 88.0 (64-bit)
**Problem description**
With voicing on opening the preference menu you do not hear which tab you are currently on 
**Steps to reproduce**
Using only keyboard 
1. Turn on voicing
2. Close preference menu
3. Navigate away and then back to preference menu 

**Visuals**

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪John Travoltage‬
URL: https://phet-dev.colorado.edu/html/john-travoltage/1.6.0-preferences.4/phet/john-travoltage_en_phet.html
Version: 1.6.0-preferences.4 2021-04-28 22:49:44 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
Language: en-US
Window: 2048x1038
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by Matthew-Moore240** [comment]
I tested with using the mouse and it works fine. Its just keyboard navigation for me that doesnt work.

**Comment by jessegreenberg** [comment]
I wasn't able to see this happening so I checked in with @Matthew-Moore240 on slack and he said it isn't happening anymore on latest for him either. Closing this issue.
