### ISSUE TITLE
(Voicing) Minor change to context response for context changes checkbox

### ISSUE THREAD

**Issue by terracoda** [phetsims/joist#712]
Some iterations on the Sim Voicing checkbox labels occurred, and the word "indirect" was removed from the description, but is still in the confirming response. 

Since we have no reading blocks for the long checkbox labels, I have decided it is better to use the same wording in the confirming responses. Please change:

- Voicing indirect sim changes.
- Indirect changes muted.

To:

- Voicing other sim changes.
- Other sim changes muted.

**Comment by jessegreenberg** [comment]
This has been collapsed into #715, closing.
