### ISSUE TITLE
Maintenance release for initialScreen/homeScreen query parameters

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#714]
It would be good to have this added to sims retroactively where needed.

**Comment by jonathanolson** [comment]
See https://github.com/phetsims/QA/issues/642#issuecomment-834751816 for sims

**Comment by jonathanolson** [comment]
Patched the "broken" homescreen cases with patches for https://github.com/phetsims/joist/issues/641

**Comment by jonathanolson** [comment]
Looks like explicit decisions were made to error out and not launch simulations when one screen was visible:

```js
      // Problems related to query parameters throw errors instead of assertions (so they are not stripped out)
      if ( QueryStringMachine.containsKey( 'homeScreen' ) ) {
        throw new Error( 'homeScreen query parameter not supported for single-screen sims' );
      }
      if ( QueryStringMachine.containsKey( 'initialScreen' ) ) {
        throw new Error( 'initialScreen query parameter not supported for single-screen sims' );
      }
      if ( QueryStringMachine.containsKey( 'screens' ) ) {
        throw new Error( 'screens query parameter not supported for single-screen sims' );
      }
```

We don't do that in master... should I remove the explicit errors?

**Comment by kathy-phet** [comment]
I think doing what we do in master now is good. My understanding from what you write is, in master, we don't hard fail, we just launch the sim and ignore the query parameter.

**Comment by jonathanolson** [comment]
Patched, pending QA with RCs.

**Comment by jonathanolson** [comment]
Closing, handled in maintenance release deployment.
