### ISSUE TITLE
Changes requested for the Preferences dialog

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/joist#715]
Changes have been requested for some of the content in the Preferences dialog here
https://docs.google.com/document/d/1Qu3U8IsFYn486oJUzQ71BXs_lBKZTVS5NVdLJlTK7gw/edit#heading=h.jghy5z2qlft1

Things in red are what need to be changed.

**Comment by jessegreenberg** [comment]
Changes from the document have been made @terracoda. The new content that was red has been changed to blue to signify that it was done. I noticed that changes from #700 were still blue so it could be difficult to distinguish this issue's changes from that one's. If it would be helpful for me to list the changes from this commit to review, please let me know.

Link to review: https://phet-dev.colorado.edu/html/john-travoltage/1.6.0-preferences.5/phet/john-travoltage_en_phet.html

**Comment by terracoda** [comment]
Nice work @jessegreenberg.
The only thing missing is "Extra Sounds, " at beginning the reading block.

**Comment by jessegreenberg** [comment]
This was done in https://github.com/phetsims/scenery-phet/commit/16f5fe26b6e7d76a48dbdb6ad46dfb32f6c8212d, back to @terracoda to review in https://phet-dev.colorado.edu/html/john-travoltage/1.6.0-preferences.7/phet/john-travoltage_en_phet.html

**Comment by terracoda** [comment]
Extra Sounds is now in the reading block and sounds good.
Closing.
