### ISSUE TITLE
Long strings cause screen buttons to overlap

### ISSUE THREAD

**Issue by liam-mulhall** [phetsims/joist#718]
### Test Device

MacBook Air

### Operating System

macOS 11.2.3

### Browser

Safari 14.0.3

### Problem Description

For https://github.com/phetsims/QA/issues/650. Perhaps related to https://github.com/phetsims/joist/issues/645.

If you put in the standard `?stringTest=long` string (or one with a similar number of characters), the screen buttons get shifted over and can overlap. See the screenshot below. With ridiculously long strings, the screen buttons will disappear entirely.

Assigning @jonathanolson because he's working on #645 and these issues seem related.

### Visuals

![buttons](https://user-images.githubusercontent.com/60749003/119199374-28cf0680-ba48-11eb-9272-3eb5f22384d1.png)

**Comment by KatieWoe** [comment]
I saw a similar shift of the icon when the label text disappears as well.
![shiftingicon](https://user-images.githubusercontent.com/41024075/119535098-e9a0fe00-bd44-11eb-9cc0-fb11baa9b742.gif)

**Comment by pixelzoom** [comment]
Is this the same as https://github.com/phetsims/joist/issues/725?  

Seems like this should definitely be blocking.

**Comment by pixelzoom** [comment]
This is blocking https://github.com/phetsims/QA/issues/657 and https://github.com/phetsims/QA/issues/662.  Since the latter has top priority, this issue is elevated to top priority.

**Comment by samreid** [comment]
This seems like a duplicate of https://github.com/phetsims/joist/issues/725, closing as duplicate.
