### ISSUE TITLE
Screens parameter may not allow for multiple screens

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/joist#720]
For https://github.com/phetsims/QA/issues/653. Seen on Win 10 Chrome for Acid Base Solutions: https://phet-dev.colorado.edu/html/acid-base-solutions/1.2.25-rc.2/acid-base-solutions_en.html.

When using `?screens=X` with X being more than one screen (`?screens=1,2`) only the first one listed seems to show up. It does not seem to happen on all sims, however.

<img width="647" alt="onlyonescreen" src="https://user-images.githubusercontent.com/41024075/120858323-db6e9100-c53f-11eb-915f-ba953c50fa22.png">

**Comment by KatieWoe** [comment]
From @phet-steele on Slack:
>I believe that some Sims use a period instead of a comma, so that Sim will probably work with ?screens=1.2

So this can probably be closed

**Comment by KatieWoe** [comment]
In https://github.com/phetsims/QA/issues/653 @CliffordH123 said:
>screens parameter partially broken for energy-skate-park-basics 1.3.15-rc.2 phet-io. screens = to any one number works but trying to use a comma to have something like screens=1,3 does not work. Notably screens=2.3 does work.

**Comment by KatieWoe** [comment]
After some conversation with @jonathanolson we discovered that this issue wasn't in published and so should be fixed.

**Comment by jonathanolson** [comment]
I believe this was fixed up, but not closed!
