### ISSUE TITLE
Make layout for Screens and top layer Nodes take a Bounds2 instead of width/height values

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/joist#723]
This is needed for Preferences and the new Toolbar. The Toolbar will take up space and the layout of Screens needs to be adjusted to fit that content. The Toolbar appears on the left side of the screen (when visible) and and the Screen layout should shift to the right and scale down accordingly. The layout for each screen and top layer Nodes is currently set by functions with a signature of `( width: {number}, height: {number} )`, which assumes the Screen takes up all available space and is centered horizontally.

To to suppot layout with the Toolbar I am going to change `ScreenView.layout` and `layout` for Nodes added to the Sim top layer to take a Bounds2 instead of width/height values. Then, I am going to go through and update all sims overriding `layout` with this change.

**Comment by jessegreenberg** [comment]
This was done in the above commits. I tested that it is set up to work as we will need for the Toolbar by modifying the `availableScreenBounds` in Sim.js and seeing sim screen content shift over.

Then I tested local aqua for all sims and saw no errors. I did a local aqua test with `availableScreenBounds` modified and basically watched all sims and saw all sim content adjusted as I would expect.

This feels potentially pretty disruptive so should have a review before next publications. @jonathanolson would you mind being the reviewer? If you don't feel you have time feel free to reassign to me.

**Comment by jessegreenberg** [comment]
Over slack it was noted that this was a breaking API change that may impact 3rd party sims, once this review is done the change should be announced to the appropriate thread for the google group.

**Comment by jonathanolson** [comment]
Changes look good to me, nice job!

I believe molecule-shapes view is a bit broken due to not being upgraded to the 3d (https://github.com/phetsims/molecule-shapes/issues/184), I'll bump the priority for that.

Assigning back for the google group notification.

**Comment by jessegreenberg** [comment]
Great, thanks for reviewing! A notification was sent to the google group, closing this issue.
