### ISSUE TITLE
Create a single Property that enables/disables all audio

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/joist#724]
With the addition of "Voicing" there is a new type of audio for PhET sims. We need a way to be able to globally enable and disable all forms of audio at once, which currently includes Voicing, Sound, and Enhanced Sound.

The requested design is that the NavigationBarSoundToggleButton control all audio for the simulation. And there is going to be a toggle in the Preferences Dialog that enables and disables all sound too. There are more controls in the Dialog to enable and disable individual audio features.

To support this I propose that we
1) Add a Property to Sim.js called `allAudioEnabledProperty` to control this.
2) Pass this Property to the NavigationBarSoundToggleButton, and then use the same Property in the Preferences Dialog.
3) Add this Property to the list of Properties that turn down the gain when sound is disabled.

**Comment by jessegreenberg** [comment]
I added this in the above commits. @jbphet would you mind reviewing this, does this seem reasonable? After review is done we will want to instrument it with PhET-iO and then update APIs.

**Comment by jbphet** [comment]
It all looks decent to me, and seems to work in Balloons and Static Electricity.  I'd say go ahead and do the phet-io instrumentation and API update.

**Comment by pixelzoom** [comment]
This seems to be causing big problems, see https://github.com/phetsims/tambo/issues/145.

**Comment by pixelzoom** [comment]
I'm wondering... Why is `allAudioEnabledProperty` needed?  Isn't that what `soundManager.enabledProperty` does?

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/tambo/issues/145 I reported:
> The sound query parameter (and maybe other things?) is broken.  I’m running Fourier with `sound=muted`, as I have been for many months.  But now the sound icon in the navbar is not showing that sound is muted. Toggling the button in the navbar has no affect on sound (it remains muted) and does not enable the sound control for my Fourier series (which is observing` soundManager.enabledProperty`).

> If I run without `sound=muted`, then the sound control for my Fourier series is permanently enabled, and the `soundManager.enabledProperty` observer is never firing.

**Comment by pixelzoom** [comment]
Adding yet-another Property to Sim.js is really not doing it for me. As we’ve discussed many time in dev meetings…. Sim.js does not need more responsibilities. Unfortunately, adding things to Sim.js is a quick-&-dirty way to move forward.

I highly recommend to reconsider this design. All types of sound should be under the "sound manager" umbrella, with different subcomponents for different types of sound (voicing, sound, enhanced sound).

**Comment by jessegreenberg** [comment]
I think the name "soundManager" still fits for its current responsibilities. PhET's current terminology for these is grouped like
-"Audio" - All auditory features.
  - "Sounds" - Auditory output like sounds and sonifications, driven by web audio.
    - "Ehanced Sounds" - Like "Sounds" but categorized differently because they may not be beneficial to all learners.
  - "Voicing" - Speech that is  driven by SpechSynthesis.

So to have a "sound manager" that controls all forms of audio doesn't feel right. I think we should have an "audio manager" that controls the output of all audio features, rather than have these in Sim.js.  I propose:
- Create an AudioManager.js that maintains all of the audio related Properties that live in Sim.js. This could include 
  - allAudioEnabledProperty
  - soundEnabledProperty
  - enhancedSoundEnabledProperty
  - soundPartOfTheAPI
  - Initializing soundManager and webSpeaker
 
- For the query parameter issue, lets add a boolean `audio=true` query parameter that enables/disables all audio. 
- For the listener issue: There are listeners like this one in DiscreteControlPanel.js
```js
    // Disable this control when soundManager is disabled.
    soundManager.enabledProperty.link( enabled => {
      this.interruptSubtreeInput();
      soundEnabledCheckbox.enabled = enabled;
      outputLevelSlider.enabled = enabled;
      volumeOffIcon.opacity = enabled ? 1 : SceneryConstants.DISABLED_OPACITY;
      volumeUpIcon.opacity = enabled ? 1 : SceneryConstants.DISABLED_OPACITY;
    } );
```

It needs to be linked to both soundManager.enabledProperty and allAudioEnabledProperty now. We could add a DerivedProperty to the AudioManager that provides this.

**Comment by jessegreenberg** [comment]
Id like to discuss this with @jbphet at least before continuing again, but wouldn't be surprised if we bring it to dev meeting.

**Comment by pixelzoom** [comment]
> It needs to be linked to both soundManager.enabledProperty and allAudioEnabledProperty now. 

Why does it need to be linked to both?

**Comment by jessegreenberg** [comment]
The button in the nav bar is for all *audio* now. Sound can be disabled while all audio is still enabled. And audio can be disabled while sounds are still enabled, though in that case there will still no output. I am assuming that the UI component should be disabled in cases where there is no output, so it needs to be linked to both Properties.

**Comment by pixelzoom** [comment]
The enabled state of the sound control for my Fourier series is supposed to match whether sound in on or off in the navbar.  Based on your discription, it sounds like I need to listen to the same Property as the button in the navbar.  So again... Which Property does that button link to, or is it also linking to both?

**Comment by pixelzoom** [comment]
@samreid FYI there are 2 listeners being added to `soundManager.enabledProperty` in WaveInterferenceConrolPanel.js.  I see this same problem with those listeners and the `sound` query parameter.

**Comment by pixelzoom** [comment]
> Id like to discuss this with @jbphet at least before continuing again, but wouldn't be surprised if we bring it to dev meeting.

Is there something we can do in the short-term to fix this? The `sound` query parameter is broken, as are my listeners for `soundManager.enabledProperty`.

**Comment by jessegreenberg** [comment]
The nav bar button links to `sim.audioEnabledProperty`.  A separate control in the Preferences dialog controls soundManager.enabledProperty. When either are false, no sound will come out of the sim.  If all we you care about is matching the nav bar button then then it could just link to audioEnabledProperty. But I assumed that the behavior for the component in DiscreteControlPanel should happen whenever sound is not coming out of the sim, in which case it will need to link to both.

**Comment by jessegreenberg** [comment]
> Is there something we can do in the short-term to fix this?

@pixelzoom @samreid -  As a temporary workaround the "sound" query parameter is now used to set the initial value of sim.allAudioEnabledProperty. If listeners link to `phet.joist.sim.allAudioEnabledProperty` instead of `soundManager.enabledProperty` it will work as before until we have a better fix.

**Comment by pixelzoom** [comment]
@jessegreenberg said:
> EDIT: Here is the current Audio panel in Preferences which may illustrate the relationship between these Properties.

Thanks, that helps a lot.  How do I get to the Preferences panel?  

The  Panel looks nice.  But I would be concerned that users will turn off Sound in the Preferences panel, then be very confused when toggling the sound control in the navbar results in no change.  Having multiple levels of sound like this is going to be very challenging for the typical user to understand.

**Comment by pixelzoom** [comment]
@jessegreenberg said:
> As a temporary workaround the "sound" query parameter is now used to set the initial value of sim.allAudioEnabledProperty. 

In the above commit, I've added a TODO, indicating that "sound" no longer does what it was intended to do.  

I've also added TODO for my workaround in Fourier, referencing this issue.   So when this issue is addressed, please search to TODOs related to this issue.

**Comment by pixelzoom** [comment]
> As a temporary workaround the "sound" query parameter is now used to set the initial value of sim.allAudioEnabledProperty.

If you want to revert this workaround now, I'm going to stop using the "sound" query parameter, because it's still broken. To reproduce in Fourier:

1. Start the sim with `?sound=muted`.
2. Note that the sound icon in the navbar indicates that sound is off. Interact with a few UI components to confirm.
3. Click on the sound icon in the navbar to turn sound on.  Interact with a few UI components and you'll see that sound is not working. 

If I start the sim without `sound=muted` and use the sound button in the navbar to turn if off, it works OK.  It's a hassle, and I don't want to hear sound all the time, but I'm not aware of any working alternative to stop sound on startup.

**Comment by samreid** [comment]
Unassigning, since my part was moved to https://github.com/phetsims/wave-interference/issues/524

**Comment by jessegreenberg** [comment]
Discussed during developer meeting today, @jbphet @jessegreenberg and @pixelzoom will be the subgroup to work on this.

**Comment by samreid** [comment]
It's unclear from the proposal in https://github.com/phetsims/joist/issues/724#issuecomment-875098337 whether we prefer the proposed terminology, or if we feel painted into a corner since "sound" currently refers to sonification and sound effects and not voicing.  Let's keep in mind that we may want to relax our definitions for this, especially for things that are client-facing. (If we want it to be called the sound manager instead of the audio manager).

**Comment by pixelzoom** [comment]
I agree with the previous comment, especially for public-facing terminology. Expecting a typical user (or even developers/designer) to understand the difference between "sound" and "audio" is unreasonable.

**Comment by pixelzoom** [comment]
Btw... PhET's current distinction between "audio" and "sound" is non-standard and uniquely PhET.   Sound is a generic word, coming from any source. Audio is sound coming from a recording, transmission, or electronic device.  Making up new definitions for these terms is confusing to everyone.

**Comment by jessegreenberg** [comment]
OK, thanks for the feedback. I started https://github.com/phetsims/joist/issues/729 to discuss and review terminology with the team so we can keep this issue about the implementation of the Property.

**Comment by pixelzoom** [comment]
@jessegreenberg @jbphet and I met on Zoom about this issue today.  @jessegreenberg has more extensive notes, but here are mine.

* We like what's in https://github.com/phetsims/joist/issues/724#issuecomment-875098337, but prefer audioManager.js and `audioEnabledProperty`.
*  "Sound" has become a confusing term, because its PhET-specific definition is very different from the standard definition.  So be very consistent about the use of "audio", "voicing", and "sound" terms -- in file names, query parameters, public-facing labels, documentation, etc.
* `sound` is a public query parameter, and its behavior has changed. It no longer controls the state of the audio button in the navbar.  Does this need to be communicated to users?
* If we're writing code that observes Properties of audio subsystems, how do we test this code without having a Preferences dialog? For example, Fourier listens to `soundManager.enabledProperty` - how do I verify that toggling that Property has the correct behavior?

Things I thought of after our meeting:

* Consider renaming webSpeaker.js to voicingManager.js, so that "audio", "voicing", and "sound" terminology is consistent throughout the implementation.  It doesn't matter that voicingManager.js uses Web Speech, that's an implementation detail that doesn't need to be reflected in the name.

**Comment by pixelzoom** [comment]
In the comment above, I asked:
> If we're writing code that observes Properties of audio subsystems, how do we test this code without having a Preferences dialog? For example, Fourier listens to `soundManager.enabledProperty` - how do I verify that toggling that Property has the correct behavior?

I discovered that I do this in the console for the "Sound" subsystem:
> phet.tambo.soundManager.enabledProperty.value = false
phet.tambo.soundManager.enabledProperty.value = true

Perhaps I'll be able to do the same thing with other audio subsystem.

**Comment by jessegreenberg** [comment]
That summary is great, thanks. Ill be working on https://github.com/phetsims/joist/issues/724#issuecomment-875098337 with the changes described, then bring it back to the sub group for review. This is still blocking publication of sims with sounds so the labels still apply.

**Comment by pixelzoom** [comment]
Self unassigning for now.  @jessegreenberg let me know if there's anything you'd like me to review, I'll be happy to have a look.

**Comment by pixelzoom** [comment]
Let me know if there's anything you'd like me to review, I'll be happy to have a look.

**Comment by jessegreenberg** [comment]
This is done in the above commits. Everything pretty much went according to plan from the above comments. To summarize the overall changes again for the reviewer:
- Properties and fields related to Sound and Voicing were moved out of Sim.js into a new audioManager.js.
- An `audio` query parameter was added with the same API as `sound`.
- NavigationBarSoundToggleButton was renamed to NavigationBarAudioToggleButton.
- audioManager has public DerivedProperties that indicate the various combinations of enabled subcomponents under "Audio", for use in Sims and common code.

@pixelzoom also commented 
> Consider renaming webSpeaker.js to voicingManager.js, so that "audio", "voicing", and "sound"

Good idea, I did that in a different issue https://github.com/phetsims/scenery/issues/1227.

> I discovered that I can this in the console for the "Sound" subsystem:
>>phet.tambo.soundManager.enabledProperty.value = false
>>phet.tambo.soundManager.enabledProperty.value = true

>Perhaps I'll be able to do the same thing with other audio subsystems.

Yes, there is access to these:
`phet.joist.audioManager.audioEnabledProperty.value = false`
`phet.scenery.voicingManager.enabledProperty.value = false`

Over slack I announced the new `audio` query parameter and it was added to the params google doc.

This is ready for a review, @jbphet would you mind taking a look?

**Comment by jessegreenberg** [comment]
Over slack @pixelzoom offered to review as well, and whoever is available to review first can take it on. Assigning to him, and thanks!

**Comment by pixelzoom** [comment]
I had a chance to review this morning.  This was an easy review, because it's done so well.  Solid code. Clear documentation - especially in audioManager.js. This is a huge improvement.  Nice work!  

Back to @jessegreenberg.  Feel free to close, unless you also want @jbphet to have a look.

**Comment by pixelzoom** [comment]
In the above commit, I replace a Fourier multilink with `audioManager.audioAndSoundEnabledProperty`.  It works great.

**Comment by jessegreenberg** [comment]
Thanks much for the review @pixelzoom. Based on comments over slack between the sub-group of devs working on this issue, I think it is OK to close. But @jbphet feel free to reopen and take a look if you wish.
