### ISSUE TITLE
AboutDialog layoutBounds look problematic

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#73]
AboutDialog is apparently implemented as a ScreenView subtype, and it appears to use the default layoutBounds.  If the sim uses a non-default layoutBounds (which some do) then the AboutDialog's layoutBounds won't match what the sim is using. And this means that there's the potential for the About dialog to overlap the navigation bar (or worse?)

Using the '?dev' query parameter shows the layoutBounds as a red outline. Below is a screenshot for graphing-lines ('master'). The bright red is the AboutDialog's layoutBounds, dark red is the 'Line Game' screen. Note how the AboutDialog's bounds are overlapping the navigation bar.

So 2 questions: (1) Does AboutDialog really need to be implemented as a subtype of ScreenView? (2) What can be done to ensure that its layoutBounds are well-behaved?

![layoutbounds](https://f.cloud.github.com/assets/3046552/1434391/349c708a-4118-11e3-9311-a4a94ff438c3.jpg)

**Comment by jonathanolson** [comment]
This is fixed by the work in #166, closing.
