### ISSUE TITLE
Use fontawesome icons in NavigationBarSoundToggleButton

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#730]
Noticed while working on https://github.com/phetsims/sherpa/issues/83.

I understand why the navigation bar isn’t using SoundToggleButton — it must be a joist button, hence NavigationBarSoundToggleButton.  

But is there a reason why NavigationBarSoundToggleButton isn’t using the fontawesome icons that are used by SoundToggleButton, and is instead drawing complicated shapes that are almost identical to the fontawesome icons?   This creates 2 issues: inconsistency of sound icons, and having to maintain complicated shapes.

**Comment by chrisklus** [comment]
I tracked down the [commit](https://github.com/phetsims/joist/commit/c444bc811712839e707edf7656ad1ec5c1fc3ced) that replaced the font-awesome icons and the associated issue, from https://github.com/phetsims/tambo/issues/19#issuecomment-405775273:

>@jbphet and I worked on drawing out the sounds icon with code instead of using the font awesome icon since it was 4 MB.

>In the process, we addressed what hadn't yet been done on the code end to match @arouinfar's screen shot from above, including vertically center aligning the icon with the 'P' and evenly spacing out the icons horizontally. I also slightly decreased the stroke of the X lines and curves to better match the outline of the keyboard. Here's what has currently been pushed:

![image](https://user-images.githubusercontent.com/5618316/42853297-d559cf40-89f2-11e8-942e-13738f9e32da.png)

>@jbphet and I also discussed the possibility of removing the fill from the sound speaker so that it better matches the keyboard and doesn't draw the eye as much. I can discuss this idea and the fine tuning details of the above changes with @arouinfar. Preview of what this could look like:

![image](https://user-images.githubusercontent.com/5618316/42853411-77a4c5f2-89f3-11e8-9d1f-3438f6647e8d.png)


Sounds like the two reasons were:

1. the FA icon was an extra 4 MB that was nice to cut (no idea if this is still the case or if that size is an issue)
2. We had the control to stroke the speaker and sound lines to match the keyboard outline. This appears to still be in the same state, though i'm unsure how desirable this still is compared to FA (I personally prefer the shape of this speaker). Sounds like a question for designers.

From BASE master:

![image](https://user-images.githubusercontent.com/5618316/125833010-78c64db9-36d9-46db-9228-809d0c100cf6.png)

**Comment by jbphet** [comment]
@pixelzoom said:

> But is there a reason why NavigationBarSoundToggleButton isn’t using the fontawesome icons that are used by SoundToggleButton[?]

@chrisklus has described the reasons above (thanks for looking at this @chrisklus).  I've added a comment with an explanation to the file header.  @pixelzoom - Since you opened the issue, please review the response.  If you think it's satisfactory, this can be closed.  If not, please assign to a designer to decide if we should revisit.
