### ISSUE TITLE
Zooming into older published sims with a trackpad in Safari can break layout

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/joist#731]
Initially reported in https://github.com/phetsims/bending-light/issues/400, but moving to joist because it is happening in many other sims too.

Zooming into old sims with a MacOS trackpad while using Safari can break sim layout and cause the whole sim to be shifted off screen.

Example:
https://drive.google.com/file/d/1sL5t2mTmJtT17eugVSTyiB8RJkDBTsD0/view?usp=sharing

This will happen for all sims that were published prior to the addition of PhET's pan and zoom support, and was the behavior for all sims for many years. So I don't know if it is worth going back to republish old sims to fix this. @kathy-phet can you please review this issue and comment on whether it is worth the time to fix?

I am not sure yet, but I think this is a bug because sims didn't prevent default for the `gesturestart` and `gesturechange` events that initiate trackpad zooming. Work for this issue would be to verify the cause, determine which published sims predate the addition of pan and zoom, apply patches, then republish all in a batch of maintenance releases.

**Comment by zepumph** [comment]
Noting here as I go through issues for https://github.com/phetsims/joist/issues/703. I would recommend keeping this on your plate, to make sure that things don't get lost in @kathy-phet's workload.

**Comment by kathy-phet** [comment]
Let's not plan on fixing this issue in older sims, and rather look forward to adding and republishing them with pan/zoom/keyboard nav features. 

Closing as won't fix.
