### ISSUE TITLE
Screenshot option in PhET menu is no longer hidden on iOS

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/joist#739]
Found during https://github.com/phetsims/qa/issues/676, but it seems to impact every sim I looked at on the website. Seen on iPadOS 14.7.1, iPhone iOS 14, and iPadOS 12.

Until recently, the Screenshot option in the PhET menu has been disabled on iPad and iPhone devices due to various bugs. I noticed while testing John Travoltage that the option was available. It is also available on many published sims, including older ones. It is also available on older OS. It was definitely not an option before, and I'm not sure when or how it was introduced. It may be connected to a maintenance release.

**Comment by pixelzoom** [comment]
In PhetMenu.js:

```js
    const isApp = phet.chipper.isApp;
...
      // "Screenshot" Menu item
      {
        text: menuItemScreenshotString,
        present: !isApp, // Not supported by IE9, see https://github.com/phetsims/joist/issues/212
```

In initialize-globals.js:

```js
    /**
     * When a simulation is run from the PhET iOS app, it should set this flag. It alters statistics that the sim sends
     * to Google Analytics and potentially other sources in the future.
     *
     * Also removes the following items from the "PhET Menu":
     * Report a Problem
     * Check for Updates
     * Screenshot
     * Full Screen
     */
    'phet-app': { type: 'flag' },
...
    /**
     * When a simulation is run from the PhET Android app, it should set this flag. It alters statistics that the sim sends
     * to Google Analytics and potentially other sources in the future.
     *
     * Also removes the following items from the "PhET Menu":
     * Report a Problem
     * Check for Updates
     * Screenshot
     * Full Screen
     */
    'phet-android-app': { type: 'flag' },
...

  // Are we running in an app?
  window.phet.chipper.isApp = phet.chipper.queryParameters[ 'phet-app' ] || phet.chipper.queryParameters[ 'phet-android-app' ];
```

So the Screenshot menu item is currently hidden only if running in the PhET iOS or Android app.

I see no commits in PhetMenu.js to indicate that Screenshot was ever hidden on iOS.  But I may have missed something.

**Comment by pixelzoom** [comment]
@KatieWoe is is possible that you're thinking of situation where you've run the sim _from the iOS app_, versus just running the sim on iOS?

**Comment by KatieWoe** [comment]
No, it was definitely from safari. I'm quite certain of that. It's been the case since I started working here and I remember revisiting it to see if bugs still occurred and they did.

**Comment by KatieWoe** [comment]
Actually looking back, I may be thinking of full screen. But I could have sworn it was both.

**Comment by pixelzoom** [comment]
Full Screen menu item is definely hidden on iOS (mobile Safari).  From PhetMenu.js:

```js
      // "Full Screen" menu item
      {
        text: menuItemFullscreenString,
        present: FullScreen.isFullScreenEnabled() && !isApp && !phet.chipper.isFuzzEnabled() && !platform.mobileSafari,
```
