### ISSUE TITLE
 offline solution: what to do about features that require an Internet connection?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#74]
...for example the "PhET website" and "Report a Problem" menu items. If you're running offline, these features are still available and fail.

**Comment by pixelzoom** [comment]
Still relevant.  

First, we need a complete list of features that require an Internet connection. 

Second, we need to pick an approach. For features that require an Internet connection, the options are (1) disable features, or (2) hide features.

**Comment by jonathanolson** [comment]
The "up-to-date" display in the About dialog should function without internet (letting people know it wasn't able to check).

Presumably the "can we connect to the internet" would come after the PhetMenu has been constructed, so we'd need to consider after-the-fact disabling/removing, correct?

**Comment by pixelzoom** [comment]
> Presumably the "can we connect to the internet" would come after the PhetMenu has been constructed, so we'd need to consider after-the-fact disabling/removing, correct?

I've added an option (3) above, which is to keep the features enabled, but have them gracefully handle lack of an internet connection, e.g. by informing the user they there's no Internet connection.  "Failing" in a way that affects the sim should not happen.

**Comment by pixelzoom** [comment]
I'm not convinced that we need to do anything for the issue.  Here's what I see when running a downloaded sim offline.

In the About dialog, "Unable to check for updates":

![screenshot_266](https://user-images.githubusercontent.com/3046552/26851750-074fa7be-4ac9-11e7-800c-79c4c704f859.png)

Selecting "Check for Updates" from the PhET menu:

![screenshot_265](https://user-images.githubusercontent.com/3046552/26851751-0750ea20-4ac9-11e7-8fcd-ead752526f7f.png)

Selecting "PhET website" or "Report a Problem" from the PhET menu (Safari, similar in Chrome and Firefox):

![screenshot_264](https://user-images.githubusercontent.com/3046552/26851752-075a3c74-4ac9-11e7-8c44-5f9d35ee9d86.png)

@ariel-phet, does this seem sufficient?

**Comment by ariel-phet** [comment]
It does seem sufficient to me. Closing.
