### ISSUE TITLE
(Preferences) Change to content on General Tab

### ISSUE THREAD

**Issue by terracoda** [phetsims/joist#740]
With upcoming changes to the sim pages on the website, we want the content in the General Tab in the Preferences menu to match.

No changes to the first paragraph:
**Current content:**
> We are adding features to our simulations to make them more inclusive. Some of these features support accessibility for learners with diverse needs and within diverse environments. Explore the tabs in this menu to review or change the default presentation settings.

> To find other simulations with accessibility features, go to the simulation filter page on the PhET website, and filter by Accessibility feature.

**Two versions of second paragraph:**
1. To find other simulations with inclusive features, go to the simulation filter page on the PhET website, look for Access and Inclusion and filter by inclusive feature.
2. To find other simulations with inclusive features, look for Access and Inclusion on the simulation filter page and filter by inclusive feature.

@emily-phet, I like the second one better. Do you have a preference?

**Comment by terracoda** [comment]
Thanks @emily-phet.

**Comment by terracoda** [comment]
@jessegreenberg, we would like this change in the the first release of JT, and we are hoping it will align quite closely with the publication of the new sim page design on the main website. The new sim page design uses the same language of inclusion.

**Comment by jessegreenberg** [comment]
Got it, thanks - Ill make this change in master and cherry pick into the JT release branch.

**Comment by jessegreenberg** [comment]
This string has been updated, closing.
