### ISSUE TITLE
Right-align contents of A11yButtonsHBox

### ISSUE THREAD

**Issue by arouinfar** [phetsims/joist#747]
A sim can currently have up to three buttons grouped next to the PhET logo:
![image](https://user-images.githubusercontent.com/8419308/133861099-8d4969d5-ff63-4c1a-a268-62c9f16702f3.png)

With PhET-iO customization, one or more of these buttons can be hidden, leaving behind a gap between the buttons and the PhET-iO logo. It already appears that the HBox is utilizing dynamic layout, since the keyboard button shifts over when the audio button is hidden:
![image](https://user-images.githubusercontent.com/8419308/133861182-d7ddbd74-b0a3-4b5c-bb43-64d5afe758ff.png)

It seems like the buttons are left-aligned within their box, and as icons are hidden, the remaining contents scoot to the left. It would be preferable to instead right-align the contents of the HBox, so that the padding between the rightmost button and the PhET-iO logo is consistent.

Here are some mockups of what it would look like if one or more of the buttons is hidden:
![image](https://user-images.githubusercontent.com/8419308/133861983-409eb57a-1d6e-4271-867f-0f24c6febf69.png)

This doesn't really feel like a PhET-iO specific issue, though it was motivated by PhET-iO design, so I'll pass this off to the responsible dev, @zepumph.

**Comment by zepumph** [comment]
@jessegreenberg, can you help with this, I know you have done a fair bit of this layout.

I tried this patch, and thought it would work because the layout is set from the right of the node (https://github.com/phetsims/joist/blob/33aab76edf4019b34a23ace105389ae787c251a3/js/NavigationBar.js#L341)


```diff
Index: js/A11yButtonsHBox.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/A11yButtonsHBox.js b/js/A11yButtonsHBox.js
--- a/js/A11yButtonsHBox.js	(revision 7f9fce34497d46ea70e59fce32698a952fb79c72)
+++ b/js/A11yButtonsHBox.js	(date 1632152710280)
@@ -26,7 +26,8 @@
   constructor( sim, backgroundColorProperty, tandem, options ) {
 
     options = merge( {
-      align: 'center',
+      align: 'right',
+      resize: true, // maybe?
       spacing: 6
     }, options );
 

```


@jessegreenberg, what do you think?

**Comment by jessegreenberg** [comment]
I think re-calling this part of `NavigationBar.layout` is what would be needed for this.
https://github.com/phetsims/joist/blob/33aab76edf4019b34a23ace105389ae787c251a3/js/NavigationBar.js#L339-L342

`right` alignment is only for vertical LayoutBoxes and `resize: true` should be enabled by default, though using that is probably important so the A11yButtonsHBox does have the correct bounds when setting its `right`.

**Comment by zepumph** [comment]
But the a11y buttons is an HBox, and thus, a LayoutBox, so I thought we would be getting this for free from `excludeInvisibleChildrenFromBounds`. This should call a relayout on the hbox each time any child's visibility is changed. I'll keep investigating

**Comment by jessegreenberg** [comment]
That's true, but changing layout of HBox children won't automatically reposition the HBox itself. On master, if you toggle `general.view.navigationBar.audioToggleButton.visibleProperty` and then resize the A11yButtonsHbox.right is set correctly.

**Comment by zepumph** [comment]
With this code in `NavigationBar.js` I was able to confirm that the HBox was re-laying out, but that it didn't respect the right dimension of it. Thanks for explaining.


```js

    const x = Rectangle.bounds( this.a11yButtonsHBox.bounds, { stroke: 'red' } );

    this.a11yButtonsHBox.boundsProperty.link( bounds => {
      x.rectBounds = bounds;
    } );

    this.barContents.addChild( x );

```


I also didn't want to deal with calling the whole layout function, which would require dimensions and scale parameters. Instead I factored out just the re-layout code that I needed for this task.

What do you think @jessegreenberg?

**Comment by jessegreenberg** [comment]
Your change was great, thanks. Note that master now uses `ManualConstraint` for dynamic layout so this can be closed.

https://github.com/phetsims/joist/blob/74f37398c5a74e007bc2e72765d2313112159ed4/js/NavigationBar.ts#L305-L311
