### ISSUE TITLE
Hide focus highlights and show Interactive Highlights if there is a certain amount of mouse/touch movement

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/joist#751]
Interactive Highlights are a different set of highlights that activate when the mouse/touch Pointer are over an interactive component. We decided in https://github.com/phetsims/balloons-and-static-electricity/issues/523 to make it so that when focus highlights are visible in the sim that Interactive Highlights should never activate to prevent cases where Interactive Highlights and focus highlights conflict.

In https://github.com/phetsims/balloons-and-static-electricity/issues/541#issuecomment-919451180 it was proposed that this could be improved such that when a small amount of mouse/touch movement occurs we re-activate Interactive Highlights and hide focus highlights.

**Comment by jessegreenberg** [comment]
This was reviewed with the team today and people thought it felt natural.

**Comment by jessegreenberg** [comment]
@zepumph would you mind reviewing HighlightVisibilityListener and the change to Sim.js? For Sim.js it was mostly just pulling code out of that class. For HighlightVisibilityListener I am most curious what you think of the structure. It is a listener that gets added to the Display that also adds listeners to the Display. Maybe that is confusing. For the `moveListener` that gets added/removed that seems fine. But for the static listeners I kind of liked how they were added with iteraction

```js
    [ 'click', 'input', 'change', 'keydown', 'keyup' ].forEach( eventType => {
      focusHighlightVisibleListener[ eventType ] = setHighlightsVisible;
    } );
    this.display.addInputListener( focusHighlightVisibleListener );
```

But I could also see it being easier to understand if they were each functions on HighlightVisibilityListener.

**Comment by zepumph** [comment]
I was surprised that I didn't see this feature when interactive highlights is not enabled. Is that expected? I would have thought that when I press tab, then move my mouse, it would hide the focus highlight. Is this part of the feature set?

**Comment by jessegreenberg** [comment]
No, my understanding was that this should only happen when the "Interactive Highlights" feature is enabled. I don't think it is necessary to hide them on move unless we need to make space for the other set of highlights. But it would not be difficult to change if people feel differently.
