### ISSUE TITLE
Hiding whole screen does not carry over when sim is previewed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/joist#757]
**Device**
Dell (and others)
**OS**
Win 11 (and others)
**Browser**
Chrome
**Problem Description**
Found during https://github.com/phetsims/qa/issues/718. In studio, if you hide a whole screen, then preview the sim, the state does not save the hidden screen.

![allvisible](https://user-images.githubusercontent.com/41024075/137018745-e4c0f697-d2ea-4b52-9991-824961ece922.gif)

**Comment by zepumph** [comment]
I don't think this should block publication btw. Many sims have been deployed with this behavior.
