### ISSUE TITLE
Enabling `supportsSound` doesn't cause the sound icon to appear on the nav bar

### ISSUE THREAD

**Issue by jbphet** [phetsims/joist#758]
In the past, using the query parameter `supportsSound=true` would turn on sound for a simulation that wasn't configured for it by default, and one of the effects of this would be to add the sound control icon to the nav bar.  Below are a couple of links that demonstrate this for the sim Energy Skate Park, a sim for which sound is not turned on by default:

- Without sound: https://phet-dev.colorado.edu/html/energy-skate-park/1.0.0-dev.5/phet/energy-skate-park_en_phet.html
- With sound:  https://phet-dev.colorado.edu/html/energy-skate-park/1.0.0-dev.5/phet/energy-skate-park_en_phet.html?supportsSound

In this example, when `supportsSound` is used, the sound icon shows up on the nav bar:

![image](https://user-images.githubusercontent.com/3082831/137963518-e59a3409-03d7-4511-9dfc-838181397175.png)

This doesn't work on the current master version.  Sound gets turned on, but the icon doesn't get added to the nav bar.

I took a quick look through the code, and I suspect the problem is in `A11yButtonsHBox.js` around the part that looks like this:
```js
    // If the sim has sound support in its API, then create the button. This is support consistent API for PhET-iO
    if ( audioManager.soundPartOfTheAPI ) {
      const audioToggleButton = new NavigationBarAudioToggleButton(
        audioManager.audioEnabledProperty,
        backgroundColorProperty,
        tandem.createTandem( 'audioToggleButton' )
      );

      // only put the sound on/off button on the nav bar if the sound library is enabled
      if ( audioManager.supportsAudio ) {
        a11yButtons.push( audioToggleButton );
      }
    }
```

The git history for this code has commits from both @jessegreenberg and @zepumph, so I'm going to assign to both of them and they can sort out who will tackle the problem.

**Comment by jbphet** [comment]
Also, the icon doesn't get added when `supportsSound` is added to the `package.json` file.

**Comment by zepumph** [comment]
I'll take a look.

**Comment by zepumph** [comment]
Today during PhET-iO meeting, we decided that it would be best to just always create the button, and ignore the "*PartOfTheAPI" flag, and then only conditionally add it to the nav bar.

**Comment by samreid** [comment]
For my understanding: It seems the problem in the issue description is that the client supplied `?supportsSound` without  toggling `soundPartOfTheAPI` to be true as well.  So since it thought sound wasn't part of the API, `?supportsSound` was a no-op.  It sounds like it simplifies things to just eliminate the "API" flags and assume they are always true.  I'll work toward removing the sound API flag, then open other issue(s) for other api flags.

**Comment by samreid** [comment]
I removed the `soundPartOfTheAPI` flag, always create the NavigationBarAudioToggle and conditionally add it.  Tested OK in energy skate park (a sim without sound) including with ?supportsSound=true and area-builder (a sim with sound) including with ?supportsSound=false.  Still, this would be good to be reviewed before we publish with it in case I'm missing something.  The only other term with `partOfTheAPI` is `accessibilityPartOfTheAPI`, so if this checks out we can do that one next?

**Comment by samreid** [comment]
This introduced a number of API changes discovered on CT, self-assigning for investigation.

**Comment by samreid** [comment]
OK I updated the API files, re-ready for review.

**Comment by zepumph** [comment]
This looks great. I used this pattern over in https://github.com/phetsims/joist/issues/765 as well. I just closed it because it was basically the same, but feel free to spot check if you'd like. Anything else here?

**Comment by samreid** [comment]
That seems good, thanks!  Closing.
