### ISSUE TITLE
PDOM should be dynamic to sim/screen name change

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#762]
I believe that this is the case because of the linking that occurs in https://github.com/phetsims/joist/blob/0f950e236b97bd9af12ecfc54f9b1116fc20c0ed/js/Screen.js#L269-L294, but it will be best to double check as part of https://github.com/phetsims/phet-io/issues/1611

This came out of today's design meeting in https://github.com/phetsims/friction/issues/236

**Comment by zepumph** [comment]
@terracoda and I just saw that changing the simNameProperty in `friction.general.model.simNameProperty`


didn't change the H1 (`Friction`)

**Comment by zepumph** [comment]
Ok, after this change, Here is what the PDOM looks like when I change the `ratioAndProportion.general.model.simNameProperty` to "Other Sim Name" and the `ratioAndProportion.discoverScreen.nameProperty` to "Oh Hello". This is running with `screens=1` so there isn't a home screen.:

![image](https://user-images.githubusercontent.com/6856943/157475034-50aaadf9-e940-4ae3-8168-2483ff9ca2bc.png)

**Comment by zepumph** [comment]
I also ran into a bit of a rabbit hole because of some bad practices we were doing for the screen button icon in https://github.com/phetsims/ratio-and-proportion/issues/444. 

Now all sim/screen related name changes via instrumented PhET-iO properties should be updating in the PDOM as well. I tested in:
* Multiscreen sim on home screen and individual screens (sim and screen names)
* Single screen sim (sim name, as there is no screen name Property instrumented in this case
* Multiscreen sim with screens=1 where the title looks like "Ratio and Proportion -- Discover Screen" in the nav bar and in the PDOM.

All is looking good here!

I am actually going to ask @chrisklus to review this one, because we were involved with adding these PhET-iO Properties to joist in the first place. Does this look acceptable to you? You can follow steps in https://github.com/phetsims/studio/issues/241#issuecomment-1062474657 to load RAP in studio in the a11y view :).  Let me know if you can think of any other changes we may want to d.

**Comment by chrisklus** [comment]
Apologies for the delay here. Everything is looking good to me too! I tested by changing all related Properties in Studio after following the instructions from https://github.com/phetsims/studio/issues/241#issuecomment-1062474657. The commits look good and I can't think of anything else to change. Back to @zepumph to close if all set.
