### ISSUE TITLE
Instrument AboutDialog and UpdateDialog with Voicing

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/joist#763]
The AboutDialog and UpdateDialog needs to be instrumented with Voicing. This likely means converting the Text used in the Dialog to VoicingText, which mixes ReadingBlock.

**Comment by jessegreenberg** [comment]
This blocks publication of Friction and was caught in https://github.com/phetsims/friction/issues/269.

**Comment by jessegreenberg** [comment]
The Text for these dialogs have been instrumented with Voicing. I also mixed Voicing into RichTextLinks so that links support voicing, which was needed for the links in these Dialogs.

@zepumph would you mind reviewing this common code change?

**Comment by zepumph** [comment]
Can you describe to me why it is better to have a different type VoicingRichText.js and VoicingText.js as apposed to adding this code directly into RichText/Text?

**Comment by jessegreenberg** [comment]
I structured it this way because we often do not want Text and RichText to have voicing. I think it is more often a combination of Text + UI component or Text + icon that requires voicing or a ReadingBlock. In the rarer cases where we have big chunks of Text that stand alone we have VoicingText and VoicingRichText.

**Comment by zepumph** [comment]
Sounds excellent. Thanks for taking care of this. All looks good to me.

**Comment by jessegreenberg** [comment]
OK, thanks!

**Comment by zepumph** [comment]
@jessegreenberg and I found 3 issues related to disposing a poolable Node that supports Voicing. Committed above. From this, @jessegreenberg was interested in taking one more look at this mixin-hierarchy in general to make sure that disposal/cleaning was complete and correct. Over to you.

Thanks @KatieWoe and @samreid for reporting.

**Comment by jessegreenberg** [comment]
I went through Voicing, InteractiveHighlighting, and ReadingBlock looking for cases like we saw in https://github.com/phetsims/scenery/commit/affb5d0adde4fa34cb51cff62f06e1bb88eff0cd that may be problematic if disposed because or used with Poolable. I didn't notice anything wrong and we haven't seen an issue like this on CT since November. I think this can be closed again.
