### ISSUE TITLE
What should readme buttons be on the home screen?

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#766]
I ran into this for RAP. @jessegreenberg, over to you in case this is not a new issue.

**Comment by jessegreenberg** [comment]
I believe this is new and we haven't considered the content for these for multi-screen sims. We should check in with the design team.

**Comment by zepumph** [comment]
Excellent. I will bring this up in next voicing design meeting.

Over to @terracoda for design

**Comment by terracoda** [comment]
@jessegreenberg and @zepumph, I did think about it. Ideas for the three buttons on the Home Screen are laid out in the design doc for Ratio and Proportion.

The content is all the same as what you find in the PDOM, but split up a bit differently.

**Comment by terracoda** [comment]
The Overview is the first part of the intro: 
- Play Overview: "Welcome to Ratio and Proportion. It has 2 interactive screens that you can explore. "

The Details come from combining the Screen button hints:
- Play Details: "On Discover Screen, Explore and discover set challenge ratios. On Create Screen, Set your own challenge ratios to explore."

The Hint is the last sentence of the intro:
- Play Hint: "Choose a screen to start exploring."

If there is a way to make those pieces separate strings that can be pulled out into the read-me buttons, that would be great!

**Comment by terracoda** [comment]
I think if we use the template we already use for the Home Screen, and then just break it up in a slightly different way for Voicing we will have the Read-Me buttons for the Home Screen done for all sims, once we have the screen button hints drafted :-)

**Comment by terracoda** [comment]
Here's a visua
<img width="503" alt="home-screen-template-for-voicing" src="https://user-images.githubusercontent.com/1902116/142500989-de24573b-a71d-429e-881b-1575fbcb3c51.png">
l

**Comment by zepumph** [comment]
Thanks, I'll implement

**Comment by zepumph** [comment]
@terracoda please review. 

The screen hints are capitalized in the middle of each details sentence, but I don't think we should try to fix that. It would be a large pain because we would need to duplicate each hint just for that one capitalization.

**Comment by terracoda** [comment]
The read-me buttons on the Home Screen sound great to me. Closing.
