### ISSUE TITLE
Abstract methods needed on ScreenView for voicing

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#767]
I think that we are past the point of obfuscated assertions like those in VoicingToolbarAlertManager.js. Can we instead just implement those methods directly on ScreenView that throw that assertion?

**Comment by jessegreenberg** [comment]
OK sounds good - What do you think of https://github.com/phetsims/joist/commit/2183bef208f23b867566b01b9681e7571a4c9cfe?

**Comment by zepumph** [comment]
Sounds excellent!
