### ISSUE TITLE
Pan-and-Zoom feature is not working with PhET "Creator" pattern.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#769]
[Creator](https://github.com/phetsims/phet-info/blob/master/doc/phet-software-design-patterns.md#creator-with-drag-forwarding) is a PhET design pattern used by toolboxes and buckets.  When something is dragged out of a toolbox or bucket, a new object is created, with a corresponding model and view.  As discovered in https://github.com/phetsims/equality-explorer/issues/179#issuecomment-971768652, if the simulation is zoomed in, then panning does not work while dragging the newly-created object.

In https://github.com/phetsims/equality-explorer/issues/179#issuecomment-970861763, @jessegreenberg confirmed that this is a general problem, and said:
> I would have expected it to keep the Node in view here. Pan and Zoom is not handling the creator pattern well, that is why it doesn't work when you pull out a term from the toolbar but does work for subsequent drags. It is not sim specific. ...

In https://github.com/phetsims/equality-explorer/issues/179#issuecomment-971768652, @KatieWoe also confirmed that this is a general problem, occuring in "a number of sims on master" and "is in phetsims/qa#736 as well".

Assigned to @jessegreenberg to investigate.  Please check with @kathy-phet and @amanda-phet for priority.

**Comment by pixelzoom** [comment]
From https://github.com/phetsims/equality-explorer/issues/179#issue-1055333825, this shows the buggy behavior:

![pandragobjects](https://user-images.githubusercontent.com/41024075/142065723-ed853357-e07f-434e-b89f-68c8cacf8688.gif)

**Comment by KatieWoe** [comment]
Noting in https://github.com/phetsims/qa/issues/748

**Comment by pixelzoom** [comment]
This will likely be a problem for geometric-optics, where we drag rulers out of a toolbox.

**Comment by Nancy-Salpepi** [comment]
When testing https://github.com/phetsims/qa/issues/771, I noticed that pan-and-zoom works when moving an object around the play area. However, if I were to remove an object from a grouping, it will not pan until I release it and grab it again. 

![panningNP](https://user-images.githubusercontent.com/87318828/151995647-a95c2dc2-2edb-4d67-bfbd-e43fc6ed1294.gif)

**Comment by jessegreenberg** [comment]
The overall approach to panning while dragging an object is pretty poor. I am going to reconsider it here first https://github.com/phetsims/scenery/issues/1356 before trying to get what we currently have with the "Creator" pattern.

**Comment by samreid** [comment]
@jessegreenberg can you please comment on the state of this issue now that https://github.com/phetsims/scenery/issues/1356 is closed?

**Comment by jessegreenberg** [comment]
I just confirmed that cases like https://github.com/phetsims/build-a-nucleus/issues/23 are not fixed so we still need to solve that. But hopefully it will be easier now that https://github.com/phetsims/scenery/issues/1356 is done.

**Comment by Luisav1** [comment]
Build a Nucleus is getting ready for publication, it'd be nice to take a look at this issue. @jessegreenberg, @zepumph and I would be happy to help.

**Comment by jessegreenberg** [comment]
Pan and zoom is working well with changes from https://github.com/phetsims/scenery/issues/1356 once the `targetNode` is set on the DragListener is set for the forwarded event. I will see if that is the case for CCK as well (https://github.com/phetsims/joist/issues/769#issuecomment-1072430805)
