### ISSUE TITLE
Incorrect import for joistVoicingUtteranceQueue

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#771]
While working on https://github.com/phetsims/chipper/issues/1177.

In PreferencesManager I currently see 

https://github.com/phetsims/joist/blob/b669e5be69887af0fc2f46f3aa40cb32fc88568c/js/preferences/PreferencesManager.js#L11

This seems like a bug. I'm going to fix and then see if @jessegreenberg agrees.

**Comment by zepumph** [comment]
Hows that?

**Comment by jessegreenberg** [comment]
Yes, thank you for fixing!
