### ISSUE TITLE
Review Voicing implementation for HomeScreen and NavBar

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#775]
I would like to go through the design doc for Ratio and Proportion and make sure joist is still up to date.

**Comment by terracoda** [comment]
The home screen and navbar are working fine for sim buttons. I am opening a new issue that outlines a design pattern for  Keyboard Shortcuts dialog and all content-heavy dialogs. I think we are already using this pattern in MAL's Light Spectrum Diagram dialog.
