### ISSUE TITLE
Ability to have voicing without adding a PreferencesConfiguration

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#780]
I ran into this over in https://github.com/phetsims/molarity/issues/243. After speaking with @jessegreenberg, it seems like an easy refactor can be done from PreferencesManager -> AudioManager to get this working. I'll commit shortly.

This does pretty much strip all the functionality from PreferencesManager, but it will be beefed back up over in #743.

**Comment by zepumph** [comment]
Pardon the bad commit message name.

**Comment by jessegreenberg** [comment]
Commit looks like what we discussed, thanks!
