### ISSUE TITLE
Splashscreen is covered up by sim if updateDisplay() is called

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#781]
I discovered this while working on https://github.com/phetsims/phet-io-wrappers/issues/430 (part of https://github.com/phetsims/phet-io/issues/1835). Basically calling `setState` from a wrapper before the splashScreen had been disposed would show the sim even though the main animation loop wasn't working.

@samreid and I tracked the issue down to Display.updateSize(), because while the splashScreen is loading, the sim's dimensions are actually -`[1,-1]`. A single call to updateDisplay sets the right size, and covers up the splashScreen before it is disposed. I propose an update to the splash screen that makes it always on top, via a z index. It also means that the black isn't the body's background color, but instead a new div that is created in the splash code.

**Comment by zepumph** [comment]
Ok, updates to the splashscreen committed above. @chrisklus can you please review this. I don't feel too confident about my css skills. Perhaps you can help me simplify this.

**Comment by zepumph** [comment]
This will need pretty extensive testing by QA to make sure it works well on all devices.

**Comment by zepumph** [comment]
@samreid mentioned that perhaps percentage may be different than view coordinates, and we should see about which is better, see https://stackoverflow.com/questions/18588835/allow-a-div-to-cover-the-whole-page-instead-of-the-area-within-the-container

**Comment by chrisklus** [comment]
The extra properties for transform origin look redundant now that we don't support IE, see https://developer.mozilla.org/en-US/docs/Web/CSS/transform-origin

Not tested, but I would expect that you could omit:

```js
splashBackground.style[ '-webkit-transform-origin' ] = '0 0';
splashBackground.style[ '-ms-transform-origin' ] = '0 0';
splashBackground.style[ 'transform-origin' ] = '0 0';
```

and get the same results with:

```js
splashBackground.style.transformOrigin = '0 0';
```

(using the same syntax as the rest of the styling)

Also not clear to me why that's needed at all, have you tested without it?

>@samreid mentioned that perhaps percentage may be different than view coordinates, and we should see about which is better

Since it's position `fixed` (no longer cares about any parent that the % size could be relative to), 100% width and height seems great (assuming we're trying to fill a whole screen). Everything else looks reasonable to me!

**Comment by zepumph** [comment]
Alrighty thanks for the review, I'll take a look.

**Comment by zepumph** [comment]
I tried out this patch, and it looked a bit off on edge, so I just gave up. I'll head over to QA to make an issue to test this now.

```diff
Index: js/splash.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/splash.js b/js/splash.js
--- a/js/splash.js	(revision f9a98554461d39fb811a105fa88a76d9ad10b6ae)
+++ b/js/splash.js	(date 1645741940274)
@@ -48,8 +48,6 @@
 
     // Position the div using CSS
     const transformString = `translate(${translationX}px, ${translationY}px) scale3d(${scale}, ${scale}, 1)`;
-    div.style[ '-webkit-transform' ] = transformString;
-    div.style[ '-ms-transform' ] = transformString;
     div.style.transform = transformString;
   }
 
@@ -62,9 +60,7 @@
   splashBackground.style.height = '100%';
   splashBackground.style.backgroundColor = 'black';
   splashBackground.style.zIndex = 10000;
-  splashBackground.style[ '-webkit-transform-origin' ] = '0 0';
-  splashBackground.style[ '-ms-transform-origin' ] = '0 0';
-  splashBackground.style[ 'transform-origin' ] = '0 0';
+  splashBackground.style.transformOrigin = '0 0';
 
   // Create the container div which will hold the splash image and progress bar
   const centerLogoAndProgress = document.createElement( 'div' );
@@ -72,9 +68,7 @@
   centerLogoAndProgress.style.position = 'fixed';
   centerLogoAndProgress.style.left = '0px';
   centerLogoAndProgress.style.top = '0px';
-  centerLogoAndProgress.style[ '-webkit-transform-origin' ] = '0 0';
-  centerLogoAndProgress.style[ '-ms-transform-origin' ] = '0 0';
-  centerLogoAndProgress.style[ 'transform-origin' ] = '0 0';
+  centerLogoAndProgress.style.transformOrigin = '0 0';
 
   // Create the splash image, which is an SVG logo
   const splashImage = document.createElement( 'img' );

**Comment by zepumph** [comment]
I created https://github.com/phetsims/qa/issues/778 for testing.

**Comment by zepumph** [comment]
Testing came back with only one potential bug. I asked a designer to determine if it is blocking, we will pick things up over there (https://github.com/phetsims/joist/issues/785). Closing

**Comment by samreid** [comment]
I added a div suffix to the divs.  Probably doesn't warrant call-out for review, but just tagging @zepumph so he is aware.
