### ISSUE TITLE
Preferences nav bar button is invisible (but clickable) on HomeScreen

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#788]
I think that Ratio and Proportion is the first multi-screen Voicing/Preferences sim, so it would make sense that there is some weirdness. I think it is because the icon is black.

Here is a nice example with Interactive Highlights on and the mouse over the icon:

![image](https://user-images.githubusercontent.com/6856943/156459346-fde7eb32-d6c6-4b2d-9f5f-b4df71c938a5.png)

**Comment by jessegreenberg** [comment]
Was incorrectly using `lookAndFeel.navigationBarTextFillProperty` so the button was invisible like the sim title in the nav bar on the home screen. Now fill is set based on the background color like other nav bar buttons.

@zepumph this has been fixed, can you please confirm?

**Comment by zepumph** [comment]
Looks great. Thanks!
