### ISSUE TITLE
Down arrow key should move focus into the selected Preferences tab

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/joist#791]
The last bit of work from https://github.com/phetsims/john-travoltage/issues/403, the down arrow should move focus into the selected Preferences tab. Currently the down arrow cycles through the tabs like left/right arrows.

**Comment by zepumph** [comment]
How does this look @jessegreenberg? I also factored out some code into getSelectedContent for use in both down and up cases.

**Comment by samreid** [comment]
@zepumph and I discussed this at today's PhET-iO meeting.  This is an important part of the upcoming milestone, @jessegreenberg can you please prioritize the review sometime soon?

**Comment by jessegreenberg** [comment]
Thanks for the ping. I reviewed https://github.com/phetsims/joist/commit/db5b61234a76808deb5bdde19daa412bad1f7009 and the implementation is understandable and refactoring was reasonable.

**Comment by zepumph** [comment]
Ok great. Closing
