### ISSUE TITLE
Remove vibrationManager from Sim

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/joist#793]
There are no plans in the next year or more to use Web based vibration. The only usage is in john-travoltage. We should remove it from both john-travoltage and Sim.js at this time. This came up as Sim.js is being converted to TypeScript. VibrationManager was only optionally included so that tappi didn't need to be a dependency for all sims, but strong typing would change that.

**Comment by jessegreenberg** [comment]
On hold until Sim TypeScript conversion is complete and changes can be made to Sim.ts.

**Comment by pixelzoom** [comment]
Duplicate of https://github.com/phetsims/joist/issues/794.
