### ISSUE TITLE
Port Sim.js to TypeScript

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#795]
I started on this, and ran into a whole bunch of places to add TODOs... Missing doc, use-before-definiton, etc.   TODOs require an associated GitHub issue, so this is it.

**Comment by zepumph** [comment]
Thanks for taking a first pass! Sounds, horrible.

**Comment by zepumph** [comment]
See https://github.com/phetsims/joist/issues/776#issuecomment-1097562908
by @samreid for the most recent conversion patch.

I will review this this week.

**Comment by samreid** [comment]
I pushed changes to joist centered around Sim.ts.  There were complications around Colors, some places expecting Color|string, some expecting just Color and some expecting just string.  There were expectations throughout joist that colors were `=== 'black'` or `=== 'white'` or `!==`, so I converted some files to *.ts to help catch errors in those areas.  It seemed best to promote LookAndFeel to use `Color`.

The quick start panel in CT (henceforth "CTQ") is green.  Local testing seems OK.  Dialogs show up in the right z-order.  Sim logic runs.  Keyboard help dialog appears.  Tab navigation works.  Type checking is passing.  Lint is passing.  Studio is working.

I'll mark this issue as blocks-publication in case anyone tries to publish something Monday.  This is scheduled for review Tuesday.

**Comment by samreid** [comment]
OK I think this is ready for review.  Please review Sim.ts and comments marked for `https://github.com/phetsims/joist/issues/795` at a minimum.  Thanks!

**Comment by zepumph** [comment]
I was able to get through the commits I saw in joist related to this work as well as the items marked with this issue number. Comments are inline. In general I think that about half of them will get better as we convert more to TypeScript. It would be nice to make the backgroundColorProperty more string or consistent. I think that usages should change to whatever we decide, which is likely to support both, but perhaps we would just want to support `Color`. Not sure.

I would love an IModel, but I don't know if it would be worth the effort to make it happen. Nor do I know the benefit beyond stronger typing in Sim.ts.

As for general typescript items, I think the main item is to reflect on if we like initializing values where they are declared when possible. In Sim.js I thought it was pretty cool, but it is a big and complicated file, and I saw a couple that I thought could be initialized where declared and weren't. I don't know how much we should care about consistency when I'm just using Ctrl + B to get to the declaration anyways, and I'm not hunting it down too much.

I'm happy to discuss further if desired, but things are looking really good. Thanks!

**Comment by samreid** [comment]
> // REVIEW: 1. How is this passing the type checker? IntentionalAny does not extend ScreenView.

`any` does not define a structure.  For instance, this code passes type checking:


```ts
let x: number = 7;
const y: any = 'hello';
x = y;
console.log( x );
```

The TypeScript handbook https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#any says: 

> The compiler effectively treats any as “please turn off type checking for this thing”. It is similar to putting an @ts-ignore comment around every usage of the variable.

**Comment by zepumph** [comment]
- [ ] I like unknown! But we call `model.step`. So that would need an ignore or something. I tried this patch and I got really close to liking it, but can you help me out with the one error I'm getting with `this.homeScreen === screen`.


<details>

```diff
Index: js/IModel.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/IModel.ts b/js/IModel.ts
new file mode 100644
--- /dev/null	(date 1650910310505)
+++ b/js/IModel.ts	(date 1650910310505)
@@ -0,0 +1,13 @@
+// Copyright 2022, University of Colorado Boulder
+
+/**
+ * Model interface as it pertains to joist's implementation.
+ * @author Michael Kauzmann (PhET Interactive Simulations)
+ */
+
+type IModel = {
+
+  step?: ( dt: number ) => void;
+}
+
+export default IModel;
\ No newline at end of file
Index: js/Sim.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/Sim.ts b/js/Sim.ts
--- a/js/Sim.ts	(revision f170b3c44238382daed60ac1b05d90c017f4bf6e)
+++ b/js/Sim.ts	(date 1650910310501)
@@ -5,7 +5,7 @@
  * Provides default initialization, such as polyfills as well.
  * If the simulation has only one screen, then there is no homescreen, home icon or screen icon in the navigation bar.
  *
- * The type for the contained Screen instances is Screen<any,any> since we do not want to parameterize Sim<[{M1,V1},{M2,V2}]
+ * The type for the contained Screen instances is Screen<IModel,ScreenView> since we do not want to parameterize Sim<[{M1,V1},{M2,V2}]
  * etc.
  *
  * @author Sam Reid (PhET Interactive Simulations)
@@ -67,6 +67,7 @@
 import ScreenView from './ScreenView.js';
 import Popupable from '../../sun/js/Popupable.js';
 import PickOptional from '../../phet-core/js/types/PickOptional.js';
+import IModel from './IModel.js';
 
 // constants
 const PROGRESS_BAR_WIDTH = 273;
@@ -160,14 +161,14 @@
 
   // the ordered list of sim-specific screens that appear in this runtime of the sim
   // REVIEW: 3. Is it time to create a Model supertype or a IModel interface that can be used for type safety here?
-  private readonly simScreens: Screen<any, ScreenView>[];
+  private readonly simScreens: Screen<IModel, ScreenView>[];
 
   // all screens that appear in the runtime of this sim, with the homeScreen first if it was created
-  private readonly screens: Screen<any, ScreenView>[];
+  private readonly screens: Screen<IModel, ScreenView>[];
 
   // the displayed name in the sim. This depends on what screens are shown this runtime (effected by query parameters).
   private readonly displayedSimNameProperty: IReadOnlyProperty<string>;
-  readonly screenProperty: Property<Screen<any, ScreenView>>;
+  readonly screenProperty: Property<Screen<IModel, ScreenView>>;
 
   // true if all possible screens are present (order-independent)
   private readonly allScreensCreated: boolean;
@@ -265,7 +266,7 @@
    * @param allSimScreens - the possible screens for the sim in order of declaration (does not include the home screen)
    * @param [providedOptions] - see below for options
    */
-  constructor( name: string, allSimScreens: Screen<any, ScreenView>[], providedOptions?: SimOptions ) {
+  constructor( name: string, allSimScreens: Screen<IModel, ScreenView>[], providedOptions?: SimOptions ) {
 
     window.phetSplashScreenDownloadComplete();
 
@@ -508,7 +509,7 @@
     this.screens = screenData.screens;
     this.allScreensCreated = screenData.allScreensCreated;
 
-    this.screenProperty = new Property<Screen<any, ScreenView>>( screenData.initialScreen, {
+    this.screenProperty = new Property<Screen<IModel, ScreenView>>( screenData.initialScreen, {
       tandem: Tandem.GENERAL_MODEL.createTandem( 'screenProperty' ),
       phetioFeatured: true,
       phetioDocumentation: 'Determines which screen is selected in the simulation',
@@ -699,7 +700,7 @@
     animationFrameTimer.runOnNextTick( () => phet.joist.display.updateDisplay() );
   }
 
-  private finishInit( screens: Screen<any, ScreenView>[] ): void {
+  private finishInit( screens: Screen<IModel, ScreenView>[] ): void {
 
     _.each( screens, screen => {
       screen.view.layerSplit = true;


```
</details>


- [ ] We could (a) separately manage an array of Node with layout, or run type assertions on them when we read them out of topLayer.children.

I don't really understand this, is it required that nodes in the topLayer have a layout function? because I didn't think it did, if so, that seems like a reasonable path.


>That sounds reasonable to me, unless there is an ordering dependency (hopefully there isn't).

Good luck!


I reviewed everything else. Thanks!

**Comment by zepumph** [comment]
Oops, I didn't assign back. Sorry.

**Comment by samreid** [comment]
> but can you help me out with the one error I'm getting with this.homeScreen === screen.

That is because the HomeScreenModel has no step function.  I think it would be very safe to add.  I also tried changing Screen's declaration to `class Screen<M extends IModel, V extends ScreenView> extends PhetioObject {` but that led to a lot of contravariance problems like so:

```
/Users/samreid/apache-document-root/main/number-play/js/number-play-main.ts(61,5): error TS2322: Type 'NumberPlayGameScreen' is not assignable to type 'Screen<IModel, ScreenView>'.
  Types of property 'createView' are incompatible.
    Type '(model: NumberPlayGameModel) => NumberPlayGameScreenView' is not assignable to type '(model: IModel) => ScreenView'.
      Types of parameters 'model' and 'model' are incompatible.
        Type 'IModel' is missing the following properties from type 'NumberPlayGameModel': subitizeLevels, countingLevels, levels, levelProperty, reset
```

How do you want to proceed on this part?

> , is it required that nodes in the topLayer have a layout function? 

It's optional at the moment, like so:

```ts
      this.topLayer.children.forEach( child => {

        // @ts-ignore TODO: See https://github.com/phetsims/joist/issues/795
        // REVIEW: I'm really not sure how to handle this one, let's talk about it.
        child.layout && child.layout( availableScreenBounds );
      } );
```

**Comment by samreid** [comment]
Good fix, thanks!  Let's go on hold until #783 is complete.

**Comment by samreid** [comment]
In #783 we decided to stick with 

```ts
type TModel = {
  step: ( dt: number ) => void;
};
```

and 

```ts
// Parameterized on M=Model and V=View
// The IntentionalAny in the model type is due to https://github.com/phetsims/joist/issues/783#issuecomment-1231017213
class Screen<M extends TModel = IntentionalAny, V extends ScreenView = ScreenView> extends PhetioObject {
```

Regarding the patch in https://github.com/phetsims/joist/issues/795#issuecomment-1212271314, I didn't fully understand it, but since `Sim` doesn't have a `scale` to pass, perhaps it should remain omitted?

Back to @zepumph for discussion/review.  I'm OK to close if you agree.

**Comment by zepumph** [comment]
I didn't make too much sense. Let me re-explain:

https://github.com/phetsims/joist/commit/d70808369e8e57ed763fecfdd2bf25ae0ce74c1d is the recommended fix for a ts-ignore

It works so-so in my opinion, but is probably good enough. Note the type error when you apply this patch:

```diff
Index: js/Popupable.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/Popupable.ts b/js/Popupable.ts
--- a/js/Popupable.ts	(revision 1677fc56a62a51a3fe7a28b58c44f9123c7b990d)
+++ b/js/Popupable.ts	(date 1660238463778)
@@ -123,7 +123,7 @@
       } );
     }
 
-    public layout( bounds: Bounds2 ): void {
+    public layout( scale: number, bounds: Bounds2 ): void {
       if ( this.layoutBounds ) {
         this.popupParent.matrix = ScreenView.getLayoutMatrix( this.layoutBounds, bounds );
       }
```

>TS2322: Type '(scale: number, bounds: Bounds2) => void' is not assignable to type '(bounds: Bounds2) => void'.

So if you try to add the wrong type signature for the layout method to the top layer, we fail. Will you take a final review of that commit and let me know if you recommend anything further? Please feel free to close.

**Comment by samreid** [comment]
Yes, that matches my understanding and I reproduced that type error by changing that layout method.  I think we are in good shape to close.
