### ISSUE TITLE
UpdaTESTate?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#797]
In joist/tsconfig-module.json:

```
    "js/**/*tests.js", // Cannot use **test** like we do elsewhere because of UpdaTESTate
    "js/**/*Tests.js", // Cannot use **test** like we do elsewhere because of UpdaTESTate
```

Just curious... Is "UpdaTESTate" a thing, or a dupicated typo?

**Comment by samreid** [comment]
There is a file called UpdateState.js which has a hidden word "test" in it.

**Comment by pixelzoom** [comment]
Never would have understood that in a million years.
