### ISSUE TITLE
Navbar blends in to other things for browsers that have no border

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#80]
In #78 @pixelzoom pointed out that:

This is also an issue when you happen to have black (or very dark) wallpaper on your desktop and the browser has no chrome along the bottom edge. This is what I've been living with on Mac OS with Chrome and Firefox (Safari has bottom-edge chrome.)

Btw... My wallpaper is not totally black, but it does fade to black along the screen edges. Examples below, showing my wallpaper and how things look with Canary.

![desktop](https://f.cloud.github.com/assets/679486/1470672/5831ab78-45c3-11e3-89b2-44fe64827899.jpg)

![desktop-browser](https://f.cloud.github.com/assets/679486/1470673/5b1caf54-45c3-11e3-96b6-0069ab67c3ea.jpg)

This could also be a problem on Android platforms that have onscreen (instead of hardware) buttons, such as the Nexus 7.

**Comment by ariel-phet** [comment]
This issue seems stale and has not affected any usage in 3 years, closing
