### ISSUE TITLE
Add the missing sounds for the Preferences dialog

### ISSUE THREAD

**Issue by jbphet** [phetsims/joist#803]
As of this writing, the Preferences Dialog makes sounds for some actions, such as opening and closing it and checking a checkbox, but it does _not_ make sounds for some other things, such as togging the AB switches or selecting a different tab.  This was discussed in today's sound design meeting, and we are going to add the needed sounds.

For now, we think all that is needed are sounds for the AB switch and the tab switching.  We are thinking that the former should be somewhat similar to the checkbox sound, and the latter should be similar (but not too similar) to the screen selection sound.

Assigning to @Ashton-Morris to create first cuts of these sounds, after which I will integrate them.

**Comment by Ashton-Morris** [comment]
[I am adding these files for review and implementation. ](https://drive.google.com/drive/folders/1YHLFqMsM_lXnnTT_Ec-yGK86mTqgX9Ec?usp=sharing)

- preferences-ab-switch-b.mp3
- preferences-ab-switch-a.mp3
- preferences-tab-switching.mp3
- preferences-tab-switching-003.mp3
- preferences-tab-switching-002.mp3
- preferences-tab-switching-001.mp3

**Comment by jbphet** [comment]
For reference, [here](https://phet-dev.colorado.edu/html/john-travoltage/1.6.4/phet/john-travoltage_en_phet.html) is a version of the John Travoltage sim that includes the preferences dialog that has partial sound.  To experience it, start the sim and go to the preferences dialog and interact with the various controls.  You'll see that things like checkboxes and radio buttons make sounds, while AB switches and the tabs do not.

**Comment by jbphet** [comment]
The sounds will need to be renamed to match the recently revised naming standards.  @Ashton-Morris - please make a note for your tracking that `preferences-ab-switch-a` was renamed to `switchToA` (and similar for the B sound).

**Comment by jbphet** [comment]
Note to self (@jbphet):
- [ ] Get the .wav files for these assets once they are finalized.

**Comment by pixelzoom** [comment]
Looks like @jbphet forgot to add & push the modulified versions of the sounds that he added in https://github.com/phetsims/tambo/commit/382620e4ce6996491b6b24fead907762fd081d51.  I added them in the above commit, please check.

**Comment by jbphet** [comment]
@arouinfar - This is implemented and was reviewed and refined by the sound design team.  I'm not sure if we want or need any additional sign-off, so I thought I'd assign it so you to decide if we do and, if so, to perhaps set up a slot at an upcoming design meeting.  Alternatively, feel free to close if you're comfortable with what we've done.  The best place to experience it is probably in the Preferences dialog in John Travoltage.

**Comment by arouinfar** [comment]
@jbphet thanks for the chance to review the sounds, and sorry for the delay. In general, I am fine with deferring to the sound design team for any decisions around common UI sounds. However, if there's a case where there's some debate or if the team would like additional input from designers, I'd be happy to review.

That said, I reviewed John Travoltage in master and the tab and toggle sounds in the Preferences dialog sound good to me, closing.
