### ISSUE TITLE
simControls should be more like OptionsDialog content

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#809]
A couple of problems here.

1. simOptions cannot be a function, it should be possible to create it lazily and provide it a tandem after the fact. This will work better with PhET-iO, in which the PreferencesDialog can be disposed and re-created.
2. I get an assertion in PhET-iO right now because two PreferencesDialogs are created which means the same contentNode is used in two different align groups. Basically wrapping this: https://github.com/phetsims/joist/blob/418f7cdc0cca1ddc52d4e0202bafb735068b0cfe/js/preferences/PreferencesPanelSection.js#L46. That is likely just the bandaid for now, But I'm hitting as assertion in PhET-iO brand.

**Comment by zepumph** [comment]
Tagging @jessegreenberg as the author of Preferences. I'll investigate a bit more and will likely ask you some questions.

**Comment by zepumph** [comment]
Ok, now I can open the preferences dialog in PhET-iO brand.

**Comment by zepumph** [comment]
I discussed with @jessegreenberg and we like turning this into a function and passing it a tandem.

**Comment by zepumph** [comment]
Something like this:

```diff
Index: js/preferences/GeneralPreferencesPanel.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/preferences/GeneralPreferencesPanel.js b/js/preferences/GeneralPreferencesPanel.js
--- a/js/preferences/GeneralPreferencesPanel.js	(revision 09e308898901a1ef41751edd417592f0b93b2389)
+++ b/js/preferences/GeneralPreferencesPanel.js	(date 1652465183425)
@@ -43,7 +43,9 @@
     super( options );
 
     const panelChildren = [];
-    generalModel.simControls && panelChildren.push( new SimControlsPanelSection( generalModel.simControls ) );
+
+    const x = generalModel.createSimControls( options.tandem.createTandem( 'simControls' ) );
+    generalModel.simControls && panelChildren.push( new SimControlsPanelSection( x ) );
 
     const introParagraphs = new VBox( { spacing: 10, align: 'left' } );
     const introTextOptions = merge( {}, PreferencesDialog.PANEL_SECTION_CONTENT_OPTIONS, {
@@ -65,6 +67,9 @@
 
     this.children = panelChildren;
   }
+  dispose(){
+    x.dispose();
+  }
 }
 
 joist.register( 'GeneralPreferencesPanel', GeneralPreferencesPanel );

**Comment by jessegreenberg** [comment]
I took a stab at this in the above commits for what was needed in https://github.com/phetsims/joist/issues/814. @zepumph helped me identify that tandems need to be passed through these functions so that a unique tandem can be used in the subcomponents that are created.

However I have a low confidence that things are working for PhET-iO. I was never able to get energy-skate-park running in the state wrapper from my changes in that issue and I will have to return to that.

**Comment by zepumph** [comment]
Ok, I haven't reviewed yet, but I fixed RAP in two ways, now I presume that the preferences dialog would work in the state wrapper, but can't test it without getting this (unrelated?) error:

```
Uncaught Error: Assertion failed: alignBounds should be a non-empty finite Bounds2
    at window.assertions.assertFunction (assert.js:28:13)
    at AlignBox.setAlignBounds (AlignBox.ts:207:15)
    at set alignBounds [as alignBounds] (AlignBox.ts:226:51)
    at AlignGroup.setBoxBounds (AlignGroup.ts:285:5)
    at AlignGroup.updateLayout (AlignGroup.ts:248:14)
    at AlignGroup.onAlignBoxResized (AlignGroup.ts:294:10)
    at AlignBox.invalidateAlignment (AlignBox.ts:190:19)
    at TinyStaticProperty.emit (TinyEmitter.ts:94:9)
    at TinyStaticProperty.notifyListeners (TinyStaticProperty.ts:58:10)
    at Node.validateBounds (Node.ts:1487:31)
```

**Comment by jessegreenberg** [comment]
I am seeing this too, I am guessing that there is an AlignBox somewhere in Preferences content that is not getting disposed for phet-io use cases. Ill take a look.

**Comment by jessegreenberg** [comment]
The above commits added missing disposals I found necessary to get Preferences working in the state wrapper for quadrilateral, balloons-and-static-electricity, ratio-and-proportion, energy-skate-park, and friction.

**Comment by jessegreenberg** [comment]
This issue wasn't for simOptions but specifically simControls of PreferencesConfiguration, I updated the title accordingly.

@zepumph can you please comment on what the next steps for this issue are?

**Comment by zepumph** [comment]
I wonder if @jonathanolson can comment on https://github.com/phetsims/joist/commit/c02d01cd8d7c7c0c130128a51bcda2fdda5e928b. Do we need this to guard against this assertion? Is it required? Is this the optimal solution? @jonathanolson the way to reproduce this issue is to move the align stuff after the Node disposal and then open the preferences dialog in the state wrapper (ratio-and-proportion/energy-skate-park/quad/likely-others).

**Comment by zepumph** [comment]
Everything else looks really good.

**Comment by zepumph** [comment]
Sorry, for the confusion, I actually can get this to easily reproduce with this patch. Open the state wrapper, open the preferences dialog, let it set state twice.

```diff
Index: js/preferences/GeneralPreferencesPanel.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/preferences/GeneralPreferencesPanel.js b/js/preferences/GeneralPreferencesPanel.js
--- a/js/preferences/GeneralPreferencesPanel.js	(revision c02d01cd8d7c7c0c130128a51bcda2fdda5e928b)
+++ b/js/preferences/GeneralPreferencesPanel.js	(date 1656449085541)
@@ -101,7 +101,7 @@
 
       // The AlignGroups used for layout need to be disposed before the content of their AlignBoxes (controls below)
       // or else bounds become undefined
-      simControlsPanelSection && simControlsPanelSection.dispose();
+      // simControlsPanelSection && simControlsPanelSection.dispose();
       localizationControlsPanelSection && localizationControlsPanelSection.dispose();
 
       simControls && simControls.dispose();
```

**Comment by jonathanolson** [comment]
Disposing a layout container can trigger it to "unset" a preferred size on its content. This was triggering an AlignGroup update to try to update an AlignBox with a content node that was empty. I've added a better default for this temporary case.

**Comment by zepumph** [comment]
Awesome! Thanks so much. @jessegreenberg, I would recommend removing comments and logic that until 6 minutes ago had an disposal order dependency. Otherwise you are free to close.

As a side note, I see that GeneratePreferencesPanel is now responsible for creating and disposing the simControls. Great!

**Comment by jessegreenberg** [comment]
Very cool. I reverted https://github.com/phetsims/joist/commit/c02d01cd8d7c7c0c130128a51bcda2fdda5e928b, verified that it failed locally. Then pulled https://github.com/phetsims/scenery/commit/b773e2aecdb622f9a040352d3f9ec6576eb81aef and saw things working.  I pushed the revert.

I think from https://github.com/phetsims/joist/issues/809#issuecomment-1169291018 that was all for this one, closing.
