### ISSUE TITLE
TypeScript issues in ScreenView

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#810]
As part of https://github.com/phetsims/joist/issues/776, ScreenView was converted to TypeScript by @samreid. 

Remaining issues:
- [ ] methods annotated as `@abstract` should be changed to use `abstract` keyword
- [x] `merge` should be replaced with `optionize` or `combineOptions`
- [x] `options?: any` should be typed
- [x] redundant `@returns` annotations should be removed

**Comment by samreid** [comment]
I tried converting the abstract annotations to abstract methods in this patch:

<details>

```diff

Index: js/ScreenView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/ScreenView.ts b/js/ScreenView.ts
--- a/js/ScreenView.ts	(revision b483f0a33c6c3339e77b2d1dc7135c2d021255be)
+++ b/js/ScreenView.ts	(date 1653329253604)
@@ -47,7 +47,7 @@
 };
 export type ScreenViewOptions = ScreenViewSelfOptions & NodeOptions & PickRequired<NodeOptions, 'tandem'>;
 
-class ScreenView extends Node {
+abstract class ScreenView extends Node {
   readonly layoutBounds: Bounds2;
   readonly visibleBoundsProperty: Property<Bounds2>; // Clients should not set this value
   private readonly pdomTitleNode: Node;
@@ -229,28 +229,19 @@
   /**
    * Create the alert content for this ScreenView when the Voicing feature is enabled and the "Overview" button
    * is pressed.
-   * @abstract
    */
-  getVoicingOverviewContent(): string {
-    throw new Error( 'The ScreenView should implement getVoicingOverviewContent if Voicing is enabled' );
-  }
+  abstract getVoicingOverviewContent(): string;
 
   /**
    * Create the alert content for this ScreenView when the Voicing feature is enabled and the "Details" button is
    * pressed.
-   * @abstract
    */
-  getVoicingDetailsContent(): string {
-    throw new Error( 'The ScreenView should implement getVoicingDetailsContent when the Voicing feature is enabled.' );
-  }
+  abstract getVoicingDetailsContent(): string;
 
   /**
    * Create the alert content for this ScreenView when the Voicing feature is enabled and the "Hint" button is pressed.
-   * @abstract
    */
-  getVoicingHintContent(): string {
-    throw new Error( 'The ScreenView should implement getVoicingHintContent when Voicing is enabled.' );
-  }
+  abstract getVoicingHintContent(): string;
 
   /**
    * Get the scale to use for laying out the sim components and the navigation bar, so its size will track

```

</details>

But it had 170+ type errors from ScreenView subtypes not implementing those abstract methods.  @jessegreenberg can you please comment on this part?

**Comment by zepumph** [comment]
This is a bit tricky, they are abstract for the purpose of any ScreenView implementing the voicing feature, but it will only be called from the voicing toolbar. I feel like the best path forward would be to change the doc from `@abstract` to `must be overridden if supporting voicing. The runtime error there seems best. I don't really want to split up ScreenView into VoicingScreenView or something, that is actually abstract.

**Comment by zepumph** [comment]
Merge and any have already been taken care of. @jessegreenberg please review and feel free to close.

**Comment by jessegreenberg** [comment]
I appreciate https://github.com/phetsims/joist/commit/d54b75d3728ad87341292ae89adc8343f67e177c, thank you! Closing.
