### ISSUE TITLE
"Synchronize Recording" button in Preferences menu needs accessible name?

### ISSUE THREAD

**Issue by terracoda** [phetsims/joist#812]
Just a heads up, I am not exactly sure how the "Synchronize Recording" button will be used by researchers or participants in upcoming research studies, but it currently does not have an accessible name. As a result it is not identifiable with a screen reader or with Voicing enabled.

Assuming this button is in common code, can we just fix it there, and push it to both Quad and RaP?

I think the button should have an accessible name in case we want a blind participant to activate it at the start of data collection, but I defer to @BLFiedler.

![image](https://user-images.githubusercontent.com/1902116/171651447-099ed07c-4bff-4b6a-abea-d9213538cb84.png)

**Comment by jessegreenberg** [comment]
I added an accessible name for the PDOM and a name response for voicing just in case. Let us know if other accessibility for this button would be helpful for interviews.

**Comment by terracoda** [comment]
That’s it thanks.
