### ISSUE TITLE
Focus and Voicing pattern for Keyboard Shortcuts dialog button (and other content-heavy dialogs)

### ISSUE THREAD

**Issue by terracoda** [phetsims/joist#815]
I have the initial documentation for dialog buttons in the design doc for the Preferences Menu.

Here https://docs.google.com/document/d/1Qu3U8IsFYn486oJUzQ71BXs_lBKZTVS5NVdLJlTK7gw/edit#heading=h.lmnes5fzhqwj

This issue is follow up to #775

I think we are already using this pattern in MAL's Light Spectrum Diagram dialog, the pattern being:
- moving the Close button tot he end of the dialog in the PDOM
- placing focus on the H1 of the dialog when the dialog is opened to prepare the learner for efficient reading the dialog's content.

**Comment by terracoda** [comment]
@zepumph and I discussed the documentation of the above pattern, and decided on a new path, that uses a custom voicing name response for the dialog's close button.

I have updates the documentation here in the Preferences Dialog Design document, just go to [Voicing Dialogs](https://docs.google.com/document/d/1Qu3U8IsFYn486oJUzQ71BXs_lBKZTVS5NVdLJlTK7gw/edit#heading=h.lmnes5fzhqwj) section

**Comment by zepumph** [comment]
OK. @jessegreenberg and I were able to get this to a good state. 

https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-dev.16/phet/ratio-and-proportion_all_phet.html?

Can you please review with this dev version and see if this aligns with the design doc?

**Comment by terracoda** [comment]
Two periods seems too hacky, so if one period doesn't work, let's stick with the comma.

**Comment by terracoda** [comment]
Let me know when the period is in place :-)

**Comment by terracoda** [comment]
We can try 2 periods, "{{dialogName}}. Close."
I have read that alt text should end in a period, maybe that is a good strategy for some button labels as well - especially action-oriented ones.

We'll just see what works.

**Comment by zepumph** [comment]
@terracoda and I decided that a comma and then a period at the end worked best. We didn't hear any change with TS's voice: "Alex" though. That is fine though! We are ready to close.
