### ISSUE TITLE
Splash screen "Loading..." text should be internationalized

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#82]
Splash screen "Loading..." text should be internationalized.  In the future, we may replace it with an animation, but for now it is in text.  I don't think our normal translation procedure will work here if the splash screen is shown before requirejs loads.  (I could be wrong about that, or we could split into two requirejs load phases).  Here is the Norwegian "nb" translation for Loading...:
"Loading..." -> "Laster..."

**Comment by ariel-phet** [comment]
It appears that https://github.com/phetsims/joist/issues/348 will be a successful strategy for showing a progress bar, so we will eventually remove any text that says "Loading" since a progress bar will give an iconic representation of that text. Closing
