### ISSUE TITLE
Convert SimInfo to typescript

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#820]
From https://github.com/phetsims/phet-io-wrappers/issues/435, there is a SimInfoType in PHET_IO_WRAPPERS/Client.ts that wants to instead be in SimInfo. Marking as high priority.

**Comment by zepumph** [comment]
All went well here. And we have a SimInfoState type now to use generally. The one spot worth double checking on is the `@ts-ignore` in SimInfo. I couldn't figure out how to provide the right type for the value of each element. @samreid, will you please take a look?

**Comment by samreid** [comment]
With the current implementation strategy, the `any` and `ts-ignore` seem reasonable.  The next level would be to eliminate `info` completely and use type-specific elements like so:

```diff
Index: js/SimInfo.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/SimInfo.ts b/js/SimInfo.ts
--- a/js/SimInfo.ts	(revision 5dab4fbc742d6ba46200a535300b65b81d368bce)
+++ b/js/SimInfo.ts	(date 1659569959057)
@@ -52,7 +52,9 @@
 };
 
 class SimInfo extends PhetioObject {
-  public readonly info: SimInfoState = {} as SimInfoState;
+  public readonly url = window.location.href;
+  public readonly language = window.navigator.language;
+  // etc
 
   public constructor( sim: Sim ) {
     super( {

```

However, that is a lot of work and what we have is working nicely.  OK to close?
