### ISSUE TITLE
Remove tandem constructor param from several joist classes.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#823]
Noticed during cleanup for "TypeScript sprint"...

There are a number of places in joist where `tandem` is not passed via options, which is the typical PhET pattern. Instead, a constructor parameter was added. And that's unfortunate, becaue `tandem` is typically included in (not omitted from) the options type for the class. 

In fb48dd0e773a01ccbe686e4cd0671091a7eab331, @samreid added a `tandem` parameter to JoistButton constructor.  `tandem` is also included in `JoistButtonOptions`, and only fails out at runtime if you provide both:

```typescript
 public constructor( content: Node, navigationBarFillProperty: IReadOnlyProperty<Color>, tandem: Tandem, providedOptions: JoistButtonOptions ) {
```

... and the same pattern is used in a few JoistButton subclasses.

In PhetMenu:
```typescript
  public constructor( sim: Sim, tandem: Tandem, providedOptions?: PhetMenuOptions ) {
```

In HomeScreenView:

```typescript
  public constructor( simNameProperty: IReadOnlyProperty<string>, model: HomeScreenModel, tandem: Tandem, providedOptions?: HomeScreenViewOptions ) {
```

So I think it would be preferrable to move `tandem` back to options, to be consistent, and to take advantage of options type-checking. Here are the joist classes to modify:

- [x] JoistButton
- [x] HomeButton
- [x] KeyboardHelpButton
- [x] NavigationBarAudioToggleButton
- [x] NavigationBarPreferencesButton
- [x] PhetMenu
- [x] HomeScreenView

@samreid do you agree? I'll be happy to handle this.

**Comment by pixelzoom** [comment]
I don't have a lot to do for the TypeScript sprint, so I'll start on this. If I run into trouble, I might toss it back to @samreid.

**Comment by pixelzoom** [comment]
Addressed in the above commits. @samreid would you like to take a peek?

**Comment by samreid** [comment]
All commits for this issue are good improvements, thanks!  Looks good to close.
