### ISSUE TITLE
`?screens` should not change the PhET-iO API

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#826]
Over in https://github.com/phetsims/studio/issues/268#issuecomment-1198714103 and https://github.com/phetsims/phet-io/issues/1699 there was a large conversation about how Query Parameters can effect PhET-iO, most specifically as it pertains to the studio customization -> standard phet-io wrapper stack. Here are some gross things about the screens query parameter when making standard phet-io wrappers:

1. Load studio with no query parameters, then add `?screens=1` to the standard wrapper. This will hard fail and not set state.
2. Load studio with `?screens=1`, then add `?screens=1,2` to the standard wrapper. This will currently fail in the "load" function because it compares what screens were used when customizing vs running.

@kathy-phet had the idea to update how ?screens works in the project so that it will always create all sim screens, but only display the currently "available" or "selected" or "visible" screens. This could be controlled by a PhET-iO instrumented Property. 

Needed for this work:

* selectScreens() and associated query parameter logic would need to be updated to always create everything
* We need to decide that this is an acceptable performance hit (since before ?screens=1 was a faster startup time).
* We need all of HomeScreen and NavigationBar to support dynamic layout so that changing the visible screens is something that can be done dynamically. 

Marking as an epic amount of work. yay!

**Comment by kathy-phet** [comment]
I'm closing this issue because after further thinking we realized that: 
1) Using ?screens= in conjuction with the Standard PhET-iO Wrapper would not work because the state is set after the query parameters are initiated. Only ?locale= works after a wrapper is created in Studio. 
2) We will pursue an easier improvement in Studio to support API clients to show just one screen 
Closing.
