### ISSUE TITLE
Non translatable text in soon-to-be-published sim

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#829]
From https://github.com/phetsims/joist/issues/772 and https://github.com/phetsims/joist/issues/694:

I believe most recently this is being worked on in https://github.com/phetsims/joist/issues/814.

https://github.com/phetsims/joist/blob/e34f1194e9b89d123a9e3b43604adefaf0ad2d48/js/preferences/SimControlsPanelSection.ts#L13-L16

@jessegreenberg can we tighten this down for our soon-to-be-released RAP with sim preferences?

**Comment by jessegreenberg** [comment]
If it will be used in friction then it can be moved back into joist strings. It was just confusing for translators to find it in the translation utility when it wasn't used in any sim yet.

Is there content under this section in friction?

**Comment by arouinfar** [comment]
In the 8/11/22 design meeting, we decided to remove the "Simulations-specific Settings" title from the General tab, see https://github.com/phetsims/joist/commit/8f36fdff2e254bfdfe4de5348ca97da4a5480d50.

@zepumph you can likely close this issue.
