### ISSUE TITLE
Review ?allowLinks=false query parameter

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/joist#831]
I looked into the `?allowLinks=false` query parameter because we received a request for disabling various PhET menu items from a user deploying sims in a kiosk fashion:

> We’re attempting to keep the users from not being able to exit the sim. We run the sim on a PC with a touchscreen and no mouse/keyboard (or onscreen keyboard) in Chrome in kiosk mode (“-kiosk”) and the computers are not connected to the internet so if the user selects “PHET Website” or “Report a Problem” it will replace the current screen with the “No internet” screen shown below and they are stuck there. The PC is on a table in our “Exploration Center” with other PCs and each table has kind of a theme so we only run one particular sim on each PC.
>  
> If we initially set it up in Full Screen Mode using the Chrome Menu command or the PHET menu “Full Screen Mode”, the user can then turn off the Full Screen Mode using the PHET menu selection by selecting “Full Screen Mode” again and then the Chrome menu bar would be visible and they could touch on the “X” in the upper right to close Chrome and modify the desktop etc. which we don’t want.
>  
> I think all the sims we use have the Options Menu, we’re using the following list now and may add more.

It sounds like the level of customization they want is best served by PhET-iO.

However, I still think it would be good to reevaluate the `?allowLinks=false` qp. From what I can tell, it disables the links to the Licensing Terms, Translation Credits, and Third-Party Credits in the About... menu, but does _not_ disable Report a Problem..., Check for Updates..., or PhET Website... . 

I'd advocate for removing or disabling all of these links/menu items with this query parameter.

**Comment by oliver-phet** [comment]
I suppose I'll add this to Dev meeting to be evaluated/prioritized?

**Comment by kathy-phet** [comment]
Hey Oliver, I made an issue about the same time as you did. JO found a potential fix he commited. So we will continue this discussion in that other issue: 
https://github.com/phetsims/joist/issues/830
