### ISSUE TITLE
Change Preferences icon when Localization tab is present

### ISSUE THREAD

**Issue by arouinfar** [phetsims/joist#833]
In https://github.com/phetsims/chipper/issues/1302 we are adding the support to switch the locale while running the simulation. The controls for this will live in the Localization tab of the Preferences Dialog, #814. The changes to support in-sim locale switching are too complex to maintenance release, so it will take quite a bit of time to support this feature in all sims. 

We want a way to visually indicate to users that the simulation supports locale switching (or localization, more broadly). The Preferences logo on its own is not enough to indicate this, since sims may have a Preferences dialog without supporting Localization settings. We are considering swapping out the Preferences icon when the Localization tab is present. We would like to incorporate the globe icon, as it is often used to indicate localization.

Here are some mockups we discussed during today's design meeting, and the order is arbitrary.
<img width="355" alt="image" src="https://user-images.githubusercontent.com/8419308/185489133-eac733c4-7893-4fe0-bd81-4e7a98429a2f.png">

Some things we discussed:
* The Localization Preferences will eventually include more than just language, such as creating region-specific character sets (skaters in ESP) or other contexts (sandwiches in RPAL).
* The speech bubble in (1) and (2) could imply that Localization is just about language, or it may falsely indicate that Voicing/Description are translatable.
* (3) implies the preferences are only about Localization.
* (5) is a bit too wide and covering both shoulders makes the icon look less like a person.

It would be great to hear some feedback from @amanda-phet and @terracoda to see if they have any concerns about this proposal or suggestions for the icon. Also tagging other design-minded folks in case they have any feedback @BLFiedler @DianaTavares @catherinecarter @matthew-blackman @emily-phet.

**Comment by emily-phet** [comment]
I wasn't part of the discussion on this, but wanted to share a thought on it.
We're providing a way to sort sims by what features they have through the website filtering page. That's how we're cueing folks to search for what kinds of key features are in a particular sim. I wonder if that's sufficient to support users in being aware of what sims have localization features - can we add the ability to filter on localization in the access and inclusion filter?

**Comment by arouinfar** [comment]
Thanks @emily-phet. I really like this idea! 

@kathy-phet could we achieve your goals using a website filter?

**Comment by amanda-phet** [comment]
I am wondering why the icon should be modified in this case. It seems confusing to me to cue a particular setting that exists, when we don't do that for other settings in the preferences dialog. 

Would it be present any time the localization tab exists? Or is this truly only for the case where you can switch locale in the sim? 

Lastly, I think that cueing this in the settings icon could imply that other sims don't have translations if they don't have this globe icon, and that's not the case. It is just a different way of accessing them. 

I think a website filter makes a ton of sense, and we can make an icon on the sim tile similar to the other inclusive icons that uses the globe imagery.

**Comment by kathy-phet** [comment]
Some of the thoughts I had for elevating/cuing language switching directly in a simulation were around the context in which many many students now use PhET sims. 

I think adding a website filter is nice, but it won't address what I was hoping to address with the icon cue. 

That is, the vast minority of users will be navigating to a simulation via the website filter or something like that. These days many many users have embedded sims or direct links via teachers or partner products, and never navigate our website. 

By including a cue that the sim language changeable in the simulation, teachers and users can quickly learn if that capability is available in that particular sim - and know to look there for that capability.

**Comment by amanda-phet** [comment]
I guess the question is just whether locale switching is a top priority to cue in the navbar, when we have a lot of wonderful things available in the preferences menu that aren't explicitly cued.

**Comment by BLFiedler** [comment]
I'm don't think I'm advocating this option so much as tossing it in the mix _and_ it goes against the existence of the Preferences menu, but if Localization does feel unique amongst the other Preferences menu options for one reason or the other, might it be worth its own icon/menu altogether?

Relevant to the original post, I like icon 4 the most.

**Comment by kathy-phet** [comment]
One quick question is whether by adding a globe, it will increase the likelihood of people clicking and discoverying all the wonderful options we have. We know that discovery and knowledge of translations is something that is definitely an issue. It could definitely be a discovery issue for all of our wonderful options. If a globe encourages clicking, perhaps that is a good thing. (Interviews could help us see.)

There are a lot of considerations for discussion around this topic long term. E.g. the trade off of file size and localized strings. 

(But I have to get back to course prep.)

**Comment by emily-phet** [comment]
Adding a special designation to the preferences menu icon privileges that feature over others. There may be good reasons to do so, but I think it would be helpful to specifically document what those reasons are.

**Comment by arouinfar** [comment]
> These days many many users have embedded sims or direct links via teachers or partner products, and never navigate our website.

If teachers are accessing the sim through a bookmarked/embedded sim, it's highly unlikely to be the _all file since we don't serve it directly on the website. For teachers to get access to locale-switching, they are going to need to revisit the PhET site and update their bookmarks. 

> One quick question is whether by adding a globe, it will increase the likelihood of people clicking and discoverying all the wonderful options we have. 

I've given this some thought, and I think we should really just encourage users to explore the Preferences dialog, in general. There are all sorts of cool things to find there. Realistically, there will be a very small set of sims with a Preferences dialog that don't also support in-sim locale switching (assuming users are on the _all file). Once we publish the first few sims with locale-switching and make the related website changes (Localization filter, access to the _all file), we can send out an email announcing this change and reminding users about the Preferences menu, in general.

**Comment by arouinfar** [comment]
We didn't have time to discuss this in depth during the 8/25/22 design meeting. However, I think we are fine with deferring this idea for now. Unclear if we want to revisit in the future, so assigning to @kathy-phet for next steps.

**Comment by zepumph** [comment]
Confirming here that this is not blocking the batch PhET-iO release. Please add to the project board if you feel differently.

**Comment by pixelzoom** [comment]
I'm wondering why it's necessary to change the icon -- I don't understand the importance of this from https://github.com/phetsims/joist/issues/833#issue-1343633858.  And will the user even notice tha the icon is different? Can't they just open the Preferences dialog and see if there's a Languages tab?  Isn't the goal to make all sims eventually have a Languages tab, thereby making different icons unnecessary?

My vote is for 1 icon for the Preference button in the navigation bar. The current icon is OK, but I don't understand the advantage of emphasizing the "person" part of the icon.  A standard "settings" icon would be much simpler/familiar, like https://fontawesome.com/v4/icon/cog:

<img width="70" alt="screenshot_1939" src="https://user-images.githubusercontent.com/3046552/198169031-77d90075-e9fb-4e75-b22e-ce25cedf5c27.png">

**Comment by kathy-phet** [comment]
I was originally thinking that it would be good to have the globe - because we would have sims with and without translation. At the moment only the _all sim version has translations available. There are some open questions around strategy and dissemination and the website, so that may evolve. 

For the moment, it seems like we have settled on using the person with gear. Let's continue to use that icon for now, and as we do more interviews with it across so many sims, we can revisit if we see the need from interviews. 

I'm going to close this issue.
