### ISSUE TITLE
Add a query parameter to enable Interactive Highlights by default

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/joist#855]
We would like to have this to support upcoming compatibility testing/user interviews. We have `voicingInitiallyEnabled`, presumably we would have `interactiveHighlightingInitiallyEnabled` to match?

**Comment by jessegreenberg** [comment]
Added `?interactiveHighlightsInitiallyEnabled` for this. @arouinfar will this be sufficient for your upcoming testing needs?

**Comment by zepumph** [comment]
@arouinfar looked today during PhET-iO meeting, all is good here. Thanks. Commits to come.
