### ISSUE TITLE
Should Preferences Menu include toggle for "Pan and Zoom" 

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/joist#857]
I noticed that Pan and Zoom is not in the preference menu, while we have moved all of the other options into that menu. Is there a use case where a user might prefer it off or want to toggle it on/off? Should there be access in the preferences menu? 

Is it a "Visual" preference? sort of. 

Related - if so, @zepumph, it would need to be in the collection of preferences.

**Comment by emily-phet** [comment]
I would prefer not to have a Pan and Zoom option in the preferences menu. We've been quite thoughtful about it's design, and it should feel relatively seamless from other system pan and zoom experiences. There is probably a case where it might not be desired (likely in a tablet situation) but I would prefer to leave it as is if and until there is a strong need arises to include an option to turn it off.

My hunch is that the Preferences menu loses utility the more cluttered it gets, so keeping the options as minimal as possible will help support ease of understanding around the options that are provided.

**Comment by kathy-phet** [comment]
I'm fine leaving it. Just wanted to check.
