### ISSUE TITLE
Does isLeftToRightProperty respect fallbacks correctly?

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#862]
From https://github.com/phetsims/phet-io/issues/1881

@marlitas and I noticed this code:

```ts
const isLeftToRightProperty = new DerivedProperty( [ localeProperty ], locale => {
  // @ts-ignore keyof localeInfoModule not helping here.
  return localeInfoModule[ locale ].direction === 'ltr';
} );
```

We specified a non-existant locale “ar_MM” and expected to see it fallback to “ar”, but the isLeftToRightProperty crashed because it didn’t know about “ar_MM” specifically.

**Comment by jonathanolson** [comment]
I previously had localeProperty's validValues to be the set of locales in localeInfoModule, which would guarantee this behavior. To me, localeProperty taking on something not in localeInfoModule seems to be the error.

**Comment by samreid** [comment]
Thanks, I believe this will be addressed as part of https://github.com/phetsims/joist/issues/862, closing.

**Comment by jonathanolson** [comment]
> Thanks, I believe this will be addressed as part of https://github.com/phetsims/joist/issues/862, closing.

That's... this issue. Did you mean another issue?

**Comment by samreid** [comment]
Yes, thanks.  I think we will address it in https://github.com/phetsims/phet-io/issues/1882
