### ISSUE TITLE
Long sim title strings break layout on single-screen sims

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#863]
To reproduce:

1. Run a single-screen sim (e.g. WOAS) with `&stringTest=asrtalasrkntalskrntalskrntalksrntlaksrntlaksrntalskrntalksrntaaslrtknaslrktnalsrktnalsrktnalskrntalksrntalskrntalskrntalksrntalskrnt`

The title will overshoot the PhET button:

<img width="881" alt="image" src="https://user-images.githubusercontent.com/480878/191358374-cabd6176-d6d9-4160-8a48-2ddd3b6dc55d.png">

Presumably we'll need a maxWidth for this

**Comment by jonathanolson** [comment]
In NavigationBar, we're subtracting by `this.a11yButtonsHBox.width`, which in this sim's case happens to have no bounds (thus its width is -Infinity), thus the maxWidth becomes +Infinity.

**Comment by jonathanolson** [comment]
@marlitas could you review this change?

**Comment by marlitas** [comment]
Looking through this I pulled up Waves on a String to test the functionality, and while using the helper dialog I hit an assertion when looking for the `A11yButtonsHBox`. It seems buggy to me that `A11yButtonsHBox` would have no bounds. If the HBox has no content its bounds should reflect that as 0.

**Comment by marlitas** [comment]
Talked through my questions with @jonathanolson. Feels good to close!
