### ISSUE TITLE
Preferences model: move toolbarEnabledProperty to Audio 

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/joist#866]
In review, we noticed that toolbarEnabledProperty was classified in the Preferences Model under "visualModel", but is hooked up to a selection under "audioModel". Please move it to the "Audio" part of the Preferences Model in the Studio Tree: 
 friction.general.model.preferencesModel.visualModel.toolbarEnabledProperty
 
 Thanks, K

**Comment by samreid** [comment]
I moved it to `friction.general.model.preferencesModel.audioModel.toolbarEnabledProperty`, @arouinfar or @kathy-phet want to review?

**Comment by arouinfar** [comment]
@samreid thanks, looks good in master.
