### ISSUE TITLE
Update localeOrderProperty algorithm

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#869]
Over in https://github.com/phetsims/phet-io/issues/1893, the PhET-iO team (KP AR SR MK) decided that it would be better to have the following locale order:

1. selected locale
2. The "shortened" version of the selected, if available.
3. The list specified by the fallbackLocalesProperty
4. en

We will still keep the optimization here: https://github.com/phetsims/joist/blob/897250904e4e1343e219fd8d9f115b22f1c0a333/js/i18n/localeOrderProperty.ts#L39-L40

**Comment by zepumph** [comment]
Tagging @jonathanolson here because he and I came to a different agreement to the algorithm over in https://github.com/phetsims/chipper/issues/1302#issuecomment-1245515050. 

@samreid, you will probably want to cherry-pick this for GAO, right?

**Comment by samreid** [comment]
https://github.com/phetsims/phet-io/issues/1893 is documented differently than I recall.  I thought we concluded that PhET-iO would not automatically fall back to shortened locales. Is that implemented and I'm not seeing it? Or was that decision overturned?

**Comment by zepumph** [comment]
That issue documents the decision that was made. We decided not to automatically fall back onto shortened locales from custom fallbacks. Is that maybe what you were thinking of?

**Comment by samreid** [comment]
> We decided not to automatically fall back onto shortened locales from custom fallbacks. Is that maybe what you were thinking of?

Yes, but it seems the implementation is still automatically falling back to the shortened one for the primary requested locale in https://github.com/phetsims/joist/blob/6500242a7ddcf1857f9bafda03fd958d73cfd600/js/i18n/localeOrderProperty.ts#L22-L26, unless I am misunderstanding something.

**Comment by zepumph** [comment]
Yes, that was specifically requested.

**Comment by samreid** [comment]
> @samreid, you will probably want to cherry-pick this for GAO, right?

If I recall correctly, @kathy-phet recommended that we would take all new SHAs after recent changes?

**Comment by zepumph** [comment]
She said that we need these changes in GAO, and if it is more work than its worth to keep track of cherry picks, then  we can do an rc

**Comment by samreid** [comment]
I opened a sim specific issue for cherry picking.
