### ISSUE TITLE
Preferences Dialog: Needs to respect UI Sound On/Off 

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/joist#870]
We found in Number Play that the Preferences Dialog plays UI sound and isn't respecting UI Sound On/Off list.

**Comment by jessegreenberg** [comment]
I think `TabSwitchSoundGenerator` was the only item missing a `categoryName`, @jbphet can you please confirm that this commit is correct?

**Comment by jessegreenberg** [comment]
Thanks for reviewing @jbphet. I think that was all for this one, @kathy-phet @amanda-phet @chrisklus FYI this was done.
