### ISSUE TITLE
Convert joist string usage to dynamic strings

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#873]

**Comment by zepumph** [comment]
Could I please review this to double check?

**Comment by zepumph** [comment]
* still some todos I'll take a look at

**Comment by zepumph** [comment]
Review: 

* I looked through all commits, and stumbled across https://github.com/phetsims/utterance-queue/issues/94
* I updated TODOs to point over to https://github.com/phetsims/joist/issues/885.
* I looked through all usages of `StringUtils.fillIn` to see if they could be `PatternStringProperty`, or some other pattern.
* I think that is all, but would you mind reviewing what I've done, and seeing if there is anything else? Thanks @AgustinVallejo.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.
