### ISSUE TITLE
Replace hasKeyboardHelpContent with "if any simScreen supplies keyboardHelpContent"

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#876]
Right now we duplicate a flag on sim and screens, but I think we can just use the presence of an option in each screen to determine if we support keyboard help. Noting and assigning myself. Please @jessegreenberg, let me know if you want to discuss this further.

**Comment by jessegreenberg** [comment]
Yes, removing the sim option seems like a good thing to do.
