### ISSUE TITLE
Updates to typescript handling of i18n dynamic strings

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#892]
While working on https://github.com/phetsims/chipper/issues/1366, I found that most of the @ts-expect-errors in joist have to do with the newish dynamic locales, mapping a locale string to a general string and then trying to pull the string union back out. Luckily, in my working copy I'm finding it quite easy to base everything on the typeof the locale map object for exact type checking.

**Comment by zepumph** [comment]
Ok. I had good success here. I like all of the changes, specifying `Locale` instead of `string` is a huge improvement in joist and expanded to a large number of other places.

**Comment by samreid** [comment]
I found some sims such as Molecule Shapes allow empty english strings, so I adjusted the assertion.  Tagging @zepumph in case this is unexpected.
