### ISSUE TITLE
Localization - How to inform screen reader users that localization is limited to on-screen text 

### ISSUE THREAD

**Issue by terracoda** [phetsims/joist#893]
For the Voicing feature we have a response that communicated that Voicing is turned off if the language gets switched to anything other than English.

For screen reader users, we are considering the case where they will be able to find the Localization Tab, but then we need to let them know that Localization is limited to on-screen text and that the Interactive Description feature, if available, is only available in English.

**Comment by terracoda** [comment]
@Nancy-Salpepi brought this issue to our attention while testing Ratio and Proportion.

**Comment by Nancy-Salpepi** [comment]
linking to https://github.com/phetsims/qa/issues/863

**Comment by terracoda** [comment]
Suggested solution is to draft a paragraph for the PDOM that succinctly captures that
[ ] localizatio is for on-screen text is only
[ ] for sims with interactive description, the designed description are only available English.

**Comment by terracoda** [comment]
**Draft 1:**
- Interactive description feature is only available in English at this time. Localization available for on-screen text only.

**Comment by zepumph** [comment]
@emily-phet and I discussed this issue today, and we feel that it isn't worth time delaying publication. Here is what the a11y view currently looks like:

![image](https://user-images.githubusercontent.com/6856943/207693505-d5cc5c7b-c46c-48fb-8941-c201885cee56.png)


The localization tab and heading are described, just not the buttons. Though it is incomplete, its blankness does convey a lack of support from a non-visual perspective.

We recommend deferring this issue and continuing with publication. We also do not recommend taking the locale panel out of the sim, as it is a nice improvement that has been tested and implemented since the summer.

**Comment by zepumph** [comment]
Sorry, I labelled thinking this issue was in RAP, not in common code, carry on for the next sim!

**Comment by terracoda** [comment]
@zepumph and @emily-phet, I completely respect your decision to not include a paragraph in the Localization Tab Panel for RaP. The lack of language names on the buttons does make it pretty impossible to make a meaningful change to the language while using screen reader software. Hopefully, screen readers won't try to change the language than get themselves in a pickle.

Maybe the paragraph should warn that changing the local language will not affect the described experience, and inform that it only changes the text that is visually on the screen.

**Comment by terracoda** [comment]
Draft 2:

- Localized language translation only available for visually displayed text. The fully described interactive experience is only available in English.

Draft 3:
- Localized language translations are only available for visually displayed text. For simulations with Interactive Description or Voicing, the described experience is available only in English.

Draft 4:
- Localization is only available for visually displayed text. The Interactive Description or Voicing features are in English only.

**Comment by terracoda** [comment]
How do folks feel about Draft 5? Short, succinct and not using negative wording like "only". There is no need to down play what these features actually provide.

Tagging @kathy-phet, @emily-phet , @Nancy-Salpepi, @zepumph, @jessegreenberg, @Matthew-Moore240.

**Comment by kathy-phet** [comment]
I like Draft 5.

**Comment by Nancy-Salpepi** [comment]
I also like the wording in Draft 5.

**Comment by terracoda** [comment]
Ok, great! 2 votes seems good to me. I am assigning to @jessegreenberg for implementation. @jessegreenberg, please re-assign to appropriate dev if you are not that person.

**Comment by terracoda** [comment]
Implementation of this is happening over in #930 (a duplicate, but more recent issue), so I will copy draft 5 over to that issue and close this one.
