### ISSUE TITLE
Type problems for Screen homeScreenIcon and navigationBarIcon

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#902]
Noted while adding `dispose` to ScreenIcon in https://github.com/phetsims/joist/issues/901...

In Screen.ts, ScreenOptions includes:

```typescript
  homeScreenIcon?: ScreenIcon | null;
  navigationBarIcon?: ScreenIcon | null;
```

But then the fields in Screen are:

```typescript
  public readonly homeScreenIcon: Node | null;
  public navigationBarIcon: Node | null;
```

And then the default `homeScreenIcon` is not even a ScreenIcon`:

```
    // Create a default homeScreenIcon, using the Screen's background color
    if ( !options.homeScreenIcon ) {
      options.homeScreenIcon = new Rectangle( 0, 0, MINIMUM_HOME_SCREEN_ICON_SIZE.width, MINIMUM_HOME_SCREEN_ICON_SIZE.height, {
        fill: options.backgroundColorProperty.value,
        stroke: 'black'
      } );
    }
```

So as soon as I add `dispose` to ScreenIcon, it's no longer structurally the same as Node, and a bunch of new tsc errors occurs, spanning multiple repos.

It looks like @samreid converted Screen to TypeScript.  I'll take a stab at fixing this, then will ask him to review.

**Comment by samreid** [comment]
I reviewed the commits, and everything looks good to me.  Closing.
