### ISSUE TITLE
AudioPreferencesPanel does not dynamically change its layout

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#903]
By default, the Audio Preferences for Number Play looks like this. It's a really strange layout, but that's not the probem I'm reporting.

<img width="1077" alt="screenshot_2228" src="https://user-images.githubusercontent.com/3046552/215908623-37e55641-80c5-4322-8ea5-8f85e2fc3799.png">

If we run Number Play with `screens=3,4`, then "Hear Total" toggle is irrelevant, and it's hidden by setting its `visible: false`. The layout then looks like this, which is really wrong. The left column is empty, so the right column should have moved to the center.

<img width="1052" alt="screenshot_2227" src="https://user-images.githubusercontent.com/3046552/215908708-136b5b5a-21de-45a7-8e00-c890f5baa06a.png">

The relevant code is in AudioPreferencesPanel.ts. `excludeInvisibleChildrenFromBounds: false` is probably the culprit here - it's default is `true` for FlowBox/VBox/HBox.  But note the comment.

```typescript
    // Some contents of this Dialog will be dynamically removed. Dont resize when this happens because we don't want
    // to shift contents of the entire Preferences dialog.
    const contentOptions: VBoxOptions = {
      align: 'left',
      spacing: PreferencesDialog.CONTENT_SPACING,
      excludeInvisibleChildrenFromBounds: false
    };
```

**Comment by marlitas** [comment]
The culprit for this was the `contentNode` being created in `PreferencesPanelSection`. I addressed this in the above commit and made sure there were no reverberations to other sims, most notably I checked: John Travoltage, Ratio and Proportion, and Quadrilateral. 

@pixelzoom can you review and close if all looks good? I'm mostly curious if I used combineOptions appropriately here. 

Also if any collateral effects are seen from this change in other sims please re-open and ping me.

**Comment by pixelzoom** [comment]
Verified that layout looks as expected with and without `screens=3,4` for NumberPlay. 

Use of `combineOptions` looks fine.

Closing.
