### ISSUE TITLE
Locale codes are not displayed in sims

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#905]
LanguageSelectionNode is the UI component that is used to select a language in the Preferences dialog. Here's what it looks like for the Localization tab:

<img width="1030" alt="screenshot_2247" src="https://user-images.githubusercontent.com/3046552/216152587-1293f0ad-7c26-469c-b0e1-74d20d595a57.png">

Here's what it looks like for Number Play's "Second Language" preference:

<img width="439" alt="screenshot_2246" src="https://user-images.githubusercontent.com/3046552/216152639-f15e5cc3-9e4b-4709-b197-ee6b15c81adf.png">

While we've been developing Number Play (@chrisklus @marlitas), it's been frustrating to test features that are locale related. We have to keep looking up these Language strings in localeInfoModule.ts in order to find out what values to use for the `locale` and `locales` query parameter.  

So...

(1) For development/testing, modify LanguageSelectionNode to include the locale code when a private query parameter is present. 

(2) Consider whether this will be a problem for teachers and PhET-iO instructional designers. How will they determine what values to use for `locale` and `locales`?  Should locale codes always be shown in the Localization preferences?

**Comment by pixelzoom** [comment]
In the above commit, I made this change to LanguageSelectionNode:

```diff
+    // Include the locale code when running with ?dev.
+    const string = phet.chipper.queryParameters.dev ?
+                   `${localeInfoModule[ locale ].localizedName} (${locale})` :
+                   localeInfoModule[ locale ].localizedName;
+
-    const text = new Text( localeInfoModule[ locale ].localizedName, {
+    const text = new Text( string, {
```

Running with `?dev` now makes the Localization preferences look like this:

<img width="1014" alt="screenshot_2245" src="https://user-images.githubusercontent.com/3046552/216154064-ac61a96d-5f87-4ccf-953a-fbc77f69bfad.png">

And Number Play's "Second Language" preference looks like this

<img width="430" alt="screenshot_2244" src="https://user-images.githubusercontent.com/3046552/216154125-3e77a637-fe0b-4383-a210-ffb96a924dd0.png">

Assigning to @jessegreenberg to review.  

Assigning to @arouinfar to answer question (2) above:
> (2) Consider whether this will be a problem for teachers and PhET-iO instructional designers. How will they determine what values to use for `locale` and `locales`? Should locale codes always be shown in the Localization preferences?

If the answer to (2) is "yes", the we should modify LanguageSelectionNode accordingly. If the answer to (2) is "no", then we might consider using a different query parameter than `?dev` for this.

**Comment by jessegreenberg** [comment]
Code change in https://github.com/phetsims/joist/commit/83f081c5d5d15e405c7021e6928df154ddc26b2e looks good to me.

**Comment by arouinfar** [comment]
> (2) Consider whether this will be a problem for teachers and PhET-iO instructional designers. How will they determine what values to use for locale and locales? Should locale codes always be shown in the Localization preferences?

Is `locales` intended to be public? We tell PhET-iO clients about `locale`, but not `locales`. In the PhET-io Guide, we recommend inspecting `localeProperty` to determine the appropriate locale code to use with the query parameter. 

As far as I know, we haven't shared either of these query parameters with teachers, since the `_all` file isn't the version we deliver on the sim pages. Students can select their desired language directly from the Localization tab, and I don't think the locale code is meaningful to most people. If teachers want to share a specific locale with a student, they're likely accessing it from the [Translations](https://phet.colorado.edu/en/simulations/ph-scale/translations) table on a sim page.

**Comment by pixelzoom** [comment]
OK, so it sounds like there's no general need/desire to show locale codes in the UI, and this issue can be closed.

But this concerns me:

> Is `locales` intended to be public? We tell PhET-iO clients about `locale`, but not `locales`. 

They are both private in initialize-globales.js.  If you're telling *anyone* outside of the PhET team about a query parameter, it needs to be set to `public: true`.  Please open an issue in phet-core if that is the case for `locale`.

**Comment by arouinfar** [comment]
There's a note in initialize-globals about `locale`:

> // Private Doc: DON'T add the `public` key here, because we want it to graceful bad values in production (falling back to en)

I think this means that we are intentionally not marking it as `public: true` even if it's being shared externally.

**Comment by pixelzoom** [comment]
That comment was added by @zepumph for https://github.com/phetsims/phet-io/issues/1882.  So I guess we should him -- what did you mean by this barely readable comment?  (And while you're there, please wordsmith it a bit.)

**Comment by pixelzoom** [comment]
Whilie I'm looking at this...  I moved the comment to a more effective location - where the `public` option would be added, see below.  I never noticed it when it was tacked on above the query-parameter description.  I also attempted to wordsmith, but I'm not positive that I deciphered this correctly.  @zepumph please refine if I did not get it right.  Then feel free to close this issue.

```
    /**
     * Select the language of the sim to the specific locale. Default to "en".
     * @memberOf PhetQueryParameters
     * @type {string}
     */
    locale: {
      type: 'string',
      defaultValue: 'en'
      // Do NOT add the `public` key here. We want this to fall back to en.
    },
```

**Comment by zepumph** [comment]
Amazing thanks. Closing
