### ISSUE TITLE
joist dynamic string Properties need PhET-iO metadata updates.

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#909]
From https://github.com/phetsims/phet-io/issues/1913 and a google doc. We want to add documentation that notes that that derivedProperty string can be changed by editing the dependency strings.

- [x] `general.view.navigationBar.titleText` should be featured.
- [x] `displayedSimNameProperty` should be featured.
- [x] `displayedSimNameProperty` documentation: "Customize this string by editing its dependencies."
- [x] simTitleWithScreenNamePatternString: "This pattern is used when a multi-screen simulation is only displaying one screen."

**Comment by zepumph** [comment]
Ok. This has been done and API files have been updated accordingly. It involved adding support for phetioDocumentation in string metadata, whereas before we just supported phetioFeatured and phetioReadOnly. Tagging @samreid so he is aware of that. Otherwise it was all quite simple.

**Comment by zepumph** [comment]
Feel free to close upon reading the above.

**Comment by samreid** [comment]
Thanks, I'm all caught up. Closing.
