### ISSUE TITLE
Update preferences icon

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/joist#919]
Based on interviews that @catherinecarter and I did, and discussions with @BLFiedler and @terracoda , we'd like to move ahead with a "cog" icon for the preferences dialog. To match the style of the other icons, we like this hollow version. 

<img width="656" alt="image" src="https://user-images.githubusercontent.com/7852916/231043692-4baca373-a652-42ff-be56-47829d6a2562.png">

However, this style isn't available in font awesome 4, so I made these PNGs. 

![preferencesIconOnWhite](https://user-images.githubusercontent.com/7852916/231043783-906bfbfe-c2ab-4fc1-b9b7-c48ab39a211c.png)
![prefeerencesIcon](https://user-images.githubusercontent.com/7852916/231043784-faca6a9b-df2f-48a9-a13f-93e5c5f0cdfc.png)

Assigning to @veillette to make this change in joist. If you need help, I believe @chrisklus is available. 

The icon should fit the scheme where the height matches the height of the P in PhET, which is also the height of the sound icon. The distance between each icon should also be equal. Let me know if any questions come up in the process!

**Comment by veillette** [comment]
@amanda-phet : do you have an svg of the cog? It is a highly symmetric shape so it would be better as an SVG.

**Comment by amanda-phet** [comment]
Sure, I just made a PNG to be consistent with the keyboard icon. Here are the icons as SVGs. 

[SVG.zip](https://github.com/phetsims/joist/files/11201605/SVG.zip)

**Comment by veillette** [comment]
Thanks @amanda-phet . I see what you mean about the keyboard Icon. I'll stick to the png then and follow the pattern for the keyboard icon.

**Comment by veillette** [comment]
I haven't committed my work on master yet but it would look like this.

In charges-and-fields (which has a projection mode) we have
![image](https://user-images.githubusercontent.com/7633344/231223538-5910e4b2-9ce2-4771-8bd6-7c91572a0227.png)
and in projection mode (there is an apparent change of size from the above screenshot due to the fact the two screenshots do not have the exact same sizes) ![image](https://user-images.githubusercontent.com/7633344/231223827-7e971653-61b7-432a-943f-b2ae59c7e130.png)

In quadrilateral, it yields,
![image](https://user-images.githubusercontent.com/7633344/231224158-af2336bc-b614-4761-9c5a-b63865407a73.png)

**Comment by veillette** [comment]
I noticed that the keyboard icons have uploaded their assets as `ai` files. I think we should the same. @amanda-phet , whenever you have the opportunity, please provide me with the assets for the icons.

**Comment by veillette** [comment]
@amanda-phet provided the assets for the icons.

**Comment by veillette** [comment]
In summary, we have updated the preference button icon. There are two png files that have been uploaded: one for the white background and the other for a black background. The pattern used here followed the pattern from the keyboard icon (which is also a png).

To review this issue, please
- Check that you can toggle the icon on master  with a sim with a projection mode (such as charges and fields) 
- Check that the license.json file has been updated correctly. 
- Look at the modifications in the `NavigationBarPreferencesButton.ts`

**Comment by veillette** [comment]
Assigning to @chrisklus to review.

**Comment by chrisklus** [comment]
Looking great, thanks @veillette! @zepumph and I reviewed together. The only thing we changed was the way the icon is scaled - by factoring out the height the image can be changed to any resolution and will render at the same size.

Back to you to close if nothing else.

**Comment by veillette** [comment]
Thanks @chrisklus and @zepumph for the quick review.

**Comment by zepumph** [comment]
Also noting that we though about how using `png` files are slightly blurrier when really zoomed in than the SVG font awesome audio button. Perhaps using SVG would make this clearer, but probably wouldn't be worth it for the amount of SVG data for something like the keyboard button. We don't want to make a new issue for that.

Number play team will proceed in https://github.com/phetsims/number-play/issues/233, and are ready to close this issue. Thanks so much for making this happen.

**Comment by veillette** [comment]
The work is done here. Closing.
