### ISSUE TITLE
Unable to open screenshots if sim title has diacritics 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/joist#921]
**Test device**
MacBook Air M1 chip

**Operating System**
13.3.1

**Browser**
Chrome 112

**Problem description**
First seen when testing https://github.com/phetsims/qa/issues/930, but is a general issue:

If I take a screenshot using the tool in the PhET Menu when a sim title contains a diacritic, I am unable to open the screenshot. 

This only occurs with mac + chrome. @KatieWoe and @stemilymill also confirmed on their devices. 

**Steps to reproduce**
Here is an example:
1. In the density sim, switch the locale to Italian. The title now has an accent mark.
2. Take a screenshot from the PhET menu.
3. Try to open the screenshot at the bottom of your screen--it doesn't open
<img width="659" alt="Screenshot 2023-04-27 at 12 07 44 PM" src="https://user-images.githubusercontent.com/87318828/234921570-d69dc182-8672-4c9d-93f3-663e69aa3a3a.png">

4. Go to your Downloads folder and try to open the screenshot --it doesn't open.    
5. Open Preview and then open the file --this works.   

<br>

@stemilymill  also reported:
>and the weird thing is that if i screenshot it in english and then change the file name to be the same as the not-working italian one, it still works fine

**Comment by zepumph** [comment]
@jonathanolson have we run into this before? I thought perhaps but I couldn't find a paper trail.

**Comment by zepumph** [comment]
Is it too horrible to just always use the english name? 

https://github.com/phetsims/joist/blob/3a5a03c897454918278899cf36070bb095ce211c/js/PhetMenu.ts#L170

I don't know who can help me make this call. @samreid can you help me with a brainstorm?

**Comment by samreid** [comment]
My first instinct was to use the project name (like the name of the github repo), but I'd like to understand the problem more.  When I download italian density screenshot on my macbook air M1 with Chrome, it opens correctly with Preview.  Also when I go to the downloads folder and double click on it, it also opens with preview.  For @Nancy-Salpepi @KatieWoe @stemilymill what application normally opens a *.png file (without a diacritic)?

**Comment by Nancy-Salpepi** [comment]
> For @Nancy-Salpepi @KatieWoe @stemilymill what application normally opens a *.png file (without a diacritic)?

   Preview opens the file

- Since posting this issue, I have updated to macOS 13.4 and Chrome 114. I am no longer able to reproduce this problem.
