### ISSUE TITLE
Chrome DevTools Issue: Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#928]
Originally reported by @Nancy-Salpepi in https://github.com/phetsims/geometric-optics/issues/476 ...

Chrome DevTools is reporting an Issue related to FileSaver-b8054a2.js.

To reproduce:

1. Launch any sim from phetmarks.  For example, density in mode "Unbuilt".
2. Open Chrome DevTools and click on the "Issues" tab.  You'll see an Issue that looks like this. Note that the blue icon means severity "An improvement issue: there is an opportunity to improve the page".

<img width="586" alt="screenshot_2555" src="https://github.com/phetsims/geometric-optics/assets/3046552/817bf18f-6183-44d7-a3f2-02e91758129f">

3. Example the issue, then expand "> 1 source".  Note that the 1 source is FileSaver-b8054a2.js.

<img width="714" alt="screenshot_2554" src="https://github.com/phetsims/geometric-optics/assets/3046552/7c92b123-69f0-4873-ae9a-7bcf45c0abb1">

**Comment by jonathanolson** [comment]
I wasn't able to reproduce the warning. We're using userAgent/platform in platform.js to detect browser/OS. Chrome (as of v113) has reduced the amount of information available in the userAgent/platform. We are fine with the current information provided (still), so the deprecation warnings before/after don't concern me. This is non-blocking, the console messages are warning about something that is not an issue for us.

**Comment by pixelzoom** [comment]
Thanks for the clarification. We can safely ignore this, so closing.
