### ISSUE TITLE
Remove dispose code in Preferences

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#929]
This doesn't not need to be disposed anymore since https://github.com/phetsims/phet-io/issues/1810

**Comment by jessegreenberg** [comment]
Disposal code under joist/js/preferences was removed. Only exception is a case involving the Voice combobox which needs to stay for its own implementation.

I tested by running local aqua for a bit for phet brand sims, phet-io brand sims, and sims that support interactive description. I also ran a few sims in the state wrapper which I think is where dispose was most important.

@zepumph would you like to spot check, anything else?

**Comment by zepumph** [comment]
Looks great. Thanks so much

**Comment by zepumph** [comment]
Oh, I got a couple more usages of sim-specific preferences taken care of. I also love all the assertions in dispose() calls in central Preferences. That will definitely help us ensure this behavior in the future.
