### ISSUE TITLE
Increase the size of pointer areas for tabs in Preferences Menu

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/joist#932]
While testing https://github.com/phetsims/qa/issues/958, with interactive highlights on, I noticed that the pointer areas between the tabs aren't flush against each other. If I quickly move my mouse from one tab to the the next, the group highlight will disappear and quickly reappear, leading to a flashing affect. 

https://github.com/phetsims/joist/assets/87318828/24c7fad9-2879-426c-adfa-f9c495e9ef22

**Comment by jessegreenberg** [comment]
Thanks @Nancy-Salpepi, this is a pretty poor UX. A fix has been made in the above commit, can you please verify?

**Comment by Nancy-Salpepi** [comment]
Yes! Much nicer now @jessegreenberg!
Closing.
