### ISSUE TITLE
Unexpected PhET-iO API changes related to About dialog

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#933]
I’m running `grunt generate-phet-io-api` for greenhouse-effect, and seeing lots of changes that are unrelated to what I’m working on. Specifically:

There are 3 new Properties, likely from joist:
* termsPrivacyAndLicensingLinkTextStringProperty
* thirdPartyCreditsLinkTextStringProperty
* translationCreditsLinkTextStringProperty

@zepumph says that this seems like a regression, so assigning to him.

**Comment by zepumph** [comment]
Thanks for the issue. I didn't really remember it, so I'm glad for an issue to track it back. 

In https://github.com/phetsims/studio/issues/308 we swapped some instrumentation from Text Nodes to their StringProperties, so we instrumented a previously uninstrumented stringProperty to support autoselect of these in the AboutDialog. 

https://github.com/phetsims/phet-io-sim-specific/commit/b987842f1ec1c3cdc9212b4436c395b78d9c0a22.

Closing
