### ISSUE TITLE
Uninstrument Text and RichText

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#934]
In https://github.com/phetsims/phet-io/issues/1952#issuecomment-1664495275 we decided that we generally don't want to instrument Text nodes, and instead just want to focus on the stringProperties, especially if they are derived or pattern. 

- [x] Let's double check that sim code isn't instrumenting Texts unless there is a reason (like hiding the Text).
- [x] Let's also look for common code UI that needs to be generally updated to support this new PhET-iO instrumented decision. (For example Natural Selection dealt with NumberDisplay and OopsDialog)

Most likely the important things are for general sim/screen names, and for HomeScreen.

**Comment by arouinfar** [comment]
I reviewed `general` and `homeScreen` for usages for Text and would recommend that we uninstrument these Text nodes:

- [ ] `general.view.navigationBar.titleText`
- [ ] `general.view.navigationBar.*ScreenButton.text`
- [ ] `homeScreen.view.buttonGroup.*ScreenButton.text`
- [ ] `homeScreen.view.titleText`

I also reviewed instances of `StringProperty` outside of `general.model.strings` and found these in the About dialog. These all link back to read-only strings, so I recommend uninstrumenting these too.
- [ ] `aboutDialogCapsule.archetype.termsPrivacyAndLicensingLinkTextStringProperty`
- [ ] `aboutDialogCapsule.archetype.thirdPartyCreditsLinkTextStringProperty`
- [ ] `aboutDialogCapsule.archetype.translationCreditsLinkTextStringProperty`

Also, autoselect is working well on the navbar. The sim title routes users to `general.model.displayedSimNameProperty` which is desirable (and should remain instrumented). Autoselecting the screen buttons in the navbar takes me directly to the appropriate `StringProperty` and bypasses the view instrumentation.

I'm not sure who should be on the hook for these changes. Maybe @zepumph? Maybe @pixelzoom since Acid-Base Solutions is likely next up in the queue?

**Comment by pixelzoom** [comment]
If this ends up on my worklist, I won't be able to get to it until August 28 at the earliest.

**Comment by samreid** [comment]
Today @kathy-phet asked if I could take the lead, and I agreed. @zepumph can review.

**Comment by samreid** [comment]
Today we agreed that the navigation bar title text should be hide-able.

**Comment by samreid** [comment]
Fixed in the commits, @arouinfar can you please review/test?  @zepumph would you like to code review? If we need migration rules (deletes), we can write them lazily.

**Comment by arouinfar** [comment]
Thanks @samreid! We reviewed with @kathy-phet @samreid @zepumph in Studio and the changes look good, closing.

**Comment by samreid** [comment]
In slack, @kathy-phet said:

> One thing we forgot re joist issue is that we are supposed to make the migration rules at this time as well for each sim that is published. @samreid can you do that please.

**Comment by samreid** [comment]
This patch makes it possible for a Natural Selection 1.5 standard wrapper (published today) will load in local natural selection studio 1.6:

<details>

```diff

Subject: [PATCH] Rename string keys, see https://github.com/phetsims/center-and-variability/issues/373
---
Index: repos/natural-selection/js/natural-selection-migration-rules.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/repos/natural-selection/js/natural-selection-migration-rules.ts b/repos/natural-selection/js/natural-selection-migration-rules.ts
--- a/repos/natural-selection/js/natural-selection-migration-rules.ts	(revision 80cdb36bf3cd8aa114bc6b2d2c4080da8f5a39d4)
+++ b/repos/natural-selection/js/natural-selection-migration-rules.ts	(date 1692302411240)
@@ -270,5 +270,12 @@
     // needs to be set by the state engine. This rule should be done last (after all renames) so that the phetioID
     // matches the new API. See further documentation in PhetioTypeDelete.ts.
     new PhetioTypeDelete( 'SimInfoIO' )
+  ],
+  '1.6.0': [
+    new TandemFragmentDelete( 'naturalSelection.homeScreen.view.titleText.stringProperty' ),
+    new TandemFragmentDelete( 'naturalSelection.general.view.navigationBar.introScreenButton.text.stringProperty' ),
+    new TandemFragmentDelete( 'naturalSelection.general.view.navigationBar.labScreenButton.text.stringProperty' ),
+    new TandemFragmentDelete( 'naturalSelection.homeScreen.view.buttonGroup.introScreenButton.text.stringProperty' ),
+    new TandemFragmentDelete( 'naturalSelection.homeScreen.view.buttonGroup.labScreenButton.text.stringProperty' )
   ]
 };
\ No newline at end of file

```

</details>

@zepumph Is this correct?

**Comment by zepumph** [comment]
> @zepumph Is this the right approach?

We haven't come to a consensus over in https://github.com/phetsims/phet-io-sim-specific/issues/27 about how to best handle migration rules for this. If we have decided to  add migration rules to sims when the breaking change is introduced, then the above looks correct, but is incomplete. This is our current list of sims that support migration (PhET-iO Hydrogen), so they would each need to get rules. Right?

```
Gravity And Orbits
pH Scale
pH Scale: Basics
Friction
Beer's Law Lab
Concentration
Molecule Shapes
Molecule Shapes: Basics
Circuit Construction Kit: DC
Circuit Construction Kit: DC - Virtual Lab
Calculus Grapher
Geometric Optics
Geometric Optics: Basics
Density
Molecule Polarity
Graphing Quadratics
Natural Selection
```

**Comment by kathy-phet** [comment]
We had decided we would try writing migration rules for each sim that needs it at the time that change is made, and we would report back on how that went. This is the first such change - since we bailed on the other common code changes we had consider in the number display. 
So @samreid - yes, please put a migration rule in place for each of these sims, in "main".

**Comment by samreid** [comment]
I'm happy to do that, but would like to confirm with @zepumph that we don't need a LinkedElement related rule for these. Without the rules, trying to load a 1.5 standard wrapper into 1.6 gives this error:

```
assert.js:24 Assertion failed:  Impossible set state from iterate; unset state: {
  "naturalSelection.general.view.navigationBar.introScreenButton.text.stringProperty": {
    "elementID": "naturalSelection.general.model.strings.naturalSelection.screen.introStringProperty"
  },
  "naturalSelection.general.view.navigationBar.labScreenButton.text.stringProperty": {
    "elementID": "naturalSelection.general.model.strings.naturalSelection.screen.labStringProperty"
  },
  "naturalSelection.homeScreen.view.titleText.stringProperty": {
    "elementID": "naturalSelection.general.model.strings.naturalSelection.naturalSelection.titleStringProperty"
  },
  "naturalSelection.homeScreen.view.buttonGroup.introScreenButton.text.stringProperty": {
    "elementID": "naturalSelection.general.model.strings.naturalSelection.screen.introStringProperty"
  },
  "naturalSelection.homeScreen.view.buttonGroup.labScreenButton.text.stringProperty": {
    "elementID": "naturalSelection.general.model.strings.naturalSelection.screen.labStringProperty"
  }
} 
```

So they do look like linked elements because of the `elementID`. It it correct that LinkedElements used to be stateful, so I need to knock them out with a `TandemFragmentDelete`? I just want to confirm this for natural selection before applying this elsewhere. If we really do just need `TandemFragmentDelete`, should I abstract out regex or patterns for copy/pasting out to different sims?  Are we at a point where we can experiment with putting 

```
1.6.0: [
    ...UNINSTRUMENT_JOIST_TEXT // see https://github.com/phetsims/joist/issues/934
]
```

With an explanatory code comment there?

**Comment by pixelzoom** [comment]
Self assigning to look at the proposal in https://github.com/phetsims/joist/issues/934#issuecomment-1683305471, so that we can unblock https://github.com/phetsims/tandem/issues/303.

**Comment by samreid** [comment]
Here's a patch that seems to work OK for calculus grapher:

<details>

```diff

Subject: [PATCH] Simplify NumberTone.play API, fix a bug in mean sound effect, see https://github.com/phetsims/center-and-variability/issues/491
---
Index: repos/calculus-grapher/js/calculus-grapher-migration-rules.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/repos/calculus-grapher/js/calculus-grapher-migration-rules.ts b/repos/calculus-grapher/js/calculus-grapher-migration-rules.ts
new file mode 100644
--- /dev/null	(date 1692709198252)
+++ b/repos/calculus-grapher/js/calculus-grapher-migration-rules.ts	(date 1692709198252)
@@ -0,0 +1,29 @@
+// Copyright 2022, University of Colorado Boulder
+// This PhET-iO file requires a license
+// USE WITHOUT A LICENSE AGREEMENT IS STRICTLY PROHIBITED.
+// For licensing, please contact phethelp@colorado.edu
+
+import TandemFragmentDelete from '../../../../phet-io-wrappers/common/js/migration/TandemFragmentDelete.js';
+
+window.phetio = window.phetio || {};
+
+// Use ${simName} in rules that are general and might be usable for other sims
+const simName = 'calculusGrapher';
+
+window.phetio.migrationRules = {
+  '1.2.0': [
+    new TandemFragmentDelete( 'calculusGrapher.homeScreen.view.titleText.stringProperty' ),
+
+    new TandemFragmentDelete( 'calculusGrapher.general.view.navigationBar.derivativeScreenButton.text.stringProperty' ),
+    new TandemFragmentDelete( 'calculusGrapher.homeScreen.view.buttonGroup.derivativeScreenButton.text.stringProperty' ),
+
+    new TandemFragmentDelete( 'calculusGrapher.general.view.navigationBar.integralScreenButton.text.stringProperty' ),
+    new TandemFragmentDelete( 'calculusGrapher.homeScreen.view.buttonGroup.integralScreenButton.text.stringProperty' ),
+
+    new TandemFragmentDelete( 'calculusGrapher.general.view.navigationBar.advancedScreenButton.text.stringProperty' ),
+    new TandemFragmentDelete( 'calculusGrapher.homeScreen.view.buttonGroup.advancedScreenButton.text.stringProperty' ),
+
+    new TandemFragmentDelete( 'calculusGrapher.general.view.navigationBar.labScreenButton.text.stringProperty' ),
+    new TandemFragmentDelete( 'calculusGrapher.homeScreen.view.buttonGroup.labScreenButton.text.stringProperty' )
+  ]
+};

```

</details>

After that change, the migration wrapper still reports:

```
assert.js:24 Assertion failed:  These phetioIDs are not found in the new API. Either they were renamed incorrectly or were not migrated at all:
calculusGrapher.advancedScreen.view.controlPanel.pushButtonGroup.smoothButton.text.stringProperty
calculusGrapher.labScreen.view.controlPanel.pushButtonGroup.smoothButton.text.stringProperty
```

**Comment by samreid** [comment]
For Calculus Grapher, I committed rules for the joist changes and for a missing `smoothButton` text. Now it's working in the migration wrapper.

**Comment by pixelzoom** [comment]
Thanks. But the problem with `smoothButton` text is a general problem with TextPushButton that should have been addressed in https://github.com/phetsims/sun/issues/854.

**Comment by zepumph** [comment]
Subset of https://github.com/phetsims/phet-io/issues/1960

**Comment by zepumph** [comment]
Alright. We can confirm that migration rules are now complete and working for this issue. Closing

**Comment by pixelzoom** [comment]
Reopening.  This TODO appears in beers-law-lab-migration-rules.ts and concentration-migration-rules.ts.  This was discovered while working on https://github.com/phetsims/beers-law-lab/issues/332, and complicated that issue.

**Comment by pixelzoom** [comment]
Also wondering why this was not reopened automatically. Is the automated task still running that looks for TODOs?

**Comment by zepumph** [comment]
Great question. It was working in https://github.com/phetsims/greenhouse-effect/issues/361#issuecomment-1712467793. I will take a look.

**Comment by samreid** [comment]
I was going to work on this next, but the comment in https://github.com/phetsims/phet-io/issues/1963#issuecomment-1714788272 indicates that maybe @pixelzoom is working on it.  So I'll self unassign and check in at standup tomorrow.

**Comment by pixelzoom** [comment]
I do not plan to do any further work on this.

**Comment by pixelzoom** [comment]
I do not plan to do any further work on this.  Or anything else related to migration until this is addressed.

**Comment by zepumph** [comment]
> Also wondering why this was not reopened automatically. Is the automated task still running that looks for TODOs?

Ahh, because the feature relies on the lint rule called `todo-should-have-issue`, and whereever that rule is turned off, we don't have this feature.

https://github.com/phetsims/phet-io-sim-specific/blob/b5d1d086b5a06ad1199acce78056ceb6eb60689b/package.json#L19

**Comment by pixelzoom** [comment]
Why is "todo-should-have-issue" turned off in phet-io-sim-specific? Shall we turn it on?

**Comment by zepumph** [comment]
https://github.com/phetsims/tasks/issues/1128

**Comment by zepumph** [comment]
@samreid will take the lead on the TODO that is left.

**Comment by samreid** [comment]
It was addressed in https://github.com/phetsims/phet-io-sim-specific/commit/43e849416cec874431b41893f7bdb88f741ef0ff, closing.
