### ISSUE TITLE
Preferences Dialog has pointer areas on text

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/joist#935]
First discussed here: https://github.com/phetsims/keplers-laws/issues/79 

Preferences dialog is showing pointer areas on some text which is not focusable. Assigning to @pixelzoom 

![image](https://github.com/phetsims/keplers-laws/assets/37052186/14d292bc-5406-4d38-8a54-942270908183)

**Comment by jessegreenberg** [comment]
Hey @AgustinVallejo, this text is interactive in some modes so the mouse/touch areas are expected. VoicingText is for the Voicing feature, and this text is clickable when Voicing is enabled. For example, see https://phet.colorado.edu/sims/html/quadrilateral/latest/quadrilateral_all.html?voicingInitiallyEnabled.
