### ISSUE TITLE
About Dialog visibleProperty failing with "These phetioIDs are not found in the new API" when migration fuzzing

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#937]
Every PhET-iO migration wrapper is failing with the error:

> Assertion failed: These phetioIDs are not found in the new API. Either they were renamed incorrectly or were not migrated at all:
beersLawLab.general.view.navigationBar.phetButton.phetMenu.aboutDialogCapsule.aboutDialog.visibleProperty

Note that tandem is in the `capsule.aboutDialog` not the `capsule.archetype`.

It is because when fuzzing the upper sim it creates an about dialog, which then appears in the state.  Then transmitting the state to the lower sim, it doesn't have an About Dialog yet.

@zepumph and I recently made the about dialog "create it once and it lives forever" for a related problem. I'm not sure if that relates to the problem at hand, but I'm not sure how to proceed.

**Comment by zepumph** [comment]
Regression occurred in https://github.com/phetsims/sun/commit/b8c7c0a252352b58ce4e07b52e195625c8f67157

**Comment by zepumph** [comment]
Subset of https://github.com/phetsims/phet-io/issues/1960

**Comment by samreid** [comment]
I feel like we fixed this.
