### ISSUE TITLE
Disable global hotkeys for components behind the top layer when a modal dialog is open

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/joist#940]
From slack:

> Nancy Salpepi
> 
> I noticed while testing CaV that using the keyboard shortcut opt + R for Reset All while a dialog is open, resets the sim but keeps the dialog open. I was sure what the desired behavior should be here. @jessegreenberg  suggested that maybe global commands like that should be disabled when a dialog is open. What do the designers think?
> 
> 
> 5 replies
> 
> 
> Amy Rouinfar
> 
> That sounds reasonable to me.
> 
> 
> Kathy Perkins
> 
> Amy - curious why disabled, versus just actually reset all ... and close the dialog? It seems like it would feel buggy to the user to not have it work?
> 
> 
> Amy Rouinfar
> 
> It sounds like the proposal applies to other hotkeys like alt+k for play/pause. With the dialog open, you can’t see what’s happened in the sim to know that you’ve successfully interacted. (edited) 
> 
> 
> Chris Malley
> 
> Dialogs are modal. Modal means you can’t do anything except what’s in the dialog while it’s open. (edited) 
> :+1::skin-tone-3:
> 1
> 
> 
> 
> Kathy Perkins
> 
> OK - makes sense. Thanks.

This should be simple since we already remove these Nodes from the traversal order.

**Comment by Nancy-Salpepi** [comment]
linking to https://github.com/phetsims/qa/issues/999 for @marlitas

**Comment by marlitas** [comment]
Is this a change we want to cherry-pick for Center and Variability? Not sure what the timeline is... @jessegreenberg? @kathy-phet?

**Comment by kathy-phet** [comment]
@jessegreenberg - Can you do this in a way that can cherry pick? And can you comment on the timeline, is it possible to fit it in Wednesday .. not sure what you have going on. Obviously this would be the 25% time, non-idt grant time.

**Comment by jessegreenberg** [comment]
Yes, I am looking at this now. This one seems like a simple one line change that should be easy to cherry pick, I am testing it now.

**Comment by jessegreenberg** [comment]
Done - this was fixed by preventing dispatch of global keyboard events for Nodes that are `pdomVisible: false`, which is more correct. So this change was actually made in scenery.

@Nancy-Salpepi can you please confirm this fix before we cherry-pick it into the release branch?

**Comment by Nancy-Salpepi** [comment]
This looks good with mac + safari. I tested the keyboard shortcuts in Quadrilateral and CaV.

**Comment by jessegreenberg** [comment]
OK, great. Thanks @Nancy-Salpepi. @marlitas here is the scenery commit to cherry-pick for CaV (also shared over slack). https://github.com/phetsims/scenery/commit/9a69b946d77cdcc224755b4055a7129058de87f5

I am going to go ahead and close this one since the common code issue has been fixed.

**Comment by jessegreenberg** [comment]
Actually, leaving open for tracking.

**Comment by marlitas** [comment]
This has been successfully cherry-picked for CAV. Closing. Thanks all!
