### ISSUE TITLE
Address `strictAxonDependencies: false` in Helper.ts

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#948]
For https://github.com/phetsims/axon/issues/441, @samreid added 1 occurrence of `strictAxonDependencies: false` to Helper.ts. It should be inspected/addressed when this repo is worked on.

**Comment by samreid** [comment]
We decided to remove this feature in https://github.com/phetsims/axon/issues/441. I will remove the flag and the TODO, closing.
