### ISSUE TITLE
Warn users if running on unsupported platform

### ISSUE THREAD

**Issue by jbphet** [phetsims/joist#95]
We should warn users somehow if they are attempting to run a PhET sim on an unsupported platform.  At the time of this writing, the two main unsupported platforms of concern are iOS6 and Safari 5.

**Comment by pixelzoom** [comment]
> we discussed the schedule for this and decided to defer it until early 2014.

It's now mid-2014. Perhaps we should revisit?

**Comment by jbphet** [comment]
This was discussed at the 8/20/2015 developer meeting, and @oliver-phet says that we're not receiving many reports from users about HTML5 sims not working.  Perhaps that can be handled just by having a list of supported/tested platforms on the web site, and not need to work this into the sim code.  We'll close this issue and reopen it or create a new one if we begin to get reports that indicate that a significant number of users are having platform issues.
