### ISSUE TITLE
Rename string keys for choices shown in RegionAndCultureComboBox.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#954]
Related to https://github.com/phetsims/joist/issues/953, where we are generalizing localized images...

"Portrayal" is a vestigial term. When https://github.com/phetsims/joist/issues/953 is completed, that term will cease to exist. Unfortunately "portrayalSets" was used throughout the string keys in joist-strings_en.json:

```ts
  "preferences.tabs.localization.regionAndCulture.portrayalSets.unitedStatesOfAmerica": {
    "value": "United States of America"
  },
  "preferences.tabs.localization.regionAndCulture.portrayalSets.multicultural": {
    "value": "Multicultural"
  },
  "preferences.tabs.localization.regionAndCulture.portrayalSets.africa": {
    "value": "Africa"
  },
  "preferences.tabs.localization.regionAndCulture.portrayalSets.africaModest": {
    "value": "Africa (Modest)"
  },
  "preferences.tabs.localization.regionAndCulture.portrayalSets.asia": {
    "value": "Asia"
  },
  "preferences.tabs.localization.regionAndCulture.portrayalSets.latinAmerica": {
    "value": "Latin America"
  },
  "preferences.tabs.localization.regionAndCulture.portrayalSets.oceania": {
    "value": "Oceania"
  },
```

It unnecessary constraining that these strings appear under "preferences.tabs.localization"; they could appear elsewhere in the UI in the future, and do appear elsewhere in PhET-iO.
 
It also results in code like this, where we still have "portrayal" lingering in the implementation:

```ts
const STRING_PROPERTY_MAP: Record<RegionAndCulture, LocalizedStringProperty> = {
  usa: JoistStrings.preferences.tabs.localization.regionAndCulture.portrayalSets.unitedStatesOfAmericaStringProperty,
  africa: JoistStrings.preferences.tabs.localization.regionAndCulture.portrayalSets.africaStringProperty,
  africaModest: JoistStrings.preferences.tabs.localization.regionAndCulture.portrayalSets.africaModestStringProperty,
  asia: JoistStrings.preferences.tabs.localization.regionAndCulture.portrayalSets.asiaStringProperty,
  latinAmerica: JoistStrings.preferences.tabs.localization.regionAndCulture.portrayalSets.latinAmericaStringProperty,
  oceania: JoistStrings.preferences.tabs.localization.regionAndCulture.portrayalSets.oceaniaStringProperty,
  multi: JoistStrings.preferences.tabs.localization.regionAndCulture.portrayalSets.multiculturalStringProperty
};
```

First, we should decide whether it's worth the effort to change this, or just live with it.  @jonathanolson and I recommending changing it.

If we decide to change it, we should decide on the revised string keys.  @jonathanolson and I recommend:

```
regionAndCulture.africa
regionAndCulture.africaModest
regionAndCulture.asia
regionAndCulture.latinAmerica
regionAndCulture.multicultural
regionAndCulture.oceania
regionAndCulture.unitedStatesOfAmerica
```

@amanda-phet @marlitas @Luisav1 thoughts?

**Comment by pixelzoom** [comment]
Adding blocks-publication label. These strings are instrumented for PhET-iO, and this will change the PhET-iO API.  So any sims that are about to create a release branch should be aware of this issue, and decide whether to proceed.

**Comment by marlitas** [comment]
I'm open to changing it, I think it just depends on the complexity of fixing the string keys. I think last time we talked @pixelzoom it looked like there weren't any translations for this yet?

**Comment by pixelzoom** [comment]
To be discussed in 3/6/2024 design meeting.

**Comment by jbphet** [comment]
Above, @pixelzoom said:

> @jbphet Could you please weigh in on how difficult changing these string keys would be?

The answer is "somewhat hard, but not insurmountable".  Here is [a description of the process for changing a string in common code](https://github.com/phetsims/rosetta/blob/main/doc/how-to-change-a-string-key.md#changing-a-string-key-for-a-common-code-repository), which is from a doc in the rosetta repo.  Hopefully this answers your question, let me know if you'd like anything more on this from me.

**Comment by pixelzoom** [comment]
From 3/7/2024 design meeting with @amanda-phet @kathy-phet @Luisav1 @jbphet @jonathanolson. FYI @marlitas.

* We will rename the string keys. @pixelzoom will run the proposed keys by @zepumph, to make sure he doesn't have any concerns.
* We will not attempt to port translations to the new keys. It's too costly.  Translators will need to retranslate, but only once since joist is a common-code repo.  In the meantime, published sims can continue to be translated using the old keys.
* We will address PhET-iO migration if we need to.  These keys appear in a lot of API files, but few (possibly none) these API files are for published PhET-iO sims the "Region and Culture" feature.  CAV may be the exception, check it out. Also confirm with @zepumph that we can skip migration rules.

**Comment by pixelzoom** [comment]
Discussesd with @zepumph.

We decided to keep the verbose string keys, and just remove the "portrayalSets" part. So:

```js
preferences.tabs.localization.regionAndCulture.africa
preferences.tabs.localization.regionAndCulture.africaModest
preferences.tabs.localization.regionAndCulture.asia
preferences.tabs.localization.regionAndCulture.latinAmerica
preferences.tabs.localization.regionAndCulture.multicultural
preferences.tabs.localization.regionAndCulture.oceania
preferences.tabs.localization.regionAndCulture.unitedStatesOfAmerica
```

Since these strings are in joist, this will change the API for all PhET-iO sims, and require `grunt generate-phet-io-api --stable`.  

CAV 1.1 is the only PhET-iO sim that has been published with the Region and Culture feature -- the only sim that appears in phet-io-stable and has "supportedRegionsAndCultures" in its package.json. So for migration, we will ignore the change for all PhET-iO sims except CAV.

CAV will need the following migration rules:

- [ ] RenamePhetioElement: `centerAndVariability.general.model.regionAndCulturePortrayalProperty` to `centerAndVariability.general.model.regionAndCultureProperty`
- [ ] ChangePhetioElementIOType: `PropertyIO<RegionAndCulturePortrayalIO>` to `PropertyIO<StringIO>`, with callback to change values.
- [ ] RenamePhetioElement for each of the above joist strings Properties.

**Comment by pixelzoom** [comment]
I moved the CAV migration rules work to https://github.com/phetsims/center-and-variability/issues/615.

**Comment by pixelzoom** [comment]
Work here is done. The new Studio tree structure for `general.model.strings.joist.preferences` is shown below.   CAV migration rules will be addressed in https://github.com/phetsims/center-and-variability/issues/615.

@marlitas and @amanda-phet please review.  Last one to review can close this issue.

<img width="380" alt="screenshot_3077" src="https://github.com/phetsims/joist/assets/3046552/e4c976d3-2655-4a53-a42a-665bc21158d1">

**Comment by pixelzoom** [comment]
@marlitas @amanda-phet Note that this issue blocks creation of the PDL release branch, which @samreid says is planned for Thu 3/21.   So please prioritize review of this issue.

**Comment by samreid** [comment]
To clarify, we will run a Dev Test first, so release branch will not be created until that is complete.

**Comment by amanda-phet** [comment]
The studio structure looks good to me!

**Comment by marlitas** [comment]
The changes in joist and other repos look good. I think this is ready to close. Thanks!
