### ISSUE TITLE
Change 'multi' to 'random' for Region and Culture.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#957]
From 3/7/2024 design meeting with @amanda-phet @kathy-phet @Luisav1 @jbphet @jonathanolson.  FYI @marlitas.

For Region and Culture, @kathy-phet requested that we change 'multi' to 'random'.   The string will also need to change, so related to https://github.com/phetsims/joist/issues/954.

There was a discussion about changing the default to 'multi', but we decided against that because it could be problematic in the classroom.  For example, if "Region and Culture" was applied to the sandwich in RPAL, it could be a problem if students were working with different representations, or unfamilar representations.  

So we will still keep 'usa' as the default, with the ability to override the default via `defaultRegionAndCulture` in package.json.

**Comment by pixelzoom** [comment]
I've done the work here, but will wait to have this reviewed until https://github.com/phetsims/joist/issues/954 is completed.

Note that this required regenerating all PhET-iO API files, because of the change from `multiculturalStringProperty` to `randomStringProperty`.

**Comment by pixelzoom** [comment]
@amanda-phet ready for review.

**Comment by amanda-phet** [comment]
I think this is a good change, and being able to override the default will be helpful in some sims.
