### ISSUE TITLE
Improve sorting of languages in the Localization tab of Preferences

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/joist#965]
Right now the sort on the Localization Tab is very odd. @jonathanolson is looking for a better way with the locale work.

**Comment by jonathanolson** [comment]
Before:
![image](https://github.com/phetsims/joist/assets/480878/8fcf6912-bc46-4592-8157-1fb72438ac06)
After:
![image](https://github.com/phetsims/joist/assets/480878/923dda45-2a3b-41fe-b772-22a118e9ea04)

**Comment by RVieyra** [comment]
Question, is this preferences dialogue set up in such a way that translators can translate the string for the name of their language? (I just note that many of the language names are not translated (e.g., Ahmharic, Armenian, Bengali, etc.). I'm guessing that that's just because translators haven't yet translated them, no?

**Comment by jonathanolson** [comment]
Not yet, but ideally that would be set up in the future. Whenever we have a request to change it, we will be able to change it without a MR.

**Comment by kathy-phet** [comment]
@solaolateju wrote

> @jonathanolson for the sort, It appears we are currently using the language code (for example, es/español is close to English ). I suggest we use the English string. Allow for more control and easier navigation for users.
> 
> For example,
> 
> Iranian Persian (fa/fas) and Afghanistan Persian (fa_DA/prs) would appear in different places using either the code or locale name (endonym). They are currently named Persian and Persian (Dari). They would help teachers/students/translator find all the options available to them. They probably would miss it if they are separated.

Sola - I see what you are saying here, but the sort will look very awkward overall, because the user doesn't have insight into the two letter codes. 

@jonathanolson - can you paste an example of what it will look like with this kind of sorting based on the two letter codes or english names.

**Comment by solaolateju** [comment]
@kathy-phet  I was also referring to and prefer sorting with the English name over the two or three letter codes. I believe most native speakers will know what their language is called in English. This way the list is sorted in English and displays the local names.
It would end up looking like what we have on the [translated sims page](https://phet.colorado.edu/en/simulations/translated)
but a different layout.
<img width="275" alt="image" src="https://github.com/phetsims/joist/assets/18397749/f92b7d13-5380-4663-9863-87bd3f0cc914">

I agree with your position on two-letter codes, users are not familiar with the two-letter codes and would find it confusing. If you consider we have custom two-letter codes as well, a lot more names will be out of place. This applies to three-letter codes.

**Comment by solaolateju** [comment]
I see what you mean now looking at `Albania/shqipe`. Let me think about other options.

**Comment by solaolateju** [comment]
I found 2 alternative in a quick search

- using to Latinized native names
or 
- sorting similar script together, with, for instance, Latin based scripts coming first, followed by other scripts (Cyrillic, Greek, Han, Hangul, and so on." This is similar to what Jonathan tried doing in the last shared sort.

![image](https://github.com/phetsims/joist/assets/18397749/18dd5e5e-9f76-42b3-868b-aa771796fabd)

- https://ux.stackexchange.com/questions/17064/how-do-you-sort-a-list-of-languages
- https://stackoverflow.com/questions/3637341/is-there-a-proper-order-for-listing-languages

**Comment by kathy-phet** [comment]
@solaolateju - 

> sorting similar script together, with, for instance, Latin based scripts coming first, followed by other scripts (Cyrillic, Greek, Han, Hangul, and so on." This is similar to what Jonathan tried doing in the last shared sort.

Yes, I believe @jonathanolson used a sorting standard to lead towards the current behavior. JO can you comment here on the resource used to set the sorting order. 

@solaolateju - Does this approach seem OK to you after talking through the options?
![image](https://github.com/phetsims/joist/assets/5096804/b455d372-1da7-4660-9a4d-2adf977fd0f0)

**Comment by jonathanolson** [comment]
We sort based on the browser's unicode-based sorting for English, which will also try to correctly sort text content from other locales. More specifically, it uses https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare.

**Comment by jonathanolson** [comment]
Current:

![image](https://github.com/phetsims/joist/assets/480878/b1ab9f9c-9900-4caa-8387-84a39f406776)

Sort by Locale code:

![image](https://github.com/phetsims/joist/assets/480878/4665a280-bca0-49a5-864d-3e9a8f04fabd)

Sort by English name:

![image](https://github.com/phetsims/joist/assets/480878/f084e783-e337-44d7-b8db-5606c0240da9)

I'm not sure about showing English names of languages. It seems VERY standard to show the translated language name, e.g. wikipedia:

![image](https://github.com/phetsims/joist/assets/480878/b3775030-ebac-43ae-9621-a20e08ea6f23)

**Comment by kathy-phet** [comment]
@solaolateju @RVieyra @DianaTavares - Can you comment on your opinions about above sorting options? We need to finalize this thread and move forward.

**Comment by RVieyra** [comment]
I vote for the "Current" solution. It is the easiest to understand visually.

Whatever is decided, I hope this ordering will be applied to the website translation drop-down as well as the simulation filter.

**Comment by DianaTavares** [comment]
I also like more the "current".

**Comment by kathy-phet** [comment]
@jonathanolson - I checked with @RVieyra and she said Global team discussed. They are all comfortable with proceeding with the "current solution", so please proceed, and close this when code review and qa testing is complete!

**Comment by solaolateju** [comment]
I'm OK with the current as well.

**Comment by jonathanolson** [comment]
Closing since this is deployed!
