### ISSUE TITLE
"PhET Homepage..." link should open in the same locale as the sim

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#97]
Rune said:

> It would be great if the link to the PhET web site from the localized HTML5 sims pointed to the corresponding language on the web site. We have a Norwegian bokmål translation of the web site up and running now, but I noticed that the link in the Norwegian Beer's Law prototype is pointing to the English web site.

**Comment by pixelzoom** [comment]
Since "Summer 2015 Redeploy" deals with translation, shouldn't this be addressed?

**Comment by pixelzoom** [comment]
@ariel-phet Is it OK to proceed with RC testing with this issue still open?

**Comment by ariel-phet** [comment]
@aaronsamuel137 @jonathanolson what would this take? Seems like good logic that if you open up a HTML5 translated sim (once we have it) that the link to the PhET site in the sim should go to the correct locale (if that locale exists for the website).

@pixelzoom fine to continue with the RC testing for the moment. Since we still need to beta test rosetta and flesh out bugs.

**Comment by pixelzoom** [comment]
The URL for the "PhET Website" menu item is currently:

`http://phet.colorado.edu`

To go to the translated website, the locale needs to be added to the URL, like this:

`http://phet.colorado.edu/ar_SA/`

**Comment by pixelzoom** [comment]
Change PhetMenu line 190 from this:

`var phetWindow = window.open( 'http://phet.colorado.edu', '_blank' );`

to this:

`var phetWindow = window.open( 'http://phet.colorado.edu/' + sim.locale, '_blank' );`

**Comment by pixelzoom** [comment]
I verified the above proposed fix in requirejs mode:

http://localhost/~cmalley/GitHub/acid-base-solutions/acid-base-solutions_en.html?brand=phet&locale=ar_SA

And in build mode:

% grunt --locales=ar_SA
http://localhost/~cmalley/GitHub/acid-base-solutions/build/acid-base-solutions_ar_SA.html

In both cases, the "PhET Website" menu item goes to http://phet.colorado.edu/ar_SA/.

@ariel-phet Do you want me to proceed with pushing this change?

**Comment by pixelzoom** [comment]
A few problems here:

(1) The website may not have been translated into the locale of the sim.  For example, for acid-base-solutions, there is an 'ar' translation for the sim, but no 'ar' translation of the website. So we get "The requested page could not be found".

(2) Consider the case where a sim has been translated into 'ar_SA', the website has not been been translated into 'ar_SA', but the website has been translated into 'ar'.  Should we direct to the less specific locale ('ar') on the website?

(3) The sim has no way to know what translations are available for the website. So any redirection (either to English or a less specific local) would need to be handled by the website.

**Comment by jonathanolson** [comment]
This won't work for translations that don't have a website translation, e.g. Lao (http://phet.colorado.edu/lo/). Please do not put that in common JS code.

If this is desired, it should request something that would be redirected on the server side.

**Comment by jonathanolson** [comment]
> Should we direct to the less specific locale ('ar') on the website?

I think that's probably the better option.

> So any redirection (either to English or a less specific local) would need to be handled by the website.

Yup.

**Comment by pixelzoom** [comment]
PhetMenu change described in https://github.com/phetsims/joist/issues/97#issuecomment-132735437 will be deferred until server side support is implemented.

**Comment by pixelzoom** [comment]
And it sure seems like this should be implemented before republishing translatable sims.

**Comment by ariel-phet** [comment]
Agreed seems like a high priority, but also seems relatively straightforward to implement...isn't that correct?

**Comment by pixelzoom** [comment]
No idea about the server side. @aaronsamuel137 or @jonathanolson will have to comment on what's involved there.

**Comment by jonathanolson** [comment]
It's probably very similar to previous redirections that have been done.

**Comment by pixelzoom** [comment]
Dev meeting consensus: 
• First try to fallback to a less-specific (language only) translation
• If that's not available, fallback to English.

**Comment by jbphet** [comment]
@pixelzoom will add code to joist, @jessegreenberg and @jonathanolson will roll new release candidates for Molecules and Light and Molecule Shapes (respectiviely), and @aaronsamuel137 will implement the redirect/fallback behavior described in previous comment.

**Comment by aaronsamuel137** [comment]
The redirect behavior already works. The only part that is not implemented is the fallback to a less specific locale. Closing this issue here and opening a website issue since the joist part is already done:

https://github.com/phetsims/website/issues/277
