### ISSUE TITLE
Chemical formulas in Dari rendering incorrectly (backwards?) in Build a Molecule

### ISSUE THREAD

**Issue by JacquiHayes** [phetsims/joist#973]
In the Build a Molecule simulations, the chemical formulas are shown incorrectly.

Here is an example from a similar language, Pashto, where they are shown correctly:
![Screenshot 2024-06-27 at 2 16 12 PM](https://github.com/phetsims/joist/assets/60244855/8e987352-2ee0-41a6-b05b-c80c53849fcb)

Here is a screenshot of how they are shown in Dari, which is incorrect:
![Screenshot 2024-06-27 at 2 13 46 PM](https://github.com/phetsims/joist/assets/60244855/ab77ae56-194b-478c-bf00-fb8ce32fdd00)

**Comment by zepumph** [comment]
Noting https://github.com/phetsims/build-a-molecule/issues/220

**Comment by jonathanolson** [comment]
Looks like this is working nicely in main. My patch in 2022 (https://github.com/phetsims/chipper/issues/1355) solves this issue. @kathy-phet should we MR this?

**Comment by kathy-phet** [comment]
Yes, please MR

——
Kathy Perkins Ph.D.
Director, PhET Interactive Simulations

(Sent from my iPhone)
________________________________

**Comment by jonathanolson** [comment]
QA test in https://github.com/phetsims/qa/issues/1113.

**Comment by jonathanolson** [comment]
Most of this work is handled. Any remaining work will be handled in https://github.com/phetsims/build-a-molecule/issues/220.
