### ISSUE TITLE
Active wrapper: animation jumps when toggling Active between true and false

### ISSUE THREAD

**Issue by Matthew-Moore240** [phetsims/joist#977]
<b>Test Device</b>

  Windows 11 Desktop 

  <b>Operating System</b>

  Windows 11 10.0.22635 build 22635

  <b>Browser</b>

  Firefox 127.0.0

  <b>Problem Description</b>

  During the active wrapper test, there seems to be some animation jumping when the sim is turned from inactive to active. 

  <b>Steps to Reproduce</b>

  1. Start the active wrapper 
  2. Release one or more particles
  3. Turn the sim from active to inactive back to active

  <b>Visuals</b>

  
One particle 
https://github.com/phetsims/gas-properties/assets/48224214/8a1707b4-7ac4-4142-94db-11d61a981ebf

Lots of particles
https://github.com/phetsims/gas-properties/assets/48224214/48d32ec3-6e26-449a-87e2-03dec8510f15

**Comment by zepumph** [comment]
Thanks for the report. This is a very nice thing to fix, though I don't think it needs an MR. As @samreid noted, it will only ever provide a jump of that Screen.maxDT value (likely half a second). All usages of the maxDT option provide a value smaller than 1/2 a second, so this seems fine in the wild, and is likely only a blip in cases like LOL and phet-io activeProperty toggling. 

Good to patch up on main though. 

@samreid and I committed this together, and feel good to close.
