### ISSUE TITLE
Create a ScreenSummaryContent class for ScreenView.screenSummaryContent

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#987]
For https://github.com/phetsims/models-of-the-hydrogen-atom/issues/67 ...

@kathy-phet requested a static screen summary for each of the screen in MOTHA.  @jessegreenberg pointed me to `ScreenViewOptions.screenSummaryContent` as the way to do this.  The documentation in ScreenView.ts says:

```ts
      // {Node|null} the Node with screen summary content to be added to the ScreenSummaryNode, and into PDOM above
      // the Play Area. This Node is added as a child to the ScreenSummaryNode.
      screenSummaryContent: null,
```

To test, I added this to SpectraScreenView:

```diff
  public constructor( model: SpectraModel, tandem: Tandem ) {

    super( {

      // ScreenViewOptions
      isDisposable: false,
      tandem: tandem,
+     screenSummaryContent: new Text( 'This is the Spectra screen summary.', {
+       font: new PhetFont( 24 )
+     } )
    } );
```

But I do not see anything related to this appearing in A11y View.   Am I doing something wrong? Or is A11y View not aware of `screenSummaryContent`?

**Comment by pixelzoom** [comment]
Looking at FaradaysLawScreenView, I discovered that `screenSummaryContent` is not just any Node.  It has to specifically be a Node, and with low-level HTML options.  

```ts
      screenSummaryContent: new Node( {
        tagName: 'p',
        innerContent: 'This is the screen summary for the Spectra screen.'
      } )
```

And then it shows up in A11y View like this:

<img width="435" alt="screenshot_3549" src="https://github.com/user-attachments/assets/82ab3128-6453-49e4-9b20-47983df658c0">

It seems like a better API would. be something like:

`screenSummaryContent: ScreenSummaryContent`

where ScreenSummaryContent handles the low-level details internally, instead of duplicating those details at the sim level. For example:

```
class ScreenSummaryContent extends Node {
  public constructor( summaryStringProperty: TReadOnlyProperty<string> ) {
    super( {
      tagName: 'p',
      innerContent: summaryStringProperty
    } );
  }
}
```

**Comment by jessegreenberg** [comment]
This is because `Text` has no accessible content. Something like this should work:

```js
    const contentString = 'This is a screen view for the Spectra screen.';

    super( {

      // ScreenViewOptions
      isDisposable: false,
      tandem: tandem,

      screenSummaryContent: new phet.scenery.Text( contentString, {
        tagName: 'p',
        accessibleName: contentString
      } )
    } );
```

**Comment by jessegreenberg** [comment]
> It seems like a better API would be something like:

That sounds good, lets do it. ScreenSummaryContent will be a good superclass, and can be extended for the more custom content (like GravityForceLabScreenSummaryNode)

**Comment by pixelzoom** [comment]
Sounds good.  I pushed to MOTHA, but added 2 TODOs that look like this:

```ts
//TODO https://github.com/phetsims/joist/issues/987 change this to ScreenSummaryContent
```

**Comment by jessegreenberg** [comment]
In https://github.com/phetsims/models-of-the-hydrogen-atom/issues/72 we need more than one element for the summary so our class should support that in a simple way.

**Comment by jessegreenberg** [comment]
I created `ScreenSummaryContent` and used it everywhere. @pixelzoom can you please review and take a look at how I used it in MOTHA? Here is the main commit: https://github.com/phetsims/joist/commit/2dca61efb7a4f26e5ef58870f5b5f3060a8988c8.

**Comment by pixelzoom** [comment]
This is a nice improvement, and I reviewed a subclass example in GFLScreenSummaryNode.  Closing.
