### ISSUE TITLE
Screen `descriptionContent` should use `helpText` for consistency

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/joist#989]
This option is used to set the help text of the home screen button for a particular screen

```ts
      // pdom/voicing - The description that is used when interacting with screen icons/buttons in joist (and home screen).
      // This is often a full but short sentence with a period at the end of it. This is also used for voicing this screen
      // in the home screen.
      descriptionContent: null,
```

We should change it to use `helpText` to for better consistency as we move toward using "accessible name" and "help text" throughout code components.

Came up while reviewing https://github.com/phetsims/models-of-the-hydrogen-atom/issues/67 with @kathy-phet and @terracoda.

**Comment by jessegreenberg** [comment]
In https://github.com/phetsims/models-of-the-hydrogen-atom/issues/73#issuecomment-2457757091 @pixelzoom recommended
```diff
- descriptionContent?: PDOMValueType | null;
+ // Help text that will be added to the Home screen button and navigation bar button for this screen.
+ screenButtonsHelpText?: PDOMValueType | null;
```

**Comment by pixelzoom** [comment]
@jessegreenberg When the API is changed, feel free to update MOTHA.  I added 2 TODOs that link to this issue.

**Comment by jessegreenberg** [comment]
OK, this is done. I updated usages, including the two in MOTHA and removed the TODOs. I also updated string keys under the `a11y` key based on a comment about how they were confusing before in https://github.com/phetsims/models-of-the-hydrogen-atom/issues/73#issuecomment-2457757091.

Here is the main joist commit: https://github.com/phetsims/joist/commit/e3366b88904079fee05627225a3afeacdce967dc with some cleanup in https://github.com/phetsims/joist/commit/07dea6da77eb788b6ad4e2a3a68815e08a867a62.

@pixelzoom would you mind reviewing this?

**Comment by pixelzoom** [comment]
Commits look good.

Should the default helpText match the default for the Home Screen button? That is `"Go to {{screenName}} Screen"` rather than just `"{{screenName}} Screen"`.   See screenshot below.

<img width="351" alt="screenshot_3578" src="https://github.com/user-attachments/assets/8f6b10bf-a980-426c-b7a3-f56702393206">

**Comment by jessegreenberg** [comment]
Yes, and that is a better default. Anything else for this?

**Comment by pixelzoom** [comment]
Looking good!

```json
    "home": {
      "value": "Home"
    },
...
    "homeScreenDescription": {
      "value": "Go to Home Screen."
    },
...
    "goToScreenPattern": {
      "value": "Go to {{name}} Screen."
    },
```

Should `homeScreenDescription` be replaced with `goToScreenPattern`?  This would ensure consistency going forward.

**Comment by terracoda** [comment]
@pixelzoom and @jessegreenberg, I also like "Go to" as a default, and hopefully folks will design screen button help text that's more directly relevant. Great default, though!

**Comment by jessegreenberg** [comment]
Thanks @terracoda, sounds good.

Good point @pixelzoom, done in the above commit. Can you please review?

**Comment by pixelzoom** [comment]
Looks good, but I'm not sure if it's safe to totally remove a string from joist-strings_en.json. @jessegreenberg please verify with @jbphet.

**Comment by jessegreenberg** [comment]
Thanks for reviewing. It is safe to remove strings under the `a11y` key, I confirmed this with @jbphet for another issue a few weeks ago.

Closing.
