### ISSUE TITLE
Navbar does not align with bottom + right sides of window (IE10/Win8)

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#99]
This is a general issue with joist, first reported in https://github.com/phetsims/ph-scale-basics/issues/32, see that ticket for details.

**Comment by pixelzoom** [comment]
Not a problem in IE11.  I don't have an IE10 test machine, can someone test whether this is still an issue?

**Comment by jonathanolson** [comment]
Definitely looks like it should be fixed soon. I'll look into it, either with an IE10 VM or in person on Tuesday.

**Comment by jonathanolson** [comment]
Could not reproduce on IE10 VM with either 1.0.0-rc.1, 1.1.0-rc.1 or the live production version:
![joist-gap](https://cloud.githubusercontent.com/assets/480878/7782496/35e858ce-00d8-11e5-96be-f70a28b4295f.png)

Will look into reproducing on Socrates (actual device) on Tuesday?

**Comment by jonathanolson** [comment]
Actual device has updated to IE11, didn't present issue. Tried another attempt with IE10 elsewhere and could not reproduce.

Will reopen if this is encountered.
